### ISSUE TITLE
Index template metrics-apm.app missing the default_pipeline setting in 8.6.0 

### ISSUE THREAD

**Issue by hubbleview** [elastic/apm-server#10055]
**Describe the bug**
Prior to 8.6.0, the out-of-the-box index template `metrics-apm.app` has `index.default_pipeline` setting as below:
```
    "name": "metrics-apm.app",
      "index_template": {
        "index_patterns": [
          "metrics-apm.app.*-*"
        ],
        "template": {
          "settings": {
            "index": {
              "default_pipeline": "metrics-apm.app-<version>"
            }
          },
        <truncated>
```

After upgrading to 8.6.0, this `index.default_pipeline` setting doesn't exist, which resulted in the events not going through the pipeline that they are supposed to do. Below is the default index template in 8.6.0:
```
      "name": "metrics-apm.app",
      "index_template": {
        "index_patterns": [
          "metrics-apm.app.*-*"
        ],
        "template": {
          "settings": {},
          "mappings": {
         <truncated>
```

I didn't find [breaking changes](https://www.elastic.co/guide/en/apm/guide/current/release-notes-8.6.html) in 8.6, thinking this setting is still needed.

**To Reproduce**
1. Install 8.5.x stack with APM.
2. `GET _index_template/metrics-apm.app`
3. Upgrade to 8.6.0.
4. `GET _index_template/metrics-apm.app`

**Expected behavior**
Index template `metrics-apm.app` still has `index.default_pipeline` configured.

**Comment by simitt** [comment]
Thanks for reporting @hubbleview . We are looking into this and will update the issue accordingly with our findings.

**Comment by lahsivjar** [comment]
@hubbleview I can see the `default_pipeline` if I were to view the ingest template directly from the Stack Management UI however, the same is not shown in the `GET _index_template/metrics-apm.app` call from the dev tools. I also checked the ingestion flow; the pipeline is applied but not visible in the dev tools call which leads me to belive that this might be an APM-independent issue.

> After upgrading to 8.6.0, this index.default_pipeline setting doesn't exist, which resulted in the events not going through the pipeline that they are supposed to do.

Can you share more details on what issue you are facing in the ingestion flow?

**Comment by glucaci** [comment]
We have @custom pipelines and after upgrade they were not processed anymore and lead to this issue.

After added the `default_pipeline` in the template everything worked well.

**Comment by lahsivjar** [comment]
@glucaci Thanks for the additional details. I am not successful in reproducing the error with the custom pipeline so far, I have created a custom pipeline in 8.5 and upgraded it to 8.6 with the pipeline working.

If you have an existing deployment showing the above error will you be able to check if the `default_pipeline` is present in ```Stack Management -> Index Management -> Index Templates -> Search for `metrics-apm.app` -> Preview```

**Comment by glucaci** [comment]
No the pipeline is not there.

I suspect that the reinstalling of the APM Integration broke it because I have put it there manually and I triggered the reinstalling of the APM integration (because of another problem) and is not there anymore. 

So something is overwriting the template which cause that the `default_pipeline` gets deleted.

**Comment by glucaci** [comment]
@lahsivjar Yes it's an Elastic Cloud cluster and this issue was opened from a support ticket.

**Comment by hubbleview** [comment]
I just realized the `default_pipeline` is set in the component template in 8.6 onwards. There must be something else which resulted in https://github.com/elastic/apm-server/issues/10055#issuecomment-1385491423. We will investigate further. 

Sorry for the confusion my initial issue description has caused.

**Comment by hubbleview** [comment]
Closing this issue, this is my misunderstanding, not a bug. Sorry about that.

**Comment by glucaci** [comment]
@hubbleview @lahsivjar I think this is still a bug.
I just found out that the order of the components in the template is wrong and is getting the wrong `default_pipeline`.

Example on the logs index the components are like these
![image](https://user-images.githubusercontent.com/13761704/213708685-2e280b54-db50-46f1-9c72-c231de8fbf90.png)

and the resulting `default_pipeline` in the preview is `.fleet_cleanup_pipeline` which means that the last components gets applied which is `.fleet_agent_id_verification-1`

If i move the components like this:
![image](https://user-images.githubusercontent.com/13761704/213709786-5aa75a0d-8851-4a63-aa57-a35d84337cf8.png)

the resulting `default_pipeline` is the right one `logs-apm.app-8.6.0`

**Comment by glucaci** [comment]
It seams that everything stays in place, only the `default_pipeline` gets changes by moving the `package` component at the end.

This is the comparation from the metrics index
![image](https://user-images.githubusercontent.com/13761704/213712846-0442e41f-ade9-416f-adaa-b12e17e95a68.png)
