### ISSUE TITLE
Documentation copied from beats

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1011]
There are some inconveniences with how we document functionality provided by beats:

- We can't have (or is very hard to have) consistent heading: eg https://github.com/elastic/apm-server/blob/master/docs/installing.asciidoc and https://github.com/elastic/apm-server/blob/master/docs/configuring.asciidoc should be at the same level.

- We have to fetch updated docs from beats regularly to not fall out of sync and review the changes manually.

- When those changes don't make sense, we have to amend them (we have to do it every time we update unless we make conditionals for the apm-server in the beats repo)

- Some functionality tested from beats we have it documented in our own docs (eg. the secret keystore) and other things are not mentioned at all (eg. kafka output)

Right now apm-server docs feel both verbose _and_ incomplete. Can we improve this? eg. document only the `apm-server` config namespace and refer/link to beats docs for other relevant options.

**Comment by bmorelli25** [comment]
@jalvz If it's alright with you, I'll close this issue.

---

> We can't have (or is very hard to have) consistent heading: eg https://github.com/elastic/apm-server/blob/master/docs/installing.asciidoc and https://github.com/elastic/apm-server/blob/master/docs/configuring.asciidoc should be at the same level.

The Asciidoctor migration in #1965 fixed this 🎉 

> We have to fetch updated docs from beats regularly to not fall out of sync and review the changes manually.

> When those changes don't make sense, we have to amend them (we have to do it every time we update unless we make conditionals for the apm-server in the beats repo)

I've taken this one off of your plate 😄

> Some functionality tested from beats we have it documented in our own docs (eg. the secret keystore) and other things are not mentioned at all (eg. kafka output)

These inconsistencies should be fixed now. We can conditionally in/exclude anything should or shouldn't be in our documentation.

In addition, the documentation redesign plan should be drastically improving our docs soon 🤞

**Comment by jalvz** [comment]
Fantastic, thanks!
