### ISSUE TITLE
Dynamic namespace in APM Integration

### ISSUE THREAD

**Issue by Freddyua** [elastic/apm-server#10126]
Hello,

On standalone APM server we could define the name of our indexes using the elasticsearch.output, and we could use variables so a single server could create apm indexes for multiple use cases or namespaces if needed.

Switching to Elastic Agents with Fleet, apm integration does not seem to offer this possibility. It seems one can only use one namespace per apm integration, so we would need multiple servers in order to handle many namespaces. Is there a way dynamic namespaces could be implemented on the APM integration? Is there a workaround to achieve this kind of functionality?

Thanks!

**Comment by b2ronn** [comment]
I'm also interested in this question. 
For now, as a workaround, we are using pipelines to modify the namespace based on global labels.

**Comment by federicobarera** [comment]
Seems related to this: https://github.com/elastic/apm-server/issues/10191

**Comment by axw** [comment]
Thanks @federicobarera, this issue escaped my attention. This will be possible in 8.10 by using the `reroute` ingest processor as mentioned in https://github.com/elastic/apm-server/issues/10991. I'll close this issue - please keep an eye out for 8.10.0 and let us know if you have issues.

#10191 tracks additional mechanisms for routing on attributes supplied by agents/OTel SDKs.
