### ISSUE TITLE
APM server tuning for heavy workload

### ISSUE THREAD

**Issue by SenthilkumarRasan** [elastic/apm-server#10149]
After deploying elastic cluster for tracing, we see following errors due to heavy workload in APM server/Agents

co.elastic.apm.agent.report.ApmServerReporter - dropped events because of full queue: 305

[elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Error sending data to APM server: Read timed out, response code is -1

Could you provide info on how to monitor APM server/java agent queue and ways to tune to resolve above errors? we are in 8.4 version and planning to upgrade to 8.61

**Comment by axw** [comment]
Please open a topic for discussion at https://discuss.elastic.co/c/observability/apm/58. We reserve GitHub Issues for known issues and enhancement requests. Thanks!
