### ISSUE TITLE
Remove outdated config options from apm-server.yaml

### ISSUE THREAD

**Issue by ebuildy** [elastic/apm-server#10150]
**APM Server version** (`apm-server version`): 8

**Description of the problem including expected versus actual behavior**:

https://github.com/elastic/apm-server/blob/main/apm-server.yml#L368 seems outdated, as `bulk_max_size` setting has been removed since v8, right?

Ref https://github.com/elastic/apm-server/pull/6940 

And replaced by

```
	FlushBytes    string        `json:"flush_bytes,omitempty"`
	FlushInterval time.Duration `json:"flush_interval,omitempty"`
```

**Steps to reproduce**:

Copy config template from apm-server.yaml to configure elasticsearch output

**Provide logs (if relevant)**:

**Comment by axw** [comment]
Yes, thanks for opening the issue @ebuildy.

**Comment by ebuildy** [comment]
Ho, I have checked with some devops friends on 3 very busy web app, they all have kept `bulk_max_size` setting ;-)

Thanks you very much for the info

**Comment by ebuildy** [comment]
Absolutely! 

Just curious, where is the code that do the output?

(I was reading https://github.com/elastic/beats/blob/main/libbeat/outputs/elasticsearch/config.go#L41 but see `bulk_max_size` setting ...)

Many thanks

**Comment by axw** [comment]
APM Server does use the configuration code from libbeat that you're referencing, mostly for convenience, but we ignore some of the properties (such as `bulk_max_size`). The code was recently moved to its own repo: https://github.com/elastic/go-docappender

**Comment by simitt** [comment]
Updated the title to reflect that we need to review the `apm-server.yml` and remove any outdated config options. This should be backported to be shipped with `8.7`.

**Comment by simitt** [comment]
Config options to remove:

- `queue.*`
- `max_procs`
- `output.elasticsearch.parameters`, `output.elasticsearch.worker`, `output.elasticsearch.bulk_max_size`, `output.elasticsearch.kerberos`
- `monitoring.elasticsearch.parameters`, `monitoring.elasticsearch.bulk_max_size`, `monitoring.elasticsearch.kerberos`

Test if following options still work:
- `cloud.id`, `cloud.auth`

**Comment by kyungeunni** [comment]
@simitt I was looking at [this](https://github.com/elastic/apm-server/pull/6940) and noticed we don't have the following configs in `apm-server.yml`:
- `output.elasticsearch.flush_bytes`
- `output.elasticsearch.flush_interval`

Should we add them as well while we are making the config file up-to-date?

**Comment by simitt** [comment]
@kyungeunni good find - yes since they are officially documented, let's also add them to the `apm-server.yml`.

**Comment by kruskall** [comment]
> Config options to remove:
> 
>     max_procs

@simitt I missed this, is there a reason why this is being removed ? The option is being used here: https://github.com/elastic/apm-server/blob/d09d4a27a3e19afb19884e618da8c04db8c82d4d/internal/beatcmd/beat.go#L155-L158

Can be reproduced with  `-e -E max_procs=10`

**Comment by simitt** [comment]
Good catch @kruskall, that one is still needed.
