### ISSUE TITLE
Testing APM server with the new dynamic ECS template

### ISSUE THREAD

**Issue by P1llus** [elastic/apm-server#10155]
Currently we are in the progress of running local tests on integrations and services on the stack with our new ECS dynamic template functionality added to elastic-package, ref: https://github.com/elastic/integrations/issues/5055

While the current process might be a bit different for APM server as the package is hosted elsewhere, we are looking into the possibility of running some local tests using this functionality as well, to see if there might be any bugs left.

The request at this point is not to include it in the APM package itself, as the template is still in testing phase, but we want to see if we might be able to run any local tests with it at this point.

**Comment by axw** [comment]
@P1llus looking at the linked issue, I think we'll need to do the following:

 - Update the version of elastic-package in https://github.com/elastic/apm-server/blob/f17d17fc4ee6772e4b278abd7e3c418379510cf8/tools/go.mod#L6
 - Update https://github.com/elastic/apm-server/blob/f17d17fc4ee6772e4b278abd7e3c418379510cf8/Makefile#L21 to `git@8.6` and add `import_mappings: true` to https://github.com/elastic/apm-server/blob/main/apmpackage/apm/_dev/build/build.yml
 - Remove `apmpackage/**/ecs.yml` files
 - Update https://github.com/elastic/apm-server/blob/f17d17fc4ee6772e4b278abd7e3c418379510cf8/apmpackage/apm/manifest.yml#L1

Then you can run `make build-package` to generate and build the package.

**Comment by P1llus** [comment]
@axw do you have any system tests that I can run at first maybe? Similar to how we perform testing for common integration packages?

Thanks a lot for the clear steps needed!

If I do not have any automated tests I can run, how would you usually approach getting the custom binary loaded by elastic agent?

**Comment by axw** [comment]
> @axw do you have any system tests that I can run at first maybe? Similar to how we perform testing for common integration packages?

Many! There are system tests under the `systemtest/` directory.

Best to run `docker-compose up -d` first, and then `cd systemtest && go test -v -run TestIntake` should be a good start. If you want to run all the tests in that directory, you may need to increase the test timeout. That particular test does not run APM Server under Elastic Agent, but it will still load the integration package and use the same data streams / index templates.

**Comment by P1llus** [comment]
Finished my testing, thought I would add the results here for reference:

Of course this was not meant to simulate an actual APM setup at this point, so I tok the liberty to modify some of the template settings to make my own tests provide output.

1. When adding my changes which was noted above here: I ran into a small issue because the ILM policies are not named correctly according to package-spec v2+:
```
   7. file "/home/marius/go/src/github.com/elastic/apm-server/build/packages/apm-8.7.0.zip/data_stream/service_transaction_10m_metrics/manifest.yml" is invalid: field ilm_policy must start with "metrics-apm.service_transaction_10m_metrics-", found "metrics-apm.service_transaction_interval_metrics-default_policy.10m"
   8. file "/home/marius/go/src/github.com/elastic/apm-server/build/packages/apm-8.7.0.zip/data_stream/service_transaction_1m_metrics/manifest.yml" is invalid: field ilm_policy must start with "metrics-apm.service_transaction_1m_metrics-", found "metrics-apm.service_transaction_interval_metrics-default_policy.1m"
 ........
```
This happens for all the datastreams using the `interval` replacement scheme. Added a small hack here to set the correct name: https://github.com/elastic/apm-server/blob/main/apmpackage/cmd/genpackage/transform.go#L129

Once the builds was running fine I noticed that the tests started failing.

I started by removing the `synthetic source` configuration and setting all packages `dynamic` setting to true (instead of strict and false). Then all tests ended up a success.


2. I then ran the complete system test scenario, all are successful, however there was certain tests that failed because `ecs.version` was set to nil, a bit unsure why but I believe it had something to do with how the tests are set up.

3. I added the synthetic source back, and all tests are still passing just fine.


In the end, while some changes was applied to make the tests pass for now, the testing for the dynamic ECS template seems to have been working quite well, I believe there was 1-2 differences in mappings in total for all the test suites, something I will be going back and see if we can accommodate on the dynamic template itself.


Thanks for all the help with setting this up 👍

**Comment by P1llus** [comment]
The above was simply for testing purposes, as there was no current plan to implement this for APM unless there is a wish for it. So if there is no questions I will close the issue a bit later!

**Comment by simitt** [comment]
Thank you for doing the analysis @P1llus . What would be your suggestion to move forward with this, to integrate with the dynamic ECS template?

**Comment by P1llus** [comment]
Hello @simitt . Great to see the interest in the feature, we are trying to get all stack solutions on board, so this would be great!

I don't believe there is much work left, mainly 3 tasks:

1. Resolve the minor issues with the system tests when using dynamic templates, from what I could see it only complained that the ecs.version field was nil, but only from a handful of tests.
There was also some failure with one of the Jaeger tests.

2. The current usage of setting dynamic: false and dynamic: strict at root level won't work with dynamic templates like this, because we do not map keyword fields (as they default to keyword). 
This is something we could handle with a quick meeting I believe.

3. More manual testing! I believe the apm team has better processes and infrastructure around setting this up quickly, but we could maybe collaborate?
It would be good to test for example what would happen when upgrading for the first time.

Lets do a quick catchup meeting to go through it then I am sure we can get it over the finish line!

**Comment by axw** [comment]
No longer relevant. Since this issue was opened, we have introduced and are now exclusively using APM-specific templates shipped with Elasticsearch: https://github.com/elastic/elasticsearch/tree/main/x-pack/plugin/apm-data/src/main/resources. This includes using the common "ecs@mappings" component template.
