### ISSUE TITLE
Visualizations broken

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1017]
Kibana version: master
Elasticsearch version: master
APM Server version: master

per elastic/kibana#19967, apm dashboard visualizations are loaded but not working properly.

**Comment by graphaelli** [comment]
Broken when updating beats containing elastic/beats#7265 without updating visualizations.

**Comment by ruflin** [comment]
@graphaelli Really sorry about this, should have pinged the team on this change.

**Comment by graphaelli** [comment]
@ruflin no problem at all - we caught part of the changes in #1001 but missed this bit - of course a heads up would be great in the future.  I'm more concerned about missing coverage for this in integration tests

**Comment by ruflin** [comment]
I wanted to ping the apm-server team when I was writing the code but forgot when I opened the PR. Will try to do better.

For the testing: If you find a nice way to test this, we also need this :-)
