### ISSUE TITLE
Dashboards doesn't render long error messages correctly

### ISSUE THREAD

**Issue by watson** [elastic/apm-server#1021]
According to https://github.com/elastic/apm-agent-nodejs/issues/390#issuecomment-395454344 the dashboards can't handle long error messages very well.

The APM UI should correctly truncate them in the UI, but it seems like the dashboards doesn't perform any truncation.

**Comment by simitt** [comment]
![Screen Shot 2018-07-05 at 16.47.43.png](https://zube.io/files/elastic/edc12ced9db16775e0618c73b70611f0-screen-shot-2018-07-05-at-16-47-43.png)

**Comment by simitt** [comment]
At the moment there is no way of truncating the data when querying from the table view for the dashboards. This means that the dashboards rely on the agents cutting the message to some sensible default.

**Comment by MartinKolarik** [comment]
Not sure what the performance impact would be but it should be possible to create a scripted field for that?

**Comment by simitt** [comment]
Closing this issue as it cannot be fixed on the APM Server dashboards at the moment. 

The [APM UI](https://www.elastic.co/guide/en/kibana/current/xpack-apm.html), part of X-Pack basic license, handles showing the messages properly.
