### ISSUE TITLE
Data not being ingested in elasticsearch after being received by APM server - complaining about APM Integration Version Mismatch

### ISSUE THREAD

**Issue by maretodoric** [elastic/apm-server#10283]
**APM Server version** (`apm-server version`): 8.6.1

**Description of the problem including expected versus actual behavior**: After upgrade from 8.5.3 to 8.6.1 (APM server is part of fleet, specifically in fleet server policy), one specific agent (that sends data to this specific policy) fails to deliver data.
Looking in nginx logs (which is in front of APM Servers) i see data incoming. When looking at agent logs, i see error message complaining about mismatched APM Integration version,  however APM integration is same version as APM Server (log displayed below)

**Steps to reproduce**: Upgrade APM Server that belongs to fleet server policy.

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Upgrade from 8.5.3 to 8.6.1
 2. No data visible in APM

**Provide logs (if relevant)**:
Nginx logs showing data is received
```
xx.xx.xx.xx - - [16/Feb/2023:00:16:20 +0100] "POST /config/v1/agents HTTP/1.1" 304 0 "-" "apm-agent-java/1.36.0 (service-name)"
xx.xx.xx.xx - - [16/Feb/2023:00:16:28 +0100] "POST /intake/v2/events HTTP/1.1" 202 0 "-" "apm-agent-java/1.36.0 (service-name)"
xx.xx.xx.xx - - [16/Feb/2023:00:16:41 +0100] "POST /intake/v2/events HTTP/1.1" 202 0 "-" "apm-agent-java/1.36.0 (service-name)"
xx.xx.xx.xx - - [16/Feb/2023:00:16:50 +0100] "POST /config/v1/agents HTTP/1.1" 304 0 "-" "apm-agent-java/1.36.0 (service-name)"
xx.xx.xx.xx - - [16/Feb/2023:00:16:52 +0100] "POST /intake/v2/events HTTP/1.1" 202 0 "-" "apm-agent-java/1.36.0 (service-name)"
xx.xx.xx.xx - - [16/Feb/2023:00:17:02 +0100] "POST /intake/v2/events HTTP/1.1" 202 0 "-" "apm-agent-java/1.36.0 (service-name)"
```

Agent logs showin data is received after proxied by nginx
```
{"log.level":"info","@timestamp":"2023-02-15T23:16:28.711Z","message":"request accepted","component":{"binary":"apm-server","dataset":"elastic_agent.apm_server","id":"apm-default","type":"apm"},"log":{"source":"apm-default"},"ecs.version":"1.6.0","log.origin":{"file.line":61,"file.name":"middleware/log_middleware.go"},"url.original":"/intake/v2/events","source.address":"xx.xx.xx.xx","http.request.id":"50d42347-fb2e-4c5f-8710-5586a4db205b","http.request.method":"POST","event.duration":33198072,"log.logger":"request","service.name":"apm-server","user_agent.original":"apm-agent-java/1.36.0 (service-name)","http.response.status_code":202,"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T23:16:52.105Z","message":"request accepted","component":{"binary":"apm-server","dataset":"elastic_agent.apm_server","id":"apm-default","type":"apm"},"log":{"source":"apm-default"},"url.original":"/intake/v2/events","user_agent.original":"apm-agent-java/1.36.0 (service-name)","log.origin":{"file.line":61,"file.name":"middleware/log_middleware.go"},"http.request.method":"POST","http.request.id":"7c67c7ea-4295-41d4-9601-3d6c8199a898","event.duration":18733716,"ecs.version":"1.6.0","http.response.status_code":202,"log.logger":"request","service.name":"apm-server","source.address":"xx.xx.xx.xx","ecs.version":"1.6.0"}
```

Agent logs complaining about failing to index event due to APM Integration version mismatch with APM Server:
```
{"log.level":"error","@timestamp":"2023-02-16T22:31:43.492Z","message":"failed to index event (fail_processor_exception): Document produced by APM Server v8.6.1, which is newer than the installed APM integration (v8.5.0-preview-1663692203). The APM integration must be upgraded.","component":{"binary":"apm-server","dataset":"elastic_agent.apm_server","id":"apm-default","type":"apm"},"log":{"source":"apm-default"},"service.name":"apm-server","ecs.version":"1.6.0","log.logger":"modelindexer","log.origin":{"file.line":448,"file.name":"modelindexer/indexer.go"},"ecs.version":"1.6.0"}
```
Same but pretty printed
```
[elastic_agent.apm_server][error] failed to index event (fail_processor_exception): fail_processor_exception: Document produced by APM Server v8.6.1, which is newer than the installed APM integration (v8.5.0-preview-1663692203). The APM integration must be upgraded.
```

Screenshot showing APM Integration Version:
![image](https://user-images.githubusercontent.com/42638763/219503005-f6b2c15b-285e-45b1-b48e-b0e86bdebe3f.png)

Screenshot showing 3 servers that belong to fleet server policy that has APM server which does not index data
![image](https://user-images.githubusercontent.com/42638763/219503160-7f21ecfc-4585-4429-845b-166828e33537.png)

Again, showing APM Server version withing fleet server policy
![image](https://user-images.githubusercontent.com/42638763/219503223-34d0c3a8-5833-49fa-a9c2-96981dd1462f.png)

For purpose of troubleshooting I've restarted elastic-agent on all three hosts belonging to fleet server policy, and kibana servers on all three hosts, issue persists.

There is only ONE agent that sends data to these 3 hosts/APM servers.

**Comment by maretodoric** [comment]
Temporary fix: Reinstall APM Integration.
However it's only temporary for next 24 hours. After that issue happens again, then i have to reinstall APM Integration again. And it's not even full 24 hours after reinstallation. It seems to regress sometime between 15:00 - 17:00 which was around the same time i upgraded all agents after upgrading elasticsearch cluster. I can see that by looking at data stream and checking 'Last updated'.
It's like this for few days now.

Anyone has any idea how to troubleshoot this further?

**Comment by simitt** [comment]
@elastic/fleet do you have an idea what could be happening here? The version for the installed apm package `v8.5.0-preview-1663692203` caught my eye.

**Comment by juliaElastic** [comment]
We had a similar issue recently where some indices were still using an old ingest pipeline.
Can we get the results of this API call? This helps identify which indices are referring outdated version of apm pipelines: 
`GET *-apm.*/_settings?filter_path=*.settings.index.default_pipeline`

**Comment by maretodoric** [comment]
Well, if that was the case, it would explain why it's working now as i have very low retention period for this specific namespace (5 days) and so those indices would be deleted now.

Otherwise, what might've fixed it is that I've completely removed APM Server integration from all agent policies, then uninstalled/installed APM Server from scratch - added it back to agent policies.

Anyway, here is requested output.

```
{
  ".ds-metrics-apm.internal-apm_central-2023.02.18-000107": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-apm_central-2023.02.19-000109": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-default-2023.01.23-000016": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-apm_central-2023.02.18-000105": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.02.18-000019": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.1"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.02.17-000018": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.1"
      }
    }
  },
  ".ds-metrics-apm.internal-apm_central-2023.02.17-000103": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.02.16-000017": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.1"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.02.15-000015": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.1"
      }
    }
  },
  ".ds-metrics-apm.internal-apm_central-2023.02.16-000101": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.02.15-000016": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.1"
      }
    }
  },
  ".ds-logs-apm.error-apm_central-2023.02.16-000101": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-apm_central-2023.02.17-000103": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-apm_central-2023.02.18-000105": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-apm_central-2023.02.18-000107": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-apm_central-2023.02.19-000109": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2022.10.31-000008": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.4.2"
      }
    }
  },
  ".ds-logs-apm.error-default-2023.02.15-000018": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-default-2023.02.15-000019": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-default-2023.02.18-000022": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-default-2023.02.19-000023": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-logs-apm.error-default-2023.02.17-000021": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.01.23-000013": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.5.2"
      }
    }
  },
  ".ds-logs-apm.error-default-2023.02.16-000020": {
    "settings": {
      "index": {
        "default_pipeline": "logs-apm.error-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.02.18-000021": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2022.11.24-000009": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.5.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.02.19-000022": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.2"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2023.02.18-000020": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.6.1"
      }
    }
  },
  ".ds-metrics-apm.internal-default-2022.12.24-000011": {
    "settings": {
      "index": {
        "default_pipeline": "metrics-apm.internal-8.5.2"
      }
    }
  }
}
```

**Comment by juliaElastic** [comment]
@maretodoric So you don't see the version mismatch error anymore? 
I see different versions of pipeline referenced in the response though.

**Comment by joshdover** [comment]
> I see different versions of pipeline referenced in the response though.

Don't we only update the write indices, not all of the old backing indices. In that case, I'd expect to see a mismatch

**Comment by maretodoric** [comment]
I honestly don't see version mismatch anymore.. Not sure what fixed it, but it was like this for few days.
However, after complete removal and reinstallation, i noticed apm server from fleet server policy is writing to default namespace (i forgot to change the namespace).
I've changed it now and will wait 24 hours to see if it's by any chance tied to namespace for whatever reason. Usually after 24 hours issue appears.

But i have 11 other agents all working properly even before (default namespace). Just these 3 under fleet server policy were acting up.

**Comment by simitt** [comment]
@maretodoric have you encountered this issue to come back? Otherwise I suggest we close this and reopen in case this comes up again.

**Comment by maretodoric** [comment]
Yeah, unfortunately u haven't faced the issue again. Too bad as i was
really keen in figuring out what happened.

Feel free to close this and I'll reach back out if it happens again.
Probably after next upgrade.

**Comment by maretodoric** [comment]
This:
https://discuss.elastic.co/t/document-produced-by-apm-server-v8-7-1-which-is-newer-than-the-installed-apm-integration-v8-2-0/334568
