### ISSUE TITLE
Benchmarks: throughput regression in 8.7

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#10295]
There has been a significant reduction in throughput in the daily benchmarks:

![image](https://user-images.githubusercontent.com/843579/220018080-a25ae1e6-e7ed-4a34-b804-f3cc4ee4fb14.png)

**Comment by kruskall** [comment]
Looking at the diff from the commit mentioned in the dashboard: https://github.com/elastic/apm-server/compare/8067611c012fe691c1e8922b641b9a55292cbd11...1716f4c7b302e2da3564ccce3c262e9603dd3542

**Comment by axw** [comment]
Indeed, benchmarks are reasonably happy now.
