### ISSUE TITLE
Build current branch in APM macro Benchmarks

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#10315]
## Description

The APM macro Benchmarks currently use the last committed Elastic Agent docker image for the APM Server's daily benchmarks https://github.com/elastic/apm-server/blob/52b02b7323b0026b08f279c680c59a5a2ba35bfe/docker-compose.yml#L53 https://github.com/elastic/apm-server/blob/52b02b7323b0026b08f279c680c59a5a2ba35bfe/testing/benchmark/Makefile#L119-L122.

Making the macro benchmarks overly reliant on the stack update workflow and assumes that unified stack builds are mostly successful, which is not always the case. This has caused the APM Server latest changes to not be benchmarked for several days, which is less than ideal.

Additionally, if we don't schedule the benchmarks to be run a few hours after the stack bump happens, we may have an unnecessarily long feedback cycle.

## Proposed path forward

To reduce dependencies, pains, and have a faster feedback cycle on the changes that are committed to the APM Server, I propose that we build the local branch changes, package it in a docker image, and use that docker image for the APM Server benchmarks. We should keep make use of the committed stack hash version since that assures us that Stack components are healthy according to our system tests.

We already have packaging and docker image building in place in [`testing/cloud`](https://github.com/elastic/apm-server/tree/main/testing/cloud#building-and-deploying-a-custom-elastic-agent-image), we only need to polish and adapt it so it can be used in `testing/benchmark`.

Once we've closed this issue, it will also enable us to run the automated benchmarks on demand in PRs (with adequate protections).

**Comment by simitt** [comment]
carried over to iteration-05
