### ISSUE TITLE
Parse user-agent field into specific and searchable fields

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#1032]
Currently the `user-agent` field is created by the apm-server and added to `context.user`.
The value for this field could look something like: 

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.2 (KHTML, like Gecko) Ubuntu/11.10 Chromium/15.0.874.106 Chrome/15.0.874.106 Safari/535.2`

This should be parsed into the following fields and stored in ES

```json
{
  "browser": {"name": "Chromium", "version": "15.0.874.106"},
  "os": {"name": "Ubuntu", "version": "11.10"}
}
```

**Comment by watson** [comment]
The `User-Agent` header is not standardized AFAIK, so trying to parse it might not be worth it.

Is there a more reliable way to get this data from within the browser?

**Comment by jahtalab** [comment]
@watson, On the browser we also have `navigator.userAgent` but the documentation for it specifically says not to rely on this field for browser identification:

> The specification asks browsers to provide as little information via this field as possible. Never assume that the value of this property will stay the same in future versions of the same browser. Try not to use it at all, or only for current and past versions of a browser. New browsers may start using the same UA, or part of it, as an older browser: you really have no guarantee that the browser agent is indeed the one advertised by this property.

> Also keep in mind that users of a browser can change the value of this field if they want (UA spoofing).

See [this](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/userAgent) and [this](https://html.spec.whatwg.org/multipage/system-state.html#dom-navigator-useragent) for more.

Also Fields in the [Navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator) API that might provide the same kind of information (like platform) are also experimental/non-standard.

And regarding the "User-Agent" header, it is defined [here](https://tools.ietf.org/html/rfc7231#section-5.5.3) with some conventions concerning it's value.

**Comment by roncohen** [comment]
This can be done today using the [user agent ingest pipeline](https://www.elastic.co/guide/en/elasticsearch/plugins/current/using-ingest-user-agent.html) and pointing APM Server to use a specific pipeline. 

We should investigate if it makes sense for APM Server to automatically set up an ingest pipeline with the plugin, or we should just document how users can set it up manually.

In general, ingest pipelines with APM Server works at the moment, but we need to consider setting up an automated test for it.

**Comment by graphaelli** [comment]
I agree with @roncohen that this makes more sense as part of the ingest pipeline.  Also agree that we should document this and consider automatically setting up this pipeline - it appears this ingest processor is shipped by default in all version of elasticsearch supported by apm-server, including oss flavors.

For manual setup, this can get you started:

## Create ingest pipeline

Parse `context.request.headers.user-agent` into `context.request.headers.ua`.

```
curl -XPUT --header "Content-Type:application/json" http://localhost:9200/_ingest/pipeline/apm_user_agent -d '
{
  "description" : "Add user agent information for APM events",
  "processors" : [
    {
      "user_agent" : {
        "field": "context.request.headers.user-agent",
        "target_field": "context.request.headers.ua",
        "ignore_missing": true
      }
    }
  ]
}'
```


## Start apm-server 
    apm-server -E output.elasticsearch.pipeline=apm_user_agent


## Observe added `ua` field
```
GET /apm-7.0.0-alpha1-error-*/_search
{
  "_source": ["context.request.headers.user-agent", "context.request.headers.ua"]
}
```

```
{
  "_source": {
    "context": {
      "request": {
        "headers": {
          "ua": {
            "os": "Other",
            "name": "Other",
            "os_name": "Other",
            "device": "Other"
          },
          "user-agent": "Mozilla Chrome Edge"
        }
      }
    }
  }
}
```

```
{
  "_source": {
    "context": {
      "request": {
        "headers": {
          "ua": {
            "patch": "874",
            "major": "15",
            "minor": "0",
            "os": "Ubuntu 11.10",
            "os_minor": "10",
            "os_major": "11",
            "name": "Chromium",
            "os_name": "Ubuntu",
            "device": "Other"
          },
          "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.2 (KHTML, like Gecko) Ubuntu/11.10 Chromium/15.0.874.106 Chrome/15.0.874.106 Safari/535.2"
        }
      }
    }
  }
}
```

**Comment by alvarolobato** [comment]
We don't have a timeframe to implement this, we will create an FAQ with instructions to create it manually in the meantime https://github.com/elastic/apm-server/issues/1056

**Comment by alvarolobato** [comment]
We are going to have a look on how to implement this and create a mini-design for it.

**Comment by alvarolobato** [comment]
Finally we are not going to need a design doc for this, it will be implemented in the pipeline.
The only decision to be made is the key where to put it.

**Comment by felixbarny** [comment]
ECS has some field names defined, we should align with that: https://github.com/elastic/ecs/blob/master/schemas/user_agent.yml

**Comment by simitt** [comment]
@felixbarny when using [ES user_agent plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/using-ingest-user-agent.html) the field names are not defined by the server. I think we should go with the plugin, which I assume to also align with ECS in the long run.
