### ISSUE TITLE
docs: update sourcemap guide

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#10341]
From `8.7` onwards, the APM Server (standalone & managed by Elastic Agent) fetches sourcemaps directly from Elasticsearch. For backwards compatibility we still support fetching from Kibana, but only as a fallback. 

**What changed?**
APM Kibana changed the internal logic to always write sourcemaps to a newly introduced system index in Elasticsearch, from which the APM Server can read them. Sourcemaps are no longer passed to the APM Server via Fleet configuration. 

Available config options: `apm-server.rum.source_mapping.elasticsearch.*` if no dedicated elasticsearch config is set, the standard output elasticsearch configuration is used .

- Fleet managed: automatically filled 
- Elastic Agent standalone or APM Server standalone : user configurable

More details in https://github.com/elastic/apm-server/issues/9643

**Comment by colleenmcginnis** [comment]
@simitt are there updates that need to be made to [this doc](https://www.elastic.co/guide/en/kibana/current/rum-sourcemap-api.html) in this Kibana guide in addition to the docs updated in #12131?
