### ISSUE TITLE
APM agent for .net

### ISSUE THREAD

**Issue by Minx-SigEp** [elastic/apm-server#1035]
Not sure which repository this request best first in. 

It would be nice to have an APM agent for .net. The elastic team has created agents for Ruby, Go, Java, and a few other. An APM agent for asp.net would be a value add to go along with all the other amazing tools elastics has created like Nest (https://www.nuget.org/packages/NEST/) for the .Net community.

**Comment by hiwjcn** [comment]
Same requirement here 👍

**Comment by watson** [comment]
An official Elastic APM .NET Agent is on our roadmap and development will most likely start some time within the next few months - but it will take some time to be ready for production use.

**Comment by cilerler** [comment]
@alvarolobato I'm not sure why you did close this issue.  As long as it is in road-map it should stay open in order us to get updates about it...  I'll appreciate if you may re-open it.  Thanks in advance.

**Comment by alvarolobato** [comment]
Hi @cilerler  this is the APM server repo, we don't manage the agent specifics here.
We're creating a .NET specific repo very soon and you'll be able to follow progress there. I'll link to it here shortly.

**Comment by gregkalapos** [comment]
Hi Everyone, good news! 
The repository is there: https://github.com/elastic/apm-agent-dotnet 

We’ll start working on this very soon. If you have any input for us, feel free to use that repo to communicate .NET specific questions, requests, issues, etc. 

I’d be very happy to learn about your specific scenario and what you expect from us.

cc @cilerler @Minx-SigEp @hiwjcn

**Comment by youngrc1** [comment]
.NET apm is on the roadmap and under development from Elastic

https://github.com/elastic/apm-server/issues/1035

**Comment by kartheek91** [comment]
How to install apm in .net framework 4.5.2

**Comment by gregkalapos** [comment]
Hi @kartheek91, 

we just shipped the first preview of the agent: https://www.elastic.co/blog/elastic-apm-dot-net-agent-preview-released 

Unfortunately 4.5.2 is not supported. We support .NET Framework from version 4.6.1 (more details in the blogpost)

I have a small favour to ask: please ask questions like this on [discuss](https://discuss.elastic.co/c/apm) and there is also the [.NET Agent repo](https://github.com/elastic/apm-agent-dotnet), which contains more info.
