### ISSUE TITLE
Document how to automatically install APM integration package

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#10361]
The APM integration package must be installed regardless of whether APM Server is run as an Elastic Agent integration or as a standalone process. Automatically installing the APM integration package is a common requirement.

We should ensure this is well documented, probably in the [APM Guide Quick start](https://www.elastic.co/guide/en/apm/guide/current/apm-quick-start.html) section. To install the package, it is enough to include the following in `kibana.yml`:

```yaml
xpack.fleet.packages:
- name: apm
```

This will even work in air-gapped environments, as we bundle the APM integration package with Kibana.

See also https://discuss.elastic.co/t/how-to-install-apm-server-in-legacy-mode-without-elastic-apm-integration/325724/2?u=axw

**Comment by axw** [comment]
@kpollich even for preconfiguration? If so, why? Can that be changed?

**Comment by kpollich** [comment]
> even for preconfiguration? If so, why? Can that be changed?

I should clarify. The bundled integration will still be installed via preconfiguration if there's no reachable package registry. When I say "a reachable instance of EPR is required" I mean required for operation of the Fleet and Integrations apps. Even without a reachable EPR configured we can still install + configure the APM integration and ingest data. 

As for the "why" - Fleet will always try to reach out to EPR to determine whether a given package is out of date. The "update required" status for packages is driven entirely by what's reported by EPR, so we're always checking with that service when packages are queried, installed, etc. There's work to do on our end around intelligently disabling those "is package up to date?" style requests, and failing fast when EPR isn't reachable. 

Some related issues:
https://github.com/elastic/kibana/issues/128130
https://github.com/elastic/kibana/issues/131505
https://github.com/elastic/kibana/issues/125548

**Comment by axw** [comment]
@kpollich thanks for clarifying.

So the goal of this docs issue is just to document how to install the package automatically, and anything related to interacting with the Fleet/Integrations apps was meant to be out of scope.

Maybe we can just mention that in airgapped environments, interacting with the app still requires access to a self-hosted EPR, and link to the Fleet air-gapped environment setup docs, which go into self-hosting EPR etc. We should be careful not to leave users with the impression that this is required for installation though.

**Comment by AlbusLumos** [comment]
Hi, I add the below setting in kibana.yml
xpack.fleet.packages:
  - name: apm

but I got the error message: [ERROR][plugins.apm] FleetUnauthorizedError: User does not have adequate permissions to access Fleet packages. 

How to fix it?

**Comment by kpollich** [comment]
Hi @AlbusLumos - your user needs the `Integrations:All` permissions from Kibana's role management UI. 

- https://www.elastic.co/guide/en/kibana/current/kibana-role-management.html
- https://www.elastic.co/guide/en/kibana/current/kibana-privileges.html

**Comment by AlbusLumos** [comment]
Thanks, @kpollich 
But it's test environment, so it didn't enable the security. 
Does it means that it must enable security? 
If security is disabled, why would such a check still be performed?

**Comment by juliaElastic** [comment]
@AlbusLumos AFAIK security is [enabled](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#general-security-settings) by default, and Fleet doesn't work with disabled security. The `Integrations:All` is a required permission to install integration packages.

**Comment by GyurkanM** [comment]
Option to use it with security disabled will be welcome, no need for security when it is deployed on an isolated VM for demonstration, testing purposes.

**Comment by simitt** [comment]
The support to disable security depends on Fleet support (part of Kibana). @juliaElastic does an enhancement request exist for this and could you link it here if so (I didn't manage to find it).

**Comment by axw** [comment]
@simitt I opened this a while back: https://github.com/elastic/kibana/issues/160486
