### ISSUE TITLE
[DOCS] Document how to modify the APM Integration settings

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/apm-server#10442]
Can we rename or make it easier to find https://www.elastic.co/guide/en/apm/guide/8.6/input-apm.html#input-apm ?

While technically correct, I think we rarely use the "APM Input" naming.

"APM Integration settings" or "configuration"?

It would make it easier for users looking for:
- How do I change the secret token
- How do I enable RUM intake
- How do I change or enable API token auth

**Comment by bmorelli25** [comment]
Yes! This is done.
