### ISSUE TITLE
Cannot modify admin password "changeme" to a new secure one

### ISSUE THREAD

**Issue by anasshatnawi** [elastic/apm-server#10495]
Hello, 

I would like to change the default admin password from "changeme" to another one. I have tried several ways but it does not work!

1- I was not able to change it via the kibana GUI although by using another superuser account. 

2-I putted the (- "ELASTIC_PASSWORD=my-new-pass") in the environment variable of elasticsearch, but it kept using "changeme" password. 

3- I tried to update the password via the console of elasticsearch container using (bin\elasticsearch-reset-password -u admin --auto) but it gave this exception: Exception in thread "main" java.io.UncheckedIOException: could not write file [/usr/share/elasticsearch/config/users]

4- I changed all places in repo where "changeme" is located to "my-new-pass", but it does not work ):

Could you please give me some directions how I can get changing this password!

Best regards

**Comment by anasshatnawi** [comment]
I would like to clearify that I talk about elasticsearch that is used in this APM server. I use the docker compose file of this repo to run the whole stack. Please note that, I can change the password for a standalone elasticsearch container but not the one used in this repo. 
![image](https://user-images.githubusercontent.com/6341042/226397476-7bcf6bc8-77cd-4bb3-a104-282fd853b63b.png)
![image](https://user-images.githubusercontent.com/6341042/226397996-30b87565-cf75-4df2-a80a-147ccc171304.png)

**Comment by axw** [comment]
The (hashed) password is defined in https://github.com/elastic/apm-server/blob/38d31a3aff8866eb4ed2b4b59f5880d8ea3eea8f/testing/docker/elasticsearch/users. You could mount an alternative users file into your Elasticsearch container.

As @simitt said above, the `docker-compose.yml` is tailored for apm-server development purposes. We won't be accepting any changes to make it more configurable for other purposes, so I'll go ahead and close this. If you have follow up questions, please open a topic at https://discuss.elastic.co/

**Comment by anasshatnawi** [comment]
Thanks! that file solved my problem :)
