### ISSUE TITLE
Service target is not considered in service destination aggregation

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-server#10531]
**APM Server version** (`apm-server version`): 8.x

**Description of the problem including expected versus actual behavior**: `service.target.*` fields are not considered for service_destination aggregation. This is because service destination aggregation skips all spans with destination service set as `nil` ([ref](https://github.com/elastic/apm-server/blob/f701332a56aabec12f6454a649b97afa48f3cae0/x-pack/apm-server/aggregation/spanmetrics/aggregator.go#L230-L232)) and we don't infer destination service fields if only service target fields are set ([ref](https://github.com/elastic/apm-data/blob/3ad1a5caedc9bf5b36ebd62cdc8193e7cedc7d05/input/elasticapm/internal/modeldecoder/v2/decoder.go#L1032-L1035)).

**Steps to reproduce**:
1. Send exit spans with `service.target.*` set but missing `destination.service.*` fields.
2. Observe that `service_destination` aggregations are not produced.

**Provide logs (if relevant)**: NA

**Comment by dmathieu** [comment]
I'm having a look at this, and I wonder what the expected behavior should be.
The aggregation [requires a destination](https://github.com/elastic/apm-server/blob/f701332a56aabec12f6454a649b97afa48f3cae0/x-pack/apm-server/aggregation/spanmetrics/aggregator.go#L262), so it seems we should detect one from the target? What should that be?

**Comment by lahsivjar** [comment]
When decoding the model, as per the spec, we do infer target from destination resource but not vice versa ([ref](https://github.com/elastic/apm-data/blob/main/input/elasticapm/internal/modeldecoder/v2/decoder.go)). Full spec available [here](https://github.com/elastic/apm/blob/main/specs/agents/tracing-spans-service-target.md).

> The aggregation [requires a destination](https://github.com/elastic/apm-server/blob/f701332a56aabec12f6454a649b97afa48f3cae0/x-pack/apm-server/aggregation/spanmetrics/aggregator.go#L262), so it seems we should detect one from the target?

IIANM, the aggregation should work without destination resource if `service.target.*` are specified.
