### ISSUE TITLE
Remove global labels from the aggregation key for service tx metrics for RUM services

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-server#10532]
In 8.7, we are enabling service transaction metrics by default (in the service inventory). For RUM, it's easy to create global labels that are actually user-specific (e.g. client IP), which could lead to an explosion of metric groups to track. Because there is currently no way to limit the number of tracked metric groups per service, this could lead to data from other services being pushed into the overflow bucket. Until we have a way of limiting the impact a single misbehaving RUM service has, we should drop global labels from the aggregation key for RUM services.

**Comment by dgieselaar** [comment]
@simitt Should this be applied to just service tx metrics or also tx metrics?

**Comment by simitt** [comment]
For tx metrics we already have overflow buckets per service groups, so any RUM related overflow would be limited to this one service group, and excluding RUM global labels wouldn't be necessary. 
However, for consistency and to keep the patch fix to a minimum I suggest to apply the fix directly in [`AggregatedGlobalLabels.Read(event *model.APMEvent)`](https://github.com/elastic/apm-server/blob/main/x-pack/apm-server/aggregation/labels/labels.go#L52), which is where the global labels are read to be part of the aggregation key, and where the `model.APMEvent` is known, which can be used for identifying the `agent.name`. 
With this, the global labels would generally be excluded from any aggregation keys for RUM agents.
