### ISSUE TITLE
Make concurrent requests limit based on memory

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1057]
Limit the number of requests automatically based on memory availability / memory usage,  transparently to the user (without config option).

**Comment by alvarolobato** [comment]
Is this still needed after V2? It seems to me that we are now memory bounded and this is not a big problem. Unless I'm understanding this wrong.

**Comment by graphaelli** [comment]
Agreed, v2 makes this much less urgent.  Of course it would be nice if APM server throttled based on how much memory is available rather than a manually set configuration option but it's not practical at the moment.
