### ISSUE TITLE
Dashboards `Services [APM]` not showing service names correct

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1059]
When loading dashboards into Kibana the visualisation `Services APM` is not shown properly in `master` and `6.x`. 

[Visualisation json code](https://github.com/elastic/apm-server/blob/master/_meta/kibana/6/dashboard/apm-dashboards.json#L5) and according [url template](https://github.com/elastic/apm-server/blob/master/_meta/fields.common.yml#L197) used for the creation of the index pattern.

**Current**:
![screen shot 2018-07-03 at 08 53 14](https://user-images.githubusercontent.com/5555349/42203449-145c0cd0-7e9f-11e8-918b-7cebe5c765ff.png)

**Expected**: 
![screen shot 2018-07-03 at 08 53 09](https://user-images.githubusercontent.com/5555349/42203445-10a952b4-7e9f-11e8-9705-a057e160f0c9.png)

**Comment by simitt** [comment]
![screen shot 2018-07-04 at 10 46 04](https://user-images.githubusercontent.com/5555349/42266759-9e9c2bae-7f77-11e8-8a74-65d49b6a439b.png)

**Comment by timroes** [comment]
@elastic/kibana-management After looking into this with @simitt this seems to be a change in field formatters. Field formatters since 6.4 doesn't seem to allow relative URLs anymore? Is this change made on purpose? You should sync up with APM team and @simitt about that, since this would break APM dashboards.

**Comment by chrisronline** [comment]
@simitt Can you click edit for the `context.service.name` field so I can see the Url configuration options, then paste that screenshot in here? Thanks

**Comment by simitt** [comment]
@chrisronline here's the screenshot.

![Screen Shot 2018-07-05 at 22.30.46.png](https://zube.io/files/elastic/0bb6cab00cf44e39a6d3226ffa6ce215-screen-shot-2018-07-05-at-22-30-46.png)

**Comment by chrisronline** [comment]
Hmm. I'm not seeing this on master.

Is it possible for me to get my local environment setup the same as yours to try and reproduce?

<img width="679" alt="screen shot 2018-07-05 at 4 38 17 pm" src="https://user-images.githubusercontent.com/56682/42346821-da2c1936-8071-11e8-90af-e15fdf43a2bf.png">
<img width="141" alt="screen shot 2018-07-05 at 4 38 25 pm" src="https://user-images.githubusercontent.com/56682/42346822-da3f286e-8071-11e8-82a7-71c2f0f22fec.png">

**Comment by simitt** [comment]
I run everything using the https://github.com/elastic/apm-integration-testing repo. There are some basic setup instructions in the readme. Once you have the prerequisites installed you can run:
```
make venv
source venv/bin/activate
./scripts/compose.py start 6.4 --with-opbeans-node
./scripts/compose.py load-dashboards
```
You should have the exact same setup then.

**Comment by simitt** [comment]
The same issue exists in master, which you can test by simply replacing `6.4` with `master`.

**Comment by chrisronline** [comment]
@simitt I have a fix: https://github.com/elastic/kibana/pull/20521
