### ISSUE TITLE
Update documentation for logstash output with the correct defaults

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-server#10643]
The [current documentation](https://www.elastic.co/guide/en/apm/guide/current/logstash-output.html#_accessing_metadata_fields) for APM-Server indicates that with logstash output the default value of `@metadata.beat` to `apm`. However, if the value of the config `output.logstash.index` is not set then the default value is `apm-server`.

**Comment by lucabelluccini** [comment]
The documentation is also broken as I think the Logstash guide should contain the "new" APM data streams with the assets installed by APM Integration and not the `apm-...` indices.

**Comment by lucabelluccini** [comment]
Just to add more context - I would expect APM Server standalone with Logstash output to be used as any other Elastic Agent integration and benefit from Data Stream auto routing https://www.elastic.co/guide/en/fleet/current/logstash-output.html

I find it odd that we need `%{[data_stream.type]}-%{[data_stream.dataset]}-%{[data_stream.namespace]}` only for APM.

**Comment by felixbarny** [comment]
I agree but I think the solution is that the Logstash data stream auto routing takes into account dotted field names.

**Comment by lucabelluccini** [comment]
For the best course of actions, I would propose the following workaround as:
- it will work transparently
- it will not break in case APM Server will start publishing the `data_stream` fields as objects
- it will not affect Elastic Agent integrations sending `data_stream` fields as objects

```
input {
  elastic_agent {
    port => 5044
  }
}

filter {
mutate {
  rename => {
    "[data_stream.type]" => "[data_stream][type]"
    "[data_stream.dataset]" => "[data_stream][dataset]"
    "[data_stream.namespace]" => "[data_stream][namespace]"
  }
}
}
output {
  elasticsearch {
    hosts => ["http://localhost:9200"] 
    data_stream => "true"
  }
}

```
