### ISSUE TITLE
agentcfg can't get agent-configs if output.elasticsearch is disabled

### ISSUE THREAD

**Issue by b2ronn** [elastic/apm-server#10656]
problem with getting agent-configs if output.elasticsearch.enabled is false

**<details><summary>apm-server configuration example</summary><blockquote>**

```apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-test
spec:
  config:
    apm-server:
      auth:
        anonymous:
          allow_agent:
            - rum-js
            - js-base
            - java
            - dotnet
            - php
            - opentelemetry/cpp
            - python
          enabled: true
        api_key:
          enabled: false
          limit: 100
      host: '0.0.0.0:8200'
      rum:
        allow_origins:
          - '*'
        enabled: true
        source_mapping:
          elasticsearch:
            hosts:
              - 'https://elasticsearch-es-http.elastic.svc:9200'
            password: '${ELASTIC_PASS}'
            ssl:
              certificate_authorities:
                - config/elasticsearch-certs/ca.crt
            username: '${ELASTIC_NAME}'
          enabled: true
      default_service_environment: undefined
      agent.config:
        elasticsearch:
          hosts:
            - 'https://elasticsearch-es-http.elastic.svc:9200'
          password: '${ELASTIC_PASS}'
          protocol: https
          ssl:
            certificate_authorities:
              - config/elasticsearch-certs/ca.crt
          username: '${ELASTIC_NAME}'
      ssl:
        supported_protocols:
          - TLSv1.1
          - TLSv1.2
          - TLSv1.3
      kibana:
        password: '${ELASTIC_PASS}'
        username: '${ELASTIC_NAME}'
      capture_personal_data: true
      pprof.enabled: false
      expvar.enabled: false
    logging.level: debug
    output:
      elasticsearch:
        enabled: false
      logstash:
        enabled: true
        hosts:
          - 'logstash:5044'
  count: 1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  podTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - env:
            - name: ELASTIC_PASS
              valueFrom:
                secretKeyRef:
                  key: elastic
                  name: elasticsearch-es-elastic-user
            - name: ELASTIC_NAME
              value: elastic
          name: apm-server
  version: 8.7.0
```
  </blockquote></details>

**Error:**
```
{"log.level":"error","@timestamp":"2023-04-14T10:09:52.467Z","log.logger":"agentcfg","log.origin":{"file.name":"agentcfg/elasticsearch.go","file.line":134},"message":"refresh cache error: context deadline exceeded","service.name":"apm-server","ecs.version":"1.6.0"}
```

ps: 
openshift 4.11
ECK 2.7.0
Ekastic/kibana 8.7.0

**Comment by simitt** [comment]
@carsonip please take a look if this is indeed a bug that was introduced with the changes in `8.7.0`.

**Comment by carsonip** [comment]
Hi @b2ronn,

According to https://www.elastic.co/guide/en/apm/guide/current/configure-agent-config.html#agent-config-authentication the only accepted elasticsearch configuration options in 8.7.0 under `agent.config.elasticsearch` are `username`, `password` and `api_key`. All the other options such as `hosts` and `ssl` under `agent.config.elasticsearch` are ignored. Other ES config e.g. `hosts` and `ssl` for agentcfg are read from `output.elasticsearch`, which are absent in your config file. Therefore, it results in a `context deadline exceeded` when it attempts to connect to the default ES host `localhost:9200`.

A workaround for your case is to enable the fallback to the pre-8.7 agent config fetcher by removing the entire `agent.config.elasticsearch` section. This way it will still log a `refresh cache error: context deadline exceeded` but at WARN level as it attempts to guess the ES endpoint, and will fallback to fetch agent config from kibana.

**Comment by b2ronn** [comment]
if i add to config
```output:
    elasticsearch:
        enabled: false
        hosts:
            - 'https://elasticsearch-es-http.elastic.svc:9200'
        password: ${ELASTIC_PASS}
        ssl:
            certificate_authorities:
                - config/elasticsearch-certs/ca.crt
        username: ${ELASTIC_NAME}
```
then all the same apm-server cannot receive agentconfigs

**Comment by carsonip** [comment]
> if i add to config
> 
> ```
>     elasticsearch:
>         enabled: false
>         hosts:
>             - 'https://elasticsearch-es-http.elastic.svc:9200'
>         password: ${ELASTIC_PASS}
>         ssl:
>             certificate_authorities:
>                 - config/elasticsearch-certs/ca.crt
>         username: ${ELASTIC_NAME}
> ```
> 
> then all the same apm-server cannot receive agentconfigs

All outputs with `enabled: false` are ignored. All the configuration under them are also ignored. The best way to make agent config work in your setup is to remove `agent.config.elasticsearch` so that apm server fetches agent config from kibana.

**Comment by simitt** [comment]
https://github.com/elastic/apm-server/issues/10659 was created as a follow-up to generally allow the new agent config fetcher to work if apm-server is running with a non-ES output. 

Since @carsonip provided a valid workaround for this report for the time being, and we haven't heard back from @b2ronn, closing this issue. Let us know if anything else comes up.

**Comment by 0xpekenbower** [comment]
i think this error indicate a problem with output 
```"log.logger":"agentcfg","log.origin```
in your config 
```    output:
      elasticsearch:
        enabled: false
      logstash:
        enabled: true
        hosts:
          - 'logstash:5044'
```
mean you use logstash so first logstash need ```logstash-input-beats``` it's a plugin you can install it using this command in your docker file ```RUN logstash-plugin install logstash-input-beats``` . 

with the same config if you disable logstash output and enable elasticsearch output , will work .

**Comment by carsonip** [comment]
@0xpekenbower thanks for the comment but I'm afraid what you said is not related to the agentcfg issue above.
