### ISSUE TITLE
[docs] update breaking changes in changelogs >= 8.0 with ILM delete phases

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#10921]
> * Introduced a delete phase for all data streams. Traces, errors and logs are kept for 10 days, metrics are kept for 90 days [6480](https://github.com/elastic/apm-server/pull/6480)
> * Changed RUM traces to use a dedicated data stream (traces-apm.rum). RUM traces are kept for 90 days [6480](https://github.com/elastic/apm-server/pull/6480)

The above changes should be listed under the `Breaking Changes` section in the [release notes](https://www.elastic.co/guide/en/apm/guide/8.0/release-notes-8.0.html) for `8.0`. The docs need to be changed from `8.0` onwards to make it clear for any users that ILM policies with delete phases are introduced in this version.

**Comment by axw** [comment]
We should also document https://github.com/elastic/apm-server/pull/10865 while we're at it.

**Comment by dmathieu** [comment]
Fixed with #10980.
