### ISSUE TITLE
docs: update default policies

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#10936]
https://www.elastic.co/guide/en/apm/guide/current/ilm-how-to.html#index-lifecycle-policies-default needs to be updated to reflect the latest datastreams and the default policy values. 

Data stream | Rollover after | Delete after | Comment
-- | -- | -- | --
traces-apm | 30 days / 50 GB | 10 days | raw trace event data
traces-apm.rum | 30 days / 50 GB | 90 days | raw RUM trace event data, used in the UI
logs-apm.error | 30 days / 50 GB | 10 days | error event data
logs-apm.app | 30 days / 50 GB | 10 days | logs event data
metrics-apm.app | 30 days / 50 GB | 90 days | custom application specific metrics 
metrics-apm.internal | 30 days / 50 GB | 90 days | common system metrics and language specific metrics, e.g. CPU and memory usage
metrics-apm.service_destination_1m | 7 days / 50GB | 90 days | aggregated transaction metrics powering the APM UI
metrics-apm.service_destination_10m | 14 days / 50GB | 180 days | aggregated transaction metrics powering the APM UI
metrics-apm.service_destination_60m | 30 days / 50GB | 390 days | aggregated transaction metrics powering the APM UI 
metrics-apm.service_summary_1m | 7 days / 50GB | 90 days | aggregated transaction metrics powering the APM UI  
metrics-apm.service_summary_10m | 14 days / 50GB | 180 days | aggregated transaction metrics powering the APM UI 
metrics-apm.service_summary_60m | 30 days / 50GB | 390 days | aggregated transaction metrics powering the APM UI 
metrics-apm.service_transaction_1m | 7 days / 50GB | 90 days  | aggregated transaction metrics powering the APM UI 
metrics-apm.service_transaction_10m | 14 days / 50GB | 180 days | aggregated transaction metrics powering the APM UI 
metrics-apm.service_transaction_60m | 30 days / 50GB | 390 days | aggregated transaction metrics powering the APM UI 
metrics-apm.transaction_1m | 7 days / 50GB | 90 days  | aggregated transaction metrics powering the APM UI 
metrics-apm.transaction_10m | 14 days / 50GB | 180 days | aggregated transaction metrics powering the APM UI 
metrics-apm.transaction_60m | 30 days / 50GB | 390 days | aggregated transaction metrics powering the APM UI

**Comment by amcsi** [comment]
Is it OK to edit these lifecycle policies to change their values, or am I somehow supposed to associate a new, custom lifecycle policy with these APM data streams or whatever?

**Comment by matthewabbott** [comment]
@amcsi, You shouldn’t edit the default policies directly. Rather, Elastic has component templates of the form `*@custom`, eg `traces-apm@custom`, for each of the default policies. These can be modified and used to effectively associate a new policy with these built-in data streams.

We have a guide in our documentation on how to implement these custom component templates here: https://www.elastic.co/guide/en/apm/guide/current/ilm-how-to.html#data-streams-custom-policy
