### ISSUE TITLE
Smoke tests are failing consistently

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#11018]
Smoke tests have been failing for a while. e.g. https://github.com/elastic/apm-server/actions/runs/5307373657

The upgrade smoke tests fail because they incorrectly expect ILM policies to exist before upgrading:
> -> ILM policy metrics-apm.service_transaction_interval_metrics-default_policy.1m error: {"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"Lifecycle policy not found: metrics-apm.service_transaction_interval_metrics-default_policy.1m"}],"type":"resource_not_found_exception","reason":"Lifecycle policy not found: metrics-apm.service_transaction_interval_metrics-default_policy.1m"},"status":404}

The OS smoke tests are failing for some other reason that looks like it's related to the automation, rather than the tests themselves:
> Run elastic/apm-pipeline-library/.github/actions/notify-build-status@current
> Run exec node /home/runner/work/_actions/elastic/apm-pipeline-library/current/.github/actions/notify-build-status/dist/index.js
> Error: Error: The env var 'MESSAGE' isn't defined.
> Error: Process completed with exit code [1](https://github.com/elastic/apm-server/actions/runs/5307373657/jobs/9606145638#step:3:1).

**Comment by kruskall** [comment]
Fixed by https://github.com/elastic/apm-server/pull/11134 and https://github.com/elastic/apm-server/pull/11067
