### ISSUE TITLE
Ability to run standalone apm server 8.x without elasticsearch output nor kibana endpoint

### ISSUE THREAD

**Issue by jguay** [elastic/apm-server#11031]
Running standalone APM Server 8.x without elasticsearch output nor kibana endpoint will return
```
{"log.level":"error","@timestamp":"2023-06-19T01:02:04.567Z","log.logger":"beater","log.origin":{"file.name":"beater/beater.go","file.line":368},"message":"error waiting for server to be ready: cannot wait for integration without either Kibana or Elasticsearch config","service.name":"apm-server","ecs.version":"1.6.0"}
```

This is a [documented requirement](https://www.elastic.co/guide/en/apm/guide/8.8/kafka-output.html#_kibana_configuration_2)

However if apm server is not intended to be allowed to connect to Kibana nor Elasticsearch, this adds a requirement to open connection to Kibana for APM Server standalone to work... Also currently with fleet, only logstash and elasticsearch output are supported hence why APM Server standalone may be used (example using Kafka or Redis output)

Requested feature would be to add the ability to disable the check for APM integration assets installation status hence something like `apm-server.check-assets` defaulting to true but setting to false would not attempt to check assets are installed or require kibana endpoint

**Comment by simitt** [comment]
This is indeed a valid usecase for outputs different than Elasticsearch. We have seen issues in the past when templates and ingest pipelines were missing before data ingestion started. After some previous internal discussions, we would want to add additional safety guards and only allow disabling the check if output is different than ES.

**Comment by heisGarvit** [comment]
Hi, any update / workout found to remove dependency on startup ?

**Comment by axw** [comment]
This will be resolved in 8.15.0, by https://github.com/elastic/apm-server/pull/12066 and https://github.com/elastic/elasticsearch/pull/108860.

**Comment by bafzachris** [comment]
With 8.15.3 is still get:

`{"log.level":"error","@timestamp":"2024-11-06T07:37:36.527Z","log.logger":"beater","log.origin":{"function":"github.com/elastic/apm-server/internal/beater.waitReady","file.name":"beater/waitready.go","file.line":64},"message":"precondition failed: dial tcp 127.0.0.1:9200: connect: connection refused","service.name":"apm-server","ecs.version":"1.6.0"}`

**Comment by derek82511** [comment]
The same problem as @bafzachris
