### ISSUE TITLE
Document OTLP/HTTP, OTLP/gRPC, and Jaeger APIs

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#11066]
We currently document the HTTP routes for Elastic APM agents: https://www.elastic.co/guide/en/apm/guide/current/api.html

We should expand this to also cover the OpenTelemetry and Jaeger HTTP and gRPC APIs we support.

**Comment by simitt** [comment]
copying from @axw 's comment in a different thread:

Elastic APM/HTTP paths:
```
/
/intake/v2/events
/intake/v2/rum/events
/intake/v3/rum/events
/config/v1/agents
/config/v1/rum/agents
```

OTLP/gRPC paths:
```
/opentelemetry.proto.collector.metrics.v1.MetricsService/Export
/opentelemetry.proto.collector.trace.v1.TraceService/Export
/opentelemetry.proto.collector.logs.v1.LogsService/Export
```

OTLP/HTTP paths:
```
/v1/metrics
/v1/traces
/v1/logs
```

Jaeger/gRPC paths:
```
/jaeger.api_v2.CollectorService/PostSpans
/jaeger.api_v2.SamplingManager/GetSamplingStrategy
```
