### ISSUE TITLE
Documentation to customise APM Server doesnt reflect recent changes

### ISSUE THREAD

**Issue by cdavid15** [elastic/apm-server#11088]
**APM Server version** (`apm-server version`): 

8.7 and above

**Description of the problem including expected versus actual behavior**:

Copy code snippet from documentation causes docker build error.

Suspect this is linked to https://github.com/elastic/apm-server/pull/9604

**Steps to reproduce**:

Copy snippet from documentation (https://www.elastic.co/guide/en/apm/guide/current/running-on-docker.html#_custom_image_configuration) and execute docker build results in error

```sh
FROM docker.elastic.co/apm/apm-server:8.8.1
COPY apm-server.yml /usr/share/apm-server/apm-server.yml
USER root
RUN chown root:apm-server /usr/share/apm-server/apm-server.yml
USER apm-server
```

**Provide logs (if relevant)**:

```sh
chown: invalid group: 'root:apm-server'
The command '/bin/sh -c chown root:apm-server /usr/share/apm-server/apm-server.yml' returned a non-zero code: 1
```

**Comment by carsonip** [comment]
Thanks for reporting the issue and I can confirm it. The Dockerfile that would copy apm-server.yml properly is:
```
FROM docker.elastic.co/apm/apm-server:8.8.1
COPY --chmod=0644 --chown=1000:1000 apm-server.yml /usr/share/apm-server/apm-server.yml
```

I'll update the docs.
