### ISSUE TITLE
php apm agent error - Elastic\Apm\Impl\getmypid()

### ISSUE THREAD

**Issue by mohammadalipour** [elastic/apm-server#11239]
**APM Server version** (`apm-server version`): 8.7.2

**Description of the problem including expected versus actual behavior**:
PHP-APM-agent 1.9.1 is installed on the php-alpine image (PHP version 8.1) on the AWS ECS machine

**Provide logs (if relevant)**:
and get this error : 

`[Elastic APM PHP Tracer][CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable] Handling shutdown call let a throwable escape - skipping the rest of the steps. Error: Call to undefined function Elastic\Apm\Impl\getmypid()`

**Comment by dmathieu** [comment]
That seems like an issue for https://github.com/elastic/apm-agent-php?
