### ISSUE TITLE
Create Known Issues section in release notes

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#11282]
Create a dedicated section _Known Issues_ in apm-server docs. The goal is that all known issues from a specific version are easily searchable and users can get a good overview before upgrading to a certain version. 

The discussed approach is as follows:
* have one common asciidoc where known issues are collected
* per release note version, pull in the existing known issues from the common file

**Comment by colleenmcginnis** [comment]
👋  @simitt are there existing known issues documented elsewhere that I can pull from or should a create an empty page for now that the team can add to as needed?

**Comment by simitt** [comment]
An empty page to start with sounds good; I think we'll need to go through a couple of different sources to pull the Known Issues together.
