### ISSUE TITLE
Fix smoke tests for apm-server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#11281]
Smoke tests are currently failing with these issues:

### 8.8 OS smoke tests:
```
Error: importing EC2 Key Pair (provisioner_key): InvalidKeyPair.Duplicate: The keypair already exists
	status code: 400, request id: 54f2e2b3-388c-4195-b3f0-c772a930dbbe
```

### 8.9 OS smoke tests:
```
-> Asserting logs-apm.error-* contains expected documents documents...
Didn't find 1 indexed documents error.id=9876543210abcdeffedcba0123456789, total hits 0
{"took":0,"timed_out":false,"_shards":{"total":0,"successful":0,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":0.0,"hits":[]}}
```

### ESS basic-upgrade-for-latest:
```
-> Sending events to APM Server...
{"ok":false,"message":"The instance rejected the connection."}
```

### ESS legacy-standalone-major-managed-for 7.17

```
-> Sending events to APM Server...
{"ok":false,"message":"The instance rejected the connection."}
```

**Comment by kruskall** [comment]
> 8.8 OS smoke tests:

I've backported https://github.com/elastic/apm-server/pull/11285 to 8.8. This is so that we can use https://github.com/elastic/apm-server/pull/10829 correctly.

> 8.9 OS smoke tests:

I'm still investigating


> ESS basic-upgrade-for-latest:

I think this is not an issue with APM Server. I rerun the tests and they passed


> ESS legacy-standalone-major-managed-for 7.17

Same as above

**Comment by kruskall** [comment]
Ok, I think both 8.8 and 8.9 should be fixed.

8.9 is failing because there is no 8.9.1-SNAPSHOT available on cloud yet.

As for the 7.17 smoke tests:

I think these are just flaky tests, there's no error on our end. Restarting them seems to fix it.

**Comment by simitt** [comment]
Great! Thanks for the fixes.
