### ISSUE TITLE
CI: skip Slack notifications for manually triggered benchmarks

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#11293]
The benchmarks job posts notifications to Slack both on failure and success: https://github.com/elastic/apm-server/blob/2a2cdc390585f38fcc76ba5e7e09cf15a0e02c15/.github/workflows/benchmarks.yml#L130-L141

The intention is to post nightly benchmark results. We also support triggering benchmarks using `workflow_dispatch`. To avoid confusion, these should not notify Slack.

**Comment by tungbq** [comment]
Can I work on this task? I've proposed a change in #11296 to resolve the issue

**Comment by axw** [comment]
@tungbq certainly! Thank you for the PR.
