### ISSUE TITLE
Log when aggregation overflow happens

### ISSUE THREAD

**Issue by carsonip** [elastic/apm-server#11362]
As we switch our aggregation implementation in #11117, ensure that on overflows, there are logs so that it is visible to users.

This is the existing behavior for txmetrics, service destination metrics, service summary metrics (but not service tx metrics), with a message of `%s Service limit of %d reached, new metric documents will be grouped under a dedicated overflow bucket identified by service name '%s`

**Comment by simitt** [comment]
+1 on adding proper logs (within `8.10`). Given that the logging happens in the `apm-aggregation` library we should ensure that the logs contain the meta information for which deployment the limits are reached.

**Comment by axw** [comment]
Closed by https://github.com/elastic/apm-server/pull/11392
