### ISSUE TITLE
Package Build change since v8.5.0 broken internal repository sync

### ISSUE THREAD

**Issue by yakhatape** [elastic/apm-server#11367]
Hi guys, 

I've identify an issue on our internal repository during sync and import package/metadata into database for specific package : 

2023/08/09 11:54:04 +02:00   Downloading packages:
2023/08/09 11:54:06 +02:00     1/13 : apm-server-8.6.1-x86_64.rpm
2023/08/09 11:54:07 +02:00     2/13 : apm-server-8.5.3-x86_64.rpm
2023/08/09 11:54:08 +02:00     3/13 : apm-server-8.8.2-x86_64.rpm
2023/08/09 11:54:08 +02:00     4/13 : apm-server-8.5.1-x86_64.rpm
2023/08/09 11:54:08 +02:00     5/13 : apm-server-8.8.0-x86_64.rpm
2023/08/09 11:54:09 +02:00     6/13 : apm-server-8.5.2-x86_64.rpm
2023/08/09 11:54:09 +02:00     7/13 : apm-server-8.7.1-x86_64.rpm
2023/08/09 11:54:09 +02:00     8/13 : apm-server-8.6.2-x86_64.rpm
2023/08/09 11:54:10 +02:00     9/13 : apm-server-8.7.0-x86_64.rpm
2023/08/09 11:54:10 +02:00     10/13 : apm-server-8.8.1-x86_64.rpm
2023/08/09 11:54:10 +02:00     11/13 : apm-server-8.5.0-x86_64.rpm
2023/08/09 11:54:12 +02:00     12/13 : apm-server-8.9.0-x86_64.rpm
2023/08/09 11:54:14 +02:00     13/13 : apm-server-8.6.0-x86_64.rpm

Our server is able to download package, but we are facing an issue when the tools try to import it into database (we are using spacewalk for moment) : 
2023/08/09 11:54:14 +02:00   Importing packages to DB:
2023/08/09 11:54:14 +02:00 list index out of range
2023/08/09 11:54:14 +02:00 list index out of range
2023/08/09 11:54:14 +02:00 list index out of range
2023/08/09 11:54:15 +02:00 list index out of range
2023/08/09 11:54:15 +02:00 list index out of range
2023/08/09 11:54:15 +02:00 list index out of range
2023/08/09 11:54:15 +02:00 list index out of range
2023/08/09 11:54:15 +02:00 list index out of range
2023/08/09 11:54:15 +02:00 list index out of range
2023/08/09 11:54:15 +02:00 list index out of range
2023/08/09 11:54:16 +02:00 list index out of range
2023/08/09 11:54:16 +02:00 list index out of range
2023/08/09 11:54:16 +02:00 list index out of range

I've make a purge on our side like this : 
Check Package/metadata in database not anymore present on Filesystem and delete it => Done 
Check Package on Filesystem not anymore present on database and delete it => Done

Retry the Sync .. => same error for apm-server package > v8.5.0.
But we haven't the problem for package =< v8.4.3-1
And we haven't the problem for our repository elk v7.x

I've download RPM of v8.4.3-1 and v8.5.0 and I've identify a change into the cpio directory structure : 
![image](https://github.com/elastic/apm-server/assets/9256016/8f88fd80-79e9-4e75-b226-102abd0121ee)

Can you help me to be in same situation as before v8.5.0 ?
Thanks in advance for your help

**Comment by yakhatape** [comment]
Isn't in link with this change done between September 2022 and November 2022 @axw ?

**Comment by yakhatape** [comment]
Looks like the FILEDEVICE FLAG is missing for RPM >=8.5.0

rpm apm-server-8.4.3,  device is 1 
rpm -q --qf '[%-15{=NAME} %-36{FILENAMES} %{FILEMODES:perms} %{FILEDEVICES}\n]' -p apm-server-8.4.3-x86_64.rpm warning: apm-server-8.4.3-x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY apm-server /etc/apm-server/apm-server.yml -rw------- 1 apm-server /lib/systemd/system/apm-server.service -rw-r--r-- 1 apm-server /usr/bin/apm-server -rwxr-xr-x 1 apm-server /usr/share/apm-server/.build_hash.txt -rw-r--r-- 1 apm-server /usr/share/apm-server/LICENSE.txt -rw-r--r-- 1 apm-server /usr/share/apm-server/NOTICE.txt -rw-r--r-- 1 apm-server /usr/share/apm-server/README.md -rw-r--r-- 1 apm-server /usr/share/apm-server/bin/apm-server -rwxr-xr-x 1 apm-server /usr/share/apm-server/bin/java-attacher.jar -rw-r--r-- 1 apm-server /var/log/apm-server drwxr-x--- 1 


rpm apm-server-8.5.0  device is (none) 
rpm -q --qf '[%-15{=NAME} %-36{FILENAMES} %{FILEMODES:perms} %{FILEDEVICES}\n]' -p apm-server-8.5.0-x86_64.rpm warning: apm-server-8.5.0-x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY apm-server /etc/apm-server/apm-server.yml -rw------- (none) apm-server /lib/systemd/system/apm-server.service -rwxr-xr-x (none) apm-server /usr/bin/apm-server -rwxr-xr-x (none) apm-server /usr/share/apm-server/.build_hash.txt -rw-r--r-- (none) apm-server /usr/share/apm-server/LICENSE.txt -rw-r--r-- (none) apm-server /usr/share/apm-server/NOTICE.txt -rw-r--r-- (none) apm-server /usr/share/apm-server/bin/apm-server -rwxr-xr-x (none) apm-server /usr/share/apm-server/java-attacher.jar -rw-r--r-- (none) apm-server /var/lib/apm-server drwxr-xr-x (none) apm-server /var/log/apm-server drwxr-xr-x (none)

**Comment by axw** [comment]
> Isn't in link with this change done between September 2022 and November 2022 @axw ?

This is most likely related to https://github.com/elastic/apm-server/pull/8732

**Comment by kruskall** [comment]
Thank you for the investigation! :bow: 

Closing this as you pointed out, it's not an issue with apm-server.
