### ISSUE TITLE
Tail-based sampling discards all traces when sampling rate and throughput are low

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#11372]
**APM Server version** (`apm-server version`): 8.9.0

**Description of the problem including expected versus actual behavior**:

Let's say we have a service that produces 4 transactions per minute, and we have configured tail-based sampling with a rate of 0.1. Roughly speaking, we calculate the desired number of traces as `sample_rate * ingest_rate`, rounding half away from zero. In this case, that would be 4*0.1=0.4 -- so the desired total number of traces is calculated as zero.

Even at low throughput we should be using random sampling. In the above scenario there should be a 10% chance of capturing any one trace. That may still lead to infrequently captured traces -- users can then address this by adding more specific sampling policies with higher sampling rates for their low-throughput services.

**Steps to reproduce**:

 1. Send 4 transactions every minute to apm-server
 2. Configure TBS with a single policy with a sample rate of 0.1
 3. Observe that no trace events are even indexed

Sample event generator:

```go
package main

import (
        "time"

        "go.elastic.co/apm/v2"
)

func main() {
        tracer := apm.DefaultTracer()
        defer tracer.Flush(nil)

        ticker := time.NewTicker(time.Minute)
        for range ticker.C {
                for i := 0; i < 4; i++ {
                        tx := tracer.StartTransaction("name", "type")
                        tx.Duration = time.Duration(i+1) * time.Second
                        tx.End()
                }
        }
}
```

**Comment by carsonip** [comment]
> APM Server version (apm-server version): 8.9.0

Is this only affecting 8.9 or potentially more versions?

**Comment by axw** [comment]
@carsonip yup, sorry, that was just the version that I verified the issue in - it has been an issue since TBS was first introduced (!)

**Comment by simitt** [comment]
>.. rounding half away from zero. In this case, that would be 4*0.1=0.4 -- so the desired total number of traces is calculated as zero.
>
>Even at low throughput we should be using random sampling. In the above scenario there should be a 10% chance of capturing any one trace.

@axw, as a fix for this issue, would it make sense to set `1` as a min value for the desired total number of traces if the applicable sampling rate is `> 0.0`? I believe this would lead to always sampling the first observed trace, but maybe that is acceptable?

**Comment by axw** [comment]
@simitt that wouldn't be strictly true to the configured sampling ratio, but at worst it would be an extra trace per minute (per sampling group). I think the simplicity would be worth the amount of error for low throughput traces.

Generalising: we could take the [ceiling](https://pkg.go.dev/math#Ceil) of the desired total, rather than rounding. e.g. if the desired total were 99.3, then we we would index 100 traces.
