### ISSUE TITLE
@timestamp gets parsed as string (keyword) in 6.3.0

### ISSUE THREAD

**Issue by myoung34** [elastic/apm-server#1138]
After much fighting Ive downgraded to 6.2.3

I think the culprit is [this](https://github.com/elastic/apm-server/pull/819/files)

If I upgrade APM to 6.3.0, i get (in kibana): im `Discover: Field [@timestamp] of type [keyword] does not support custom time zones` 

The kibana index shows `keyword` for the mapping type on `@timestamp` which causes me not to be able to view any data despite the data being valid:

```
$ curl -s -u '' https://es.redact.com:9200/apm-*/_search | jq . | head -n 27
{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 435,
    "max_score": 1,
    "hits": [
      {
        "_index": "apm-6.3.0-2018.07.17",
        "_type": "doc",
        "_id": "qc7GpWQB0RZNVzye-G9P",
        "_score": 1,
        "_source": {
          "@timestamp": "2018-07-17T01:07:10.150Z",
```

if i run `apm-server setup` when no data is present, it sets up the kibana index for `@timestamp` as date, but none of the dashboards work.

If I run `apm-server setup` after some data has been ingested, the index already exists (because apm-server created it before `setup` with type: `keyword`: ss [here](https://imgur.com/a/THXntyq)

I downgraded back to 6.2.3 (ES/logstash/Kibana are all 6.3.0) and it worked perfectly out of the box.

**Comment by simitt** [comment]
Hi @myoung34, sorry to hear you are having troubles with upgrading. 
After checking a couple of combinations we were not able to reproduce the issue, especially producing a Kibana index pattern that has type `keyword` for `@timestamp`. 
Could you please provide some more details, e.g.
* you are mentioning logstash - are you using it in combination with APM Server?
* the screenshot you provided shows 93 fields in the Kibana index pattern, which is less than expected. Can you ensure that `apm-server setup` worked as expected?
* which agent are you using and in which version?
* did you try to remove the `Kibana index pattern` (not data) and run `apm-server setup` again?
* could you provide details about the created Elasticsearch template?

**Comment by myoung34** [comment]
Im not sure what was going on before. I re-did this a few times bumping from 6.2.3 to 6.3.0 and it seems to be going fine now.

**Comment by myoung34** [comment]
If I delete the new 6.3.0 index:

```
$ curl -s -u 'redact' https://es.redact.com:9200/_cat/indices | grep -E 'apm.*07.30'
green open apm-6.3.0-2018.07.30        599Kxm-VR2uJ3MCuCgBVWQ 5 1    2109  0    9.1mb    4.5mb
green open apm-6.2.3-2018.07.30        6Ha_cc0FRQyFRlVIebFrAQ 1 1   29723  0   79.4mb   47.6mb

$ curl -XDELETE -s -u 'redact' https://es.redact.com:9200/apm-6.3.0-2018.07.30
{"acknowledged":true}

```

And refresh the kibana index:

![](https://imgur.com/jCKc5iX.png)

I can view shards again (you can see the obvious emptiness of 6.3.0)

![](https://imgur.com/MWunxmQ.png)

And life is good again.

This happens every single time moving from 6.2.3 to 6.3.0

New logs for 6.2.3 just in case:

```
INFO    instance/beat.go:468    Home path: [/] Config path: [/] Data path: [//data] Logs path: [//logs]
INFO    instance/beat.go:475    Beat UUID: cda7303a-ee2d-4a92-ad39-c596272287c7
INFO    instance/beat.go:213    Setup Beat: apm-server; Version: 6.2.3
INFO    elasticsearch/client.go:145     Elasticsearch url: https://es.redact.com:9200
INFO    pipeline/module.go:76   Beat name: ip-10-0-3-52.ec2.internal
INFO    instance/beat.go:301    apm-server start running.
INFO    beater/handlers.go:80   Path /healthcheck added to request handler
INFO    beater/handlers.go:80   Path /v1/client-side/sourcemaps added to request handler
INFO    beater/handlers.go:80   Path /v1/transactions added to request handler
INFO    beater/handlers.go:80   Path /v1/client-side/transactions added to request handler
INFO    beater/handlers.go:80   Path /v1/errors added to request handler
INFO    beater/handlers.go:80   Path /v1/client-side/errors added to request handler
INFO    beater/server.go:28     Starting apm-server! Hit CTRL-C to stop it.
INFO    beater/server.go:29     Listening on: 0.0.0.0:8200
INFO    beater/server.go:34     Frontend endpoints disabled
INFO    [monitoring]    log/log.go:97   Starting metrics logging every 30s
INFO    [request]       beater/handlers.go:150  handled request {"request_id": "2f9e1628-f134-483c-a392-bf7b854e7099", "response_code": 200, "method": "GET", "URL": "/healthcheck", "content_length": 0, "remote_address": "127.0.0.1", "user_agent": "Go-http-client/1.1"} 
INFO    beater/client.go:32     HTTP Server ready
INFO    beater/onboarding.go:19 Publishing onboarding document
INFO    elasticsearch/client.go:690     Connected to Elasticsearch version 6.3.0
INFO    template/load.go:73     Template already exists and will not be overwritten.
INFO    [request]       beater/handlers.go:150  handled request {"request_id": "3e899f4d-4186-4499-bf84-dde0323c3e11", "response_code": 200, "method": "GET", "URL": "/healthcheck", "content_length": 0, "remote_address": "10.0.3.4", "user_agent": "ELB-HealthChecker/2.0"}
```

**Comment by myoung34** [comment]
Heres the ES `/_template` for `apm-6.3.0`:

https://gist.github.com/myoung34/ea74a29b398a6a0d44103bef833e9c7b

**Comment by graphaelli** [comment]
@myoung34 Something appears to be off with your 6.3.0 version - `transaction.marks.navigationTiming.*` won't be available until the next release and many fields are missing.

I suggest verifying your 6.3 build (6.3.2 is out now) and removing the existing 6.3.0 template (`DELETE http://localhost:9200/_template/apm-6.3.0`) before trying again - you should see `Elasticsearch template with name 'apm-6.3.0' loaded` logged.  Your templates should look like: https://gist.github.com/graphaelli/748c7603220910944cfc5a47e9f715a4 if using the default configuration.

**Comment by myoung34** [comment]
@graphaelli that got me part of the way
Theres no longer a `conflict` on @timestamp and I got:

```
INFO    instance/beat.go:225    Setup Beat: apm-server; Version: 6.3.0
INFO    elasticsearch/client.go:145     Elasticsearch url: https://es.redact.com:9200
INFO    pipeline/module.go:81   Beat name: ip-10-0-3-49.ec2.internal
INFO    instance/beat.go:315    apm-server start running.
INFO    [beater]        beater/beater.go:75     host resolved from 0.0.0.0:8200 to [::]:8200
INFO    [handler]       beater/handlers.go:134  Path /v1/client-side/errors added to request handler
INFO    [handler]       beater/handlers.go:134  Path /healthcheck added to request handler
INFO    [handler]       beater/handlers.go:134  Path /v1/client-side/sourcemaps added to request handler
INFO    [handler]       beater/handlers.go:134  Path /v1/transactions added to request handler
INFO    [handler]       beater/handlers.go:134  Path /v1/client-side/transactions added to request handler
INFO    [handler]       beater/handlers.go:134  Path /v1/errors added to request handler
INFO    [server]        beater/server.go:30     Starting apm-server [ built 2018-07-30 12:34:32 +0000 UTC]. Hit CTRL-C to stop it. 
INFO    [server]        beater/server.go:31     Listening on: [::]:8200
INFO    [server]        beater/server.go:36     Frontend endpoints disabled
INFO    [monitoring]    log/log.go:97   Starting metrics logging every 30s 
INFO    [request]       beater/handlers.go:239  handled request {"request_id": "9b6e4aa7-9719-4f21-8bb4-15ed05193757", "method": "GET", "URL": "/healthcheck", "content_length": 0, "remote_address": "127.0.0.1", "user-agent": "Go-http-client/1.1", "response_code": 200}
INFO    [http_client]   beater/client.go:32     HTTP Server ready
INFO    [onboarding]    beater/onboarding.go:19 Publishing onboarding document
INFO    elasticsearch/client.go:690     Connected to Elasticsearch version 6.3.0
INFO    template/load.go:55     Loading template for Elasticsearch version: 6.3.0
INFO    template/load.go:89     Elasticsearch template with name 'apm-6.3.0' loaded
INFO    [request]       beater/handlers.go:239  handled request {"request_id": "77176328-d3a5-4231-a61f-f34ff253e5ae", "method": "GET", "URL": "/healthcheck", "content_length": 0, "remote_address": "10.0.3.4", "user-agent": "ELB-HealthChecker/2.0", "response_code": 200}

```

So it did load it.

So I think what happened was: 

I got `fields.yml` from [here](https://github.com/elastic/apm-server/blob/master/processor/transaction/_meta/fields.yml) (404 now) which was likely for 6.3.2 and loaded it as 6.3.0 and it kept propagating the error.

So I pulled fields.yml from the 6.3 branch [here]($ wget https://raw.githubusercontent.com/elastic/apm-server/6.3/processor/transaction/_meta/fields.yml)

But now Im getting a different error and still getting shards failed:

```
[2018-07-30T17:15:58,116][INFO ][o.e.c.m.MetaDataMappingService] [ip-10-0-3-47] [apm-6.3.0-2018.07.30/d44z-bp1SwKN3RsMYNtO5g] update_mapping [doc]                                       
[2018-07-30T17:16:24,319][DEBUG][o.e.a.b.TransportShardBulkAction] [logstash-2018.07.30][1] failed to execute bulk item (index) BulkShardRequest [[logstash-2018.07.30][1]] containing [index {[logstash-2018.07.30][doc][A9Qw7GQBxf8Tjflx429-], source[{"prospector":{"type":"log"},"source":"/var/log/secure","offset":2427,"@version":"1","message":"Jul 30 17:16:21 ip-10-0-3-47 sudo:     marc : TTY=pts/0 ; PWD=/home/marc ; USER=root ; COMMAND=/usr/bin/tail -f /var/log/elasticsearch/foo.log","host":{"name":"ip-10-0-3-47"},"beat":{"hostname":"ip-10-0-3-47","name":"ip-10-0-3-47","version":"6.3.0"},"fields":{"ec2":{"tags":{"managed_by":"terraform","name":"elasticsearch","environment":"operations"}},"env":"operations","s3_prefix":"syslog","class":"logstash","tags":["syslog","elasticsearch"]},"@timestamp":"2018-07-30T17:16:23.478Z","input":{"type":"log"},"meta":{"cloud":{"provider":"ec2","machine_type":"i3.large","availability_zone":"us-east-1a","region":"us-east-1","instance_id":"i-0caddc6879b547100"}},"tags":["beats_input_codec_plain_applied"]}]}]                                                                 
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [host]                                                              
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:302) ~[elasticsearch-6.3.0.jar:6.3.0]                                                                      
                at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:481) ~[elasticsearch-6.3.0.jar:6.3.0]                                
                        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:496) ~[elasticsearch-6.3.0.jar:6.3.0] 
```

Im aware that [hosts was removed from elasticsearch 6.3](https://discuss.elastic.co/t/my-metricbeats-stopped-working-after-the-latest-ugprade-and-i-have-errors-on-mapping-6-3-0/137158/2) or at least has conflicts.

Whats the resolution for this one? The fix to logstash was easy:

```
  mutate {
    remove_field => [ "type" ]
    remove_field => [ "[host]" ]
  }
  mutate {
    add_field => {
        "host" => "%{[beat][hostname]}"
    }   
  }
```

Also: it seems that keeping fields.yml and loading it is part of my problem (its gone from master branch). Whats the proper way of doing it vs what I have:

Dockerfile:

```
  COPY --from=builder $APM_SERVER_PATH/apm-server /usr/bin/
  COPY apm-server.yml /etc/apm-server/apm-server.yml
  COPY fields.yml /etc/apm-server/fields.yml
```

and `apm-server.yml`: 

```
setup:
  template:
    fields: /etc/apm-server/fields.yml
```

**Comment by graphaelli** [comment]
Ah, that explains a lot.  [This](https://raw.githubusercontent.com/elastic/apm-server/6.3/processor/transaction/_meta/fields.yml) is only one part of what ends up in the fields.yml normally distributed with apm-server - it's actually generated at build time from a bunch of inputs.

If you prefer to build your own apm-server image from source, you should `make update` and copy the `fields.yml` that is generated, `from=builder` per your example.  You need python to run `make update` - if that's an issue you could choose to copy fields.yml from the official Elastic docker container images, like:

```
FROM docker.elastic.co/apm/apm-server:6.3.2 as apm
...
FROM scratch
COPY --from=apm /usr/share/apm-server/fields.yml /etc/apm-server/fields.yml
```

**Comment by myoung34** [comment]
@graphaelli 

That got me working. Thanks!

I didnt realize fields was generated from the docs

**Comment by graphaelli** [comment]
glad to hear it!
