### ISSUE TITLE
Consider return a response body with meaningful data for all apm-server requests

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1140]
Right now we just return `202 - Accepted`, we could start returning a json response that opens the door for meaningful data... eg:
https://github.com/elastic/apm-server/issues/1128#issuecomment-405306365

More fancy: also return current number of items in the queue, memory pressure, things like that.

**Comment by watson** [comment]
I like the idea as it's nice for debugging purposes, but I would prefer if it's optional - e.g. if it can be switched on using a query param or something. If it's returned all the time it will add a processing overhead to the agents.

**Comment by graphaelli** [comment]
Agreed, optional sounds reasonable.  Adding support for this in #957 so it should be available for experimentation shortly.

**Comment by jalvz** [comment]
Since this is an enhancement for another team, I'll close this until there is a real need for it. If so, feel free to reopen with what info agents would like, desired behaviour, etc.
