### ISSUE TITLE
[APM] Add Release notes to docs

### ISSUE THREAD

**Issue by makwarth** [elastic/apm-server#1153]
I'd like to add a Release notes page to our docs, similar to those of [ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html). We already have releases notes for the server and each agent, but we should give users a quick overview of each APM release in its entirety. I don't think the release notes will be more than 4-5 bullets per release.

I propose this docs structure:

- APM
  - _APM overview_
    -  _Release notes_
       - _6.4_
  - APM Server Reference
  - APM Agents

I'm having trouble building the docs, so I would appreciate help with the following:
- Rename "Getting Started with Elastic APM" to "APM overview"
- Add "Release notes" page
- Add "6.4" page under Release notes

I'll update the 6.4 releases notes once the file exists. I'll maintain release notes for future releases.

NB: It doesn't really make sense that the "APM overview" docs live in the `apm-server` repo, but I suggest we just keep them here.

Any thoughts or objections?

**Comment by jalvz** [comment]
@makwarth lmk if we should get back to this

**Comment by jalvz** [comment]
Sure thing, send me the content when you have it

**Comment by makwarth** [comment]
Will do, thanks

**Comment by makwarth** [comment]
@jalvz here's the 6.4 release notes. cc @sqren @simitt @alvarolobato 
Feel free to modify/add. 

-----

# APM version 6.4

## Breaking changes

- In 6.3, we separated APM data into separate indices (`transaction`, `span`, `error`). If you run APM Server 6.2 with Kibana 6.4, the APM UI will not be able to see any APM data. To fix this, use the Kibana APM configuration options to specify the location of the APM index.
- When upgrading to Kibana 6.4, you might need to refresh your APM index pattern for certain APM UI features to work.

## New features

#### APM Server
- Logstash output
- Kafka output

#### APM UI
- Query bar
- Machine Learning integration: Anomaly detection on service response times
- Kibana objects (index pattern, dashboards, etc.) can now be imported via the Kibana setup instuctions

#### APM agents
- RUM is now GA
- Ruby is now GA
- Java is now Beta
- Go is now Beta
- Python added instrumentation for Cassandra, PyODBC and PyMSSQL
- Node.js added instrumentation for Cassandra and broader MySQL support

**Comment by simitt** [comment]
I find the Breaking changes section a bit confusing (although I should know about what was introduced in which version). 
As this describes breaking changes for 6.4 how about something like:

* We previously split APM data into separate indices (transaction, span, error, etc.). In 6.4 APM Kibana UI starts to leverage those separate indices for queries. In case you only update Kibana but run an older version of APM Server you will not be able to see any APM data by default. To fix this, ...

**Comment by makwarth** [comment]
Sounds good @simitt - updated breaking changes copy:

---

- We previously split APM data into separate indices (transaction, span, error, etc.). In 6.4 APM Kibana UI starts to leverage those separate indices for queries. In case you only update Kibana but run an older version of APM Server you will not be able to see any APM data by default. To fix this, use the Kibana APM configuration options to specify the location of the APM index.
- When upgrading to Kibana 6.4, you might need to refresh your APM index pattern for certain APM UI features to work.

**Comment by jalvz** [comment]
done in https://github.com/elastic/apm-server/pull/1280
