### ISSUE TITLE
libbeat output processor storing apmevents past the processor lifetime

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#11563]
**APM Server version** (`apm-server version`):

**Description of the problem including expected versus actual behavior**:

The libbeat output processor is sending `modelpb.Batch`es to a channel for async processing. Because the batch/events are used past the processor lifetime we are using the builtin copy function to create a new slice:

https://github.com/elastic/apm-server/blob/44b352c03a602da9433d4ecf8b12e66743b2eefa/internal/publish/pub.go#L145

This was ok when we had a slice of concrete types but now we have pointers everywhere so the new slice is still going to reference the same pointers.

This issue is not critical because we're creating a new slice and only "storing" the elements (APMEvents) which we're not reusing at the moment.

In the future we might start using the vtpool to reuse protobuf types (https://github.com/elastic/apm-data/issues/130) and this might become more severe.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by carsonip** [comment]
Just adding more info:

In [apm-aggregation processHarvest](https://github.com/elastic/apm-aggregation/blob/main/aggregators/aggregator.go#L578), we are fine with processor mutating CombinedMetrics, although we will return CombinedMetrics to pool, meaning that storing CombinedMetrics past processHarvest lifetime will lead to data corruption. However, in apm-server, we first call `CombinedMetricsToBatch`, if we do not reuse anything from CombinedMetrics, then we should be safe. And I believe that we do not. TLDR: There should be no bugs in our current 8.10 LSM implementation.

@kruskall it may be a good idea to improve the comments in apm-aggregation after double checking on this.
1. Note that if CombinedMetrics needs to be used past the lifetime of processor call, caller should create a deep copy
2.  Note that CombinedMetricsToBatch create Batch from scratch and never reuse anything from CombinedMetrics (though I have a feeling that we should only document when the opposite is true)
