### ISSUE TITLE
Move onboarding document to its own index

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1158]
When APM Server starts it sends an onboarding document to the general APM index of the format `apm-%{[beat.version]}-%{+yyyy.MM.dd}`.

All other documents go to their own indices, that one can specifically query one, e.g. `apm-%{[beat.version]}-error-%{+yyyy.MM.dd}` to query with `apm-*-error-*`. 

We discussed to move the onboarding docs to their own index too, to be able to specifically query for them. 
New index format: `apm-%{[beat.version]}-onboarding-%{+yyyy.MM.dd}`

**Comment by jalvz** [comment]
done here https://github.com/elastic/apm-server/commit/8e2435ae46aaf62d2211f681fa97ba7abfffc844
