### ISSUE TITLE
Update integration package to package spec v3

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#11643]
https://github.com/elastic/package-spec/issues/539

We should also add "apm" (and "observability"?) as a required capability for installing the package. See https://github.com/elastic/package-spec/blob/889754b93f7ee6f48651630dc4315cc59d43ec3b/spec/integration/manifest.spec.yml#L104-L119

**Comment by kyungeunni** [comment]
This is currently blocked by [this ticket](https://github.com/elastic/ingest-dev/issues/2572). For the timebeing, it can be unblocked if the package-spec allows us to specify the mapping definition that has `dynamic` property in the `manifest.yml`, at least until we have the proper fix.

Before migrating, the following mapping was added to the template:
```
  "labels": {
    "type": "object",
    "dynamic": "true"
  },
  "numeric_labels": {
    "type": "object",
    "dynamic": "true"
  },
```
But with the latest version, it doesn't add this but only creates the dynamic_templates and it's causing an error like this:
```
.ds-metrics-apm.transaction.1m-default-2023.10.24-000001' (illegal_state_exception): Missing intermediate object numeric_labels"
```
cc @jsoriano @simitt

**Comment by kyungeunni** [comment]
It's unblocked thanks to the Fleet change: https://github.com/elastic/kibana/pull/169981

**Comment by kyungeunni** [comment]
Mark it as blocked as we are depending on the Kibana snapshot that contains the change

**Comment by kyungeunni** [comment]
https://github.com/elastic/apm-server/pull/11822
