### ISSUE TITLE
Deprecate jaeger protocol

### ISSUE THREAD

**Issue by dmathieu** [elastic/apm-server#11671]
The jaeger protocol has been deprecated by the jaeger project, and they now recommend using OpenTelemetry and OTLP rather than their own clients.
Otel itself has recently removed all jaeger exporters from their specification, and each library.
https://github.com/open-telemetry/opentelemetry-specification/pull/2858

We should also be looking into deprecating and removing our support for the jaeger endpoints in apm-server.

**Comment by simitt** [comment]
In a first step we'll only be able to deprecate, and then afterwards remove.

**Comment by simitt** [comment]
@rubvs looks like this can be closed?
