### ISSUE TITLE
Scale max service destination and max per service service destination aggregations based on available memory

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-server#11721]
Currently, we scale transactions and service transaction groups based on available memory ([ref](https://github.com/elastic/apm-server/blob/c220ed40b6bed913b7d92ed4be10e416aa449e6e/internal/beater/beater.go#L232-L251)). However, we don't do the same for service destination aggregations. The max service destination aggregations default to a constant size of 10_000 ([ref](https://github.com/elastic/apm-server/blob/c220ed40b6bed913b7d92ed4be10e416aa449e6e/internal/beater/config/aggregation.go#L20-L22)).

**Comment by simitt** [comment]
I don't think this was on purpose but rather an oversight, and suggest to label as bug.
