### ISSUE TITLE
nil pointer dereference on nil slice elements

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#11727]
**APM Server version** (`apm-server version`): 8.9+

**Description of the problem including expected versus actual behavior**:

APM data is not properly validation slice elements. Validation is skipped causing nil elements to be accepted.
A specific case can be reproduced that triggers a nil pointer dereference by sending a nil element in the cause slice.

The issue is fixed on main but I'm opening this issue for discussion.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

bug.ndjson:

```json
{"metadata":{"service":{"name":"1234_service-12a3","version":"4.3.0","agent":{"version":"1.10.0","name":"java"}}}}
{"error":{"id":"9876543210abcdeffedcba0123456789","timestamp":1571657444929001,"exception":{"message":"Theusernamerootisunknown","type":"java.net.UnknownHostException","handled":true,"module":"org.springframework.http.client","code":42,"handled":false,"attributes":{"foo":"bar"},"cause":[{"type":"InternalDbError","message":"something wrong writing a file"}, null],"stacktrace":[{"abs_path":"/tmp/AbstractPlainSocketImpl.java","filename":"AbstractPlainSocketImpl.java","function":"connect","vars":{"key":"value"},"pre_context":["line1","line2"],"context_line":"3","library_frame":true,"lineno":3,"module":"java.net","colno":4,"post_context":["line4","line5"]}]}}}
```

 1. tilt up
 2. curl -H 'Content-type: application/x-ndjson' localhost:8200/intake/v2/events --data-binary "@bug.ndjson"
 3. Look at the logs

**Provide logs (if relevant)**:

**Comment by simitt** [comment]
>The issue is fixed on main but I'm opening this issue for discussion.

@kruskall what are you looking for here, as you mentioned that the issue itself is fixed?
