### ISSUE TITLE
ESS snapshot smoketest

### ISSUE THREAD

**Issue by carsonip** [elastic/apm-server#11759]
1. There is no smoketest coverage on ESS APM snapshot currently. Add it back.
2. We have coverage on latest ESS release through basic-upgrade only. We do not test new ESS deployments. Check if that is needed.

**Comment by marclop** [comment]
@carsonip, @simitt  looking at our smoke tests, I can see we're using `SNAPSHOT` builds. Is this issue just outdated?

**Comment by simitt** [comment]
I remember Carson working on some smoke test improvements a while ago, so this might indeed be fixed. Closing for now, if Carson has more to add, we can reopen.
