### ISSUE TITLE
Update logstash docs to object notation for data_stream

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#11917]
Since https://github.com/elastic/apm-data/pull/124 the `apm-server` sends the `data_stream` information in object notation rather than dotted fields. This aligns better with `logstash` expectations. 

Update the [logstash guide](https://www.elastic.co/guide/en/apm/guide/current/logstash-output.html#ls-config-pipeline) to remove the mutate filter as it is not necessary anymore.

**Comment by simitt** [comment]
The docs for previous versions would still contain the section, but the docs since `8.10`, where the behavior changed wouldn't. IMO it'd be more confusing to discuss workarounds in a version where they are not relevant anymore.

**Comment by bmorelli25** [comment]
@colleenmcginnis, sorry for not seeing this earlier. Would've been super easy to add this onto https://github.com/elastic/apm-server/issues/11989.
