### ISSUE TITLE
docs/otel-direct.asciidoc has outdated configuration

### ISSUE THREAD

**Issue by mx-psi** [elastic/apm-server#11998]
The Collector example in https://github.com/elastic/apm-server/blob/8.10/docs/otel-direct.asciidoc is outdated in two ways:

- It uses the `logging` exporter instead of the recommended replacement, the `debug` exporter
- It uses the legacy `${..}` environment variable syntax, instead of the new `${env:...}` syntax

It should be updated to avoid using legacy features

**Comment by axw** [comment]
Thanks for reporting this @mx-psi!

**Comment by axw** [comment]
This has been on pause while some work was happening to centralise docs - will be fixed by https://github.com/elastic/observability-docs/pull/3518
