### ISSUE TITLE
Store universal profiling stacktrace IDs on transactions

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-server#12054]
https://github.com/elastic/apm-data/issues/180 will add the capabiltiy to receive universal profiling stacktrace-IDs for transactions from APM agents. We will need to store those as `counted_keyword` field on the transaction documents.

**Comment by simitt** [comment]
@JonasKunz is it reasonable to assign this task to you, given that you also work on https://github.com/elastic/apm-data/issues/180 or would you prefer this to be covered by the intake-service team?

**Comment by JonasKunz** [comment]
Yes, those two imo are a single feature, which just happens to be spread out across two repos.

**Comment by JonasKunz** [comment]
Unfortunately currently blocked by https://github.com/elastic/package-spec/issues/698.
