### ISSUE TITLE
automate version bumps

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1207]
The version bump process is manual and error prone.  Create a script, one per branch - the process is different on 6.3 vs newer versions - to automate the updates needed for a version bump:

* [ ] create release notes for patches
* [ ] update _beats/dev-tools/packer/version.yml (only 6.3?)
* [ ] update `:stack-version` in docs/version.asciidoc
* [ ] update `vendor/github.com/elastic/beats/libbeat/version/version.go`

**Comment by jalvz** [comment]
@graphaelli I think the process here improved particularly since docs team is taking care of the docs process (that is to say: since we have a docs team). I'll close but feel free to reopen if you think is worth tackling.
