### ISSUE TITLE
Use dynamic: false instead of dynamic: runtime for data streams

### ISSUE THREAD

**Issue by carsonip** [elastic/apm-server#12097]
In #10968 we set dynamic: runtime on internal metrics, all aggregated metrics, and TBS metrics. Out of all, internal metrics and all aggregated metrics are actually using synthetic source, meaning that the extra fields will not be indexed anyway. There is no value in creating a runtime field for a field that is not indexed. Consider moving to dynamic: false, as well as consider the case of TBS metrics because it does not use synthetic source.

Using dynamic runtime has caused issues for upgrades to 8.11.0 and 8.11.1: #12103

**Comment by axw** [comment]
As of 8.15 we will no longer use `dynamic: runtime` -- we're not setting this in the apm-data plugin.
