### ISSUE TITLE
Limit sourcemap file size

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1220]

**Comment by alvarolobato** [comment]
@jalvz can you give us some more details about the reason to do this?

**Comment by simitt** [comment]
Source map upload can be password secured, so I don't think this is a hard requirement. However, one could see it as additional security step in case no password is used, or as making the server more resilient against bugs in deploy scripts etc. 
If we limit this, it should be a config setting and no hardcoded limit.
