### ISSUE TITLE
add more golang metrics to index template

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1229]
As discovered in https://github.com/elastic/apm-agent-go/issues/153, gc metrics are not included in the apm metrics index template.  Consider adding all of the missing ones, but at least those for `gc`.

**Comment by alvarolobato** [comment]
Does this still make sense or we should review all the agent metrics together?

**Comment by graphaelli** [comment]
Let's review them together even though I feel these are among the core metrics for go. This hasn't been started yet because it's not clear how we'd like to distribute either the index template or the dashboards for this - users could accomplish this on their own right now but it would take a bit of effort and is not currently documented.

**Comment by graphaelli** [comment]
On second thought, let's revisit as part of the agent metrics review.
