### ISSUE TITLE
nc: connect to host1 port 8200 (tcp) failed: Connection refused while success on host2

### ISSUE THREAD

**Issue by patpatpat123** [elastic/apm-server#12321]
Hello team,

I would like to report an issue using apm server.

For the setup, I have two different hosts. By host here, I am referring to two different hardware. For later, I am going to call the first hardware host1, and the second hardware host2.

While installing elastic + apm server, version 8.11.3, using this link https://www.elastic.co/downloads/apm

I then start elasticsearch with security disabled (I do understand the risk of disabling security) and then start apm server using the command ```./apm-server -e``` on host1

I then run nc -zv directly within host1, and get a success on port 8200.

However, when using another host2 (host where the application supposed to send traces to apm server) is trying to connect to apm server, I am always getting connection refused.

Running nc -zv from host2 (application) to host1 (apm), I am always getting nc: connect to host1 port 8200 (tcp) failed: Connection refused

While, from within host1, port 8200 seems to be up.

Hence, I would like to report this issue, it seems application needs to reside within the same host as apm server, which is quite a drawback.

Thank you

**Comment by simitt** [comment]
@patpatpat123 this is not a confirmed bug, please open a topic in the [discuss forum](https://discuss.elastic.co/c/observability/apm/58) instead.
