### ISSUE TITLE
docs: changelogs and compatibility matrix to reflect a bugfix that can lead to missing metrics

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#12401]
https://github.com/elastic/apm-data/pull/157 fixed a bug in the apm-server where a validation was not properly applied. Before the fix, empty metricset values were accepted by the apm-server, although they should have been rejected. The fix was released in `8.11.0`. 
The apm-java-agent had been sending empty histogram metricsets for micrometer up until version `1.42`, and fixed the bug on the agent side in `1.43.0`. 

The fixes impact users of the java agent in a version `<1.43.0`, where empty micrometer histogram metrics would be recorded. The docs need to be updated accordingly for visibility before upgrading the server. 

1. `8.11` release notes should contain a note that the validation was fixed, requiring users to upgrade to java agent version `>= 1.43.0` if they are collecting micrometer or custom metrics with potentially empty .
2. Update the https://www.elastic.co/guide/en/apm/guide/8.11/known-issues.html section with a note
3. Update the https://www.elastic.co/guide/en/apm/guide/current/agent-server-compatibility.html compatibility matrix with a * annotation explaining the edge case where the agent is not compatible with the server

**Comment by colleenmcginnis** [comment]
@simitt there's a draft PR up here: https://github.com/elastic/observability-docs/pull/3591. Can you take a look?
