### ISSUE TITLE
How to handle spans starting after transaction is already finished. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1242]
Is there a way of detecting spans that were started after the trace/transaction has been finished, in the server? Is it  necessary to detect? 
Figure out possible implications for @elastic/apm-ui .

**Comment by simitt** [comment]
@elastic/apm-ui can you figure out a way to handle `spans` that started after a `transaction` already finished? I don't think there is a straight forward way to handle this in the Server.

**Comment by sqren** [comment]
Will the spans still be attached to the finished transaction with `transaction.id`? In that case we already visualize them. 

It should be possible to handle. Do we still want to draw them, or should we hide them and warn the user that something in their setup is off?

**Comment by simitt** [comment]
As long as the @elastic/apm-agent-devs set the `transaction.id` we will store it.

**Comment by sqren** [comment]
Cool! 
I'm still not sure exactly how to handle this, since I don't know if spans outside a transaction should be treated like an error in the setup, or expected behaviour.

**Comment by formgeist** [comment]
We could possibly also go over this tomorrow (along with https://github.com/elastic/apm-server/issues/1241)

**Comment by simitt** [comment]
The trace view will cover the duration from the first to the last span. This will be handled in the UI.

**Comment by simitt** [comment]
No action from the APM Server, so closing this issue.
