### ISSUE TITLE
tbs code not setting entry TTL 

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#12449]
**APM Server version** (`apm-server version`): 

**Description of the problem including expected versus actual behavior**:

TBS code is setting the entry without the TTL: https://github.com/elastic/apm-server/blob/03ec4426b2afffb789f03dd3abaa3846928d801c/x-pack/apm-server/sampling/eventstorage/storage.go#L209

This was spotted during the bugfix in https://github.com/elastic/apm-server/pull/12120#discussion_r1450628513 but was kept as is. We should investigate whether this is a bug.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by carsonip** [comment]
This only affects cases where `badger.ErrTxnTooBig` happens. Nevertheless this is concerning.
