### ISSUE TITLE
Deployment of APM server in kuberetes

### ISSUE THREAD

**Issue by Narenlogi** [elastic/apm-server#1244]
I did not find any documentation on how to deploy the APM sever in Kubernetes environment. I recently created a deployment doc in my organisation. Can I contribute the same for this project.

**Comment by roncohen** [comment]
Hi @Narenlogi. 

Sorry for the slow reply here. We're currently investigating the right way forward here. I'll keep this issue open to track any progress we make.

**Comment by nchudleigh** [comment]
In the same boat here just got up and running, have some config that would be valuable to share.

**Comment by roncohen** [comment]
hey! I've created this issue in our helm charts repo to track this request: https://github.com/elastic/helm-charts/issues/68
I'll close this issue in the mean time. Feel free to re-open if you feel it's appropriate.
