### ISSUE TITLE
Fix Windows tests

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1248]
Windows system tests are not running, report is still success. 

eg: https://apm-ci.elastic.co/job/elastic+apm-server+master+multijob-windows/beat=apm-server,label=windows/225/console
```
09:08:51 nosetests : The term 'nosetests' is not recognized as the name of a cmdlet, function, script file, or operable 
09:08:51 program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
09:08:51 At C:\Users\jenkins\workspace\elastic+apm-server+master+multijob-windows\beat\apm-server\label\windows\src\github.com\e
09:08:51 lastic\apm-server\script\jenkins\ci.ps1:48 char:8
```

We should also reuse as much as possible Beats scripting code, to get all changes on building fields, etc.

That is done in https://github.com/elastic/apm-server/pull/1247 for the other tests, but for windows is  more complicated.

**Comment by alvarolobato** [comment]
We will check if 6.4 is also affected and decide priority accordingly
