### ISSUE TITLE
docs: release notes to reflect breaking change for ingest pipelines

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#12498]
Add a breaking change section to the release notes in `8.12`, reflecting what is explained in https://github.com/elastic/ingest-docs/pull/851/files

**Comment by carsonip** [comment]
Perhaps we should also update known issues: https://www.elastic.co/guide/en/observability/8.12/known-issues.html as well as stating the (planned) fix version?

**Comment by carsonip** [comment]
Closing via https://github.com/elastic/apm-server/pull/12556 and https://github.com/elastic/observability-docs/pull/3597
