### ISSUE TITLE
ea-managed apm-server smoke test fails

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#12510]
**APM Server version** (`apm-server version`): main (8.13.0)

**Description of the problem including expected versus actual behavior**:

Smoke test at https://github.com/elastic/apm-server/tree/main/testing/smoke/managed fails because the terraform script is not able to download Elastic Agent when provisioning the infrastructure.
The script to download elastic agent is available at https://github.com/elastic/apm-server/blob/main/testing/infra/terraform/modules/standalone_apm_server/latest_elastic_agent.sh
At some point the "elastic-agent" project was removed from the artifact API and split into two projects.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. run smoketest

**Provide logs (if relevant)**:

**Comment by marclop** [comment]
I'll take care of this since I'm on SDH duty

**Comment by marclop** [comment]
https://github.com/elastic/apm-server/pull/12530 should fix the `8.12` smoke tests.

**Comment by simitt** [comment]
Smoke tests are still failing
