### ISSUE TITLE
Global context values override local transaction context values

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1255]
As shown in [the tests](https://github.com/elastic/apm-server/blob/master/model/context_test.go#L108-L111), context from the top level values currently override any local values. Local values should take precedence.

**Comment by alvarolobato** [comment]
Related https://github.com/elastic/apm-server/issues/1175

**Comment by jalvz** [comment]
@simitt can we close this now?

**Comment by alvarolobato** [comment]
This is probably fixed, needs checking.

**Comment by simitt** [comment]
Just checked, the `user` is currently the only object that can be set in the `metadata` as well as per event. When merging the user the one sent with the event has precedence of the one sent with the metadata. So this issue can be closed.
