### ISSUE TITLE
dev/test dependencies included in the final binary

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#12580]
**APM Server version** (`apm-server version`): https://github.com/elastic/apm-server/commit/90b9ac565126e03b694f2144788b2520c90412a4

**Description of the problem including expected versus actual behavior**:

Dev/Test dependencies are included in the finaly binary. We should investigate why this is happening and possible solution

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. make apm-server
 2. `strings apm-server | grep testify` is not empty

**Provide logs (if relevant)**:

```
$ strings apm-server | grep testify 
dep     github.com/stretchr/testify     v1.8.4  h1:CcVxjf3Q8PM0mHUKJCdn+eZZtm5yQwehR5yeSVQQcUk=
github.com/stretchr/testify/assert.init
github.com/stretchr/testify@v1.8.4/assert/assertion_compare.go
dep     github.com/stretchr/testify     v1.8.4  h1:CcVxjf3Q8PM0mHUKJCdn+eZZtm5yQwehR5yeSVQQcUk=
```

**Comment by axw** [comment]
`goda graph -std .:all` says it is `libbeat/idxmgmt/lifecycle` -- https://github.com/elastic/beats/pull/37939
