### ISSUE TITLE
Review and update changelog with docappender changes

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#12612]
https://github.com/elastic/go-docappender was bumped but the last version was over a month old

We should review the changes and update the changelog accordingly.

PR bump: https://github.com/elastic/apm-server/pull/12604

**Comment by carsonip** [comment]
There was another bump in https://github.com/elastic/apm-server/pull/12179 backported to 8.12
- https://github.com/elastic/go-docappender/compare/c69a1cf8ce35...44217001fa53
