### ISSUE TITLE
Support APM Server on Amazon Linux 2023

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#12701]
Investigate effort and requirements for supporting APM Server on Amazon Linux 2023. 

Today APM Server is supported on Amazon Linux 2, find a [comparison of AL2 vs. Amazon Linux 2023](https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html).

**Comment by vikmik** [comment]
Works out of the box. I did a quick scan of possible `dlopen` calls on a running APM servers which could be problematic when supporting a new platform, but everything seems to be in order.

Supporting AL2023 should be a no brainer given that it is pretty much the default on AWS, so I added tests for it in #13358

**Comment by simitt** [comment]
>(checking if this needs to be backported. The changes on main don't exactly translate to older versions, though that would be easily addressed)

A backport is not necessary, it can be supported from the next minor version release then. 
cc @chrisdistasio can you consider this in the updates for the support matrix please for the next minor release.
