### ISSUE TITLE
Refactoring / Cleanup apm-server

### ISSUE THREAD

**Issue by ruflin** [elastic/apm-server#128]
This meta issue should help to discuss and track refactorings which we want to do in apm-server to improve the code base. Each person should update and edit the tasks on this list.

* [ ] Improve handler testing
* [ ] Improve server and config handling
* [ ] ...

**Comment by simitt** [comment]
I suggest to close this meta issue, as I think we are at a pretty good stage right now and don't need a specific meta issue for future refatoring. 
What do you think @roncohen , @graphaelli , @jalvz ?
