### ISSUE TITLE
Add geo ip pipeline to default pipeline definitions in APM Server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1283]
Investigate if it makes sense (and implement if so) to add geo-ip pipeline to default pipelines in APM
https://www.elastic.co/guide/en/elasticsearch/plugins/6.3/ingest-geoip.html.

**Comment by makwarth** [comment]
FYI https://github.com/elastic/elasticsearch/pull/36898

**Comment by simitt** [comment]
Update from [Ingest geoip](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-geoip.html) (>= 6.7): 
> The geoip processor is no longer distributed as a plugin, but is now a module distributed by default with Elasticsearch. See the GeoIP processor for more details.

This means that we _could_ make use of the geo-ip processor by default, as long as an ES version >= 6.7 is used.

**Comment by makwarth** [comment]
@simitt I think we should definitely do that, and I'd include the [user-agent module](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-user-agent.html). What's the best way to move forward with this?

**Comment by simitt** [comment]
@makwarth thanks for the feedback. I'll bring it to some internal discussions for how to prioritize this.

**Comment by alvarolobato** [comment]
We checked that the new APM Server 7.0 will only need to support ES from 6.7 to 7.x, so we can enable this without doing a version check. 
We can do this task then for 7.1 instead of 7.2

**Comment by graphaelli** [comment]
Add a second pipeline with both user_agent and geoip processors, update commented out default in configuration file.  Verify that upgrade from single pipeline in 7.1 to multiple in 7.2 works as expected / users the new pipeline by default.

**Comment by jahtalab** [comment]
Recently in our sync meeting, it was mentioned that having ASN (Autonomous System Number) data available would help with debugging, e.g. knowing ASN is registered for a mobile service provider.

It seems that this data is available in a different database (GeoLite2 ASN). I'm not sure if we can work around this and have the fields from both the "GeoLite2 City" database as well as the "GeoLite2 ASN" database.

If adding ASN makes the implementation too complicated for this iteration, I'm ok with postponing it.

**Comment by graphaelli** [comment]
It's not especially complicated, but I think we should hold off inclusion of the ASN information until the fields are [standardized in ECS](https://github.com/elastic/ecs/pull/341) and the elasticsearch processor supports those fields directly.  We can document usage in the meantime for users who want this functionality immediately.

**Comment by jahtalab** [comment]
Thanks @graphaelli , documenting the usage is a good idea 👍

**Comment by ariel-kiel** [comment]
How can i use the new default pipeline when i already have a pipeline i have created? 
how to setup the APM.yml for this ?

**Comment by graphaelli** [comment]
To migrate to the configuration shipping with the next release immediately, you could:

1. Create the two new ingest node pipelines (assuming `apm_user_agent` already exists):
```
PUT _ingest/pipeline/apm_user_geo
{
  "description": "Add user geo information for APM events",
  "processors": [
    {
      "geoip": {
        "database_file": "GeoLite2-City.mmdb",
        "field": "client.ip",
        "target_field": "client.geo",
        "ignore_missing": true
      }
    }
  ]
}

PUT _ingest/pipeline/apm
{
  "description": "Default enrichment for APM events",
  "processors": [
    {
      "pipeline": {
        "name": "apm_user_agent"
      }
    },
    {
      "pipeline": {
        "name": "apm_user_geo"
      }
    }
  ]
}
```

2. Update the elasticsearch `output` in apm-server.yml to utilize them:
```
output.elasticsearch
  pipelines:
  - pipeline: "apm"
```

@bmorelli25 fyi in case you think this fits into any plans you had for 7.2 notes or ingest pipeline examples.
