### ISSUE TITLE
Revisit decision for `output.elasticsearch.max_retries` 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1284]
The APM Server is started with `PublishMode: GuaranteedSend`, and `max_retries` is set to a default value of 3. 

In case the Server returns errors to the agents, they discard the events instead of retrying, for several performance reasons. 

Revisit if it is worth to have a default value of 3, and to use _GuaranteedSend_ over _DropIfFull_ in combination with a memory queue.

**Comment by jalvz** [comment]
Linking to https://github.com/elastic/apm-server/issues/992 as is somewhat related.
Based to benchmarks agains different elasticsearch setups, we should also reconsider default  batch size, etc.

**Comment by simitt** [comment]
With the APM Integration the output settings are not defined directly in the APM Server anymore and the whole output handling has been reworked.
