### ISSUE TITLE
Document release process with the automation workflow

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-server#12864]
The current [RELEASES.md](https://github.com/elastic/apm-server/blob/main/dev_docs/RELEASES.md) doesn't mention how to use the CI automation or when to run them. This takes precious time to figure things out OR to create the manual PR. We should document the updated/streamlined process using the CI jobs.

**Comment by carsonip** [comment]
+1 on documentation.

Here are the automation jobs that should be triggered manually:
https://github.com/elastic/apm-server/actions/workflows/run-minor-release.yml
https://github.com/elastic/apm-server/actions/workflows/run-patch-release.yml

**Comment by lahsivjar** [comment]
> Here are the automation jobs that should be triggered manually:
https://github.com/elastic/apm-server/actions/workflows/run-minor-release.yml
https://github.com/elastic/apm-server/actions/workflows/run-patch-release.yml

Those are quite straightforward to find out however, that is just the start of the confusion (at least for me) as it is still not clear when to run those. For example, the process for minor release is:

1. Day after FF, cut a new release branch from main and update the dependencies + versions in both main and the new branch.
2. On release day, bump the version on the new versioned branch to the next release version.

IIUC, technically none of the jobs perform step `2`, however, it could be done by running the `run-patch-release` job -- not sure if it is intended to run this way but it does do what we want for step `2`. If this is true then for minor release also we would end up running the patch release job.

**Comment by endorama** [comment]
Working on improving documentation and process! Draft PR where I'm collecting all the changes as I go: https://github.com/elastic/apm-server/pull/12983

New issues:
- https://github.com/elastic/apm-server/issues/12989
-

**Comment by endorama** [comment]
PRs for the mentioned issues has been created, waiting on review.
