### ISSUE TITLE
Support for ILM in APM Server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1290]
Use Index Life Cycle Management for automate rollover for APM documents. 

**Update:**
https://github.com/elastic/beats/pull/10347 allows to implement our own index and ilm supporter, which are handling everything around index setup, ilm and template loading. 
The supporter have full access to the raw config, which means we are also free to define our own configuration for ILM. 

We need to come up with a draft on how ILM config should look like in APM Server. 

**Outdated information:**

Things to discuss:
* Is it still the best setup to have daily indices or is it better to have one index and create a size based rollover strategy?
* Could we allow and change the default to having an index per service if we can get rid of daily indices?

Related Work to ILM:
https://github.com/elastic/beats/issues/7935
https://github.com/elastic/elasticsearch/issues/29823

TODO:
- ~[ ] allow one template per index https://github.com/elastic/apm-server/issues/1483~
- ~[ ] update to ILM implementation from beats and adapt APM Server settings accordingly.~
- ~[ ] document ILM and change to ILM in APM Server https://github.com/elastic/apm-server/issues/1545~

**Comment by makwarth** [comment]
Notes from IRL convo with Shane:

- ILM will be supported in Beats in 6.6, but he said we should check if the support is in libbeat or just Filebeat
- ILM will most likely be supported in Kibana in 6.6
- There's a build we can try when we're ready to implement and test

**Comment by simitt** [comment]
We created a doc about [ILM beats and APM Server](https://docs.google.com/document/d/1kk9ECrvxzkhhkACV2TXHOxtBDT1Lo3YvXgkJ_T6xVsU/edit) integration a while ago, that links to ES and ongoing beats implementation and summarizes the open points we have to clarify.

**Comment by simitt** [comment]
Notes from discussions with @ruflin and @elastic/apm-server team:
- Focus on solving the template per index problem
- Neglect the flexibel index creation, and find an easy solution for APM e.g. index aliases defined per event type up front
- Implement a basic version for the first implementation

Next step: 
- Investigate which changes would be necessary to allow one template per index.

**Comment by simitt** [comment]
Waiting for PR comments on https://github.com/elastic/beats/pull/9616, as recent discussions showed that the current config approach might indicate more flexibility than what it actually allows (cc @urso ).

**Comment by simitt** [comment]
PR https://github.com/elastic/beats/pull/10002 following beats core team suggestions around how to build indices has been closed again, after discussions that introducing this new config option seems rushed.

**Comment by simitt** [comment]
https://github.com/elastic/beats/pull/10347 introduces new `index management supporter` and `ilm supporter` that allow for more flexibility.

**Comment by simitt** [comment]
We decided to move forward with a fixed implementation and minimal configuration for the users to get ILM started. This will be achieved by adding a `apm-server.ilm.enabled` option, with default set to `false`. If enabled, the server takes care of setting up additional templates, the policies and write aliases and uses the write aliases as index names to write to. The first implementation will not allow users to modify any of this. If the setup doesn't satisfy user needs, users can always take care of the ILM setup manually and then set the rollover aliases as index names in the server config, see #1545 for more details.
