### ISSUE TITLE
Make mapping explosion on `tags` visible

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1292]
Investigate what is the best option to raise awareness around mapping explosion:
* Add information to monitoring tab, by showing number of dropped events and storing APM Server logs or storing documents that could not be indexed. 
* Return response to agents for the next request, if documents have been dropped. 
* Add a warning to UI if number of fields in and index gets critical
* ..

**Comment by alvarolobato** [comment]
Related: https://github.com/elastic/apm-dev/issues/89

**Comment by alvarolobato** [comment]
This issue won't be needed if we finally do this: https://github.com/elastic/apm-server/issues/1477

**Comment by axw** [comment]
There's some new discussions ongoing about having labels use the `flattened` field type, which would eliminate the mapping explosion issue altogether. We will need to address numerical labels somehow (see https://github.com/elastic/apm-server/issues/3873), and for that we will need https://github.com/elastic/elasticsearch/issues/61550. For flattened labels we will need https://github.com/elastic/kibana/issues/25820.

I'll leave this open for now until there's some more certainty.

**Comment by simitt** [comment]
We can follow the progress in https://github.com/elastic/apm-server/issues/5963. Closing this issue for now.
