### ISSUE TITLE
Define deployment profiles for APM and create best practices for it.

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1293]
Come up with some default customer profiles and different default values and best practices around them (e.g. having different apm-server.discover.yml, apm-server.highload.yml, apm-server.microservices.yml, ..)

**Comment by alvarolobato** [comment]
We should discuss if the best approach is creating different yml files or just document the sizes.
Using the sizing we recently did should be enough for these values.

**Comment by graphaelli** [comment]
lowering priority and moving to backlog as we consider alternatives like automatically adjusting configuration based on available resources

**Comment by bmorelli25** [comment]
@graphaelli Is there anything we can do now to resolve this issue, or are we still not sure of the path forward?

**Comment by graphaelli** [comment]
Thanks for the mention, we can remove the `docs` label and mention #2631 as that's likely when we can take a real look at this.
