### ISSUE TITLE
Make error.exception.message optional

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#1297]
In Java, the exception message is a nullable property, so I propose making it optional in the JSON schema as well. Are there any dragons hiding in the shadows when doing this?

**Comment by simitt** [comment]
An error document has to either provide an `error.exception` or an `error.log`. For both of them a `message` is required. The `message` is the only required field for both, ensuring that if nothing else is provided, some information is available for calculating how to group errors together. 

In case the Java exception message is null, would the agent have some valuable information that could be set as message?

**Comment by felixbarny** [comment]
The only useful thing would then be the `exception.type`. As a workaround, I'm currently sending `"message": "null"` if the exception message is `null`.

**Comment by roncohen** [comment]
We use the message (either `log.message` or `exception.message`) in the UI, so we'd need to have a way to deal with null messages there too.

**Comment by roncohen** [comment]
@felixbarny just throwing it out there, but maybe what you're doing now (`"null"`) is fine?

**Comment by felixbarny** [comment]
I'm ok with just transmitting `"null"` if that's easier. If we get more reports from other agent devs that they struggle with null values, we could re-evaluate this.

If you are fine with this, feel free to close.

**Comment by felixbarny** [comment]
At the moment, I don't have a use-case for `error.log` so I have not yet implemented them. But logging something without a message does not seem useful to me.

**Comment by watson** [comment]
In the case of languages that can use `type` instead of the `message` (like Java), I think the best thing would be if the UI was updated to fall back to using `type` if `message` wasn't provided in all the places where `message` is expected today.

This would of course require us to make `message` optional. But I wouldn't want to make `type` required either. But I think the JSON schema allows us to make just one of them required without specifying which one, correct?

**Comment by simitt** [comment]
We could do that in the json schema yes. 
Thoughts from the @elastic/apm-ui team regarding @watson 's suggestion?

**Comment by formgeist** [comment]
AFAIK the current errors overview table is showing only error message, which in this case needs to be either or both `error.message` and `error.type` as title? Is the language (agent) consistent, so it's either message or type being used or might that change for each error group/occurrence for a single language (agent)?

**Comment by watson** [comment]
@formgeist In my opinion it's either or. If there's a `message`, show that. If not, show the `type` instead. It should be the same rule for all agents

**Comment by felixbarny** [comment]
In Java, the type would always be present but the message might be absent in some (rather rare) cases.

**Comment by formgeist** [comment]
Do you want to know if it's either or in the list, or does that not matter? You're just interested in what it says, and then you can see the details on the individual error pages. Just wondering if we need to specify if it's `message` or `type` for each row in the list, if it might be mixed.

**Comment by felixbarny** [comment]
@formgeist was that a question for me or for @watson? I don't quite get what you are asking.

**Comment by formgeist** [comment]
<img width="1642" alt="screen shot 2018-08-22 at 13 26 40" src="https://user-images.githubusercontent.com/4104278/44460880-144b4e80-a60f-11e8-8dd5-152f976d01d0.png">

Both of you potentially 🙂Above is a screenshot of the errors overview table where we're currently printing the `error.message` and `error.culprit` to make up the title and subtitle of each row. My question is whether we might end up in a situation where it's a mix of both `message` and `type` for errors for a particular service. Do you think it's necessary to print a label next to the `message` or `type` so the user knows where the title is coming from? Or is it arbitrary as long as we print something meaningful in there so you can recognize the error group.

**Comment by felixbarny** [comment]
I think, as a Java developer, I'd actually prefer to also see the exception type. For example, when the message is just `foo`, that's not very meaningful. Knowing whether this is an `IllegalStateException` or maybe a `NullPointerException` would give more context at a glance.

So I'd probably add both the type and the message if present. Any of them can absent, but at least one has to be present.

**Comment by formgeist** [comment]
@felixbarny Thanks for the clarification 👍

**Comment by simitt** [comment]
It sounds like all are agreeing on making `error.exception.message` optional?

**Comment by sqren** [comment]
Fine with me 👍 
@formgeist are you creating a design issue for this?

**Comment by formgeist** [comment]
@sqren Will do :thu

**Comment by formgeist** [comment]
@sqren Design issue https://github.com/elastic/kibana/issues/22329

**Comment by roncohen** [comment]
@simitt looks to me that the discussion is still ongoing in the design issue?

**Comment by simitt** [comment]
I thought the discussion is only about how to show it, but not anymore that we require either of them.
