### ISSUE TITLE
v2: Investigate "full queue" behavior

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1298]
Reporting timeout is 1s at the moment., which is probably too high. We should investigate the behavior of v2 when the queue is full.

**Comment by roncohen** [comment]
The reason we can't just block for a second every time data comes in, is that eventually the agents "write" call on the socket will start timing out. This sort of timeout can also happen for other reasons e.g. APM Server isn't working properly, or there's a faulty proxy in between. In other words, we can't just say that whenever a write in the agent times out, it means the queue in APM Server is full. 

When APM Server queue is full we could simply write "Write error: timeout" to the agent logs, but it would be a much better user experience if agents are able to write a more meaningful message to their logs.

After discussions with @urso, we can't get rid of the 1s timeout without making significant changes to libbeat. For the first iteration of v2, i suggest we should do the simple thing and keep the 1s timeout in the APM Server, but return a ERR_FULL_QUEUE response to the agent immediately (see https://github.com/elastic/apm-server/issues/1240) if we've been unable to deliver the events to the internal beats queue within the 1s timeout.

WDYT @elastic/apm-agent-devs ?

**Comment by felixbarny** [comment]
Sounds good. But it would be necessary that all HTTP clients used by the agents support receiving a response before the request has been fully written. If it doesn't I'd expect to get an `IOException` `Connection reset by peer`, which can be handled as well, but without having access to the response. Maybe the TCP connection can also not be reused in that case, needs investigation.

What is an easy way to reproduce that situation so I can test that? Reporting lots of transactions to the APM server and not starting Elasticsearch?

**Comment by simitt** [comment]
fyi - @graphaelli already [created a PR](https://github.com/elastic/apm-integration-testing/pull/167) in the apm-integration-testing so that you can use the testing repo for starting the `v2` branch of the server.

**Comment by felixbarny** [comment]
To keep track which agents have already been tested:

* [ ] go 
* [ ] java
* [ ] nodejs
* [ ] python
* [ ] ruby 
* [ ] RUM

**Comment by watson** [comment]
In the Node.js agent the risk of errors and how we handle them are the same for both api-v1 or v2. So there's no difference between the two versions for us. We're all good 👍

**Comment by urso** [comment]
Proposed libbeat changes: elastic/beats#8080

**Comment by felixbarny** [comment]
@watson how did you test the TCP half-close when the APM server queue is full? I tried shutting down ES and sending lots of transactions but then I got read timeouts from the APM server.

**Comment by watson** [comment]
@felixbarny I just set up a mock HTTP server that would respond the way I wanted and then send data at it. I can share the code with you if you want

**Comment by felixbarny** [comment]
that would be helpful

**Comment by watson** [comment]
@felixbarny https://gist.github.com/watson/16938f3b36e2ce1190f9d7e4e100b1c2

**Comment by felixbarny** [comment]
That works perfectly with the Java agent. Although, not compressing the response would make the handling a bit simpler. Do you think compression would be beneficial?

**Comment by jahtalab** [comment]
I've tested this with the latest versions of Chrome, Firefox and Safari and it works as expected (the agent can receive the error response from the APM Server). 

Thanks for the APM Server mock @watson  👍

**Comment by felixbarny** [comment]
I would have to manually wrap the response into an `InflaterInputStream` or `GzipInputStream`, based on the headers returned. In some cases, I might not be able to read the headers (for example if the apm server died abruptly). So handling possibly compressed data would make the handling more complex (although not impossible). I'm trying to weigh the advantages of having compressed response data against the complexity in the agents (might just be a Java thing that it's complex).

Because the agents are doing an exponential backoff, and thus sending the error response is quite infrequent, I don't think compression adds a lot of value. So the APM server should at least respect the `Accept-Encoding` header and don't compress if the agent does not support it.

**Comment by watson** [comment]
In Node.js, how a response from an HTTP server is handled is unrelated to if it's received while the request body is still being sent or not. So for the Node.js agent this makes no difference.

But if it's a problem with some HTTP frameworks, I think the agent should be free to set the `Accept-Encoding: identity` to instruct the server not to use any encoding in the reply. We need to make sure the server supports the `Accept-Encoding` header though. Or maybe the default should be no encoding, unless the agent explicitly sets `Accept-Encoding: gzip` for instance.

**Comment by felixbarny** [comment]
> Or maybe the default should be no encoding, unless the agent explicitly sets `Accept-Encoding: gzip` for instance.

That would be according to spec. If the client does not explicitly accept a specific encoding, the server should not apply one.

**Comment by felixbarny** [comment]
Actually, this is what the spec says:

> If no Accept-Encoding field is present in a request, the server MAY assume that the client will accept any content coding. In this case, if "identity" is one of the available content-codings, then the server SHOULD use the "identity" content-coding, unless it has additional information that a different content-coding is meaningful to the client.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by felixbarny** [comment]
But I think in our case, the APM server should not compress unless the agent explicitly sets an `Accept-Encoding` header.

**Comment by watson** [comment]
Sounds reasonable. /cc @roncohen wanna get this into the v2 api?

**Comment by roncohen** [comment]
@simitt do you have time to help with this one?

**Comment by simitt** [comment]
@felixbarny , @watson which compression types should be implemented for the response? So far I have:
* unset `Accept-Encoding`: no encoding
* `Accept-Encoding: identity`: no encoding
* `Accept-Encoding: gzip`: gzip

**Comment by roncohen** [comment]
why do we even need compression for the response? Let's do the simple thing and never compress the response.

**Comment by watson** [comment]
Since we're including the failed documents in the response, can't it be large?

**Comment by roncohen** [comment]
We'll only be including up to ~5 and we're capping the size of the documents already (to something rather large, maybe 10kb - 100kb, to be sure), so I don't think it's going to be a problem.

**Comment by watson** [comment]
It would be interesting to benchmark which produces the biggest overhead in the agents. A large uncompressed response payload, or the same payload compressed. Even if the difference is only small I'm fine with just dropping compression. But if there's a significant performance improvement by compressing we might want to consider it right?

If we don't have time for this now, we can of course also just wait and add it later if it complicates matters in the server.

**Comment by felixbarny** [comment]
To quote myself:
> Because the agents are doing an exponential backoff, and thus sending the error response is quite infrequent, I don't think compression adds a lot of value.

Plus we can always add compression later

**Comment by roncohen** [comment]
thanks all. I'll defer it for now.

**Comment by simitt** [comment]
@roncohen this issue can be closed with https://github.com/roncohen/apm-server/pull/3, right?

**Comment by felixbarny** [comment]
I'd like to re-test with the java agent before closing this

**Comment by roncohen** [comment]
@felixbarny the changes have been merged now. Please give it another try.

**Comment by felixbarny** [comment]
It's working really well now. See also the agent logs:

```
12:31:51.325 - Ending request with 12171243 uncompressed 1053641 compressed bytes
12:31:52.236 - Backing off for 0 seconds
12:31:52.237 - Server returned HTTP response code: 429 for URL: http://localhost:8200/v2/intake
12:31:52.240 - {"accepted":4190,"errors":[{"message":"queue is full","document":""}]}
12:31:52.742 - Ending request with 12356081 uncompressed 1044277 compressed bytes
12:31:53.465 - Backing off for 1 seconds
12:31:53.465 - Server returned HTTP response code: 429 for URL: http://localhost:8200/v2/intake
12:31:53.465 - {"accepted":0,"errors":[{"message":"queue is full","document":""}]}
12:31:54.574 - Ending request with 12516988 uncompressed 1039444 compressed bytes
12:31:55.474 - Backing off for 4 seconds
12:31:55.474 - Server returned HTTP response code: 429 for URL: http://localhost:8200/v2/intake
12:31:55.475 - {"accepted":0,"errors":[{"message":"queue is full","document":""}]}
12:32:00.082 - Ending request with 12563716 uncompressed 1038356 compressed bytes
12:32:00.491 - Backing off for 9 seconds
12:32:00.491 - Server returned HTTP response code: 429 for URL: http://localhost:8200/v2/intake
12:32:00.491 - {"accepted":0,"errors":[{"message":"queue is full","document":""}]}
12:32:09.575 - Ending request with 12816144 uncompressed 1058085 compressed bytes
12:32:10.497 - Backing off for 16 seconds
12:32:10.497 - Server returned HTTP response code: 429 for URL: http://localhost:8200/v2/intake
12:32:10.498 - {"accepted":0,"errors":[{"message":"queue is full","document":""}]}
```

Some notes:
* The APM server responds within < 1 s, which is much better
* `"document":""` seems redundant

**Comment by simitt** [comment]
@roncohen you could use `omitempty` for the json tags for errors, then `document` would be skipped.

**Comment by roncohen** [comment]
@felixbarny thats great! thanks for testing
@simitt right. I thought I had. I'll make sure it gets included in one of the following PRs.

**Comment by simitt** [comment]
@roncohen you have added it [here](https://github.com/elastic/apm-server/pull/1347/files#diff-f95ef51f0c5f93f6949bc23027455a88), so should be all set.

**Comment by simitt** [comment]
@roncohen @felixbarny can we close this issue?

**Comment by felixbarny** [comment]
I'm done with the testing but we might want to keep this open until all agents have tested with the apm server v2 branch, not sure though.

**Comment by simitt** [comment]
@elastic/apm-agent-devs as the implementation was changed could you please tick off again when tested:
* [ ] go 
* [ ] java
* [ ] nodejs
* [ ] python
* [ ] ruby 
* [ ] RUM

**Comment by watson** [comment]
@simitt did anything in the TCP/HTTP API change, or just internally how things are handled inside the APM Server?

**Comment by simitt** [comment]
With https://github.com/elastic/apm-server/pull/1324 the Server immediately returns when the queue is full, without trying to process the remaining data. Also the response format changed to not have a type anymore.

**Comment by felixbarny** [comment]
Another important difference is that the current v2 branch requires DT, although that can be mocked by setting a random `trace_id` (@simitt correct me if I'm wrong).

**Comment by simitt** [comment]
@watson , @Qard, @mikker any updates on this one?

**Comment by watson** [comment]
We need to make a small change to the Node agent, but we can support it, so it's a 👍 from me

**Comment by mikker** [comment]
Should be fine! 👍

**Comment by roncohen** [comment]
thanks everyone!
