### ISSUE TITLE
APM Server 8.14.0 Test Plan

### ISSUE THREAD

**Issue by endorama** [elastic/apm-server#12988]
# Manual Test Plan

When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished.
Testing can be started when the first build candidate (BC) is available in the CFT region.

## Smoke Testing ESS setup

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now.
**Consider extending the smoke tests to include more test cases which we'd like to cover**

## Test cases from the GitHub board

[apm-server 8.14 test-plan](https://github.com/elastic/apm-server/issues?q=label%3Atest-plan+-label%3Atest-plan-ok+is%3Aclosed+label%3Av8.14.0)

Add yourself as _assignee_ on the PR before you start testing.

- [x] https://github.com/elastic/apm-server/pull/12759

## Regressions

Link any regressions to this issue.

**Comment by endorama** [comment]
BC 3 is out on May 2nd and there is only 1 BC after that before 8.14 being released!

**Comment by endorama** [comment]
Removing dependencies bumps from the test plan

**Comment by simitt** [comment]
>Removing dependencies bumps from the test plan

Have you verified that they didn't pull in any changes that require manual testing?

**Comment by endorama** [comment]
@simitt there has been some internal discussion around testing those issues and the conclusion (from Andrew and Vishal) has been that we cannot test them beyond what the smoke test would be doing.

After reviewing them I agree, they are code changes that do not have a defined manual test plan but rely on our automated test suite.

**Comment by endorama** [comment]
I tested today the only issue in the test plan (thanks @carsonip for you guidance!). That makes for the completion of our 8.14 test plan :tada: Closing.
