### ISSUE TITLE
ci: minor-release automation is not aligned with expectations

### ISSUE THREAD

**Issue by endorama** [elastic/apm-server#12989]
Release automation for minor releases does not:
- add `apm-` prefix to Asciidoc links and targets
- use tags instead of branches in compare links

A manual fix we applied for latest release was [`a0d4d2d` (#12984)](https://github.com/elastic/apm-server/pull/12984/commits/a0d4d2d60f292cf98d10c717cb903ec257c1e580), but we want to fix the automation so this is not a manual step.

**Comment by simitt** [comment]
@cachedout could the eng.prod team help out with this and add it to your planning?

**Comment by cachedout** [comment]
@simitt done (cc: @v1v )
