### ISSUE TITLE
Perf regression, too many small bulk requests 

### ISSUE THREAD

**Issue by StephanErb** [elastic/apm-server#13024]
**APM Server version** (`apm-server version`):
8.13.2

**Description of the problem including expected versus actual behavior**:

I believe there is a regression in the number of bulk requests/s emitted by APM Server towards Elastic. I don't have all data for it, but I believe the issue started in 8.12.x and then got worse with the upgrade to 8.13.x.

This is from the Elastic cloud console: On otherwise identical clients/agents, we see that with the upgrade from 8.12 to 8.13 the number of indexing requests/s jumped noticeably.

![Screenshot_2024-04-16_at_23 59 50](https://github.com/elastic/apm-server/assets/483730/9111106c-0be5-4aee-b90e-302b3e6298c6)

The number of documents/s that get ingested didn't really change much, but our hot nodes started to run under higher load. Fortunately, we observed that setting `index.translog.durability=async` on the all APM indices drops IOPS per hot node back to acceptable levels:  

![Screenshot_2024-04-21_at_21 35 36](https://github.com/elastic/apm-server/assets/483730/78125df8-33ae-4f99-a915-fe76dd253e61)

On a decently tuned `bulk_max_size` setting I'd not expect such a big drop in IOPS/s. I am thus wondering if the APM server is misconfigured in newer versions. 

It almost feels like the server uses the agent defaults instead of its custom bulk size option?  Was it maybe forgotten to set `preset: custom` into the server config once https://github.com/elastic/elastic-agent/issues/3797 got merged into the agent?

**Comment by axw** [comment]
@StephanErb thanks for raising this. I've had a look at the code changes, and nothing obviously stands out. There were some changes in the ES output code, but they're not enabled in APM Server 8.13.x. We'll need to try and reproduce the issue and work back from there.

> The number of documents/s that get ingested didn't really change much

Just to clarify: are you referring to the number of documents successfully indexed in Elasticsearch?

> It almost feels like the server uses the agent defaults instead of its custom bulk size option? Was it maybe forgotten to set preset: custom into the server config once https://github.com/elastic/elastic-agent/issues/3797 got merged into the agent?

APM Server has its own ES output implementation, completely independent of Elastic Agent/Beats.

**Comment by StephanErb** [comment]
>> The number of documents/s that get ingested didn't really change much 
>
> Just to clarify: are you referring to the number of documents successfully indexed in Elasticsearch?

We have upgraded the APM Server and Elastic but the APM clients remained unchanged. There was such no change in data forwarded to APM Server and ultimately indexed into Elastic.

Some stats on ingestion from stack monitoring:
* Ingestion of 18000 docs/s into .ds-metrics-apm.app.all-default-2024.04.23-004117 
* Ingestion of 4000 docs/s into .ds-metrics-apm.internal-default-2024.04.21-000931
* Ingestion of 2000 docs/s into .ds-traces-apm-default-2024.04.23-001742
* Ingestion of 1000 docs/s into .ds-logs-apm.app.all-default-2024.04.17-000162

Please note we are running a `reroute` pipeline to prevent per-service indices and instead have them all flow into one `all` datastream for all services.

When checking ` GET _tasks?pretty&human&detailed=true&actions=indices:data/write/bulk` we see a few hundred parallel tasks such as:

```
"iaCFp3aFSnuliL3GpI_fnQ:1325096688": {
      "node": "iaCFp3aFSnuliL3GpI_fnQ",
      "id": 1325096688,
      "type": "transport",
      "action": "indices:data/write/bulk",
      "description": "requests[211], indices[metrics-apm <SNIP not to leak service names> traces-apm-default]",
      "start_time": "2024-04-23T20:26:19.872Z",
      "start_time_in_millis": 1713903979872,
      "running_time": "299.7ms",
      "running_time_in_nanos": 299780808,
      "cancellable": false,
      "headers": {
        "X-elastic-product-origin": "observability"
      }
},
"iaCFp3aFSnuliL3GpI_fnQ:1325097388": {
      "node": "iaCFp3aFSnuliL3GpI_fnQ",
      "id": 1325097388,
      "type": "transport",
      "action": "indices:data/write/bulk",
      "description": "requests[261], indices[metrics-apm.internal-default, metrics-apm.app <SNIP not to leak service names>]",
      "start_time": "2024-04-23T20:26:20.165Z",
      "start_time_in_millis": 1713903980165,
      "running_time": "61.3ms",
      "running_time_in_nanos": 61304826,
      "cancellable": false,
      "headers": {
        "X-elastic-product-origin": "observability"
    }
}

As per `requests[211]` and `requests[261]` my interpretation is we are seeing a batch size of ~200 documents which appears relatively low to me given the overall throughput of the system. (I hope this is correct, I could not find any docs on the format).

**Comment by StephanErb** [comment]
Thanks for picking this up. 

We just upgraded in the Cloud console without any additional configuration changes for the APM server (flush interval, etc) or APM server memory changes. We are running two APM servers in the max configuration (2x30 GB). 

This is how the load looks like as per Stack Monitoring (incl request stats):
![Screenshot 2024-04-29 at 12 45 11](https://github.com/elastic/apm-server/assets/483730/6170e86d-8e80-4567-b979-8e8187f0a2e3)
![Screenshot 2024-04-29 at 12 45 20](https://github.com/elastic/apm-server/assets/483730/9a4ff4c7-cf10-44c6-aa06-dc7bb8a7e6d6)

Unfortunately I don't have enough history retention on the monitoring cluster too look at what happened around the time we upgraded.

In our logs we see a relative large number of indexing errors:
```
10:23:19.114 agent.log [agent.log][error] failed to index documents in '.ds-metrics-apm.app.all-default-2024.04.29-004154' (document_parsing_exception): [1:366] object mapping for [kafka.consumer.fetch.manager.records.lag] tried to parse field [lag] as object, but found a concrete value
10:23:19.115 agent.log [agent.log][error] failed to index documents in '.ds-metrics-apm.app.all-default-2024.04.29-004154' (document_parsing_exception): [1:366] object mapping for [kafka.consumer.fetch.manager.records.lag] tried to parse field [lag] as object, but found a concrete value
10:23:19.116 agent.log [][access]   "POST /intake/v2/events HTTP/" 202
10:23:19.117 agent.log [][access]   "POST /intake/v2/events HTTP/" 202
10:23:19.118 agent.log [agent.log][error] failed to index documents in '.ds-metrics-apm.app.all-default-2024.04.29-004154' (document_parsing_exception): [1:366] object mapping for [kafka.consumer.fetch.manager.records.lag] tried to parse field [lag] as object, but found a concrete value
10:23:19.118 agent.log [agent.log][error] failed to index documents in '.ds-metrics-apm.app.all-default-2024.04.29-004154' (document_parsing_exception): [1:156] failed to parse field [hikaricp.connections] of type [double] in document with id 'yIhhKY8BTYD0o0NlX6M_'
```

Could those errors lead to higher-ingest load now that https://github.com/elastic/go-docappender/pull/99 has landed?

**Comment by StephanErb** [comment]
@simitt this is with:

* head-based sampling
* sample rate of about 10%

**Comment by StephanErb** [comment]
Yes, both got updated to the same version via a regular update initiated on Elastic cloud.

**Comment by marclop** [comment]
I'm investigating this issue and I think I've found the bug. I'll create a PR urgently to fix this.
