### ISSUE TITLE
Document 7.17.20 being broken for apm-server managed by Fleet with self-signed certificates

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#13031]
Add a note to the known issues for `7.17.20`, similar to https://github.com/elastic/ingest-docs/pull/1006. Due to a bug in the Fleet Server, the APM Server fails to startup when managed by Elastic Agent and Fleet and using self signed certificates. The only current workaround is to downgrade to `7.17.19`. 

Detailed description in https://github.com/elastic/fleet-server/issues/3435

**Comment by lahsivjar** [comment]
Added a known issue section in `7.17.20`: https://github.com/elastic/apm-server/pull/13063 and also added this as fixed in the `7.17.21` release notes: https://github.com/elastic/apm-server/pull/13074
