### ISSUE TITLE
Investigate usage of libbeat's `common.MapVal`

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1307]
Currently data are validated against a dedicated json schema and afterwards decoded into dedicated go structs. This means decoding data twice. The code between the validation and the decode step could get out of sync and cause server errors. 
Using [libbeat common mapval](https://godoc.org/github.com/elastic/beats/libbeat/common/mapval) could allow for combining the json validation and decoding step.

Investigate if it can handle all cases and if it would be worth to switch over. Also check performance impacts. 

Note: Agent Devs currently build their tests around the defined json specs.

**Comment by jalvz** [comment]
I don't think this deserves the effort for now, but we can reconsider in the future if we have the bandwidth
