### ISSUE TITLE
custom ILM policy for specific event types in integrated APM server

### ISSUE THREAD

**Issue by raymaxar** [elastic/apm-server#13146]
Hi! first time poster here and a somewhat newbie to the APM server (though longtime Elasticsearch user) so forgive me if I sound like a dolt.

My goal is to extend the lifecycle of APM trace events for transactions only, ie I want to create a custom ILM policy that only applies for transactions.

This seems possible using the legacy standalone-APM server approach via event-type mapping:
https://www.elastic.co/guide/en/apm/guide/7.17/ilm.html

However the standalone-APM server is deprecated,  and the new integrated-APM server approach only seems to allow custom lifecycle policies as described here:
https://www.elastic.co/guide/en/observability/current/apm-ilm-how-to.html#apm-data-streams-custom-policy-namespace
which doesn't seem to allow for event-type specific mappings.

Am I missing something? 

I posed this question on the Elastic Observability message board, but no response -
https://discuss.elastic.co/t/setting-apm-trace-lifecycle-policy-per-type-transaction-v-span-using-custom-policy/358992

**Comment by axw** [comment]
> so forgive me if I sound like a dolt.

@raymaxar you certainly do not!

> I posed this question on the Elastic Observability message board, but no response -

Sorry about that. I have responded over there.
