### ISSUE TITLE
Possible data issues due to timestamp being optional.

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1314]
In V2 spans and their transactions might come in different requests.

Timestamps are optional for all the agents (not only RUM), so if a backend agent does not send the timestamp, all the data will be messed up. The job of the validation phase is precisely to avoid that.

Making timestamps required again would be a breaking change.

**Comment by simitt** [comment]
@watson atm backend and RUM agent endpoints share a json spec. We could change this if we think it is worth it.

**Comment by roncohen** [comment]
Somewhat related: https://github.com/elastic/apm-server/issues/1340

**Comment by alvarolobato** [comment]
We need to investigate if this can still happen after the changes pointed in the previous comment.

**Comment by simitt** [comment]
With https://github.com/elastic/apm-server/pull/1413#issue-219523008 a `timestamp.us` and a `@timstamp` will be always set for `transaction, error, span` in v2. If it is not sent, it is calculated on the server. 

I just checked the behaviour if timestamp is not set, but https://github.com/elastic/apm-server/blob/v2/utility/data_fetcher.go#L219 is setting time to `0001-01-01T00:00:00Z`. Looks like we have a bug here atm.

**Comment by simitt** [comment]
see https://github.com/elastic/apm-server/pull/1437 for a fix for the `error` event.

**Comment by simitt** [comment]
Closing this after discussing the v2 changes with @jalvz .
