### ISSUE TITLE
Validate go-docappender metrics are produced when monitoring is enabled

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#13244]
We should make sure that go-docappender metrics are produced when monitoring is enabled.

flush latency and similar metrics are important to debug issues

**Comment by carsonip** [comment]
I looked into this again. apm-server does get stats from the appender and publish libbeat monitoring metrics, other than the fact that go-docappender publishes OTel metrics itself.

The observation is that there are no `output.elasticsearch.bulk_requests` metrics [published by this code](https://github.com/elastic/apm-server/blob/main/internal/beater/beater.go#L746), but I see `output.events.*` metrics. This may reveal a bug somewhere. I wonder if using the `monitoring.Default` registry is causing a problem. This issue has to be investigated.

**Comment by carsonip** [comment]
Might be related to https://github.com/elastic/apm-server/issues/8383

**Comment by carsonip** [comment]
Observation: when `monitoring.enabled: true` and `monitoring.elasticsearch` is configured, the metrics are sent to ES directly under `.monitoring-beats-7-*`. The `output.elasticsearch.*` fields exist in source but are unmapped.

**Comment by carsonip** [comment]
In that case there may be 2 problems:
1. the `.monitoring-beats-7-*` does not have the mappings for some of our fields
2. metricbeat beat module may be ignoring the fields because some of our fields do not fall into ["exported fields" defined by metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/8.14/exported-fields-beat.html). Pending confirmation.

**Comment by carsonip** [comment]
> metricbeat beat module may be ignoring the fields because some of our fields do not fall into ["exported fields" defined by metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/8.14/exported-fields-beat.html). Pending confirmation.

(2) is not right. The mapping is actually defined in EA integration. Created https://github.com/elastic/apm-server/issues/13475 to take care of missing metrics due to EA integration apm-server metrics mapping.

**Comment by rnyburia** [comment]
![Uploading wp10474410-amazon-web-services-wallpapers.jpg…]()

**Comment by carsonip** [comment]
It should be closed by https://github.com/elastic/apm-server/issues/13475
