### ISSUE TITLE
Revisit docappender config autosizing values

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-server#13285]
We use some heuristic to adjust the max buffer size, max decoder size and max requests.

https://github.com/elastic/apm-server/blob/6309df6a5bb7c654e54852b94731a7574a752c7c/internal/beater/beater.go#L543-L552

https://github.com/elastic/apm-server/blob/6309df6a5bb7c654e54852b94731a7574a752c7c/internal/beater/beater.go#L769-L799

This formulas are really old and we had a lot of improvements since then, we should revisit them to ensure we are not underutilizing apm-server

**Comment by marclop** [comment]
We could easily update the `max_requests` formula to `memLimit * 2` instead of `memLimit * 1.5`.

```go
 	// 1	2 	4	8	15	30
 	// 12	14	18	26	40	70
 	maxRequests := int(float64(10) + memLimit*2) 
 	if maxRequests > 80 { 
 		maxRequests = 80 
 	} 
```

**Comment by rubvs** [comment]
I've updated the benchmark report in https://github.com/elastic/apm-dev/pull/1088. 

Please review and do not hesitate to ask questions.

@simitt @kruskall @marclop @1pkg
