### ISSUE TITLE
ci: `run-patch-release` tries to run unexisting make target `update-docs`

### ISSUE THREAD

**Issue by endorama** [elastic/apm-server#13381]
[`RELEASE.md`](https://github.com/elastic/apm-server/blob/main/dev_docs/RELEASES.md) specified to run `run-patch-release` GitHub workflow when a new patch release should be cut from the release branch.

Trying to follow through for the next `7.17` release I [run](https://github.com/elastic/apm-server/actions/runs/9451199647/job/26031589474) that workflow but it failed with `No rule to make target 'update-docs'`; see logs:

```
Run make patch-release
INFO: Create feature branch and update the versions. Target branch main.
create-branch update-7.17.23
  Switched to a new branch 'main'
  branch 'main' set up to track 'origin/main'.
  Switched to a new branch 'update-7.17.23'
go: downloading go1.22.1 (linux/amd64)
>> update-version
make[1]: *** No rule to make target 'update-docs'.  Stop.
make: *** [release.mk:140: patch-release] Error 2
Error: Process completed with exit code 2.
```

That target has been removed in c25abdd8d0ab6c100e302d1dcc66bac34643fa28 for releases >8.13, so I expect it to be available on 7.17 and I can grep for it locally:

```
❯ ag update-docs
release.mk
119:	$(MAKE) update-docs VERSION=$(RELEASE_VERSION)
140:	$(MAKE) update-docs VERSION=$(RELEASE_VERSION)
185:.PHONY: update-docs
186:update-docs: VERSION=$${VERSION}
187:update-docs: setup-yq
188:	@echo ">> update-docs"
```

The CI job did check out branch `7.17`, so I'm not sure why this failure.
![338260626-69da053d-b218-4860-be48-e9202e6eff86](https://github.com/elastic/apm-server/assets/526307/85390686-ab31-4653-a855-1298e0edb00d)

As a workaround I've been able to run the command locally with:

```
❯ RELEASE_BRANCH=7.17 RELEASE_VERSION=7.17.22 make patch-release
```

to create this [PR](https://github.com/elastic/apm-server/pull/13380/files)

**Comment by v1v** [comment]
PR:
- https://github.com/elastic/apm-server/pull/13382

I'm trying to recall how it worked in the past, and likely. it did when I tried locally but in the GitHub actions it didn't work.

Regardless, you can run using `main` always for `minor` and `patch` releases. The version is the important input parameter and will be used to switch to the specific branch (`main`, `7.17` or `8.14` ...)

**Comment by endorama** [comment]
@v1v thanks for chiming in! So the issue here is that I run the workflow from branch `7.17` instead of main? I'll document this, as I guessed I needed to use the correct release branch.

**Comment by v1v** [comment]
> The CI job did check out branch 7.17, so I'm not sure why this failure.


The problem is related to the `RELEASE_TYPE?= minor` therefore it uses `main` as the default branch and the makefile branches off from `main`.

<img width="749" alt="image" src="https://github.com/elastic/apm-server/assets/2871786/0dd710da-b0d2-4180-9166-831a0689ae80">


Even though it initially used the `7.17` branch.

> So the issue here is that I run the workflow from branch 7.17 instead of main

It should behave similarly. The issue was that `patch-release` didn't set the variable `RELEASE_TYPE=patch`, then it won't use the `main` branch but the `7.17` or `8.14`

**Comment by endorama** [comment]
Thanks for the explanations and the fix! :heart:

**Comment by endorama** [comment]
Improved docs around how to run the workflows in [`97877ca` (#13339)](https://github.com/elastic/apm-server/pull/13339/commits/97877ca32d227fba61735bd5870f59bbe64c0e8b)

**Comment by endorama** [comment]
https://github.com/elastic/apm-server/pull/13380 has been merged and I added some clarification to the `RELEASE.md` file in [`97877ca` (#13339)](https://github.com/elastic/apm-server/pull/13339/commits/97877ca32d227fba61735bd5870f59bbe64c0e8b). Closing
