### ISSUE TITLE
[v2] Rename "metric" entity to "metricset"

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#1356]
The metrics API defines a [metric](https://github.com/elastic/apm-server/blob/v2/docs/spec/metrics/metric.json) entity, which is really a set of metrics. I propose that we rename this to "metricset", or something similar. Calling it "metric" might give the impression that it is a singular measurement.

**Comment by watson** [comment]
How about just `metrics` (plural). I try to stick to one-word names if I can in these cases. But maybe I misunderstood the use-case here...

**Comment by axw** [comment]
This is for v2 objects, e.g.

```json
{"metadata":{}}
{"transaction":{}}
{"metrics":{"tags":{}, "samples":{}}}
```

"metrics" as an object name seems a bit odd to me, but better than just "metric". We could flatten the structure so we fold "tags" into each entry of "samples", but that would lead to a lot of repetition.

**Comment by roncohen** [comment]
I like `metricset`

**Comment by watson** [comment]
I'm fine either way. Just wanted to throw in the other option 😃

**Comment by roncohen** [comment]
metricbeat uses 'metricset' as well by the way: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-modules.html
