### ISSUE TITLE
APM Server 8.15 Test Plan

### ISSUE THREAD

**Issue by inge4pres** [elastic/apm-server#13604]
# Manual Test Plan

**[Build Candidate Schedule](https://github.com/elastic/dev/issues/2641)**

When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished.
Testing can be started when the first build candidate (BC) is available in the CFT region.

- [x] https://github.com/elastic/apm-server/pull/13196 [contains unit test but the UI side should be reviewed] 
- [x] https://github.com/elastic/apm-server/pull/13472
- [x] https://github.com/elastic/apm-server/pull/13514
- [x] https://github.com/elastic/apm-server/pull/13653
- [x] https://github.com/elastic/apm-server/pull/13691
- [x] https://github.com/elastic/apm-server/issues/13475
  - https://github.com/elastic/beats/pull/40127
  - https://github.com/elastic/elasticsearch/pull/110568
  - https://github.com/elastic/integrations/pull/10414
- [x] https://github.com/elastic/apm-server/pull/13790

## Smoke Testing ESS setup

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now.
**Consider extending the smoke tests to include more test cases which we'd like to cover**

_Is it worth adding a smoke test that sets up the Fleet output to a higher/smaller value_?

## go-docappender library

[v1.1.1 -> v2.1.4](https://github.com/elastic/go-docappender/compare/v1.1.1...v2.1.4)

All changes between 8.14.2 (using go-docappender v1.1.1) and 8.15.0 (using go-docappender v2.2.0) are unit tested in the library.

## apm-data library

[v1.1.0 -> v1.8.0](https://github.com/elastic/apm-data/compare/v1.1.0...v1.8.0)

- [x] https://github.com/elastic/apm-data/pull/296

## Test cases from the GitHub board

Add yourself as _assignee_ on the PR before you start testing.

## Regressions

- [x] https://github.com/elastic/apm-server/issues/13475: Waiting for BC3 since we didn't merge the backport.

**Comment by inge4pres** [comment]
Suggesting assignments of manual test plan items as I will be on PTO for the next 2 weeks.
If you are unable to perform the testing in the upcoming weeks before 8.15 release please sync with another peer to complete the testing.

- [ ] #13196 @carsonip  
- [ ] #13514 @kruskall 
- [ ] #13472 @kyungeunni 
- [ ] #13653 @1pkg 
- [ ] #13475 @lahsivjar 
- [ ] #https://github.com/elastic/apm-data/pull/296 @inge4pres

**Comment by inge4pres** [comment]
Testing methodology https://github.com/elastic/apm-data/pull/296 for is explained in the description in https://github.com/elastic/apm-server/pull/13196

**Comment by carsonip** [comment]
https://github.com/elastic/apm-data/pull/296 :heavy_check_mark: test-plan-ok

**Comment by 1pkg** [comment]
https://github.com/elastic/apm-server/issues/13597 and related https://github.com/elastic/apm-server/pull/13653 https://github.com/elastic/apm-server/pull/13691 ✅ verified

**Comment by marclop** [comment]
Seems like all has been tested and marked as OK except for https://github.com/elastic/apm-server/issues/13475. We're waiting for BC3 and will test once that's available.

**Comment by lahsivjar** [comment]
Tested #13475 with BC3 and is working as expcted.

**Comment by 1pkg** [comment]
Updating the test plan to include an additional fix from 8.15 release.
[] https://github.com/elastic/apm-server/pull/13790

**Comment by 1pkg** [comment]
The changes from https://github.com/elastic/apm-server/pull/13790 were validated in the latest 8.15 snapshot.

**Comment by inge4pres** [comment]
Closing this one as completed, yesterday 8.15 was released.
We will raise dedicated test plans for the upcoming 8.15 patch releases.
