### ISSUE TITLE
Show health of the configured output on status page

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#1366]
Maybe, we could leverage `./apm-server test output` for that.

Use case: making debugging easier. The agents can also call this endpoint and log the result into the agent logs.

**Comment by graphaelli** [comment]
Does status page == monitoring ui in kibana?  If so, that's planned per elastic/kibana#22508.

**Comment by felixbarny** [comment]
I mean what you get back when hitting the root url of the apm server.

**Comment by graphaelli** [comment]
Per discussion with cloud team, this could be useful for highlighting issues with apm-server deployments on ECE/ESS.  Currently Elasticsearch will flag `Deployment health warning` or `Unhealthy deployment` along with a brief summary of the issue, like `An Elasticsearch index is in a read-only state`.

**Comment by jalvz** [comment]
We decided to not prioritize this for now, we'll get back to it for 8.0.
 I'll close this to reduce the noise, but it is tracked in meta issue https://github.com/elastic/apm-server/issues/2632

Feel free to reopen if a new need arises. Thanks!
