### ISSUE TITLE
"View Job" on java service 404s

### ISSUE THREAD

**Issue by jamiesmith** [elastic/apm-server#1370]
AJ was on the internal APM server (ping me if you don't know which I mean) and clicked the "view job" 

![transactions](https://user-images.githubusercontent.com/220994/45239334-d3ac3000-b2b2-11e8-9342-95de34c66dcc.png)

But the result was a 404.  Also tried with the other services and got the same thing.  

Perhaps this is due to ML jobs being created, deleted, and re-created in that env?

**Comment by sqren** [comment]
Fixed in #22820

**Comment by sqren** [comment]
Fixed in https://github.com/elastic/kibana/pull/22820
