### ISSUE TITLE
Investigate indexing `span.context.db.*`

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1371]
Currently `span.context.db.*` properties are stored but not indexed in ES. This makes it impossible to query/aggregate on them, which might be helpful for multiple use cases (aggregate on them to figure out occurence of queries per type, problematic instances, etc.).

Suggested solution:

attribute | type | description | index type | limit (server) | limit (agent) | note
-- | -- | -- | -- | -- | -- | --
instance | string | db instance name | keyword | 1024 | 1024 | -
user | string | username for accessing db | keyword | 1024 | 1024 |-  
type | string | database type | keyword | 1024 |  1024| -
statement | string | concrete query | text | none | ? | should be sanitized for grouping

**Comment by alvarolobato** [comment]
We discussed this in the server meeting. Originally these fields were removed from the indexes because we where concerned for the disk space usage. We've decided to document how to add these fields to the index in `fields.yml` instead of indexing it by default.

**Comment by graphaelli** [comment]
After some investigation and discussion with the beats team, the fields.yml approach seems too manual and error prone to be the right long-term solution.  Most notably, upgrades become very manual, with merging new fields with user-modified fields.yml.  

Adding discuss label for brainstorming alternative solutions.

**Comment by roncohen** [comment]
there's `setup.template.append_fields` which allows users to add arbitrary fields to the template: https://www.elastic.co/guide/en/beats/filebeat/6.x/configuration-template.html

seems slightly better than asking people to edit their `fields.yml`

**Comment by simitt** [comment]
This is still marked as experimental though (although it landed quite a while ago, see https://github.com/elastic/beats/pull/6024/files). Did you talk to the beats team if there are plans to make this feature stable?

**Comment by roncohen** [comment]
Related: https://github.com/elastic/beats/issues/8607

**Comment by ruflin** [comment]
+1 on making append_fields GA. The main challenge I see around it is that users will add fields after they did run the Beat for the first and will have to overwrite the template to make use of it. We should solve this by docs and think about other options how to raise awareness.

**Comment by simitt** [comment]
The docs already mention when `append_fields` can be used, how to overwrite the template and when template changes are applied. With https://github.com/elastic/beats/pull/16576 the `experimental` flag from `append_fields` will be removed.

**Comment by tobiasstadler** [comment]
What is the status? Are their plans to index the fields by default?

**Comment by simitt** [comment]
@tobiasstadler we don't have any plans to index additional span fields, but the [`setup.template.append_fields`](https://www.elastic.co/guide/en/apm/server/current/configuration-template.html) setting has been released as GA for a while. Are you able to achieve what you need by making use of this setting?

**Comment by tobiasstadler** [comment]
@smith Yes, that works for me. Thank You!

**Comment by simitt** [comment]
Closing this issue since we don't have plans to work on this.
