### ISSUE TITLE
Document importance of `output.elasticseach.indices` 

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-server#1372]
Currently, the APM UI "breaks" (as in, shows no data) if the `output.elasticsearch.indices` section in `apm-server.yml` is removed or substantially changed. The documentation doesn't make that dependency between the APM Server configuration and the APM UI clear.

Possible locations for adding such a warning/note:

https://www.elastic.co/guide/en/apm/server/6.4/apm-server-configuration.html
https://www.elastic.co/guide/en/apm/server/6.4/elasticsearch-output.html
https://www.elastic.co/guide/en/apm/server/6.4/elasticsearch-output.html#_literal_indices_literal

**Comment by simitt** [comment]
@beniwohli I gave this another thought, and as this is currently considered a bug and will be fixed with the `6.4.1` release, I'll consider documenting the introduced issue in the [Release Notes](https://www.elastic.co/guide/en/apm/get-started/current/apm-release-notes.html#_breaking_changes) to be sufficient. WDYT?

**Comment by beniwohli** [comment]
So in 6.4.1+, `output.elasticsearch.indices` can be removed/changed at will without effect on the APM UI?

**Comment by simitt** [comment]
Yes the default pattern for querying indices is changed to `apm-*`, see the [fix in Kibana](https://github.com/elastic/kibana/pull/22854). The users can overwrite the configurations if they want to leverage having `events` split into separate indices.

**Comment by beniwohli** [comment]
@simitt Do you think it would still make sense to document in https://www.elastic.co/guide/en/apm/server/6.4/elasticsearch-output.html#_literal_indices_literal that deviating from `apm-*` breaks the APM UI and needs analogous changes in the APM UI settings?

With the example in the docs, the APM UI wouldn't find any errors anymore AFAICT.

**Comment by simitt** [comment]
I'll add it once 6.4.1 is out.
