### ISSUE TITLE
Update Elastic apm go agent

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1381]
May need to update `go-sysinfo` first.

**Comment by axw** [comment]
might need to get rethink how (or if) spans are created with v2, I think each request may now yield many calls into the beats pipeline

**Comment by graphaelli** [comment]
Great point @axw, created #1385 for that. Will continue to use this issue for updated apm-agent-go to the latest release instead.

**Comment by graphaelli** [comment]
closed by #1387
