### ISSUE TITLE
[v2] Update Instrumentation

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1385]
Per https://github.com/elastic/apm-server/issues/1381#issuecomment-420688708, we may want additional instrumentation specifically for v2.

**Comment by axw** [comment]
maybe s/additional/alternative/

(I think we'll now see many spans for calling into the beats publishing pipeline for each request/transaction, which is probably not that useful or helpful.)

**Comment by graphaelli** [comment]
@axw Opened #1420 to reduce the span count as the current instrumentation isn't helpful as you expected.  Leaving this open after that goes in to track progress on useful v2 instrumentation.
