### ISSUE TITLE
8.15.1 Test plan

### ISSUE THREAD

**Issue by inge4pres** [elastic/apm-server#13965]
# Manual Test Plan

List of changes: https://github.com/elastic/apm-server/compare/v8.15.0...8.15

Changes to be tested

- [x] https://github.com/elastic/apm-server/pull/13838 [@kruskall]
- [ ] https://github.com/elastic/apm-server/pull/13918 (already tested by @lahsivjar and @endorama, but should be tested again)

## go-docappender library

go-docappender version upgrade: [v2.1.4 -> v2.2.1](https://github.com/elastic/go-docappender/compare/v2.1.4...v2.2.1)

- [x] https://github.com/elastic/go-docappender/pull/177 @carsonip 
- [x] https://github.com/elastic/go-docappender/pull/182 @carsonip 
- [x] https://github.com/elastic/go-docappender/pull/190 @endorama 

## apm-data library

apm-data version upgrade: [v1.8.4 -> v1.9.1](https://github.com/elastic/apm-data/compare/v1.8.4...v1.9.1) 

- [x] https://github.com/elastic/apm-data/pull/321 @inge4pres 
- [x] https://github.com/elastic/apm-data/pull/323 @inge4pres 
- [x] https://github.com/elastic/apm-data/pull/327 @carsonip

**Comment by inge4pres** [comment]
@axw @lahsivjar @simitt please confirm if the ILM/DLM change will be pushing the release deadline.

**Comment by inge4pres** [comment]
Tested the added feature for the Java agent, with the help of the author


![Image](https://github.com/user-attachments/assets/e85acd99-607f-423f-b2c8-05202b24ade9)

**Comment by endorama** [comment]
Tested https://github.com/elastic/go-docappender/pull/190 with: `v8.15.0` vs `8.15` and `main` branch. Logs do not contain the mentioned details so ✅ 

<details><summary>Details</summary>

Using apm-server v8.15.0 and `8.15`.

To reproduce:
- I started the stack with Docker Compose in `apm-server`
- started sending data with `apmsoak`, `apm-server` scenario
- stopped `apmsoak`
- added Ingest pipeline `logs@custom` with content 
  ```
  [
    {
      "json": {
        "field": "error.culprit"
      }
    }
  ]
  ```
  following the recomendation in https://github.com/elastic/apm-managed-service/issues/927#issuecomment-2255690982
- started `apmsoak` again (I've used a less intensive scenario):
  ```
    apm-server3:
      - event_rate: 10/1s
        agent_name: apm-go
        agent_replicas: 1
  ```

I run with with `apm-server` `v8.15.0` tag and `8.15` branch.

`v8.15.0` logs:
```
{"log.level":"error","@timestamp":"2024-09-02T16:47:02.656+0200","log.origin":{"function":"github.com/elastic/go-docappender/v2.(*Appender).flush","file.name":"v2@v2.1.4/appender.go","file.line":403},"message":"failed to index documents in 'logs-apm.error-default' (x_content_parse_exception): [1:17] Unrecognized token 'logrusMiddleware': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (String)\"logrusMiddleware\"; line: 1, column: 17]","service.name":"apm-server","documents":2,"ecs.version":"1.6.0"}
```

to `8.15`

```
{"log.level":"error","@timestamp":"2024-09-02T16:57:56.213+0200","log.origin":{"function":"github.com/elastic/go-docappender/v2.(*Appender).flush","file.name":"v2@v2.2.1/appender.go","file.line":443},"message":"failed to index documents in 'logs-apm.error-default' (x_content_parse_exception): ","service.name":"apm-server","documents":2,"ecs.version":"1.6.0"}
```

I run the same test with `main`, and it shows the same behavior.

</details>

**Comment by inge4pres** [comment]
Testing completed by Vishal for the ILM/DLM changes.
Thanks a lot @carsonip @endorama @kruskall @lahsivjar
