### ISSUE TITLE
Update indirect dependency opentelemetry-lib to 0.9.0

### ISSUE THREAD

**Issue by tskorupka** [elastic/apm-server#14002]
Hey,

apm-server in 8.15.x uses opentelemetry-lib in version 0.7.x

opentelemetry-lib 0.9.0 introduces changes in hostmetric scrapers interface changes, see https://github.com/elastic/opentelemetry-lib/releases/tag/v0.9.0

When we can expect newer version of apm-server with the updates?

This prevents us from using opentelemetry collectors in v0.108.0 :(

Kind Regards,
Tomasz

**Comment by tskorupka** [comment]
Hey,

Sorry, I meant it uses 0.7.x,

I would like to raise a request to update it to 0.8.x

Tomasz

**Comment by tskorupka** [comment]
> Could you clarify this ? what's the impact on the collector ?

hostmetrics scraper labels/ids changed in otel 0.107.0 (format), when we have updated otel collector to newest version, 0.108.0 we no longers see host metrics in elastic apm.

Tomasz

**Comment by lahsivjar** [comment]
The opentelemetry-lib dependency is via apm-data. The dependencies are auto-upgraded and I can see an upgrade PR created: https://github.com/elastic/apm-data/pull/357

Also, main already uses 0.8.1 now: https://github.com/elastic/apm-server/blob/a7de634679ae20f03009ee3cdf8b08a45a70ddaf/go.mod#L93

The changes should be released with apm-server v8.16.0
