### ISSUE TITLE
OTel data stream routing does not sanitize values

### ISSUE THREAD

**Issue by carsonip** [elastic/apm-server#14043]
OTel data stream routing implemented in elastic/apm-data#201 does not sanitize values, i.e. a `-` in the supplied dataset / namespace will go through the logic and result in non-compliant data stream name. There are more rules to observe, see in https://www.elastic.co/guide/en/ecs/current/ecs-data_stream.html . There is also an [implementation of DS fields sanitization in ES](https://github.com/elastic/elasticsearch/blob/33d63fa9c2fc3afb9184f31e2681942cfd8dc7fd/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RerouteProcessor.java#L203-L206), but there are also issues with Elasticsearch's implementation as stated in https://github.com/elastic/elasticsearch/issues/112936

The bugfix can be a breaking change for existing users and should be stated as such in changelog.

Equiv task in es exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34285

**Comment by simitt** [comment]
> The bugfix can be a breaking change for existing users and should be stated as such in changelog.

Let's call it out in the release notes to make users aware, but generally I would see this as a bugfix.
