### ISSUE TITLE
Java Agent

### ISSUE THREAD

**Issue by friesoft** [elastic/apm-server#142]
Are there any plans to create a java agent to report java internal metrics (jvm memory, jmx, threads, ...) and stuff like backend calls (webservices, database, ...)

Related products:
* New Relic Java Agent: https://newrelic.com/java
* CA APM Java Agent: https://docops.ca.com/ca-apm/10-5/en/implementing-agents/java-agent

**Comment by makwarth** [comment]
Hey there! Java is definitely high on the list, but no timelines yet. I'll close the issue, but your input has been noted. Thanks for reaching out!

**Comment by ruflin** [comment]
Some discussion from the community side about which agents should be next also going on here :-) https://discuss.elastic.co/t/next-apm-agent/99900/3
