### ISSUE TITLE
adapting an existing agent to apm-server

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-server#1426]
Hi,

I'm running my own java agent on multiple applications. I actuallly send data to logstash and want to migrate to apm-server.

I noticed some differences between my data model and what the apm-server intake api (v1) allows .

The main differences are the ability to
- send metrics and counters such as memory/cpu/jvm consumption
- send spans independently from transaction (useful for very long transactions, or distributed tracing)
- correlate server side transaction with end used (rum) transaction 

My question is to know if the v2 api will support those features ?

**Comment by simitt** [comment]
`v2` allows for sending `spans` separated from `transactions`. It also introduces a `trace_id` which can be used to link together `transactions` from different `services`. There are two meta issues describing changes in v2: https://github.com/elastic/apm-server/issues/1237 and https://github.com/elastic/apm-server/issues/1390. 

There is an experimental endpoint for sending `metrics` already in [v1](https://github.com/elastic/apm-server/blob/master/beater/handlers.go#L61). 

You can also check out the official [Java agent](https://www.elastic.co/guide/en/apm/agent/java/current/index.html) and the [RUM agent](https://www.elastic.co/guide/en/apm/agent/js-base/current/index.html).

**Comment by alvarolobato** [comment]
I'm closing this issue, let us know if you have any further questions. Also feel free to use the discuss APM forums to ask question https://discuss.elastic.co/c/apm
