### ISSUE TITLE
APM agent for Rust

### ISSUE THREAD

**Issue by u238** [elastic/apm-server#1431]
It would be nice to have an APM agent for Rust.

**Comment by alvarolobato** [comment]
Hi, have evaluated it and we don't plan to create an agent for Rust in the mid term.

There is an alternative to having one which is using our [Rest API](https://www.elastic.co/guide/en/apm/server/current/intake-api.html) to send trace data directly from your application. It involves a lot more work tough.

Thank you for your interest.

**Comment by vsotog** [comment]
> Hi, have evaluated it and we don't plan to create an agent for Rust in the mid term.
> 
> There is an alternative to having one which is using our [Rest API](https://www.elastic.co/guide/en/apm/server/current/intake-api.html) to send trace data directly from your application. It involves a lot more work tough.
> 
> Thank you for your interest.

Is this still valid?
