### ISSUE TITLE
[v2] Add concurrency tests

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1432]
Data from different agents shouldn't be mixed up

**Comment by jalvz** [comment]
cc @roncohen maybe you worked on / tested this already? 
I didn't find any explicit mentions, so lmk if I just missed it!

**Comment by simitt** [comment]
We have some automated [concurrency tests](https://github.com/elastic/apm-integration-testing/blob/master/tests/agent/test_multiple_agents.py) in the integration testing repo, testing that data from agents are not mixed up. But we are not testing `v2` branch against anything (see [server versions](https://github.com/elastic/apm-integration-testing/blob/master/tests/versions/apm_server.yml)) atm. I created an Issue https://github.com/elastic/apm-integration-testing/issues/193 for updating test matrix. 

I think it would make a lot of sense to do some manual testing with hey-apm against the current v2 server input though, to see how the server behaves under load with the newly added and some dropped config settings (e.g. concurrency limit).

**Comment by jalvz** [comment]
checked that transactions and spans link correctly to each other, belong to the right service and don't get mixed up (eg. sending data from different agents and services at a time).
did this by linking spans and transactions and adding tags to their names, eg. per service and agent, and firing requests with multiple services and agents concurrently.
used a variation of https://github.com/jalvz/hey-apm/tree/simulate-agents
