### ISSUE TITLE
Add additional fields to `span.context.http`. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1435]
```
{
  "context": {
    "http": {
      "status_code": 201,
      "method": "PUT"
    }
  }
}
```

`status_code`: optional, long
`method`: optional, keyword

**Comment by watson** [comment]
I might have misunderstood, but I think we agreed to add `context.http.url` as well right?

cc @jahtalab @eyalkoren

**Comment by simitt** [comment]
[span.context.http.url](https://github.com/elastic/apm-server/blob/master/docs/spec/transactions/span.json#L39) is already available.

**Comment by watson** [comment]
Oh, didn't know. Carry on 😄
