### ISSUE TITLE
Add `max_event_size` config option to apm-server.yml

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1454]
With https://github.com/elastic/apm-server/pull/1352 support for having a `max_event_size` was added. The config option was not documented in the `apm-server.yml`.

**Comment by roncohen** [comment]
@alvarolobato @jalvz  this is done, right?

**Comment by jalvz** [comment]
yes! did Zube automatically reopened this...?

**Comment by alvarolobato** [comment]
No, it says I reopened it, but I really don't remember why I did. By the date it seems it was during the server meeting 🤷‍♂️
