### ISSUE TITLE
APM Server 8.17 test plan

### ISSUE THREAD

**Issue by 1pkg** [elastic/apm-server#14695]
# Manual Test Plan

List of changes: https://github.com/elastic/apm-server/compare/8.16...8.17

When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished.
Testing can be started when the first build candidate (BC) is available in the CFT region.

## Smoke Testing ESS setup

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now.
**Consider extending the smoke tests to include more test cases which we'd like to cover**

## go-docappender library

- [x] https://github.com/elastic/go-docappender/pull/206 [@carsonip ]
- [x] https://github.com/elastic/go-docappender/pull/209 [@1pkg @kruskall ]

## apm-data ES plugin

- [x] https://github.com/elastic/elasticsearch/pull/116995 [@lahsivjar ]
- [x] https://github.com/elastic/elasticsearch/pull/115687 [@1pkg @simitt]

## Test cases from the GitHub board

Add yourself as _assignee_ on the PR before you start testing.

- [x] https://github.com/elastic/apm-server/pull/14551 [@endorama ]
- [x] https://github.com/elastic/apm-server/pull/14574 [@1pkg @rubvs ]
- [x] https://github.com/elastic/apm-server/pull/14865 [@carsonip ]

**Comment by endorama** [comment]
✅ for the scroll request fix, I uploaded ~200 source maps, the scroll context after ingesting was `0`.

**Comment by rubvs** [comment]
Left a comment: https://github.com/elastic/apm-server/pull/14574#issuecomment-2537789018
