### ISSUE TITLE
Potentially flaky rate limit test

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1521]
This PR ran into what seems to be a flaky test: https://github.com/elastic/apm-server/pull/1518

The job that failed:
https://apm-ci.elastic.co/job/elastic+apm-server+pull-request+multijob-windows/beat=apm-server,label=windows/15/console

```
13:17:17 Package: github.com/elastic/apm-server/processor/stream
13:17:17 Test:    TestRateLimiting
13:17:17 Error: go test failed: 1 test failures
13:17:17 approvals.go:50: 
13:17:17 		Error Trace:	approvals.go:50
13:17:17 		            				stream_processor_test.go:49
13:17:17 		            				stream_processor_test.go:174
13:17:17 		Error:      	Test approved-stream-result/testIntegrationResultLimiterPartiallyUsedLimitAllow failed with error: Received data differ from approved data. Run 'make update' and then 'approvals' to verify the Diff.
13:17:17 		Test:       	TestRateLimiting
13:17:17 ----
```

A rerun here passed: https://apm-ci.elastic.co/job/elastic+apm-server+pull-request+multijob-windows/beat=apm-server,label=windows/17/console

**Comment by simitt** [comment]
@ron have you ever been able to reproduce this test failure locally? I've never seen that on Jenkins again, and cannot reproduce. I suggest to close this, assuming it was fixed by something else, except if anyone has seen / can reproduce?

**Comment by roncohen** [comment]
OK, closing for now
