### ISSUE TITLE
Update examples documents for docs

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1532]
Update examples for Intake API and ES for all event types related to distributed tracing changes.

**Comment by simitt** [comment]
@bmorelli25 what do you think about getting rid of the examples per event type and instead adding a subsection `Example` after `Metricsets`:
 
![screen shot 2018-11-09 at 09 17 00](https://user-images.githubusercontent.com/5555349/48250962-58751080-e400-11e8-8518-a9a964ac332e.png)

with one example including the `metadata` and all `events`. 

I'd like to keep the process of automatically copying over some of the testdata we use, as this guarantees that the examples we show are up to date, and suggest to use this file as example: 
https://github.com/elastic/apm-server/blob/master/testdata/intake-v2/events.ndjson

**Comment by bmorelli25** [comment]
That's a great idea! Keeping the process automatic is important. I'll add it in.

**Comment by simitt** [comment]
@bmorelli25 I created https://github.com/bmorelli25/apm-server/pull/2 where I updated the generation of the doc files and a suggestion for how to include into the doc files.

**Comment by bmorelli25** [comment]
Merged 👍
