### ISSUE TITLE
Sourcemap upload does not recognize fields with a content-type

### ISSUE THREAD

**Issue by pgross41** [elastic/apm-server#1533]
Fields in multipart/form-data [may optionally have a Content-Type](https://tools.ietf.org/html/rfc7578#section-4.4). However, APM Server does not see these fields if a content type is provided. 

#### A request like this is accepted: 
```
--------------------------1541659240356
Content-Disposition: form-data; name="service_name"

my-service-name
--------------------------1541659240356
Content-Disposition: form-data; name="service_version"

1.0.0
--------------------------1541659240356
Content-Disposition: form-data; name="bundle_filepath"

http://localhost/js/main.js
--------------------------1541659240356
Content-Disposition: form-data; name="sourcemap"; filename="main.js.map"
Content-Type: application/octet-stream

{"version":3,"sources":[],"names":[],"mappings":"","file":"","sourcesContent":[],"sourceRoot":""}
--------------------------1541659240356--
```

#### However, a request like this returns:
 `data validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"sourcemap#\"\n  I[#/service_version] S[#/properties/service_version/minLength] length must be \u003e= 1, but got 0`
```
--------------------------1541659240356
Content-Disposition: form-data; name="service_name"
Content-Type: text/plain

my-service-name
--------------------------1541659240356
Content-Disposition: form-data; name="service_version"
Content-Type: text/plain

1.0.0
--------------------------1541659240356
Content-Disposition: form-data; name="bundle_filepath"
Content-Type: text/plain

http://localhost/js/main.js
--------------------------1541659240356
Content-Disposition: form-data; name="sourcemap"; filename="main.js.map"
Content-Type: application/octet-stream

{"version":3,"sources":[],"names":[],"mappings":"","file":"","sourcesContent":[],"sourceRoot":""}
--------------------------1541659240356--
```

Notice the only difference is the text fields have a Content-Type of text/plain (which is allowed  for multipart/form-data). It is an issue because some HTTP libraries add that Content-Type automatically.

**Comment by graphaelli** [comment]
Hi @pgross41, sorry for the lack of response on this one.  I've just [tried to reproduce](https://github.com/elastic/apm-server/compare/master...graphaelli:sourcemap-content-type) this issue without success - can you verify whether this is still an issue?

**Comment by pgross41** [comment]
I don't remember what version was used when I logged this but I just tried again with 6.5.4 and it is working as expected, thanks for the follow-up.

**Comment by graphaelli** [comment]
Excellent, thanks for checking back in.
