### ISSUE TITLE
APM Server should support Beats central configuration

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-server#1539]
Beats team is working on centralized configuration for all the beats, APM server should support using it to set its configuration.
We will need to coordinate with the beats team to agree on APM specifics ie. Different UI.

Reference: https://github.com/elastic/beats/issues/7028

Note: Issues on Apm-server, Kibana and any other related repos should be created to implement the changes

**Comment by jalvz** [comment]
@alvarolobato are you ok closing this for the time being and create a new one when the opportunity comes around?

**Comment by alvarolobato** [comment]
Yes, I'm ok with it.
