### ISSUE TITLE
Come up with scalable values for config settings on cloud

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1544]
Goal is to come up with config option values for different deployment scenarios for APM on cloud.

**config settings to investigate**:
`queue.mem.events`, `queue.mem.flush.min_events`, `queue.mem.flush.timeout`, `output.elasticsearch.worker`, `output.elasticsearch.max_bulk_size`, `output.elasticsearch. compression_level`

**related issues**
[APM Server horizontal scaling](https://github.com/elastic/apm-server/issues/1321)
[APM Server vertical scaling](https://github.com/elastic/apm-server/issues/1414)

**Comment by jalvz** [comment]
This is *only* for cloud, or generally?

Note: also consider https://www.elastic.co/guide/en/elasticsearch/reference/current/indexing-buffer.htm

**Comment by simitt** [comment]
This is meant to be specifically for cloud. We might derive some general recommendations from this though. 
I don't think we can mess with the `indexing-buffer` settings from APM Server on cloud, as we don't have any information about the ES cluster. Those settings need to be changed by the customer if necessary.

**Comment by JCMais** [comment]
If possible also include logstash output settings in the fields to investigate.
