### ISSUE TITLE
Update APM release notes for 6.5

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1554]
@elastic/apm-agent-devs and @elastic/apm-ui we need to update the APM release notes https://www.elastic.co/guide/en/apm/get-started/current/apm-release-notes.html. Please drop a line here what should be added for your agents. For 6.4 the notes were pretty high level.

**Comment by beniwohli** [comment]
Python: 

 * use `contextvars` instead of thread locals for context tracking in Python 3.7
 * Support for intake v2 API and distributed tracing (I guess this could be an overall item for all agents)

**Comment by axw** [comment]
Go:

- The Go agent is now generally available. This version requires APM Server v6.5 or later.
- The canonical import path is now "go.elastic.co/apm", and top-level package name is "apm"
- Added support APM Server intake API version 2
- Added support for Distributed Tracing
- Added support for multiple APM Servers, with failover
- Added support for mixing OpenTracing spans with native transactions/spans
- Added instrumentation for gomodule/redigo
- Added instrumentation for go-restful

**Comment by simitt** [comment]
closed with #1555 

@axw should we add the additional information in a separate PR?

**Comment by axw** [comment]
@simitt ah didn't see that. No, I think what you have there is good enough.
