### ISSUE TITLE
docs: server SSL config is hiding

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#1579]
I went looking in the server docs to see how to configure the server to require TLS. I immediately went to "Configuring APM Server", and then figured "Specify SSL settings" would be a good bet. I lost the bet, it's only for configuring certs for Elasticsearch and Logstash.

Next I expanded "Securing APM Server" and found sub sections for, again, configuring ES/Logstash config, and also X-Pack and seccomp. Finally, I looked in the top level "Securing APM Server" page and found it there.

I think we should:
 - Add a section to "Configuring APM Server > Specify SSL settings" about configuring the server's own certificates for agent->server comms.
 - Add a page to "Securing APM Server" about the secret token and cert so they show in the TOC. We might want to expand that page to give pointers on generating self-signed certs for private network deployments.

Also related: https://discuss.elastic.co/t/authentication-of-rum-event-post-from-browser/197655

**Comment by bmorelli25** [comment]
@axw - There's currently a redesign of the beats security documentation and this is the perfect time to implement these changes.

In regards to the two statements below, are you someone that could walk me through these ideas so I can document them? Or should I meet with someone on the server team instead? This is not a topic I'm very familiar with. 

> Add a section...about configuring the server's own certificates for agent->server comms

> ...expand [securing APM Server] to give pointers on generating self-signed certs for private network deployments.

**Comment by axw** [comment]
@bmorelli25 I can help, but I think it would be more useful to speak to someone on the server team. I find that going through a documentation exercise can sometimes lead to ideas to simplify/improve code and configuration, and the server team would be best placed to do that.

**Comment by simitt** [comment]
@bmorelli25 I'll take a look at current status and open points, and happy to set something up to discuss it through then with you.

**Comment by bmorelli25** [comment]
Thanks @simitt, sounds like a plan.
