### ISSUE TITLE
Concerns regarding monitoring data 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1614]
Looking at monitoring data some values look slightly off:
- [x] Responses `ok`+`accepted`+`failed` do not always sum up to `all`. Could this be due to connections that are terminated by a proxy?
- [x] CPU usage seems too low. Has anything changed in how cpu gets reported or in the calculation? 
- [ ] Viewing `Requests` before `Output Events Rate` might be a more user friendly order to show the metrics.

![screen shot 2018-12-03 at 18 22 53](https://user-images.githubusercontent.com/5555349/49390206-97a92f80-f728-11e8-8fc3-10dde3fd784a.png)

**Comment by simitt** [comment]
> Responses ok+accepted+failed do not always sum up to all. Could this be due to connections that are terminated by a proxy?

We miss `response.errors.internal` in the monitoring tab, so `5xx` errors are not shown currently.

**Comment by simitt** [comment]
> CPU usage seems too low. Has anything changed in how cpu gets reported or in the calculation? 

Created a bug report in https://github.com/elastic/beats/issues/9377

**Comment by graphaelli** [comment]
For the internal error reporting, status is:

master
- [x] es: https://github.com/elastic/elasticsearch/pull/36178
- [ ] kibana: https://github.com/elastic/kibana/pull/26570

6.x
- [ ] es: https://github.com/elastic/elasticsearch/pull/36319
- [ ] kibana: (to be created once ^ is merged and makes it to a snapshot)

6.5
- [x] es: https://github.com/elastic/elasticsearch/pull/36273, in for 6.5.3
- [x] kibana: https://github.com/elastic/kibana/pull/26787 not in for 6.5.3

**Comment by simitt** [comment]
There's a PR up for the CPU usage fix: https://github.com/elastic/kibana/pull/27060

**Comment by simitt** [comment]
PR merged for CPU usage fix https://github.com/elastic/kibana/pull/27416
