### ISSUE TITLE
Investigate behaviour on 503s. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1638]
Run some tests locally / on cloud where 503s are returned and check whether events are still written to ES while 503s are returned.

**Comment by simitt** [comment]
I tried to reproduce this behaviour on a local setup, and saw a similar but not the same behaviour as I saw on cloud. 

Steps to reproduce:
- setup apm server and ES. Use changed settings in the `apm-server.yml` (for local reproduction, might not be necessary to reproduce):
```
apm-server.concurrent_requests:1
queue.mem.events: 1000
queue.mem.flush.min_events: 1250
output.elasticsearch.worker: 4
output.elasticsearch.max_bulk_size: 1250
```
- create load with https://gist.github.com/graphaelli/22ff5736a68c99ade50573041751e35b, which is using the go agent, e.g. `ELASTIC_APM_SERVER_URL=http://localhost:8200 AGENTS=200 RUN_TIMEOUT=600s make run-multi`. Ensure to produce enough load so that a large spike of 503s happens

The observed behaviour on cloud, that data output to ES drops to 0, when large 503 spikes are returned was not reproducable with my local setup. But I observed similar behaviour that the output to ES decreased significantly when 503s occured. 
The used ES instance for testing on cloud was large enough to ensure it was not the bottleneck.

Behaviour in cloud setup (gcp):
![screen shot 2018-12-12 at 13 56 01](https://user-images.githubusercontent.com/5555349/49871289-17648780-fe16-11e8-8bc3-516c3fab3172.png)


Behaviour in local setup:
![screen shot 2018-12-12 at 13 58 43](https://user-images.githubusercontent.com/5555349/49871279-116ea680-fe16-11e8-8a11-2e9ea54092a0.png)

**Comment by nachogiljaldo** [comment]
We did a test on production's GCP region where we enabled compression, that made the 503s where no output is sent to ES disappear.
The next thing we tried was increasing apm-server.read_timeout even further which removed some 504s we observed on the previous test.
