### ISSUE TITLE
launching apm-server in backgroup from vagrant ssh causes shell to hang

### ISSUE THREAD

**Issue by LeeDr** [elastic/apm-server#1646]
In a private elastic/integration-test repo, I have tests that use vagrant to create instances of different operating systems and install most of the build artifacts on them, including apm-server.  
I don't have any problems when I start the apm-server service for the .deb or .rpm packages.  But I'm having problems on 6.5.3 when I start the process detached in the background from the tar.gz package on Ubuntu (I think the problem started right at 6.5.0 but not 100% sure yet).

One outer bash script jenkins_test.sh does this call after the VM has been provisioned.
`time vagrant ssh $vm -c "sudo /vagrant/qa/phase2.sh"  -- -t`

It's hard to find documentation on the `-- -t` extra args I used above.  Here's some snippets I found online;
"-t parameter to SSH which will open a pseudo-tty"
"-t option forces pseudo-tty allocation. So interactive programs such as top can be executed"
I thought this could be the problem but it seems to hang regardless of removing that.  And this same code works on 6.4.3.  I just ran another test on Jenkins without the `-- -t` and it hung on 6.5.

And that phase2.sh calls configure_start_apm.sh.

And configure_start_apm.sh starts apm-server like this;
`su vagrant -c "nohup $INSTALL_DIR/apm-server/apm-server -e --path.config ${CONFIG_DIR}/apm-server/ &"`
(reference https://www.vagrantup.com/docs/cli/ssh.html#background-execution)

On the 6.4.3 released build, when phase2.sh completes, the process returns control to jenkins_test.sh and the script continues and runs tests.
But on 6.5.x I see the logging that it got to the end of phase2.sh but just hangs there.

But I'm only having this problem on Jenkins.  When I run this locally (or other Kibana-QA people run it locally) it doesn't hang.  Of course this makes it pretty hard to debug.  Jenkins workers are Linux, I'm on Windows, other Kibana-QA are on OSX.  I have a Linux machine at home too so I can see if I can reproduce it there.

I just made Jenkins run the exact same scripts on the released 6.4.3 build and it didn't hang.  So it can't be the version of Vagrant causing the issue (Vagrant 2.2.2) or any changes in the setup.

**Comment by LeeDr** [comment]
I forgot to mention, the user can ignore the error and continue to create a cross cluster index pattern, and everything else seems to work in using that index pattern.  So this is just an unpleasant error.

**Comment by graphaelli** [comment]
@LeeDr Is this still an issue?  I don't know how to address this.

**Comment by LeeDr** [comment]
I'm not sure what changed but I see (on 7.2.0 now) that I'm running the exact same command still;
`su vagrant -c "nohup $INSTALL_DIR/apm-server/apm-server -e --path.config ${CONFIG_DIR}/apm-server/ &"`
and it's working OK.
