### ISSUE TITLE
Support wildcards in bundle_filepath when looking up source maps

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#1649]
This is useful for websites that have many subdomains and it would be impractical to upload the source map file for each one of them.

[discuss reference](https://discuss.elastic.co/t/apm-rum-agent-source-maps-for-multiple-subdomains/160426)

**Comment by steve21168** [comment]
This feature would be greatly appreciated.  Any organization who provides subdomains on a per client basis will run into this issue.

**Comment by jalvz** [comment]
@steve21168 this will be included in the 6.6 release, which will be out very soon.
You don't need to set any wildcards, but after upgrading you need to upload the sourcemap again in the same way as before.
I hope that helps!

**Comment by wangking873** [comment]
It is recommended to match only resource paths and source maps

No, service.name

No, service.version

Only bundle_ filepath



https://cdn.xxx.com/ [hash]/ xxx.js -> sourceMap

**Comment by steve21168** [comment]
@jalvz This was previously working but is now no longer matching my existing sourcemap on `7.9.2`.  Was there any known changes that break this?
