### ISSUE TITLE
Forward validation errors to agents

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-server#166]
The apm server helpfully spits out great validation error messages if a payload fails the JSON Schema validation:

    2017/09/13 09:12:20.138559 server.go:164: INFO Data validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "error#"
      I[#/errors/0/log] S[#/properties/errors/items/properties/log/required] missing properties: "message", code=400

This is great, but all the agent gets back is an empty `400 Bad Request` response. It would be great if the validation error message could be returned to the agent, e.g. as a JSON payload.

**Comment by watson** [comment]
We had a discussion about error responses in #6 and we implemented changes in #37, so it should already reply with the validation error. But maybe something broke along the way?

**Comment by beniwohli** [comment]
Weird. Just verified that I get back an empty response. Can you check with the Node agent, @watson?

**Comment by watson** [comment]
@beniwohli I just tested it with curl from the latest master. Here's the results. I think the issue is that the server sends back `Content-Type: text/plain; charset=utf-8` even though the body is JSON -
 which obviously is wrong.

With curl default (`Accept: */*`):

```
$ curl -v -X POST -H 'Content-Type: application/json' -d '{"app":{"name":"foo","agent":{"name":"foo","version":"1"}},"errors":[{"timestamp":"2017-01-01T00:00:00+00:00","log":{"message":"foo"}}]}' localhost:8200/v1/errors
> POST /v1/errors HTTP/1.1
> Host: localhost:8200
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 136
>
< HTTP/1.1 400 Bad Request
< Date: Wed, 13 Sep 2017 11:09:06 GMT
< Content-Length: 325
< Content-Type: text/plain; charset=utf-8
<
{"error":"Data Validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"error#\"\n  I[#/errors/0/timestamp] S[#/properties/errors/items/properties/timestamp/pattern] does not match pattern \"^(\\\\d{4})-(\\\\d{2})-(\\\\d{2})T(\\\\d{2}):(\\\\d{2}):(\\\\d{2})(\\\\.\\\\d{1,6})?Z$\""}%
```

With curl and the header `Accept: application/json`:

```
$ curl -v -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"app":{"name":"foo","agent":{"name":"foo","version":"1"}},"errors":[{"timestamp":"2017-01-01T00:00:00+00:00","log":{"message":"foo"}}]}' localhost:8200/v1/errors
> POST /v1/errors HTTP/1.1
> Host: localhost:8200
> User-Agent: curl/7.54.0
> Content-Type: application/json
> Accept: application/json
> Content-Length: 136
>
< HTTP/1.1 400 Bad Request
< Date: Wed, 13 Sep 2017 11:09:30 GMT
< Content-Length: 325
< Content-Type: text/plain; charset=utf-8
<
{"error":"Data Validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"error#\"\n  I[#/errors/0/timestamp] S[#/properties/errors/items/properties/timestamp/pattern] does not match pattern \"^(\\\\d{4})-(\\\\d{2})-(\\\\d{2})T(\\\\d{2}):(\\\\d{2}):(\\\\d{2})(\\\\.\\\\d{1,6})?Z$\""}%
```

**Comment by watson** [comment]
I changed this to a bug as it's not working as intended

**Comment by beniwohli** [comment]
OK, turns out I was using urllib3 wrong :( (in my defense, there are several stackoverflow questions and urllib3 bug reports that are similarly confused)

@watson should we close this and open another issue specific to the buggy `content-type`?

**Comment by watson** [comment]
@beniwohli good idea
