### ISSUE TITLE
Investigate to move `transaction.span_count.dropped.total` to `transaction.span_count.dropped`

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1675]
Move `transaction.span_count.dropped.total` to `transaction.span_count.dropped` so it's at the same level as transaction.span_count.started and aligns with the v2 intake protocol.

I don't see how we can change that without conflicting with 6.x indices, as the type of the ES field would change.

**Comment by jalvz** [comment]
This can be done with the reindexing script

**Comment by graphaelli** [comment]
FYI @elastic/apm-ui, field rename not related to ECS
