### ISSUE TITLE
Investigate auto-setting config options related to ES output based on other config values. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1676]
As figured out in previous investigations, following config settings are closely related to each other and it is tedious to figure out how they should be set in relation: 
`queue.mem.events`, `queue.mem.flush.min_events`, `queue.mem.flush.timeout`, `output.elasticsearch.worker`, `output.elasticsearch.max_bulk_size`.

I propose to use following formula as default settings:
- use `runtime.GOMAXPROCS(0)` as default value for `output.elasticsearch.worker`: The number of workers writing to ES can have a large impact on apm server performance. It should be aligned with the number of CPUs available in apm server, and the used ES cluster. We don't have access to the ES cluster, so respecting the number of CPUs seems like a good decision.  
- `output.elasticsearch.max_bulk_size = queue.mem.events / output.elasticsearch.worker / 1.5`
- `queue.mem.flush.min_events = output.elasticsearch.max_bulk_size`

In case the user overrides one or both of those settings we should respect the user set values. 

related:
[Blogpost how-to-tune-elastic-beats-performance](https://www.elastic.co/blog/how-to-tune-elastic-beats-performance-a-practical-example-with-batch-size-worker-count-and-more)
Investigations related to [vertical scaling](https://github.com/elastic/apm-server/issues/1414), also showing the influence of some settings.

**Comment by jalvz** [comment]
we are definitely dropping this, right?

**Comment by simitt** [comment]
For now yes.
