### ISSUE TITLE
Moving `span.hex_id` to `span.id`

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1677]
`span.hex_id` is a `keyword` while `span.id` is a `long`. 
Investigate if we can find a way to move `hex_id` to `id` without this being a breaking change.

**Comment by jalvz** [comment]
This can be done in the reindexing script

**Comment by jalvz** [comment]
related: https://github.com/elastic/apm-server/issues/1808

**Comment by graphaelli** [comment]
closing this out as it has been moved in code and #1807 is tracking the reindex task
