### ISSUE TITLE
Investigate changing default indices and retention policy

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1680]
Use one index per event type in favour of daily indices. 

Depends on ILM, see https://github.com/elastic/apm-server/issues/1290

At the moment we store events in daily indices, in a separate index per event type (transaction, span, error, metric). This allows users to delete span indices for one event type while keeping other events around for a longer time. E.g. the detailed information that spans provide might not be very important after a few weeks, while the more high level information that transactions provide should still be kept around. 

When using ILM one can define a [policy](https://www.elastic.co/guide/en/elasticsearch///reference/master/ilm-put-lifecycle.html) per index template. 
As soon as APM Server supports having an index template per index, ILM can be used to allow different retention policies per event type. 

We should investigate which ilm policies we want to define as default per event type.

**Comment by jalvz** [comment]
@roncohen @alvarolobato do you want this in (setting the new setting as default) for 7.0?

**Comment by simitt** [comment]
As we are not going to introduce ILM in 7.0, we cannot change the default policy. I suggest to close this issue (cc @roncohen ).
