### ISSUE TITLE
[discuss] switching to a more user friendly configuration

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1681]
Copied from https://github.com/elastic/apm-server/issues/1509#issuecomment-446721979:

> Switch to user-friendly configuration. For example, replace:
> ```
> output.elasticsearch.indices:
>     - index: "apm-%{[beat.version]}-error-%{+yyyy.MM.dd}"
>       when.contains:
>         processor.event: "error"
> ```
> with something like:
> 
> ```
> apm-server.elasticsearch.indices:
>   - error: "apm-%{[beat.version]}-error-%{+yyyy.MM.dd}"
> ```

**Comment by jalvz** [comment]
Outdated
