### ISSUE TITLE
update apm-server writes to corresponding to 6.6 aliases

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1683]
Fields aliased according to https://github.com/elastic/apm-server/blob/6.x/_meta/ecs-migration.yml should instead write to those directly, aliases in reverse are not to be added (no need for 6.x UI to load 7.x index data)

non-indexed fields are not represented there and should be migrated as well, where required.

**Comment by simitt** [comment]
Closing this as we are not using aliases.
