### ISSUE TITLE
apm-server won't start as a service (rpm/deb package) on 6.6 or 7.0

### ISSUE THREAD

**Issue by LeeDr** [elastic/apm-server#1698]
Same issue as fixed in beats https://github.com/elastic/beats/issues/9558

**Comment by LeeDr** [comment]
Double-checking, might be fixed...

**Comment by graphaelli** [comment]
good to close @LeeDr  ?

**Comment by LeeDr** [comment]
yep.  All good.  Sorry for not getting back to this before the holidays.
