### ISSUE TITLE
Clarify the Cloud setup instructions in the APM Server docs

### ISSUE THREAD

**Issue by kellyemurphy** [elastic/apm-server#1714]
Per the [Cloud issue #22949](https://github.com/elastic/cloud/issues/22949) , some clarity could be added to the APM Server documentation. 

Per @R0ky: 
> Currently there is a documentation page specifying how to setup output for Elastic Cloud for APM server in APM documentation:
https://www.elastic.co/guide/en/apm/server/current/configure-cloud-id.html. This is causing a bit of confusion as customers believe that we support APM within Cloud, but we don't yet. 

Basically, the docs should say that this is how to integrate a separate APM Server with an existing Cloud deployment, and that it is **not** an APM Server included with Cloud deployments.

**Comment by bmorelli25** [comment]
Thanks for following up on this @kellyemurphy! Will get this fixed.

**Comment by bmorelli25** [comment]
This documentation is copied from beats. I've added a conditional `NOTE` for APM in my currently open PR: https://github.com/elastic/beats/pull/9595/commits/7122f50d352abd1429fa1e334b9381ddc0cb7e24

**Comment by bmorelli25** [comment]
A fix has been merged in the Beats repo and will show up shortly on `elastic.co`
