### ISSUE TITLE
Bypass APM server and log APM data in logstash

### ISSUE THREAD

**Issue by pratik8787** [elastic/apm-server#1736]
Hello,

I want to run APM on my nodejs app.
Due to some IT policies at my workplace, I'm not given APM server url and service token and asked to log the apm data directly into logstash.
Is there anyway i can do that? 
Can I pass logstash url as serverUrl in APM agent configuration?

**Comment by graphaelli** [comment]
That's not currently a support configuration.  An alternative is to colocate your APM Server with your application (run them on the same host) and utilize apm-server logstash output - https://elastic.co/blog/how-to-send-data-through-logstash-or-kafka-from-apm-server can help with this.

In the future, please direct questions and feature requests to the [forums](https://discuss.elastic.co/c/apm) and reserve github for bug reports, thanks!
