### ISSUE TITLE
Cleanup docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/apm-server#176]
I'm compiling a list of global issues that need to be cleaned up in the docs:

- [x] Use asciidoc attributes to resolve paths. We should use the shared attributes here: https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc. See Example 1 for details.
- [x] Fix broken links to data files. Not sure what we are expecting to show here, but see Example 2 to learn how to embed the content of the file in the html page.
- [x] Add IDs for any headings that will be chunked into a separate topic. It's a good idea to just add IDs to level == and === headings. Otherwise, you end up with URLs that change whenever the text used in a heading changes. See Example 3.

**Example 1:**

Use asciidoc attributes to resolve book paths.

To import the attributes,  add the following lines to the index file (usually called index.asciidoc):

```
:branch: master

include::{asciidoc-dir}/../../shared/attributes.asciidoc[]
```
Set `branch` to the correct branch for your project.

Then you can use any attributes in the [shared attributes file](https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc) to resolve the book path.

For example `{ref}/getting-started.html `resolves as `https://www.elastic.co/guide/en/elasticsearch/reference/master/getting-started.html ` in the generated html files.

A word of caution: If you make a typo or use an attribute that doesn't exist, the build won't warn you. In fact, it will delete the entire line of text after the attribute. So it's a good idea to verify that your links resolve correctly in the generated html.

**Example 2:**

You can use an asciidoc include to pull the contents of the JSON file into the document and then use code tags to format the JSON:
```
=== Transaction document

[source,json]
----
include::./data/elasticsearch/transaction.json[]
----
```
Note that you'll also need to update the conf.yaml so the doc build knows to look in this directory for files.

**Example 3:**

Specify an ID (anchor) for linking and to set the name of the generated html file.
```
[[apm-security]]
=== Security
```
With the `[[ID]]` specified, you get https://www.elastic.co/guide/en/apm/server/current/apm-security.html

Without it specified, you get https://www.elastic.co/guide/en/apm/server/current/_security.html. If you change the title, the URL changes...and stuff breaks.

**Comment by watson** [comment]
I've added some APM related asciidoc attribute references that I thought would come in handy. Feedback welcome 😄  elastic/docs#236

**Comment by simitt** [comment]
I think after reworking the docs before the release we have cleaned up the issues pointed out by @dedemorton. 
@roncohen , @ruflin , @watson , @beniwohli if there are no objections I'd close this Issue.
