### ISSUE TITLE
Default index differs when using elasticsearch or logstash output

### ISSUE THREAD

**Issue by HonzaKral** [elastic/apm-server#1792]
When you point `apm-server` directly to elasticsearch it will create indices `apm-VERSION-DATE`, if output is switched to logstash with the default `beats` workflow the index will be `apm-server-VERSION-DATE` causing the default index not to be applied.

Ideally the default index when going through logstash would be the same as when going direct to es.

seems a leftover from https://github.com/elastic/apm-server/issues/143

**Comment by simitt** [comment]
depends on https://github.com/elastic/beats/pull/10841
