### ISSUE TITLE
Remove aliases in 6.6 after decision to go with a reindex strategy

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1794]
We've decided to go with a reindexing strategy for upgrading to 7.0 and that means we need to clean up the aliases that were added for 6.6 which are no longer needed.

**Comment by graphaelli** [comment]
mostly reverting https://github.com/elastic/apm-server/pull/1609

**Comment by roncohen** [comment]
fixed in https://github.com/elastic/apm-server/pull/1795
