### ISSUE TITLE
Reflect ECS changes in documentation

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1803]
* Udpate `context.asciidoc` etc.
* Add field changes to breaking changes (like [beats did](https://www.elastic.co/guide/en/beats/libbeat/master/breaking-changes-7.0.html))
* APM Overview breaking changes should include information on ECS changes and reindexing per https://github.com/elastic/kibana/pull/29845

**Comment by bmorelli25** [comment]
Closed in #1940.
