### ISSUE TITLE
Move remaining context fields

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1804]
Review all field names and agree on them for 7.0, with special attention to avoid possible ECS conflicts in the future

**Comment by jalvz** [comment]
Special attention to `context.db`, `context.custom` and `context.response.finished`

**Comment by jalvz** [comment]
Agreed to move everything out of context and rename `span.http` fields names for ECS alignment if it makes sense (just field rename for consistency, not move it to the top)


cc @roncohen

**Comment by simitt** [comment]
Also remember to move `context.page`, see https://github.com/elastic/apm-server/issues/411#issuecomment-420178858

**Comment by roncohen** [comment]
@jalvz thanks for the ping. Seems to make sense to me to get rid of the last stuff in `context`. Is there an overview somewhere of all the changes we're making?

**Comment by simitt** [comment]
[ECS migration](https://github.com/elastic/apm-server/blob/master/_meta/ecs-migration.yml) lists all the changes so far.
