### ISSUE TITLE
Merge all metadata information to span

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1806]
Is there a reason we only merge minimal information from the `metadata` to the `span`?

I know there is a difference in the `context` between `spans` and `transactions`, where I think this difference originates from, but as the metadata are given for all events within this request, I think we should merge all `metadata` to all events, and would even call this a bug.

**Comment by roncohen** [comment]
the general the argument for minimizing the amount of data in spans was that we were trying to minimize the space that spans take up. 

Are there specific metadata fields that you feel should be on spans in order to fulfil a specific use case?

**Comment by simitt** [comment]
I stumbled across this when moving the `user` to the new ECS field and realised we don't store it with spans. 
The argument about reducing storage is valid. I am good to close this issue again, if you think we should stick with the current solution.

**Comment by jalvz** [comment]
This has an impact in that UI might need some attributes not in span and have to get them from the transaction, maybe fetching it from the Kibana backend. 

We might be saving space but adding latency, in which case this might worth revisiting.

@elastic/apm-ui probably has a better idea than me about what can be convenient to have in span.

**Comment by simitt** [comment]
Just discussed this offline with @sqren, and it seems this is easily fixable in the UI so closing this issue again.
