### ISSUE TITLE
Index error.exception as an array of objects

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#1817]
In order to support chained exceptions, we'll move towards storing exceptions as an array of objects. Each object in the array will describe the items in an exception chain.

We don't need to change the mapping, just need to change the events we generate to be a slice. Initially, it'll just be a slice/array with one object; we'll extend this later when we update the intake API to add `error.exception.cause`.

**Comment by simitt** [comment]
Sorry for bringing this up that late, but I am not sure using an array is the best option here. 

Maybe an array datatype is just fine, depending on what the requirements for querying this information are. But arrays of objects behave different in ES than one might expect, e.g. you cannot query for objects independent of each other. Now I am not sure what our requirements for `error.exception` are, but maybe we should consider using `nested objects` instead. cc @sqren as he also mentioned some concerns. 

[nested objects in ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html)
[arrays datatype in ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html)

**Comment by axw** [comment]
@simitt this was an intentional decision, but I'm happy to discuss further. The idea was that searching for multiple attributes of a specific exception in the chain would be unlikely. Nested will also be more expensive, as each chain item will create a separate doc.

**Comment by sqren** [comment]
> Nested will also be more expensive, as each chain item will create a separate doc.

"Expensive" as-in: require more storage, but cheaper to query (if we only need specific exceptions), right?

**Comment by simitt** [comment]
Thanks for explaining @axw , I just wanted to ensure we are aware of the consequences.

**Comment by axw** [comment]
@sqren how would you search for a specific exception in a way that's less expensive? (Not rhetorical, I'm wondering if I'm missing something.)

When you do a nested query, it's going to search through each of the nested docs for matches. I haven't measured, but I wouldn't expect that to be less expensive than searching an array of objects.

Anyway, the assumption I baked into the schema was that we would treat the chain as a single entity which can only be searched as a whole, rather than a collection of entities that can be searched independently.

If there are future designs that would be prevented by this, we could consider changing it. We could also do that in 8.0 whenever that may be. If this approach doesn't work out for whatever reason, we could stick to indexing a single exception (not a chain) as a single-element array; the queries we're able to perform have not changed since there's no mapping change.

**Comment by sqren** [comment]
> @sqren how would you search for a specific exception in a way that's less expensive? (Not rhetorical, I'm wondering if I'm missing something.)
When you do a nested query, it's going to search through each of the nested docs for matches. I haven't measured, but I wouldn't expect that to be less expensive than searching an array of objects

Elasticsearch doesn't handle arrays of objects as one intuitively would expect. Object hierarchies are flattened into a list of field names and values, which makes it impossible (afaict) to query for specific objects in the array. 

For instance, currently the UI is only showing the first exception, and until we get around to showing all of them, it would be nice to only fetch the first exception from ES. With the array of objects, I'm not aware of a way to sort the list of exceptions (eg. by time) and then return the first one. This is possible with nested documents. Thus the array of objects ES will return the full exception chain (=more data), which I expect to be more "expensive" (let's pretend extreme cases with a veeery long exception chain).

**Querying by multiple fields**
With arrays of objects there is also no way to find documents by specifying multiple properties of a nested object. For instance finding errors that contains one or more exceptions where `library_frame=true` and `exclude_from_grouping=true` (just a weird example). Again, we can do this with nested documents.

This is probably not a show-stopper, and we might never need the query capabilities of nested fields. Just pointing out the limitations of arrays of objects so we are on the same page.

**Comment by sqren** [comment]
> how would you search for a specific exception in a way that's less expensive? (Not rhetorical, I'm wondering if I'm missing something.)
When you do a nested query, it's going to search through each of the nested docs for matches. I haven't measured, but I wouldn't expect that to be less expensive than searching an array of objects
@axw 

As mentioned above Elasticsearch doesn't handle arrays of objects as one intuitively would expect. Object hierarchies are flattened into a list of field names and values, which makes it impossible (afaict) to query for specific objects in the array. 

For instance, currently the UI is only showing the first exception, and until we get around to showing all of them, it would be nice to only fetch the first exception from ES. With the array of objects, I'm not aware of a way to sort the list of exceptions (eg. by time) and then return the first one. This is possible with nested documents. Thus the array of objects returned by ES will be the full exception chain (=more data), which I expect to be more "expensive" (let's pretend extreme cases with a veeery long exception chain).

This might not be needed (I'm not aware what we will need in the future tbh) but this is what I mean with "more expensive to query". Just pointing out the limitations of arrays of objects so we are on the same page.

**Comment by sqren** [comment]
> how would you search for a specific exception in a way that's less expensive? (Not rhetorical, I'm wondering if I'm missing something.)
When you do a nested query, it's going to search through each of the nested docs for matches.

Oh, to actually answer your question: I don't know how you would search for a specific exception with objects of arrays. With nested documents I would do it like:
```js
{
  "query": {
    "nested": {
      "path": "error.exception",
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "error.exception.code": "ECONNRESET"
              }
            },
            {
              "match": {
                "error.exception.handled": true 
              }
            }
          ]
        }
      }
    }
  }
}
```

(this obviously requires that the neccessary fields on `exception` are indexed)

**Comment by axw** [comment]
@sqren that query will return the whole document still. However, you can use `nested.inner_hits` to restrict to just the matched exception, e.g.:

```json
GET index/_search
{
  "_source": false,
  "query": {
    "nested": {
      "path": "nested",
      "query": {
        "match_all": {}
      },
      "inner_hits": {"size": 1}
    }
  }
}
```

> For instance, currently the UI is only showing the first exception, and until we get around to showing all of them, it would be nice to only fetch the first exception from ES. With the array of objects, I'm not aware of a way to sort the list of exceptions (eg. by time) and then return the first one. This is possible with nested documents. Thus the array of objects returned by ES will be the full exception chain (=more data), which I expect to be more "expensive" (let's pretend extreme cases with a veeery long exception chain).

You could use a scripted field to pull out the first element, and exclude the full exception from the search results. That may have other issues, I don't know.

> This might not be needed (I'm not aware what we will need in the future tbh) but this is what I mean with "more expensive to query". Just pointing out the limitations of arrays of objects so we are on the same page.

OK. Let's stick with this for now, we can review later. A couple of possible alternatives, which this change does not preclude:

(a) change to nested in a future major version, if/when we come up with use cases which outweigh the storage and indexing costs; and/or
(b) introduce a secondary field for the part of the exception chain following the first element, enabling detailed querying of the initial exception like today

**Comment by sqren** [comment]
> hat query will return the whole document still 

True. I actually meant it as two different examples: the first for fetching just a single exception in the chain (can be accomplished with `inner_hits` as you mentioned). 
The second as a way to find an `error` document by searching for multiple `exception` fields. 

> Let's stick with this for now, we can review later.
👍
