### ISSUE TITLE
Automatic update approved files in system tests

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#1827]
In a similar way as for package tests.
While at it, consider other improvements for system tests, like changing LOG level for elasticsearch or urllib, etc.

**Comment by axw** [comment]
I'm currently working on https://github.com/elastic/apm-server/issues/3025, adding new fields to intake.

I think it would help to have this, to avoid having to hand-edit the 'approved' files in much the same way that we do for integration tests.
