### ISSUE TITLE
Return "something" from the health check when there's no secret token

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1828]
If a user clicks into an APM Server using their browser, they'll see a blank screen if there's no secret token set. It's not obvious that APM Server is replying with a "200 OK". It would be a slightly better user experience if APM Server replied with a simple message, for example "APM Server OK" if the request has `Accept: text/html` or

```
{"status": "OK"}
```
or similar when `Accept: application/json`

**Comment by jalvz** [comment]
We decided to not prioritize this for now, we'll get back to it for 8.0.
 I'll close this to reduce the noise, but it is tracked in meta issue https://github.com/elastic/apm-server/issues/2632

Feel free to reopen if a new need arises. Thanks!
