### ISSUE TITLE
Investigate behaviour of `gomaxprocs` on cloud

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1841]
`gomaxprocs` is used for the [publisher](https://github.com/elastic/apm-server/blob/master/publish/pub.go) to define the size of the buffer to store transformables in and for the amount of readers reading from the queue. 

Let's run some quick tests how this behaves with limited CPU ticks, to see if we need to do some changes, e.g. use a multiple of gomaxprocs or change this behaviour in any other way.

**Comment by simitt** [comment]
When initializing the beat, if the root level config option `MaxProcs` is set, it is used to [initialize GomaxProcs](https://github.com/elastic/beats/blob/master/libbeat/cmd/instance/beat.go#L583), so basically the number of CPUs that can be executing simultaneously. 

In the APM code, we call `GOMAXPROCS(0)` afterwards to set the size of the channel for the pending requests, and also for the amount of workers reading from this channel. The call to `GOMAXPROCS(0)` returns the number of CPUs set by default, or the value set by using the config option, as just described. 

On cloud the `MaxProcs` setting cannot be overwritten by users.

With this setup there is an option to change the number of workers and the queue size if necessary. However, this would also change the number of max procs used by golang. 

I suggest to keep the setup as is for now, and defer a thorough testing of the behaviour to when we have an automated test setup allowing us to run more comparable stresstests on a regular basis. 

@graphaelli @roncohen wdyt?

**Comment by roncohen** [comment]
Generally, I think setting queue sizes to 1 (when `GOMAXPROCS(0)=1`) in a dynamic environment like this is never a good idea. The scheduler might decide to spend a lot of time in the producer. Especially considering there can be many producers (one per http client), but in this case only one consumer (`GOMAXPROCS(0)=1`). You can imagine the scheduler spending way more time in producers than in consumers. When the consumer goroutine gets scheduled to run it can max. consume one item from the queue and then it's back to the producers. This is a simplified story of course. 

The fact that producers will [wait up to 1 second](https://github.com/elastic/apm-server/blob/master/publish/pub.go#L135) here probably saves us quite a lot of trouble.

I think the only downside to increasing the queue size is memory usage. Setting it to always be minimum 3 or 5 would probably not affect memory usage significantly? So perhaps setting it at max(4, GOMAXPROCS(0)) could be a way forward?

All that being said, I'm OK to keep it as is and make a note to test more when we have a better setup.

**Comment by simitt** [comment]
A thought behind this suggestion comes from previous testing in the cloud setup. We saw highest throughput when the channel size for `pendingReq` was rather small. This was surprising at first. 
The probability that a `pendingReq` will be copied into the buffered channel before being processed increases, the larger the channel gets though. Having the channel size set to some similar value as the workers reading from the channel increases the chance that the `pendingReq` does not need to get copied to the buffer before, but directly gets sent to the receiver. This should have positive effects on memory but especially also on garbage collection. 

As mentioned before, we need some more thorough testing for this though.

**Comment by graphaelli** [comment]
Thanks for the investigation and summary @simitt, I agree we should invest more in our benchmarking setup first and investigate this after.  

> I think the only downside to increasing the queue size is memory usage. Setting it to always be minimum 3 or 5 would probably not affect memory usage significantly? So perhaps setting it at max(4, GOMAXPROCS(0)) could be a way forward?

For users running many apm-servers on huge boxes but with memory constraints for each (eg ECE/ESS), a situation where gomaxprocs is huge while memory is small seems very likely.  It appears that the full set of CPUs is made available to apm-servers on ECE, so a minimal deployment may find a small 512 MB mem apm-server paired with 128 cores, and therefore a possibly oversized queue.  I tested this with `fmt.Println(runtime.GOMAXPROCS(0))` under docker on a 16-core box using the same-ish parameters apm-server was launched by ECE with.  In fact, I was only able to affect that value by setting `-cpuset-cpus`, which defaults to "" in ECE. The `--cpus` flag didn't change anything, and is set to 0 by default in ECE afaict.

**Comment by roncohen** [comment]
thanks for the elaboration @simitt @graphaelli

> The point is, perhaps this needs both a min and max bound to make sense.

sounds right to me 👍

**Comment by simitt** [comment]
So do I understand you correct that both of you are fine with leaving as is and running more checks once we have a better automation set up?

**Comment by graphaelli** [comment]
+1 from me

**Comment by roncohen** [comment]
+1

**Comment by embano1** [comment]
Not strictly related to the outcome here, but might still be useful: a while ago I did some cpu-bound benchmarking for GOMAXPROCS in CPU limited scenarios (i.e. throttling) -> https://github.com/uber-go/automaxprocs/issues/12

**Comment by graphaelli** [comment]
Thanks @embano1!

**Comment by jalvz** [comment]
We have a somewhat better benchmark setup now, is this still relevant?
If not we rather close and reopen if needed.

**Comment by graphaelli** [comment]
Agreed, closing now.
