### ISSUE TITLE
Ensure libbeat does not set `host.name`

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1846]
Look into how setting `host.name` can be prevented. Easiest fix seems to overwrite it by the 
APM Server. 

Note: Remove excluding the `host` from the system approval tests afterwards.

**Comment by simitt** [comment]
Currently libbeat sets a `host.name`, which is not accurate for APM, as the `host` should reflect the host where the monitored service is running and not the APM Server. 
This is a similar issue to what we had with `agent` metadata information, that has been solved by using a processor. According to https://github.com/elastic/beats/pull/9952#discussion_r246077029 we should not necessarily use processors for this. @urso is there any other way we can solve this already or are you fine with introducing another processor for this?

**Comment by urso** [comment]
The `host.name` field is set in 2 locations in Beats:
- by the publisher pipeline
- via `add_host_metadata` processor

The processor is enabled by default for all beats.

I assume you don't want to have any of these default processors enabled? I think it would make sense to remove the field from the publisher pipelines builtin fields.

**Comment by simitt** [comment]
depending on https://github.com/elastic/beats/issues/10698

**Comment by simitt** [comment]
As pointed out in an offline discussion by @urso, the implemented solution had some side effect on beats `xpack monitoring`. Thus the PR in libbeat got [reverted](https://github.com/elastic/beats/pull/10769) and @urso will refactor the current handling and provide a fix from libbeat.

**Comment by simitt** [comment]
Unblocked as https://github.com/elastic/beats/pull/10801 got merged and backported to 7.0

**Comment by graphaelli** [comment]
fixed on 7.0 by #1981, #1982 is set to fix this on master
