### ISSUE TITLE
transaction.name and error.culprit type updates

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#1856]
from @webmat:

`error.culprit` is `text`, should it be?  If so, switch to `keyword` and add a multifield at `error.culprit.text`

`transaction.name` is `text`.  Switch to `keyword` and add a multifield at `transaction.name.text`

No obligation to do this but it would align with the ECS approach generally.

**Comment by webmat** [comment]
Thanks @graphaelli 

Note that `error.culprit` doesn't need to have the `.text` multi-field, if you don't need it.

The convention I'm proposing is for all fields (except message fields) to be `keyword` first.

Then *only if needed*, the `.text` is added as a multi-field. So if you don't need `text` for `error.culprit`, feel free to skip it.

cc @ruflin

**Comment by graphaelli** [comment]
confirmed that UI does not aggregate or search on `error.culprit` - it has apparently been `text` from the beginning but it's unclear why.  @elastic/apm-server thoughts on converting it to a keyword at least?

**Comment by graphaelli** [comment]
UI changes are of course required for `transaction.name`, which currently uses `transaction.name.keyword` (search for: `${TRANSACTION_NAME}.keyword`)
