### ISSUE TITLE
Nodejs agent sending undefined values in `context`

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1873]
So far I found that the nodejs agent sends following fields within `context` that have been stored for 6.x documents, but will be removed in 7.0 as of https://github.com/elastic/apm-server/issues/411:
* `context.request.headers.accept`,
* `context.request.headers.host`

According to previous discussions no additional information should have been sent up by the nodejs agent (outside of `context.custom`). @watson and @Qard right now those fields will not be stored any more in 7.0, and they would also be removed from 6.x docs once they are reindexed. If they should be stored, we need to define them on API level.

**Comment by roncohen** [comment]
Users will probably expect all headers to show up. I suggest we move to change the JSON and APM Server handling of `context.request.headers` to accept and store arbitrary headers. We should probably still have a max length on the values.

**Comment by Qard** [comment]
Yeah, the current behaviour is to send everything. :+1: to not restricting the headers object.

**Comment by simitt** [comment]
@roncohen the headers are not going to be indexed. Usually we limit the values when they are indexed as keywords. What would be the motivation for limiting the length? When adding checks we would also need to define how to handle other value types (int, objects, ..). 
Since we haven't had any restrictions on headers, this would be a breaking change and could only be introduced with a new API version. 
The handling that would be closest to what is currently released would be to simply store whatever is sent without any restrictions. I suggest we move forward with this now and consider limitations when working on a new API version.
