### ISSUE TITLE
Question | issue, spring cloud gateway not being instrumented

### ISSUE THREAD

**Issue by michaelcouck** [elastic/apm-server#1880]
Hello,

We are integrating Elastic APM into our landscape, eureka gets instrumented, the custom services, even the config server gets instrumented, but not the spring cloud gateway. Anyone done this, please post your startup script.

This is my startup script: java -javaagent:/opt/elastic-apm-agent-1.1.0.jar -Delastic.apm.server_urls=http://sl01757v.ops.vdab.be:8200 -Delastic.apm.service_name=gateway -Delastic.apm.application_packages=org.springframework -Dspring.profiles.active=sand-box -jar gateway-server-1.0.0.jar

Already tried other packages to instrument, like be.vdab & both spring and vdab. As the single highest volume component we despreately need to monitor these.

Cheers,
Michael

**Comment by jalvz** [comment]
Hi, @michaelcouck sorry to hear about this. I think is better that you post that question in the forum https://discuss.elastic.co/c/apm, which is closely monitored by the Java agent developers.

**Comment by michaelcouck** [comment]
Hi Juan,

Thanks for that :) 

No problem, we'll sort it our eventually...

Cheers,
Michael

**Comment by jalvz** [comment]
No worries, I'm sure you'll find help over there. I'll close this in the meanwhile, but feel free to reopen if something else comes up!
