### ISSUE TITLE
APM storage retention settings for low-cost use cases

### ISSUE THREAD

**Issue by ciarancourtney** [elastic/apm-server#1883]
What I really want is to just store short-term spans/errors in fine detail for, lets say, the last month, and I want to retain the high-level metrics like RPM, errors per month, cpu/mem usage forever (surely years of these 1min interval metrics is no more than a few MBs?)

Can you bundle presets for users not willing to get bogged-down with elasticsearch tuning and nomenclature?

Sorry for opening a general annoyance as an issue, I saw https://github.com/elastic/apm-server/issues/1855 but don't know what it refers to

**Comment by jalvz** [comment]
Hi Ciaran,

> Can you bundle presets

This is currently being working on, but we are not there yet so I will have to draw upon Elasticsearch nomenclature for the time being. 
What you are looking for is called Index Life Management (ILM) and it allows you to specify retention policies for your indices. By default, APM event types are stored in different indices each, so you can have different retentions per type (`transaction`, `span`, etc).

ILM policies support a number of settings eg. for defining roll-over thresholds, and then you assign those policies to index templates. For now, you have to set this up yourself.

You can see what templates you have for APM with a query like `GET _template` to Elasticsearch (look for `apm-{version}` in there)

This comment gives a full example for setting an ILM policy in the index template for spans.
https://github.com/elastic/apm-server/issues/1545#issuecomment-446817453

I hope that helps, let me know if you have any more questions!

**Comment by ciarancourtney** [comment]
OK thanks, I followed @graphaelli's steps and will see how it goes. Look forward to later versions of APM, keep up the good work

**Comment by jalvz** [comment]
Thanks. I'll close the issue for now, feel free to reopen if something comes up!
