### ISSUE TITLE
[docs] Document 7.0 reindexing

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#1900]
Related to: https://github.com/elastic/kibana/pull/29845
See also: https://github.com/elastic/kibana/pull/29510

Where?
Breaking change in the [release notes](https://www.elastic.co/guide/en/apm/get-started/master/apm-release-notes.html) with links to more information.

**Comment by alvarolobato** [comment]
Related issue about migration instructions from Kibana APM UI. https://github.com/elastic/kibana/issues/30274

**Comment by bmorelli25** [comment]
Closed in #1940
