### ISSUE TITLE
[APM-CI][Server] Benchmarks to run at part of CI

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1910]
As APM Server becomes increasingly complex, we need to keep track of performance. It would be great if we ran benchmarks as part of CI and could output a general score to make sure performance doesn't regress.

There's already a number of benchmark tests that we can start with, but over time we'd want to elaborate on these. Especially considering the significant amount of work that goes on in libbeat, we'll need to understand how the performance improvements we can make in APM Server relates to the overhead introduced in libbeat.

As an example, we up until recently cached some of the metadata "fields". This was removed as part of the ECS move: https://github.com/elastic/apm-server/pull/1766/files#diff-2e4f6015e9b6ea4b862b2b19bdcc25b3L84. 

The code is cleaner now, but when we introduced the cached fields it was as a performance improvement. At the moment it's unclear whether removing them made things much worse. Without continuously measuring performance, it's very easy to miss something like this.

**Comment by kuisathaverat** [comment]
Do Hey APM not do that? it makes some performance test and stores then on ES, also compares results and return a fail in case of a performance decrease.

**Comment by jalvz** [comment]
This is done (both micro and external benchmarks)

**Comment by simitt** [comment]
@jalvz I am aware of the setup for the external benchmarks, but where are micro benchmarks run for the server in an automated manner?

**Comment by jalvz** [comment]
here for instance: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/master/122/pipeline/89
