### ISSUE TITLE
I have enabled javaApm agent for my application in docker but cant find my app in apm services

### ISSUE THREAD

**Issue by sylesh687** [elastic/apm-server#1931]
I have checked network connectivity and healthcheck that looks fine side by side i also enabled java apm agent to a java app running in ec2 instance ( i this case that service is visible in kibana apm service)

Please help

**Comment by simitt** [comment]
Hi @sylesh687, thanks for reporting. This doesn't necessarily sound like an issue with the Server, but might be related to the agent collecting data. Could you please create an entry in the [apm discuss](https://discuss.elastic.co/c/apm) forum, listing the exact versions you use. This makes it easier to identify who can help you.

**Comment by simitt** [comment]
referencing the [discuss entry](https://discuss.elastic.co/t/enabled-javaapm-agent-to-my-app-in-docker-but-i-cant-see-it-in-kibana-under-apm-services/168560)
