### ISSUE TITLE
Race Condition by having same metrics interval reporting and read_timeout default values

### ISSUE THREAD

**Issue by reveil** [elastic/apm-server#1936]
Having a default HTTP read_timeout the same value as default metrics interval leads to a race condition on the HTTP connection.

The problem scenario:

1. An TCP connection is established due to a previous HTTP request from an agent
2. Exactly 30s passes with no requests on this TCP stream
3. A client tries HTTP POST to /intake/v2/events to report metrics
4. At the same time but a few nano seconds later the server decides to timeout the connection and send a TCP FIN packet
5. The client never gets an HTTP response and can't re-transmit it due to how the HTTP protocol works: https://tools.ietf.org/html/rfc2616#section-8.1.4
6. An exception happens on the client as it can't double POST not knowing whenever the server got it or not

You can see a wireshark packet capture of this scenario here:
https://github.com/elastic/apm-agent-python/issues/409#issuecomment-463012525

If in point 4 happens a few nanoseconds sooner than 3 a new TCP connection get established with a SYN packet.

If I changed the read_timeout to 45 seconds the metrics requests always happen over the same TCP connection with no disconnects and FIN packets from the apm server side.

There is an investigation from the amp python agent side:
https://github.com/elastic/apm-agent-python/issues/409

**Comment by simitt** [comment]
Closed by #2122
