### ISSUE TITLE
Enable ingest pipelines by default

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1972]
From the [ingest user-agent docs](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-user-agent.html):
>The user_agent processor is no longer distributed as a plugin, but is now a module distributed by default with Elasticsearch. See the User Agent processor for more details.

This will be true for ES versions >= 6.7, and would allow us to enable the user [agent processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/user-agent-processor.html) by default from 7.0 on. We could also add a check if the used ES versions is >= 6.7 and only turn on in case this is true.

**Comment by simitt** [comment]
pinging @makwarth here as this might be interesting for you.

**Comment by makwarth** [comment]
@simitt ah, I just mentioned this in the geo-ip issue 👍

**Comment by simitt** [comment]
linking to the geo-ip issue for clarity #1283

**Comment by jalvz** [comment]
this doesn't seem to be a big undertaking, any reason for not aiming 7.1?

**Comment by jalvz** [comment]
Re-labelling this as per https://github.com/elastic/apm-server/issues/1283#issuecomment-476632253

**Comment by graphaelli** [comment]
Update title to reflect addition of geoip processor alongside the user agent processor as recommended defaults.
