### ISSUE TITLE
Documenting non indexed fields by adding to fields.yml

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#1980]
Follow up on https://github.com/elastic/apm-server/pull/1961. 

In 6.6 fields that are not indexed in ES have been added to the `fields.yml` to document also non-indexed fields. [Documentation](https://www.elastic.co/guide/en/apm/server/6.6/exported-fields-apm.html#_context_fields) shows a _Field is not indexed_ if `index: false` is set in the base yml. For objects and groups this field is missing, as only `enabled: false` is set. 

Ensure to forward port documenting the fields to 6.7 and 7.x

**Comment by graphaelli** [comment]
In latest docs, [for example](https://www.elastic.co/guide/en/apm/server/master/exported-fields-apm.html#_url_fields), objects with `enabled:false` generate this doc:

```
http.response.headers
type: object

The canonicalized headers of the monitored HTTP response.

Object is not enabled.
```

https://github.com/elastic/beats/pull/11214 in to backport this change, then it can be sync'd over.
