### ISSUE TITLE
[docs] 7.0 testing - compatibility 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-server#2003]
I'm doing testing for 7.0 and I go through the installation instructions. On the [Install and run page](https://github.com/elastic/apm-server/blob/master/docs/guide/install-and-run.asciidoc) we have:

> Important | You must ensure you’re using the same version of Elasticsearch, Kibana, and APM Server.

But according to the [support matrix](https://www.elastic.co/support/matrix#matrix_compatibility) 6.x servers should work with any 6.x Kibana/Elasticsearch version. (we even discussed this in a recent meeting).

I'm not sure what the plan is for 7.x, but I think the two statements for 6.x are contrary.

@bmorelli25 Could you please take a look?

**Comment by bmorelli25** [comment]
Good catch @gregkalapos. I'll update the copy to recommend the same version, and point to the support matrix for further information.

**Comment by bmorelli25** [comment]
Fixed in https://github.com/elastic/apm-server/pull/2009
