### ISSUE TITLE
Clarify "beat" messaging in apm-server

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2026]
As discussed in https://github.com/elastic/apm-server/issues/2001, it's confusing that apm-server emits errors referring to the `beat` user [here](https://github.com/elastic/apm-server/blob/1a4f76ba725b257d63f51418e29928847ac8840b/vendor/github.com/elastic/beats/libbeat/keystore/file_keystore.go#L392-L393) and [here](https://github.com/elastic/apm-server/blob/1a4f76ba725b257d63f51418e29928847ac8840b/vendor/github.com/elastic/beats/libbeat/common/config.go#L434-L437).   There are also many references to `beat` in the default `apm-server.yml`.

**Comment by jalvz** [comment]
fixed in #1982
