### ISSUE TITLE
Provide the version for removing the previous source map endpoint in the docs

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#2031]
Currently [here](https://www.elastic.co/guide/en/apm/server/6.6/sourcemap-api.html) there's a note about deprecating the old source map url but it doesn't mention in which version:

> The URL for uploading sourcemaps was previously /v1/sourcemaps. It still works, but is being deprecated in favor of /assets/v1/sourcemaps.

Also in the above note previous endpoint is wrong it should be ` /v1/rum/sourcemaps`

**Comment by bmorelli25** [comment]
Closed in #2063
