### ISSUE TITLE
Add labels to metadata

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#2037]
As a result of https://github.com/elastic/apm/issues/48 we need to add the option to provide labels on in the metadata. 

Labels in metadata should be added automatically to all transactions, metrics and errors but not on spans.

**Comment by jalvz** [comment]
so they should be merged with existing transaction/error labels, and if there is a name clash, the one in the event wins?

**Comment by roncohen** [comment]
that sounds good to me @jalvz  👍

**Comment by felixbarny** [comment]
Correct. Metrics are relevant as well.
