### ISSUE TITLE
Warn when starting APM Server with a secret token but no SSL set

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#204]
We should log a warning if the APM Server has a secret token set without SSL being enabled. 

Sending the secret token over clear text HTTP is pointless and dangerous. 

Alternatively the APM Server could refuse to start entirely in this scenario, but users might still want to terminate SSL at a upstream (for example, at the load balancer), so I vote for logging a warning instead of refusing to start.

**Comment by Benoss** [comment]
I would terminate SSL on Nginx but it makes sense to log a warning

**Comment by ruflin** [comment]
+1 on warning. Also our k8s setup terminates SSL at the load balancer. So internally the token is passed on without SSL.
