### ISSUE TITLE
Field data types should be unified to allow opentracing log collection

### ISSUE THREAD

**Issue by vbohata** [elastic/apm-server#2060]
I am currently trying to map azure application insights metrics to APM fields. In this https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation page I found it can be easily "mapped" to OpenTracing format. But in APM exported fields I found fields like span.id (long) which seems to be deprecated by hex_id which I assumes should be in HEX. But span.id in this case is arbitrary string. As APM uses "root" fields like span.id and not apm.span.id I think it should be as much unified as possible. So not fixed to this long datatypes nor hex values.

**Comment by roncohen** [comment]
Hi @vbohata. Thanks for reaching out and for your interest in Elastic APM. `span.id` is being changed to a string in 7.0. Hope that helps!

I'll close this for now but feel free to reopen if applicable.
