### ISSUE TITLE
Add latest output error to 503s

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2075]
Some [common problems](https://www.elastic.co/guide/en/apm/server/6.6/common-problems.html#queue-full) with apm-server are simpler to troubleshoot by reviewing the apm-server logs.  In practice, users may not access to those logs as easily as they would to application server logs.  

apm-server could include more information on why the common problem occurred, eg `"no such index and [action.auto_create_index] ([.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*]) doesn't match`.

It should be possible to disable the detailed error message for users that want that, with default set to enabled.

**Comment by simitt** [comment]
Closing, as the output handling has been completely reworked.
