### ISSUE TITLE
Mention the config option to enable the RUM endpoints in the error message

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#2085]
Currently, if RUM specific endpoints are accessed while `apm-server.rum.enabled` is not set to true in the configuration the following error message is returned:
```
{
  "error": "forbidden request: endpoint is disabled"
}
```

It would help users if we mention the config option to enable these endpoints in the error message.

**Comment by racevedoo** [comment]
Can I take this? I'd like to start contributing :D

**Comment by simitt** [comment]
Hi @racevedoo you're welcome to contribute. Let us know if you run into any issues.

**Comment by graphaelli** [comment]
duplicated by #2866, closed by #2869
