### ISSUE TITLE
[docs] Make it more clear that you need to enable RUM support

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#2087]
In addition to #2085, I think it makes sense to also update the documentation.

The problem (I think) is that the RUM [sourcemap documentation](https://www.elastic.co/guide/en/apm/agent/js-base/current/sourcemap.html) links directly to the APM Server _second level_ [sourcemap documentation](https://www.elastic.co/guide/en/apm/server/current/sourcemaps.html). We only mention that RUM needs to be enabled on the [section overview page](https://www.elastic.co/guide/en/apm/server/current/rum.html). We've learned in other issues that sometimes these pages are skipped over by readers.

I'll add a note the _second level_ sourcemap documentation page to remedy this.

It probably also makes sense for the [APM Server RUM](https://www.elastic.co/guide/en/apm/server/current/rum.html) page and the [RUM Introduction](https://www.elastic.co/guide/en/apm/agent/js-base/current/intro.html) page
to link to the top of the [configuration page](https://www.elastic.co/guide/en/apm/server/current/configuration-rum.html), instead of their current link locations.

@jahtalab / @vigneshshanmugam - sound good?

**Comment by vigneshshanmugam** [comment]
Yeah, good idea 👍. Thanks @bmorelli25
