### ISSUE TITLE
[Docs] Create article on how to add labels, user and custom metadata to transactions

### ISSUE THREAD

**Issue by formgeist** [elastic/apm-server#2111]
# Summary

In the APM UI, we're making some layout changes to the metadata (contextual information) that sits on the transaction. It's displayed as a tab next to Timeline, and will from https://github.com/elastic/kibana/pull/35150 be consolidated into a single tab, "Metadata". For the section of information that could be user customized (labels, user and custom) we had help messages that linked to the appropriate agent API information on how to set context for each part. I'd like to consolidate this information in an article that we can link to and manage separately, so there's just a single link to a help article to get people started. Perhaps with more information beyond just linking to the agent documentation itself.

![01 DT - Transaction detail - Context (show all).png](https://zube.io/files/elastic/cd8f3cbb1b9dd39722062ad7f61f1f27-01-dt-transaction-detail-context-show-all.png)

@bmorelli25 let me know what you think about this

**Comment by bmorelli25** [comment]
So, as an example for myself, currently with a transaction sample from the node agent I'm seeing links to the api reference:

* **User** - You can configure your agent to add contextual information about your users.
  [Learn more in the documentation.](https://www.elastic.co/guide/en/apm/agent/nodejs/2.x/agent-api.html#apm-set-user-context) _(set-user-context)_
* **Labels** - You can configure your agent to add filterable tags on transactions.
  [Learn more in the documentation.](https://www.elastic.co/guide/en/apm/agent/nodejs/2.x/agent-api.html#apm-set-tag) _(set-tag)_
* **Custom** - You can configure your agent to add custom contextual information on transactions. 
  [Learn more in the documentation.](https://www.elastic.co/guide/en/apm/agent/nodejs/2.x/agent-api.html#apm-set-custom-context) _(set-custom-context)_

New consolidated link will be: "**How to add labels and other data**"

Cool!

Quick question: Can you clarify what _article_ means to you? Would this article live in a blog post, documentation book, somewhere else?

My main concern with linking to something new (versus the documentation) is it's another thing that needs to be maintained. With that being said, we currently have to maintain the Kib -> agent links individually (keep the version current) so perhaps this change isn't a big deal.

I think it makes sense to have a landing page somewhere in the docs (apm overview maybe) that explains centrally what labels, user, and custom are. We can then link out to each agent from there. Similar to what we did with the dropped spans links from Kibana.

**Comment by formgeist** [comment]
> I think it makes sense to have a landing page somewhere in the docs (apm overview maybe) that explains centrally what labels, user, and custom are. We can then link out to each agent from there. Similar to what we did with the dropped spans links from Kibana.

This is exactly what I had in mind. A documentation page in APM overview that just adds more consistent information than what's in each agent api docs. Btw. looks like we're likely deprecating custom soon (https://github.com/elastic/apm/issues/7#issuecomment-445844339), so something to keep an eye on.

**Comment by jasonrhodes** [comment]
> I think it makes sense to have a landing page somewhere in the docs (apm overview maybe) that explains centrally what labels, user, and custom are. We can then link out to each agent from there. Similar to what we did with the dropped spans links from Kibana.

:clap: three cheers for this, I love this approach. Takes the complexity of linking to tons of different targets out of the application code and moves it to docs where it can be easily edited outside of the software release cycle.

**Comment by bmorelli25** [comment]
Awesome, let's do it!

**Comment by formgeist** [comment]
@bmorelli25 When you know the URL, please let @jasonrhodes know in https://github.com/elastic/kibana/pull/35150 👍 thanks!

**Comment by bmorelli25** [comment]
URL will be:
```js
{config.docs.base_url}guide/en/apm/get-started/{config.docs.version}/apm-data-model.html
```

Added a temporary landing page in https://github.com/elastic/apm-server/pull/2125.

Note to future Brandon -> **Don't forget to remove the temporary landing page when this issue is closed!**
