### ISSUE TITLE
[docs] Update APM Architecture diagram to include cloud

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#2117]
I know we just updated the [APM architecture diagram](https://github.com/elastic/apm-server/blob/master/docs/guide/apm-architecture.png) in January, but I'm wondering if it's time to update it again to include cloud?

![apm](https://user-images.githubusercontent.com/5618806/56244173-199f5280-6051-11e9-83ca-e658a3ab78e0.png)

---

Here's an absolutely awful artist's rendition of what this could look like. Although, you don't have to run the entire stack on/off cloud, so this might not be the best way to do it 🤷‍♂️

<img width="1160" alt="Screen Shot 2019-04-16 at 2 03 34 PM" src="https://user-images.githubusercontent.com/5618806/56244195-2ae85f00-6051-11e9-90f3-7f96a77a78cd.png">

@formgeist - do you have the bandwidth to assist with this at some point?

**Comment by formgeist** [comment]
@bmorelli25 I agree we should include Cloud somewhere in that diagram, but not sure if duplicating the same components like it's shown in your mock is the right way to go. Either I'm thinking keeping the existing diagram, but perhaps change the "Elastic Stack" title that surrounds the server, ES and Kibana components to something like "Elastic Stack - On-Prem or Elastic Cloud". Not sure if we use On-Prem in our usual marketing, but something along those lines. Otherwise we probably have to use a different section coming after the diagram to explain that this is available on Cloud, maybe even with it's own simplified diagram showing which parts can be hosted on Cloud and those that can't (i.e. agents) - just to really hammer it home. Thoughts?

**Comment by bmorelli25** [comment]
Good points!

>Either I'm thinking keeping the existing diagram, but perhaps change the "Elastic Stack" title that surrounds the server, ES and Kibana components to something like "Elastic Stack - On-Prem or Elastic Cloud".

The more I think about this, I actually really like the idea of keeping the existing diagram as is. At that point in the documentation users don't need to know there are multiple options for installing the Elastic Stack. 

> Otherwise we probably have to use a different section coming after the diagram to explain that this is available on Cloud, maybe even with it's own simplified diagram showing which parts can be hosted on Cloud and those that can't (i.e. agents) - just to really hammer it home. 

I like this. In the installation section, we can have a new diagram that visually explains which components are available on cloud. It can be very similar to the current diagram, and like you said above, it might just need a new box around it with some text that says Cloud vs Install yourself.

> Not sure if we use On-Prem in our usual marketing, but something along those lines.

On-prem is actually the terminology we use to refer to ECE (Elastic Cloud Enterprise), so we need to be careful about using that term. Here's how other products refer to each option:

Cloud
* `Hosted Elasticsearch Service`
* `Elastic Cloud`
* `Hosted Elasticsearch Service on Elastic Cloud`

Not cloud
* `Install yourself`

So, it could be something like: "Elastic Cloud or Install yourself"

---

Sources: [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/install-elasticsearch.html), [Kib docs](https://www.elastic.co/guide/en/kibana/current/install.html), [Beats docs (kinda)](https://www.elastic.co/guide/en/beats/libbeat/current/getting-started.html), [cloud](https://www.elastic.co/cloud/)

**Comment by formgeist** [comment]
So, you're thinking something along these lines?

**Install yourself**

![apm-install-yourself-diagram](https://user-images.githubusercontent.com/4104278/56665497-75e62000-66aa-11e9-9232-70342de96baf.png)

**Elastic Cloud**

![apm-elastic-cloud-diagram](https://user-images.githubusercontent.com/4104278/56665506-7b436a80-66aa-11e9-81e1-8b20537d729c.png)

**Comment by bmorelli25** [comment]
🔥 🔥 🔥 I love it. I think this would be perfect on our installation page. Thanks so much for your help!

**Comment by formgeist** [comment]
No worries 👍

**Comment by alvarolobato** [comment]
Cloud should be at the top.
