### ISSUE TITLE
Improve requirements, developer and contribution section in README.

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2118]
Following up on https://github.com/elastic/apm-server/pull/1513 the _Requirements_ and the _Developer/Contribution_ sections of the README need some rework to make it more clear which setup steps are necessary for which changes.

**Comment by bmorelli25** [comment]
It looks like there were many changes made to the readme in https://github.com/elastic/apm-server/pull/3418. Has this been resolved @simitt , or do you still see room for improvement?

**Comment by simitt** [comment]
Agree that this can be closed.
