### ISSUE TITLE
Document ILM support in APM Server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2136]
Document newly added ILM support in APM Server, implemented with https://github.com/elastic/apm-server/pull/2099.

**Comment by bmorelli25** [comment]
Coordinate with #2099 before merging

**Comment by simitt** [comment]
Please also document the additional privileges the [APM Server `write_user`](https://www.elastic.co/guide/en/apm/server/7.0/beats-basic-auth.html) needs when making use of ILM. 
See the privileges [defined in the integration tests](https://github.com/elastic/apm-integration-testing/pull/451/files). 
Get inspired by the [beats docs](https://www.elastic.co/guide/en/beats/filebeat/current/beats-basic-auth.html)

**Comment by bmorelli25** [comment]
Related to https://github.com/elastic/apm-server/pull/2228
