### ISSUE TITLE
Deal with failing ci test for saved objects in Kibana

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2137]
A ci check called _Check Kibana Object updated_ is run on every PR and on push to master. This test runs a command in APM Server to create the Kibana index pattern based on the ES template, and then checks if the created index pattern is in sync with the one bundled in Kibana for APM. 
It test fails on following occasions:
- updating libbeat changes inherited fields for the apm-server leading to changes in the Kibana index pattern
- changing fields directly in apm server leading to changes in the Kibana index pattern
- changes in Kibana touching the stored objects (e.g. moving the files around).

Since field changes requires a PR in APM Server and Kibana to be merged at the same time, a lot of PRs fail related to this test, although not directly related. 

We should discuss how to improve this situation on a CI level. A few options:
(1) In case only this stage fails we could mark the build as instable. 
(2) Run the test as a separate check outside of the `pr-merge`. 
(3) Trigger the test only if something in `_meta/fields.common.yml` or in `_beats/libbeat/_meta` changed and on pushes to release branches and master.

I suggest to apply option (3), and maybe also option (2) to give a better overview on the PR what is failing.

**Comment by kuisathaverat** [comment]
Implementing option 3 does not resolve the issue, it will hide it because the `kibana sync` does not pass in the master branch, it is broken for a few days after upgrade libbeat.
Implementing option 2 would extract the problem to other build but we still have the issue.
Finally implementing option 1 we'd assume that the build will be on an unstable state for a few days
My suggestion is to make the option 1, and think about how to make that a libbeats update does not break the kibana sync.

**Comment by mdelapenya** [comment]
How is `kibana sync` consuming `libbeat`? If it does not require `latest` version of the code, I'd go with using a fixed version of `libbeat`, like `libbeat-1.2.3`, so new changes in libbeat are not ported to Kibana.

On the other hand, if that's not possible, then kibana could add checks for `libbeat` compatibility.

**Comment by simitt** [comment]
APM Server is built on top of libbeat. It vendors in libbeat and inherits functionality, e.g. also the logic on how to create the Kibana index pattern. The index pattern is therefore created in APM Server. It can change when the APM Server adds new fields, new fields are added by updating libbeat, or the generator logic is changed by updating libbeat. The created index pattern then needs to be synced to the Kibana repo, as it is bundled and shipped with Kibana. The versions of libbeat, APM Server and Kibana are fixed and aligned with the stackversion, e.g. libbeat 7.x goes into APM Server 7.x, and the created index pattern needs to be synced to Kibana 7.x.

**Comment by jalvz** [comment]
Well, the fundamental issue is an implicit dependency between APM Server and Kibana, not that something is wrong with the CI. None of the options fixes the issue, the only fix is to actually remove that dependency.

A visual cue to know that Kibana sync is broken without having to go to Jenkins could be a minor nice to have, but I don't like option `1` much because it could end up in us merging unstable builds after unstable builds simply because they are not painted red.

Among those alternatives I slightly prefer option `2`.

**Comment by kuisathaverat** [comment]
We've taken a look at the script that performs the comparison, it compares the output os the APM-Server with a file from a commit/branch of the Kibana repo, by default it is always Kibana master branch. It is possible to make this comparison with a PR in the Kibana repo, but the process will be a little tricky, it would require an additional PR to the APM-Server when the kibana PR is merge something like that:

* Create a PR to the Kibana repo with the new data objects (something like https://github.com/elastic/kibana/pull/36666/files)
* Create a PR to the APM-Server repo with the libbeats update (something like https://github.com/elastic/apm-server/pull/2150/files) it has an environment variable that points to the Kibana PR 
* Merge Kibana PR
* Update APM-Server PR to point to Kibana master again
* Merge APM-Server PR

In this way, the build will never break. All the stuff related to this issue make me think that we should try to automate (half-automate) the libbeat update process, this will remove all the pain with this stage and we would make @graphaelli really happy ;)

```
BEATS_VERSION?=master
...
are-kibana-objects-updated: python-env
	@$(MAKE) clean update apm-server
	@$(PYTHON_ENV)/bin/python ./script/are_kibana_saved_objects_updated.py --branch ${BEATS_VERSION} <(./apm-server export index-pattern)
```

**Comment by jalvz** [comment]
We do look up Kibana PR's already here: https://github.com/elastic/apm-server/blob/b953715c90136e7ffea1fd48f9bc4e134a73eee2/script/are_kibana_saved_objects_updated.py#L104

**Comment by kuisathaverat** [comment]
true, in that case, what we have a delay to make this PR? Is it possible to make it before the APM-Server PR? What are the whole manual steps need we perform now to make the libbeats update?

**Comment by jalvz** [comment]
Yes, ideally we should create the Kibana PR before putting up the server one. I often forget, so I create the server PR, then Kibana, then retrigger server tests.

**Comment by kuisathaverat** [comment]
The beats update process looks like this one

```
branch=master # or 6.4 ...
git checkout -b update-beats-${branch} --track origin/${branch}
make update-beats &> tmp && mv tmp out
msg=`tail -1 out | sed s/"--- Use this commit message: "//g`
git add -A
git commit -m "${msg}"
git push -u origin update-beats-${branch}
```

Could I said that the PR to the kibana repo is something like this?

```
git clone https://github.com/elastic/kibana.git
hub fork --remote-name=origin
./apm-server export index-pattern > kibana/src/legacy/core_plugins/kibana/server/tutorials/apm/index_pattern.json
cd kibana
git add src/legacy/core_plugins/kibana/server/tutorials/apm/index_pattern.json
echo "Updating apm index pattern
Changes in index-pattern.json:
$(git diff)" > prepared-message.md
git commit -m "[apm] update index pattern"
git push -u origin apm-update-index-pattern
hub pull-request -c -F prepared-message.md
```

**Comment by jalvz** [comment]
Close to that, yeah. You need some `jq` magic to get the rigth object in there. And be careful when Kibana team changes the location of that file (they do some times), or there is any other kind of change.

**Comment by kuisathaverat** [comment]
finally, we have the fix to mark only stages as unstable, Could it be a start to manage it?

![image](https://user-images.githubusercontent.com/5400788/59110528-9f4bca00-893f-11e9-90b8-36ea80872108.png)

**Comment by kuisathaverat** [comment]
PR with the proposal https://github.com/elastic/apm-server/pull/2322
