### ISSUE TITLE
Panics can lead to lost error logs and request counter for rum endpoints missing. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2143]
If a panic occurs while processing requests, we don't recover from the panic and therefore also don't log the panic. Ensure the server recovers on panics while processing requests and logs an appropriate message.  

RUM endpoint is not wrapped in `logHandler` which leads to RUM requests not being part of the overall request cound.

**Comment by graphaelli** [comment]
closed by #2144
