### ISSUE TITLE
Document that _source is required for the UI or remove from apm-server.yml

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#2152]
See this section in `apm-server.yml`:
https://github.com/elastic/apm-server/blob/c61eefc16af65814061f1275577c2e23f0377bc2/apm-server.yml#L216-L219

It's not clear that uncommenting this leads to a malfunctioning UI: https://discuss.elastic.co/t/java-agent-is-sending-empty-transations-span/178923

So I suggest to either remove this or to add a warning.

**Comment by jalvz** [comment]
removed in #2153 , thanks!
