### ISSUE TITLE
Host APM on-premise/internally and fetch metrics from cloud

### ISSUE THREAD

**Issue by ciarancourtney** [elastic/apm-server#2169]
The biggest issue I have running APM in the cloud is cost, particularly disk usage. On-prem storage/compute is much cheaper.

Is there any feature planned that APM can periodically fetch collected data from clients in the cloud, instead of clients pushing data to APM?

**Comment by simitt** [comment]
There are no plans of making the APM Server pull based. But you can run APM Server on-prem and configure the agents to point to that APM Server. 

Our documentation around [storage management](https://www.elastic.co/guide/en/apm/server/current/storage-management.html) could also be of interest for you.
