### ISSUE TITLE
[docs]APM Server support on Elasticsearch Service

### ISSUE THREAD

**Issue by ErnestoBezanilla** [elastic/apm-server#2178]
As per [release notes](https://www.elastic.co/guide/en/cloud/current/ec-release-notes-2019-01-24.html) I believe the statement `APM Server is not yet supported on Elasticsearch Service` on this [page](https://www.elastic.co/guide/en/apm/server/7.0/configure-cloud-id.html) is incorrect

**Comment by bmorelli25** [comment]
Thanks for catching this!
