### ISSUE TITLE
[self-instrumentation] report error events

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2198]
apm-server does not report errors other than panics during request handling.  Good candidates on intake are
- [ ] non-authorization related 4xx and all 5xx responses
- [ ] libbeat queue insertion failures

**Comment by axw** [comment]
Let's come back to this later when we have a problem statement that motivates the changes.

(Also I think this will be more important, and we'll be more motivated to make the changes, if/when we enable instrumentation by default for APM Server running in ESS.)
