### ISSUE TITLE
[self instrumentation] Enhance existing intake traces

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2199]
- [ ] add response information for non-200 responses.  Currently only a status code is included but no additional information.  503 can be caused by a few different issues and should be distinguishable when looking at traces
- [ ] add client information when metadata can't be read at all, for debugging max request header too large, invalid metadata, pending req timeout

**Comment by jalvz** [comment]
Related https://github.com/elastic/apm-server/issues/1140

**Comment by axw** [comment]
Let's come back to this later when we have a problem statement that motivates the changes.

(Also I think this will be more important, and we'll be more motivated to make the changes, if/when we enable instrumentation by default for APM Server running in ESS.)
