### ISSUE TITLE
[self instrumentation] Enhance publishing traces

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2200]
- [ ] Trace concurrent request and pending request queue timings
- [ ] Tag counts per types of each type of transaction processed, perhaps size too?  # of stacktrace frames?

**Comment by jalvz** [comment]
So this is 2 different things, right? Improve instrumentation, and improve monitoring.

**Comment by graphaelli** [comment]
This was intended to just cover tracer instrumentation but if we end up juggling some logging and metrics as a result I think that's a win.

**Comment by axw** [comment]
Let's come back to this later when we have a problem statement that motivates the changes.
