### ISSUE TITLE
[ILM] Make policies more flexible

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2240]
As a follow up on having basic ILM support added to APM, policies should be more flexible to support advanced user needs. 
Find a good way of making policies more flexible, e.g. by 
* providing multiple pre-defined policies
* ship a policy json file which can be changed by users
* allow to define phases and actions per event type in the `apm-server.yml` config file
* ..

**Comment by graphaelli** [comment]
Perhaps a quick alternative would be to bundle multiple named policies that users can use as a baseline and them customize via the UI.
