### ISSUE TITLE
[ILM] Ensure event specific template is overwritten 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2253]
When starting up APM Server, a generic template with all the mappings and a minimal template per event type with `index.lifecycle` information is loaded to ES. 
In case `ilm` is enabled, the `index.lifecycle` information should be set accordingly, in case `ilm` is disabled, this information should be removed accordingly. 

When running `apm-server setup` the `setup.template.overwrite` setting is implicitly set to `true`, to ensure the whole setup is completed. 

When starting APM Server, usually templates do *not* get overwritten for the current APM Server version once they have been loaded, as the default value for `setup.template.overwrite` is `false`. This is because multiple APM Server instances can be running, and it is enough to take care of the setup once. 

When switching from non ILM to ILM handling the first time, all the ILM policies will be newly created. If this happens, the server also ensures that the event type specific templates get overwritten accordingly, so everything works as expected out of the box. 

**Switching between ilm enabled and disabled more often, policies don't get newly created, and therefore also templates do not get overwritten by default.** 

This could lead to following scenarios though:
* Having ilm disabled, enabled, disabled and then enable again: event specific templates are already created without `index.lifecycle` information and are therefore not overwritten. Indices with ILM pattern are created, but no rollover policy can be applied, so indices are unmanaged but don't have a daily pattern, and therefore grow endless. 
Possible solution (for error indices):
```
POST apm-8.0.0-error-000001/_ilm/remove
PUT apm-8.0.0-error-000001/_settings
{
    "index.lifecycle.name": "apm-8.0.0-error",
    "index.lifecycle.rollover_alias": "apm-8.0.0-error"
}
```

* Setup APM Server with ILM enabled, then switch to disabled: the event specific template would still hold ILM information, and therefore ILM lifecycle errors would occur.  

Possible solution (for error indices):
```
POST apm-8.0.0-error-000001/_ilm/remove
```

One can check if an index is managed or not with `
GET indexname/_ilm/explain`

**Comment by bmorelli25** [comment]
Added a small note about this into the ILM documentation: https://github.com/elastic/apm-server/pull/2231

**Comment by graphaelli** [comment]
closing for now, we can revisit if this ends up being a problem in real usage.
