### ISSUE TITLE
Apply Geo-IP pipeline also on http.request.socket.remote_address

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2262]
Currently the geo-ip pipeline is defined to be applied only on RUM agent based events on the [`client.ip`](https://github.com/elastic/apm-server/blob/master/ingest/pipeline/definition.json#L43) field. 

~We could also apply it to process the `host.ip` information and store into `host.geo`.~

Update:
The `host.ip` is the ip parsed from the requests remote address, which is always the host from which the request is sent to the server. 
The agents can send up the `remote_ip` of the original request though, which is stored in `http.request.socket.remote_address`. It would make sense to apply the geo-ip pipeline on this field.

**Comment by graphaelli** [comment]
avoid `client.geo`, up to implementer to find the right field.

**Comment by simitt** [comment]
Thinking about this from an ECS perspective, would it really be _wrong_ to also store information from `http.request.socket.remote_address` in `client.ip` and apply the geo ip pipeline on it? How about we define an additional field, indicating whether or not this is _real user_ information, something like setting `client.end_user: false` for non RUM events? Not sure how maps are built exactly on top of that data and if that would be complicated or error prone.

**Comment by simitt** [comment]
@roncohen what do you think about the above suggestion?

**Comment by roncohen** [comment]
@simitt I like the idea of extracting `http.request.socket.remote_address` into `client.ip` in APM Server.

**Comment by jalvz** [comment]
I have one question about this (and sorry for being late):

Lets say that someone wants to count number of requests per country (derived from IP). Lets say also that that person is using DT.

Would that mean that they'd get duplicated counts, one from RUM's `client.ip` and another from the backend's `http.request.socket.remote_address`?

**Comment by simitt** [comment]
There could be a number of events available for the same trace. So yes if you want to count per trace, and only count on `client.ip` you probably have duplicates. For uniqueness one would need to e.g. include a non-exist check on `parent.id`.
