### ISSUE TITLE
APM with Django putting double metrics for http status codes

### ISSUE THREAD

**Issue by lokeshjawane** [elastic/apm-server#2266]
I have a new application and I was trying to implement APM plugin with Django, followed the steps as per official documents(https://www.elastic.co/solutions/apm) to integrate with Django app. But Somehow in Kibana, the HTTP metrics counts are getting double, means when i bombard 100 rps to ap server? the kibana dashboard shows 200 rps, where for other metrics it works fine.

Appreciate a Help here, Thanks.

**Comment by graphaelli** [comment]
@lokeshjawane Thanks for getting in touch, we'd love to help out but we could use some more information to help narrow down where the issue might be.  Can you start a thread over in the [forum](https://discuss.elastic.co/c/apm) - you will be prompted for the information we'll need to get started.

If we determine there's an issue we can follow up with a GH issue to track the enhancement or fix.  Thanks!
