### ISSUE TITLE
Metric names starting with span and transaction are dropped

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#2286]
To reproduce:

```
curl -H 'Content-Type: application/x-ndjson' -XPOST localhost:8200/intake/v2/events -d \
'{"metadata":{"service":{"name":"test","environment":"dev","agent":{"name":"java","ephemeral_id":"5699134d-7765-47b0-ba23-50d628430399","version":"1.6.2-SNAPSHOT"},"language":{"name":"Java","version":"1.8.0_162"},"runtime":{"name":"Java","version":"1.8.0_162"},"version":null},"process":{"pid":46597,"title":"/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/bin/java"},"system":{"architecture":"x86_64","hostname":"Felixs-MBP.fritz.box","platform":"Mac OS X"}}}
{"metricset":{"timestamp":1560518272600000,"samples":{"span.self_time.count":{"value":1},"span.self_time.sum":{"value":633.288}}}}
'
```

The resulting documents in Elasticsearch don't contain the `span.self_time.count` and `span.self_time.sum` metrics. When removing the `span` prefix, the metrics are present.

It seems like the APM server disallows metric names to have that namespace. For the breakdown metrics elastic/apm#70, we need to have metrics which mimic the document structure of transactions and spans.

Neither the response of the APM server nor the logs indicate that the metrics are dropped.

**Comment by felixbarny** [comment]
I should probably add that there's another situation to watch out for:

The metricsets also contain `span` and `transaction` at the top-level. So it's worth adding a test which such a metricset:

```
{
  "metricset": {
    "timestamp": 1555603735414000,
    "transaction": {
      "name": "test transaction",
      "type": "request"
    },
    "span": {
      "type": "app"
    },
    "samples": {
      "span.self_time.count": { "value": 10 },
      "span.self_time.sum":   { "value": 200.000 }
    }
  }
}
```

**Comment by simitt** [comment]
Thanks @felixbarny for the info. The test cases are covered in the referenced PR.
