### ISSUE TITLE
Multiple Application's pointing to parent index pattern with different keywords

### ISSUE THREAD

**Issue by kgrvamsi** [elastic/apm-server#2304]
If i have different applications consider like AppA,AppB,AppC and if i setup the indexPattern on the APM server as "apm-*" then is there a way that i can feed all my metrics at application level like "app-AppA-*","app-AppB-*" so that the filtering of the apm logs specific to the application in kibana would be easy

**Comment by jalvz** [comment]
Hi, 
I am not sure I understand your issue.
Metric events collected by agents and indexed by apm-server have a `service.name` attribute that should contain those `AppA`,`AppB`,`AppC` values, that you could use to filter in Kibana.
Have you tried it, or does that not work for you?

**Comment by graphaelli** [comment]
Closing this out as we haven't heard back - feel free to reopen if there's more to add.
