### ISSUE TITLE
Define fields supporting breakdown graphs

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2306]
Specifically, as described in https://github.com/elastic/apm/issues/78

That is not final, so we can only follow and adapt as reqs change

**Comment by felixbarny** [comment]
The hopefully final changes have been applied. Note that now durations are reported as µs without fraction. Previously, it was ms with fractions. That should be reflected in the mapping (`long` or `integer` vs `scaled_float`). Technically, it would be a long but an `integer` may be good enough.
