### ISSUE TITLE
agent specific metrics in index template?

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2312]
While working with some custom node metrics today @watson discovered that the metrics reported by the agent were only useful in some cases, ultimately depending on whether a mapping existed for the metric.  For metrics known to apm-server, there was no issue.  For those unknown, the utility depends on the first data point reported.   In this specific case, the node agent reported 3 cpu metrics -  the known one as a `scaled_float`, the two unknown were a `float` and a `long` respectively based on the first points reported.  This is highly related to https://github.com/elastic/apm-server/issues/1229.

The purpose of this issue is to discuss approaches for resolving this.

Per preliminary discussion with @watson, we don't believe always reporting values that could be floating point, be formatted as such (`0.0`) works or is even feasible.

One option could be a requirement that all floats must be known to apm-server ahead of time.  This clearly limits the agent's ability to add metrics out of cycle with apm-server and the Elastic Stack but could be a reasonable trade off for having the correct/efficient data type used for storage.

Another option is to provide agent-specific index templates that users would be responsible for loading themselves (perhaps through an apm-server subcommand, `apm-server import-agent-metrics template http://...`).  Those templates could be updated without need for a stack release.

Another thought is to have dynamic mappings per namespace in the metrics index mapping, something like:
```json
{
  "labels": {
    "path_match": "nodejs.*",
    "mapping": {
      "scaling_factor": 1000000,
      "type": "scaled_float"
    }
  }
}
```
Known fields would get their mapping while unknown ones could fall back on this.

**Comment by simitt** [comment]
I like the idea of having dedicated templates installed per agent. 

Maybe we could be smart about this in the server by providing something like `apm-server.agent.templates` config that loads configured templates from files on startup, and additionally  offer a command to load them. Maybe we could also leverage CM by checking for registered services and agents on startup and loading according templates by default. 
We could bundle the newest agent metric configs with every APM Server release, but also allow customers to override with newer ones, when agents update in between. 

The problem with additional templates is that they only get applied for new indices. Now as long as we have daily indices this wouldn't be a big issue, but if someone uses ILM with current policies it would take up to a week until templates would be applied based on a index rollover.

**Comment by axw** [comment]
Once https://github.com/elastic/elasticsearch/issues/61939 is available, we can extend the metricset definition to include a metric type. This would enable out-of-cycle additions to the agents, without any need to update templates.

Given that we're moving towards Fleet, it no longer makes sense to build a feature that involves loading templates from apm-server. I'll close this under the assumption that we can rely on type hints in the future. @elastic/apm-server let me know if you have any concerns and we can discuss/reopen.
