### ISSUE TITLE
[docs] Adding definition of "frame"

### ISSUE THREAD

**Issue by kunisen** [elastic/apm-server#2329]
By reading this page, I found it's hard to understand what is a `frame`.
https://www.elastic.co/guide/en/apm/server/current/sizing-guide.html

Currently we have very clear definition of [`transaction`](https://www.elastic.co/guide/en/apm/get-started/7.2/transactions.html) and [`span`](https://www.elastic.co/guide/en/apm/get-started/7.2/transactions.html), but we don't have that for `frame`.
Appreciate if we can have that adding to docs.

**Comment by graphaelli** [comment]
Good idea, I don't think we have this currently.
