### ISSUE TITLE
Consider unifying all fields.yml files

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2331]
Some time ago it was ok, because errors didn't have anything to do with transactions.

But now errors have some transaction fields, so metricsets, and data types are more related/dependent.

fields.common.yml is also confusing because some attributes are common to transactions and spans, others to transactions and metrics, others to transactions and errors... so it doesn't help much.

I think a single file with all the apm fields would be cleaner.

**Comment by graphaelli** [comment]
We can revisit this as we work on ingestion strategy for 8.0, I don't think we should touch it before then.
