### ISSUE TITLE
[Automation] Lint stage

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-server#2342]
the intake stage invokes the `check-full` target here https://github.com/elastic/apm-server/blob/9f9eb1913e93c06d6936a95107cbc61920651958/script/jenkins/intake.sh#L13, which in turn invokes the linter here https://github.com/elastic/apm-server/blob/bdd4550116fa50a288f37b8ff6a46f4a25d2b2fd/Makefile#L116

it would be to take the linter out of `check-full` in the make file and run it alone in a separate stage after the integration tests

**Comment by cachedout** [comment]
Closing after discussion in https://github.com/elastic/apm-server/pull/3966
