### ISSUE TITLE
npm install error (APM-AGENT)

### ISSUE THREAD

**Issue by zqc0512** [elastic/apm-server#239]
[root@soc apm-server-6.0.0-rc1-linux-x86_64]#npm install elastic-apm --save
npm WARN saveError ENOENT: no such file or directory, open '/opt/elasticsearch-apm/apm-server-6.0.0-rc1-linux-x86_64/package.json'
/opt/elasticsearch-apm/apm-server-6.0.0-rc1-linux-x86_64
└─┬ elastic-apm@0.3.1
├── after-all-results@2.0.0
├── console-log-level@1.4.0
├── cookie@0.3.1
├── core-util-is@1.0.2
├─┬ debug@3.1.0
│ └── ms@2.0.0
├── elastic-apm-http-client@4.1.0
├─┬ end-of-stream@1.4.0
│ └─┬ once@1.4.0
│ └── wrappy@1.0.2
├── fast-safe-stringify@1.2.0
├─┬ http-headers@3.0.1
│ └── next-line@1.1.0
├── https-pem@1.0.4
├─┬ is-native@1.0.1
│ ├── is-nil@1.0.1
│ └── to-source-code@1.0.2
├── normalize-bool@1.0.0
├── object-assign@4.1.1
├─┬ redact-secrets@1.0.0
│ ├── is-secret@1.1.1
│ └── traverse@0.6.6
├─┬ require-in-the-middle@2.1.2
│ ├── module-details-from-path@1.0.3
│ └─┬ resolve@1.4.0
│ └── path-parse@1.0.5
├── semver@5.4.1
├── sql-summary@1.0.0
├─┬ stackman@2.0.1
│ ├─┬ async-cache@1.1.0
│ │ └─┬ lru-cache@4.1.1
│ │ ├── pseudomap@1.0.2
│ │ └── yallist@2.1.2
│ ├── debug@2.6.9
│ ├── error-callsites@1.0.1
│ ├─┬ load-source-map@1.0.0
│ │ ├── in-publish@2.0.0
│ │ └── source-map@0.5.7
│ └── path-is-absolute@1.0.1
├─┬ unicode-byte-truncate@1.0.0
│ ├─┬ is-integer@1.0.7
│ │ └─┬ is-finite@1.0.2
│ │ └── number-is-nan@1.0.1
│ └── unicode-substring@0.1.0
└── uuid@3.1.0

`npm WARN enoent ENOENT: no such file or directory, open '/opt/elasticsearch-apm/apm-server-6.0.0-rc1-linux-x86_64/package.json'`
npm WARN apm-server-6.0.0-rc1-linux-x86_64 No description
npm WARN apm-server-6.0.0-rc1-linux-x86_64 No repository field.
npm WARN apm-server-6.0.0-rc1-linux-x86_64 No README data
npm WARN apm-server-6.0.0-rc1-linux-x86_64 No license field.

**Comment by watson** [comment]
Hi @zqc0512 

Thanks for reaching out 😃 

I responded to your question on our Discuss forum:
https://discuss.elastic.co/t/fail-install-apm-agent-output-package-json-not-find/104174

I'm therefore going to close this issue for now. If you have any questions related to the APM agent for Node.js, you can create issues in the agent repository: https://github.com/elastic/apm-agent-nodejs
