### ISSUE TITLE
[APM-CI] move integration testing out of pull request pipeline

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2413]
We're starting to ignore the new apm-integration-testing failures since they're failing frequently.   Let's move them to their own pipeline for now while we work on making them more reliable.

**Comment by v1v** [comment]
There were a couple of fixes recently which affected the apm-integration-testing:
- https://github.com/elastic/apm-integration-testing/issues/525
- https://github.com/elastic/apm-integration-testing/pull/524 

Is this an issue yet?

**Comment by v1v** [comment]
Another existing issue with the rumjs agent:
- https://github.com/elastic/apm-integration-testing/issues/531

**Comment by mdelapenya** [comment]
@graphaelli if this is not still an issue, we can close it. Could you check this behavior again please?
Thanks!

**Comment by graphaelli** [comment]
i don't think this is an issue
