### ISSUE TITLE
Central config: Etag not updated when updating configuration

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#2434]
The Etag does not change when changing the configuration. For example, set the sample rate to 0.1, and query the endpoint. Now set the sample rate to 0.2 and query again. The Etag is the same.

Similarly, when providing the Etag in a `If-None-Match` header, the server responds with `304 Not Modified` when updating the configuration as opposed to responding with a 200.

**Comment by felixbarny** [comment]
The problem is that the Etag is just the document ID and does not take the `_version` field into account:

https://github.com/elastic/apm-server/blob/b54c8f10f3afa8688c9512940f04f9415da3d695/agentcfg/fetch.go#L73

**Comment by axw** [comment]
Suggestion: hash all the config attributes. This would have the added benefit that if you go from `A -> B -> A` (unlikely as it may be), agents that have seen `A` but not `B` will not have to take any action.

**Comment by simitt** [comment]
@felixbarny thanks for reporting. Just to ensure we are on the same page here, this is a _theoretical_ bug at the moment, as the current UI doesn't allow to edit configs, but only to delete and recreate.

**Comment by axw** [comment]
@simitt the UI does allow editing (I'd do a screencast by the app keeps crashing...)

There's a pencil icon to edit next to each service config. Click that, edit the config, hit "Save configuration".

**Comment by simitt** [comment]
oh right!
