### ISSUE TITLE
Should not reset pipelines on startup if they already exists

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#2440]
As a user, i might change the APM pipeline to do something slightly different. If APM Server is restarted, my pipeline gets reset. APM Server shouldn't reset the APM pipeline once it's been created

**Comment by simitt** [comment]
There's a setting `apm-server.pipeline.overwrite` that is set to `true` by default. I think this could be as simple as setting it to `false` (by default). 
By the way, this got just recently _fixed_, https://github.com/elastic/apm-server/pull/2273, as this was the agreed on behavior but not applied due to a bug. The bugfix will go out in `7.2.1`.

**Comment by roncohen** [comment]
`setup.template.overwrite` is false by default. Seems like we should stick to that also for `apm-server.pipeline.overwrite` ?

**Comment by simitt** [comment]
I agree it is inconsistent. Some context on this decision from when we introduced the pipeline registration. The Server ships with the `pipeline/definition.json` file where users can create their own pipeline, using another name, so the overwrite would not be a problem. This would also allow to update the default pipelines by adding new processors without user interaction. 
For this to work we require the pipeline file to be overwritten on update, which would lead to losing the users settings in the file. Agree, this is not a nice behavior. 
For a workaround: users can always create their own pipelines directly in ES and configure the server to use those pipelines.

**Comment by roncohen** [comment]
Thanks for the additional context. A pipeline "owned" by APM Server makes sense, but i suggest we name it `.apm` or similar to indictate that it's a "system" pipeline.

For now, I suggest we revert the code change and update the docs to make them correctly state that `apm-server.pipeline.overwrite` defaults to false.

**Comment by graphaelli** [comment]
IIRC we made this change because otherwise it is difficult to push out pipeline updates, as the pipelines not versioned.  Looking at it again I agree it's more surprising that `overwrite` is always on versus not getting the latest pipeline configuration when upgrading.
