### ISSUE TITLE
[Docs] document more prominent the importance of loading template

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2470]
There seem to be issues occasionally because of missing templates when template loading is  disabled. While it is enabled by default, we should document the importance of either having `setup.template.enabled: true` or explicitly running `apm-server setup` before startup and on every upgrade, as templates are versioned. 

cc @bmorelli25

**Comment by sqren** [comment]
This problem keeps occurring: 

 - https://github.com/elastic/support-dev-help/issues/7454
 - https://github.com/elastic/support-dev-help/issues/7856
 - https://github.com/elastic/support-dev-help/issues/7930
 - https://github.com/elastic/kibana/issues/44468

@bmorelli25 Do you have bandwidth to look into improving docs for this?

**Comment by bmorelli25** [comment]
Yup, I'll prioritize this. Thanks @sqren.

**Comment by bmorelli25** [comment]
Partially implemented in #2170. Will also add a troubleshooting section in the Kibana docs.
