### ISSUE TITLE
Provide configuration for `Access-Control-Allow-Headers` response header on the RUM endpoint

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#2497]
In certain setups, e.g. [running frontend application in a headless browser](https://github.com/elastic/apm-agent-rum-js/issues/331), there's a need to add a header to all of the requests made from the frontend application. However, adding any header to the request that the RUM agent makes to the APM server would make the request to fail since the value for `Access-Control-Allow-Headers` is hardcoded with predetermined headers.

Another use-case for this, is for generating fake load from a headless browser and adding `x-forwarded-ip` header to all requests so that the load seems to be coming from a different ip.

**Comment by simitt** [comment]
@jahtalab trying to figure out how urgent this is. Would you consider it an edge case or is it a blocker?

**Comment by jahtalab** [comment]
@simitt , AFAICS, this is only a blocker for small number of use-cases!

**Comment by graphaelli** [comment]
Sorry this has been sitting for so long @jahtalab.  How should this work, would a user configure APM Server to append to the hard coded list of the headers unconditionally?  Something like:

```yaml
allow_headers:
  - header1
  - header2
```

And then all requests received `Access-Control-Allow-Headers: Content-Type, Content-Encoding, Accept, header1, header2` ?

Is there any use case for removing from the static list / allowing the user to define the entire list?

**Comment by jahtalab** [comment]
@graphaelli , thanks for picking this up. I think appending to the hard coded list of headers should be sufficient. I can't think of any use case for removing from the hard coded list specially since the those headers are necessary for the agent<>APM server communication.

**Comment by jalvz** [comment]
@jahtalab this is only for OPTIONS requests, correct?
