### ISSUE TITLE
POST /config/v1/agents not documented

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-server#2523]
Only `GET` is mentioned in [the documentation](https://www.elastic.co/guide/en/apm/server/7.3/agent-configuration-api.html).

The java agent uses `POST`, which is apparently officially supported.
https://github.com/elastic/apm-agent-java/issues/781#issuecomment-518637176

**Comment by felixbarny** [comment]
Currently, it's only documented here: https://github.com/elastic/apm/blob/master/docs/agent-development.md#apm-agent-configuration-via-kibana

**Comment by felixbarny** [comment]
Out of curiosity: do you want this to be documented because you are implementing an agent yourself or want to otherwise consume the API?

**Comment by simitt** [comment]
While on it, we should also change the section _Intake API_ to _API_ and the subsection _Events API_ to _Intake API_. 
<img width="248" alt="Screenshot 2019-08-06 at 14 25 41" src="https://user-images.githubusercontent.com/5555349/62539729-35c03d00-b856-11e9-82a7-27dbf80e0c77.png">

**Comment by OrangeDog** [comment]
I want it to be documented because public, supported APIs should be documented.
