### ISSUE TITLE
[Automation][ci] more resilience to environmental issues 

### ISSUE THREAD

**Issue by v1v** [elastic/apm-server#2529]
Some broken builds were related to some issues when accessing to dockerhub, in order to minimize this particular glitches we will retry twice with sleep time, it might take a bit longer the builds but ideally, it might reduce the broken builds when there are issues related to accessing dockerhub for instance.

An example of the typical environmental issue is:

![image](https://user-images.githubusercontent.com/2871786/62619571-fe619700-b90e-11e9-91d9-22db50e127a0.png)

**Comment by kuisathaverat** [comment]
see https://github.com/elastic/apm-pipeline-library/pull/150 that PR add the golang image to the packer cache, so there is no longer need to be build
