### ISSUE TITLE
Add component property (with APM Server value) to server information API response

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-server#2538]
The motivation for this enhancement to make it easier to diagnose issues like https://github.com/elastic/apm-agent-dotnet/issues/436. An APM agent can use [APM Server's information API](https://www.elastic.co/guide/en/apm/server/current/server-info.html) to verify that agent's `server-URL(s)` configuration option value indeed points to APM Server and not some other component (like Elasticsearch, etc.). At the moment APM Server's information API response doesn't contain anything guaranteeing that the response came from APM Server - adding `component` property (with `APM Server` value) will provide agents with bullet-proof mechanism to verify if the component with which it communicates is indeed APM Server.

**Comment by SergeyKleyman** [comment]
> I'm not familiar with `component` - can you elaborate?

`component` refers to to the new property name in APM Server's information API response JSON. For example:
```
{
  "ok": {
    "build_date": "2018-07-27T18:49:58Z",
    "build_sha": "bc4d9a286a65b4283c2462404add86a26be61dca",
    "version": "7.0.0-alpha1"
    "component": "APM Server"
  }
}
```
The name of the new property doesn't have to be `component` - it can be any suitable name as long as the client can deduce that it indeed communicates with APM Server.

> What do you think of using a [`Server`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server) header?

Yes, [`Server`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server) header can be used for this purpose but I would prefer this information as JSON property for the following reasons (in the decending order of importance):
1. If there is a proxy between the agent and the APM Server it can override `Server` header.
2. This new `component` property is tightly related to already existing properties above: `version`, `build_date`, etc. so returning them via different mechanisms will seem as a strange design decision - to wit it will make documentation for APM Server's information API look cumbersome: some info returned in body and some in headers.
3. I know that it became very popular with the rise of REST approach but I personally always disliked using transport layer to pass application data. If we pass `component` info (application data) as `Server` HTTP header (transport layer) we will have to rethink it if we switch to another transport, for example gRPC.

**Comment by jalvz** [comment]
We decided to not prioritize this for now, we'll get back to it for 8.0.
 I'll close this to reduce the noise, but it is tracked in meta issue https://github.com/elastic/apm-server/issues/2632

Feel free to reopen if a new need arises. Thanks!
