### ISSUE TITLE
Docs: 7.2 and earlier have "funny" fields.asciidoc

### ISSUE THREAD

**Issue by nik9000** [elastic/apm-server#2577]
`fields.asciidoc` is broken for asciidoctor in 7.2 and earlier. It looks like 7.3 and later they are fixed because they have elastic/beats#12242. Is there any chance they just need to pick up that change? I don't know nearly enough about the builds here to fix it. Or if it is even worth it. We need to fix the `fields.asciidoc` file to be compatible with asciidoctor, but maybe we can do it manually and just never run the generator again? I have no idea.

@dedemorton, could you comment on this?

**Comment by bmorelli25** [comment]
Ahh, looks like @dedemorton already figured this out on the Beats side. Here's the PR that needs to be backported for Beats: https://github.com/elastic/beats/pull/12432

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/apm-server/pull/2578.
