### ISSUE TITLE
APM agent queue/buffers increased 

### ISSUE THREAD

**Issue by vikassharma12345** [elastic/apm-server#2579]
APM Server goes down for While. APM agent queue/buffers increased.please suggest,how to free that Queue From all APM Agent. I have 15 different APM Agent to only one APM Server.
Using elastic-apm-agent-1.8.0.jar, elasticapm.properties files to tomcat bin and added following to setenv.bat:CATALINA_OPTS="$CATALINA_OPTS -javaagent:/home/tomcat/elastic-apm-agent-1.8.0.jar -Delastic.apm.service_name=P_24_CA -Delastic.apm.server_url=http://IP -Delastic.apm.environment=PR -Delastic.apm.capture_body=all"

**Comment by jalvz** [comment]
Please use the forum (https://discuss.elastic.co/) for troubleshooting and questions, we use github issues for verified bugs and items planned for implementation.

Thanks!
