### ISSUE TITLE
Ambiguous kafka and logstash config documentation

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2580]
In https://www.elastic.co/guide/en/apm/server/master/kafka-output.html and https://www.elastic.co/guide/en/apm/server/master/logstash-output.html (for every release version) it says that the default value for `enabled` is true, which it is ambiguous at best.

AFAIK those `enabled` are true "by default" only **if** (the whole `output.elasticsearch` sections is commented out **or** `output.elasticsearch.enabled` is false) **and** the corresponding section is uncommented (`output.kafka` or `output.logstash`). 
Since by default that is not the case, you can't really say that `output.kafka.enabled` and `output.logstash.enabled` are on by default.

IMO we should be explicit and document it as I said above, or event better just mention that  kafka / logstash `enabled` settings are disabled by default and add `enabled: true` in the example snippets.

**Comment by bmorelli25** [comment]
Closed in #3093.
