### ISSUE TITLE
Allow any ECS field on metricset root

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#2627]
As we add more metrics in agents, we'll likely see the need to allow an increasing number of fields on the root of metricset documents. For breakdown graphs, we added field on the root for `span` and `transaction`. Upcoming metricsets changes will likely require to have `destination.address` (issue incoming) and more fields on the root. Adding fields today require special cases in APM Server.

Instead of adding more special cases, I suggest we move to allow any ECS fields to be set on the root of metricset documents in the Intake API.  cc @simitt

**Comment by graphaelli** [comment]
pushing this out again

**Comment by axw** [comment]
I haven't seen any issues that would have been resolved by implementing this, so closing for now. Let's come back to it when we see a strong need.
