### ISSUE TITLE
apm-server systemd file has invalid docs link

### ISSUE THREAD

**Issue by tsg** [elastic/apm-server#264]
Minor issue, but after installing the deb package:

```
# systemctl status apm-server
● apm-server.service - apm-server
   Loaded: loaded (/lib/systemd/system/apm-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-10-30 11:25:09 UTC; 9min ago
     Docs: https://www.elastic.co/guide/en/beats/apm-server/current/index.html
 Main PID: 5106 (apm-server)
   CGroup: /system.slice/apm-server.service
           └─5106 /usr/share/apm-server/bin/apm-server -c /etc/apm-server/apm-server.yml -path.home /usr/share/apm-se

Oct 30 11:25:09 ubuntu-xenial systemd[1]: Started apm-server.
```

The "docs" link (https://www.elastic.co/guide/en/beats/apm-server/current/index.htm) is invalid and seems to be a leak from the Beats packaging system. I'm opening the ticket here for better visibility, but the fix might be needed in the Beats repo.

**Comment by simitt** [comment]
Also the docs link in the packaged `Readme` is invalid for all packages, as it is also built with the standard beats script.
