### ISSUE TITLE
Provide Access-Control-Allow-Origin header on the response to RUM ACM endpoint

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#2646]
Requests made to the /config/v1/agents by the RUM agent will fail if the `Access-Control-Allow-Origin` header is not present on the response.

The value of this header should be generated using the same algorithm used for the `/intake/v2/rum/events` endpoint.

**Comment by jahtalab** [comment]
@elastic/apm-server , Is it possibility to provide the CORS headers on all endpoints by default?

**Comment by jalvz** [comment]
On all endpoints? What is the use case eg for `/intake/v2/events` ?

**Comment by jahtalab** [comment]
I'm basically looking for a solution to make sure we don't forget about CORS headers for the endpoints that are going to be used by the RUM agent. 

We can consider other solutions, if you think having the CORS headers for all endpoints has 
drawbacks. Either way, I don't have a strong opinion on the solution itself but I think we should find a way to make sure these headers are added for all RUM endpoints in the future.

**Comment by jalvz** [comment]
got it, thanks!
