### ISSUE TITLE
Remove trailing slash for apm-server.kibana.host configuration option

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#2647]
If the value of `apm-server.kibana.host` config option contains a trailing slash, e.g. `http://kibana:5601/` the APM server fails to connect to Kibana. We can however check the presence of a trailing slash and remove it.

**Comment by jalvz** [comment]
I did implement this, but got me thinking again about it - I think I was too quick to stamp a "bug" label...

_Semantically_, a URL with a trailing slash represents a directory, and without it represents a regular file. The code for that is in Beats and used also for Elasticsearch, etc. It might be the case that in some case there is a _meaningful_ difference and if we just go around remove trailing slashes, then we might unexpectedly break things (on a minor release, never the less).

I understand it is annoying that `http://kibana:5601/` doesn't work, but I am not sure that solutions like "oh I guess you meant X, so I'll go ahead and do X for you even if you said Z" are any better. 

I'll bring this up to the team, but I am leaning towards not fixing. We could, however, provide a test command that checks Kibana connection, or generally improve upon the `test config` subcommand.
This is non trivial, significant work.

**Comment by graphaelli** [comment]
I'm in favor of stripping it.

**Comment by graphaelli** [comment]
let's try a custom ucfg unpack function for this
