### ISSUE TITLE
APM dashboards all `Store time with dashboard` to `Last 24 hours`

### ISSUE THREAD

**Issue by LeeDr** [elastic/apm-server#266]
**Kibana version**: 6.0.0-rc2

**Elasticsearch version**: 6.0.0-rc2

**Server OS version**: CentOS

**Browser version**: Chrome

**Original Kibana install method (e.g. download page, yum, from source, etc.)**: rpm packages

**Description of the problem including expected versus actual behavior**:
The APM Dashboards that get optionally loaded as part of the setup have the `Last 24 hours` timespan saved in them.  So if you're looking at some other timespan of data anywhere in Kibana and open an APM dashboard, it changes the timepicker to `Last 24 hours`.  It gets annoying after a few times if you're looking at data further in the past.

Any dashboard can be saved with its `Store time with dashboard` set, but I don't think any of the beats dashboards have the time stored with them so this seems unusual.

Since there's only 5 [APM] dashboards, it's pretty easy to just click Edit, uncheck the `Store time with dashboard`, and Click Save.

Or maybe there really is a reason that APM users would only ever want to see the last 24 hours and the Dashboards are fine as-is.

**Steps to reproduce**:
 1. From any page in Kibana, set the time picker to something other than `Last 24 hours`
 2. Open an APM dashboard
 3. The timepicker is changed to Last 24 hours

View of the checkbox when saving a Dashboard:
![image](https://user-images.githubusercontent.com/13542669/32187680-c4b2085c-bd73-11e7-8888-8c189c5ec727.png)

**Comment by roncohen** [comment]
thanks @LeeDr!

@makwarth OK to change this so it follows the standard pattern?

**Comment by makwarth** [comment]
@roncohen Yes, I spoke with Lee about this on Slack yesterday. I don't know why the APM dashboards don't follow the standard behavior. Maybe @simianhacker has input?

**Comment by simianhacker** [comment]
I was just trying to make the experience match the behavior of the original site. Also there are instances where the default “last 15 minutes” wasn’t enough data.

**Comment by simianhacker** [comment]
I’m cool with whatever, we should probably test it a bit to make sure the results give us what we expect. If we do change this it will need to happen in both the link in the index pattern and the dashboard.

**Comment by makwarth** [comment]
@roncohen mind taking this on in the APM Server team?
