### ISSUE TITLE
Custom properties for Spans

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-server#2666]
Hello,

Is there any idea of having Custom properties for spans? 

Usage example : 
During execution, we need to make HTTP requests to external services and log both request\response and headers for each request. 

Currently, the only way which I found to use a transaction custom, take span id, and create property "request_<span_id>". But it's pretty complicated to log and view the information in such way.

Thanks,
Stas

**Comment by jalvz** [comment]
Hello! 

We generally use GitHub Issues for verified bugs and planned features. Please do not submit issues for questions and feature requests. However, we do want to help! 

Head on over to our official Discuss forum and let us know there what's on your mind. You will reach a higher audience, get help from the broader community, and maybe learn how others solved similar problems to yours.

https://discuss.elastic.co/c/apm

Thanks!
