### ISSUE TITLE
[docs] Switch to shared docs versioning

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#2692]
Currently we update the documentation version in `version.asciidoc` for each release. Example [here](https://github.com/elastic/apm-server/pull/2684/files#diff-bb1c954f8a5c98b5e555ebe570a0f4a1R1). It's not time consuming, but it is prone to errors.

With the addition of https://github.com/elastic/docs/pull/1147 and https://github.com/elastic/docs/pull/1148, there's now an easy way to let the docs repo (and the docs release manager) handle this. Lisa's already done this for the stack-docs repo in https://github.com/elastic/stack-docs/pull/493.

I think it makes sense to do the same for APM Server.

Relevant discussion in https://github.com/elastic/docs/issues/804.

---

Implementation:

- [x] Add `current` file for Agents -- https://github.com/elastic/docs/pull/1198
- [x] Add APM Server attribute to docs -- https://github.com/elastic/docs/pull/1187
- [x] Tell APM Server to use shared version file -- https://github.com/elastic/apm-server/pull/2741
- [x] Tell Agents to use "current" file (after 7.4) -- https://github.com/elastic/apm/issues/150
- [x] Remove Agent attributes from APM Server (after 7.4) -- https://github.com/elastic/apm-server/pull/2741
- [x] Update internal [documentation](https://github.com/elastic/apm-dev/blob/master/docs/apm-documentation.md#updating-an-apm-agent-to-a-new-version) 
- [ ] ~Clean up/remove deprecated `*-v` and hardcoded attributes in the docs repo -- Maybe?
https://github.com/elastic/docs/pull/1187/commits/3519dd934de87a1ba3c8649136b359f36762a788~

**Comment by graphaelli** [comment]
Agreed, I don't see any reason not to do this.

**Comment by bmorelli25** [comment]
This PR requires two steps:

Step 1 is to update the doc repo. Changes have been proposed in https://github.com/elastic/docs/pull/1187. I didn't realize it when I created this issue, but this change also allows us to finally stop linking to `current` versions of the APM Agent documentation. I've also added that change to this PR. Once merged, I'll start step 2 which involves changes in apm-server.

**Comment by bmorelli25** [comment]
✅Done in the PRs linked in the description.
