### ISSUE TITLE
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200

### ISSUE THREAD

**Issue by YasiruDev** [elastic/apm-server#2695]
I have installed apm-server and setup apm-server.yml as bellow

```
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "elastic"
```
then run service apm-server start .

configured Node side as bellow

```
var apm = require('elastic-apm-node').start({
    serviceName: 'MyApp',
    serverUrl: 'http://localhost:8200'
  })
```
Checked status

**APM Server status : You have correctly setup APM Server**

**Agent status : Data successfully received from one or more agents**

It's worked last night and showed charts on kibana dashboard.but now i'm getting bellow error on my Console and No services found on dashboard

`[ERROR] APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200`

And bellow is `sudo service apm-server status

![eeeeee](https://user-images.githubusercontent.com/36979604/64530299-664e3780-d32a-11e9-8624-bf002e5763b2.png)
`

**Comment by simitt** [comment]
Please check your apm server logs for more information, as suggested in https://github.com/elastic/apm-agent-nodejs/issues/1332#issuecomment-529433120.

**Comment by YasiruDev** [comment]
I have checked apm-server logs inside `/var/log/apm-server` . but there are no any error log file

**Comment by jalvz** [comment]
Hey, I am closing this as you reopened in https://discuss.elastic.co/t/apm-server-transport-error-econnrefused-connect-econnrefused-127-0-0-1-8200/198693 (which is the right place!)
