### ISSUE TITLE
[RUM] metricsets schema @timestamp should be created on server to avoid clock drift

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-server#2700]
+ When sending the metricsets events from the agents side, we use the current system clock time and send it along with `@timestamp` field in the metricset schema.
+ This value is susceptible to clock drift or users clock, Instead the server must be creating the value when the metricsets are sent from the agents. 

There are workarounds other agents are doing like https://github.com/watson/relative-microtime/blob/e91dbc903809d5b5e1228e6a28b84f0032871b9a/index.js#L4-L12 , Instead we would like this to be changed in the server atleast for the RUM agent. 

**NOTE: This is a blocker for RUM agent**

**Comment by vigneshshanmugam** [comment]
Figured out a workaround in RUM agent, Its not a blocker but still would be good to be done on server side.

**Comment by simitt** [comment]
In https://github.com/elastic/apm-server/issues/723 the timestamp was made optional, and if not set, then it is created by the server. Afaik it was intended that the RUM agent doesn't send the timestamp and then it would be set by the server. 
@vigneshshanmugam is there a reason the RUM agent sends the timestamp and cases where the timestamp should be used and not ignored? Should this only concern metric events or all event types?

Somewhat related discussion about calculating and setting the RUM timestamp in the server https://github.com/elastic/apm-server/issues/1830.

**Comment by jahtalab** [comment]
@simitt , The issue is that timestamp is defined as required in the [metricset](https://github.com/elastic/apm-server/blob/master/docs/spec/metricsets/metricset.json#L31) which means the payload will fail if we don't set it. We should define the timestamp as optional and then the RUM agent will not set it and APM server can provide it. The same way it works for transactions.

**Comment by simitt** [comment]
You're right! I am going to make it optional right away.
