### ISSUE TITLE
APM Server should properly respond to config endpoint when Kibana is unreachable

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#2702]
Currently APM server keeps the connection to the config endpoint open while waiting for the Kibana endpoint to respond. In cases in which the Kibana endpoint is not available and the request timeouts the APM server just closes the connection instead of responding to it.

from the APM server logs:
```
apm-server             | 2019-09-12T11:54:36.011Z	ERROR	[request]	beater/agent_config_handler.go:156	error handling request	{"request_id": "b6f6b98d-8f38-44cf-90bb-251edc22c781", "method": "GET", "URL": "/config/v1/agents?service.name=nonexistent-service", "content_length": 0, "remote_address": "172.22.0.1", "user-agent": "curl/7.54.0", "response_code": 503, "error": "sending request to kibana failed: Post http://kibana:5601/api/apm/settings/agent-configuration/search: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
```

From the curl logs:
```
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8200 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8200 (#0)
> GET /config/v1/agents?service.name=nonexistent-service HTTP/1.1
> Host: localhost:8200
> User-Agent: curl/7.54.0
> Accept: */*
>
* Empty reply from server
* Connection #0   to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by jalvz** [comment]
I can't reproduce this. Patched Kibana client with following:
```go
	go func() {
		time.Sleep(time.Second * 5) // let connection be established without problem
		dialer = transport.NetDialer(time.Nanosecond)
		client.Connection.HTTP =
			&http.Client{
				Transport: &http.Transport{
					Dial:    dialer.Dial,
					DialTLS: tlsDialer.Dial,
				},
				Timeout: time.Nanosecond,
			}
	}()
```

`curl -v  http://localhost:8200/config/v1/agents?service.name='a'`
```*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8200 (#0)
> GET /config/v1/agents?service.name=a HTTP/1.1
> Host: localhost:8200
> User-Agent: curl/7.61.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Cache-Control: max-age=300, must-revalidate
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Date: Fri, 13 Sep 2019 12:12:29 GMT
< Content-Length: 50
< 
{
  "error": "sending request to kibana failed"
}
* Connection #0 to host localhost left intact
```

That is correct behaviour. Server log looking the same as yours:

`ERROR	[request]	middleware/log_middleware.go:74	sending request to kibana failed	{"request_id": "e4823c15-becf-4bb3-9937-5a2083dd3554", "method": "GET", "URL": "/config/v1/agents?service.name=a", "content_length": 0, "remote_address": "127.0.0.1", "user-agent": "curl/7.61.0", "response_code": 503, "error": "sending request to kibana failed: Post http://localhost:5601/api/apm/settings/agent-configuration/search: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}`

**Comment by jalvz** [comment]
@jahtalab have you been able to reproduce this more than once?

**Comment by jahtalab** [comment]
@jalvz , I haven't encountered it again! I will reopen once I have more detail!

**Comment by Palecha** [comment]
@jahtalab , I am facing the same issue which you have highlighted above, may i know what was the fix.

**Comment by axw** [comment]
@Palecha I would recommend opening a topic at https://discuss.elastic.co/c/observability/apm/58, with some information about what the issue you are facing. Your questions are more likely to be seen and answered there.
