### ISSUE TITLE
APM Server monitoring using apm_system role fails

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#2708]
**Describe the bug**

The [Monitoring APM Server](https://www.elastic.co/guide/en/apm/server/7.2/monitoring.html) section in the docs describes how to configure the server to send monitoring data to Elasticsearch, and recommends using the built-in `apm_system` user/role.

In 7.2 this fails with an error in the logs like this:

> Failed to publish events: 403 Forbidden: {"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:data/write/bulk] is unauthorized for user [apm_system]"}],"type":"security_exception","reason":"action [indices:data/write/bulk] is unauthorized for user [apm_system]"},"status":403}

**To Reproduce**

1. Create a 7.2 stack with security enabled. Set a password for the `apm_system` user
2. Configure apm-server.yml according to https://www.elastic.co/guide/en/apm/server/7.2/monitoring.html, using the password from step 1.
3. Start the APM Server
4. Check the logs, see there's an error

**Expected behavior**

Monitoring should work using the apm_system user/role.

**Comment by axw** [comment]
This appears to be a regression in 7.2, relating to changes in the underlying Beats infrastructure.

The apm_system role has the same cluster-level privileges as beats_system, but the latter has some additional index-level privileges. These were added to beats_system in https://github.com/elastic/elasticsearch/pull/40876; apm_system should presumably have been updated at the same time.

**Comment by cachedout** [comment]
I have opened https://github.com/elastic/elasticsearch/pull/47302 to start work on this issue.

**Comment by simitt** [comment]
@cachedout can you confirm this issue was fixed with https://github.com/elastic/elasticsearch/pull/47302#issuecomment-539020207?

**Comment by cachedout** [comment]
@simitt I am still waiting for reviews on this: https://github.com/elastic/elasticsearch/pull/47668

**Comment by cachedout** [comment]
Hi again @simitt and @axw.

I have merged https://github.com/elastic/elasticsearch/pull/47668 into master in Elasticsearch.

Backports have been opened to [7.5](https://github.com/elastic/elasticsearch/pull/49913) and [7.x](https://github.com/elastic/elasticsearch/pull/49912). Please let me know if you have any concerns. Thanks!

**Comment by simitt** [comment]
LGTM

**Comment by axw** [comment]
Backports are all done, so closing this out. Thanks @cachedout!

**Comment by simitt** [comment]
Tested with `apm_system` user by enabling xpack security in Elasticsearch and following the steps in the [APM Server docs](https://www.elastic.co/guide/en/apm/server/7.2/monitoring.html):
```
monitoring:
  enabled: true
  elasticsearch:
    username: apm_system
    password: somepassword
```

Kibana Monitoring UI:
![Screenshot 2020-01-23 at 13 41 30](https://user-images.githubusercontent.com/5555349/72985355-23c35e00-3de6-11ea-9463-23837ecad201.png)


Using built in `apm_system` user works as expected.
