### ISSUE TITLE
APM server unable to load config, Permission denied

### ISSUE THREAD

**Issue by ivssh** [elastic/apm-server#2721]
OS: Ubuntu 18.04 bionic beaver

Installation: DEB package 64-bit

My config is as follows:
```
output.elasticsearch:
  hosts: ["localhost:9200"]
```

After I start the apm-server service using
`sudo service apm-server restart`

I get this error:
`Exiting: error loading config file: config file ("/etc/apm-server/apm-server.yml") must be owned by the user identifier (uid=1000) or root`

I do
`sudo chown -R root:root /etc/apm-server`

then I get this error
`Exiting: error loading config file: open /etc/apm-server/apm-server.yml: permission denied`

But if I do
`sudo apm-server run`

it works, docs say to use `apm-server run`. Am I missing something here?

**Comment by graphaelli** [comment]
I'd like to ask you to open a [discuss thread](https://discuss.elastic.co/c/apm) for this issue, and link to it from here.   The discuss forum is the place to discuss issues and solutions, keeping this in one place makes it easier to follow along. In case we identify a bug or feature request during discussion we can open a dedicated issue again.
