### ISSUE TITLE
Sourcemap in existing errors

### ISSUE THREAD

**Issue by xiz0r** [elastic/apm-server#2724]
Hi, I have RUM in a production application and collect several errors, at this time I had not uploaded the source map.
Now upload the sorcemap, to analyze those errors, but I still see the stacktrace of the error without the source map.
Is there a way to update this errors that were already tracked to use the sourcemp?

I uploaded the sourcemap to: 
https://xxx.apm.us-central1.gcp.cloud.es.io/assets/v1/rum/sourcemaps
and 
https://xxx.apm.us-central1.gcp.cloud.es.io/assets/v1/sourcemaps

I uploaded the sourcemap in two endpoints since I don't know which one is correct...
Deploy version: 6.5.4
Thanks

**Comment by graphaelli** [comment]
We have some ideas on this but no concrete plans to tackle it yet.

**Comment by axw** [comment]
Unfortunately the idea that we had in mind (applying source maps in ingest node) did not really pan out, so this is not something we're going to be able to address. If we find an alternative that would enable reindexing with source maps, we'll reopen.
