### ISSUE TITLE
Test and run built binaries on target platforms

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2733]
We would like to start adding support for more Operative Systems, gradually.
For that, we would need to have tests ensuring the binary works on each platform and version officially supported.

Running the entire test suite on each supported platform and for each PR would incur a high overhead and is not needed, but we should have some smoke tests covering the basics:

- Grab the latest snapshot for each relevant branch. 
- Generate OS specific package.
- Install the package.
- Point it to some available elasticsearch and kibana instances and run it for a few seconds.
- Do a few essential checks:
  - Test subcommand
  - Connect to Elasticsearch and Kibana
  - Load template
  - Accept requests
  - Validate healtcheck endpoint
  ...

**Comment by jalvz** [comment]
cc @kuisathaverat

**Comment by kuisathaverat** [comment]
support matrix https://docs.google.com/spreadsheets/d/10B1c0kFe0XrUu9lUwzUEr4XMeK_4ppao2KNzJp_Wp4M/edit#gid=497386949

**Comment by v1v** [comment]
IIUC there are three different tasks:
- Code the essential checks.
- Provide an infra/platform for each required OS.
- Automate the execution of those checks for the above platform/infra.

Something to have a look might be what the beats team use for a kind of similar scenario:
- https://github.com/elastic/beats-tester

Not sure whether it might be relevant for this particular feature or something we could potentially extend it to fulfill the requirement of different OS support.

@mdelapenya and @ElWPenn

**Comment by cachedout** [comment]
I have submitted https://github.com/elastic/beats-tester/pull/160 as a way to move forward on this request.

It adds APM server to the [beats-tester project ](https://github.com/elastic/beats-tester/)which is currently in use to do the kind of package validation requested here.

As you can see by looking at the project, it performs validation by grabbing snapshots and then ensuring that installations work fine and then performs some basic validation checks, such as ensuring that appropriate successful startup messages appear in logs.

It does *not* connect to an Elasticsearch instance nor does it perform functional tests. In effect, it verifies that the packages are installed and can start.

IMHO, this is an easy way for us to get basic validation across a wide variety of platforms. If after looking at this, we feel as though we should do additional functional testing on this set of platforms, please let me know and we'll discuss whether it's more appropriate to add that functionality to the beats-tester project or find another path forward.

Thanks!

**Comment by axw** [comment]
@cachedout this looks great, thank you. I think this is sufficient for now.

**Comment by cachedout** [comment]
@axw Great! How would you prefer to consume these test results? Let me give you a few options:

* Just run the `beats-tester` project by hand as-needed locally. This is more or less what the Beats team does now, though this is obviously not ideal.

* Use the existing job on the Beats CI to invoke the tests ad-hoc: https://beats-ci.elastic.co/job/Beats/job/beats-tester-mbp/

* We create a new job on the APM CI which just runs the APM Server portion of the Beats tester, which could be run either ad-hoc or on a schedule and send you notifications.

* Something else?

Let me know what you'd prefer and we'll make it happen. Thanks!

**Comment by axw** [comment]
I feel like we're going to either forget, or leave things too late, if we make it ad-hoc/manually triggered.
Is it expensive to run? If we could run it weekly with notifications then I think that would be ideal.

**Comment by cachedout** [comment]
> Is it expensive to run?

Totally agree. I will set this up on the APM CI and set it to run weekly with email notifications. I'll get back to you with details once this is all provisioned and ready for you. Thanks!
