### ISSUE TITLE
Cypher test failing

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2737]
`test_https_no_cipher_selected` fails with:

```AssertionError: "No cipher can be selected" does not match "[SSL: NO_CIPHERS_AVAILABLE] no ciphers available (_ssl.c:727)"```

Reproduced locally on Linux, with Python 2.7.

Not 100% sure if if fails always, or only sometimes.

**Comment by graphaelli** [comment]
I haven't seen this on CI or locally - can you reopen if still necessary?
