### ISSUE TITLE
Copy client.ip address to source.ip address for SIEM integration

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2766]
Copy the value of `client.ip` to `source.ip` when available for future APM SIEM integration. 

@MikePaquette I am not a 100% sure about the semantic difference between `client` and `source` for APM related data. Would you agree that we can just copy the value and treat it the same?
cc @SergeyKleyman as you are more familiar with the semantics of this value (it corresponds to `context.request.socket.remote_address` on intake API).

**Comment by MikePaquette** [comment]
@simitt Yes, for the APM use case, it is fine to just copy the `client.ip` value to the `source.ip` field.

**Comment by simitt** [comment]
fyi @graphaelli I moved this into the 7.5 milestone.

**Comment by simitt** [comment]
@spong this might be interesting for you, as I assume you are going to use `source.ip` instead of `client.ip` in https://github.com/elastic/kibana/issues/47067.
I do not plan to enable the GeoIP pipeline, so the only field under `source` will be `ip`.

**Comment by spong** [comment]
@simitt, thanks for the heads up! I don't think there's any requirement to start showing APM data on the map, so we should be fine without enriching the `source.geo` fields. For ref though, this is the [minimum configuration](https://www.elastic.co/guide/en/siem/guide/7.4/conf-map-ui.html) we publish in the SIEM docs.
