### ISSUE TITLE
Change ILM default policies (on-prem, cloud)

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2788]
With https://github.com/elastic/apm-server/pull/2764 we make ILM policies user configurable. Supporting to change policies directly in the server yml file makes it easier for users to change policies, e.g. different rollover time or adding a delete phase. 

To avoid having more indices than necessary, we discussed changing the default policies.

**Current policies summary** (see details [here](https://github.com/elastic/apm-server/blob/master/idxmgmt/ilm/policy.go#L24)):
span, error: rollover after 1 day OR 50gb (whichever is first), move to warm phase after 7 days
transaction, metric: rollover after 7 days OR 50gb, move to warm index after 31 days

**Suggested new default policies (on-prem and cloud):**
span, error, transaction, metric: rollover after 30 days OR 50gb, move to warm phase after 30 days

@elastic/apm-server , @nehaduggal please comment your preferences.
Target: 7.5 release

cc @nachogiljaldo fyi

**Comment by nehaduggal** [comment]
The new proposal looks good to me!
