### ISSUE TITLE
Split up indices for Errors and Transactions

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#279]
We should discuss if we want to generate seperate indices for `errors` and for `transactions`. The documents are semantically different and splitting up indices would allow easier handling in some cases.

**Comment by roncohen** [comment]
This could probably be achieved by changing the default index pattern to include `processor.name`. It's currently set to either `transaction` or `error`.

```diff
- index: "apm-%{[beat.version]}-%{+yyyy.MM.dd}"
+ index: "apm-%{[beat.version]}-%{[processor.name]}-%{+yyyy.MM.dd}"

**Comment by graphaelli** [comment]
per #351, we plan to hold of support for this configuration immediately as not all events include a processor, eg onboarding.

**Comment by simitt** [comment]
see https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_literal_indices_literal

**Comment by simitt** [comment]
Investigate if this can be solved in a similare way as sourcemaps are now written to their own index.

**Comment by beniwohli** [comment]
@elastic/apm-server a bit late to the party, sorry, but would it be possible to also put spans into their own index? That would e.g. allow to have a much shorter retention time for spans than for transactions.
