### ISSUE TITLE
Creating docs and ES index template out of fields.yml

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#28]
The `fields.yml` file is used as a base to create documentation, kibana index-patterns and indexing templates for ES.

Not all options that are allowed by [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-params.html) are implemented for index template creation right now. Also there are some limitations per mapping param that might not be that obvious. Eg 
- `enabled:false` can only be used for `mapping types` and `object` fields, see [official doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html).
- difference between `enabled` and `index`. 
- ..

It would be nice if we could document all known fields, with additional information if the field is indexed, searchable, etc. For this we need to implement additional logic in beats, see https://github.com/elastic/beats/pull/4853

Right now we have set `dynamic: false` only for `context`. This means that no additional attributes are indexed dynamically. In case we don't want to automatically index all other fields we either have to implement proper functionality for the index template creation or also set `dynamic: false` for other objects.

**Comment by simitt** [comment]
@roncohen not sure if you saw the state here, is it ok with you to keep the docs to only include what is indexed?

**Comment by roncohen** [comment]
@simitt Any idea how much work it would take to make sure all fields and child fields are written to documentation?

**Comment by alvarolobato** [comment]
The index patterns are being moved to kibana, this changes probably doesn't make too much sense anymore. Will re-evaluate later if needed and create an up to date issue.
