### ISSUE TITLE
Add `rows_affected` for database queries in spans

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2802]
* [ ] Add `span.context.db.rows_affected` to Intake API as optional field
* [ ] Clarify if field needs to be indexed.
* [ ] Decide where to store the field in ES. There is an issue in [ECS](https://github.com/elastic/ecs/issues/514) to standardize on sql fields.

**Comment by axw** [comment]
Confirmed this works with BC1, using Go agent v1.7.0:

![image](https://user-images.githubusercontent.com/843579/72696223-6979ef80-3b76-11ea-8bd4-e142311d0838.png)
