### ISSUE TITLE
docs: apm-server.ssl.certificate example uses confusing file name

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#2815]
The [docs for setting up TLS for the server](https://www.elastic.co/guide/en/apm/server/current/secure-communication-agents.html#ssl-setup) show sample configuration, referencing an imaginary file called "/etc/pki/client.pem". The file name suggests that it's a client certificate, but this config `apm-server.ssl.certificate` relates to the server's own certificate.

@bmorelli25

**Comment by axw** [comment]
I would suggest renaming it to "/etc/pki/server.pem", or maybe "/etc/pki/apm-server.pem".

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/apm-server/pull/3092.
