### ISSUE TITLE
docs: intake example request body uses old v1 format for span

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#2825]
As pointed out in a Discuss forum post, our docs have an [example request body](https://www.elastic.co/guide/en/apm/server/master/example-intake-events.html) which use a mix of the old v1 and newer v2 formats for the span event:

```{"span": {"id": "0123456a89012345", "trace_id": "0123456789abcdef0123456789abcdef", "parent_id": "ab23456a89012345", "transaction_id": "ab23456a89012345", "parent": 1, "name": "GET /api/types", "type": "request.external", "action": "get", "start": 1.845, "duration": 3.5642981, "stacktrace": [], "context": {}}}```

A few things stick out:
 - `"parent": 1` is not a thing any more
 - "start" is only for RUM, so we should probably not use it as an example; instead include a timestamp
 - type/subtype/action were added post-v1 I think?

**Comment by axw** [comment]
@bmorelli25

**Comment by simitt** [comment]
The example is generated from [testdata](https://github.com/elastic/apm-server/blob/master/testdata/intake-v2/events.ndjson) used for automated testcases . We should clean up the testdata input to reflect more real world data.
