### ISSUE TITLE
Add description to remote_address

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#2840]
The JSON Schema spec does not provide a description for [transaction.request.socket.remote_address](https://github.com/elastic/apm-server/blob/0ba2567155df30e1ced50337980a638352956bc3/docs/spec/request.json#L45-L47). We should add a description to make it clear what value agents should populate.

Relates to https://github.com/elastic/apm/issues/157

**Comment by simitt** [comment]
This has been lying around for a few days, just hadn't come around to merge, but it is closed now with https://github.com/elastic/apm-server/pull/2809.

**Comment by axw** [comment]
Thanks/sorry - I thought you were planning to do it, I didn't search hard enough.
