### ISSUE TITLE
Upload sourcemaps synchronously

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2862]
Change sourcemap upload from asyncronous to syncronous. This can be achieved by using the new go-elasticsearch client.

**Comment by simitt** [comment]
Working on this I realized we have some issues here:
* Currently sourcemaps are uploaded as beats events, by using libbeat outputs. Therefore there is no direct requirement having ES configured when uploading sourcemaps. Switching to the new go-elasticsearch-client for uploading could be considered a breaking change, as it requires a configuration for Elasticsearch. The counter argument is for sourcemaps to be usable during ingestion one needs to configure either an ES output or a dedicated sourcemap ES instance. If none is configured the uploaded sourcemaps are of no value as they cannot be used. So technically the requirements change a bit, but for using sourcemaps overall requirements stay the same. 
* At the moment the sourcemap index is defined in the `output.elasticsearch` section. Users can can make use of index build selectors, e.g. use a different sourcemap index for different service names. The build selectors used by the ES output are not accessible from the APM Server, so they cannot easily be reused to figure out the proper index for the sourcemap. A kind of hackish way would be to initialize a new `BuildSelector` with the given ES output and use that for sourcemap upload. This could be error prone to future changes, as it needs to be implemented independent of the libbeat logic.

**Comment by simitt** [comment]
Even when sourcemaps can only be used when an ES endpoint is configured, this change would force users to permit APM Server write access to ES, even when using a different output for ingestion. Thanks @graphaelli for pointing this out. 
Based on above mentioned issues, we consider this a breaking change and revisit for 8.0.0. 

Another possibility is to remove functionality from APM Server and instead add it to the Kibana endpoint in 8.0.0 (cc @sqren ).

**Comment by axw** [comment]
The current rough plan is to move source mapping out of APM Server altogether, and rely on ingest node (https://github.com/elastic/apm-server/issues/3606) and uploading through Kibana. Closing this, we can reopen as needed.
