### ISSUE TITLE
usr/local/bin/docker-entrypoint: line 8: exec: apm-server: not found

### ISSUE THREAD

**Issue by Nurlan199206** [elastic/apm-server#2863]
I'm trying run APM server v 7.3.0 on OpenShift 3.11 but receiving error log console `usr/local/bin/docker-entrypoint: line 8: exec: apm-server: not found`

Kubernetes version 1.11 on OpenShift.

how to fix?

**Comment by j-chao** [comment]
@Nurlan199206 
According to the OpenShift [docs](https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html):

> directories and files that may be written to by processes in the image should be owned by the root group and be read/writable by that group.

Looking at the filesystem, it looks like /usr/share/apm-server is owned by the apm-server group:
`drwxr-x---.  6 root apm-server  193 Oct 28 18:54 apm-server`

Therefore, you'll need to modify the filesystem to give the root group access to that executable.
Something like the following Dockerfile should work:

```
FROM elastic/apm-server:7.4.2
USER root
RUN chown -R apm-server /usr/share/apm-server
RUN chmod -R 777 /usr/share/apm-server

USER apm-server
WORKDIR /usr/share/apm-server
EXPOSE 8200
CMD ./apm-server -e -d "*"
```

**Comment by graphaelli** [comment]
Thanks for chiming in @j-chao.  I should have followed up earlier that these kinds of issues are best brought to the [Discuss forum](https://discuss.elastic.co/c/apm) as we like to keep the Github repository for product issues - verified bug reports, pull requests, apm-server specific feature requests.  If this issues results in one of those please feel free to reopen.
