### ISSUE TITLE
Parse headers for client IP address and use remote_address only as fallback. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2867]
With https://github.com/elastic/apm/issues/157 the agents are streamlining on sending the remote_address in `context.request.socket.remote_address` without trying to parse any original IP from headers. 
Users can configure agents to not send up headers, by default request headers are sent to the APM Server. When headers are sent, the APM Server can parse them to try to collect information about the source of the request and store that in `client.ip` and `source.ip`. Those values are used for SIEM integration and the GeoIP processor. 

For RUM events the APM Server already has an algorithm in place to [derive the IP address from headers if available](https://github.com/elastic/apm-server/blob/master/utility/remoteaddr.go#L40). I suggest to reuse this logic also for backend events to collect the `client.ip` and `source.ip` address.

**Comment by axw** [comment]
Verified. I created a simple HTTP service, instrumented with the Go agent. Tested the following:
 - curl the service with no headers, `client.ip` and `source.ip` are set to `127.0.0.1` (curl'd localhost) for sampled transactions
 - curl the service with `X-Real-Ip: 1.1.1.1`, `client.ip` and `source.ip` are set to `1.1.1.1` and doc enriched with `client.geo`
 - curl the service with `X-Forwarded-For: 203.0.113.195, 70.41.3.18, 150.172.238.178`, `client.ip` and `source.ip` are set to `203.0.113.195` (no `client.geo`)
 - curl the service with `X-Forwarded-For: 2001:db8:85a3:8d3:1319:8a2e:370:7348`, `client.ip` and `source.ip` are set to `2001:db8:85a3:8d3:1319:8a2e:370:7348` (no `client.geo`)
 - curl the service with `Forwarded: For="[2001:db8:cafe::17]:4711`, `client.ip` and `source.ip` are set to `2001:db8:cafe::17` (no `client.geo`)
 - curl the service with `Forwarded: for=192.0.2.43, for=198.51.100.17`, `client.ip` and `source.ip` are set to `192.0.2.43` (no `client.geo`)
