### ISSUE TITLE
Switch reading sourcemaps to use the official go-elasticsearch client

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2868]
Since there is an official go-elasticsearch client, switch to use this library instead of the libbeat client for fetching the sourcemaps from ES.

**Comment by axw** [comment]
Verified that source mapping still works. I translated some basic CoffeeScript to JavaScript, and followed the instructions at https://www.elastic.co/guide/en/apm/server/current/sourcemap-api.html to upload. Caused the app to throw an exception, and verified the error in the UI showed up properly mapped.

There's an issue with privileges in apm-integration-testing: the `apm_server` role we create lacks the "read" privilege for "apm-*", so it can't query source maps. I tested with the admin user.
