### ISSUE TITLE
Consider ignore_malformed for appropriate fields

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2875]
Following up on #2765, we should consider whether [`ignore_malformed`](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html) would be appropriate on some, like `client.ip`.  It makes sense to reject documents with bad required fields but being a little more lenient on optional fields is probably a good idea.

**Comment by axw** [comment]
I think doing this is going to end up masking bugs in the server or agents, and that we should fix these bugs rather than being permissive. Otherwise the bugs may become entrenched. See also https://tools.ietf.org/html/draft-iab-protocol-maintenance-04

Closing for now, happy to discuss.
