### ISSUE TITLE
Ensure pipeline errors do not cause infinite ingest retries

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2880]
The APM Server currently uses a pipeline with two processors, where no `on_failure` or `ignore_failure` is defined. In case a processor fails on an event, ES will return a status code `500` leading to retries of indexing the failed events in the APM Server. See [libbeat implementation](https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/client.go#L375).
Since the APM Server uses [GuaranteedSend](https://github.com/elastic/apm-server/blob/master/publish/pub.go#L90), the retry results in an infinite loop, see [retry implementation](https://github.com/elastic/beats/blob/master/libbeat/publisher/pipeline/retry.go#L233).

Ensure to user proper error handling on pipelines to avoid an infinite retry loop.

**Comment by simitt** [comment]
related https://github.com/elastic/elasticsearch/issues/48803

**Comment by graphaelli** [comment]
Let's go ahead with the `ignore_failure` patch for master & 7.5 and track the linked elaticsearch issue to see if it makes the next minor, and revert going forward at that point.
