### ISSUE TITLE
[docs] Add stack quick start to documentation

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#2884]
Look at adding a link to the [stack quick start](https://github.com/elastic/apm-contrib/tree/master/stack) to the documentation. The apm-contrib repo is not versioned like our documentation is.

> Maybe a section dedicated to running locally / in development environment?
>
> Also note this is http://ela.st/apm-quick

**Comment by graphaelli** [comment]
Just came across https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html, maybe a stack guide makes sense?  I think it would be ok to duplicate this content in apm-contrb and some other version location.
