### ISSUE TITLE
go build: -i flag seems no longer needed since go v1.10

### ISSUE THREAD

**Issue by BlackYoup** [elastic/apm-server#2885]
Hello,

When trying to compile apm-server on my machine using go v1.12.10, I had an issue:
```
~ $ make apm-server
go build -i -ldflags "-s -X github.com/elastic/apm-server/vendor/github.com/elastic/beats/libbeat/version.buildTime=2019-11-04T16:07:40Z -X github.com/elastic/apm-server/vendor/githu
b.com/elastic/beats/libbeat/version.commit=1726aa000d8e1558879c9e9700966d1a2ce6d4d2"
go build runtime/cgo: open /usr/lib/go/pkg/linux_amd64/runtime/cgo.a: permission denied
make: *** [_beats/libbeat/scripts/Makefile:107: apm-server] Error 1
```

I then found this issue talking about it on the go issue tracker: https://github.com/golang/go/issues/24674

When I drop the `-i` flag from the `GOBUILD_FLAGS` variable in https://github.com/elastic/apm-server/blob/master/Makefile#L25 the build runs successfully.

I'm far away from being a go expert so there may be reasons you're keeping it that I'm not aware of. This issue is mostly a heads up, sorry if you already considered it, I couldn't find a similar issue using the search.

I can make a pull request to remove it if you wish.

**Comment by graphaelli** [comment]
@jalvz to verify on linux, but this seems reasonable

**Comment by jalvz** [comment]
yeah, its fine. feel free to submit a pr @BlackYoup 
thanks
