### ISSUE TITLE
Update Kibana index pattern

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2898]
The APM index pattern in Kibana has not been synced with the latest beats changes. Ensure the Server and Kibana are in sync.

**Comment by jalvz** [comment]
Looks like we are good: 
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/master/223/pipeline
https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/7.x/139/

Can we close, or is this about something else?

**Comment by simitt** [comment]
I created it based on the failing test, but also as a reminder to check when branching out `7.6`. Up to you if you want to close it now.

**Comment by graphaelli** [comment]
closed by https://github.com/elastic/kibana/pull/52938
