### ISSUE TITLE
Model change: transaction.id -> transaction.transaction_id

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#291]
@gingerwizard pointed out that it would be nice to have the field `transaction_id` always be called `transaction_id` across our output model. Today we have `transaction.id` and `trace.transaction_id`. Let's change it so it's `transaction.transaction_id` instead.

This make it easier to filter for a specific transaction for example in a dashboard and show the transaction, all the traces etc. with a single filter

**Comment by ruflin** [comment]
Why not going with `transaction.id` for the `trace` and the `transaction` object? So the trace object would look more like:

```
{
    "context": {
        ...
    },
    "processor": {
        ...
    },
    "trace": {
        "id": 0,
        ...
        "type": "db.postgresql.query"
    },
    "transaction": {
        "id": "945254c5-67a5-417e-8a4e-aa29efcbfb79",
    }
}
```

Ignoring the change in implementation this would require, I think it would be what the user expects.

**Comment by roncohen** [comment]
Nice idea. Let's do that.

**Comment by roncohen** [comment]
Fixed in #345

**Comment by ruflin** [comment]
@roncohen Looking at #345 it seems it's now `trace.transaction.id`. The idea was to have `transaction.id` to make it the same for transaction and trace documents.

**Comment by roncohen** [comment]
Created new issue to track this: https://github.com/elastic/apm-server/issues/357
