### ISSUE TITLE
RUM config endpoint should have Access-Control-Expose-Headers: ETag header in its response

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#2915]
`Access-Control-Expose-Headers: ETag` should be present on the RUM config endpoint. This is required so that the agent would be able to read this header.

Related discussion: https://github.com/elastic/apm-server/issues/2694#issuecomment-533518378

**Comment by vigneshshanmugam** [comment]
I thought this was done already? 

https://github.com/elastic/apm-server/blob/2a12655fa733a58c7676585d18136f7b8d2a9e84/beater/middleware/cors_middleware.go#L70

**Comment by jahtalab** [comment]
Yeah, It was done but this seems to be a bug.

**Comment by simitt** [comment]
calling `curl -i -X OPTIONS "http://localhost:8200/config/v1/rum/agents?service.name=123"` returns
```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type, Content-Encoding, Accept
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Origin:
Access-Control-Expose-Headers: Etag
Access-Control-Max-Age: 3600
Content-Length: 0
Vary: Origin
X-Content-Type-Options: nosniff
Date: Mon, 18 Nov 2019 14:17:03 GMT
```

Not sure if intended or a typo in your report, the server returns `Etag`, not `ETag`.

**Comment by jahtalab** [comment]
The header should be present on the response of the endpoint as well.

**Comment by axw** [comment]
Confirmed that both the OPTIONS and GET response headers include `Access-Control-Expose-Headers: Etag`.

While testing, I found `apm-integration-testing`'s apm-server is failing to read from the central config index. Seems to be an issue with the privileges for the `apm_server_user` user; when I changed to `admin`, it worked as expected.
