### ISSUE TITLE
Add support for `destination` on Intake API

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2917]
According to https://github.com/elastic/apm/issues/115#issuecomment-555814374 add following to the Intake API for `spans`:
*  `context.destination.address`: `keyword`, optional, store as `destination.address` in ES
* `context.destination.port`: `long`, optional, store as `destination.port` in ES

See [ECS#destination](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#ecs-destination)

---
With adding the destination information the server could also
* add logic to parse and populate `destination.ip`, `destination.domain`, `destination.port` if available. This information might be used for APM/SIEM integration in the future. 
* create a geoIP pipeline on `destination.ip`, similar to what we do for `client.ip`.

**Comment by jalvz** [comment]
Works as expected.
