### ISSUE TITLE
Update ILM blogpost to point to ILM docs 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#2930]
The blogpost about using [ILM with APM](https://www.elastic.co/blog/how-to-apply-index-lifecycle-management-to-apm-data) will be outdated for users running APM Server >= 7.5.

Update the blogpost with a note on top, pointing the users to the official [ILM docs](https://www.elastic.co/guide/en/apm/server/7.5/ilm.html) instead. 

Suggested Note:

> With 7.5 APM Server changed the default policies and added support for customized policies. The described configuration settings are partially outdated, and we suggest you refer to the [ILM docs](https://www.elastic.co/guide/en/apm/server/7.5/ilm.html) instead, when using APM Server >= 7.5.

**Comment by simitt** [comment]
@bmorelli25 could you have a look at the suggested note and let me know what you think?

**Comment by bmorelli25** [comment]
Nice! Here are a couple edits:

> In version 7.5, APM Server changed the default ILM policies and added support for custom policies. If you're using APM Server version >=7.5, some of the settings described in this blog post are outdated. We suggest you refer to the [ILM documentation] instead.
