### ISSUE TITLE
Official Definitions for Transaction and Trace

### ISSUE THREAD

**Issue by gingerwizard** [elastic/apm-server#297]
Request for official definitions for these in the docs. There seems to be some variation depending on the agent. This is more useful for messaging and when communicating in the field.

@asawariS @jamiesmith

**Comment by roncohen** [comment]
@gingerwizard there are some big naming changes coming up, we'll make sure we get a proper definition written after.

**Comment by gingerwizard** [comment]
@roncohen if would be nice to know how the schema changes as well between rc2 and GA. Nothing formal just some of the big points. I suspect it will be easier for us to recapture our dataset.

**Comment by roncohen** [comment]
@gingerwizard we try to keep https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc#breaking-changes updated.

**Comment by gingerwizard** [comment]
@roncohen super useful thanks.

**Comment by simitt** [comment]
We currently embed the json spec for the input API in the [official docs](https://www.elastic.co/guide/en/apm/server/6.1/transaction-api.html#transaction-schema-definition) for `transactions` and `errors`. 
The embedded schema definitions contain descriptions for the objects and keys, e.g.
![screen shot 2018-01-24 at 16 41 07](https://user-images.githubusercontent.com/5555349/35341217-6dfbf3e2-0125-11e8-8c37-68f7dc9336d8.png)

I'd appreciate if we werent duplicating descriptions, as this gets easily out of sync. 
What do you think about removing the `description` from the json schema files and instead explicitly add a description section to the docs to make it more user friendly?

**Comment by roncohen** [comment]
I think this issue meant to ask for a couple of paragraphs that explains the general data model in the big picture and how the different document types are related. E.g. what is a span? What does a span represent? How does it relate to transactions? etc.

People can then go into details in the [field descriptions](https://www.elastic.co/guide/en/apm/server/current/exported-fields-apm-trace.html) that we already have.
