### ISSUE TITLE
Ensure that the Elasticsearch client in 8.0 can work with a 7.x elasticsearch instance

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2975]
apm-server 8.0 needs to be compatible with the last 7.x.

Now that we have our own elasticsearch client, we need to ensure we use the right dependency in function of the stack version.

https://github.com/elastic/apm-server/pull/2974 needs a follow up so that, when a v8 agent is created, we ping Elasticsearch to retrieve the version, and if it is 7.x, we tear down the client, make a 7.x connection, and return it as an interface.

This should have no impact in the code other than the `elasticsearch` package.

**Comment by graphaelli** [comment]
* Can go-elasticsearch support this directly?
* What happens during rolling upgrades, what version does the ES cluster report?
* How does libbeat handle this today?
* How do we test this?

**Comment by jalvz** [comment]
> Can go-elasticsearch support this directly

Probably no, but will summon @karmi for confirmation

> What happens during rolling upgrades, what version does the ES cluster report

If there no breaking changes concerning the APIs we use, nothing happens.
If there are breaking changes regarding uploading sourcemaps or creating API keys, we would recommend users to not do those operations during a rolling upgrade.
If there are breaking changes in the `has_privileges` API, we could recommend to upgrade APM Server before Elasticsearch, and detect or recover from that specific error:
eg. if the path changes, the error would be a `404`, and we could trigger a client reconnect upon seeing it to get a fresh version. 
If the response format changes, the error would be an empty struct after JSON unmarshalling, and we could do the same. 

However I don't think that the `has_privileges` will break in 8.0, and even if it does I would tackle this problem when it comes.

> How do we test this

If we migrate Python tests to Go we will be in a better position to test that automatically.

**Comment by simitt** [comment]
APM Server 8.0 is not supposed to work with an ES of version 7.x. Therefore this is not a concern and the issue can be closed.
