### ISSUE TITLE
Bundle Metricbeat/Filebeat with apm-server

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-server#2981]
For the 8.0.0 release of the stack, we are aiming to remove monitoring internal collectors/exporters (#47214, #47215) for Stack Monitoring. 

While Metricbeat can now monitor the stack, the removal of internal collection leaves our users in a position where they have to take extra steps to do such monitoring via Metricbeat. We want to keep the experience of monitoring  simple. 

To that end, we are aiming to bundle Metricbeat and Filebeat with each product in the stack and have its lifecycle managed by the stack product. This saves the user from having to install Metricbeat and Filebeat, and also manage their lifecycles.

This request is similar to others across the stack and I have referenced them below:

https://github.com/elastic/elasticsearch/issues/49399
https://github.com/elastic/kibana/issues/51224
https://github.com/elastic/logstash/issues/11328

**Comment by graphaelli** [comment]
per https://github.com/elastic/beats/issues/14886#issuecomment-562605546, closing this out as the plan is to:

* continue shipping monitoring data directly from APM Server in 8.x
* ship monitoring data externally when Agent is ready to do this
