### ISSUE TITLE
Provide a setup command to create API keys

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2987]
At minimum apm-server should be able to create API keys and apm privileges, and invalidate them.

Optionally/future: 
- list existing keys and privileges 
- validate keys (`has_privileges` call) 
- batch creation (eg. for several services)
- reference docs

**Comment by jalvz** [comment]
Depends on: https://github.com/elastic/apm-server/issues/2338

**Comment by simitt** [comment]
## The following behavior was tested and works as expected:

**Testing configuration settings**
* API Key command works even when `apm-server.api_key.enabled: false`: Running `./apm-server apikey create -E apm-server.api_key.enabled=false` still creates api keys.
* Defaulting back to configured `output.elasticsearch.*` if no dedicated elasticsearch is configured for API Key
* Overwriting user configured in `output.elasticsearch.username` by passing in `apm-server.api_key.elasticsearch.username`

**Testing user privileges**
* Trying to create an API Key with a non-existing user results in a 401: `./apm-server apikey create -E apm-server.api_key.elasticsearch.username=foo -E apm-server.api_key.elasticsearch.password=changeme --json`
* Trying to create an API Key with an existing user, that does not have apm privileges results in an according error
* Trying to create an API Key with an existing user, that has APM privileges but not the `manage_security` privilege results in a `403`. 

**Testing API Key `create`**
* Creating API Key without any information returns key valid for all APM privileges that never expires: `./apm-server apikey create`
* Creating API Key with dedicated name: `./apm-server apikey create --name test`
* Creating API Key with expiration date - API Key is not valid after expiration period: `./apm-server apikey create --expiration 1m` 
* Creating API Key only valid for certain APM privileges: 
```
./apm-server apikey create --name simi-apikey --ingest
```
`curl -i -H 'Authorization: ApiKey createdApiKey' "http://localhost:8200/config/v1/agents?service.name=123"` returns `401` 
but
`curl -i -k -H "Content-type: application/x-ndjson" -H "Authorization: ApiKey dy1tdzBtOEI5NnZwcjk5aTdYX2E6cUd6b1pxQ0FTT2ladlVmVWduOTI0UQ" --data-binary @events.ndjson http://localhost:8200/intake/v2/events` returns `202` 

**Testing API Key `info`**
* `./apm-server apikey info --name simi-apikey --json` returns information about all API Keys with this name
* `./apm-server apikey info --id foo --json` returns information about API Key with this ID
* `./apm-server apikey info --name simi-apikey --valid-only` only returns valid API Keys

**Testing API Key `invalidate`**
* `./apm-server apikey invalidate -name simi-apikey --json` returns array with invalidated API Keys; also checked they are invalid afterwards

**Testing API Key `verify`**:
Verifying for all privileges as well as for dedicated ones works as expected for valid and invalid keys. 

## The following behavior caught my attention:
* trying to create an API Key with a user that is missing privileges results in an error (correct), but something seems off with the json serialization:
Passing in the `--json` flag results in:
```
{
	"error": "simi is missing the following requested privilege(s): sourcemap:write, event:write, config_agent:read.\n\nYou might try with the superuser, or add the APM application privileges to the role of the authenticated user, eg.:\nPUT /_security/role/my_role {\n\t...\n\t\"applications\": [{\n\t  \"application\": \"apm\",\n\t  \"privileges\": [\"sourcemap:write\", \"event:write\", \"config_agent:read\"],\n\t  \"resources\": [\"*\"]\n\t}],\n\t...\n}\n\t\t"
}
```
whereas **not** passing in `--json` results in:
```
simi is missing the following requested privilege(s): sourcemap:write, event:write, config_agent:read.

You might try with the superuser, or add the APM application privileges to the role of the authenticated user, eg.:
PUT /_security/role/my_role {
	...
	"applications": [{
	  "application": "apm",
	  "privileges": ["sourcemap:write", "event:write", "config_agent:read"],
	  "resources": ["*"]
	}],
	...
}
```

* Creating and purging apm app privileges: I might be misunderstanding something here, but the APM Server can only create apm privileges for a superuser or for users that already have a role with apm privileges assigned. In both cases I do not understand why the apm privileges need to be additionally created. If a user does not have the privileges, they are not created by the APM Server. 
The `purge` flag works respectively - it can only delete apm privileges created by the Server, not from any roles created outside. What is the objective of the APM Server creating these privileges in above mentioned use cases and then purging them if they were created by the server? Could we remove the creation part and the purge flag?

**Comment by axw** [comment]
++ to removing auto-creation of privileges, and purge flag

They're operating at a different auth level to the rest of the commands.

It might be useful to have separate sub-sub-commands to create/remove/grant the privileges, which you could use if you're superuser. So basically I think we should completely separate anything that requires `manage_security` from `manage_api_key`.

**Comment by simitt** [comment]
This is how I tested the behavior:


**create roles**
```
PUT /_security/role/apm_apikey 
{
	"applications": [{
	  "application": "apm",
	  "privileges": ["sourcemap:write", "event:write", "config_agent:read"],
	  "resources": ["*"]
	}]
}
```

additional via Kibana UI:
m_apikey: cluster privilege: manage_api_key
m_security: cluster privilege: manage_security

**create users with following roles**
basic: no role
mapikey: m_apikey
msecurity: m_security
apmmapikey: m_apikey,apm_apikey
apmmsecurity: m_security,apm_apikey

**check users privileges (for verification)**
```
curl -u user:pass -H 'Content-Type: application/json' -XPOST http://localhost:9200/_security/user/_has_privileges?pretty -d '
{
  "application":[
    {
      "application": "apm",
      "privileges": ["sourcemap:write","event:write","config_agent:read"],
      "resources":"*"
    }
  ]
}'
```

**create apikeys via CLI (current functionality)**
basic: fails
mapikey: fails
msecurity: fails with `msecurity is missing the following requested privilege(s): config_agent:read, sourcemap:write, event:write.`, but actually creates app privileges
apmmapikey: fails as privileges cannot be created (although user already has the role)
apmmsecurity: valid API Key created
elastic (superuser): valid API Key created

**create apikeys via CLI (without creating app privileges on the fly)**
basic: fails
mapikey: fails
msecurity: fails
apmmapikey: valid API Key created
apmmsecurity: valid API Key created
elastic (superuser): valid API Key created

**Comment by simitt** [comment]
Removal of privilege creation was tested with https://github.com/elastic/apm-server/pull/3251#issuecomment-580065847, therefore this can be set to `test-plan-ok`.
