### ISSUE TITLE
Duplicated Elasticsearch config

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#2990]
Currently, the config for the Elasticsearch client https://github.com/elastic/apm-server/blob/master/elasticsearch/config.go#L45-L55 mirrors libbeat's Elasticsearch output config: https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/config.go#L27

This is a bit dangerous, because if they change or remove fields; config unmarshalling might fail silently and we won't notice. It is also easy to miss new settings.

We should have access to the original data structure to force us be in sync.

**Comment by graphaelli** [comment]
how about a test that compares the structs?
