### ISSUE TITLE
Make container images suitable for ESS/ECE

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#3000]
ECE currently runs a customized version of the default apm-server docker container image, `docker.elastic.co/cloud-assets/apm`.  APM Server should provide an image suitable for direct use instead.

- [ ] Accept UID/GID of apm-server user via environment variable
- [ ] `RUN find / -xdev -perm -4000 -exec chmod u-s {} +`
- [ ] Address zombie reaping issue (needs detail)

**Comment by graphaelli** [comment]
Also, the cloud image creates a user (apm-server) with GID/UID 1000 and moves the binaries from /usr/share/apm-server to /apm-server - need to determine if that's really needed.

**Comment by axw** [comment]
>  Address zombie reaping issue (needs detail)

Since apm-server does not spawn child processes, this shouldn't be needed

**Comment by axw** [comment]
We discussed this recently: given that nobody is clamouring for this, I'm going to close it and we can reopen as needed. The original ask was for ESS/ECE images to be suitable as base images, and that's already the case; I think it still makes sense to apply hardening on top specific to the environment/needs.
