### ISSUE TITLE
Add `classname` to stack trace frame fields

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3006]
As discussed in https://github.com/elastic/kibana/issues/49467 the server should accept `classname` attributes on `stacktrace frames` and require agents to either send a `classname` or a `filename`.

Agent devs need to be aware that stop sending `filename` information is breaking with older versions of the APM Server.

**Comment by axw** [comment]
Verified. I wrote a hello world program in Java, and used the API to capture an exception. I ran it twice: once with agent version 1.12.0 (no support for "classname"), and once with the agent built from source off master (has support for "classname"). Confirmed that classname as well as filename are recorded in the second instance, and that both lead to the same error grouping key.

**Comment by mdelapenya** [comment]
> Verified. I wrote a hello world program in Java, and used the API to capture an exception. I ran it twice: once with agent version 1.12.0 (no support for "classname"), and once with the agent built from source off master (has support for "classname"). Confirmed that classname as well as filename are recorded in the second instance, and that both lead to the same error grouping key.

Hey @axw, could you upload the JAR/Java file with the Hello world? That way anybody could test it with the same scenario than you prepared.

**Comment by axw** [comment]
Sure, it was just this:

```java
import co.elastic.apm.api.ElasticApm;
import co.elastic.apm.api.Transaction;

public class Main {
        public static void main(String []args) {
                for (String arg: args) {
                        System.out.println(arg);
                }

                Transaction transaction = ElasticApm.startTransaction();
                transaction.setName("hoi");
                transaction.setType("polloi");
                transaction.captureException(new Exception());
                transaction.end();
        }
}
```
