### ISSUE TITLE
[Jaeger] Add HTTP endpoint accepting spans via thrift from Jaeger client

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3008]
Add HTTP endpoint, running on port `14268`  to ingest spans sent by jaeger-client via thrift over http.

Part of https://github.com/elastic/apm-server/issues/2886

Starting point: implementation from https://github.com/elastic/apm-server/compare/7.x...axw:otel-7.x

**Comment by jalvz** [comment]
Verified this works. Started the `HotROD` sample app from https://www.jaegertracing.io/docs/1.16/getting-started/#sample-app-hotrod and pointed it to apm-server with `JAEGER_ENDPOINT` environment variable, while having `apm-server.jaeger.http.enabled=true`.

Jaeger traces show up in the Kibana UI with the equivalent structure of the Jaeger UI. Non default ports work too, and disabling the setting also works as expected.

![image](https://user-images.githubusercontent.com/3432712/72818489-dae79a00-3c6b-11ea-857f-274b60c28fb3.png)

![image](https://user-images.githubusercontent.com/3432712/72818554-f81c6880-3c6b-11ea-9107-c15cde840a9d.png)
