### ISSUE TITLE
[Jaeger] Add system tests for http thrift integration with Jaeger agent

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3010]
Add system tests sending spans via a Jaeger client (http) to the APM Server.

See if we can leverage python opentelemetry-api for the tests. Be aware that it is only supported for python 3.

Part of elastic/apm-server#2886

**Comment by simitt** [comment]
According to [Jaeger Docs#client-features](https://www.jaegertracing.io/docs/1.16/client-features/)`jaeger.thrift` over HTTP is not supported for Python. 

An option is to start adding `integration-tests` in golang, using a local Elasticsearch test instance, and ensuring integration tests are only run when running system tests. 

An alternative would be to record an http trift request from another library, e.g. `go` and then use the recorded event together with the [python apache thrift](https://github.com/apache/thrift/tree/master/lib/py) implementation to send requests via the python system tests. 

@axw any other suggestions are very welcome.

**Comment by axw** [comment]
> An alternative would be to record an http trift request from another library, e.g. go and then use the recorded event together with the python apache thrift implementation to send requests via the python system tests.

A simpler option would be to just send the pre-recorded with `requests`, similar to what we do for the standard intake API:

    requests.post(..., headers={"content-type": "application/vnd.apache.thrift.binary"})

It would be ideal to use a Jaeger client directly, but I think this reasonable would be reasonable to start with.

**Comment by simitt** [comment]
We can probably setup an end-to-end test including using a jaeger client to the [APM Integration Testing](https://github.com/elastic/apm-integration-testing/) repo, which is better suited for that any ways.
