### ISSUE TITLE
[Jaeger] How to support sampling

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3011]
When using probabilistic sampling Jaeger only sends sampled spans. Elastic APM UI currently requires a 100% of the transaction events. Elastic APM agent only sample spans.
Investigate how to solve sampling with Jaeger integration.

Part of elastic/apm-server#2886

UPDATE:
As probabilistic sampling support was added with elastic/apm-server#3487 this Issue now solely focuses on changes necessary to integrate Jaeger sampled traces into the APM app.

**Comment by jalvz** [comment]
Has there been any thought / discussion about this already?

**Comment by axw** [comment]
Copying this over from https://github.com/elastic/apm-server/issues/2886#issuecomment-558442620:

>> [concept]: When using probabilistic sampling jaeger only sends sampled spans. Elastic APM requires a 100% of the transaction events and only samples spans. Investigate how to solve sampling with jaeger integration.
>
> Outside of the context of Jaeger, there's been some discussion around relying on metrics so we don't need to send and store non-sampled transactions. This is elastic/apm#104.
>
> If we were to do that, we could have the server aggregate metrics based on sampled Jaeger trace data. Jaeger sends up the sampling rate in effect at the time a trace is captured, so we can scale the count/total based on that.

**Comment by simitt** [comment]
As part of this Issue #3487 was created to add a gRPC Jaeger sampling endpoint. This issue does not consider any changes related to how APM UI calculates transactions per minutes, etc.
