### ISSUE TITLE
Additional `destination` fields for spans (part 2)

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3025]
Add to Intake API for `spans`:

* `context.destination.service.resource`: `keyword`, optional 
*    context.destination.service.name: `keyword`, optional 
*    context.destination.service.type: `keyword`, optional 

Figure out where to put the information in ES.

Details in https://github.com/elastic/apm/issues/180

**Comment by jalvz** [comment]
Works as expected. (fields are in `span.destination.*`)
