### ISSUE TITLE
[7.6] APM Server should vendor go-elasticsearch client version 7.6

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3131]
APM Server now integrates with the official [go-elasticsearch](https://github.com/elastic/go-elasticsearch) client. To ensure the correct version of the client is used, @karmi and I discussed that a dedicated `7.6` branch of the `go-elasticsearch` client will be created in time, so the server can vendor this branch for the `7.6` release. 
Vendoring the `go-elasticsearch` 7.6 release is not possible, as the APM Server and the client will be released together.

**Comment by karmi** [comment]
I've created a [`7.6`](https://github.com/elastic/go-elasticsearch/tree/7.6) branch in the client repository. Can you have a look into vendoring that, @simitt, and let me know if all is OK?

**Comment by axw** [comment]
I wanted to verify this without looking at the source code. In the end I used tshark to sniff the traffic, and grepped the user-agent header. We are using the 7.6 branch, but its version is reported as 7.5-SNAPSHOT in user-agent headers.

**Comment by karmi** [comment]
Sorry about that — it was fixed in https://github.com/elastic/go-elasticsearch/commit/7550e30bc9546e055670c5136238b4350e6d6599.
