### ISSUE TITLE
Merge conflict text included in published docs

### ISSUE THREAD

**Issue by feenst** [elastic/apm-server#3168]
I searched around on GitHub for a bit, but I couldn't find the repo with the problematic text in it anywhere.

On [this page](https://www.elastic.co/guide/en/apm/get-started/current/agents.html):

![image](https://user-images.githubusercontent.com/997971/72373128-7f8e3880-36bc-11ea-9692-25956e6ac511.png)

**Comment by nik9000** [comment]
> I searched around on GitHub for a bit, but I couldn't find the repo with the problematic text in it anywhere.

I've moved this issue from the built-docs repo into the apm-server repo. I *think* that is the right spot.

**Comment by bmorelli25** [comment]
@feenst, thank you so much for reporting this! Looks like I made a mistake somewhere. Will fix this ASAP.

**Comment by bmorelli25** [comment]
Yup, I did this yesterday in https://github.com/elastic/apm-server/pull/3152/files#diff-48a49027b22f354fcd04b3c1bd6ed6f0R118-R123. Opening a fix. Thanks @nik9000 for sending this my way.

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/apm-server/pull/3169.
