### ISSUE TITLE
Run packaging tests on relevant prs

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#3181]
Per discussion, investigate:
* Always run them async?
* And/or trigger them with a comment?

**Comment by simitt** [comment]
@elastic/observablt-robots currently we do not run the `release` stage on PRs to `master`. This is unfortunate as breaking changes on beats updates are hidden until after we merge the PR. 

We brainstormed some ideas on how to improve the situation and would like to get your input on what's possible:
* always run the `release` stage but async in a similar manner as we do for `integration-tests`. If the PR does not contain any changes that could break the `release` stage we do not have to wait for it
* only run the `release` stage when certain files or directories are changed (`_beats` or `magefile.go`), but allow to additionally trigger the stage via a keyword. 

I slightly remember we have discussed this at some point, but couldn't find previous discussions.

**Comment by kuisathaverat** [comment]
Currently, you can launch the job manually for any PR and set the releaser_ci parameter to run only that stage, also if there are changes in the _beats folder this stage is launched

https://github.com/elastic/apm-server/blob/master/Jenkinsfile#L401
https://github.com/elastic/apm-server/blob/master/Jenkinsfile#L403
https://github.com/elastic/apm-server/blob/master/Jenkinsfile#L66-L76

if you want, we could add the trigger with a comment too.

**Comment by simitt** [comment]
Triggering the Release stage automatically when files within the `_beats` directory change sounds great. But that is not how it works at the moment, e.g. see https://github.com/elastic/apm-server/pull/3153. There have been plenty of changes within `_beats` but the `Release` stage was not built.

**Comment by kuisathaverat** [comment]
yep, something is not working that PR should trigger the pattern in https://github.com/elastic/apm-server/blob/master/Jenkinsfile#L66-L76, I will take a look.

**Comment by kuisathaverat** [comment]
The trigger on changes related to beats update is fixed, Do you need the comment trigger or is enough with the manual trigger from Jenkins?

**Comment by simitt** [comment]
I think this is good enough as is then. Thanks for the fix.
