### ISSUE TITLE
Enforce version labels on prs

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#3182]
To support missing backport detection.

- [ ] strategy for tagging PRs against master - `needs_backport` vs `no_backport`
- [ ] notify when backport has not been backported to 7.x (next release)
- [ ] tooling for identifying missing backports against any branch - perhaps https://github.com/sqren/didibackport

**Comment by axw** [comment]
This hasn't been a problem in recent history, let's reopen it later if needed.
