### ISSUE TITLE
[self instrumentation] instrument Elasticsearch clients

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3184]
Instrument the Elasticsearch clients using the Go agent's `module/apmelasticsearch`, so we can see how queries (e.g. for sourcemaps, and API Key auth) are performing.

We'll need to add context to the functions in the `apm-server/elasticsearch` package, and plumb context through from requests.

**Comment by graphaelli** [comment]
Pretty excited about this, though obv limited initially since it's not used for bulk ingestion.  This could enable:
* calc of distributiuon es query duration and rate
* calc of distribution of es query request and response sizes
* response status codes
* es comm error reporting
