### ISSUE TITLE
go-elasticsearch user-agent is invalid

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3213]
We're using the go-elasticsearch client 7.6 branch. Its version still says 7.5-SNAPSHOT: https://github.com/elastic/go-elasticsearch/blob/ed288cdc5128a5729c32b4f6aa5e30b09ebba294/internal/version/version.go#L9

https://github.com/elastic/go-elasticsearch/issues/125

**Comment by axw** [comment]
Found while testing https://github.com/elastic/apm-server/issues/3131

**Comment by graphaelli** [comment]
fixed upstream, looks like we need to vendor the update

**Comment by axw** [comment]
Closed by #3229

**Comment by axw** [comment]
Verified with BC3: `User-Agent: go-elasticsearch/7.6.0 (linux amd64; Go 1.13.6)`
