### ISSUE TITLE
APM-Server RUM-JS for React and Redux does not work.

### ISSUE THREAD

**Issue by Nadhu18** [elastic/apm-server#3231]
Hi,
When we are trying to use ApmRoute and withTransaction() in React Framework, the page re-renders and we are getting the maximum call stack error. Can you please help me with this?

Thanks in advance.

**Comment by axw** [comment]
Hello! Issues are meant for bugs and feature requests, and this isn't directly related to APM Server, so I'm closing the issue. 

Please open a new topic at https://discuss.elastic.co/c/apm, and hopefully someone can point you in the right direction.
