### ISSUE TITLE
Decrease API Key cache time to 1 minute

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3237]
Decrease cache time to one minute to avoid caching of potentially expired keys for up to 5 minutes. 

Also found a related issue while testing https://github.com/elastic/apm-server/issues/3215:
The cache size is calculated by multiplying the limit times the cache duration, https://github.com/elastic/apm-server/blob/master/beater/authorization/builder.go#L64: `cfg.APIKeyConfig.LimitMin * cacheTimeoutMinute`

By using this calculation, the _average_ limit per minute over time is identical to the configured limit, but it can be uneven distributed, e.g. allowing 5*limit in the first minute and then no new keys in the next 4 minutes until the cache time expires. This might be confusing to users and behavior gets more clear when decreasing the cache time to 1 minute.

**Comment by axw** [comment]
Verified with BC3:

1. Create API Key
2. `watch 'curl -XPOST -H "Content-Type: application/x-ndjson" -H "Authorization: ApiKey <api-key>" http://localhost:8200/intake/v2/events'`
3. Invalidate API Key (immediately after first server response, which should be an "EOF while reading metadata" error, implying the request passed auth)
4. Wait for 1 minute, observe that requests start failing with "unauthorized"
