### ISSUE TITLE
[docs] Document required privileges for agent configuration

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3261]
The APM app in Kibana provides a server route for the Kibana frontend and APM Server to query and update agent config. In order to access the endpoint, it is necessary to have access to the "APM" feature under Kibana space privileges:

![image](https://user-images.githubusercontent.com/843579/73423732-eface780-4367-11ea-91b1-e5cb16458230.png)

I think we should update the APM Server docs, defining the required privileges. Perhaps update https://www.elastic.co/guide/en/apm/server/current/feature-roles.html, with a pointer from https://www.elastic.co/guide/en/apm/server/current/setup-kibana-endpoint.html#_apm_server_kibana_username.

**Comment by bmorelli25** [comment]
This was updated in https://github.com/elastic/apm-server/pull/3799 and https://github.com/elastic/kibana/pull/67401.

Documentation links:

* [Grant privileges and roles needed for APM Agent central configuration](https://www.elastic.co/guide/en/apm/server/current/privileges-agent-central-config.html)
* [APM app central config user](https://www.elastic.co/guide/en/kibana/current/apm-app-central-config-user.html)
