### ISSUE TITLE
move capture_personal_data under rum configuration

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#3273]
move `apm-server.capture_personal_data` to `apm-server.rum.capture_personal_data`.  I propose:

* deprecate immediately (7.x)
* keep deprecated in 8.x
* remove in 9.0

If both are set, use `apm-server.rum.capture_personal_data`

**Comment by simitt** [comment]
The `capture_personal_data` configuration also concerns backend events, therefore we are not moving the config to the `rum` focused section. Closing this issue.
