### ISSUE TITLE
[docs] Add information on node attributes for hot-warm clusters

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#3302]
For setups utilizing hot-warm architecture, we should document how to add the proper node attributes to ensure warm-phase data moves to warm nodes.

More feedback in https://github.com/elastic/apm-server/issues/3287.

**Comment by axw** [comment]
From 7.10 onwards ILM will automatically inject a [migrate](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/ilm-migrate.html#ilm-migrate) action into the default ILM policy, which will move data to warm/cold data tiers in the relevant phases.

There's nothing APM-specific about data tiers (https://www.elastic.co/guide/en/elasticsearch/reference/7.10/data-tiers.html), so I think we can close this. Feel free to reopen if you disagree.
