### ISSUE TITLE
Move "system" tests to Go

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3318]
Explore the Docker API, https://github.com/testcontainers/testcontainers-go, or a similar library to write integration/system tests in Go, and gradually move existing Python tests.

Now is a good time for this, since Python 2 just reached its End Of Life.

**Comment by bsideup** [comment]
Just out of curiosity:

Why not testcontainers-java, the most feature complete solution out there? :)

Although I should mention that testcontainers-go is well developed and they try to catch up feature wise with the Java version :)

**Comment by axw** [comment]
@bsideup the primary reason is that this project is written in Go. We're trying to simplify things. The main change we're discussing here is removing our dependency on Python, and consolidating on Go.

**Comment by axw** [comment]
Not completely migrated, but we'll tackle them one by one over time. New system tests will be written in Go.
