### ISSUE TITLE
Ensure Elasticsearch client compatibility between major versions

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3321]
Specifically, APM Server 8.0 should work with the latest minor of Elasticsearch 7.

This could be achieved for instance by querying the Elasticsearch version at startup and then returning the appropriate version from `NewClient`

**Comment by simitt** [comment]
Isn't that a duplicate issue of https://github.com/elastic/apm-server/issues/2975?

**Comment by jalvz** [comment]
Oh yeah, I couldn't find it - thanks
