### ISSUE TITLE
APM Server Telemetry

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3334]
Investigate how can we start reporting Telemetry metrics, and which metrics would be interesting for us to report.

Libbeat gives support through the `monitoring` package:
https://github.com/elastic/beats/blob/master/libbeat/publisher/pipeline/module.go#L42
 
We want a registry in the `state` namespace, and then use it eg. like:
`monitors.NewString(telemetry, "key").Set("value")`

**Comment by jalvz** [comment]
Maybe for inspiration: https://github.com/elastic/kibana/issues/50757

**Comment by graphaelli** [comment]
next step is to come up with list of telemetry that we need to track

**Comment by jalvz** [comment]
Initial proposal:

- How many are using custom pipelines
`register.ingest.pipeline.overwrite`

- How many are using API keys
`api_key.enabled`

- How many are using RUM (although I think is possible to track this already?):
`rum.enabled`

- How many are potentially using remove config 
`kibana.enabled`

- How many are using custom ILM policies
`ilm.setup.overwrite`

- How many are configuring custom ILM policies from apm-server
`ilm.setup.require_policy`

- How many are using Jaeger/GRPC
`jaeger.grpc.enabled`

- How many are using Jaeger/HTTP
`jaeger.http.enabled`

- How many are tuning for performance
`queue.mem.events != 4096`
`queue.mem.flush.min_events != 2048`

- How many are using custom templates
`setup.template.overwrite`

- How many are using the Elasticsearch output
`output.elasticsearch.enabled`

- How many are using the Logstash output
`output.logstash.enabled`

- How many are using the Kafka output
`output.kafka.enabled`

**Comment by axw** [comment]
> queue.mem.events != 4096
> queue.mem.flush.min_events != 2048

Any reason why we should not just record the values?

I would also add `ilm.enabled`

**Comment by axw** [comment]
Sample "state" monitoring doc, based on existing libbeat monitoring:

```json
          "timestamp" : "2020-06-26T07:50:16.744Z",
          "type" : "beats_state",
          "beats_state" : {
            "beat" : {
              "type" : "apm-server",
              "version" : "8.0.0",
              "name" : "goat",
              "host" : "goat",
              "uuid" : "0ddccead-2600-47c2-b488-9704600e82bb"
            },
            "state" : {
              "host" : {
                "architecture" : "x86_64",
                "os" : {
                  "kernel" : "5.4.0-28-generic",
                  "codename" : "focal",
                  "platform" : "ubuntu",
                  "version" : "20.04 LTS (Focal Fossa)",
                  "family" : "debian",
                  "name" : "Ubuntu"
                },
                "id" : "6390f2c0fff84b63a1a1815024bff218",
                "containerized" : "containerized",
                "hostname" : "goat"
              },
              "outputs" : {
                "elasticsearch" : {
                  "cluster_uuid" : "a1fQDI4ETQSnMguQSxUN3w"
                }
              },
              "management" : {
                "enabled" : false
              },
              "queue" : {
                "name" : "mem"
              },
              "output" : {
                "name" : "elasticsearch"
              },
              "service" : {
                "name" : "apm-server",
                "id" : "0ddccead-2600-47c2-b488-9704600e82bb",
                "version" : "8.0.0"
              },
              "beat" : {
                "name" : "goat"
              }
            },
            "timestamp" : "2020-06-26T07:50:16.744Z"
          },
          "interval_ms" : 10000,
          "cluster_uuid" : "a1fQDI4ETQSnMguQSxUN3w"
```

Since the output name is already in there (`output.name`), I don't think we need to add `output.elasticsearch.enabled` etc. I feel like it would be useful to enhance libbeat to add the elasticsearch cluster version under `outputs.elasticsearch`, so we have an idea of how many people are using APM Server with older or newer versions of ES. Likewise for Kibana.

**Comment by graphaelli** [comment]
Kibana and es version info are a great idea.
