### ISSUE TITLE
Process additional Jaeger Span `logs` 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3338]
At the moment only `error` logs are processed and transformed into Elastic APM error events. Record additional Span Logs according to the [OpenTracing spec](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#log-fields-table).

Pick up previous discussion about investigating if it makes sense to introduce a dedicated Elastic APM convention for extended support.

**Comment by graphaelli** [comment]
Linking to #3723.  I had thought these would turn into transaction marks originally but generalizing them to actual logs would make them even more useful.

**Comment by Dmitry31** [comment]
Any future for this feature? There is no clear statement in the documentation about OpenTracing and OpenTelemetry support. Looking around on github I feel like Jaeger support is no more a priority as OpenTracing merged into OpenTelemetry ... But OpenTelemetry logs specs are in experimental state so no support neither?

**Comment by axw** [comment]
@Dmitry31 Jaeger span logs are equivalent to OpenTelemetry span events, so when we get to https://github.com/elastic/apm-server/issues/4715 we will be able to address this too.
