### ISSUE TITLE
Add support for Jaeger auth handling

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3339]
The APM Server Jaeger gRPC endpoint supports TLS. If apm-server.ssl is configured, the settings are automatically applied to the APM Server's Jaeger gRPC endpoint. The implemented HTTP endpoint does not support TLS or using a secret token for now. 

Investigate possibilities and limitations for supporting auth handling for Jaeger spans. 

Considerations from [issue#2886](https://github.com/elastic/apm-server/issues/2886#issue-519237545):
> One thing that is yet to be solved is auth. A limited subset of the Jaeger clients (Java and C#) support the JAEGER_AUTH_TOKEN config, which can be used to send a bearer token along with requests to the collector. This only works when using HTTP. The Jaeger agent only supports client certificate auth. We do support this, but it might also be worth a lighter-weight option, such as ferrying a secret/bearer token through tags, using the --jaeger.tags CLI flag.

**Comment by graphaelli** [comment]
Helpful for cloud deployment, when ready.
