### ISSUE TITLE
Jaeger integration part 2

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3340]
Since elastic/apm-server#2886 the APM Server can act as a basic Jaeger collector, allowing to receive and process Jaeger spans. As listed in the issue and in the docs it is an experimental feature.

In a next step the integration should be extended and remove some of the current caveats: 

**Add/Improve Logic:**

* [Auth handling](https://github.com/elastic/apm-server/issues/3339)
* [Support Sampling ](https://github.com/elastic/apm-server/issues/3011)
* [Record additional Span Logs](https://github.com/elastic/apm-server/issues/3338)

**End-to-end Testing:**

*  Add automated tests to CI, creating a test app instrumented by a jaeger agent sending data in expected format to ES (elastic/apm-integration-testing#679)
*  Add automated tests to CI, creating a test app using the jaeger client sending data via thrift over http to the APM Server and ingesting in expected format to ES (elastic/apm-integration-testing#680)

**Comment by axw** [comment]
Moving to backlog until we have logs/events support, there's a separate issue for sampling.

**Comment by axw** [comment]
Closing this since we have support for sampling and auth now, and issues for the remaining things.
