### ISSUE TITLE
apm-server 7.6.0 can`t start, again. 

### ISSUE THREAD

**Issue by DeveloperMos** [elastic/apm-server#3392]
https://github.com/elastic/apm-server/issues/2496#issuecomment-546514806
[Problem](https://github.com/elastic/apm-server/issues/2496#issuecomment-546514806)

### If these actions are related
Often restarted the service. About 30 times.
Аfter so many restarts, the service broke down.

launch with flag -е, ok.
If deleting user and group apm-server in apm-server.service, service work.

### OS 
Debian buster
### All stack 
7.6.0 v.

**Comment by graphaelli** [comment]
Sorry to hear you're having trouble but we use GitHub for verified bug reports, feature requests, and pull requests. There's an active community in the [forum](https://discuss.elastic.co/c/apm) that should be able to help get an answer to your question.
