### ISSUE TITLE
[RUM v3] Optimize fields

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3404]
This includes:
- Derive `parent_id`, `trace_id` and `transaction_id` in the `span` from its `transaction`
- Make required booleans optional, defining absence as `false` ( `sync`)

- ~~Make `start` and `duration` int~~.
- ~~Remove unneeded fields: `transaction.marks.navigationTiming`, `http.url`~~

**Comment by axw** [comment]
> Make start and duration int.

They're currently "number", which allows the agent to send an integer as well as a float. What's the reason for making the schema stricter?

**Comment by jalvz** [comment]
> They're currently "number", which allows the agent to send an integer

Good point, I haven't noticed. 
But while looking at how to implement this, I changed my mind about the approach: it's probably simpler for us that the agent embeds the spans inside their transactions.

There is no easy way that we can take fields out of a transaction decoder and pass them as arguments to the spans decoder.

I think we would need an specific `HandlerRawModel` for this, or a flag inside the processor, and it would break the uniformity of the work flow (decoder signatures, etc).

wdyt?

**Comment by axw** [comment]
If the RUM agent will always have spans within transactions, then I think we wouldn't need or want a separate span decoder. The RUM transaction decoder would return a Transformable which internally combines info from the transaction and embedded span objects to produce the transaction and span docs.

**Comment by jalvz** [comment]
All boolean fields are optional, so they can default to false when missing.

I think that with https://github.com/elastic/apm-server/pull/3659 this can be closed.
