### ISSUE TITLE
Rejecting mapping update as the final mapping would have more than 1 type

### ISSUE THREAD

**Issue by Abmun** [elastic/apm-server#3410]
As the data is from 2018, it is not getting indexed to ES 7xx. Is there any plan to update apm data?

Thanks!

**Comment by axw** [comment]
I'm afraid I don't understand your question. We use GitHub for verified bug reports, feature requests, and pull requests. There's an active community in the [Discuss forum](https://discuss.elastic.co/c/apm) where you may find someone able to answer to your question.
