### ISSUE TITLE
Missing mage fmt target

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3415]
A CI error might report something like "Error: some files are not up-to-date. Run 'mage fmt update' then review and commit the changes. Modified: [docs/data/elasticsearch/generated/errors.json]"

However, locally `mage fmt update` returns "Unknown target specified: fmt"

**Comment by axw** [comment]
In the mean time, `make fmt` still works.

**Comment by jalvz** [comment]
Yeah, I don't think this is new.
