### ISSUE TITLE
Update APM server code for breaking changes in libbeat API (transport)

### ISSUE THREAD

**Issue by ycombinator** [elastic/apm-server#3416]
We're undertaking some refactoring/cleanup in the libbeat codebase. One part of this is done by this PR: https://github.com/elastic/beats/pull/16734. 

Please see the "Developer Docs" section in the PR description for how it might impact APM server code. From my snooping around, it looks like the following locations might be impacted:

- https://github.com/elastic/apm-server/blob/a3a2ff36752368d4fff7c63911a9b427f435d4a0/vendor/vendor.json#L1258
- https://github.com/elastic/apm-server/blob/a3a2ff36752368d4fff7c63911a9b427f435d4a0/vendor/vendor.json#L1250
- https://github.com/elastic/apm-server/blob/28268169317376004da3191ca02a448e72a9d498/Makefile#L187
- https://github.com/elastic/apm-server/blob/e36b645628a7eef612730e20c921dd30df647d78/elasticsearch/config.go#L30

**Comment by graphaelli** [comment]
Thanks for the heads up / opening this!

**Comment by ycombinator** [comment]
Further heads up: we're about to merge elastic/beats#16734. It should happen some time today.
