### ISSUE TITLE
Update APM server code for breaking changes in libbeat API (ES client)

### ISSUE THREAD

**Issue by ycombinator** [elastic/apm-server#3433]
We're undertaking some major refactoring/cleanup in the libbeat codebase, specifically in the Elasticsearch output package. The PR for this is https://github.com/elastic/beats/pull/16150. 

Please see the "Developer Docs" section in the PR description for how it might impact APM server code. From my snooping around, it looks like the following locations might be impacted:

- https://github.com/elastic/apm-server/blob/72c446d4cb7904ec27198a887f09d6f7764aad2a/beater/beater.go#L210
- https://github.com/elastic/apm-server/blob/72c446d4cb7904ec27198a887f09d6f7764aad2a/beater/beater.go#L217
- https://github.com/elastic/apm-server/blob/eaaf95ccb608ad84ce77ec894322ddf43a5da5f8/_beats/libbeat/scripts/cmd/stress_pipeline/main.go#L32
- https://github.com/elastic/apm-server/blob/6ef930506cd8ac3b08706ffa53a09105178d84c8/elasticsearch/config_test.go#L102-L105 
- https://github.com/elastic/apm-server/blob/3732dad722a7b76915f4cdcfca647638f859ff62/ingest/pipeline/register.go#L31
- https://github.com/elastic/apm-server/blob/3732dad722a7b76915f4cdcfca647638f859ff62/ingest/pipeline/register_test.go#L34
- https://github.com/elastic/apm-server/blob/3732dad722a7b76915f4cdcfca647638f859ff62/ingest/pipeline/register_test.go#L52

**Comment by axw** [comment]
Assigning myself, since this is going to get tangled up with go-modules migration.

**Comment by ycombinator** [comment]
@axw you might want to be aware of https://github.com/elastic/apm-server/issues/3416 as well — these two are related.

**Comment by axw** [comment]
:+1: thanks @ycombinator
