### ISSUE TITLE
Identify parts of the code that trigger specific build steps in the CI

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-server#3437]
We'd like to start a discussion about triggering certain build steps based on certain conditions. As an example, we could run the benchmarks if and only if the files or directories A, B or C are modified by a PR. Therefore we would run the benchmarks for that PR.

Same for tests: if we have a project layout that takes different separation of concerns and is able to separate their tests too, it would be possible to run those tests in isolation: i.e, run systems tests for module X.

cc/ @elastic/observablt-robots

**Comment by cachedout** [comment]
We could use `when` and `changeset` directives to do this pretty easily, I think.

**Comment by kuisathaverat** [comment]
We have implemented something is several projects, the most recent is Beats, the pipeline run stages based on the file changes, so if you changed Metricbeat only you will run the CI for Metricbeat, is you modified libbeat you would run whole stages because your change affects all Beats.

The pipeline checks the changes between two commits and apply regexp to select stages to build.
https://github.com/elastic/beats/blob/master/Jenkinsfile#L650-L716

The APM server has something implemented to run the beats-update stage https://github.com/elastic/apm-server/blob/master/Jenkinsfile#L65-L76

**Comment by axw** [comment]
@kuisathaverat we're going to have to change that BEATS_UPDATED bit soon, as we will soon no longer be vendoring. Would it be difficult to change it to grep for changes in the diff? i.e. look to see if any lines in `go.mod` containing "beats" changed.

**Comment by graphaelli** [comment]
What do we need to do to satisfy this issue?

**Comment by kuisathaverat** [comment]
>@kuisathaverat we're going to have to change that BEATS_UPDATED bit soon, as we will soon no longer be vendoring. Would it be difficult to change it to grep for changes in the diff? i.e. look to see if any lines in go.mod containing "beats" changed.

It is the same check plus check the difference for changes on beats something. If the go.mod file does not change too much, I think that check for go.mod changes is enough. Also if you change dependencies it is good to run the package stage

**Comment by kuisathaverat** [comment]
>What do we need to do to satisfy this issue?

This is out current pipeline, we have a couple of condition to run or not the stages. On changes only on docs no stage is build, and on changes in the beats library the release stage is run. Also, the release stage is executed on branch merges. Finally, you can run the Hey APM test with a GitHub comment.

<img width="856" alt="Screenshot 2020-04-01 at 10 12 32" src="https://user-images.githubusercontent.com/5400788/78114293-5484cc80-7401-11ea-9356-c9f33fba9508.png">

So, from this pipeline what is not in the critical path and we want to move to changes based execution.

**Comment by axw** [comment]
This issue appears moribund, so I'm closing. Please reopen if it's still relevant.
