### ISSUE TITLE
Avoid requesting certification on the RUM endpoint

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#3442]
When the `client_authentication` is set to `optional` (the default value) the APM server seems to request client certification on all endpoints. When the request is made from the RUM agent, requesting a certification would result in the browser to prompt the user to choose a certification to present to the server. The request still succeeds if the user cancels this prompt, since presenting certification is optional, but if the user chooses an invalid certification the request would fail.

I propose to avoid requesting certification on the RUM endpoint when `client_authentication` is set to `optional`.

**Comment by simitt** [comment]
I can confirm that the server sends a certificate request when `ssl.client_authentication: optional`. If no certificate is presented, it doesn't lead to an error though.

**Comment by simitt** [comment]
The `golang` implementation does request a client certificate when `ClientAuth >= RequestClientCert`, see [crypto/tls/handshake_server.go](https://github.com/golang/go/blob/master/src/crypto/tls/handshake_server.go#L486) (same for the TLS 1.3 implementation).

Valid options for `ClientAuth` are: 
	* `NoClientCert`
	* `RequestClientCert`
	* `RequireAnyClientCert`
	* `VerifyClientCertIfGiven`
	* `RequireAndVerifyClientCert`

If setting the server config to `NoClientCert` a provided certificate would never be verified, this is the behavior when configuring `apm-server.ssl.client_authentication: "none"`. This is not an option for `apm-server.ssl.client_authentication: "optional"`, as given certs need to be verified.

We could switch the default configuration to `apm-server.ssl.client_authentication: "none"`. As I see this as a breaking change, I suggest to change in 8.0 and document this caveat for the RUM agent until then.

**Comment by wolframhaussig** [comment]
Why not use the option `VerifyClientCertIfGiven` you mentioned? Don't ask for a certificate as it is optional but verify it if it is given?

**Comment by simitt** [comment]
That's actually what happens: `apm-server.ssl.client_authenticaion: "optional"` is translated to `VerifyClientCertIfGiven`. As linked above, a client certificate is requested though for every option except for `NoClientCert`
```
if c.config.ClientAuth >= RequestClientCert {
    // Request a client certificate
    ...
}
```

**Comment by simitt** [comment]
Tested with Firefox and Chrome and could only observe Chrome to print for a certificate. There is no change in behavior testing for `7.6` and `6.8`.

**Comment by wolframhaussig** [comment]
@simitt  What can I do to help? We have our production system on APM server 6.8 and our testsystem on 7.6. Our P-system was not affected, our Q-System was affected until changing the client_authentication setting

**Comment by simitt** [comment]
@wolframhaussig can you ensure that the setup for P and Q is the same, basically that in both cases no certificate is configured in the browser and that no proxy interrupts the request, etc. that could explain the change in behavior? 
When querying the APM Server version `6.8` from a browser that has no client certificate configured I see the same prompt, same behavior as when querying a `7.6` server (with Chrome).

**Comment by wolframhaussig** [comment]
I use the same browser to access both applications. We have smartCards to login into some of the web applications using Chrome - so Chrome might be aware that there exists a certificate even when the smartcard is not connected.

**Comment by joshbressers** [comment]
I think changing the default behaviour to "none" makes sense. Any time a user has to interact with a security prompt containing multiple choices they inevitably make the wrong choice.

Right now with the certificate as optional it doesn't prevent anyone from writing anything into the server, changing the default to "none" shouldn't change any existing security protection.

I would expect users who want to use certificates will require them rather than set them as optional.

**Comment by jahtalab** [comment]
@axw @simitt , I've tested with the build candidate, the issue is resolved with the default configuration. I can confirm that changing the `client_authentication` back to `optional` or `required` produces the effect explained in this issue.

Incidentally, now that we are considering possible values for `client_authentication`, what is the use-case for having `optional` value?

**Comment by axw** [comment]
Thanks @jahtalab!

> Incidentally, now that we are considering possible values for client_authentication, what is the use-case for having optional value?

I'm not aware of us having any use-cases -- it's just a common configuration type provided by libbeat.

Hypothetically we could make use of `optional` as an alternative, optional auth mechanism. For unauthenticated clients (no client cert provided), we would treat the client the same as we to today: allowed for RUM and the root handler, but rate-limited.

**Comment by simitt** [comment]
I think https://github.com/elastic/apm-server/issues/3442#issuecomment-600628214 summarized well that there is no obvious usecase for it. 
One somewhat constructed usecase that comes to my mind is an upgrade process, where  agents are upgraded to sending a client certificate, but not all are upgraded at the same time. Choosing `optional` would allow for early feedback on potential misconfiguration, while still allowing other agents to connect without certificate.
