### ISSUE TITLE
docs: mention TLSv1.3 in supported_protocols

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3453]
https://www.elastic.co/guide/en/apm/server/current/agent-server-ssl.html#_supported_protocols_2 say the default TLS supported_protocols are `[TLSv1.1, TLSv1.2]`, and makes no mention of TLSv1.3 at all. This changed in 7.6.0: we now support TLSv1.3, and it is one of the defaults.

**Comment by axw** [comment]
See #3452 for why this matters

**Comment by graphaelli** [comment]
and configuration file

**Comment by simitt** [comment]
Assigning this to myself as it also involves some test changes.
