### ISSUE TITLE
Promote API Key auth to GA

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#3461]
Required for GA:
- [x] Introduce metadata identifying APM-related API Keys https://github.com/elastic/apm-server/pull/5090
- [x] Remove experimental label from docs https://github.com/elastic/apm-server/pull/5091
- [x] Enable API Key auth by default in Cloud

Out of scope for GA:
- elastic/kibana#77966 (can come later)

**Comment by simitt** [comment]
Depends on https://github.com/elastic/kibana/issues/77966
