### ISSUE TITLE
Agent config management verify configured user has required privileges

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3478]
Verify whether the configured Kibana user has the necessary privileges to query the Agent configurations by calling the `has_privilege` API in Kibana. If the configured user doesn't have access provide error message to the requester accordingly. 

This would be a nice improvement to help users track down issues with Agent config management more easily. 

Thanks @sqren for the request.

**Comment by graphaelli** [comment]
Verify whether the permission denied is relayed back to the agent or only logged by apm-server.

Consider checking application access on connection to kibana.

**Comment by axw** [comment]
Now that we've got a Fleet-based implementation of agent config, let's close this instead of investing more effort and time on the old way.
