### ISSUE TITLE
Support `ilm.pattern` option in APM Server

### ISSUE THREAD

**Issue by sw-jung** [elastic/apm-server#3482]
When I want to use a custom ILM pattern such as `my_index-{now/d}-000001`, I can use [`setup.ilm.pattern`](https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html#setup-ilm-pattern-option) option for it in Beats but APM Server doesn't support that option yet.

Custom ILM pattern or ILM pattern with date math support will be useful to manage indices.

**Comment by graphaelli** [comment]
We don't currently have plans to implement this, thanks for reporting.

**Comment by axw** [comment]
We are moving towards using data streams (part of https://github.com/elastic/apm-server/issues/4004), so I don't think this will ever be implemented. Closing for now.
