### ISSUE TITLE
[Jaeger] Add gRPC Sampling endpoint

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3487]
As part of elastic/apm-server#3011 add the gRPC Jaeger sampling endpoint to the APM Server acting as Jaeger collector. 

The endpoint will only support probabilistic sampling and should fetch the sampling rates from Kibana's agent configuration management. 

By default the Jaeger sampling rate should be set to 100%. 

Sampling in Jaeger tracing behaves different than Elastic APM sampling. Elastic APM currently always records 100% of transactions to allow a correct calculation of _Requests per minute_. Jaeger tracing only samples the configured percentage of transactions and spans, as there is no dedicated concept of transactions. If users configure a sampling rate smaller than 1, it will lead to incorrect values in the APM UI. We need to ensure this caveat is documented (cc @bmorelli25 ). 

Why do we want to support sampling given this caveat?
Without the support of the sampling endpoint users that rely on sampling are excluding from using the Jaeger integration. With this change they can not depend on the _Requests per Minute_ visualization, but can still make use of other Elastic APM features.

**Comment by bmorelli25** [comment]
Thank you for the detailed write-up Silvia! Hope it's not too soon -- I've added documentation for this in https://github.com/elastic/apm-server/pull/3493.
