### ISSUE TITLE
[docs] Clarify client certificate related TLS config options

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3494]
There are two server side TLS configuration options related to verifying client certificates:
* `apm-server.ssl.certificate_authorities`
* `apm-server.ssl.client_authentication`   

We've seen some confusion around these configuration options. As requested by @beniwohli 
these options should be moved to a dedicated section, where it becomes clear that they should only be customized when the agent provides a client certificate. None of the backend agents currently supports this. This is only useful for the RUM agent, when a client certificate is configured to be presented in the browser.

**Comment by beniwohli** [comment]
See also https://github.com/elastic/apm-agent-python/issues/758

**Comment by simitt** [comment]
Update: the option can also be used by Jaeger agents.
