### ISSUE TITLE
client_authentication is not working as described in reference

### ISSUE THREAD

**Issue by insukcho** [elastic/apm-server#3498]
I'm trying to set up a self-managed Elastic APM Server in my machine for the test.

When we check the reference [here](https://www.elastic.co/guide/en/apm/server/current/agent-server-ssl.html#_client_authentication), we can see below comments.

**client_authentication**
_This configures what types of client authentication are supported. The valid options are none, optional, and required. The default is optional. If certificate_authorities has been specified, this setting will automatically change to required._
- none - Disables client authentication.
- optional - When a client certificate is given, the server will verify it.
- required - Requires clients to provide a valid certificate.

So, if a client certificate is given, `optional` and `required` should be working as same, right?

But when I send data from APM Python Agent (Django/Flask), APM Java Agent on Tomcat, only `optional` was working but `required` give me `TLS handshake error` like below.
```
http: TLS handshake error from 127.0.0.1:54321: remote error: tls: unsupported extension
```

You can reproduce this with below steps.

1) Create self-assigned certificates (PEM format) with [elasticsearch-certutil](https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html#certutil)
```
$ vi ./instance.yml
instances:
  - name: 'client'
    dns: [ 'localhost' ]

$  bin/elasticsearch-certutil cert ca --pem --in ./instance.yml --out ./certs.zip
```

2) Unzip ./certs.zip file and use copy and paste under APM Server home directory. Put SSL configuration in apm-server.yml like below.
```
apm-server.ssl.enabled: true
apm-server.ssl.key: "./certs/client/client.key"
apm-server.ssl.certificate: "./certs/client/client.crt"
apm-server.ssl.certificate_authorities: ['./certs/ca/ca.crt']
apm-server.ssl.secret_token: ${SECRET_TOKEN}
 
# Currently, this setup is required. If not setting up, it will fail for SSL hand shaking.
apm-server.ssl.client_authentication: 'optional'
 
# For Java Agents, we need to limit supported protocol to avoid using TLSv1.3
supported_protocols: [TLSv1.1, TLSv1.2]
```

3) Copied same certificates to each Agent's home directory. and change configuration like below.
- Java Agent on Tomcat
Need to change CA certificate to DER, and then store it in JKS(Java KeyStore). Set it up in `$TOMCAT_HOME/bin/setenv.sh`
```
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:elastic-apm-agent-1.11.0.jar"
export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.service_name=tomcat-hello-world"
export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.server_urls=https://localhost:8200"
export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.secret_token=<YOUR_SECRET_TOKEN_OF_APM_SERVER>"
export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.application_packages=mypackage"
export CATALINA_OPTS="$CATALINA_OPTS -Djavax.net.ssl.trustStore=$CATALINA_HOME/certs/ca/ca.jks"
export CATALINA_OPTS="$CATALINA_OPTS -Djavax.net.ssl.trustStorePassword=<YOUR_PASSWORD_OF_JKS>"
```

- Python Agent on Django
```
ELASTIC_APM = {
  'DEBUG': True,
  'SERVICE_NAME': 'amazing_django_service',
  'SECRET_TOKEN': '<YOUR_SECRET_TOKEN_OF_APM_SERVER>',
  'SERVER_URL': 'https://127.0.0.1:8200',
  'SERVER_CERT': './certs/client/client.crt',
}
```

- Python Agent on Flask
```
app.config['ELASTIC_APM'] = {
  'DEBUG': True,
  'SERVICE_NAME': 'flask-hello-service',
  'SECRET_TOKEN': '<YOUR_SECRET_TOKEN_OF_APM_SERVER>',
  'SERVER_URL': 'https://localhost:8200',
  'SERVER_CERT': './certs/client/client.crt',
}
```

I have checked all 3 agents are sending data to APM Server properly. 
However, when I changed `client_authentication` from `optional` to `required` like below.
```
apm-server.ssl.client_authentication: 'required'
```

Server will print error logs like below and agents couldn't send data to APM Server.
```
2020/03/18 12:10:02 http: TLS handshake error from 127.0.0.1:51768: remote error: tls: unknown certificate
2020/03/18 12:10:02 http: TLS handshake error from 127.0.0.1:51769: remote error: tls: unknown certificate
2020/03/18 12:10:02 http: TLS handshake error from 127.0.0.1:51770: remote error: tls: unknown certificate
2020/03/18 12:10:32 http: TLS handshake error from 127.0.0.1:51774: remote error: tls: unknown certificate
```

I expect it should be working as documentation said but I'm not sure I didn't miss anything for this whole setup. Could you please check it up?

**Comment by insukcho** [comment]
Just for your information, I put some comments on documentation improvements here: https://github.com/elastic/apm-server/issues/3198#issuecomment-600500768

When I setup `certificate_authorities` with my CA certificate,  `client_authentication`  automatically changed to `required` and I kept failing even sending right client side certificates. It was very easy to miss [those comments](https://www.elastic.co/guide/en/apm/server/current/agent-server-ssl.html#_client_authentication) that are not in apm-server.yml statements.

**Comment by beniwohli** [comment]
@insukcho none of the backend agents currently support client certificates. Documenting this should be addressed in https://github.com/elastic/apm-server/issues/3494

**Comment by insukcho** [comment]
> none of the backend agents currently support client certificates.

@beniwohli What does it mean exactly? Could you please give me clarification about below questions?

- `backend agents` means all APM Agents except RUM Agent, right?
- Does it mean we cannot setup client certificates from Agent side?
- If yes, what does [this reference](https://www.elastic.co/guide/en/apm/server/current/agent-server-ssl.html#_client_authentication) mean about `The client certificate is given`?

**Comment by beniwohli** [comment]
Yes, only the RUM agent supports client certificates, due to the fact that most browsers support it (the RUM agent itself doesn't have specific support for client certificates, it just piggybacks on the browser support).

As I mentioned in our discussion on Slack, client certificates are a very niche authentication method. AFAIK, we never had requests to support it in backend agents. The main problem here is that the documentation doesn't make it very clear that most people don't need to set it up even for RUM.

**Comment by simitt** [comment]
As @beniwohli pointed out the backend agents do not support sending client certificates. Documentation changes in https://github.com/elastic/apm-server/pull/3500 should clarify this config option.

**Comment by insukcho** [comment]
@beniwohli @simitt Thanks for the reply. 

Can I just get the last clarification about the exact purpose of [server_cert](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-server-cert) from APM Python Agent while none of the backend agents currently support client certificates?

**Comment by axw** [comment]
@insukcho `server_cert` is for authenticating the server, and unrelated to client certificates.

- Client certificates are used for authenticating clients (i.e. APM Agents)
- Server certificates are used for authenticating servers (i.e. the APM Server)

Client certificate authentication works like this:
 - Agents are configured with a client certificate/key pair
 - Server is configured with one or more certificate authority (CA) certificates, used to sign the client certificates. The server will reject any clients with invalid client certificates, depending on the server configuration (client_authentication, certificate_authorities)

Server certificate authentication goes the other way:
 - Server is configured with a certificate/key pair
 - Agents are configured (via `server_cert`) with the server's certificate, which enables them to verify the server's identity by checking the certificate that the server is using matches the one that the agent knows about. If the server starts using a different certificate, agents would abort connection. This is known as certificate pinning.

**Comment by insukcho** [comment]
@axw Thank you very much for the clarification!!
