### ISSUE TITLE
Update generate_notice.py to use go-licence-detector

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3516]
The generate_notice.py script could be used by other Go projects - we should consider pulling it out into a separate repo to facilitate that.

I think we should also consider rewriting it in Go to remove the Python dependency (Go is naturally required). If we did that, it might make sense to contribute it to https://github.com/elastic/go-licenser.

**Comment by simitt** [comment]
Also see https://github.com/elastic/cloud-on-k8s/tree/master/hack/licence-detector

**Comment by axw** [comment]
I'm looking into migrating to go-licence-detector now. `generate_notice.py` is having some issues with the latest beats master, and it doesn't make sense to keep maintaining it.

**Comment by axw** [comment]
Reopening this while we work on fixing the PR, which broke release manager.
