### ISSUE TITLE
Add script verifying libbeat dependency can be upgraded

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3536]
In the past we had CI scripts running checking that libbeat can be updated to the latest according version (`master`, `7.x`). The script being removed in https://github.com/elastic/apm-server/pull/3371 seems unintentional. The usage was commented out in the `Jenkinsfile`, suggesting the script not being used anymore.
However, it is still run from https://beats-ci.elastic.co/job/elastic+apm-server+7.x+beats-update/ and https://beats-ci.elastic.co/job/elastic+apm-server+master+beats-update/

The test runs still have the same value than before the cleanup and switching to go modules.

**Comment by axw** [comment]
Oops, sorry. I intentionally removed it thinking it was unused.

**Comment by graphaelli** [comment]
I think https://github.com/elastic/beats/pull/17218 resolves this issue.
