### ISSUE TITLE
[docs] Include Agent content instead of linking to it

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#3556]
## The problem

Our doc build has severe limitations in how we can share and reuse content. Because of this, the APM Server reference and APM overview are forced to link to relevant Agent content. In certain instances, this makes sense, but it most, it means that users have to leave the page and then come back, before they can complete a task. For users with multiple agents, this might mean jumping to multiple pages before completing their task.

Here's an example of one of these link farms, in the [secret-token](https://www.elastic.co/guide/en/apm/server/current/secret-token.html) docs:

<kbd>
<img width="939" alt="Screen Shot 2020-03-25 at 8 13 09 AM" src="https://user-images.githubusercontent.com/5618806/77552215-7ebe1380-6e70-11ea-963e-6bcb0c908240.png">

</kbd>

## A better user experience

A better user experience would be to include all relevant content in one place, so users don't have to jump around to complete a task. Here's a mockup of what this could look like:

<kbd>

![pick-n-agent](https://user-images.githubusercontent.com/5618806/77499804-59012200-6e10-11ea-81f6-a7c8873ea9cd.gif)

</kbd>

Note: When necessary, "More info" links could also be included at the bottom of each Agent's section.

## How?

**Today**
The only way we can pull this off with our current build, and how I created the gif above, is with an [HTML passthrough block](https://asciidoctor.org/docs/user-manual/#pass-blocks). Passthroughs allow us to pass HTML directly from asciidoc files to the rendered HTML output. The problem with this method is that it is hacky. Take a look to see what I mean: https://github.com/elastic/apm-server/compare/f624064b266f4621119c18b82ac99d768aaf9f37...bmorelli25:agent-examples.

**Ideally**
This needs to be baked into the documentation build. Implementation might be similar to what we do for the Elasticsearch Client examples. PR here: https://github.com/elastic/docs/pull/1024. See it in action here: https://www.elastic.co/guide/en/cloud/current/ec_connect_a_client.html. Screenshot below.

<kbd>

<img width="928" alt="Screen Shot 2020-03-25 at 8 29 27 AM" src="https://user-images.githubusercontent.com/5618806/77554003-c2198180-6e72-11ea-8152-717aab5f3a5b.png">

</kbd>
Obviously, the use case is different (clients only need code shared, APM needs content in general), but we have the ability to build something like this.

**Comment by simitt** [comment]
@bmorelli25 is this something we still want to look into (in the near term) with all the refactoring you are currently working on? Otherwise we can move it to backlog or close if not relevant anymore.

**Comment by bmorelli25** [comment]
I'll close this as it won't be addressed in our current doc system.
