### ISSUE TITLE
Add example for configuring Jaeger intake under ECK

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#3560]
Following up on https://github.com/elastic/apm/issues/212.

**Comment by simitt** [comment]
Also see https://github.com/elastic/apm-server/issues/2107#issuecomment-593461208

**Comment by axw** [comment]
Since Jaeger clients are deprecated in favour of OpenTelemetry SDKs and OTLP, I think we should close this.

We have a reasonable amount of documentation for OTel support already at https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html.

Closing, please reopen if you disagree.
