### ISSUE TITLE
[7.7] Upgrade go-elasticsearch client to latest commit of 7.7 branch 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3572]
New commits have been added to the [go-elasticsearch `7.7` branch](https://github.com/elastic/go-elasticsearch/commits/7.7), since the last upgrade in the APM Server. 
Ensure the APM Server branch is upgraded to the latest version.

**Comment by axw** [comment]
Closed by https://github.com/elastic/apm-server/pull/3597
