### ISSUE TITLE
Proposal: test kibana connection subcommand

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3575]
APM Server comes with, virtue of libbeat, a subcommand to test the configuration and the connection to the configured output.
It would be cool to have another option for testing the Kibana connection.

**Comment by axw** [comment]
Once we've fully moved things over to Elastic Agent and Fleet, the apm-server command is not something that users will be dealing with directly. Let's close this for now, happy to reopen if I missed a use case.
