### ISSUE TITLE
Central config never shows as having been applied, when applied by Jaeger agent

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3579]
When using the recently introduced support for central config + Jaeger, I noticed that the config never shows as having been applied:

![image](https://user-images.githubusercontent.com/843579/78002608-138da900-736a-11ea-90e9-a27ac85e3894.png)

We can't tell from the server whether a Jaeger client has applied the config. We can do one of the following:
 - Remove that indicator from the UI for Jaeger
 - Assume it's not applied, like we do today (doesn't seem very helpful?)
 - Mark it as having been applied upon query (hypothetically, could be untrue)

Given that we only support pushing out a probabilistic sampling rate, I think the hypothetical case is unlikely, and we should just mark it as applied immediately at query time.

**Comment by simitt** [comment]
The suggestion of labeling it as applied on query time SGTM. Should we aim for getting this in as fix for 7.7?

**Comment by axw** [comment]
I do think it's a bug, and have relabelled it as such. If it's a small change I think it would be good to fix it in 7.7, but I also don't think it's a big deal if it slips to 7.8.

**Comment by simitt** [comment]
The _has-been-applied_ label is set in Kibana when the remote config request from the server contains the current `Etag`, as it indicates the same response has been returned and at least somewhat successfully been applied already.
Jaeger agents will never send the Etag. I see two possible solutions here. Either the APM Server caches Etags for requests from Jaeger agents and adds the Etag before it sends the query to Kibana. Second option is that Kibana checks if the agent name of a queried configuration starts with `Jaeger`, in which case it sets the label. Pulling in @elastic/apm-ui team for discussion.

**Comment by axw** [comment]
> Jaeger agents will never send the Etag. I see two possible solutions here. Either the APM Server caches Etags for requests from Jaeger agents and adds the Etag before it sends the query to Kibana. Second option is that Kibana checks if the agent name of a queried configuration starts with Jaeger, in which case it sets the label. Pulling in @elastic/apm-ui team for discussion.

Another couple of related options:
 - apm-server could make a second query to Kibana straight away, with the Etag returned from the first result
 - apm-server could tell Kibana to set it as applied in the query, via a query param, based on the Jaeger prefix

**Comment by simitt** [comment]
I'd rather not use a query param, since it is a post request, but we could encode an attribute in the request body indicating that the _applied_ flag should be set. @elastic/apm-ui what do you think about adding such an indicator to the request body when fetching the agent configuration?

I'd also be fine with just implementing a second call to Kibana from the APM Server, but if we can avoid another call by directly applying the label on the first call it would be a bit nicer.

**Comment by cauemarcondes** [comment]
@simitt I can add a new attribute in the request body, maybe called `appliedByAgent:true`, which is going to be optional. WDYT?

**Comment by simitt** [comment]
That sounds good; the server would set it for `Jaeger` related config requests. One question - if the configuration returned by Kibana is a generic one (`all` agents, `all` environments), the applied label would still be applied right?

**Comment by cauemarcondes** [comment]
> That sounds good; the server would set it for `Jaeger` related config requests. One question - if the configuration returned by Kibana is a generic one (`all` agents, `all` environments), the applied label would still be applied right?

yes.
