### ISSUE TITLE
GeoIP enrichment processor

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3613]
For https://github.com/elastic/apm-server/issues/3485 we will need to perform GeoIP enrichment early enough to incorporate into latency histogram aggregation keys, to enable the RUM map visualisation. We (currently) just need the country ISO code.

Ideally we would bundle the MaxMind GeoLite2 database, and enable users to load their own commercially licensed copy of GeoIP2, like Elasticsearch does.

**Comment by axw** [comment]
Since the RUM-specific charts have been removed from the APM UI (https://github.com/elastic/kibana/pull/77458), I don't think we need to incorporate geo information into transaction metrics any more, and we should be remove the browser name from the transaction metrics.

In the new Client Side Monitoring app, it is possible to visualise a breakdown by location, device, and more. This app, however, does not expect data to be pre-aggregated. The RUM agent will continue to send "unsampled" transactions so that users can perform high fidelity, ad-hoc breakdowns.

@sqren @andrewvc can you please let me know if this is accurate?

**Comment by sqren** [comment]
This is accurate for now at least. I don't know if the longer term plans are for the UX app to also transition to pre-aggregated data. @vigneshshanmugam / @jahtalab / @shahzad31 would know.

**Comment by paulb-elastic** [comment]
Although we may have a need for this in the future, it is unclear what they will be now. As such, please go ahead with your changes, and we will consider our implementation if/when we need to do this. (cc @jahtalab)

**Comment by axw** [comment]
Thanks @paulb-elastic, sounds good!
