### ISSUE TITLE
[docs] Add libbeat processor documentation

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#3624]
Libbeat's [processor documentation](https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html) might be useful for some APM users. For example, a user that wants to drop certain span fields to save on storage.

**Comment by axw** [comment]
The team has been discussing this recently, and we've come to the conclusion that adding support for processors is in conflict with proposed performance improvements such as described in https://github.com/elastic/apm-server/issues/3565. Let's not document processors, as we would like to replace them with more APM-specific functionality/config.

**Comment by leyao-daily** [comment]
> #3565

Sorry for bothering after so long time. What will be a more APM-specific functionality/config to replace the processors when upgrading from 7.x to 8.x by using standalone apm-server. For example my configuration in 7.x
```
processors:
- add_host_metadata:
    netinfo.enabled: true
```
