### ISSUE TITLE
Elastic APM .net agent is not instrumenting methods

### ISSUE THREAD

**Issue by ramkms6666** [elastic/apm-server#3669]
Hi, 

I just set up Elastic APM .Net agent, I have Asp.net core web api project, I used below configuration in my startup file to configure the APM, now it is sending the data to APM. 
```
using Elastic.Apm.NetCoreAll;

 app.UseAllElasticApm(Configuration);
```
my problem is I am only seeing Http top level requests as If I am seeing in Chrome network tab, selecting each http request is not drilling down to method calls and time it took to start and and the method and follow the call stack. I am looking here .Net code method instrumentation also under the http web api call.  Please advice if there is anything I am missing.  

below is how it looks no further breaking down, I would like to drill down further into each and everymethod, please advise if we can achieve this or not. 

![image](https://user-images.githubusercontent.com/3129328/79729831-983a6a00-830d-11ea-822e-2731b1f5c6cc.png)

**Comment by ramkms6666** [comment]
also I am attaching debug logs here. 
[Elastic.Apm-2020-04-20.log](https://github.com/elastic/apm-server/files/4502080/Elastic.Apm-2020-04-20.log)

**Comment by simitt** [comment]
Please use the [APM discuss](https://discuss.elastic.co/c/apm/) forum for posting questions. We'd like to reserve github issues for confirmed bugs and feature requests. In case the outcome of the discussion is a confirmed bug, feel free to open an issue again in the corresponding repository (this repo for APM Server issues, [apm-agent-dotnet](https://github.com/elastic/apm-agent-dotnet/) for issues with the .NET agent).

**Comment by simitt** [comment]
Thanks for opening https://discuss.elastic.co/t/elastic-apm-net-agent-is-not-instrumenting-methods/228815, closing this issue now.
