### ISSUE TITLE
Do not create daily indices for onboarding docs

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3670]
Currently the `onboarding` doc is still written to a daily index. Rethink current index handling for onboarding documents, to also make use of ILM. A dedicated rollover policy that only considers the size instead of time might make sense for onboarding docs.

When only restarting the APM Server occasionally or on upgrade the current approach is not an issue, but can lead to a higher number of unnecessary indices in deployment scenarios where APM Servers might be restarted every day/several times per day.

**Comment by graphaelli** [comment]
Consider upserting the same document instead of creating new docs.

**Comment by axw** [comment]
We'll be removing onboarding docs when we move to Elastic Agent and Data Streams.
