### ISSUE TITLE
Add `only_library_frames` bool to span

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#372]
Add a boolean `has_in_app_frame` to every `span` to determine whether it has in_app frames. 
This can be done while [iterating over frames](https://github.com/elastic/apm-server/blob/master/model/stacktrace.go#L18). 

This field should be indexed, so it needs to be added to the [fields](https://github.com/elastic/apm-server/blob/master/processor/transaction/_meta/fields.yml).

**Comment by beniwohli** [comment]
Why does the field need to be indexed? AFAICT, we don't plan to filter on it (e.g. only get traces that have in-app frames).

**Comment by vanjacosic** [comment]
Please ping `@elastic/apm-ui` once this has been implemented, thanks! 👍

**Comment by graphaelli** [comment]
updated to `only_library_frames` per #384

**Comment by simitt** [comment]
@beniwohli you are probably right, as this only needs to be detected for specific traces.

**Comment by graphaelli** [comment]
waiting for #388 to be merged before putting up a pull request for this, preview at https://github.com/graphaelli/apm-server/compare/remove-stacktrace-transform-fn...graphaelli:only_library_frames
