### ISSUE TITLE
docs: Improve feature overviews

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#3726]
Analytics show that pages like [RUM](https://www.elastic.co/guide/en/apm/get-started/current/rum.html) and [Distributed tracing](https://www.elastic.co/guide/en/apm/get-started/current/distributed-tracing.html) are popular starting points in the APM documentation. We explain features on these pages, but we don't do a good job of providing relevant next steps. We should add a "Learn more" section to the bottom of these pages, and any other overview pages, with links and explanations of how to...learn more.

As an example, Distributed tracing might link to a few different places:
* The RUM DT guide, for setting up DT to work with front-end applications
* The data model, for learning more about the components that make up a trace
* The distributed tracing waterfall documentation in the APM app, to learn more about what DT looks like.

**Comment by simitt** [comment]
@bmorelli25 is this something we still want to look into (in the near term) with all the refactoring you are currently working on? Otherwise we can move it to backlog or close if not relevant anymore.

**Comment by bmorelli25** [comment]
Not really relevant anymore. Most of these pages have been updated since then or have other updates pending with the refactoring work.
