### ISSUE TITLE
Print build date/time and commit hash on startup?

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-server#375]
For easy debuggability, especially of snapshot builds, it would be nice if the apm-server would print out its build date/time and commit hash, similar to how it prints the version:

    2017/12/04 14:44:27.223895 beat.go:203: INFO Setup Beat: apm-server; Version: 7.0.0-alpha1

A more involved version would be an endpoint where this information could be queried, but this has certain security implications: making it easy to discover which version of the apm-server is running could make it easy for attackers to find outdated and possibly insecure versions of the apm-server in the wild.

**Comment by roncohen** [comment]
Thanks @beniwohli! Writing out the hash and build time would be useful.
Regarding making that information available over HTTP: We could make the version information only returned when the secret token is set and supplied in the request.

**Comment by graphaelli** [comment]
this was implemented in #396 and fixed in #404
