### ISSUE TITLE
Have no settings for set custom rollover_alias

### ISSUE THREAD

**Issue by MaxymVlasov** [elastic/apm-server#3779]
Hi!

I need to set custom `rollover_alias` how I did it in `filebeat`, but found that APM [have no configuration](https://github.com/elastic/apm-server/blob/master/apm-server.yml) for it.

I searching how it can be done and found that in [template.go](https://github.com/elastic/apm-server/blob/master/idxmgmt/ilm/template.go#L39) exist `"lifecycle.rollover_alias": name,` construction introduced in #2099. But I have no idea how I can use it.

So, this is or feature request or docs improvement request. 

Here how it looks like in filebeat: 

```yaml
setup.ilm.rollover_alias: "filebeat-prod"
```

### Use case 

Now we use one EFK for all environments. Each environment have it own ILM policy with different settings.
So I need setup all indexes like this:
![](http://i.piccy.info/i9/fd6f3102a2eda576f6c1cb0671533e58/1588957135/8602/1370499/Screenshot_from_2020_05_08_19_51_04.png)

Otherwise, data from all envs will be mixed in one index.

But this not works for APM, so now I must use different APM-server versions in each environment. 
![](http://i.piccy.info/i9/d683b8a8bb724011b58401735dd5ef65/1588957475/7362/1370499/Screenshot_from_2020_05_08_19_57_16.png)

**Comment by simitt** [comment]
Hi @MaxymVlasov, you are right that we currently do not support setting custom `rollover_alias`. If you depend on customizing the aliases you would need to manually set up ILM (rollover_aliases, policies and templates), disable the setup by APM Server (`apm-server.ilm.setup.enabled=false`) and configure the rollover aliases as indices in the `output.elasticsearch.indices` section. 

I'll label this issue as enhancement request and investigate how much effort it would be to add support in the APM Server.

**Comment by MaxymVlasov** [comment]
We also need ILM, because time to time we have logs/metrics peaks and give up to 10 more data in this periods, so day-by-day rotation is not works for as very well => `curator` not suitable solution.

In same time, I have many projects with +- same settings, so for me "Everything as Code" better than any manual work in long term.

**Comment by simitt** [comment]
This has been implemented with #3826. The configuration for `rollover_alias` is restricted to known strings or variable parts from `observer.*` that are known at setup time. (The same restriction applies for beats at the moment).

**Comment by MaxymVlasov** [comment]
Thank you!

I will definitely try when v7.9.0 will be released.
