### ISSUE TITLE
Test (manually) the RUM V3 endpoint

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3786]
The tester should ensure that the same data that RUM reports in V2, is still accepted, ingested and indexed in Elasticsearch (with the same types, etc.) with the V3 endpoint.

This needs a RUM agent capable of using the new endpoint. Get in touch with @vigneshshanmugam and @jahtalab for that.

Meta issue: https://github.com/elastic/apm-server/issues/2854

Main PR's:

https://github.com/elastic/apm-server/pull/3328
https://github.com/elastic/apm-server/pull/3414
https://github.com/elastic/apm-server/pull/3526
https://github.com/elastic/apm-server/pull/3616
https://github.com/elastic/apm-server/pull/3648
https://github.com/elastic/apm-server/pull/3659
https://github.com/elastic/apm-server/pull/3733

Related issue:

https://github.com/elastic/apm-server/issues/3481

**Comment by simitt** [comment]
@vigneshshanmugam and @jahtalab can you assist in how to test this with a new RUM agent please?

**Comment by jahtalab** [comment]
@simitt , [The PR](https://github.com/elastic/apm-agent-rum-js/pull/771) that contains support for v3 endpoint has already been merged. As a part of that @vigneshshanmugam did some manual tests on the payload/ES/Kibana. Are there any specific tests you had in mind?

We can also release those changes in the agent if needed to make integration testing easier, since v3 support is behind a feature flag.

**Comment by vigneshshanmugam** [comment]
@simitt As hamid pointed out, I have tested most of the functionality(Transaction, Spans, Breakdowns) with the v3 spec and the values on APM UI as well and have created issues in server where appropriate #3746. 

If you have anything specific in mind, Please do let us know and we are happy to help with testing.

**Comment by simitt** [comment]
Ah great to hear! @jalvz this sounds like it has been tested then, do you have anything specific in mind that we should additionally test from the server side?

**Comment by jalvz** [comment]
Ah, nice. Maybe check that transactions with unknown marks and metrics are ignored, but not rejected?

**Comment by simitt** [comment]
I tested unknown marks and metrics for the v3 endpoint and it works as expected.
