### ISSUE TITLE
beater/middleware: update fields to be ECS-compliant

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3796]
We should update the logging middleware to use ECS-compliant field names and values:

https://github.com/elastic/apm-server/blob/c0f47670caa543889907501d1c26820311912991/beater/middleware/log_middleware.go#L34

"method" -> "http.method", "URL" -> "http.url", etc.

**Comment by simitt** [comment]
Depends on https://github.com/elastic/beats/pull/18820
