### ISSUE TITLE
Transaction duration metrics not published for apm-server

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-server#3801]
When aggregation of transaction duration metrics is enabled (via `apm-server.aggregation.enabled=true`), metrics for apm-server are seemingly not published. For other services, transaction duration metrics _are_ published.

**Comment by axw** [comment]
https://github.com/elastic/apm-server/blob/fa9bc094c330351478c06b3678aa042b1fb9d866/beater/beater.go#L157

The trace server is running with the core reporter, and not the wrapped one (i.e. the one that performs aggregation.)  We'll probably need to change CreatorParams.RunServer to be a middleware type of function, which takes a RunServerFunc and returns a wrapped RunServerFunc.
