### ISSUE TITLE
Add docs for RUM response headers

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#3821]
Issues elastic/apm-server#3696 
PR elastic/apm-server#3820

**Comment by bmorelli25** [comment]
Am I correct in assuming we just need to add information about `apm-server.rum.response_headers` to [this](https://www.elastic.co/guide/en/apm/server/7.12/configuration-rum.html) page?

**Comment by simitt** [comment]
Apologies for never coming back to you @bmorelli25 and thanks for putting up the PR!
