### ISSUE TITLE
Duplicate page.url as url.*, to make it searchable

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#3827]
For RUM page load transactions and errors, index the page URL into ECS [url](https://www.elastic.co/guide/en/ecs/current/ecs-url.html) fields so it is full-text searchable. For backwards compatibility (up until 8.0), we would need to continue indexing into `page.url` as well.

---

*Original description*

The current Transaction.page.url is not indexed and therefore not searchable (it's only used in the UI). Since searching over the page url has been requested before we should consider indexing this field. 

We should, also, clean up the url for indexing. e.g. removing query strings. another possiblity is to add a `fullUrl` field, that contains the url without any change and set the clean up url on `page.url`

**Comment by jahtalab** [comment]
@axw, two questions:

1. Do you think we can get this on 7.9 milestone?
2. Is there a possibility to reindex existing data to duplicate the url when users upgrade? This is not a requirement but only nice to have, if the complexity of reindexing is not huge.

**Comment by axw** [comment]
@jahtalab 

> Do you think we can get this on 7.9 milestone?

I think we can probably manage that.

> Is there a possibility to reindex existing data to duplicate the url when users upgrade? This is not a requirement but only nice to have, if the complexity of reindexing is not huge.

It's theoretically possible, but unlikely that we would do that - at least not for 7.9, and likely not in the foreseeable future. We don't have any infrastructure in place for things like this.

We could suggest an _update_by_query script to run manually though.

**Comment by jahtalab** [comment]
Thanks @axw , I think it's fine to duplicate url only on new data for now.

**Comment by simitt** [comment]
What is the usecase for collecting `page.url.*`? Depending on the usecase it might make sense to not only duplicate the field in `url.full` but split it into it's parts and fill as many of the [ECS defined `url.*` fields](https://github.com/elastic/ecs/blob/master/schemas/url.yml) as applicable. 

Since the `url.full` is indexed as multifield, I'd also not trim it to `1024` chars but leave it unchanged.

**Comment by jahtalab** [comment]
Good idea @simitt , for now the use-cases have been around trying to search for a particular url. but I think if we start splitting the url into its fields (as well as keeping the full url), it can help address many more use-cases (e.g. ad-hoc search queries based on scheme).

cc @andrewvc  @shahzad31 @justinkambic  @drewpost

**Comment by jahtalab** [comment]
I've updated the description to apply the same solution for both Transactions and Errors

**Comment by drewpost** [comment]
I like @simitt suggest to break it down as much as possible. Question - would you propose normalising the query strings or storing them as received?

**Comment by simitt** [comment]
I was not thinking to normalize them; we could reuse the logic we have for jaeger in place https://github.com/elastic/apm-server/blob/master/processor/otel/consumer.go#L508.

**Comment by simitt** [comment]
While on it, we could also map `page.referer` to the ECS field `http.request.referer`.

**Comment by jalvz** [comment]
where should the duplicated field be stored? 
`url` is used already for `context.request.url`

**Comment by axw** [comment]
@jalvz the (previously unwritten) assumption here is that you only ever pass `context.page` *or* `context.request`.

I would suggest we codify that by making the JSON Schema more strict.

**Comment by jalvz** [comment]
@jahtalab any reasons to not go with https://github.com/elastic/apm-server/issues/3827#issuecomment-638192942? (This was expected at least by 1 customer)

**Comment by jahtalab** [comment]
I don't see any reason why not. Other than the fact that ECS field is `referrer` and the actual http header name is `referer` wrong spelling but it is the standard 😄
