### ISSUE TITLE
APM server should behave like beats input in regards to index management

### ISSUE THREAD

**Issue by philippkahr** [elastic/apm-server#3882]
Hello!

I personally am confused by how apm-server is handling index management differently than beats. I have hundreds of apm-* indexes with just a few kb in them. (my application is not seeing much traffic)

Would it be possible to match apm-server index handling to how beats handle indexes? E.g. 50gb one shard, if exceeded create a new index, or if the index is older than 30 days?

I am using 7.7.1 all across the entire stack.

**Comment by simitt** [comment]
Hi @philippkahr,
APM Server on purpose generates an index per event type. The reason for this is to allow different retention periods for different data. For example, one might want to keep high level information (e.g. transactions) around longer than very detailed information (spans). 

When using the default index setup with APM 7.7 you should see a rollover policy of `50gb` or `30d` though. Therefore I am surprised to hear that you see a lot of small indices. You can see the default Index Lifecycle Management (ILM) configurations in the [apm-server.yml](https://github.com/elastic/apm-server/blob/master/apm-server.yml#L391). Have you changed anything related to the ILM setup, or did you configure anything for unmanaged indices via `output.elasticsearch.indices`, which would automatically disable ILM?

One exception from the above mentioned is the onboarding index, that is still unmanaged and gets created on server startup. 

Did you know we also have a [discuss forum](https://discuss.elastic.co/c/observability/apm/)? It'd be great if you could post future questions there, allowing other users to follow along if interested and keeping issues in this repository reserved for confirmed bugs and feature requests.

**Comment by philippkahr** [comment]
Hi @simitt 
Thanks for the quick reply. It was an issue on my side, I forgot to start ILM. With > 7.7 you are right, there is an ILM policy in place. I will double-check the discussion forum before posting a GitHub issue.
