### ISSUE TITLE
JSON decoding error when POSTing from a client-side application

### ISSUE THREAD

**Issue by Zertz** [elastic/apm-server#389]
Hello, I'm having some trouble trying to log a client-side transaction into apm-server. I've set up Elasticsearch, Kibana and apm-server and all three are running happily, I can access the Kibana dashboard and the APM dashboards are displayed. I have also setup `allow_origins` to get past CORS and got to a point where apm-server gets the request but seems unhappy about its format even when I copy/paste the sample minimal payload from the docs. I tried both building from source and using [master](https://www.elastic.co/guide/en/apm/server/master/transaction-api.html#payload-with-minimal-transaction) and downloading from the Elastic website using [current](https://www.elastic.co/guide/en/apm/server/current/transaction-api.html#payload-with-minimal-transaction). (and vice-versa even!)

Request:

```js
const request = new Request('http://localhost:8200/v1/client-side/transactions', {
  method: 'POST',
  headers: new Headers({
    'Content-Type': 'application/json'
  }),
  body: {
    "app": {
      "name": "app1",
      "agent": {
        "name": "python",
        "version": "1.0"
      }
    },
    "transactions": [{
      "id": "945254c5-67a5-417e-8a4e-aa29efcbfb79",
      "name": "GET /api/types",
      "type": "request",
      "duration": 32.592981,
      "timestamp": "2017-05-09T15:04:05.999999Z"
    }]
  }
})

const response = await fetch(request)
const json = await response.json()
```

Response:
```json
{
  "error": "Decoding error: Data read error: json: cannot unmarshal array into Go value of type map[string]interface {}"
}
```

Any ideas as to what I'm doing wrong?

**Comment by jalvz** [comment]
Hi @Zertz,

I am not JS expert, so forgive me if this isn't correct; but don't you have to wrap the body in a string? The following works for me:

```javascript
> const req = new Request('http://localhost:8200/v1/client-side/transactions', {
  method: 'POST',
  headers: new Headers({
    'Content-Type': 'application/json'
  }),
  body: `{
    "service": {
      "name": "app1",
      "agent": {
        "name": "python",
        "version": "1.0"
      }
    },
    "transactions": [{
      "id": "945254c5-67a5-417e-8a4e-aa29efcbfb79",
      "name": "GET /api/types",
      "type": "request",
      "duration": 32.592981,
      "timestamp": "2017-05-09T15:04:05.999999Z"
    }]
  }`
})

> const resp = await fetch(req)

> resp.status
< 202
```

`resp.json()` would fail here because if the request goes through we don't return anything (just 202 - Accepted), so you need to check the status first, and only if it is 4XX or 5XX you check the content.

Other than that, there has been a breaking change in master with respect to 6.0 and 6.1: `app` has been renamed to `service`.

Does this make sense?

**Comment by Zertz** [comment]
You are genius, thanks! I was just missing the quotes, pretty obvious now that you mention it 🙄 

I'm making a small wrapper for plain JavaScript and writing a React integration on top of that!

**Comment by jalvz** [comment]
Great @Zertz , happy to help!
