### ISSUE TITLE
Use race-neutral terminology

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3896]
- Rename default branch from master to main
- Replace any occurrences of "whitelist" and "blacklist"

Branch renaming will require changes to the docs build, CI, and possibly release manager.

**Comment by kseniia-kolpakova** [comment]
We have this planned in our roadmap for this year for all Observability. Let's collaborate on this.

**Comment by simitt** [comment]
@v1v has finished the branch renaming, therefore unblocking this issue.
