### ISSUE TITLE
More useful access log

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-server#390]
Currently, the apm-server only prints this for successful requests

    request successful, code=202

and an error message plus the status code for unsuccessful ones.

To properly debug issues, it would be useful if the apm-server logged something more akin to an access log of an http server, including IP address of sender, user agent of sender, requested path, and HTTP method.

I also think `INFO` would be a better level than `DEBUG` for these log messages.

**Comment by jalvz** [comment]
Would you prefer *exactly an access log format (with hyphens for unknown data, etc), or you think that as long we log that info is good enough?

**Comment by beniwohli** [comment]
for debuggin purposes, having it there in some form would already be great. Trying to emulate a certain log format is probably not super helpful, since HTTP servers usually allow it to be customized. We could make it easily parse-able by using some key-value format
