### ISSUE TITLE
Server exits with unhelpful error when ssl.enabled=true, but cert/key files are unspecified

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3908]
When you configure apm-server with `ssl.enabled: true`, but don't specify either `ssl.certificate` or `ssl.key`, then apm-server will exit with the following error message:

`Exiting: open : no such file or directory`

The [docs](https://www.elastic.co/guide/en/apm/server/current/agent-server-ssl.html) say:

> certificate
> The path to the file containing the certificate for Server authentication. Required if apm-server.ssl.enabled is true.
>
> key
> The path to the file containing the Server certificate key. Required if apm-server.ssl.enabled is true.

We should validate these requirements during startup, and exit with a more helpful error message, suggesting what needs to be changed.

**Comment by simitt** [comment]
It might make sense to make the changes directly in libbeat, as this error message is currently the same for all the beats.

**Comment by axw** [comment]
Verified with BC2. Procedure:
 - Started stack with apm-it
 - Modified docker-compose.yml, adding `-E apm-server.ssl.enabled=true` to apm-server command
 - Found a moderately more useful error message:

> localtesting_7.9.0_apm-server | Exiting: Error processing configuration: certificate file not configured accessing 'apm-server.ssl' (source:'command line flag')
