### ISSUE TITLE
how to open alerts function?kibana now has ssl config ,apm-server can't connect to kibana,can you give me a tempalte of the apm-server.yml file for ssl settings

### ISSUE THREAD

**Issue by ZemarLi549** [elastic/apm-server#3944]
Hello!

We like to keep the Github repository for product issues - verified bug reports, pull requests, apm-server specific feature requests, etc and have users ask questions about how to use the product or a particular feature in our discuss forums.

If you have a question or are experiencing some problem please head on over to our official [Discuss forum](https://discuss.elastic.co/c/apm). You will reach a wider audience, get help from the broader community, and maybe learn how others solved problems similar to yours.

Thanks!

**Comment by simitt** [comment]
Hi @ZemarLi549 , please head over to the [Discuss forum](https://discuss.elastic.co/c/observability/apm/58) and post your question there to reach a wider audience and to keep this repository for confirmed bugs and enhancement requests. Include error and log messages if available, to help identiying and solving issues faster.
