### ISSUE TITLE
certificate is valid for elasticsearch, not localhost

### ISSUE THREAD

**Issue by ZemarLi549** [elastic/apm-server#3949]
Hello!

We like to keep the Github repository for product issues - verified bug reports, pull requests, apm-server specific feature requests, etc and have users ask questions about how to use the product or a particular feature in our discuss forums.

If you have a question or are experiencing some problem please head on over to our official [Discuss forum](https://discuss.elastic.co/c/apm). You will reach a wider audience, get help from the broader community, and maybe learn how others solved problems similar to yours.

Thanks!

**Comment by ZemarLi549** [comment]
when i open ssl setting ,apm-server can't connet to elaticsearch

**Comment by jalvz** [comment]
Hello, we will be happy to help if you ask this question in [Discuss](official Discuss forum) and give as much information as possible about the problem you are experiencing. Like this everyone can benefit from your question!

Thanks!!

**Comment by ZemarLi549** [comment]
ok
