### ISSUE TITLE
beater/api/profile: add support for JFR encoding

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3960]
Currently we have experimental support for receiving pprof-encoded profiles. To enable profiling Java applications, we should also add support for decoding JFR (Java Flight Recorder) profiles to the server. This will offload the cost of translation to a common data model to the server, to avoid impacting applications.

**Comment by felixbarny** [comment]
Happy to help with tests here. We're already parsing JFR files for inferred spans. But for CPU/allocation/lock profiling, we'd like to avoid having to parse the file.

Here's our current JFR parser: https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/asyncprofiler/JfrParser.java

Note that async-profiler doesn't use the most recent JFR version (0.7 IIRC). The format may slightly change in the future as well as async-profiler has plans to support continuous profiling. Once we have a target version for this, we should sync on what's left to do and which things should be included in the first version.

**Comment by axw** [comment]
Perfect, thanks for the pointer @felixbarny. In terms of testing, it would be ideal if we had some sample profiles that we can use for "golden testing". No rush as we won't get to this for a little while yet.

**Comment by axw** [comment]
Closing as we have no concrete plans to get to this, I'll resurrect it if/when we do.
