### ISSUE TITLE
Elastic APM -Logstash query

### ISSUE THREAD

**Issue by MandarGV** [elastic/apm-server#3963]
Hi
I have installed ElasticSearch, APM Server, Kibana, Java agents successfully.

Do I need to install logstash as well? 

when i try to trace my transactions I dont see the trace is it because Logstash is not installed?
I see something like this.
![image](https://user-images.githubusercontent.com/68057654/87294703-bcc76c00-c521-11ea-8f40-3ac5292fe0b3.png)

Thanks

**Comment by axw** [comment]
Hello, we will be happy to help if you ask this question in [Discuss](https://discuss.elastic.co/c/apm) and give as much information as possible about the problem you are experiencing. Like this everyone can benefit from your question!

Thanks!
