### ISSUE TITLE
Add "experience" properties to RUM transaction schema

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#3972]
In the RUM agent we need to store structured metrics/metadata on transactions.

We have these requirements:
1. The data needs to be on the transaction (to avoid expensive queries)
2. The data needs to be indexed (filtering)
3. The structure needs to be defined in the intake schema (to use compression)

I propose to add the following structure to the transaction schema
```
{
    "experience": {
        "type": "object",
        "properties": {
            "cls": {
                "type": "number",
                "description": "The Cumulative Layout Shift metric",
                "minimum": 0
            },
            "tbt": {
                "type": "number",
                "description": "The Total Blocking Time metric",
                "minimum": 0
            },
            "fid": {
                "type": "number",
                "description": "The First Input Delay metric",
                "minimum": 0
            }
        }
    }
}
```

We should use the above structure for intake v2 and storage in ES. 

For intake v3 we only need to abbreviate `experience` to `exp`:

```
{
    "exp": {
        "type": "object",
        "properties": {
            "cls": {
                "type": "number",
                "description": "The Cumulative Layout Shift metric",
                "minimum": 0
            },
            "tbt": {
                "type": "number",
                "description": "The Total Blocking Time metric",
                "minimum": 0
            },
            "fid": {
                "type": "number",
                "description": "The First Input Delay metric",
                "minimum": 0
            }
        }
    }
}
```

We also [discussed defining metadata/metrics on transactions](https://github.com/elastic/apm/issues/293) for all agents but this doesn't seem to apply to backend agents.

**Comment by jahtalab** [comment]
Had a meeting:
- We discussed using this new field for storing marks as well but only for the RUM schema
- We discussed `experience` as the name for the field

**Comment by axw** [comment]
The RUMv3 protocol supports nesting metrics within transactions: https://github.com/elastic/apm-server/pull/3733. The way that works, however, is that it creates separate metrics docs with the `transaction.name` and `transaction.type` taken from the outer transaction. Just want to clarify: what you're asking for is to add the metrics fields on the transaction docs themselves? i.e. request-scoped metrics.

> We discussed using this new field for storing marks as well but only for the RUM schema
> We discussed experience as the name for the field

"experience" does not have a clear meaning to me. If it's hard to find a word that covers all the uses, that may be an indication that there's multiple concepts being conflated.

Anyway, please use the [new fields](https://github.com/elastic/apm/issues/new?labels=agents%2C+poll&template=new-fields-issue.md) issue template in elastic/apm. I think request-scoped metrics may be relevant to more than just RUM.

**Comment by jahtalab** [comment]
@axw , that's correct the `experience` field should be store on the transaction document.

With this field we want to capture user experience metrics [such as core vitals](https://web.dev/vitals/), we discussed `metrics` as well but we were worried that would create confusion since we already have a similar concept. I'll bring up naming on our next meeting again.

We already discussed whether this field would be useful for other agents on the agents weekly please see the referenced issue in the description for details, in summary, backend agents did not have a foreseeable use-case for this. Happy to discuss that further with the apm-server team if needed.

**Comment by jahtalab** [comment]
I gave the naming some more thought and from my perspective we can take two approaches, one is to make this field very specific to what we now need i.e. "user experience metrics" and if we need to add more attributes in the future we will have to define other top level fields. Or we can make this field a generic one, similar to labels but with the structure predefined.

I slightly prefer the generic approach since this allows us to limit the number of top-level transaction fields and at the same time gives space for experimental/new attributes.


@andrewvc @vigneshshanmugam , @axw,  any thoughts or suggestions?

**Comment by axw** [comment]
@jahtalab sorry, I think I read the first issue and this one together and got a bit mixed up about what you were asking for.

I understand now that you're asking about adding `experience.cls`, and not a free-form schema for metrics that end up under `experience`. Is that right? My concern was about having arbitrary metrics that end up under a more specific/restrictive field name like "experience". I don't have any concern if we're defining the metric names that are restricted to user experience.

Assuming we're building dashboards off these, I think having well-defined fields is the ideal way to go. I think there might still be a case for arbitrary request-scoped metrics, but I don't think we build core features like this on top of something so free-form.

Are these user experience metrics specific to page load transactions? Should `experience` be nested under `page`?

**Comment by vigneshshanmugam** [comment]
> I think having well-defined fields is the ideal way to go. I think there might still be a case for arbitrary request-scoped metrics, but I don't think we build core features like this on top of something so free-form.

👍 , Also the way we use compression for RUM agent, we would need to predefine these metrics and free-form wont work for us. Cumulative Layout Shift(CLS) is just an example, we are planning to expand this field with experience related metrics as well. 
```js
// example
{
  experience: {
    cls: 0.02,
    totalBlockingTime: 200,
    firstInputDelay: 20
  }
}
```

> Are these user experience metrics specific to page load transactions? Should experience be nested under page?

For now, most of the new proposed metics are specific to the first hard navigation (page-load), but there are plans to add these metrics to the subsequent navigations as well (route-change). We might need to redefine these metrics later on if we scope it under `page`, IMO having it under transaction sounds safer to me.

**Comment by jahtalab** [comment]
As Vignesh mentioned, this won't be a free-form field and I think having it under transaction makes more sense. 

Just to make sure, the current version of APM server will ignore field on transaction that are not defined in the schema, right? (we don't want the payload to fail for older versions after we add this field in the agent.)

@axw , Is it possible to get this on one of milestones (preferably 7.10 if possible)? Also, if it doesn't delay adding `cls`, maybe we should add the totalBlockingTime `tbt` and firstInputDelay `fid` in the same issue as well, WDYT?

**Comment by axw** [comment]
Sounds good. It would be easier to add them at the same time, if they're all going to be added eventually.

> Just to make sure, the current version of APM server will ignore field on transaction that are not defined in the schema, right? (we don't want the payload to fail for older versions after we add this field in the agent.)

That's correct, they'll just be ignored.

> @axw , Is it possible to get this on one of milestones (preferably 7.10 if possible)? Also, if it doesn't delay adding cls, maybe we should add the totalBlockingTime tbt and firstInputDelay fid in the same issue as well, WDYT?

I think this is small enough that we can add it to 7.10, but can you please help clarify the following in the description:

 - the full list of added properties to both intake v2 and v3 (i.e. abbreviated for RUM)
 - the names to use in Elasticsearch -- I don't think ECS is necessary here

**Comment by jahtalab** [comment]
Thanks @axw , I've updated the description to clarify those points, and I agree, using ECS doesn't apply here.

**Comment by axw** [comment]
Thanks @jahtalab. Should these be stored in Elasticsearch as `transaction.experience.{cls,tbt,fid}` too? AIUI, they're fairly common abbreviations in the webperf world. Would be helpful to spell them out as `cumulative_layout_shift`, etc., or overkill?

**Comment by vigneshshanmugam** [comment]
@jahtalab `ex` is already taken for `exception`, let's use `exp` or `ep` for v3 intake. I have updated the description, wanted to inform here before i change the description.

**Comment by jahtalab** [comment]
@vigneshshanmugam, good point, I did check the [transaction schema](https://github.com/elastic/apm-server/blob/master/docs/spec/transactions/rum_v3_transaction.json), `ex` is not defined there, but it's defined for errors. Let's go with `exp` since that's safer.

**Comment by vigneshshanmugam** [comment]
Its not directly under the transaction, but here is the full list https://github.com/elastic/apm-server/blob/master/model/modeldecoder/field/rum_v3_mapping.go#L53

**Comment by jahtalab** [comment]
@axw , Following our conversation I've added this to 7.10 milestone to make sure we don't miss this. Please let me know if this is not possible since some features rely on this.

**Comment by axw** [comment]
@jahtalab that should be fine, thanks.
