### ISSUE TITLE
[RUM] User agent devices are marked as "Others"

### ISSUE THREAD

**Issue by shahzad31** [elastic/apm-server#3974]
APM is identifying majority of user agents passed from rum events as others.
in Following example we can see 50% of devices are marked as others.

![image](https://user-images.githubusercontent.com/3505601/87535402-b8bd5a80-c697-11ea-9d6d-4f8f6a433fa6.png)

This is actual list of user agents used for above data
```
const UserAgents = [
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
  'Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36',
  'Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/69.0.3497.105 Mobile/15E148 Safari/605.1',
  'Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1',
  'Mozilla/5.0 (Linux; Android 7.0; Pixel C Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.98 Safari/537.36',
  'Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9',
  'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1',
  'Mozilla/5.0 (CrKey armv7l 1.5.16041) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.0 Safari/537.36',
];
```

It seems like there is some issue identifying desktop/laptop user agents. Ideally it should identify devices correctly so that user can have clear picture about their data.

Same issues is persistent in a customer data, where upto 75% devices are marked as "Others".

**Comment by shahzad31** [comment]
cc @vigneshshanmugam @jahtalab

**Comment by axw** [comment]
APM Server does not do the parsing you're referring to, ingest node does: https://www.elastic.co/guide/en/elasticsearch/reference/current/user-agent-processor.html

It appears that the uap-core regular expressions shipped with Elasticsearch haven't been updated in a while, and they're missing at least the generic "Mac OS" rule: https://github.com/ua-parser/uap-core/blob/f21592418f6323f9ce32f10e231841cf8e782b43/regexes.yaml#L5578-L5587

Can you please open an issue on Elasticsearch instead? You may want to try loading https://github.com/ua-parser/uap-core/blob/master/regexes.yaml into Elasticsearch (see the ingest node link above for details) first; I don't know if just updating that will be enough to fix this, but it may be.

**Comment by shahzad31** [comment]
opened issue in es  https://github.com/elastic/elasticsearch/issues/59694
