### ISSUE TITLE
Load dashboard in Kibana 5.6

### ISSUE THREAD

**Issue by Cesaragsilva** [elastic/apm-server#3999]
Hello!

I'm using Kibana and Elastic in version 5.6 and APM Server in version 6.8. With the Kibana 5.6 it's possible have a dashboard for APM Server like a dashboards in Kibana (APM App) 7.1 for example. If it's possible, how i can do this?

**Comment by axw** [comment]
Hi @Cesaragsilva, please head over to the [Discuss forum](https://discuss.elastic.co/c/observability/apm) and post your question there. We use GitHub issues for confirmed bugs and enhancement requests, and you will reach a wider audience in the forum. Thanks!
