### ISSUE TITLE
APM dashboard shows maximum only 10 environments for a service.

### ISSUE THREAD

**Issue by saminnit** [elastic/apm-server#4005]
Hello
APM dashboard shows maximum only 10 environments for a service.
One of our services has more than 10 environments. Is there a way this limit can be opened?

**Comment by axw** [comment]
Hi @saminnit. We like to keep the Github repository for product issues - verified bug reports, pull requests, apm-server specific feature requests, etc., and have users ask questions about how to use the product or a particular feature in our discuss forums.

Please head on over to our official [Discuss forum](https://discuss.elastic.co/c/apm). You will reach a wider audience, get help from the broader community, and maybe learn how others solved problems similar to yours.
