### ISSUE TITLE
Report cgroup metrics for better monitoring support

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#4070]
When APM Server runs inside a container `cgroup` stats should be collected for stack monitoring. 

**Related issues:**
https://github.com/elastic/apm/issues/291
[Report cgroup stats if running in container](https://github.com/elastic/beats/issues/14691)
[Support CgroupsV2 in processors and Metricbeat](https://github.com/elastic/beats/issues/16958)

**Comment by axw** [comment]
https://github.com/elastic/beats/pull/21113 adds the cgroup metrics to libbeat. This is just reusing the existing cgroup support, and does not do anything towards cgroup v2 support.

**Comment by axw** [comment]
Opened https://github.com/elastic/kibana/issues/79050 to use this in Stack Monitoring

**Comment by simitt** [comment]
@axw I see this is assigned to you, are you planning on testing this? All of the PRs in stack monitoring are merged and should be available with the next BC. If not - no worries, I have tested the changes through when they got merged.

**Comment by axw** [comment]
@simitt no I just never unassigned myself. Seeing as you already tested, I think we're good here.
