### ISSUE TITLE
Collect stats on apm-server performance

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#408]
Get insights on CPU and RAM usage for apm-server.

**Comment by graphaelli** [comment]
Until we have a go APM agent ...

We can enable basic in-process memory stats by hooking into beats with something like https://github.com/elastic/apm-server/compare/master...graphaelli:apm-server-monitoring.  If that's interesting, we can [enhance](https://golang.org/pkg/runtime/#MemStats) the metrics beats collects or drop our own in.

If we prefer an out of process monitor, metricbeat with expvar seems the natural choice for users but our work is probably more along documentation lines.  That approach is reusable for cpu metrics.

Once we pick a direction, we can take performance baselines and start to automate regression tests.

As discussed offline, adding a spot in kibana's monitoring tab should at least be a longer term goal.  Looking forward to discussing all of this.

**Comment by ruflin** [comment]
+1 on hooking into the beats metrics. I assume the relevant base metrics will be the same for beats and apm-server. You might be interested in https://github.com/elastic/beats/pull/5545

**Comment by graphaelli** [comment]
goal for v6.2: understand key inputs driving hardware requirements and perform benchmark them
