### ISSUE TITLE
Connecting errors with transactions

### ISSUE THREAD

**Issue by watson** [elastic/apm-server#409]
It would be valuable if errors had a reference to the transaction that was active when the error occurred.

I suggest that we simply add an optional `transactionId` to the list of [error properties](https://github.com/elastic/apm-server/blob/master/docs/spec/errors/error.json) in the intake API. In the Elasticsearch model I imagine this should be stored as `transaction.id`.

If possible it would be nice to get this out in the data model before 6.2. We can always improve the usage of this in the UI later, but having it in the model before 6.2 would be beneficial.

Crazy bonus idea: This might even allow us to remove duplicate information from errors that are already stored on the transaction. But that would potentially have serious downsides once we introduce sampling, as the active transaction might not have been sampled.

cc @elastic/apm

**Comment by beniwohli** [comment]
I agree that this would be super helpful, even without exposing it in the APM UI in 6.2. If transactions, traces *and* errors all have a `transaction.id`, it will be super easy to correlate logs/errors with transactions.

A further problem with the crazy bonus idea (de-duplication) is that we can't do JOINs on elasticsearch, so if we e.g. de-duplicated the `context.request`, you couldn't easily filter errors on `request`-fields.
