### ISSUE TITLE
Trace standard?

### ISSUE THREAD

**Issue by draco2003** [elastic/apm-server#412]
Seems like there are a few different trace standards floating around.
Is there the potential for accepting different formats to the apm-server and translating to whats expected in ES for display purposes?

Is there schema/payload definition for the data being sent to the apm-server for coding new agents?

Example tracing formats that would be great to support:
General: http://opentracing.io/
More specific example for graphql: https://github.com/apollographql/apollo-tracing

**Comment by watson** [comment]
Good question @draco2003

Our current intake API is described here:
- Transaction API: https://www.elastic.co/guide/en/apm/server/current/transaction-api.html
- Error API: https://www.elastic.co/guide/en/apm/server/current/error-api.html

OpenTracing is indeed on our radar. But while we don't have any concrete plans, it should be possible to make a wrapper so that OpenTracing data can be sent to the APM Server.

**Comment by ekarlso** [comment]
I would look at OpenCensus / TraceContext if I where you, alot of work is being done there.

**Comment by roncohen** [comment]
@ekarlso thanks! We are aware and happy to see standardization in this space :)

**Comment by alvarolobato** [comment]
We are going to support distributed tracing soon, by means of TraceContext. We are already working on it on the server, agents and UI:
- https://github.com/elastic/apm-server/issues/968
- https://github.com/elastic/apm-agent-java/issues/111
- https://github.com/elastic/apm-agent-go/issues/99
- https://github.com/elastic/apm-agent-js-base/issues/32
- https://github.com/elastic/apm-agent-nodejs/issues/421
- https://github.com/elastic/apm-agent-ruby/issues/161
- https://github.com/elastic/kibana/issues/20760

We also plan to support OpenTracing by means of an API bridge on the agents, work has also started on some of them:
- https://github.com/elastic/apm-agent-java/pull/70
- https://github.com/elastic/apm-agent-go/issues/131
- https://github.com/elastic/apm-agent-js-base/issues/36
- https://github.com/elastic/apm-agent-nodejs/issues/431
- https://github.com/elastic/apm-agent-python/issues/249
- https://github.com/elastic/apm-agent-ruby/issues/167

As for OpenCensus, we are well aware about the efforts being done in their agents, but we don't have any specific plans yet, we will probably make a decision in the near future after Distributed Tracing and Open Tracing compatibility are released.

I'll close this issue, please follow the specific items in the linked issues.
Thanks
