### ISSUE TITLE
Remove references to untested configurations

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#413]
Because APM inherits so much infrastructure from beats, there are a number of unsupported/undocumented configuration options exposed in [apm-server.reference.yml](https://github.com/elastic/apm-server/blob/75c0e67ead2e3d8958b675ed4502eceb62b8c93c/apm-server.reference.yml).  They should be removed for now and re-added as development supports them.

Any documentation should be removed accordingly.

**Comment by jalvz** [comment]
close this?
