### ISSUE TITLE
Test/investigate Elasticsearch connection backoff improvements

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4138]
The Elasticsearch libbeat output has configuration for backing off on network errors. We should implement some tests (perhaps manual, but documented and repeatable) to verify that the server will not cause retry storms when Elasticsearch is unavailable.

**Comment by graphaelli** [comment]
Is the intention to allowlist this on ESS based on the results?  If not, can we include that as a goal?

**Comment by axw** [comment]
My intention is to make the default behave well enough that user intervention should be unnecessary, and make adjustments to code as necessary to get there. We can allow list existing config anyway in the interim.

**Comment by stuartnelson3** [comment]
closed by #4991
