### ISSUE TITLE
[Index Template] Use index.auto_expand_replicas '0-1'

### ISSUE THREAD

**Issue by pickypg** [elastic/apm-server#414]
The APM index / indices should consider using the `index.auto_expand_replicas` setting, set to `"0-1"` in favor of `index.number_of_replicas` set to `1` (or leaving it as the default).

Doing so will allow single node (e.g., dev) clusters to startup as green, which gives a better getting started experience.

**Comment by graphaelli** [comment]
related to elastic/beats#5921

**Comment by graphaelli** [comment]
We came to the same conclusion as beats (risk > reward) and will not be moving forward with this.
