### ISSUE TITLE
Validation for metadata.service not working

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#4141]
Turns out that the current way of writing the [validation rules](https://github.com/elastic/apm-server/blob/master/docs/spec/metadata.json#L11:L20) for `metadata.service.*` fields in the json-schema is not working properly. 
Instead of writing e.g. ` "properties.agent.required": ["name", "version"]` one would need to expand to objects like 
```
            "properties": {
                "agent": {
                    "type": "object",
                    "required": [
                        "name",
                        "version"
                    ]
                }
             }

```
or probably even better, just copy & paste the whole `service`  definition and adapt the required fields. 

Unfortunately this has also been missed in the `package_tests` as tests for metadata are very sparse. 

Following fields should be changed to the key being `required` and value not being allowed to be `null`: 
* `metadata.service.name` (currently key required but value allowed to be `null`) , 
* `metadata.service.agent` (currently key required but value allowed to be `null`), * `metadata.service.agent.name`,`metadata.service.agent.version`,`metadata.service.runtime.name`,`metadata.serice.runtime.version`, `metadata.service.language.name` (currently key not required and value allowed to be `null`)

Technically this is a bug and we should fix it; but it would potentially break agents that might not send the required fields.

I suggest to create a fix and ask agents to run their tests against the fixed json schema to see if any current agent versions would break when fixing this. 

The bug exists since `7.0`.

**Comment by simitt** [comment]
One more note - since we use the same schema validation for the metadata sent for `profiles` we would also need to check that this endpoint doesn't break.

**Comment by axw** [comment]
> One more note - since we use the same schema validation for the metadata sent for profiles we would also need to check that this endpoint doesn't break.

Profiling is still experimental, so no big deal if we have to update the Go agent to match the change.
