### ISSUE TITLE
limit sourcemap line length

### ISSUE THREAD

**Issue by clyfish** [elastic/apm-server#4149]
My coordinating node got OOM when query documents with huge lone lines in the sourcemap, so I want limit the line length of the sourcemap.

I've made a PR, but it's too hard for me to make the limit configurable.
So I closed the PR.
https://github.com/elastic/apm-server/pull/4143

**Comment by stuartnelson3** [comment]
closing this as we haven't been able to reproduce ourselves. If you can provide a way for us to reproduce it we'll take another look.

**Comment by clyfish** [comment]
After doubering the memory limit from `-Xmx3g -Xms3g` to `-Xmx6g -Xms6g`, our cluster is stable without OOM In recent months.
