### ISSUE TITLE
Change OS X to macOS in UA Parser

### ISSUE THREAD

**Issue by drewpost** [elastic/apm-server#4203]
Currently the RUM UA parser identifies Mac computer operating systems as "OS X" even though the branding changed to macOS in 2016. 

Can we please update the parser to save the OS family as "macOS"?

I'd also expect that selecting macOS in a UI would include results previously saved as OS X. Given the duration between this transition and now plus the high upgrade rate amongst apple users, I don't see the OS X users representing a meaningful volume of traffic in typical RUM data.

**Comment by simitt** [comment]
The UserAgent fields are populated by an [ingest pipeline](https://github.com/elastic/apm-server/blob/master/ingest/pipeline/definition.json#L36) making use of the [ES user_agent processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/user-agent-processor.html). Please open an enhancement request in ES for this, as the parsing happens in this processor.

**Comment by axw** [comment]
We _could_ introduce a post-processing step which changes the value, but then the OS family would be different in APM/RUM compared to other data (e.g. logs), potentially breaking correlations.

So, agreed, this should go upstream. Ultimately I think this requires a change in https://github.com/ua-parser/uap-core/blob/master/regexes.yaml.

However...

> I'd also expect that selecting macOS in a UI would include results previously saved as OS X.

Changing the value at indexing time won't help with this requirement. If you want to normalise new and existing data, you would either have to force everyone to reindex existing data (not great, and not something that we automate), or do this at query time (normalise in the UI; combine results for "OS X" and "macOS").

**Comment by axw** [comment]
@drewpost please reach out if you disagree with the above assessment and we can discuss options.
