### ISSUE TITLE
Remove field `system.process.cgroup.memory.stats.inactive_file.bytes`

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4206]
As discussed with @eyalkoren (who is going to update the spec), this field is not needed:

https://github.com/elastic/apm-server/blob/3d8578779134060e0244f4062be7ad81a7220f9f/model/metricset/_meta/fields.yml#L97-L100

Subtracting `inactive_file` from `usage` results in the working set (see https://github.com/google/cadvisor/issues/2149#issuecomment-455693608), but we only want to show usage.

**Comment by cauemarcondes** [comment]
@axw does it mean that I don't need to subtract this field anymore here https://github.com/elastic/kibana/pull/76768/files#diff-0957f863ca859891032e87ceb4652c8eR98?

**Comment by eyalkoren** [comment]
@cauemarcondes yes, sorry about that... 🙁
