### ISSUE TITLE
yum install of 7.9.1 apm-server, apm-7.9.1 template does not load

### ISSUE THREAD

**Issue by predogma** [elastic/apm-server#4229]
**APM Server version** (`apm-server version`): 7.9.1

**Description of the problem including expected versus actual behavior**:

related to https://github.com/elastic/sdh-apm/issues/83

Customer installed apm-server 7.9.1 using yum.  

- https://www.elastic.co/guide/en/apm/server/7.9/setup-repositories.html#_yum

Was unable to see visualizations, after bit of retrying to load templates, apm-7.9.1 template was never loaded.   Had to deleted the yum install used the rpm install and was able to load apm-7.9.1 template successfully. 

If we supply yum source, it may need to be fixed.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Install Elasticsearch/Kibana 7.9.1
 2. Install yum apm-server 7.9.1
 3. Edit apm-server.yml set output.elasticsearch host, user, password
4.  Setup templates
```apm-server -e```
5. Check Kibana for templates (missing apm-7.9.1)
```
GET _cat/templates/apm-*?v&s=index_patterns

name                   index_patterns           order version composed_of       
apm-7.9.1-error        [apm-7.9.1-error*]              2             
apm-7.9.1-metric       [apm-7.9.1-metric*]            2             
apm-7.9.1-profile      [apm-7.9.1-profile*]            2             
apm-7.9.1-span         [apm-7.9.1-span*]              2             
apm-7.9.1-transaction  [apm-7.9.1-transaction*]     2
```
6. missing apm-7.9.1, delete apm indices, delete apm templates, load again, still not seeing apm-7.9.1 templates
```
 apm-server -e setup -index-management -E setup.template.overwrite=true -E apm-server.ilm.setup.enabled=true
```
7. Uninstall yum apm-server 7.9.1.
8. Install using rpm, run setup command again, check Kibana > Dev Tools for templates see apm-7.9.1 templates 
```
GET _cat/templates/apm-*?v&s=index_patterns

name                   index_patterns           order version composed_of
apm-7.9.1              [apm-7.9.1*]                       1             
apm-7.9.1-error        [apm-7.9.1-error*]              2             
apm-7.9.1-metric       [apm-7.9.1-metric*]            2             
apm-7.9.1-profile      [apm-7.9.1-profile*]            2             
apm-7.9.1-span         [apm-7.9.1-span*]              2             
apm-7.9.1-transaction  [apm-7.9.1-transaction*]     2
```
9. complete service install (.NET) test and see data visualizations in Kibana > APM > (service)

**Provide logs (if relevant)**:

**Comment by axw** [comment]
@predogma Have you reproduced this issue? I just ran through the steps, and I could not; everything worked as expected:

```
GET _cat/templates/apm-*?v&s=index_patterns

name                  index_patterns           order version composed_of
apm-7.9.1             [apm-7.9.1*]             1             
apm-7.9.1-error       [apm-7.9.1-error*]       2             
apm-7.9.1-metric      [apm-7.9.1-metric*]      2             
apm-7.9.1-profile     [apm-7.9.1-profile*]     2             
apm-7.9.1-span        [apm-7.9.1-span*]        2             
apm-7.9.1-transaction [apm-7.9.1-transaction*] 2             
```

**Comment by predogma** [comment]
@axw thank you for confirming, we updated customer
