### ISSUE TITLE
[Jaeger Intake] Support tracer specific service.version tags

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#4319]
As a follow up on https://github.com/elastic/apm-server/pull/4061, also support process-/tracer specific tags for `service.version`.

E.g. when configuring a tag via `JAEGER_TAGS=service.version=x.y.z` for the instrumented service the tags should also be used for the `service.version`. In case both are set, the span specific tag should override the process/tracer specific one.

**Comment by axw** [comment]
Done in #4602
