### ISSUE TITLE
agentcfg: reduce number of Kibana queries by caching rules

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4350]
Currently the server makes individual queries to Kibana for each agent that requests config. The result (either 404 or 200) will be cached, per service name/environment pair for a configurable amount of time, defaulting to 30 seconds, after which the server will query Kibana again on the next agent request.

With this approach the number of requests to Kibana scales with the number of agents. This can lead to storms of requests (which we could -- but currently do not -- smooth out with a limiter).

As an alternative approach, we could have the server poll for the config rules set up in Kibana by the user. The server would store these in memory, and would match them against agent queries. With each request for config, the server would tell Kibana which rules have been matched (i.e. applied by an agent) in the most recent interval.

This alternative approach would have us make exactly one request to Kibana every configurable time period, regardless of how many agents there are in the system. The main downside I can see is that it would push knowledge of the rules to the server, which is currently encapsulated in Kibana.

**Comment by jalvz** [comment]
> As an alternative approach, we could have the server poll for the config rules

This was considered initially, but can't remember why we didn't go that way in the end... :thinking:

**Comment by axw** [comment]
We should also consider this while researching https://github.com/elastic/apm-server/issues/4573. If APM Agent config is added to the APM integration policy then it will get pushed down to APM Server. This would avoid the need for APM Server to query Kibana altogether.

**Comment by axw** [comment]
Closing in favour of https://github.com/elastic/apm-server/issues/5018
