### ISSUE TITLE
Add trace.id to span metrics

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-server#4371]
The service map is built by getting trace ids from a set of interesting spans (via a composite aggregation). This is not always reliable, because there could be a lot of spans and this request could time out. In most cases, span metrics will generate significantly less documents. If (some) trace IDs are recorded on a span metric,  we could use span metrics to get trace ids.

**Comment by dgieselaar** [comment]
I should clarify that I'm not 100% sure whether we should do this. It would certainly improve things, but not fundamentally resolve the issues with service maps.

**Comment by axw** [comment]
I'm closing this for now, as it's unclear if we should do it. If we conclude that relying on aggregated trace paths (https://github.com/elastic/apm/issues/364) are not viable, then we can come back and reopen this.
