### ISSUE TITLE
Invalid GitHub links in Events Intake API docs

### ISSUE THREAD

**Issue by ebeahan** [elastic/apm-server#4372]
**APM Server version** (`apm-server version`): `7.9` APM Server documentation

**Description of the problem including expected versus actual behavior**:

Noted while browsing through the Events API intake docs that the included GitHub links contain invalid URLs.

Example: https://www.elastic.co/guide/en/apm/server/current/span-api.html#span-schema

Links to: https://github.com/elastic/apm-server/blob/7.9.3/docs/spec/spans/span.json

Working link: https://github.com/elastic/apm-server/blob/v7.9.3/docs/spec/spans/span.json

**Comment by axw** [comment]
Thanks for raising this @ebeahan !
