### ISSUE TITLE
Implement the new indexing strategy

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#4378]
This is for integration with Elastic Agent, part of https://github.com/elastic/apm-server/issues/4004

The new indexing strategy is defined [here](https://docs.google.com/document/d/1y56a9fjkLi6Zen5qGC_JKYM9ljYpBA5W0fgdWilcwYc/edit?ts=5f6c1aab#).

### TL;DR
Index names will have 3 variable "chunks": `type` and `service name`, that come from ingested data; and `namespace`, that comes from Elastic Agent. 
`service name` and `namespace` are user-defined, while `type` is well known in advance and can be `logs`, `metrics`, or `traces`. 
We need to route the right events to the right indices based on those variables.

### Requires  

For `service name`:
https://github.com/elastic/package-spec/issues/64

For `traces` type:
https://github.com/elastic/package-spec/issues/68
https://github.com/elastic/kibana/issues/81451
https://github.com/elastic/elasticsearch/issues/64047

**Comment by axw** [comment]
For posterity, code for agent/fleet config: https://github.com/elastic/apm-server/compare/master...jalvz:integration-model?expand=1

**Comment by axw** [comment]
Existing integrations add the fields `data_stream.type`, `data_stream.dataset` and `data_stream.namespace` as fields to docs. We should do the same; this will also simplify the rest of this task, since we can define index selection rules based on these fields.

**Comment by axw** [comment]
Still TODO:

- [ ] system tests
- [ ] set `apm-server.data_streams.enabled` when in Fleet mode
- [ ] make `data_stream.namespace` configurable using config received from Elastic Agent
- [ ] improve config validation, to ensure things like `output.elasticsearch.indices` cannot be set in conjunction `apm-server.data_streams.enabled`

**Comment by axw** [comment]
Punting docs to 7.12+: https://github.com/elastic/apm-server/issues/4603
