### ISSUE TITLE
[CI] Kibana sync is failing 

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-server#4453]
The script `are_kibana_saved_objects_updated` fails on CI but the stage is set to not change the build result. @elastic/observablt-robots do we know if this is a real failure that must be addressed on our side?

**Build URL**: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/master/713/pipeline/116

>[2020-11-23T08:41:24.348Z] Error generating Index Pattern: field <processor.name> is duplicated, remove it or set 'overwrite: true', {Name:processor.name Type:keyword Description:Processor name. Format: Fields:[] MultiFields:[] Enabled:<nil> Analyzer: SearchAnalyzer: Norms:false Dynamic:{Value:<nil>} Index:<nil> DocValues:<nil> CopyTo: IgnoreAbove:0 AliasPath: MigrationAlias:false Dimension:<nil> ObjectType: ObjectTypeMappingType: ScalingFactor:0 ObjectTypeParams:[] Analyzed:<nil> Count:0 Searchable:<nil> Aggregatable:<nil> Script: Pattern: InputFormat: OutputFormat: OutputPrecision:<nil> LabelTemplate: UrlTemplate:[] OpenLinkInCurrentTab:<nil> Overwrite:false DefaultField:<nil> Path:processor.name}, {"aggregatable":true,"analyzed":false,"count":0,"doc_values":true,"indexed":true,"name":"processor.name","scripted":false,"searchable":true,"type":"string"}.
[2020-11-23T08:41:24.348Z] Makefile:194: recipe for target 'build/index-pattern.json' failed

**Comment by simitt** [comment]
@mdelapenya that actually behaves as expected. This test is an indicator for the server team to update the saved objects in Kibana before FF, but should not label the CI pipeline as failed in general as it is an external dependency that needs to be updated.

**Comment by mdelapenya** [comment]
Good to know. Do you know if it's possible to automate when kibana objects are updated, so that a PR is sent with the changes?

**Comment by simitt** [comment]
The Kibana objects need to be updated when the index pattern in APM Server updates. This is already a semi-automated process, there is a [script](https://github.com/elastic/apm-server/blob/master/script/update_kibana_objects.py) to update the kibana objects, we just don't create the PR automatically yet.

**Comment by mdelapenya** [comment]
Ok, let me open an internal issue to track how can we improve this part (if possible)

Will close this one and link the new ticket to this

Thanks!
