### ISSUE TITLE
Run apm-server Docker image with non-root user

### ISSUE THREAD

**Issue by caiconkhicon** [elastic/apm-server#4466]
This issue is created from this issue with apm-server Helm chart: https://github.com/elastic/helm-charts/issues/785#issuecomment-735385087

In short, I want to run apm-server in a Docker container with non-root user. However, because the binary is owned by root and cannot be ran by others:

```
-rwxr-x--- 1 root root 102M Nov 28 07:07 /usr/share/apm-server/apm-server
```

Thus, when running it as non-root, this error appears:

```
/usr/local/bin/docker-entrypoint: line 8: /usr/share/apm-server/apm-server: Permission denied
```

I checked the Dockerfile in this repository quickly but didn't understand much. Please have a look and fix it. My idea is to have the apm-server binary executable by all users (i.e. chmod 755)

**Comment by kuisathaverat** [comment]
Which version are you using? the 7.10.0 Docker image does not use a root user to run APM any more

```
>docker run -it --entrypoint /bin/id docker.elastic.co/apm/apm-server:7.10.0 
uid=1000(apm-server) gid=1000(apm-server) groups=1000(apm-server),0(root)
```

There is a way to disable the strict permissions check, you have to pass the parameter `--strict.perms=false`
https://www.elastic.co/guide/en/beats/libbeat/master/config-file-permissions.html#_disabling_strict_permission_checks

```
> docker run -it docker.elastic.co/apm/apm-server:7.10.0 --help
Usage:
  apm-server [flags]
  apm-server [command]

Available Commands:
  apikey      Manage API Keys for communication between APM agents and server
  export      Export current config or index template
  help        Help about any command
  keystore    Manage secrets keystore
  run         Run apm-server
  setup       Setup Elasticsearch index management components and pipelines
  test        Test config
  version     Show current version info

Flags:
  -E, --E setting=value              Configuration overwrite
  -N, --N                            Disable actual publishing for testing
  -c, --c string                     Configuration file, relative to path.config (default "apm-server.yml")
      --cpuprofile string            Write cpu profile to file
  -d, --d string                     Enable certain debug selectors
  -e, --e                            Log to stderr and disable syslog/file output
      --environment environmentVar   set environment being ran in (default default)
  -h, --help                         help for apm-server
      --httpprof string              Start pprof http server
      --memprofile string            Write memory profile to this file
      --path.config string           Configuration path
      --path.data string             Data path
      --path.home string             Home path
      --path.logs string             Logs path
      --plugin pluginList            Load additional plugins
      --strict.perms                 Strict permission checking on config files (default true)
  -v, --v                            Log at INFO level

```

**Comment by caiconkhicon** [comment]
@kuisathaverat : thanks for your reply. I am using 7.10.0 also. Yes I check the image and it is exactly as you said. However, when I deploy to K8S, something changes, so the user is not a part of the `root` group. Notice this: `groups=1000(apm-server)`, not `groups=1000(apm-server),0(root)`

```
bash-4.2$ /bin/id
uid=1000(apm-server) gid=1000(apm-server) groups=1000(apm-server)
bash-4.2$ cat /etc/group
root:x:0:apm-server
```

Maybe, you have more idea about this than me?

**Comment by kuisathaverat** [comment]
it is true in the helm chart by default is running as root, you can change it either add this to your helm-values.yml file, for more param check https://github.com/elastic/helm-charts/tree/master/apm-server

```
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 0
  privileged: false
```

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by axw** [comment]
It doesn't look like there's a bug here, so I'm going to close this.
@caiconkhicon if you have any further questions, please open a topic at https://discuss.elastic.co/c/apm

**Comment by caiconkhicon** [comment]
@kuisathaverat : yes I know it. However, that means I must use the gid 0? If I use gid 1000, the result is same as my comment above

**Comment by kuisathaverat** [comment]
> @kuisathaverat : yes I know it. However, that means I must use the gid 0? If I use gid 1000, the result is same as my comment above

if you want to change the guide to 100 you have to pass the `--strict.perms=false` argument to the APM Server to ignore the permissions of that file
