### ISSUE TITLE
Use _doc_count data type when indexing histograms 

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-server#4474]
In the APM app, we are currently using `value_count` aggregations for transactions, as transaction metric documents use histogram fields, meaning `doc_count` is no longer representative. ES now also has a `_doc_count` data type that allows us to specify how many documents a transaction metric document represents. ES will then use this field in its bucketing aggregations, removing the need for an additional `value_count` aggregation, which should speed up some of our queries and remove some complexity from our queries.

https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-doc-count-field.html

**Comment by axw** [comment]
I think this should be straightforward. I thought we would need to update betas and fields.yml; that is not the case.

To whomever implements this: I think we'll just need to add a field describing the doc count to `model.Metricset`, and use that to add a `_doc_count` field to the metric event docs that we index.

**Comment by jalvz** [comment]
Checked `_doc_count` field in metrics matched the number of docs running the aggregation:

```
GET apm-7.12.0-transaction/_search
{
  "aggs": {
    "txnames": {
      "terms": { "field": "transaction.name" } 
    }
  }
}
```
