### ISSUE TITLE
[Fleet] Add service name to datasets

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#4492]
- ~Depends on [spec definition](https://github.com/elastic/package-spec/issues/64)~
- Depends on [kibana support](https://github.com/elastic/kibana/issues/88307)
- Should rely on [existing code to sanitize service name](https://github.com/elastic/apm-server/blob/master/datastreams/servicename.go)

**Comment by axw** [comment]
Confirmed with BC2 and epr-snapshot, with opbeans-python and opbeans-go running:

`apm-integration-testing$ ./scripts/compose.py start 7.12 --bc=latest --apm-server-managed --with-elastic-agent --package-registry-url=https://epr-snapshot.elastic.co --with-opbeans-python --with-opbeans-go`

The "-" in the service names, which is a reserved character (data stream separator) is replaced with "_".

![image](https://user-images.githubusercontent.com/843579/109102005-d50f9280-7762-11eb-9b9f-41159754ea5f.png)
