### ISSUE TITLE
[Fleet] Test apm package

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#4493]
Some things to test/consider:

- Package versioning and upgrade
- Elastic agent integration (enrolling, upgrading, etc)
- Behavior in Docker
- Shipped assets (templates and pipelines)
- Missing features and workarounds for them (if any)
- Issues in the APM UI 
- Data streams coexisting with legacy templates
- Experimental data streams coexisting with GA data streams (ie. service name in datasets)
- Arbitrary apm policy edits, including compatible (eg. `secret_token`) and conflicting (eg. `ilm`) settings
- Use and reference more Elasticsearch outputs than the `default`, eg. for API Keys
- Central config 
- Sourcemaps
- To Be Updated...

**Comment by axw** [comment]
This issue is pretty open ended. I think we've tested everything we can, i.e. everything except sourcemaps and agent central config. Can we close this now?

**Comment by jalvz** [comment]
I was about to close it yesterday, but wanted to give it a final check once the last package version lands on `production`, so please leave it open for now

**Comment by axw** [comment]
@jalvz how about now?
