### ISSUE TITLE
[Fleet] Document apm fleet integration

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#4494]
## Overview

The apm package will be released in 7.12 as experimental. Package versions have a version independent of the stack; for this release we will ship 0.1.0. Later we'll probably align with stack versioning.

The documentation template file is at https://github.com/elastic/apm-server/blob/master/apmpackage/apm/0.1.0/_dev/docs/README.template.md

Run `make update` to generate the actual readme file that will be shown in the APM integration page: https://github.com/elastic/apm-server/tree/master/apmpackage/apm/0.1.0/docs 

### Usage

* apm-server will use data streams with a new indexing strategy. Indices are named after event type, service name, and  namespace. Details: https://docs.google.com/document/d/1y56a9fjkLi6Zen5qGC_JKYM9ljYpBA5W0fgdWilcwYc/edit?ts=5f6c1aab#

* The service name part of an index is case insensitive and with special characters removed.

* If customers don't use RUM, it is recommended that they run Elastic Agent (and therefore apm-server) on the edge machines.

* We do not support running apm-server under Elastic Agent standalone: https://www.elastic.co/guide/en/fleet/current/run-elastic-agent-standalone.html

* Sourcemaps need to be uploaded directly to Elasticsearch, not apm-server. In the future we might have something so users can upload sourcemaps to Kibana. 

### Limitations

* ILM: we install default ILM policies for all event types, but users need to query Elasticsearch directly to override them. Same for pipelines. 

* Can't use an Elastic Agent enrolled in a previous release: https://github.com/elastic/kibana/issues/85777

* No onboarding document: https://github.com/elastic/kibana/issues/86462

* For sourcemaps and agent central config features customer need to create api keys and them enter those api keys in the apm policy editor. This will be improved in future releases.

* Not all settings are supported, the whole list is at https://github.com/elastic/apm-server/blob/master/apmpackage/apm/0.1.0/manifest.yml#L28
Crucially, `mem.queue.*` settings are not supported (yet).  

## References 

7.12 meta issue: https://github.com/elastic/apm-server/issues/4558
GA meta issue: https://github.com/elastic/apm-server/issues/4636

**Comment by bmorelli25** [comment]
Related: Adding a Quickstart guide to the docs https://github.com/elastic/observability-docs/issues/421.

**Comment by bmorelli25** [comment]
Docs are going to be kinda all over the place while we figure out the best path forward. Here's what we're thinking of adding for `7.12`:

* _APM Server reference_
  * Top-level TOC heading for the APM integration:
    * About
    * Limitations
    * Datastream naming recommendations
    * How to configure (linking out to Fleet user guide)
* _Fleet user guide_
  * All integrations will have their configs defined in the Fleet user guide. For the `apm` input, we'll source the content from the `apm-server` repo so it's easy to update. Eventually, this will (hopefully) be generated.
  * Top-level TOC heading for Data streams
    * Elastic Agent data stream naming scheme information
    * Deleting data
* _APM integration_
  * Minor cleanup, including adding links to relevant documentation pages.
 
Pushed to next iteration:

* _Fleet user guide_
  * Adding a Quickstart guide to the docs elastic/observability-docs#421.

**Comment by bmorelli25** [comment]
All documentation for 7.12 has been added.
