### ISSUE TITLE
[packaging] Add arm64 Docker images

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#4502]
tracking https://github.com/elastic/beats/issues/18334

**Comment by axw** [comment]
While waiting for the required Beats bits, I wanted to check the latest apm-server on a linux-aarch64 machine. I fired up a `t4g.medium` on AWS, copied over a cross-build `apm-server-linux-arm64` binary, and it passed a smoke test. I just used `output.console` and sent a transaction to it, and it happily received and printed it out to the console.

**Comment by axw** [comment]
https://github.com/elastic/apm-server/pull/4695 brings us up to date with beats master, which now has support for building AArch64 Docker images. Next step is to update the release manager.

**Comment by axw** [comment]
Smoke-tested 7.13.0-40b6b79a (`docker.elastic.co/staging/apm-server:7.13.0-40b6b79a`), looks good.
