### ISSUE TITLE
[Elastic Agent] Only allow installing APM Server once per policy

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#4539]
Right now the APM integration can be added multiple times to a policy, which leads to an error when applying the policy to an Elastic Agent that tries to start two APM Server. 

<img width="914" alt="Screenshot 2020-12-15 at 11 59 24" src="https://user-images.githubusercontent.com/5555349/102206524-123ae700-3ecd-11eb-8bc6-8f62f76a24ee.png">

There is no use case coming to my mind where it would make sense to have multiple APM Servers running as subprocess of one Elastic Agent.

**Comment by ruflin** [comment]
@simitt Agree. We have for the endpoint integration that it can only be configured once per policy. We should do the same here. @jonathan-buttner Where did we set this?

**Comment by axw** [comment]
I believe I have stumbled across the solution, which is to set `multiple: false` in the package manifest.

**Comment by jalvz** [comment]
Tested trough the UI, works as expected
