### ISSUE TITLE
Update culprit for sourcemapping

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#455]
Update `error.culprit` with `filename` and `function` of stacktrace frame causing error after applying sourcemapping.
Take the information from the latest stack trace frame.

**Comment by simitt** [comment]
@jahtalab, @roncohen we do have `error.log.stacktrace` and `error.exception.stacktrace`. What should the logic be for deriving the culprit?

**Comment by jahtalab** [comment]
@simitt , Currently , the frontend agent only sends `error.exception` but we will send `error.log` eventually. I think `error.log` should have priority over `error.exception`. But if only one of them exist we should use it regardless of priority.
