### ISSUE TITLE
Logic for determining whether or not a field is an ECS field is wrong

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#4554]
All the fields that have `overwrite: true` set seem to be labeled as `ECS` field.

see https://github.com/elastic/apm-server/pull/4548

**Comment by jalvz** [comment]
For reference: https://github.com/elastic/beats/blob/master/libbeat/scripts/generate_fields_docs.py#L87-L93

We could reuse the logic in the package to fix this.

**Comment by axw** [comment]
I just found that the index templates are missing the APM-specific dynamic template for labels: https://github.com/elastic/apm-server/pull/4473#issuecomment-758527539. Maybe related to this issue?

**Comment by jalvz** [comment]
No, that is unrelated, good catch!
This if fixed by the beats/23188, closing
