### ISSUE TITLE
"Secret token" setting should have string type

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4572]
**APM Server version** (`apm-server version`):

7.11.0 BC1, integration 0.1.0-dev2

**Description of the problem including expected versus actual behavior**:

In the APM integration settings, the "secret token" setting is a toggle (bool). It should be a free-form text entry.

See also https://github.com/elastic/apm-server/pull/4542#issuecomment-748872123

**Steps to reproduce**:

 1. Install the "apm" integration in Fleet
 2. Navigate to the integration settings, expand "Colllect application traces"
 3. Secret token is a toggle, but should be a text entry like for "Host":

![image](https://user-images.githubusercontent.com/843579/102762022-ab2c9f00-43b2-11eb-9e27-25075cf2dcaa.png)

**Comment by jalvz** [comment]
Created an apm integration with version `0.1.0-dev.3`, this shows a text box now.
