### ISSUE TITLE
`labels_...` dynamic templates are repeated in index template

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4576]
**APM Server version** (`apm-server version`):

7.11 BC1

**Description of the problem including expected versus actual behavior**:

The dynamic templates for labels are repeated multiple times:

![image](https://user-images.githubusercontent.com/843579/102855344-70cd0b80-445f-11eb-8844-1c0f3a4d64b0.png)

There should be one of each, like in 7.10.

**Steps to reproduce**:

Run `apm-server export template` with APM Server 7.11 BC1.

There will be multiple entries under `dynamic_template` for `labels_string`, `labels_boolean`, and `labels_*`.

**Comment by jalvz** [comment]
This doesn't seem fixed in 7.12, I assume is because some backports are still open in libbeat?

**Comment by axw** [comment]
Indeed, the backports have not been merged.

**Comment by jalvz** [comment]
tested finally, all good
