### ISSUE TITLE
NOTICE has incorrect revision information for deps of deps

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#460]
While investigating #450, discovered that `NOTICE.txt` has revisions information from `vendor/vendor.json`for dependencies of dependencies.  Unfortunately those revisions are those of the `origin`, not the package being vendored.

eg, https://github.com/elastic/apm-server/blob/7bfb7ccd5065cc7abc123212d81513ececc69c33/NOTICE.txt#L34-L35

https://github.com/elastic/beats/commit/2463fd833024b2782962b18060ce642af2bdf1f4 is actually the commit in beats, which is the origin for that dependency.

**Comment by simitt** [comment]
@graphaelli I think this should be fixed with https://github.com/elastic/apm-server/pull/550 right?

**Comment by graphaelli** [comment]
https://github.com/elastic/beats/pull/6721 in to support this.  If that can't get in quickly, we can work around it but have to make a change in r-m

**Comment by graphaelli** [comment]
It's in, doing the necessary
