### ISSUE TITLE
[Jaeger] Document support for gRPC on the standard port

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4621]
When https://github.com/elastic/apm-server/pull/4618 lands, APM Server will serve Jaeger gRPC over the same port as the Elastic APM agent protocol (i.e. port 8200 by default).

~We should first have a discussion about how we want the UX to look around auth tags. I think we should probably replace `elastic-apm-auth` with two possible tags: `elastic-api-key` and `elastic-secret-token`. I'll mark this issue blocked until we have a decision.~ Let's stick with what we've got for now, we can always introduce separate tags later.

**Comment by bmorelli25** [comment]
More info: https://github.com/elastic/apm/issues/212#issuecomment-830976883
