### ISSUE TITLE
Jaeger does not strip 0 from trace/span IDs anlylonger

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-server#4661]
In elastic/apm-server#3849 I implemented support for stripping leading 0s from trace/span ids when they where created by Jaeger (Fixed #3837). Currently Jaeger is in the process of switching to full length ids (see jaegertracing/jaeger#1657).

Should the apm-server also switch to full length ids?

**Comment by tobiasstadler** [comment]
One could also introduce a configuration property in the jaeger configuration or add a new processor which does the stripping.

**Comment by axw** [comment]
@tobiasstadler thanks for raising this!

I was thinking about this recently, in a different context: distributed tracing across a mix of Jaeger clients, Elastic APM agents, and OpenTelemetry SDKs. The latter two will already record full trace IDs, whereas Jaeger trace IDs might be trimmed. In the case of inconsistent IDs, distributed tracing would fail to work across them. Given that only the Java client for Jaeger supports W3C TraceContext (https://github.com/jaegertracing/jaeger/issues/855) anyway, this hasn't been a problem so far, hence why we haven't done anything about it yet.

I think it would be a good idea to switch to full length IDs. I would prefer to just drop support for trimming and not add configuration. Jaeger support is still labelled as experimental to allow for changes like this. Would that pose a problem for you?

**Comment by tobiasstadler** [comment]
@axw That is fine for me
