### ISSUE TITLE
docs: known issue with cloud metadata in 7.9

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4665]
APM Server 7.9.x introduced support for cloud metadata (https://github.com/elastic/apm-server/pull/3729). Unfortunately the additions to the JSON Schema were too strict, and did not account for `null` values like we do for other properties. Sending a `null` value for `cloud.instance.name` (for example), would cause the payload to be rejected.

See https://discuss.elastic.co/t/apm-agent-is-not-working-on-fips-enabled-java-application/261815/10

This issue was resolved in 7.10.0 (https://github.com/elastic/apm-server/pull/4142). We should document this as a known issue, with upgrading to 7.10.0+ as the recommended solution.

**Comment by axw** [comment]
@bmorelli25 where would be the best place to document known issues like this?

**Comment by bmorelli25** [comment]
My suggestion would be adding a **Known issues** heading to the top of the [7.9 release notes](https://www.elastic.co/guide/en/apm/server/7.9/release-notes-7.9.html) with all of the details.
