### ISSUE TITLE
[OTLP] Document support for OTLP/gRPC on the standard port

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4678]
When elastic/apm-server#4503 is fully implemented, APM Server will serve OTLP gRPC over the same port as the Elastic APM agent protocol (i.e. port 8200 by default).

~Like in https://github.com/elastic/apm-server/issues/4621, I think we should first have a discussion about how we want the UX to look around auth tags, and again I'll mark this issue blocked until we have a decision.~ Let's stick with what we've got for now, we can always introduce separate tags later.

**Comment by cyrille-leclerc** [comment]
@bmorelli25 can we work together on this improvement of OTLP docs? I have prepared elements for this.

**Comment by bmorelli25** [comment]
👍 Sure! Fair warning: this issue wasn't in our 7.12 docs planning, so it hasn't been prioritized. I'd like to wrap @EamonnTP into the conversations as well in case he is able to pick it up before me.

**Comment by bmorelli25** [comment]
Hmmm. Ignore that comment. I mentioned it in https://github.com/elastic/observability-dev/issues/1279#issuecomment-749772370, but it never made it into the planning doc for some reason. Oh well. Between @EamonnTP and I, I'm sure we can get it done.

**Comment by EamonnTP** [comment]
@bmorelli25 I can pick this up. @cyrille-leclerc I'll put some time in your calendar to discuss more.
