### ISSUE TITLE
Document enabling frontend endpoint

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#468]
Also need to update `apm-server.reference.yml` as well

**Comment by jahtalab** [comment]
Related:
[Add description for sourcemapping.](https://github.com/elastic/apm-server/issues/421)

**Comment by simitt** [comment]
Ensure there is a route `https://www.elastic.co/guide/en/apm/server/current/frontend.html` as the packaged descriptions will link to this.

**Comment by jahtalab** [comment]
To be exact the docs will link to `https://www.elastic.co/guide/en/apm/server/6.2/frontend.html` instead of current!

**Comment by simitt** [comment]
PR #462
