### ISSUE TITLE
Limit cardinality of RUM data streams

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4709]
The new [APM indexing strategy](https://github.com/elastic/apm-server/issues/4378) incorporates the service name in the data stream's dataset. By doing this we effectively partition data by service name, enabling per-service policies (ILM, security, ...)

Because RUM is typically unauthenticated, this means that the cardinality of RUM data streams would be unbounded if we did not restrict the incoming service names. We should introduce a configuration that rejects data not matching a given service name.

**Comment by simitt** [comment]
We will also need to ensure this is allowed on ESS and ECE
