### ISSUE TITLE
[OpenTelemetry] Add support for OpenTelemetry Span Status

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#4716]
OpenTelemetry `span.status` is currently ignored when ingested in Elastic.

See OpenTelemetry Span Status specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status

Acceptance criteria: verify the following cases are properly rendered
* `span.status.StatusCode = Ok`
* `span.status.StatusCode = Unset`
* `span.status.StatusCode = Error`
* `span.status.StatusCode = Error` combined with `span.status.Description=this is an error`

**Comment by axw** [comment]
@cyrille-leclerc do you mean when using the exporter, or ingesting directly into APM Server?

We already do use the span status to set outcome and result. How did you test this?
