### ISSUE TITLE
[OpenTelemetry] Ensure Elastic APM supports the Otel Baggage API

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#4717]
OpenTelemetry has the concept of a Baggage API https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md

We have to ensure we properly support it in our visualisation. Note that we accept that services instrumented with Elastic APM agents may ignore and not forward the Baggage items they have received.

See also the [W3C Propagation format for distributed trace context: Baggage](https://w3c.github.io/baggage/)

**Comment by axw** [comment]
> We have to ensure we properly support it in our visualisation. Note that we accept that services instrumented with Elastic APM agents may ignore and not forward the Baggage items they have received.

@cyrille-leclerc baggage is for propagating information between instrumented applications. I don't think it's relevant at the server level.

**Comment by axw** [comment]
Please reopen if you think something needs doing in the server and let us know what that is.
