### ISSUE TITLE
[OpenTelemetry - Metrics]  `DoubleValueRecorder` and `LongValueRecorder` are silently ignored

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#4718]
`DoubleValueRecorder` and `LongValueRecorder` are silently ignored. We could document it and maybe emit a least one warning message per metric waiting to add support for it.

See problem description on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1610
Relates to https://github.com/elastic/apm/issues/377

**Comment by axw** [comment]
Closed by https://github.com/elastic/apm-server/pull/5239

**Comment by cyrille-leclerc** [comment]
Thank you @axw !!!
