### ISSUE TITLE
Keyword field for error group name

### ISSUE THREAD

**Issue by dgieselaar** [elastic/apm-server#4726]
Currently we use `error.log.message` or `error.exception.message` to display the title for an error group. When we need a list of error groups, we use a terms aggregation on `error.grouping_key`, and then a `top_hits` aggregation to get `error.log.message` and `error.exception.message`. Using a top_hits aggregation like this is slow, esp if there are a lot of different error groups. The faster alternative, a top_metrics aggregation only works on numeric fields and keywords.

My suggestion is to add `error.grouping_name` as a keyword field, so we A) have a more consistent way of displaying error group names, and B) we can use the top_metrics aggregation where it makes sense.

**Comment by axw** [comment]
`error.log.message` and `error.exception.message` may have high cardinality, e.g. they may be interpolated strings. Because of this we prefer not to use these fields in the grouping key calculation. Thus one grouping key may have two errors with different messages.

Will that be a problem? What would the new sequence of aggs using `top_metrics` look like?

**Comment by dgieselaar** [comment]
@axw that's similar to what we have today: group by error.grouping_key, then pick the most recent document to get the title. I don't expect `error.grouping_name` to be consistent for all error instances, just that it is consistently `error.log.message || error.exception.message` (in one field). But the performance improvement is more interesting to me.

Query (handrolled so might have an error):
```
{
  "aggs": {
    "error_groups": {
      "terms": {
        "field": "error.grouping_key",
        "size": 500
      },
      "aggs": {
        "latest": {
          "top_metrics": {
            "sort": { "@timestamp": "desc" },
            "metrics": [
              { "field": "error.grouping_name" }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by axw** [comment]
OK, so basically the same pattern as with `top_hits` but because we only need the latest doc we can use the more efficient `top_metrics`. I think this should be fairly straightforward then.
