### ISSUE TITLE
Add how to disable APM in Kibana UI to documentation

### ISSUE THREAD

**Issue by damianpfister** [elastic/apm-server#477]
Currently our documentation only gives details how to disable reporting, machine learning and graph but not APM in Kibana.

As this was asked of us by a customer recently I had to obtain the following from the APM dev team to resolve the issue.

Add the following to kibana.yml:
`xpack.apm.ui.enabled: false`

**Comment by beniwohli** [comment]
There's a similar setting for ML, which is documented here: https://github.com/elastic/x-pack-kibana/blob/master/docs/en/settings/ml-settings.asciidoc#general-machine-learning-settings

Guess we should follow that lead and document it in x-pack-kibana as well

**Comment by jakommo** [comment]
Fixed by https://github.com/elastic/x-pack-kibana/pull/3767
