### ISSUE TITLE
docker.elastic.co/apm/apm-server:7.11.1 report wrong version 

### ISSUE THREAD

**Issue by jmlrt** [elastic/apm-server#4791]
**APM Server version** (`apm-server version`): 7.11.1

**Description of the problem including expected versus actual behavior**:

`docker.elastic.co/apm/apm-server:7.11.1` report 7.11.0 version

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

```console
➜  ~ CONTAINER_ID=$(docker run -d docker.elastic.co/apm/apm-server:7.11.1)
➜  ~ docker exec $CONTAINER_ID curl localhost:8200
{
  "build_date": "2021-02-15T12:37:48Z",
  "build_sha": "e77061bb3aaedae5ae8dd0ca193eb662513aedde",
  "version": "7.11.0"
}
```

**Provide logs (if relevant)**:

```console
➜  ~ docker logs $CONTAINER_ID
{"log.level":"info","@timestamp":"2021-02-18T11:43:25.463Z","log.origin":{"file.name":"instance/beat.go","file.line":660},"message":"Home path: [/usr/share/apm-server] Config path: [/usr/share/apm-server] Data path: [/usr/share/apm-server/data] Logs path: [/usr/share/apm-server/logs]","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-02-18T11:43:25.464Z","log.origin":{"file.name":"instance/beat.go","file.line":668},"message":"Beat ID: 2d68839d-cc7b-4669-a7ba-66e69c730156","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-02-18T11:43:25.464Z","log.logger":"seccomp","log.origin":{"file.name":"seccomp/seccomp.go","file.line":124},"message":"Syscall filter successfully installed","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-02-18T11:43:25.464Z","log.logger":"beat","log.origin":{"file.name":"instance/beat.go","file.line":996},"message":"Beat info","system_info":{"beat":{"path":{"config":"/usr/share/apm-server","data":"/usr/share/apm-server/data","home":"/usr/share/apm-server","logs":"/usr/share/apm-server/logs"},"type":"apm-server","uuid":"2d68839d-cc7b-4669-a7ba-66e69c730156"},"ecs.version":"1.6.0"}}
{"log.level":"info","@timestamp":"2021-02-18T11:43:25.464Z","log.logger":"beat","log.origin":{"file.name":"instance/beat.go","file.line":1005},"message":"Build info","system_info":{"build":{"commit":"e77061bb3aaedae5ae8dd0ca193eb662513aedde","libbeat":"7.11.0","time":"2021-02-15T12:37:48.000Z","version":"7.11.1"},"ecs.version":"1.6.0"}}
...
```

**Comment by axw** [comment]
@jmlrt given that 7.11.1 is shipped, there's nothing we can do about that is there? We've already bumped 7.11 to 7.11.2, and that definitely reports the right version -- so if there's a 7.11.2 then that will be correct.

**Comment by jmlrt** [comment]
Is it something that could be added in automated tests in the future?

**Comment by axw** [comment]
Yes I think we could write an automated for this. The underlying issue that caused the version drift has been fixed in master, 7.x, and 7.12 with https://github.com/elastic/apm-server/pull/4725. It would still be useful to have a test though.

**Comment by axw** [comment]
@jmlrt opened https://github.com/elastic/apm-server/issues/4823. Is there an API that we can query for the expected version for a branch? I thought maybe I could use artifacts-api, but doesn't look like it knows that 7.x should be 7.13.0 now, for example.

**Comment by jmlrt** [comment]
You may use that:
```console
➜  curl https://snapshots.elastic.co/latest/7.x.json
{
  "version" : "7.12.0-SNAPSHOT",
  "build_id" : "7.12.0-7f1cfbda",
  "manifest_url" : "https://snapshots.elastic.co/7.12.0-7f1cfbda/manifest-7.12.0-SNAPSHOT.json",
  "summary_url" : "https://snapshots.elastic.co/7.12.0-7f1cfbda/summary-7.12.0-SNAPSHOT.html"
}%
```

**Comment by axw** [comment]
Closing this as there's nothing we can do, if you have any ideas about how to automate testing of this I'd appreciate your thoughts on #4823.
