### ISSUE TITLE
[fleet] Bundle the java agent attacher

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#4824]
We can do it manually or automate as part of the build / package process.

As we don't expect that the attacher will be updated often, it is probably easier do it manually. The attacher won't necessarily follow stack versioning. 

See https://github.com/elastic/apm-agent-java/pull/1667

**Comment by simitt** [comment]
@felixbarny and @jalvz let's figure out the details how we want to bundle this so we can work on it for 7.14.

**Comment by simitt** [comment]
@felixbarny can you provide details from where the java agent attacher can be pulled when bundling?

> We can do it manually or automate as part of the build / package process.
@jalvz maybe I am misunderstandind, but I'd like to avoid adding any manual steps. The java agent attacher should be part of the packaging process, used in the release process.

**Comment by jalvz** [comment]
The attacher lives in the java agent repo: https://github.com/elastic/apm-agent-java/tree/master/apm-agent-attach

Maybe just copying it to some folder in apm-server is enough for start, wdyt? 

But we need to get "notified" if there are important (or breaking) changes in the attacher that need to be aware of...

**Comment by felixbarny** [comment]
Two options: you can either download the attacher from [maven central](https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:apm-agent-attach-cli), or we just commit the attacher binaries to the APM Server GitHub repo.

**Comment by stuartnelson3** [comment]
@simitt @axw preference on how to manage this? I'd be inclined to add it as a manual release step, similar to updating beats.

**Comment by axw** [comment]
Updating manually sounds fine to me.

I'd prefer not to commit the jar to the repo. We could instead inject them into the packages, fetching them at package build time: https://github.com/elastic/apm-server/blob/67548186320f36367c3b641761657620107cbd97/magefile.go#L372

WDYT @stuartnelson3?

**Comment by stuartnelson3** [comment]
That sounds fine to me, then we just update the fetch url in the magefile

**Comment by stuartnelson3** [comment]
closed in #6593
