### ISSUE TITLE
[fleet] Support java attacher settings via apm-server.yml 

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#4829]
Mainly: java agent version, and include/exclude rules.

**Comment by felixbarny** [comment]
As a first step, this could be implemented as regular `apm-server.yaml` settings. In a second step, we could expose that part of the settings in the Fleet policy editor (depends on https://github.com/elastic/kibana/issues/89987).

**Comment by jalvz** [comment]
To make it configurable it needs to be in the policy editor, users can't edit apm-server.yml by hand.

**Comment by axw** [comment]
I think what @felixbarny meant (correct me if I'm wrong) is that we can do that later. Support it via `apm-server.yml` to start with would enable us to test the feature without waiting for the policy changes.

**Comment by simitt** [comment]
Updated the title to reflect that his issue is only concerned with adding the include/exclude rules to the `apm-server.yml` and support them in the server.
