### ISSUE TITLE
[docs] Add code examples on how to create APM Server security resources

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-server#4842]
[Here](https://www.elastic.co/guide/en/apm/server/7.10/feature-roles.html) in the guide there is a list with the security resources that are needed for APM Server to communicate with the stack when Security is enabled.

- Setup role: To set up index templates and other dependencies.
- Writer role: To publish events collected by APM Server.
- Monitoring role: One for sending monitoring information, and another for viewing it.
- API key role: To create and manage API keys.
- Central configuration management role: To view APM Agent central configurations.

But there are no code examples (cURL) that simplifies the creation of those resources.

**Comment by axw** [comment]
We suggest users create API Keys through Kibana now. For users that want to create them through an HTTP API, there are docs with examples at https://www.elastic.co/guide/en/kibana/current/agent-key-api.html
