### ISSUE TITLE
Align package version with Stack version

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4898]
We will publish new APM integration packages along with the stack.

Not yet clear if we would need to do this on *every* stack release (e.g. patch releases). The main point is that any new package should be published at the same time as a stack release, and have the same version as that stack release.

**Comment by simitt** [comment]
related https://github.com/elastic/kibana/issues/93393

**Comment by axw** [comment]
Done in https://github.com/elastic/apm-server/commit/0502a9b9076d795c727ee31dc4eab3ab23e96167
