### ISSUE TITLE
Apply geo-ip data to mobile trace data

### ISSUE THREAD

**Issue by bryce-b** [elastic/apm-server#4935]
Related: elastic/apm-server#2262
Due to platform constraints, the easiest way to capture geo-ip data is to use the host ip address available in the header data when connecting to the apm server. According to elastic/apm-server#2262 this will be `host.id`. For context, the iOS agent utilizes the otelp interface on the apm server.

**Comment by axw** [comment]
Thanks @bryce-b. If we record the IP in `client.ip` then it'll just work.

@stuartnelson3 is looking at a tangentially related issue that will make this possible: https://github.com/elastic/apm-server/pull/4934.

Once that change is in it's a matter of us identifying requests over OpenTelemetry which represent clients (end users), and filling in `client.ip` using the client address. The existing ingest pipeline will pick that up and perform geoIP enrichment.

**Comment by axw** [comment]
> it's a matter of us identifying requests over OpenTelemetry which represent clients (end users)

We can do this by looking for `agent.name: iOS/swift`
