### ISSUE TITLE
CI: automate update-beats

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4941]
Currently we need to periodically run `make update-beats` to keep apm-server up to date with libbeat and beats packaging. I'd like this to be automated to avoid prolonged version skew. There's some overlap here with https://github.com/elastic/apm-server/issues/4240.

The way I imagine this working is to have a Jenkins job that:
 1. Runs `make update-beats`
 2. Stages the changes to `go.mod`, `go.sum`, `NOTICE.txt` ~and `testing/environments` (mirrored from libbeat)~
 3. Creates a PR with auto-merge and delete-on-merge bits set

I think (1) and (2) should be taken care of by https://github.com/axw/apm-server/commit/54cbe197056a7fc633bf03c366ffb5f32f5e8b66.

For (3) we should be able to use `githubCreatePullRequest`, but I'd really like this to be auto-merged and branches deleted automatically. I think that might require migrating to use the official GitHub CLI (`gh`, cli.github.com) instead of `hub`, which provides access to auto-merge/delete through `gh pr merge --auto --delete-branch`.

**Comment by v1v** [comment]
> For (3) we should be able to use githubCreatePullRequest, but I'd really like this to be auto-merged and branches deleted automatically. I think that might require migrating to use the official GitHub CLI (gh, cli.github.com) instead of hub, which provides access to auto-merge/delete through gh pr merge --auto --delete-branch.

There is a CI pipeline step for the `gh` -> https://github.com/elastic/apm-pipeline-library/blob/master/vars/gh.txt
`gh(command: 'pr merge --auto --delete-branch')`

**Comment by v1v** [comment]
PRs:
- https://github.com/elastic/apm-server/pull/5690 to create the Job in the Jenkins UI
- Another PR will be created with the whole automation.

The idea to split in two different PRs will help with the development process:
- JJBB are nothing but a change in the UI.
- Pipelines can be tested on a PR basis if the above already exists.

But my local environment is not in a good shape so, I'm iterating with the above approach for now
