### ISSUE TITLE
[OpenTelemetry] functional and stress-testing in ESS

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4948]
When the new OTLP intake is accessible in ESS, let's perform functional and stress testing to ensure it's ready for prime time.

At a minimum we need to test:
 - auth works as expected
 - data shows up in the UI as expected
 - throughput is acceptable, for some as yet undefined value of acceptable

**Comment by axw** [comment]
> throughput is acceptable, for some as yet undefined value of acceptable

I think we're good here.

I've created a 7.12.0 ESS cluster in GCP australia-southeast1, and a GCP VM in the same region for sending load. The ESS cluster has the following configuration:
 - Elasticsearch in 2 zones, 8GB RAM (gcp.data.highio.1)
 - APM Server in 1 zone, 512MB
 - All default settings.

I generated load with a simple custom Go program, using opentelemetry-go, that sends spans in batches and blocks when the queue is full. No additional resource attributes are defined, so the spans are as empty as they could be.

I ran a handful of tests, and saw throughput of approximately 16K events/s in each run (each run lasting ~8-10s). That's the time for the load generator to complete. I've also included a `extended_stats` aggregation over `event.ingested - @timestamp` to get an idea of the end-to-end ingestion lag, which includes time queued in the client's batcher.

```
GET /apm-7.12.0-transaction/_search
{
  "size": 0,
  "aggs": {
    "lag": {
      "percentiles": {
        "script": {
          "source": """
          doc['event.ingested'].value.millis - doc['@timestamp'].value.millis
          """
        }
      }
    }
  }
}

{
  "took" : 1952,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "lag" : {
      "values" : {
        "1.0" : 108.07755311452931,
        "5.0" : 305.65889988044853,
        "25.0" : 983.2756512743795,
        "50.0" : 1226.6955514188735,
        "75.0" : 1466.607917906349,
        "95.0" : 1905.329799431822,
        "99.0" : 2182.535828622067
      }
    }
  }
}
```

**Comment by axw** [comment]
Tested auth:
 - with no `Authorization` header: `rpc error: code = Unauthenticated desc = unauthorized`
 - with `Authorization: nonsense`: `rpc error: code = Unauthenticated desc = unauthorized`
 - with `Authorization: Bearer invalid`: `rpc error: code = Unauthenticated desc = unauthorized`
 - with `Authorization: ApiKey invalid`: `rpc error: code = Unauthenticated desc = unauthorized`
 - with `Authorization: Bearer <secret-token>`: (success)
 - with `Authorization: ApiKey <api-key>`: (success)

**Comment by axw** [comment]
> data shows up in the UI as expected

Functionally working as well as non-ESS, which is to be expected. I haven't found anything concerning, so I'm going to close this and move on to working on general improvements (RPC conventions, better auth errors, etc.)

**Comment by axw** [comment]
Adding this to the test plan to run some more tests after feature freeze.

**Comment by simitt** [comment]
@axw have you (had) time to do more testing on this or should someone else pick it up?

**Comment by axw** [comment]
@simitt I think it would be beneficial to have someone other than me pick this up, so we potentially cover more ground and test in different ways. I haven't had time to do any more.

**Comment by simitt** [comment]
Tested against ESS - generally seeing same behavior for `7.13-snapshot` as with `7.12`; 
* auth handling works as expected - seeing `rpc error: code = Unauthenticated desc = unauthorized` if unauthorized, otherwise events are accepted
* when queue is full/APM Server is under too much load, seeing grpc errors `exporter disconnected` (same behavior vor `7.12` or when running via opentelemetry-exporter-collector).
* data in UI showing up
