### ISSUE TITLE
Registry doesn't serve APM package

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#4951]
The APM package `0.1.0` was added to the `production` branch of the package-storage recently, see [production/packages/apm/0.1.0](https://github.com/elastic/package-storage/tree/production/packages/apm/0.1.0).

Sending a request to fetch the package returns an empty result:
```
curl -i "https://epr.elastic.co/search?package=apm&experimental=true"
```

while the same request against the snapshot URL returns the last `dev` version. 
```
curl -i "https://epr-snapshot.elastic.co/search?package=apm&experimental=true"
```

**Comment by simitt** [comment]
@ycombinator @mtojek I was under the impression that the package would be served from the production registry with https://github.com/elastic/package-storage/pull/1012 being merged. Looking at the [elastic-package-promote](https://github.com/elastic/elastic-package#elastic-package-promote), the command would basically also open PRs to add/remove packages, so I _thought_ nothing else should be involved on our side. Could you please provide guidance?

**Comment by mtojek** [comment]
> Could you please provide guidance?

Yes, please.

If you look at the CONTRIBUTING guide available here: https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md , please notice the section: https://github.com/elastic/integrations/blob/master/docs/developer_workflow_promote_release_integration.md . There is a step which mentions "1-click Jenkins form" - it's responsible for recycling the Kubernetes environment with a new storage's image. I suspect that it hasn't been clicked (triggered) by developer owning the process.

If the release operation is finished (we should get a notification), but you can't see the APM package, then it's a probably a bug and we can take it from there.

**Comment by axw** [comment]
@mtojek thanks for the pointer. I've just kicked off a new production rollout.

**Comment by mtojek** [comment]
Thank you @axw for the action. It seems that the package has been published: https://epr.elastic.co/search?package=apm&experimental=true

**Comment by simitt** [comment]
Thank you both!
