### ISSUE TITLE
Use -buildmode=pie (position independence executable)

### ISSUE THREAD

**Issue by ruflin** [elastic/apm-server#4960]
I'm not sure if apm-server would get this automatically if beats is adjusted https://github.com/elastic/beats/issues/24323 or if it needs to be added manually, so filing this here too. Check https://github.com/elastic/beats/issues/24323 for more details.

**Comment by axw** [comment]
It should be automatic, but let's leave this open so we can use it for tracking on our test plan. Thanks.

**Comment by axw** [comment]
Tested with https://staging.elastic.co/7.13.0-100107e6/summary-7.13.0.html, Linux and macOS x86_64 binaries are PIE. Go 1.15 builds Windows binaries as PIE by default, no change there.
