### ISSUE TITLE
[OpenTelemetry] Mapping of `transaction.type` is different when using Otel Collector exporter and APM Server OTLP intake

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#5006]
The APM Server OTLP intake  OpenTelemetry Collector defaults the transaction type to `custom` when the OpenTelemetry Collector Exporter for Elastic defaults it to `unknown`.

It breaks the Elastic redirection URL of the Jenkins OpenTelemetry plugin as Kibana requires the `&transactionType=...` http parameter to be passed. See [jenkins/opentelemetry-plugin: Elastic Observability Redirection URL is broken #51](https://github.com/jenkinsci/opentelemetry-plugin/issues/51).

Could the easiest fix be to change the default on the OpenTelemetry Collector Exporter for Elastic?

APM Server OTLP Intake:

https://github.com/elastic/apm-server/blob/8c7ccaf0fb3300f8f53f8bb548a096e934436e3c/processor/otel/consumer.go#L323

OpenTelemetry Collector Exporter for Elastic:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/716e0a0ccc722e2442a0374bd4f03fac35ce3062/exporter/elasticexporter/internal/translator/elastic/traces.go#L197

```go
tx.Type = "unknown"
if context.model.Request != nil {
   tx.Type = "request"
    ...
```

**Comment by axw** [comment]
I suggest that we don't go changing the fallback transaction type, but instead:
 1. find a way to explicitly set a transaction type relevant to the operation
 2. see if we can update the APM app in Kibana to make the `transactionType` parameter optional (seems to me if you have a known unique transaction name, the type shouldn't be required)

(1) can be done when sending spans directly to APM Server (or Collector to APM Server using otlp exporter) by setting a "type" span attribute. e.g. `type=job`
(2) will make it work regardless of whether data is being sent directly to APM Server, or if the Collector exporter is being used.

**Comment by cyrille-leclerc** [comment]
@axw I used successfully the span.attribute `type=job` with the Elastic OTLP intake but unfortunately, it's ignored by the Otel Collector exporter for Elastic that reports `transaction.type=unknown` even when I define `type=job`

**Comment by axw** [comment]
@cyrille-leclerc ah yes indeed, I think the "type" attribute was added back when we introduced support for Jaeger in APM Server, before adding support for OTLP. I suppose we can create a PR to add that to the exporter. Longer term I hope we can just point users at APM Server's OTLP intake, and not try to keep them in sync?

I still think it would be ideal if the UI would allow you to not have to know the transaction type ahead of time. I asked the UI team, and @ogupte said:

> it’s required now because all the charts and metrics don’t make any sense when you don’t filter by transaction type. we could choose the top one but it would block loading the rest of the page.

I tend to think that would be OK, but I don't know all the details. I wonder if we couldn't use a terms aggregation on `transaction.type` with size 1, which would scope everything to transaction type with the greatest number of events.

**Comment by cyrille-leclerc** [comment]
>  Longer term I hope we can just point users at APM Server's OTLP intake, and not try to keep them in sync?

+100%. My ideas are that 
* as soon as the Elastic OTLP intake is marked Generally Available, we deprecate the OpenTelemetry Collector exporter for Elastic.
* in the meantime, our rule is to not add features to the OpenTelemetry Collector exporter for Elastic

The reason why I'm asking for `type` to work when using the OpenTelemetry Collector Exporter for Elastic is that we want to remove the beta status of the [jenkinsci/opentelemetry-plugin/](https://github.com/jenkinsci/opentelemetry-plugin/) anytime soon.

>> it’s required now because all the charts and metrics don’t make any sense when you don’t filter by transaction type.

I have to learn where we differentiate transaction types. FWIU, it's used with some Ruby libraries to mark `worker` activities, I'm not clear where else it's used.

**Comment by cyrille-leclerc** [comment]
The solution we found in the Jenkins Otel Plugin is to set the otel trace attribute`type` to `unknown` so that the Elastic transaction type is always `unknown`, whatever the trace goes through the Otel Collector Exporter for Elastic or through the Elastic APM Server OTLP Intake.

Once the Elastic APM Server OTLP Intake goes GA, we will get back to a transaction type `job` rather than `unknown` asking users to stop using the Otel Collector Exporter for Elastic and do plain OTLP until Elastic Observability backend (APM Server).
