### ISSUE TITLE
[RUM] Add session information to Transaction schema

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#5032]
As part of [providing insight into User Sessions](https://github.com/elastic/apm-agent-rum-js/issues/998) for Real User Monitoring, APM server should accept session information on Transaction documents. 

The following fields should be added to Transactions:

```
{
    "session": {
        "type": "object",
        "properties": {
            "id": {
                "type": "string",
                "description": "The User Session ID"
            },
            "sequence": {
                "type": "number",
                "description": "The sequence of the Transaction within the session",
                "minimum": 1
            }
        }
    }
}
```

The `session.id` is based on a [proposed ECS field](https://github.com/elastic/ecs/pull/935) (currently in Stage 2).
The `sequence` however is specific to RUM use-case and is added to enable faster delivery of dashboards (we might remove this in the future)

Note: There doesn't seem to be an OpenTelemetry equivalent for these fields. Therefore, users would have to use custom
[attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-and-label-naming.md) to capture session information. We can work with OpenTelemetry team to define a convention here though.

cc @paulb-elastic , @andrewvc , @graphaelli

**Comment by jahtalab** [comment]
I've updated the description to address OpenTelemetry question.

**Comment by axw** [comment]
Thanks @jahtalab! For sequence, should we be recording that as `session.sequence` in Elasticsearch? As a long? There's an existing [`event.sequence`](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-sequence) field in ECS, but I'm not sure if the semantics are the same -- so perhaps better not to use that?

Any preference for shortened field names for RUMv3?

**Comment by jahtalab** [comment]
I think the `session.sequence` is similar to `event.sequence`, but only defines the sequence for a particular session. I'm not sure if `event.sequence` can be used here. But, the description for `event.sequence` is broad enough to include the session use-case. The only concern is that if the `event.sequence` might be used for a different purpose. 

Re. shortened fields, I've used the following in the [RUM agent PR](https://github.com/elastic/apm-agent-rum-js/pull/1005):
- `ses` for `session`
- `seq` for `sequence`
- `id` is the same

**Comment by axw** [comment]
> I think the session.sequence is similar to event.sequence, but only defines the sequence for a particular session. I'm not sure if event.sequence can be used here.

OK, makes sense - let's just call it `session.sequence` in the docs for now then.
