### ISSUE TITLE
Support for user.domain

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-server#5064]
ECS has a field user.domain. Can we please add support for ingesting this field?

**Comment by axw** [comment]
@tobiasstadler certainly. Is this for the Jaeger intake, Elastic APM agents, or OpenTelemetry? We can update APM Server to set this field in Elasticsearch docs, but how will you be sending the data to APM Server?

**Comment by tobiasstadler** [comment]
I will be using the elastic apm java agent to send the data to to the server.
