### ISSUE TITLE
monitoring: report configured queue.mem.*, output.elasticsearch.workers, output.elasticsearch.bulk_max_size

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5092]
Tracking issue for testing for https://github.com/elastic/beats/issues/22215 in apm-server

**Comment by simitt** [comment]
Tested with BC 4: 
The metrics are indexed, but they are missing in the template. 
@axw is that expected?

**Comment by axw** [comment]
That slipped my mind. I think they should be part of the template.

**Comment by simitt** [comment]
Created https://github.com/elastic/beats/issues/25628 as a follow up; I'd not call this a critical bug.
