### ISSUE TITLE
The index template(apm-7.4.0*) is overridden and restored, include index setting and mappings.

### ISSUE THREAD

**Issue by Holyfiled** [elastic/apm-server#5112]
**APM Server version** (`apm-server version`):
7.4.0
**Description of the problem including expected versus actual behavior**:
1. Template section keep default values in apm-server.yml, it's never changed:
#setup.template.enabled: true
#setup.template.overwrite: false
2. When the template(apm-7.4.0*) is auto loaded into the ES, I modify the index settings, mainly including:
"number_of_shards" : "1" to "number_of_shards" : "15"
"refresh_interval" : "5s"  to "refresh_interval" : "60s"
3. After some days, i found that the template(apm-7.4.0*) was overwritten and restored, all index settings was restored,
"number_of_shards" : "15" to "number_of_shards" : "1"(dafult)
"refresh_interval" : "60s"  to "refresh_interval" : "5s"(dafult)
4. I confirm that the template is not deleted or modified artificially，and ES server is not interrupted or restarted; 
5. So i want to know when the template(apm-7.4.0*) will be overwritten and restored.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by Holyfiled** [comment]
![image](https://user-images.githubusercontent.com/38369051/115024542-cfc4fd80-9ef2-11eb-93f6-50ef470f8a9b.png)

**Comment by axw** [comment]
This sounds like it might be related to the ILM feature. There were some changes made in 7.5 related to overwriting templates when ILM is either explicitly or automatically enabled: https://github.com/elastic/apm-server/pull/2877

I suggest upgrading to a more recent version. If you still observe the issue, then please open a topic at https://discuss.elastic.co/c/observability/apm/58 so someone can try and find out the cause.
