### ISSUE TITLE
Mobile spans don't line up with server side spans

### ISSUE THREAD

**Issue by bryce-b** [elastic/apm-server#5173]
<img width="1843" alt="Screen Shot 2021-04-26 at 10 44 06 AM" src="https://user-images.githubusercontent.com/75274611/116285620-27f5ce00-a743-11eb-9785-02f536a96063.png">

The timestamps generated on the mobile device can be significantly different than the server-side timestamp. 

It sounds like this issue has already been identified and solved for the rum agent. (per @axw "[Rum uses] the timestamp the event payload was received from the agent[...]") That same logic should be applied to mobile transactions, as well.

A few questions: 
1. Mobile data is sent using the OpenTelemetry Protocol. Will that cause issues with this solution?
2. Will all spans in the mobile transaction need to be "re-tuned" based off the server side timestamp?

Let me know if there is any additional information needed.

**Comment by felixbarny** [comment]
It works for RUM as it sends the spans within the transaction document. Implementing a similar functionality on top of OTLP would be a bit more challenging as events can be interleaved.


Potential issues
* Is it guaranteed that all spans of a single transaction are sent to the same server if there's a load balancer in front of multiple APM Servers? Not quite sure how load balancing works for gRPC - when and how often are new requests started.
* Spans may start after their parent ends (example: button click creates a short span that schedules a background action)


Solution approaches
* APM Server could buffer spans sent by mobile agents until the corresponding transaction is received and then adjust the span and transaction timestamps accordingly.
* An alternative that also accounts for spans that end after their transaction ends: The first span of a trace that's received by APM Server determines the offset (arrival time-span duration). The offset is stored in a map that has the trace id as a key. The key is cleared either if a span has no parent id (root span) or after a timeout.
* The mobile agent buffers spans (on disk or in memory) until all spans of a trace are ended. It then sends all spans in batch to APM Server. The mobile agent could also add a custom attribute to the root span to indicate for how long it has been queued. Open question: can we ensure it's sent to the same Server?
* Send data using the RUM intake API protocol.

**Comment by axw** [comment]
We also have some outstanding issues with how timestamps are dealt with in RUM: https://github.com/elastic/apm-server/issues/1830. Ideally I'd like to come up with a solution which addresses both.

I think we could deal with this is by sending an additional timestamp (set to the current time when the request is sent), independent of the event timestamps, in each request to the server. When the server receives the request it will work out the difference between the client-reported timestamp and the time at which the request was received; this delta will be applied to every event timestamp in the request. That should address the issue of RUM transaction timestamps, and would also work with OTLP.

How exactly we send the timestamp is TBD. In theory we could use the "Date" HTTP header, but it is probably no good for RUM (not allowed in `fetch`) and may not survive proxies. We would probably instead need to encode the timestamp in metadata for RUM, and perhaps as a resource attribute for OTLP.

**Comment by axw** [comment]
There's an issue for this in OpenTelemetry: https://github.com/open-telemetry/opentelemetry-specification/issues/1270

**Comment by bryce-b** [comment]
Let me know if any coordinating efforts are needed with the iOS agent.

**Comment by bryce-b** [comment]
Here's a link to a rudimentary test app for generating iOS data: https://github.com/elastic/ios-integration-testing
It requires MacOS. 
the apm server ip/url can be set in this file : https://github.com/elastic/ios-integration-testing/blob/master/Shared/Model/ios_integration_testingApp.swift
Let me know if you need help getting it set up.

**Comment by felixbarny** [comment]
As for the next steps... Could we use a custom resource attribute (for example `telemetry.elastic.export_timestamp` that captures the timestamp when the batch has been sent off for now and align with https://github.com/open-telemetry/opentelemetry-specification/issues/1270 once it’s resolved?

**Comment by axw** [comment]
SGTM. How about this specifically:

- resource attribute name: `telemetry.sdk.elastic_export_timestamp`
- type: int64
- value: nanoseconds since epoch (like OTel [span timestamps](https://github.com/open-telemetry/opentelemetry-proto/blob/795cc815ce9bb438b46a4a7f6ecb465b52d50935/opentelemetry/proto/trace/v1/trace.proto#L145-L151))

@bryce-b does that work for you?

**Comment by bryce-b** [comment]
I'll look into this today.

**Comment by bryce-b** [comment]
Here's a PR with that attribute added : https://github.com/elastic/apm-agent-ios/pull/36

**Comment by axw** [comment]
@bryce-b I don't have macOS, so I can't run your test app. The server changes are merged on master, and the backport to 7.x is running through CI now. Can you please take care of testing it with your changes?

**Comment by bryce-b** [comment]
I pulled down `master` which appears to have the change `processor/otel: adjust timestamps for mobile (#5433)`

Here's the data it produced : https://edge-oblt.elastic.dev/app/apm/services/ios-integration-testing/transactions/view?rangeFrom=2021-06-16T22:21:32.694Z&rangeTo=2021-06-16T22:36:34.722Z&environment=&transactionName=GET%20opbeans-java.35.241.242.16.ip.es.io&transactionType=request&latencyAggregationType=avg&traceId=84d10ac968e46864dc2cf011a3470429&transactionId=110e1dc59d1a250c&detailTab=metadata

still seems to be an issue with lining things up... maybe this is because the timestamp we discussed is being added under `lables.telemetry_sdk_elastic_export_timestamp` instead of `telemetry.sdk.elastic_export_timestamp`?

**Comment by axw** [comment]
We're still recording the attribute as a label which is probably a mistake (though potentially useful to record as a different field). The timestamp adjustment _should_ be being applied. I'm going to implement https://github.com/elastic/apm-server/issues/5431 to help debug this.
