### ISSUE TITLE
cgroup ids are mapped as long, should be keyword

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5175]
See https://github.com/elastic/apm-server/pull/4956#issuecomment-828122358. We have introduced mappings for some cgroup fields. These should be consistent with the fields defined by beats. We're mapping `system.process.cgroup.cpuacct.id` and `system.process.cgroup.cpu.id` as `long`, but they should be `keyword`.

**Comment by simitt** [comment]
Checked - the mappings are there but the Kibana index pattern is not updated.

**Comment by axw** [comment]
https://github.com/elastic/kibana/pull/100015
