### ISSUE TITLE
gmuxed Jaeger requests incur "metrics registry missing" error logs

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5176]
See https://github.com/elastic/apm-server/pull/4934#issuecomment-828135152. I configured jaeger-agent to send data as gRPC to apm-server's main port (8200), and for each request the server logs an error like this:

```
localtesting_7.13.0_apm-server | {"log.level":"error","@timestamp":"2021-04-28T04:23:14.190Z","log.logger":"beater.grpc","log.origin":{"file.name":"interceptors/metrics.go","file.line":48},"message":"metrics registry missing","grpc.request.method":"/jaeger.api_v2.CollectorService/PostSpans","ecs.version":"1.6.0"}
```

We should not be logging such errors. This probably also means there are no metrics being captured for this gRPC service/method.

**Comment by simitt** [comment]
tested with BC 6 - no error logs showing up.
