### ISSUE TITLE
Add fields for mobile network connectivity attributes

### ISSUE THREAD

**Issue by bryce-b** [elastic/apm-server#5203]
* The following fields need to be added:
`net.host.connection_type`: `5G`,`4G`,`3G`,`2G`,`1G`, `wifi`,`unavailable` (String)
`net.host.carrier.mcc` : mobile country codes (String)
`net.host.carrier.mnc` : mobile network codes (String) 
`net.host.carrier.name`: Carrier names (String)  (e.g.: `T-Mobile`, `AT&T`, etc)
`net.host.carrier.icc`: 2-character iso country code (String) (e.g.: `US`, `DE`)

* These fields also need to be added into ECS 

Note: Here are related tickets
[OpenTelemetry spec issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1647)
[iOS agent ticket](https://github.com/elastic/apm-agent-ios/issues/23)

**Comment by bryce-b** [comment]
Here's a link to a rudimentary test app for generating iOS data: https://github.com/elastic/ios-integration-testing
It requires MacOS. 
the apm server ip/url can be set in this file : https://github.com/elastic/ios-integration-testing/blob/master/Shared/Model/ios_integration_testingApp.swift
Let me know if you need help getting it set up.

**Comment by axw** [comment]
We should keep https://github.com/elastic/apm-server/pull/4912 in mind when we do this - specifically there's overlap on `net.host.connection_type`.

**Comment by jalvz** [comment]
@bryce-b should any of these fields be required?

**Comment by bryce-b** [comment]
@jalvz what are the implications of being 'required'? Will the traces be ignored if they are not attached? If so, they shouldn't be required.

**Comment by jalvz** [comment]
Exactly, thanks 👍
