### ISSUE TITLE
Updating messaging context fields according to spec

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-server#5229]
As per our [messaging spec](https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-messaging.md), we should have a `context.message.routing_key`  field both for transactions and spans (optional, string). 

In addition, `context.message.body` and `context.message.headers` exist in both spans and transactions, but they are only relevant to transactions (similar to the corresponding fields in `context.http`).

**Comment by eyalkoren** [comment]
> is this something that agents already send and should be supported already?

@simitt no, currently no agent is sending this AFAIK, but in the Java agent we have a [PR](https://github.com/elastic/apm-agent-java/pull/1767) that adds it to our RabbitMQ instrumentation and it is blocked on the addition of this field.

**Comment by marclop** [comment]
@eyalkoren I opened an PR to add the fields to the intake API, how are these going to be used, are we planning on showing them in the UI? do they need to be indexed?

**Comment by eyalkoren** [comment]
Thanks @marclop 

> I opened an PR to add the fields to the intake API

Note that this is about adding one field (`context.message.routing_key`) to both transactions and spans and possibly removing two fields only from spans 

> how are these going to be used, are we planning on showing them in the UI?

We should probably show them in the span/transaction details. I am not sure whether we need a UI task for that or if anything under `context` is automatically added to the context data table.

> do they need to be indexed?

I believe they should. @SylvainJuge WDYT?

**Comment by marclop** [comment]
@eyalkoren, I think we'll hold off removing these fields from the Spans for now, we can always remove them as part of `8.x`, for now I think they'd introduce unnecessary complexity in the model and will make the Transaction and the Span have different fields that are allowed in regards with messaging.

@SylvainJuge Let me know if we should index the `routing_key` fields, the current open PR does not add mappings for them, but I can easily change it.

**Comment by SylvainJuge** [comment]
I think that indexing `routing_key` would make sense too.

One thing to remember when adding support for this in the agents is that we must properly apply some normalization as random values could be used, we already do that for exchange and queue names.

**Comment by eyalkoren** [comment]
Thanks @SylvainJuge !

Do you have an idea how we can apply such normalization logic?

**Comment by eyalkoren** [comment]
@marclop @SylvainJuge and I just discussed this and we can't currently come up with a good plan for identifying temporary/ephemeral routing keys in order to normalize them when they are such. Therefore, it's probably better to start with not indexing this field after all and figure this out only if and when there is a concrete demand.
Sorry for reverting our call here, but it seems to be the better call 🙏

**Comment by marclop** [comment]
@eyalkoren no problem, I'll reopen the issue and open up a PR to remove the mapping
