### ISSUE TITLE
APM Server not handling OpenTelemetry rpc.* semantic conventions

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/apm-server#5234]
**Note**: There's a high likelihood I'm instrumenting my code wrong. I'm not sure if what I'm doing with the client is correct, but since the client appears as "unknown", and I'm starting a new span in the server instead of extracting one from the context, I feel like the sample code isn't working correctly. This would be in `grpc/server/server.go#50`.

**APM Server version** (`apm-server version`): apm-server version 7.13.0 (amd64), libbeat 7.13.0 [0aa1b50a5b680be19556d53f870fa9723bdc9a03 built 2021-04-27 15:36:50 +0000 UTC]

**Description of the problem including expected versus actual behavior**: While following the test plan for https://github.com/elastic/apm-server/pull/5074, the output I saw did not match the expected output in the test description.

The expected results of viewing a transaction/span were:

>Instrument gRPC-based server and client with OpenTelemetry, collect traces with APM Server and check:
>- transaction type should be "request"
>- transaction result should be "OK" (or some other gRPC status code's string representation)
>- span type should be "external", and subtype should be "grpc"
>- client and server should be connected in the service map in Kibana
>- there should be no "labels.rpc.*" fields

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. In the `apm-integration-testing` repo, start version 7.13 of kibana and elasticsearch: `./scripts/compose.py start 7.13 --no-apm-server`
 2. Start the `apm-server` in a terminal window, ./apm-server -e -E output.elasticsearch.username=admin -E output.elasticsearch.password=changeme
 2. Clone the repo with the sample code: `git clone https://git.sr.ht/~stuartnelson3/notes`
 3. `cd notes/otlp`
 4. start the opentelemetry collector with the `collector-config.yml`: `docker run --rm -it --name collector --net host -v $(pwd)/collector-config.yml:/etc/collector-config.yml otel/opentelemetry-collector-contrib --config=/etc/collector-config.yml`
 5. In the same directory in a separate terminal window, run the gRPC server: `go run ./grpc/server/`
 6. In the same directory in a separate terminal window, run the gRPC client: `go run ./grpc/client/`
 7. Navigate to the apm service dashboard, which should be available at http://localhost:5601/app/apm/services/hello-server/transactions
 8. Select the transaction `api.HelloService/SayHello`. Click on the sampled transaction and view the metadata.

**Provide logs (if relevant)**: Example transaction document is available in the original PR

**Comment by axw** [comment]
> start the opentelemetry collector

Sorry for the lack of clarity in testing instructions -- this is where things went wrong. There are two OpenTelemetry implementations for Elastic APM:

 - elastic exporter in opentelemetry-collector-contrib
 - native OTLP intake directly in apm-server

The elastic exporter is superseded by the native OTLP intake, and we only updated the latter to support RPC conventions. So to test this change, don't run opentelemetry-collector-contrib at all, and set `EXPORTER_ENDPOINT=localhost:8200`.

One other note about manual testing for releases: you should use `./scripts/compose.py start 7.13.0 --bc` to get the latest build candidate. IIANM, with your above command you get `-SNAPSHOT` images. Best we run the same BC for all stack components, as that's how things will be released.

**Comment by simitt** [comment]
@axw looking at the [collector-config.yml](https://git.sr.ht/~stuartnelson3/notes/tree/master/item/otlp/collector-config.yml) can you confirm that setting 
```
exporters:
  otlp:
    endpoint: "apm-server:8200"
    headers:
      Authorization: "Bearer 1234"
```
instead of 
```
exporters:
  elastic:
    apm_server_url: "http://localhost:8200"
    # secret_token: "APM_SERVER_SECRET_TOKEN"
```
should also work? Afaik this also sends the data to the native OTLP intake

**Comment by axw** [comment]
Yes, good idea. I think `insecure: true` will also be needed under the otlp section.

**Comment by simitt** [comment]
@stuartnelson3 can you retest this please with the above mentioned changes in your setup?

**Comment by stuartnelson3** [comment]
Sure thing. Everything checks out now with latest BC except `span.type` and `span.subtype`, server only reports `span.type: app`.

**Comment by stuartnelson3** [comment]
@axw do I have to modify the test setup to ensure that the transaction has `rpc.system` set?

**Comment by axw** [comment]
@stuartnelson3 is the `rpc.system` attribute not being set by the grpc interceptor? According to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md it's required, and it's what we use to decide a transaction/span is RPC-related.

**Comment by stuartnelson3** [comment]
it definitely looks like it's getting set in both the client and server:

client:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/0e5bef9af1c708e28aabcadd3fd8b35c36526e44/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L416
server:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/instrumentation/google.golang.org/grpc/otelgrpc/v0.20.0/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L327

the constant:
https://github.com/open-telemetry/opentelemetry-go/blob/v0.20.0/semconv/trace.go#L238

**Comment by stuartnelson3** [comment]
Confirmed that this is working as expected. I was looking at the span created by the `otel` interceptor, but because that was the root span it was being converted to a transaction on ingest into apm-server, which means it didn't show any span attributes. After adding a custom span in the RPC call that would be the root, the interceptor span was ingested as a span and showed the expected `span.type` and `span.subtype`.
