### ISSUE TITLE
Create one metrics document with jvm metrics per opentelemetry event

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5275]
Follow up from https://github.com/elastic/apm-server/pull/4986#issuecomment-843050707: when translating JVM metrics one document with all JVM metrics should be created, rather than creating one document per metric, as otherwise JVM metrics do not show up in the UI as expected.

**Comment by axw** [comment]
I think the simplest thing to do will be to remove the ingest pipeline I added for 7.13, and do it in code in processor/otel. That's where we split metrics by labels currently.
