### ISSUE TITLE
Remove Kibana only fields from ES template

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#531]
The `fields.yml` contains information for creating the Kibana Index Pattern as well as the ES Template.

Some of the information provided should only be used for Kibana Index Pattern, so it can be used in the dashboards. 
Currently this information is also added to the ES Template, indexed and shows up in the Discover page. 

E.g. [view errors](https://github.com/elastic/apm-server/blob/master/processor/error/_meta/fields.yml#L5)

**Comment by ruflin** [comment]
We could add and option `elasticsearch.template: false` to the fields.yml to support this use case?

**Comment by simitt** [comment]
SGTM. Currently `index` and `enabled` also exist, but only for certain types, maybe we could also make use of them.

**Comment by ruflin** [comment]
@simitt I assume if we use `index` / `enabled` they still show up somehow in the template? Can you open a PR on the beats side for this?

**Comment by graphaelli** [comment]
no longer needed
