### ISSUE TITLE
Zoom into `Request Per Minute [APM]` visualisation does not work properly.

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#532]
When zooming into the `Requests Per Minute [APM]` visualisation in the `Transactions` dashboard, values are not shown properly. 

Neither the counter in the legend, nor the graph matches with the values that are shown before zooming in.

**Comment by simitt** [comment]
@simianhacker could you please have a look at this bug in the visualisation?

**Comment by simitt** [comment]
**Request Per Minute - 15mins all requests**
![rpm_all](https://user-images.githubusercontent.com/5555349/35332048-ef8ba662-0109-11e8-8db8-92f800b8e17c.png)
The value for rpm in the legend doesn't seem to be correct, compared to the graph.

**Request Per Minute - 15mins only HTTP 3xx group**
![rpm_3xxx](https://user-images.githubusercontent.com/5555349/35332130-2daa53ee-010a-11e8-9a00-1b749ae788f4.png)
A count 0 for RPM doesn't seem to be correct. 

**Request Per Minute - Zoom in HTTP 3xx group**
![zoom_empty](https://user-images.githubusercontent.com/5555349/35332160-4532ddb0-010a-11e8-8db3-61541b593842.png)
Zooming in at a time span where the above screenshot clearly shows data, the data disappear and the legend still says 0 count.

**Comment by simianhacker** [comment]
You’ve zoomed in past the resolution of the data. There is a feature added to TSVB that allows you to limit the size of the buckets to the resolution of your data. If you’re are indexing at 10 second intervals then you should set the interval in TSVB under panel options to >=10s

**Comment by simitt** [comment]
@simianhacker would you mind adding this option to the [apm-server.json](https://github.com/elastic/apm-server/blob/master/_meta/kibana/6/dashboard/apm-dashboards.json#L190)?

**Comment by simitt** [comment]
@simianhacker @elastic/apm-ui it would be great to get some help with this to get it fixed.

**Comment by simianhacker** [comment]
I will take a look at it this morning
