### ISSUE TITLE
Legend values are incorrect in dashboards

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#537]
The OSS dashboards consist of several visualisations, which show different kinds of timeseries data. All of them seem to show inaccurate data in the legends. 
It appears that the values for `sum`, `avg`, etc. in the legend are calculated for the last recevied datapoints and not over the times range that is applied in Kibana.

**Services Visualisation:**
![services](https://user-images.githubusercontent.com/5555349/35331511-f7650f92-0107-11e8-8b43-7c9db6d8d4e6.png)

[Top Services by Response Time]: The response time shown in the legend doesn't match the response time in the table. 
[Top Services by Request Per Minute]: The numper of rpm * 15 minutes is far off compared to the number of Total Transactions in the table.  

**Transactions**
![transactions](https://user-images.githubusercontent.com/5555349/35331721-ae4aa460-0108-11e8-9cee-fadd7de2a57e.png)
![transaction_detail](https://user-images.githubusercontent.com/5555349/35331726-b144b9b2-0108-11e8-8352-63c0415ab410.png)

[Response Time]: The Transaction detail snapshot shows that the average response time does differ from the avg response time in the table.
[Request Per Minute]: The rpm in the legend doesn't fit the graph, and also differs from what is shown in the curated UI.

**Errors**
![errors](https://user-images.githubusercontent.com/5555349/35331880-38ffda9e-0109-11e8-92db-c7bdce9ed09e.png)
The value of the legend shows the number of error occurences per grouping key for the last bucket.

**Comment by simianhacker** [comment]
The legend always shows the last bucket OR the value closest to the cursor. Everything you described is working as it’s intended to work; this is not a bug.

The difference between the legend and the table is the table shows the response time for the entire time period (average of all the points).

**Comment by simitt** [comment]
Thanks for explaining @simianhacker . 
Is there a way to change this behavior, to also show the values in the legend for the entire time period and not just for the last bucket?

**Comment by simianhacker** [comment]
No... I’m actually planning on removing the values from the legend because it’s causing too much confusion. It’s a bad UX

**Comment by simitt** [comment]
It is quite confusing, especially when comparing the values of the dashboards to the values in the curated UI, where values are calculated over time. 

I am going to close this issue then, as works as expected.
