### ISSUE TITLE
Upgrade to Golang 1.16.5

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5374]
* [x] upgrade to go `1.16.4` and pull in changes from libbeat
* [x]  upgrade to go `1.16.5` (https://github.com/elastic/beats/issues/26182) and pull in changes from libbeat
* [x] update [support matrix](https://www.elastic.co/support/matrix#matrix_os) to reflect that `OSX <10.14` is not supported for apm-server >= `7.14`.

**Comment by michel-laterman** [comment]
@simitt, beats has now been updated to 1.16.5 on both master and 7.x
