### ISSUE TITLE
Send APM Server configurations to Kibana APM endpoint on startup

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5377]
APM Server needs to send its configuration values to a Kibana APM endpoint on startup when running on ESS/ECE. The request is only made if an `apm-server.kibana.*` section is configured and APM Server is running on Elastic cloud (ENV indicating that apm-server is running on cloud, or `apm-server.kibana` config option, ..).

Ideally the configuration options are already flattened (dotted), and any credentials for ES and Kibana are removed. APM Server startup should not be blocked by the request, the existing ConnectingClient implementation should be reusable for setting up a connecting and retrying.

**Comment by simitt** [comment]
Align with the @elastic/apm-ui team on the concrete endpoint, related to https://github.com/elastic/kibana/issues/100657.

**Comment by stuartnelson3** [comment]
>Ideally the configuration options are already flattened (dotted)

Is there support for this already within apm-server or some other elastic libraries?

**Comment by stuartnelson3** [comment]
>Ideally the configuration options are already flattened (dotted)

Should everything be flattened, or just objects that have single keys?

eg.

```
{parent: {child: 1, other_child: 2}, 'other_parent.child': 3}
// or
{'parent.child': 1, 'parent.other_child': 2, 'other_parent.child': 3}
```

**Comment by simitt** [comment]
Everything should be flattened, so it would just be `key: value` pairs. Beats `common.MapStr` has a `flatten` method https://github.com/elastic/beats/blob/master/libbeat/common/mapstr.go#L269-L291 that you might want to reuse or use for inspiration.
