### ISSUE TITLE
Log error if sourcemaps with the same key are uploaded

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#538]
Uploaded sourcemaps are uniquely identified by their `service.name`, `service.version` and `bundle_filepath`. In case multiple sourcemaps with the same key information are uploaded, an error should be logged. 

see [former discussions](https://github.com/elastic/apm-server/pull/381#pullrequestreview-83951603).

**Comment by jalvz** [comment]
Just with the same key, or with the same key and different content?

**Comment by simitt** [comment]
I don't see a lot of value in also checking for the content. It shouldn't be the standard case to upload  the same document twice, so we could simply log an error or warning for the same key.
