### ISSUE TITLE
Adapt dashboards for frontend data.

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#540]
Currently the OSS dashboards are tailored for data from existing (backend) agents. 
Investigate and adapt dashboards for specific frontend requirements.

**Comment by simitt** [comment]
@jahtalab I assigned this to you as we recently discussed you taking overview the coordination of this.

**Comment by jahtalab** [comment]
Dashboards/ [APM] Services:

![image](https://user-images.githubusercontent.com/6134122/35979737-62e00046-0ce9-11e8-9c01-f484979b4399.png)

The top charts are not relevant for frontend applications: 
General solution would be to show a "Top Services by Transaction per minute" chart
Also in the table "Avg. Resp. Time" is not relevant for frontend applications, should be "Avg. Trans Time". The same with "95th percentile of Resp. Time"

**Comment by jahtalab** [comment]
Dashboard / [APM] Transactions

![image](https://user-images.githubusercontent.com/6134122/35980151-480bc6dc-0cea-11e8-9039-6a7e17b05dce.png)

The same issues as above ^

**Comment by jahtalab** [comment]
@elastic/apm-server , I talked to @roncohen about the dashboards and he decided to adopt a generic solution for dashboards. Meaning we should try not to be specific about backend data. The main difference in the dashboards are in transaction data since the concept of Requests and Response is not relevant for frontend. 

@roncohen, Per our discussion about dashboards, Would you please coordinate how these fixes should be implemented?

**Comment by simitt** [comment]
Is there something that should be done for 6.3? (ping @roncohen @jahtalab )

**Comment by jahtalab** [comment]
To summarise the following changes are needed:

- In [APM] Services dashboard:
   - Chart title "Top Services by Response Time [APM]" should be changed to "Top Services by Transaction Time [APM]"
  - Chart title "Top Services by Request Per Minute [APM]" should be changed to "Top Services by Transaction Per Minute [APM]"
  - Table column header "Avg. Resp. Time" --> "Avg. Trans. Time"
  - Table column header "95th percentile of Resp. Time" --> "95th percentile of Trans. Time"
- In [APM] Transactions dashboard:
  - Chart title "Response Times [APM]" --> "Transaction Times [APM]"
  - The query for "Request Per Minute [APM]" chart should be changed in a way that it includes all transactions (currently it seems it only includes transactions with request field)
  - Chart title "Request Per Minute [APM]" --> "Transaction Per Minute [APM]"
  - Table column header "Avg. Resp Time (ms)" --> "Avg. Trans. Time (ms)"
  - Table column header "95th percentile of Resp Time (ms)" --> "95th percentile of Trans. Time (ms)"

cc @alvarolobato , @roncohen

**Comment by alvarolobato** [comment]
@simitt do you think you can get these before 6.4?

**Comment by simitt** [comment]
Regarding the `Request Per Minute [APM]` visualisation what do you think about showing the overall number of transactions instead of grouping by `transaction.result`? We can either create a seperate dashboard for `RUM` and just remove the grouping there or remove the grouping for all agents and keep one dashboard. 

You can have a look at both solutions by importing the dashboards with `make update import-dashboards` from https://github.com/elastic/apm-server/compare/master...simitt:change-dashboards
@jahtalab , @roncohen, @makwarth please have a look and let me know which solution you prefer.

**Comment by jahtalab** [comment]
@simitt , I would prefer the generic approach (one dashboard) since the cost of maintaining multiple dashboards quickly adds up.

**Comment by simitt** [comment]
The curated APM UI shows different visualisations for the RUM agent and the other agents. 

But I agree that it would be nicer and easier to only maintain one view. It'd probably also be easier to grasp for the users. 

@roncohen @alvarolobato @elastic/apm-ui WDYT - is it ok to only show the `transactions_per_minute` and not group them into `transaction.result`?

**Comment by simitt** [comment]
This is how it is shown when grouped by `transaction.result`:
![screen shot 2018-06-28 at 14 43 04](https://user-images.githubusercontent.com/5555349/42034929-d988f5ac-7ae1-11e8-9d79-cbc35816ccbd.png)



This would be the new visualisation without a grouping:
![screen shot 2018-06-28 at 14 43 18](https://user-images.githubusercontent.com/5555349/42034935-dfe07f74-7ae1-11e8-9cb2-c8b65cd0d809.png)

**Comment by simitt** [comment]
@makwarth afaik you only get rid of the grouping for `RUM` data but not for data collected by other agents in the curated UI.
Is it ok to not do a grouping for all data no matter the agent for the dashboards or should we have two different dashboards?

**Comment by makwarth** [comment]
Sorry, I was too quick. OK, let's go with no grouping.
