### ISSUE TITLE
How to update quickstart docker-compose.yml

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#5417]
Back in https://github.com/elastic/apm-server/pull/3106, this docker-compose file was added to our docker quickstart guide: https://github.com/elastic/apm-server/blob/master/docs/guide/docker-compose.yml. A similar file can be created today with apm-integration-testing:

```
./scripts/compose.py start 7.13.0 --release --no-xpack-secure --output-format yaml --docker-compose-path - | sed 's/7.13.0/{VERSION}/'
``` 

My question is: How can I easily update this file moving forward? As @axw stated in https://github.com/elastic/apm-server/pull/3106#discussion_r363566158:

> There's a bunch of command args passed to apm-server that are not relevant to a "quick start" experience, like enabling profiling, rate-limiting, self-instrumentation. Having all of those makes it more difficult for people to understand, which invariably leads to cargo-culting

https://github.com/elastic/apm-integration-testing/issues/712 was opened to address this, but based on https://github.com/elastic/apm-integration-testing/issues/712#issuecomment-577718178, it was too big of an undertaking to automatically remove all of the noise.

**Comment by axw** [comment]
@bmorelli25 is the current `docker-compose.yml` file in docs not functional? We rarely make breaking changes in apm-server, so it should continue to function throughout the 7.x lifetime. When we get to 8.0 we can revise it by hand?

**Comment by bmorelli25** [comment]
🤦 You're right. After rereading my original https://github.com/elastic/apm-server/pull/3106#issue-359691105, I think I misread _updated every **major**_ as _updated ever **minor**_.

It sounds like I can just remove the `-XX:UseAVX=2` from the docs and we're good until 8.0.0?

**Comment by axw** [comment]
Yes that sounds right to me

**Comment by simitt** [comment]
I don't think the `docker-compose.yml` exists anymore after restructuring the docs. @bmorelli25 can this issue be closed?
