### ISSUE TITLE
Periodically report applied agent configuration

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5470]
The server should periodically report which agent configuration, injected into the server config via Fleet (https://github.com/elastic/apm-server/issues/5018), has been applied by one or more agents.

See the description of https://github.com/elastic/apm-server/issues/5018 for some thoughts on how we might go about this. Another option not listed there might be to use the [Manager.SetPayload](https://github.com/elastic/beats/blob/4684ac7ed3da20ecc533af492862cdb029f5cb3a/x-pack/libbeat/management/manager.go#L186) method to record information in the integration's status. I don't know if this is possible, just something to look into.

**Comment by stuartnelson3** [comment]
I've tracked metadata like this before via prometheus metrics. What would you think about some sort of gauge vec (metric type is sort of unimportant since we're kind of abusing metrics) where we track etag as label? Should be able to get the instantaneous status, and time to full convergence, and if there are any agents who are stuck on an old version.

**Comment by axw** [comment]
I think that would be a fine approach. It's kinda what I was thinking in #5018:

> Alternatively, we could have agents periodically send an internal agent statistics event which includes the current config Etag value. This would have the benefit of enabling us to see how many and which agents have applied the config.

But I assume you mean we would do it in the server, and not in agents.

**Comment by stuartnelson3** [comment]
I think the agents would be the right place actually

**Comment by stuartnelson3** [comment]
As a first step we'll add it to the server, and evaluate from there
