### ISSUE TITLE
[fleet] Trigger Java Agent binary download via Elastic Agent

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5477]
APM Server asks the Elastic Agent to download the Java Agent binaries in a specific version (the version from the `apm-server.yml`). Elastic Agent downloads the binaries and returns the path to the binaries to the APM Server.

part of https://github.com/elastic/apm-server/issues/4830

TODO: link to elastic-agent issue

**Comment by simitt** [comment]
moved to blocked for implementation; 
but we can work on defining the communication with the elastic-agent.

**Comment by stuartnelson3** [comment]
what about something like

request:
```
GET /api/agent/java/1.1.0
```
response:
not found -- 404, some sort of response like
```json
{
    "agent": "agent-java-1.0.0",
    "status": "downloading"
}
```
which indicates to check back later. If we request a binary that can't be found, then the status would be something like "not found" or whatever.

when it's been downloaded the response is something like:
```json
{
    "path": "/path/to/java-agent-linux-x86_64/1.0.0/java-agent",
    "sha256": "7bfa7e5908c7cc9e75da5ddf3066d7cbcf3fd9fa51945851325eebc17f50ba80"
}
```

then we can verify the checksum and use the path.

another option would be to make a request to EA and register some sort of callback endpoint for when it's complete, but i think that would end up being more complicated than just polling for a little while.

**Comment by felixbarny** [comment]
Closing in favor of https://github.com/elastic/apm-server/issues/5477
