### ISSUE TITLE
[fleet] Run the Java agent attacher to attach binaries to all matching JVMs

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5478]
APM Server runs the improved Java agent attacher (prefer `$JAVA_HOME/bin/java` over `java`), which takes care of attaching the binary to all matching JVMs on the same host 

Take care of processing attacher logs.

part of https://github.com/elastic/apm-server/issues/4830

**Comment by stuartnelson3** [comment]
Checking that `ELASTIC_AGENT_CLOUD` is unset should hopefully be enough

**Comment by axw** [comment]
This can't be tested as it's not wired up yet.
