### ISSUE TITLE
Data race in pub/sub implementation

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#5480]
Error:
`http: superfluous response.WriteHeader call from github.com/elastic/apm-server/x-pack/apm-server/sampling/pubsub_test.newRequestResponseWriterServer.func1 (pubsub_test.go:400)`

Details:
https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-5468/5/testReport/junit/(root)/pubsub/Build_and_Test___ARM_build_test___TestSubscribeSampledTraceIDs/

**Comment by axw** [comment]
I looked into this a bit, and I'm _pretty_ sure (but not 100% sure) that it's an issue in the test rather than the implementation. However, while testing I did find another issue in the implementation: https://github.com/elastic/apm-server/issues/5493
