### ISSUE TITLE
[OpenTelemetry] add support for receiving logs

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5491]
APM Server currently supports receiving OpenTelemetry traces and metrics. It would be nice to round that out with support for logs. The [OpenTelemetry Logging](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/overview.md) spec is currently in experimental status; we would provide no greater support guarantees than this, at least until the spec graduates.

**Comment by axw** [comment]
Logs is now beta: https://github.com/open-telemetry/opentelemetry-proto/pull/311

**Comment by vchirikov** [comment]
Do you have a plan or estimate when the apm server will be able to receive otel logs?

**Comment by axw** [comment]
@vchirikov no, we don't currently have this scheduled.

**Comment by axw** [comment]
@cristianmad not that I can think of, sorry.

**Comment by chickeaterbanana** [comment]
Do I understand the labels correctly that `v8.0.0` will support this?

**Comment by axw** [comment]
@chickeaterbanana it is a stretch goal. The label is for the release we're targeting, but it may slip. We have a lot on our plates.

**Comment by axw** [comment]
https://github.com/axw/apm-server/tree/otel-logs has some of the code required to implement this. If anyone wants to take it over the line, it'll need to be hooked up to the gRPC server and needs tests added.
