### ISSUE TITLE
Unable to increase heap memory

### ISSUE THREAD

**Issue by subhasisbanik** [elastic/apm-server#5498]
**APM Server version** (`apm-server version`): 6.7

**Description of the problem including expected versus actual behavior**:
I am observing requests of more than 4800 events/second and require more throughput that that. I am looking to increase the memory utilised by the server on startup to address this.

**Comment by axw** [comment]
We prefer to reserve GitHub issues for bug reports and feature requests; this is neither. Please make sure you have read the [docs](https://www.elastic.co/guide/en/apm/server/current/tune-apm-server.html), and if you still have questions then open a topic at https://discuss.elastic.co/c/apm. Also bear in mind that 6.7 reached [EOL](https://www.elastic.co/support/eol) quite some time ago.
