### ISSUE TITLE
Support OpenTelemetry attributes in the APM intake API

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-server#5516]
With the current intake API, APM agents that bridge the OpenTelemetry APIs (see https://github.com/elastic/apm-agent-java/pull/1631) need to take care of mapping OpenTelemetry attributes to internal fields. As the APM Server already provides the functionality of mapping OTel attributes as part of the OTLP intake, we should avoid duplicating this logic and potentially introducing divergence or inconsistencies. 

The intake API should allow agents to set OpenTelemetry fields (e.g. bridged from the corresponding OpenTelemetry API) on Transaction, Span and Metrics documents. The APM Server would take care of mapping these fields (with the same logic as in the OTLP intake) to the internal fields.

**Comment by axw** [comment]
@felixbarny @AlexanderWert am I right in thinking that we should only handle span attributes, and not resource attributes? Resource attributes are roughly equivalent to our stream-level metadata.

**Comment by AlexanderWert** [comment]
> am I right in thinking that we should only handle span attributes, and not resource attributes? Resource attributes are roughly equivalent to our stream-level metadata.

I think so, since with the OTel bridge scenario the metadata (OTel's Resource attributes equivalent) is collected by our agent as it has been before

**Comment by SylvainJuge** [comment]
Closing as #6259 duplicates it.
