### ISSUE TITLE
[compressed spans] Adapt span metrics calculation

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5595]
To make the compressed feature (https://github.com/elastic/apm/issues/432) work we need to extend the intake API (https://github.com/elastic/apm-server/issues/5485) and adapt the calculation of span metrics.

## Adapt span metrics calculation
Since this feature is folding a set of spans into one single we need to adapt the calculation of span metrics so that the resulting metric values are still correct.

**Comment by axw** [comment]
I _think_ this is a simple matter of updating `model.Span.RepresentativeCount` when decoding "span.composite": https://github.com/elastic/apm-server/blob/06bea7cfe1263c416bb904f455e4e9d436a4f9b0/model/span.go#L80-L85

i.e. if we set that to `1/sample_rate * composite.count`, then the existing span metrics aggregator should do the right thing, IIANM
