### ISSUE TITLE
serverMap Module data exceptions

### ISSUE THREAD

**Issue by tttoad** [elastic/apm-server#5609]
APM Server version 7.13.2 elasticSearch: 7.13.2 kibana: 7.13.2 

The service node of the serverMap module on the Kibana Apm interface cannot be linked up.

1.run apm,es,kibana,opentele :
	docker run --name elasticsearch --network=my-jaeger-net  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -d elasticsearch:7.13.2
	docker run --name kibana --network=my-jaeger-net  -p 5601:5601 -d kibana:7.13.2
	docker run -d  -p 8200:8200 --name=apm-server --network=my-jaeger-net --user=apm-server elastic/apm-server:7.13.2 --strict.perms=false -e  -E output.elasticsearch.hosts=["elasticsearch:9200"]
2. run openTelemetry: 0.27.0
3. Use uber/jaeger-client-go to send data to jaeger-agent,agent to send data to openTelemetry
4. The apm interface can view the tracing information normally, but there is no connection information between the services of the serverMap module. The data is reported to AliCloud sls service at the same time, and AliCloud can show the dependency of the service normally.
5. Everything is fine when using go-agent to report data

**Comment by axw** [comment]
@ttoad please open a topic at https://discuss.elastic.co/c/observability/apm/58. It's not clear why this would happen, and we prefer to reserve GitHub issues for confirmed apm-server bugs. Once we understand the cause, we may come back here and open an issue.

When you do open a topic in Discuss, please provide some more details so we can understand why this is happening. Ideally a sample Jaeger-instrumented program which produces the problem.
