### ISSUE TITLE
Extend Intake to accept FaaS / Serverless context fields 

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-server#5753]
With [adding AWS Lambda support to our agents](https://github.com/elastic/apm/pull/470) we need additional context in the intake API that accepts function as a service (faas)-specific fields.

Fields to be added:

Field | Example | Metadata | Transaction | Description
---   | ---   | --- | --- | ---
`service.id` | e.g. `arn:aws:lambda:us-west-2:123456789012:function:my-function` | yes | yes | Add `service.id`(available in ECS) to the intake model. Value for Lambda: The ARN of the function without alias suffix. 
`faas.trigger.type` | `http` | no | yes | The trigger type. 
`faas.execution` | `af9aa4-a6...` | no | yes | The AWS request ID of the function invocation 
`faas.coldstart` | `true` / `false` | no | yes | Boolean value indicating whether a Lambda function invocation was a cold start or not.
`faas.trigger.reuqest_id` | `af9aa4-a6...` | no | yes | The ID of the origin trigger request
`cloud.origin.*` | - |  no  |  yes | Allow to self-nest all cloud fields under `cloud.origin` to specify trigger cloud data. See https://github.com/elastic/ecs/pull/1542
`service.origin.*` | - |  no  |  yes | Allow to self-nest all service fields under `service.origin` to specify trigger service data. See https://github.com/elastic/ecs/pull/1542

Names and fields are inspired by the [OpenTelemetry specification for functions as a service](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/faas.md).

There is a [PR for starting the RFC process](https://github.com/elastic/ecs/pull/1518) to add these fields also to ECS.

**Comment by axw** [comment]
Also relevant: https://github.com/elastic/apm-server/issues/5456
