### ISSUE TITLE
Release note links on GitHub Releases are broken (404) for the last few releases

### ISSUE THREAD

**Issue by BenB196** [elastic/apm-server#5779]
**APM Server version** (`apm-server version`): 7.9.x+?

**Description of the problem including expected versus actual behavior**:

The release note links on GitHub are broken for the last few 7.x releases. 6.x release appear to not be broken.

The broken links end in 404.

This issue appears to go back to around 7.9-ish.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Got to APM server GitHub releases: https://github.com/elastic/apm-server/releases/tag/v7.13.4
 2. Click on release note links: https://www.elastic.co/guide/en/apm/server/7.13/release-notes-7.13.4.html
 3. Get 404:
 
![image](https://user-images.githubusercontent.com/8277432/126543897-0cfb9ffc-999d-446c-89d6-62e54e9b6787.png)

**Provide logs (if relevant)**: N/A

**Comment by axw** [comment]
Oops, thanks for raising this @BenB196! We'll look into it.

**Comment by bmorelli25** [comment]
Thanks for pointing this out, @BenB196! I've fixed the old links and opened a PR to ensure we're using the right URL pattern moving forward.
