### ISSUE TITLE
server setup - ingest pipeline apm_error_grouping_name - [value] required property is missing

### ISSUE THREAD

**Issue by domanq** [elastic/apm-server#5786]
The APM Server 7.13.4 setup fails at "PUT https://...:9200/_ingest/pipeline/apm_error_grouping_name ..."  with Elasticsearch 7.9.3. 
The pipeline definition uses copy_from, which is not supported by this version of Elastic.
According to the compatibility matrix it should be: Elasticsearch 7.9.x -> APM Server 7.0.x-7.13.x.

**Comment by axw** [comment]
Thanks for the bug report -- that was an oversight which we'll fix.
