### ISSUE TITLE
Soak testing

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5821]
We should perform [soak testing](https://en.wikipedia.org/wiki/Soak_testing) (AKA "long run testing"), to identify issues in apm-server (and associated software) that may become evident over, such as memory leaks/bloat. I think, ideally, we would run this in ESS. We might use hey-apm or apmbench for load generation, or perhaps opbeans with standard HTTP load generators.

**Comment by cachedout** [comment]
> We should perform soak testing (AKA "long run testing"), to identify issues in apm-server (and associated software) that may become evident over, such as memory leaks/bloat

We have a solution that's [pretty close to being ready for this](https://github.com/elastic/beatbox/). It was originally designed for Beats/Agent but we could adapt it to work with APM Server. Let me know if you'd like to chat more about it.

**Comment by axw** [comment]
@cachedout sounds good, I'll ping you some time soon to have a chat

**Comment by simitt** [comment]
Soak testing was handled in https://github.com/elastic/apm-server/issues/8302; closing this as duplicate.
