### ISSUE TITLE
[spans dropped stats] Extend intake to support stats for dropped spans

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-server#5850]
As specified in [this APM agents spec](https://github.com/elastic/apm/blob/master/specs/agents/handling-huge-traces/tracing-spans-dropped-stats.md), there might be different reasons for spans being dropped by APM agents. 

In this case agents should collect statistics about the dropped spans in a `transaction` object as follows:
```
{
  ... ,

  "dropped_spans_stats": [
    {
      "type": "external",
      "subtype": "http",
      "destination_service_resource": "example.com:443",
      "outcome": "failure",
      "duration.count": 28,
      "duration.sum.us": 123456
    },
    {
      "type": "db",
      "subtype": "mysql",
      "destination_service_resource": "mysql",
      "outcome": "success",
      "duration.count": 81,
      "duration.sum.us": 9876543
    }
  ]
}
```
 

This issue is about extending the APM server's intake API to accept this kind of data and store it with the transaction documents in ES.

**Comment by axw** [comment]
Do any of these fields need to be indexed? i.e. do they need to be searched or aggregated, or only available for human consumption?

**Comment by simitt** [comment]
@AlexanderWert can you help figure out whether these fields are purely informational or supposed to be indexed/aggregatable?

**Comment by AlexanderWert** [comment]
In the first place we would use them to show the dropped spans statistics for individual traces / transactions (thus, for this use case the fields are rather informational). 
However, we should ensure that these values are considered when destination metrics are calculated by the APM server, otherwise the destination metrics would miss information / show wrong numbers.

@felixbarny do I miss something else?

**Comment by felixbarny** [comment]
Agree, these don't need to be indexed.

**Comment by axw** [comment]
@felixbarny in the spec we have `dropped_spans_stats.count` and `dropped_spans_stats.duration.sum.us`. This is slightly different to other metrics we have, like `span.self_time.count` and `span.self_time.sum.us`.

Any objection to nesting `count` under `dropped_spans_stats.duration`, so it's similar? This would slightly simplify server code.

**Comment by felixbarny** [comment]
> Any objection to changing the Elasticsearch document structure to nest count under dropped_spans_stats.duration, so it's similar?

No objections.
Should we change the Intake API as well? Python has started the implementation but I don't think it's too late.

**Comment by axw** [comment]
@felixbarny I think it would make sense to align with other metrics sent by the agents (which I think is also nested), but I don't think this part matters so much. Whatever works for agents.

**Comment by marclop** [comment]
@axw sounds good, I missed the differences on implementation. One thing that sticks out is that the spec sets that the duration sum in microseconds, while `Sum time.Duration` base type is `time.Nanosecond`. https://github.com/elastic/apm-server/blob/d37d372c53fb54723e6a1b14a849162140d0d86d/model/metricset.go#L117-L124

Should we change the spec to reflect that (`duration.sum.us` => `duration.sum.ns `)? Or are we going to handle this math inside the `apm-server`?

```javascript
{
  ... ,

  "dropped_spans_stats": [
    {
       ... ,
      "duration.sum.ns": 123456
    },
    {
       ... ,
      "duration.sum.ns": 9876543
    }
  ]
}
```

**Comment by AlexanderWert** [comment]
@beniwohli FYI ☝️

**Comment by axw** [comment]
@marclop that's just the in-memory representation, making it more natural to deal with as a duration. When we emit the Elasticsearch document, we still only emit microseconds.

**Comment by axw** [comment]
> I think it would make sense to align with other metrics sent by the agents (which I think is also nested), but I don't think this part matters so much. Whatever works for agents.

If we do change the intake protocol, maybe agents should send just `sum` as floating point milliseconds, similar to [composite spans](https://github.com/elastic/apm/blob/master/specs/agents/handling-huge-traces/tracing-spans-compress.md#composite-span)

**Comment by marclop** [comment]
@axw got it, I was just wondering if it made sense to align the units between the internal representation and the intake API, but looking at it again now, it doesn't seem like nanoseconds would be a good unit for aggregated spans, since they're unlikely to be in the low nanoseconds range.
