### ISSUE TITLE
7.x branch test failure due to timeout exceeded

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-server#5858]
We have recently detected a failure on the 7.x branch of APM Server: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/7.x/890/pipeline

It appears that a test has taken too long to run and has thrown the following error:

`*** Test killed with quit: ran too long (11m0s)`

We're happy to adjust the pipeline if needed, but this seems as if it is either a legitimate software defect in the 7.x branch or an adjustment to the test runner itself may be required.

**Comment by cachedout** [comment]
Haven't seen this error again so I'm going to close this and we can re-open it if it comes back.

**Comment by axw** [comment]
@cachedout thanks, and sorry for the silence. Our "system tests" have been getting increasingly slower (https://github.com/elastic/apm-server/issues/6034), so I wouldn't be surprised if this comes back. We may need to increase the timeout, but let's wait and see.
