### ISSUE TITLE
Inconsistent behaviour on startup when ES is missing

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#586]
If ES is not available, `apm-server -e` will start happily and just log errors every time a connection is attempted; but `apm-server -e -E setup.dashboards.enabled=true` will refuse to start. 

Dashboards don't require an ES connection any more than (eg) source maps.

**Comment by simitt** [comment]
I think the difference is when the ES connection is needed. 

Definitly worth to discuss whether we want this to be 'self-healing' when the ES instance is not yet up or if we just want to crash on it.

**Comment by jalvz** [comment]
@roncohen forgot to bring up this specific case  (also in connection with https://github.com/elastic/apm-server/issues/620)

what should we do if there isn't a ES connection, with and without kibana dashboards?

**Comment by jalvz** [comment]
This should be addressed in beats.
