### ISSUE TITLE
destination.ip not always an IP when set by pipeline

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#5898]
**APM Server version** 8.0.0-SNAPSHOT ~, likely 7.14.0+~

**Description of the problem including expected versus actual behavior**:

When ingesting a span containing an `destination.address` that is not an IP apm-server will accept the payload but fail to index with:

```
Cannot index event publisher.Event ... "failed to parse field [destination.ip] of type [ip] ... 'XXX' is not an IP string
```

It appears this is a regression introduced in elastic/apm-server#5876 where the previous processor filtered out addresses that did not parse to IPs.

**Comment by axw** [comment]
> likely 7.14.0+

#5876 was backported to 7.14, but only for the error grouping pipeline. The destination address pipeline doesn't exist in 7.14 -- this bug only affects the master branch.

**Comment by graphaelli** [comment]
That's excellent news, updated description
