### ISSUE TITLE
[docs] logging.files.permissions config is misleading

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5899]
https://www.elastic.co/guide/en/apm/server/current/configuration-logging.html has examples of setting logging.files.permissions to 0644 and 0664. Since 2019 (https://github.com/elastic/beats/pull/14119), log files cannot be created with anything more than the permissions 0640, as libbeat sets a umask.

**Comment by bmorelli25** [comment]
Related to https://github.com/elastic/beats/issues/20584
