### ISSUE TITLE
[docs] Document upgrade order when moving asset setup to Kibana

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5948]
When Kibana (Fleet) takes care of the APM package installation and upgrade (installing templates, pipelines, etc), a more strict upgrade order will be required, where ES and Kibana need to >= APM Server version. 
This will be the case for managed APM Server and for standalone APM Server >= `8.0`.

This needs to be reflected in 
* [ ] support matrix
* [x] docs #7103

**Comment by simitt** [comment]
Kibana will not automatically install the APM Package, but it will bundle with the APM Integration in the future (potentially from 8.2 on). The upgrade order for 8.0 is therefore not that strict, but still recommended to first upgrade Elasticsearch and Kibana, upgrade the APM Integration, and then upgrade the APM Server (or the Elastic Agent bundling the APM Server).

**Comment by bmorelli25** [comment]
This shouldn't have been closed -- AFAIK, the product support matrix hasn't been updated.

**Comment by bmorelli25** [comment]
Per your comment above, we should recommend that ES/Kib are upgraded first (which we do in the upgrade guides). Since bundling isn't happening in 8.0, does anything need to change in the support matrix for 8.0?

**Comment by simitt** [comment]
Bundling is going to happen in `8.1`. Nothing to be reflected on the support matrix for `8.0`. We should be good to close this.
