### ISSUE TITLE
Test Stack Monitoring behavior for Elastic Agent managed APM Server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5986]
Ensure that the Stack Monitoring UI works as expected for APM Server instances that are managed by the Elastic Agent. 

This needs to be tested for the ESS/ECE setup, but also for on-prem users. Collect details for on-prem setup as precondition for the [documentation issue](https://github.com/elastic/apm-server/issues/5987).

Reach out to @simitt for detailed test options.

**Comment by stuartnelson3** [comment]
Tested with ECE running in AWS using version `7.16-SNAPSHOT`

**Comment by stuartnelson3** [comment]
This was incorrectly tested, issue is being re-opened

**Comment by simitt** [comment]
@stuartnelson3 this can be closed now right?

**Comment by stuartnelson3** [comment]
yes, thanks for following up!
