### ISSUE TITLE
[docs] Document how to enable Stack Monitoring with agent managed apm-server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5987]
The agent can be configured to expose its suprocesses' metrics as http endpoint by setting `agent.monitoring.http.enabled: true` (exposes processes on `host:port/processes `where the default port is `6791`). An external metricbeat needs to be configured to collect metrics from these endpoints to ship data to ES indices, with moving slightly changed fields to the structure that is expected by Stack Monitoring. 

dependend on https://github.com/elastic/apm-server/issues/5986

**Comment by bmorelli25** [comment]
Note to self: links changed in https://github.com/elastic/elasticsearch/pull/79411 should be updated when these docs are added.

**Comment by bmorelli25** [comment]
Related to https://github.com/elastic/observability-docs/issues/942

**Comment by bmorelli25** [comment]
Played around with this for a bit but couldn't get it working. Here's what I did:

0. Assume an EA is running with the APM integration installed
1. Update `elastic-agent.yml` to include:
```
agent.monitoring.http.enabled: true
```
2. Stop then restart the agent: https://www.elastic.co/guide/en/fleet/current/start-stop-elastic-agent.html
3. I verified stats were showing up by navigating to http://localhost:6791/processes/apm-server-default/stats
4. Download metricbeat to the same host as Elastic Agent. Configure ES output or Cloud ID
5. Enable beat-xpack `./metricbeat modules enable beat-xpack`
6. Configure `modules.d/beat-xpack.yml` to point to 6791.
```
- module: beat
  xpack.enabled: true
  period: 10s
  hosts: ["http://localhost:6791"]
  username: remote_monitoring_user
  password: password
```
7. Start Metricbeat https://www.elastic.co/guide/en/beats/metricbeat/7.15/metricbeat-installation-configuration.html#start
8. Send APM data

Data flows into the APM app, but I'm not seeing anything in stack monitoring.

**Comment by simitt** [comment]
@stuartnelson3 can you help figure this out please?

**Comment by stuartnelson3** [comment]
metricbeat is trying to scrape from `http://localhost:6791` directly. If you add `basepath` to indicate that the stats are not at `/`, it should work, ie.

```yml
- module: beat
  xpack.enabled: true
  period: 10s
  hosts: ["http://localhost:6791"]
  basepath: "/processes/apm-server-default" # <= right here
```

**Comment by bmorelli25** [comment]
Added a basepath. Not seeing anymore 404s in the logs, but I'm still not seeing anything in the Stack Monitoring tab in Kibana 

```
{"log.level":"info","@timestamp":"2022-02-03T15:25:54.772-0800","log.logger":"monitoring","log.origin":{"file.name":"log/log.go","file.line":184},"message":"Non-zero metrics in the last 30s","service.name":"metricbeat","monitoring":{"metrics":{"beat":{"cpu":{"system":{"ticks":370,"time":{"ms":13}},"total":{"ticks":559,"time":{"ms":28},"value":559},"user":{"ticks":189,"time":{"ms":15}}},"info":{"ephemeral_id":"185f0bf8-2d6f-48c9-92f0-105234e6c03c","uptime":{"ms":123387},"version":"8.0.0-rc2"},"memstats":{"gc_next":22470848,"memory_alloc":12655584,"memory_total":43117976,"rss":63963136},"runtime":{"goroutines":51}},"libbeat":{"config":{"module":{"running":1}},"output":{"events":{"acked":6,"active":0,"batches":3,"total":6},"read":{"bytes":1662},"write":{"bytes":20519}},"pipeline":{"clients":2,"events":{"active":0,"published":6,"total":6},"queue":{"acked":6}}},"metricbeat":{"beat":{"state":{"events":3,"success":3},"stats":{"events":3,"success":3}}},"system":{"load":{"1":5.1006,"15":6.2051,"5":6.2813,"norm":{"1":0.425,"15":0.5171,"5":0.5234}}}},"ecs.version":"1.6.0"}}
{"log.level":"info","@timestamp":"2022-02-03T15:26:24.774-0800","log.logger":"monitoring","log.origin":{"file.name":"log/log.go","file.line":184},"message":"Non-zero metrics in the last 30s","service.name":"metricbeat","monitoring":{"metrics":{"beat":{"cpu":{"system":{"ticks":378,"time":{"ms":7}},"total":{"ticks":575,"time":{"ms":15},"value":575},"user":{"ticks":197,"time":{"ms":8}}},"info":{"ephemeral_id":"185f0bf8-2d6f-48c9-92f0-105234e6c03c","uptime":{"ms":153384},"version":"8.0.0-rc2"},"memstats":{"gc_next":22470848,"memory_alloc":14470384,"memory_total":44932776,"rss":62476288},"runtime":{"goroutines":51}},"libbeat":{"config":{"module":{"running":1}},"output":{"events":{"acked":6,"active":0,"batches":3,"total":6},"read":{"bytes":1666},"write":{"bytes":20518}},"pipeline":{"clients":2,"events":{"active":0,"published":6,"total":6},"queue":{"acked":6}}},"metricbeat":{"beat":{"state":{"events":3,"success":3},"stats":{"events":3,"success":3}}},"system":{"load":{"1":4.4526,"15":6.1152,"5":6.0259,"norm":{"1":0.3711,"15":0.5096,"5":0.5022}}}},"ecs.version":"1.6.0"}}
{"log.level":"info","@timestamp":"2022-02-03T15:26:54.771-0800","log.logger":"monitoring","log.origin":{"file.name":"log/log.go","file.line":184},"message":"Non-zero metrics in the last 30s","service.name":"metricbeat","monitoring":{"metrics":{"beat":{"cpu":{"system":{"ticks":384,"time":{"ms":6}},"total":{"ticks":588,"time":{"ms":13},"value":588},"user":{"ticks":204,"time":{"ms":7}}},"info":{"ephemeral_id":"185f0bf8-2d6f-48c9-92f0-105234e6c03c","uptime":{"ms":183385},"version":"8.0.0-rc2"},"memstats":{"gc_next":22470848,"memory_alloc":17079656,"memory_total":47542048,"rss":64045056},"runtime":{"goroutines":51}},"libbeat":{"config":{"module":{"running":1}},"output":{"events":{"acked":6,"active":0,"batches":3,"total":6},"read":{"bytes":1668},"write":{"bytes":20519}},"pipeline":{"clients":2,"events":{"active":0,"published":6,"total":6},"queue":{"acked":6}}},"metricbeat":{"beat":{"state":{"events":3,"success":3},"stats":{"events":3,"success":3}}},"system":{"load":{"1":3.6509,"15":5.9883,"5":5.686,"norm":{"1":0.3042,"15":0.499,"5":0.4738}}}},"ecs.version":"1.6.0"}}
```

**Comment by bmorelli25** [comment]
I think this is the index that I'm sending data to... so it looks like data is being ingested.

<img width="1081" alt="Screen Shot 2022-02-03 at 5 57 04 PM" src="https://user-images.githubusercontent.com/5618806/152459820-5bc92582-5544-4ee4-9805-4e753aefba3e.png">

Yup, definitely there. But the Stack monitoring page is still not populating.

<img width="1029" alt="Screen Shot 2022-02-03 at 5 59 56 PM" src="https://user-images.githubusercontent.com/5618806/152460093-d67f6fef-5f41-4779-9c11-bcf8dbc61526.png">

**Comment by stuartnelson3** [comment]
confirmed that it works on cloud and when running locally with apm-integration-testing + elastic-agent in a docker container. How are you spinning up your `8.0.0-rc2` cluster? I'm starting up the latest rc2:

```
# ./scripts/compose.py start 8.0.0-rc2 --bc 27a50a27 --no-apm-server --remove-orphans
```

and then in a separate window, after elasticsearch has come up, starting elastic-agent:
```
# TOKEN=$(curl -fsSL -XPOST "http://admin:changeme@localhost:9200/_security/service/elastic/fleet-server/credential/token/token1"|jq -r .token.value)
# docker pull docker.elastic.co/beats/elastic-agent:8.0.0-rc2
# docker run --name elastic-agent-local -it \
    --env KIBANA_FLEET_SETUP=1  \
    --env FLEET_SERVER_ENABLE=1 \
    --env ELASTICSEARCH_HOST="http://localhost:9200" \
    --env FLEET_SERVER_SERVICE_TOKEN=$TOKEN \
    --env FLEET_INSECURE=1 \
    --env FLEET_ENROLL=1  \
    --env KIBANA_FLEET_HOST="http://localhost:5601" \
    --env KIBANA_FLEET_PASSWORD="changeme" \
    --env KIBANA_FLEET_USERNAME="admin"  \
    --env ELASTIC_APM_LOG_LEVEL=debug \
    --env ELASTIC_APM_LOG_FILE=stderr \
    --network host \
    -v (pwd)/elastic-agent.yml:/usr/share/elastic-agent/elastic-agent.yml \
    --rm docker.elastic.co/beats/elastic-agent:8.0.0-rc2
```

the `elastic-agent.yml` i'm using sets `agent.monitoring.http.enabled: true`, then I install the apm-integration and update the elasticsearch endpoint in fleet to `http://0.0.0.0:9200`.

**Comment by bmorelli25** [comment]
Thanks, Stuart. Your docker example works perfectly for me!

> How are you spinning up your 8.0.0-rc2 cluster?

Previously I was running everything from source. Since then, I've also tried sending data to an 8.0.0-rc2 ESS cluster, and I've tried using Kibana's `yarn start` + `yarn es snapshot`. Data flows into `.ds-.monitoring-beats-8-mb-2022.02.04-000001` every time, but I cannot populate the stack monitoring page except for with your docker example.

**Comment by bmorelli25** [comment]
FINALLY got this working. The trick? You need to monitor Elasticsearch as well. I was only monitoring APM. Enabling Elasticsearch monitoring enables the Stack Monitoring UI as the UI keys off the `cluster_uuid` field of `.monitoring-es-*` first.

I'll update my above PR with this change.

**Comment by simitt** [comment]
> FINALLY got this working. The trick? You need to monitor Elasticsearch as well. I was only monitoring APM. Enabling Elasticsearch monitoring enables the Stack Monitoring UI as the UI keys off the cluster_uuid field of .monitoring-es-* first.

Oh wow; I wasn't aware of that. @jasonrhodes is this expected behavior?
