### ISSUE TITLE
[docs] Document how to customize index settings and ILM policies for managed apm-server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5988]
By default, an empty custom component template is created per data stream. If users want to change index settings and/or ILM policies they can use these component templates for any customization. Custom templats are not overwritten on upgrade. 

* `GET _index_template/<data-stream>` to identify the custom component template name (`composed_of`)
* `GET _component_template/t<custom-component-name>` to retrieve custom component template settings
*  `PUT  _component_template/t<custom-component-name>` to update it, for example:
```
PUT _component_template/traces-apm@custom
{
 "template": {
   "settings": {
     "number_of_shards": 3 
   }
 }
}
```

Document that default ILM policies might be changed within minor version upgrades. This is not considered a breaking change, but helps to continually improve and adapt the index management to new features and requirements. If users want to avoid any surprises, they are supposed to make use of setting up a custom ILM policy.

**Comment by Mpdreamz** [comment]
Should we document this under: https://www.elastic.co/guide/en/apm/guide/current/apm-tune-elasticsearch.html ? 


The custom component template names are fixed right? We can just document the `PUT _component/template/<name>` invocation?

**Comment by bmorelli25** [comment]
@Mpdreamz We have custom ILM docs in that bucket already: https://www.elastic.co/guide/en/apm/guide/8.0/ilm-how-to.html. AFAIK though, the edits to `@custom` templates have not been fixed to persist through version upgrades, so we may need to remove these docs prior to 8.0.

This is the issue I'm tracking: https://github.com/elastic/kibana/issues/121184.

**Comment by simitt** [comment]
Setting custom ILM policies that are persisted between updates is supposed to be working. https://github.com/elastic/kibana/pull/111197 moved the `settings` from the index template to the default component template, allowing users to overwrite the `settings` via the `custom` component template. This means that users can generate their own ILM policies and set the policy name in the custom component templates settings. This should be persisted between updates.

**Comment by bmorelli25** [comment]
Silvia is right. I misunderstood https://github.com/elastic/kibana/issues/121184.

I'll close this issue as documentation already exists in 7.17+ for custom APM ILM
