### ISSUE TITLE
Stop storing unsampled transactions

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#5997]
Stop storing unsampled transactions by setting `apm-server.sampling.keep_unsampled: false`. 

This probably breaks alerting and ML job. Figure out what needs to be done to make this a smooth change with as little user impact as possible. (Collaborate with the @elastic/apm-ui team on this).

**Comment by sqren** [comment]
Alerting now uses transaction metrics when enabled. Correlations and ML jobs are still WIP.

**Comment by graphaelli** [comment]
Depends on https://github.com/elastic/kibana/issues/108466

**Comment by axw** [comment]
Proposal: https://docs.google.com/document/d/17wNGGh3u53tQsl938FZmQBa-If8TFKEGyto-Jvjzobk/edit
