### ISSUE TITLE
Document "Why is APM Server a separate component"

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#602]
This can serve as inspiration: https://discuss.elastic.co/t/trying-to-understand-apm-architecture-why-a-dedicated-apm-server-process/117876/2

**Comment by palash25** [comment]
Hi @roncohen I'm new to elastic and I would like to get familiar with it and eventually contribute some code to it too. But right now I would like to get started with writing the docs and I think this issue would be a right fit for me please assign this to me. :smile: 
And I guess this is the file that needs to be changed https://github.com/elastic/apm-server/blob/master/docs/guide/index.asciidoc , right?

**Comment by roncohen** [comment]
hey @palash25! Yes, that would be a fine place to put that documentation. Thank you for your interest. Looking forward to your PR!
