### ISSUE TITLE
Speed up systemtests

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6034]
The systemtests currently take ~25m on CI:

Python Tests (~16minutes): 
* 10 minutes for initial downloads, builds and starting of the environment
* 6 minutes for running the python tests

Go System Tests (~9minutes) :
* 56s: `TestAgentConfig`
* 36s: `TestFleetIntegrationAnonymousAuth`
* 36s: `TestTailSamplingUnlicensed`
* 29s: `TestFleetPackageNonMultiple`
* 22s: `TestTailSampling`
* 14s: `TestAPMServerInstrumentationAuth` (3 sub-tests, 5s each)
* 9s: `TestKeepUnsampled` (2 sub-tests, 5s each)
There's a bunch of tests that take roughly 5sec, for example: 
`TestTransactionAggregation`, `TestServiceDestinationAggregation`, `TestDataStreamMigrationIngestPipeline`, `TestIngestPipelinePipeline`, `TestOTLPGRPCAuth`, `TestJaegerGRPCMuxed`, `TestJaegerGRPCMuxedTLS`, `TestJaegerGRPCSampling`

Although the python tests take longer over time, we should rather focus on making the Go system tests performant and keep moving python system tests over to the new system.

**Comment by axw** [comment]
https://github.com/elastic/kibana/issues/110500 will help with this. Increasingly, as we keep adding tests which rely on data streams.

**Comment by simitt** [comment]
Closing as the python tests have been removed, and some setup related improvements have landed.
