### ISSUE TITLE
Log level value not displayed for generated APM log.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/apm-server#6037]
**Kibana version:**
7.15 BC1 Kibana Cloud Cloud-prod environment 

**Host OS and Browser version:**
APM & Fleet, All

**Preconditions**
1.  7.15 BC1 Kibana Cloud Cloud-prod environment should be available.
```
Kibana version: 7.15 BC1
BUILD 43636
COMMIT d791226d9385122f33f4a5ca38fa5369012fbec3
Artifact link: https://staging.elastic.co/7.15.0-d9929120/summary-7.15.0.html
```
2. Managed host should be available under Agents tab.

**Steps to reproduce:**
1. Enable logs and metrics at cloud deployment.
2. Wait for 1-2 mins for action to complete.
3. Got to stack monitoring Tab in kibana.
4. Validate data sync at apm & fleet overview resource usage.
5. Restart Kibana.
6. Hit below api through command prompt with Admin rights: curl -i copied_apm_url/invalid 
7. Go to logs tab.
8. Apply event.dataset filter for below: "apm.log" 

**Reference Link:**
https://github.com/elastic/kibana/issues/99470

**Actual Result:**
- "elastic_agent.apm" data events are available on Logs tab however, log level value is not displayed.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/130603329-3688830f-530b-4536-9971-20a5a800e0cb.png)

**Comment by simitt** [comment]
I saw the same behavior for elastic agent logs, don't believe this is an actual apm-server issue, but rather a log collection issue.

**Comment by dikshachauhan-qasource** [comment]
Hi @simitt Thanks for the feedback on reported issue

**Comment by axw** [comment]
This is a duplicate of https://github.com/elastic/apm/issues/463 I think?

https://github.com/elastic/apm/issues/463#issuecomment-952523895

**Comment by dikshachauhan-qasource** [comment]
Hi @axw 

Yes, These are duplicates and I'm closing out this one and we can follow up on the other ticket.

Thanks
QAS
