### ISSUE TITLE
Add Kibana index pattern(s) to the integration package

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#6059]
The APM UI installs an index pattern so that users can view APM documents in Discover, which requires index patterns. This is particularly important because of the `View sample document` actions in the APM UI, which take the user from the APM UI to Discover.

The index pattern is built by apm-server (`apm-server export index-pattern`), and manually copied across to Kibana. This is cumbersome.

Fleet integration packages can also define index patterns. We should investigate this approach as an alternative: add index pattern(s) to the package, and rely on Fleet to install them; remove the APM UI code that creates the index pattern.

**Comment by axw** [comment]
Turns out the Fleet does not honour the index pattern assets in packages, so it's not currently possible. I'll open an issue about that soon.

**Comment by axw** [comment]
Given that Fleet doesn't currently install package-specified index patterns, I'm no longer sure this is the right direction.

I think we can pare back the index pattern we install to the bare essentials: the timestamp field and index pattern. Kibana should use field metadata (via _field_caps) for deciding the appropriate default formatter. I think that's all we need. Seems overkill to implement installation in Fleet for this.

**Comment by sqren** [comment]
> This is particularly important because of the `View sample document` actions in the APM UI, which take the user from the APM UI to Discover.

I just want to call out that we don't strictly need the index pattern from APM Server to do this. With a small adjustment the index pattern can be generated automatically when Kibana starts up. The only disadvantage is that any custom formatters set by beats won't be applied. Is that something we want to do instead?

**Comment by axw** [comment]
IMO, for the sake of simplicity we should do that. Maybe we could hard code a handful of field formatters in Kibana code then? They won't be changing frequently. Longer term I'm hoping we can just rely on Kibana to pull field metadata out of _field_caps, and there'll be no need to hard code anything.

**Comment by sqren** [comment]
> Maybe we could hard code a handful of field formatters in Kibana code then?

Yes, that sounds doable.

**Comment by sqren** [comment]
Created https://github.com/elastic/kibana/issues/110635 to track this for apm ui

**Comment by axw** [comment]
Thanks @sqren, I'll close one this for now then.
