### ISSUE TITLE
deprecate the APM Server standalone binary >= 8.0

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6060]
The default way of installing and running the APM Server will be to manage it via Elastic Agent from >= `8.0`. While some standalone binaries still continue to be distributed, they are going to be deprecated. We will need to flag this on the download page. 

@bmorelli25 can you provide guidance around how to do this?

**Comment by bmorelli25** [comment]
Sure can. I've opened elastic/observability-docs#1023 to track all of the related changes for 8.0.
