### ISSUE TITLE
index template has no match, patch_match or mapping_type

### ISSUE THREAD

**Issue by hjmwijnen** [elastic/apm-server#6074]
**APM Server version** (`7.14.0`):

**Description of the problem including expected versus actual behavior**:
The dynamic index template mapping for the histogram field has no match, patch_match or mapping_type set.

**Steps to reproduce**:

 1. Extract apm-server 7.14.0
 2. Export template: ./apm-server export template >template.json
 3. Observe histogram mapping has no match, patch_match or mapping_type set.
 `{
  "histogram": {
    "mapping": {
      "type": "histogram"
    }
  }
}`
 4. Installation: curl -u "user:pass" -X PUT -H "Content-Type: application/json" "https://server/_template/apm-server" -d@"template.json"
 5. Error returned: 
 `{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"template must have match, path_match or match_mapping_type set {mapping={type=histogram}}"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: template must have match, path_match or match_mapping_type set {mapping={type=histogram}}","caused_by":{"type":"mapper_parsing_exception","reason":"template must have match, path_match or match_mapping_type set {mapping={type=histogram}}"}},"status":400}`

**Comment by axw** [comment]
Please create a topic at https://discuss.elastic.co/c/apm for unconfirmed bugs in the future.

> Export template: ./apm-server export template >template.json

If you don't specify `--es.version`, the exported template will be compatible with the same version of Elasticsearch as the APM Server version (i.e. 7.14.0). I'm guessing that you're using an older version of Elasticsearch. Can you please confirm which version of Elasticsearch you have?

If you have an older version of Elasticsearch, then you need to add `--es.version`. For example, if you have Elasticsearch v7.10.0: `./apm-server export template --es.version=7.10.0`

**Comment by hjmwijnen** [comment]
ah, you are totally right, apologies for the inconvenience.. thanks!
