### ISSUE TITLE
Don't create high cardinality transaction names in self-instrumentation

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#6085]
When `instrumentation.enabled: true` is configured, apm-server uses `go.elastic.co/module/apmhttp` to instrument its HTTP server: https://github.com/elastic/apm-server/blob/ad6601dfb8d064a4b1e1b7c16c4a8475b944a6d7/beater/server.go#L160

Because we're using the low-level apmhttp wrapper, and not a router-specific instrumentation, transactions are simply named after the URL path. This can lead to high cardinality transaction names. We should ensure the transaction names are limited, perhaps by using a router such as `httprouter` along with router-specific instrumentation (`apmhttprouter` in this case).

**Comment by felixbarny** [comment]
> transactions are simply named after the URL path

Sounds like this violates the [HTTP instrumentation spec](https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-http.md)

> In case a name cannot be automatically determined, and a custom name has not been provided by other means, the transaction should be named `<METHOD> unknown route`
