### ISSUE TITLE
Stop recording `transaction.duration.{sum.us,count}` metrics

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#6176]
Agents capture and send `transaction.duration.sum.us` and `transaction.duration.count` metrics to apm-server, which we have been dutifully recording as part of transaction breakdown metrics. The original intention behind these was to enable metrics-based UI.

We now capture transaction latency distributions in apm-server, so the above mentioned metrics are no longer needed. They're not used anywhere, so let's stop recording them.

**Comment by simitt** [comment]
fyi @elastic/apm-ui

**Comment by sqren** [comment]
Sounds good to me. Not used in the ui.
