### ISSUE TITLE
Disable source context for in-app span frames before 6.2?

### ISSUE THREAD

**Issue by watson** [elastic/apm-server#622]
Today all span stack frames will include 5 lines of source code for in-app frames and zero for library frames. We have discussed whether it would be worth the Elasticsearch storage savings if we changed that default to not collect source code for in-app span frames as well (a user can always change this default in the agents), but we never reached a conclusion. As this can be considered a breaking change in the agents, we should decide this before version 6.2 is launched.

Note that this decision does not affect the source code we collect for error stack traces.

One downside of making this change at this points is that the UI isn't optimized for not having any source code. For the next version, I think we should consider just displaying the stack trace like a normal stack trace if there's no source code. This is how it would look today:

![image](https://user-images.githubusercontent.com/10602/35811433-c40e6f2c-0a8e-11e8-89f9-4ee75f664c50.png)

@beniwohli If I remember correctly, you had some numbers on the storage cost savings for a Python app with heavy load?

ping @elastic/apm-ui @elastic/apm-agent-devs @makwarth @roncohen

**Comment by beniwohli** [comment]
I don't have numbers for the no-context-lines-at-all case yet. The only-for-in-app-frames case reduced storage use by about two thirds for the opbeans-python app. 

I guess one of the questions we need to answer is, for which case do we optimize? For the first-use experience, which you run locally, or for production use with thousands of transactions per minute? And if we go for first-use-experience, how do we keep people from blowing up their production cluster when they simply deploy what is working locally/staging to production?

**Comment by watson** [comment]
Time is up in regards to 6.2. @beniwohli and I decided to change the defaults, so that we don't collect any source code for spans.
