### ISSUE TITLE
Add a delete phase to APM ILM policies

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#6223]
APM data reduces in value as it ages. Users generally do not want to look at a distributed trace from 2 months ago.

We should consider adding a delete phase to APM's ILM policies to keep costs in check. Each data stream may retain data for a longer period by default; metrics consume less space and provide greater long-term value than individual traces.

**Comment by stuartnelson3** [comment]
Should we just add a delete phase at 60d as the default? 60+ days for metrics even starts to seem old to me, but users could easily supply a modified policy if they want more

**Comment by stuartnelson3** [comment]
eg.
```diff
diff --git a/idxmgmt/ilm/config.go b/idxmgmt/ilm/config.go
index 4f80c69d3..04746c83c 100644
--- a/idxmgmt/ilm/config.go
+++ b/idxmgmt/ilm/config.go
@@ -255,6 +255,12 @@ func defaultPolicies() map[string]Policy {
                                                                "readonly": map[string]interface{}{},
                                                        },
                                                },
+                                             "delete": map[string]interface{}{
+                                                     "min_age": "60d",
+                                                     "actions": map[string]interface{}{
+                                                             "delete": map[string]interface{}{},
+                                                     },
+                                             },
                                        },
                                },
                        },
```

**Comment by axw** [comment]
> Should we just add a delete phase at 60d as the default? 60+ days for metrics even starts to seem old to me, but users could easily supply a modified policy if they want more

Not across the board. 60d is too long for traces. It might be okay for many users for metrics, but there will be users who want to use metrics (namely transaction and span metrics) for comparisons over a longer period. The primary goal here is to keep costs down by default, and metrics are typically much cheaper than traces.

If customising ILM policies (and having customisations survive upgrade) were straightforward through the UI, then I think the default matters a lot less. As things are it's still going to be somewhat involved: create a new ILM policy, update the `@custom` component template with the right Elasticsearch index settings. Ideally we would provide a more guided experience.

Re https://github.com/elastic/apm-server/issues/6223#issuecomment-933348056, I think we'll do this just in the integration package and leave the standalone ILM policy as-is as it won't exist in 8.0.
