### ISSUE TITLE
APM server 7.15.0 breaks json value in capturing API body by not escaping quotes

### ISSUE THREAD

**Issue by mraliagha** [elastic/apm-server#6250]
Since I have upgraded to APM server 7.15.0 (on Elastic cloud) when capture_body is enabled JSON body is stored in a single field. This is not different from the older versions. However, the value of JSON message stored is not normalised it means if there are any characters such as quotations in that field, it must be escaped. This is used to work in 7.14.x but seems to be broken after it's upgraded.

Example of an APM message in 7.14.0

```
{
  "http": {
    "request": {
      "method": "PUT",
      "body.original": "[{\"channel_id\":\"123456\",\"channel_name\":\"Test\",\"source_username\":null,\"url\":\"xyz.com\"}]"
    }
  }
}
```

Same message in 7.15.0:

```
{
  "http": {
    "request": {
      "method": "PUT",
      "body.original": """[{"channel_id":"123456","channel_name":"Test","source_username":null,"url":"xyz.com"}]"""
    }
  }
}
```

P.S: I am using java-agent (1.26.0) with Spring boot 2.5.4

**Comment by simitt** [comment]
As clarified in the [discuss forum](https://discuss.elastic.co/t/apm-capture-body-is-broken-after-upgrading-from-7-14-0-to-7-15-0/285300), the escaping is fine, but the ingest processor is broken, as described in https://github.com/elastic/apm-server/issues/6255.
