### ISSUE TITLE
Missing sentences in the docs

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#627]
When looking at https://www.elastic.co/guide/en/apm/server/master/configuration-template.html, I noticed some incomplete sentences:

> setup.template.settings
A dictionary of settings to place into the settings.index dictionary of the Elasticsearch template. For more details about the available Elasticsearch mapping options, please

> setup.template.settings._source
A dictionary of settings for the _source field. For the available settings,

@watson found out that https://github.com/elastic/beats/blob/master/libbeat/docs/shared-beats-attributes.asciidoc is not yet copied from beats, which contains certain variables like the Elasticsearch URL.

That's why the asciidoc rendering fails whenever the `{elasticsearch}` template variable is referenced. 

However, the build does not fail with an error but the corresponding line does not get rendered which is quite scary.

So we should at first fix this by copying over the file from beats. But we should also see if we get the build to fail or at least to warn if there are missing variables. Furthermore we should look at ways to reduce copy/paste from beats docs by using git submodules for example. But I guess that one is for another issue.

**Comment by watson** [comment]
@dedemorton would it be possible to have the docs build fail instead in these cases?

**Comment by dedemorton** [comment]
@watson I've been asking for this for awhile: https://github.com/elastic/docs/issues/220
