### ISSUE TITLE
db statement is truncated

### ISSUE THREAD

**Issue by devops-akinox** [elastic/apm-server#6303]
https://github.com/elastic/apm-server/blob/a275ed9dc843762b42737a108b47533afa1eef70/processor/otel/traces.go#L535

when string is a db.statement the value is truncated, but db.statement is a text type in the ES data. It should not be truncated before knowing if it is a keyword or a text.

Either we should truncate only when we are sure it is a keyword (truncate in every case statement) or for the db statement we use v.StringVal() as a value directly

**Comment by axw** [comment]
Thanks for the issue, I agree that this one should not be truncated.
