### ISSUE TITLE
Remove `apm-server.transaction.aggregation.enabled`

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#6348]
Transaction metrics will become increasingly critical to the APM UI. We turned them on by default in 7.13.

To minimise complexity, we should now deprecate the configuration to enable/disable; they should always be produced in 8.0, with no option to disable them.

**Comment by simitt** [comment]
We have documented the option to be [experimental](https://www.elastic.co/guide/en/apm/server/current/transaction-metrics.html), also in the [cloud docs](https://www.elastic.co/guide/en/cloud/current/ec-manage-apm-settings.html#ec-apm-settings). The option is not in the apmpackage, so we only have to deprecate and remove it for standalone.

**Comment by marclop** [comment]
I think the correct setting name is `apm-server.aggregation.transactions.enabled`.

There is also an enable setting for serviceDestination aggregations, should we look into always enabling that by default and drop the setting?

**Comment by axw** [comment]
@marclop good thought, yes I think so. If service destination metrics aren't produced then the Dependencies view in the UI won't work.

**Comment by marclop** [comment]
I'll open a separate issue for it.
