### ISSUE TITLE
Profile memory usage

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#639]
Transactions seem to have a multiplying affect on memory usage - a 17 MB payload increases process memory by many times that amount.

This demonstrates apm-server RSS at various transaction sizes sent with very low request rates.  Baseline RSS is 16 MB.  The plateaus are:

1. 8 MB payload,  single serial request (1 rps)
1. 8 MB payload, 2 concurrent requests (2 rps) & 17 MB, single serial request (.56 rps)
1. ignore
1. 17 MB, 2 concurrent requests (1 rps)

![image](https://user-images.githubusercontent.com/83483/35891772-e71105d0-0b73-11e8-9930-08892d9d2e5b.png)

**Comment by jalvz** [comment]
I am reading this right, that 2 concurrent request every 0.5 seconds leads to memory usage of 0,5gb?

**Comment by graphaelli** [comment]
@jalvz yes, that's correct

**Comment by graphaelli** [comment]
memprofile points to stacktrace transform as one path to explore.  https://github.com/elastic/apm-server/compare/master...graphaelli:mem-profile#diff-45171a069180fd9ebaa6fa421c459273 produces this profile:

![mem](https://user-images.githubusercontent.com/83483/35946077-6c1c2572-0c30-11e8-9f12-33bbbe22ff94.png)

seems like a good place to start digging in

**Comment by roncohen** [comment]
good work @graphaelli!

**Comment by simitt** [comment]
Improvement attempt for `transform` method: https://github.com/elastic/apm-server/pull/673

**Comment by graphaelli** [comment]
Thanks everyone for the amazing progress on this, closing it out.
