### ISSUE TITLE
Introduce version check on installed package

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/apm-server#6425]
We currently validate that the APM integration is installed while running standalone and assume it is when running managed. 

We don't validate the installed package actually satisfies our `Stack Version >= APM Version` constraint. 

A drift in the installed package could mean that APM Server will introduce new fields with wrong mappings. This can lead to a broken UI experience which can be hard to diagnose. 

Opening this up to discuss if we want to:

* Do nothing. 
* Check and warn
* Check and go into wait loop.
* Check and version our write logic.
   * E.g when introducing new fields only write these if we know the integration supports it.

The first 2 options feel trappy to me, the user won't know they are potentially indexing data the wrong way. This could potentially stay un-diagnosed for a long time.

relates: https://github.com/elastic/beats/issues/28643

**Comment by axw** [comment]
I'm going to go ahead with what I described above -- please let me know if you have any concerns. When #28643 is done we might want to update the "wait for integration" code in apm-server standalone to check the installed version.
