### ISSUE TITLE
Support OpenTracing

### ISSUE THREAD

**Issue by DanielYWoo** [elastic/apm-server#649]
We currently collect tracing info as log files in OpenTracing format. We have our own analysis tool and dashboard, we could switch to other analysis tools if only OpenTracing is supported, but the question is, will Elastic APM support OpenTracing?

**Comment by roncohen** [comment]
Thank you for your interest in Elastic APM!

We think OpenTracing is a great initiative and we're looking to be compatible with open standard initiatives.

Which specific agents are you using to collect the information at the moment?

**Comment by DanielYWoo** [comment]
We have our own agent integrated into our own framework, writing OpenTracing compliant logs.

**Comment by felixbarny** [comment]
What do you exactly mean with "OpenTracing format" and "OpenTracing compliant logs"? IIRC, OpenTracing does not specify any specific format.

**Comment by DanielYWoo** [comment]
My bad, what I wanted to say is that my log files contains all the data structures defined in OpenTracing. I guess there is no standard log format or on-wire serialization format yet.

**Comment by DanielYWoo** [comment]
close since duplicate with #412
