### ISSUE TITLE
jvm metrics not displayed with opentelemetry-collector v0.34.0

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/apm-server#6528]
**APM Server version** (`apm-server version`): `apm-server version 7.16.0 (amd64), libbeat 7.16.0 [73339c29675f6f987cd96ffac8d4b24284f0275b built 2021-10-27 20:20:27 +0000 UTC]` (BC2)

**Description of the problem including expected versus actual behavior**:

Running an [otel instrumented sample app](https://github.com/cyrille-leclerc/my-shopping-cart/tree/open-telemetry) correctly showed transaction metrics, but did not show any jvm metrics.

transaction metrics:
![image](https://user-images.githubusercontent.com/1398104/140054607-611e832e-f438-4675-9d64-64add7729f28.png)
jvm metrics:
![image](https://user-images.githubusercontent.com/1398104/140054640-e01a808c-c120-4bd7-b33d-e4bf95c2b8d9.png)

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Start apm-server
 2. Setup and run the sample app locally:
```
# setup
git clone git@github.com:cyrille-leclerc/my-shopping-cart.git
cd my-shopping-cart
git checkout open-telemetry
./mvnw install
npm install copyfiles -g
```
update `setenv.default.sh`:
```diff
diff --git a/setenv.default.sh b/setenv.default.sh
index 9aa3795..4d2ca35 100644
--- a/setenv.default.sh
+++ b/setenv.default.sh
@@ -1,7 +1,8 @@
 export OPEN_TELEMETRY_AGENT_VERSION="1.6.0"
 export OPEN_TELEMETRY_DEPLOYMENT_ENVIRONMENT="staging"

-export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317"
+# export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317"
+export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:55680"


 export OTEL_COLLECTOR_EXPORTER_OTLP_ENDPOINT="http://localhost:8200"
 ```
 3. in one terminal window, start postgres: `docker run --rm -e POSTGRES_PASSWORD=test -e POSTGRES_USER=test -e POSTGRES_DB=test -p 5432:5432 postgres`
 4. in one terminal window, start the collector: `docker run --rm -it --name collector --net=host -v (pwd)/collector-config.yml:/etc/collector-config.yml otel/opentelemetry-collector-contrib --config=/etc/collector-config.yml`. config available [here](https://gist.github.com/stuartnelson3/d3f19e99c69634379e35710d89d5f707)
 5. in one terminal window, start the backend app in the `anti-fraud-java` dir
 6. in one terminal window, start the frontend app in the `frontend-java` dir
 7. in one terminal window, start the load generating app in the `monitor-java` dir

**Comment by stuartnelson3** [comment]
Note: jvm metrics are also missing when using apm-server as the otel exporter otlp endpoint, `export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:8200"`

**Comment by axw** [comment]
I think the issue here might just be that metrics aren't enabled by default -- you have to set `OTEL_METRICS_EXPORTER=otlp` explicitly, and I don't see that being set in my-shopping-cart anywhere.

I had some trouble getting the test app to build on my machine, so I wrote a hello world Java program and ran it with opentelemetry-java-instrumentation. With `OTEL_METRICS_EXPORTER=otlp`, and `OTEL_IMR_EXPORT_INTERVAL=1000` (send metrics every 1s), I'm seeing JVM metrics.

**Comment by stuartnelson3** [comment]
:+1: confirmed, works with `OTEL_METRICS_EXPORTER=otlp`
