### ISSUE TITLE
Automated benchmarks 2.0

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6549]
Rethink our current benchmarking setup for APM Server to make it more actionable and useful. Ideally with this work we would have a design proposal ready for the benchmarking framework, a good understanding of how we can use this in the future for benchmark analysis for different shapes of events and a rough understanding about the involved complexity. 

We want to build on top of and grow work started in [ambench](https://github.com/elastic/apm-server/blob/master/systemtest/cmd/apmbench/main.go)

**Comment by simitt** [comment]
@marclop with the Benchmark 2.0 proposal and https://github.com/elastic/apm-server/issues/7216 Is there anything left before being able to close this out?

**Comment by marclop** [comment]
I will re-review the proposal document and will close this after I've addressed your and Andrew's comments yesterday.
