### ISSUE TITLE
Enable frontend endpoint by default

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#655]
@elastic/apm-server , I think we should enable the frontend endpoint by default in 6.3.
Any Thoughts? Are there any blockers for this?

**Comment by beniwohli** [comment]
I'm a big fan of "secure by default", and the frontend endpoints are somewhat of a problem security wise, there's no way around that. By disabling them by default and informing the user about the trade-offs, we can at least give them a chance to make an informed decision.

**Comment by jahtalab** [comment]
@beniwohli , Would you please elaborate on your security concerns?
In my view, the security concerns either should be addressed regardless of frontend configuration or they're the same concerns that other providers of the same kind (the kind that accepts data from web applications) need to deal with and there are known mitigation for them.

**Comment by beniwohli** [comment]
We can't use a secure token for frontend agents, thereby allowing everybody to write stuff into the users elasticsearch instance. Like I said, there's no way to prevent this _if_ you want to use frontend agents, but I don't think we should open up the apm-server by default.

**Comment by jalvz** [comment]
@alvarolobato @jahtalab do we have a final decision on this?

**Comment by simitt** [comment]
Is this something that is still open for discussion or can we close the issue? (@jahtalab)

**Comment by jahtalab** [comment]
I think we can close it for now, thanks for the reminder @simitt!

Will reopen if needed!
