### ISSUE TITLE
Add additional fields to transaction metrics for serverless UI 

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-server#6576]
Transactions reported for AWS lambda functions populate the boolean fields `faas.coldstart` and `faas.trigger.type`.
Furthermore, the field `service.runtime.name` is required to determine whether a service is in a serverless context.
In order to derive additional, Lambda-specific insights it would be very useful, if the transaction metrics derived from transaction events in the APM could include the `service.runtime.name`, `faas.coldstart` and `faas.trigger.type` fields (when available) into the metric documents reported to Elasticsearch.

**Comment by stuartnelson3** [comment]
I took a quick look at this -- it appears that this is supported if the incoming `service.runtime.name` is nested under `transaction.context`. Is this correct?

**Comment by AlexanderWert** [comment]
There is a more general issue that includes this one: https://github.com/elastic/apm-server/issues/6843

**Comment by simitt** [comment]
Closing this issue, as it's covered by #6843
