### ISSUE TITLE
Consider removing `enum` limitation on log level in JSON Schema

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-server#665]
At the moment, the log level is limited to a fairly concise list of levels: https://github.com/elastic/apm-server/blob/4feeae5a028b8f6626f839b7e44edba033541c8e/docs/spec/errors/error.json#L66

This mostly works for Python, where the available log levels are [well defined](https://docs.python.org/3/library/logging.html#logging-levels) and seldom changed. But other logging frameworks allow easy customization of log levels, e.g. [Log4j](https://logging.apache.org/log4j/2.x/manual/customloglevels.html).

I don't think that the X-Pack UI depends on the log levels being restricted. Please correct me if I'm wrong @sqren @formgeist.

**Comment by beniwohli** [comment]
actually, this list is missing a somewhat, ahem, `CRITICAL` python level as well...

**Comment by sqren** [comment]
@beniwohli No - I don't even think we show them in the UI atm.

**Comment by simitt** [comment]
As nobody argumented against removing the enum, I'll remove it.

**Comment by beniwohli** [comment]
Awesome, thanks @simitt!
