### ISSUE TITLE
Update apt installation instructions

### ISSUE THREAD

**Issue by mikker** [elastic/apm-server#666]
Just ran through this guide on a brand new Ubuntu and ended up with an outdated version: https://www.elastic.co/guide/en/apm/server/current/setup-repositories.html

`6.x-prerelease` needs to be corrected to `6.x`. According to @beniwohli, the beats team has a fancy thing going in their docs at: https://raw.githubusercontent.com/elastic/beats/faeb3d1f3fe9193fb2b7c31bb6d33bb477fb69ce/libbeat/docs/repositories.asciidoc

**Comment by simitt** [comment]
@graphaelli are you testing this since you labelled `In Review`?

**Comment by graphaelli** [comment]
I don't recall doing that.  I can certainly test it.

**Comment by graphaelli** [comment]
Those docs currently install 6.3.0, the latest release in the 6 series.  I'll sync up our docs with beats and elasticsearch, where these instructions are replaced with `Version 6.4.0 of Elasticsearch has not yet been released.`

**Comment by graphaelli** [comment]
Actually, we don't build 6.x docs any more and this is already done on master - https://www.elastic.co/guide/en/apm/server/master/setup-repositories.html
