### ISSUE TITLE
`traces-apm.rum-*` refers to non-existent ILM policy

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#6755]
The RUM traces data stream refers to the `traces-apm.rum-traces-default_policy` (`...rum-traces...`) ILM policy, but it's actually called `traces-apm.rum_traces-default_policy` (`...rum_traces...`).

![image](https://user-images.githubusercontent.com/843579/144041165-db4c8913-eaaf-4adf-b9ed-cd78ddca681a.png)

**Comment by marclop** [comment]
oops, sorry about that, will fix it ASAP

**Comment by axw** [comment]
No worries. Our tools should help us more here, picking up such typos. I'll open an issue to introduce some more structured tooling around APM-specific integration package checks.
