### ISSUE TITLE
Document how to disable sensitive data capture by APM Server

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-server#6775]
There is no mention of `capture_personal_data` APM server configuration in [this documentation page](https://www.elastic.co/guide/en/apm/get-started/current/data-security.html).

The Asciidoc file to update seems to be this one [docs/legacy/guide/data-security.asciidoc](https://github.com/elastic/apm-server/blob/master/docs/legacy/guide/data-security.asciidoc) 

I'm not aware of any other PII/sensitive data parameter in apm-server, feel free to add others if they are relevant.

**Comment by simitt** [comment]
cc @bmorelli25
