### ISSUE TITLE
Fix systemtest failure on metrics

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6788]
The `TestApprovieMetrics` test is [failing on 8.0](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/8.0/64/tests/) and `master`.
Investigate if this is a testing issue or uncovers a real issue and fix it.

**Comment by marclop** [comment]
I was unable to reproduce in my machine with: `go test -v -count=50 -run TestApprovedMetrics .`.

**Comment by marclop** [comment]
This test has 3 metric sets that have the same timestamp and no other fields that differ between the stored documents, I'll open a PR to update the timestamps to be slightly different, so the sorting / approving works in a deterministic way.
