### ISSUE TITLE
Provide apm-server status

### ISSUE THREAD

**Issue by formgeist** [elastic/apm-server#68]
Having the APM Server installed and running is critical to the APM experience, which is why in terms of both onboarding and continued status, it would great to have a status provided, perhaps into Elasticsearch which can be queried, that it's setup and it's running.

**Comment by ruflin** [comment]
I suggest to start with the definition on what means `apm-server` is available. Also as there can be more then one `apm-server` how will this play into this? In case we have different definitions for available like red, yellow, green, what is the criteria for each?

This ties also into https://github.com/elastic/beats/issues/3422 and should be coordinated with beats.
