### ISSUE TITLE
Docs: Update documentation for managing API keys to authorize requests to the APM Server

### ISSUE THREAD

**Issue by gbamparop** [elastic/apm-server#6844]
Agent API key management support has been added as part of https://github.com/elastic/kibana/issues/77966 and the work has been done in https://github.com/elastic/kibana/pull/119543 and https://github.com/elastic/kibana/pull/120373.

[API keys documentation ](https://www.elastic.co/guide/en/apm/server/current/api-key.html
) in the APM server could be updated to reflect these changes.

A how to guide could also be added in the Kibana [APM docs](https://www.elastic.co/guide/en/kibana/7.16/apm-how-to.html).

The management view is located in Kibana (APM -> Settings -> Agent Keys) and users can check the privileges they want to assign to the API key being created instead of pasting them in JSON into the role descriptors box like they do in the stack management.

https://user-images.githubusercontent.com/5831975/145042317-432602f7-89ae-4f14-9ed7-1c71047ee87e.mov

Please also find some screenshots below that you might find useful:

![image](https://user-images.githubusercontent.com/5831975/145041520-e8481135-1093-433c-940e-461a18bd157b.png)

![image](https://user-images.githubusercontent.com/5831975/145041852-b0f70cc5-f324-4874-b4ec-2df0e7750cdc.png)

**Comment by gbamparop** [comment]
@bmorelli25 could you please have a look at this?

**Comment by simitt** [comment]
Updated and now available in https://www.elastic.co/guide/en/apm/guide/current/api-key.html#create-an-api-key.

**Comment by gbamparop** [comment]
> Updated and now available in https://www.elastic.co/guide/en/apm/guide/current/api-key.html#create-an-api-key.

@simitt the docs in this link seem to suggest to create an API key through `Stack Management > API keys` instead of `APM settings -> Agent Keys` mentioned in the description.

**Comment by bmorelli25** [comment]
Repeating what I [posted](https://elastic.slack.com/archives/C95SB62AG/p1651870344637949) on Slack:

@elastic/apm-server I'm confused about the `sourcemap:write` privilege. Is this privilege still required for anything? As far as I can tell, the `/assets/v1/sourcemaps` endpoint was removed in https://github.com/elastic/apm-server/pull/6447.

I tried spinning up an 8.2 standalone APM Server and when I hit `http://127.0.0.1:8200/assets/v1/sourcemaps`, I get:

```
{
  "error": "404 page not found"
}
```

Maybe the backward compatibility with the apm-server/elasticsearch connection (`apm-server.rum.source_mapping.elasticsearch.*`) requires this privilege? I'm not sure how to test that one.

**Comment by axw** [comment]
@bmorelli25 you're quite right, there is no longer any code path in apm-server that checks this privilege. It would only make sense when using an older version of apm-server, e.g. 7.17.x.

**Comment by bmorelli25** [comment]
Thanks, @axw.

@gbamparop should I create an APM UI issue? I guess we should remove the `sourcemap:write` privilege from the flyout. Alternatively, we could name it something different and update the privileges to those required for Kibana's [RUM source map API](https://github.com/elastic/kibana/edit/main/docs/apm/api.asciidoc):

```json
{
   "apm": {
      "applications": [
         {
            "application":"kibana-.kibana",
            "privileges":[ "feature_apm.all" ],
            "resources":[ "space:default" ]
         }
      ]
   }
}
```

**Comment by gbamparop** [comment]
> @gbamparop should I create an APM UI issue? I guess we should remove the `sourcemap:write` privilege from the flyout. Alternatively, we could name it something different and update the privileges to those required for Kibana's [RUM source map API](https://github.com/elastic/kibana/edit/main/docs/apm/api.asciidoc):

@bmorelli25 please do, that would be great so we can have a look what the best approach should be.
