### ISSUE TITLE
[APM] Dashboard graph is hard to read and not consistent with one shown in APM view

### ISSUE THREAD

**Issue by liza-mae** [elastic/apm-server#686]
Kibana version: 6.2.2 BC1

Elasticsearch version: 6.2.2 BC1

Server OS version: Ubuntu tar

Browser version: Chrome latest

Browser OS version: OSX

Original install method (e.g. download page, yum, from source, etc.):
From staging

Description of the problem including expected versus actual behavior:

APM dashboard graph is hard to read

Steps to reproduce:

Install Elasticsearch, Kibana and APM
Import APM data
Go to APM
From the dashboard view of Response Times, the graph just has dots that are hard to read and not all the dots as shown in the key are displayed this is in comparison to the graph shown in APM which shows better.

<img width="1571" alt="36324263-10ab0b4e-1311-11e8-875a-d9b29f3b103c" src="https://user-images.githubusercontent.com/23424008/36450145-3a1731c4-164a-11e8-8a3a-1a6f0b35b187.png">

**Comment by liza-mae** [comment]
Originally opened as: https://github.com/elastic/kibana/issues/16789

**Comment by alvarolobato** [comment]
@liza-mae  are you still seeing this problem? Usually there is more data and you would see a line instead of dots.

**Comment by liza-mae** [comment]
@alvarolobato it appears I do still see this on 6.3.1, not sure if it is expected behavior, but should it look the same as the graph represented under APM -> Request, if so then that one does show a line, but not the one from dashboard.

**Comment by simitt** [comment]
Closing this issue related to #1673 (removing to bundle dashboards with APM Server and Kibana).
