### ISSUE TITLE
Update Java agent attacher version

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6887]
Update the Java agent attacher version to `1.28.2` once it is out. 

@felixbarny please let us know when it is available.

**Comment by felixbarny** [comment]
1.28.4 is available now. Please prioritise updating before 8.0 is released.

**Comment by marclop** [comment]
https://github.com/elastic/apm-server/pull/6948 (update to `1.28.3`) wasn't back ported to `8.0`, should we back port it? and then do this?

**Comment by felixbarny** [comment]
The vmargs conversion doesn't have to be backported but the update to 1.28.4 includes important security updates. Both `vmarg` and `vmargs` works.
