### ISSUE TITLE
Bind to a Unix Domain Socket or Windows Named Pipe instead of a TCP port

### ISSUE THREAD

**Issue by watson** [elastic/apm-server#689]
I've been thinking that it would be a good feature if we allowed the APM Server to bind to a Unix Domain Socket or Windows Named Pipe instead of a TCP port. This removes the overhead of the TCP handshake and allows the agent to do proper IPC when the APM Server is installed on the edge machine. This doesn't change the fact that the agents will be speaking HTTP to the server, but the underlying socket will be different.

I originally started researching this because I hoped it would allow for greater throughput, but it seems we currently have a bottleneck elsewhere, e.g:

Throughput when binding to TCP socket:

```
$ autocannon -m POST -H 'Content-Type: application/json' -b '{"service":{"name":"foo","agent":{"name":"foo","version":"1"}},"errors":[{"timestamp":"2017-01-01T00:00:00Z","log":{"message":"foo"}}]}' http://localhost:8200/v1/errors
Running 10s test @ http://localhost:8200/v1/errors
10 connections

Stat         Avg    Stdev   Max
Latency (ms) 2.31   2.26    70.98
Req/Sec      3555.2 324.04  3928
Bytes/Sec    434 kB 38.1 kB 479 kB

36k requests in 10s, 4.34 MB read
```

Throughput when binding to Unix Domain Socket:

```
$ autocannon -S /tmp/apm-server.sock -m POST -H 'Content-Type: application/json' -b '{"service":{"name":"foo","agent":{"name":"foo","version":"1"}},"errors":[{"timestamp":"2017-01-01T00:00:00Z","log":{"message":"foo"}}]}' http://localhost/v1/errors
Running 10s test @ http://localhost/v1/errors (/tmp/apm-server.sock)
10 connections

Stat         Avg    Stdev Max
Latency (ms) 2.45   2.47  67.17
Req/Sec      3397.4 408.5 4044
Bytes/Sec    416 kB 51 kB 493 kB

34k requests in 10s, 4.14 MB read
```

Binding to a Unix Domain Socket or a Windows Named Pipe like this also means that the system admin don't have to consider the risk of the open TCP port.

Updating the APM Server to bind to a Unix Domain Socket is fairly easy. All I did was change the following in `beater/server.go`:

```diff
 func newServer(config *Config, report reporter) *http.Server {
        mux := newMuxer(config, report)

-       return &http.Server{
-               Addr:           config.Host,
+       server := &http.Server{
                Handler:        mux,
                ReadTimeout:    config.ReadTimeout,
                WriteTimeout:   config.WriteTimeout,
                MaxHeaderBytes: config.MaxHeaderSize,
        }
+
+       unixListener, err := net.Listen("unix", "/tmp/apm-server.sock")
+       if err != nil {
+               panic(err)
+       }
+       server.Serve(unixListener)
+
+       return server
 }
```

This doesn't correctly close the socket on close, and will fail if the `.sock` file is present on boot, but it was enough for my little test.

What do you think?

**Comment by graphaelli** [comment]
I think it's a good idea to give users flexibility for deployment.  We may even want to consider multiple listeners simultaneously, eg https and unix domain socket.  As you've demonstrated,  this wouldn't be hard to implement - I'd anticipate a good percent of the work going into refactoring the tests.  @roncohen - perhaps you can prioritize based on expectations of use?
