### ISSUE TITLE
Add TBS configuration options to apmpackage

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6895]
Make required changes to the apmpackage for the TBS related configuration and default values. 

Current configuration options:
```
apm-server:
 sampling:
   keep_unsampled: bool
   tail:
     enabled: bool
     policies:
       - service.name: string
         service.environment: string
         trace.name: string
         trace.outcome: string
         sample_rate: number
     interval: duration
     ingest_rate_decay: duration
     storage_dir: string
     storage_gc_interval: duration
     ttl: duration
     elasticsearch:
```

precondition for https://github.com/elastic/kibana/issues/121534

**Comment by axw** [comment]
I added `tail_sampling_interval` and `tail_sampling_policies` in https://github.com/elastic/apm-server/pull/6139, so tail-based sampling could be tested via Fleet:

- `tail_sampling_interval` is a duration string, e.g. "30s"
- `tail_sampling_policies` is a list of tail-sampling policies with the format as in the issue description

We could leave `ingest_rate_decay`, `storage_gc_interval`, and `ttl` for the initial release, to keep things simple and minimal.

**Comment by simitt** [comment]
Ah I missed that; so this would basically only concern following options then:
*  `apm-server.sampling.tail.storage_dir` - do we expect users to temper with that? I'm inclined to also not make it configurable until we have some requests for it. 
*  `apm-server.sampling.tail.elasticsearch.*` - dependend on https://github.com/elastic/apm-server/issues/7025

**Comment by axw** [comment]
> - `apm-server.sampling.tail.storage_dir` - do we expect users to temper with that? I'm inclined to also not make it configurable until we have some requests for it.

No we don't. In fact, I removed that config in https://github.com/elastic/apm-server/pull/6236 :smile: 

> apm-server.sampling.tail.elasticsearch.* - dependend on TBS support for APM Integration when using non-Elatsichsearch output #7025

Can we close this issue, and follow up on #7025?
