### ISSUE TITLE
Upgrade Java agent attacher and remove argument conversion

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-server#6898]
With https://github.com/elastic/apm-agent-java/pull/2310 merged, the next release of the Java agent (> 1.28.2) will include an attacher CLI that accepts `--include/exclude-vmarg` in addition to `--include/exclude-vmargs`. So by upgrading to it, the APM server can remove its current conversion from `--include/exclude-vmarg` (as it is received from Fleet) to `--include/exclude-vmargs`.

**Comment by axw** [comment]
Closed by #6948
