### ISSUE TITLE
Clarify that Elastic Agent standalone is not officially supported for APM usecase

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6921]
It should be clear from our docs that APM Integration is only officially supported with **Fleet-managed** Elastic Agent (using Fleet) and APM Server might not be fully functional with standalone Elastic Agent.

@bmorelli25 I don't think that we explicitly discussed this before. Is there a chance to add a note to the `7.16` docs?

**Comment by bmorelli25** [comment]
Ah. Thanks. Yup, I can add this to the docs.

**Comment by bmorelli25** [comment]
Our upgrade guides mention this limitation, but I've opened https://github.com/elastic/observability-docs/pull/1647 to add this to our quick start as well.
