### ISSUE TITLE
`processor.event: log` not being dropped

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/apm-server#6925]
**APM Server version** (`apm-server version`): https://github.com/elastic/apm-server/commit/2d1c27052b5ddce37858c85b48a84561752f791d

**Description of the problem including expected versus actual behavior**:

I sent an OTLP span with an event. I expected there to be no log events indexed, but one was.

**Steps to reproduce**:

 1. start `apm-server`: `./apm-server -e -E apm-server.data_streams.enabled=false`
 2. start this [OTLP server](https://gist.github.com/stuartnelson3/5df3fc136e856b10d712b753d94e4d56)
 3. `curl http://localhost:8080/users/123` the OTLP server
 4. Run the following query and check for a `processor.event` field with `log`:
    ```
    GET apm-*,traces-apm*,logs-apm*/_search
    {
      "_source": [false],
      "fields": [
        "processor.event"
      ]
    }
    ```
5. One result has
    ```
    "fields" : {
      "processor.event" : [
        "log"
      ]
     }
    ```

**Comment by simitt** [comment]
@marclop can you take a look at this?

**Comment by marclop** [comment]
Thanks for the ping, I believe this is not a regression since data streams can only be enabled now, I don't think you can disable them. The description in my PR states:

```
Fixes a bug which prevented the libbeat pipeline client from using the
drop_event processor we use to drop events with processor.event: log
set, when data streams are disabled.
```

The change can't be verified for `8.0` with what we're currently planning to ship. Does that make sense?

**Comment by stuartnelson3** [comment]
makes sense, I was wondering about that (the fact that the documents were still being indexed into a data stream)
