### ISSUE TITLE
[cloud] Making changes to ES host configuration puts APM Server in shutdown mode

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6964]
When making a configuration change to the Fleet setting's Elasticsearch output, the (managed) APM Server goes into shutdown mode, without actually shutting down. The only way of recovering is to restart the APM Server. 
This behavior was not reproducable locally, but could only be observed on cloud. 

## How to reproduce
0. Spin up an ECE environment and create a cloud deployment including APM for version`7.16.2` (behavior on ESS has not been tested)
1. Migrate APM from standalone to managed by Elastic Agent
2. Navigate to `Kibana/Fleet/Agent policies/Fleet Settings` and change the ES host to the internal URL, for example:
<img width="1773" alt="Screenshot 2021-12-30 at 15 36 19" src="https://user-images.githubusercontent.com/5555349/147761853-e7ae3215-4864-4962-b412-28e6ef48c38b.png">

3. Wait a bit and then try to send data to the APM Server. Observe following response:
```
% curl -i -k -H "Content-type: application/x-ndjson" -H "Authorization: Bearer ${APM_SERVER_TOKEN}" --data-binary @testdata/intake-v2/events.ndjson ${APM_SERVER_URL}/intake/v2/events


HTTP/2 503
content-type: application/json
date: Thu, 30 Dec 2021 13:53:47 GMT
x-cloud-request-id: GfTCIACqSIuzIsh1CWQzQg
x-content-type-options: nosniff
x-found-handling-cluster: 3c2764843bdf439fa321182c08ecd18c
x-found-handling-instance: instance-0000000000
content-length: 94

{
  "accepted": 0,
  "errors": [
    {
      "message": "server is shutting down"
    }
  ]
}
```

The same behavior can be observed when making changes to anything in the `Elasticsearch output configuration yaml`, such as setting `worker: 4`.

**Comment by marclop** [comment]
I have been unable to reproduce this in ESS today, but I haven't tested in an ECE environment, I can do that next. Following the these steps:

1. Create `7.16.3` deployment with APM & Fleet Server set.
2. Migrate to managed mode via `Kibana > Observability > APM > Schema`
3. Update integration to `7.16.1`.
4. Navigate to `Fleet > Agent Policies > Settings`, add `experimental: true` in the free text box.

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/7286993/149469915-1f3a855e-403c-478d-a7ea-f7450bdb2e3a.png">

5. Issue curl command:

```console
$ curl -Ls -H "Authorization: Bearer ${APM_SERVER_TOKEN}" ${APM_SERVER_URL}/
{
  "build_date": "2022-01-06T23:27:35Z",
  "build_sha": "fde0af4fa2b9f39e518b333c5be56cf8be215ca0",
  "publish_ready": true,
  "version": "7.16.3"
}
```

I was also able to send data with this small Go program:


```go
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"go.elastic.co/apm"
)

func main() {
	version := "undefined"
	if len(os.Args) > 1 {
		version = os.Args[1]
	}
	name := fmt.Sprintf("apm-server-%s", version)
	apm.DefaultTracer.SetSampler(apm.NewRatioSampler(0.0))
	tx := apm.DefaultTracer.StartTransaction(name, "type")
	ctx := apm.ContextWithTransaction(context.Background(), tx)
	span, ctx := apm.StartSpan(ctx, name, "type")
	span.Duration = time.Second
	span.End()
	tx.Duration = 2 * time.Second
	tx.End()
	apm.DefaultTracer.Flush(nil)
	fmt.Printf("%s: %+v\n", name, apm.DefaultTracer.Stats())
}
```

```console
$ go run main.go
apm-server-undefined: {Errors:{SetContext:0 SendStream:0} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:1 TransactionsDropped:0 SpansSent:0 SpansDropped:0}
```

I also verified that the APM Server is being restarted by the Elastic Agent on every output config change, am I missing something?

**Comment by simitt** [comment]
I caught this when testing with ECE; have you also tried to changing to the internal ES host instead of only making changes in the yml box?

**Comment by marclop** [comment]
yes, I changed it to an invalid host and issued an HTTP request, and I can see that `publish_ready` is `false`.

```console
$ curl -Ls -H "Authorization: Bearer ${APM_SERVER_TOKEN}" ${APM_SERVER_URL}/
{
  "build_date": "2022-01-06T23:27:35Z",
  "build_sha": "fde0af4fa2b9f39e518b333c5be56cf8be215ca0",
  "publish_ready": false,
  "version": "7.16.3"
}
```

<img width="1740" alt="image" src="https://user-images.githubusercontent.com/7286993/149701251-64ae6dfd-6ce1-4990-8181-8659fbd26542.png">

**Comment by simitt** [comment]
I just reproduced it on latest ESS master, with changing the ES hosts to the *valid* internal ES route (e.g. from `https://52f4ad1bed5c4f11a8b120010d687783.192.168.43.10.ip.es.io:9243` to `http://52f4ad1bed5c4f11a8b120010d687783.192.168.43.10.containerhost:9244`. 

```
curl -k -i -H "Authorization: Bearer xyz" https://ae9998b07bbb4345a94f46d793e9e03d.apm.192.168.43.10.ip.es.io:9243

HTTP/2 200
content-type: application/json
date: Mon, 17 Jan 2022 11:17:27 GMT
x-cloud-request-id: UuuUO4TGS369u1Qo9ZGOoA
x-content-type-options: nosniff
x-found-handling-cluster: 2263ee44ffaa44a48bd8a99c5832d80f
x-found-handling-instance: instance-0000000000
content-length: 150

{
  "build_date": "2022-01-16T00:31:39Z",
  "build_sha": "df433279cb70245cec0a1d66434a5fd9a443851f",
  "publish_ready": true,
  "version": "7.17.0"
} 
```

But the APM Server logs showing errors and no data being ingested:
```
{"log.level":"error","@timestamp":"2022-01-17T11:17:33.688Z","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":60},"message":"server is shutting down","service.name":"apm-server","url.original":"/intake/v2/events","http.request.method":"POST","user_agent.original":"apm-agent-nodejs/3.26.0 (opbeans-node 1.0.0)","source.address":"192.168.43.1","http.request.id":"8af57c5a-ae51-40f5-87c6-d955a059a05f","event.duration":466737190,"http.response.status_code":503,"error.message":"server is shutting down","ecs.version":"1.6.0"}
```

**Comment by marclop** [comment]
I've tried to reproduce this issue again toda Cloud Staging with the latest `7.17` but was unable to:

I have been alternating back and forth the public and internal Elasticsearch endpoint, but wasn't able to make the APM Server go into this deadlock scenario:

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/7286993/153141693-a1e75087-a638-4018-9ff9-23ed5bb9691f.png">

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/7286993/153141524-cb22127c-15dc-48f0-b3ed-0d89e926bf05.png">

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/7286993/153141810-235ad272-12bd-40f6-b683-d8667a80d993.png">

The Go program that I've been running is:

```go
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"go.elastic.co/apm"
)

func main() {
	name := "apm-server-undefined"

	for {
		for i := 0; i < 100; i++ {
			tx := apm.DefaultTracer.StartTransaction(name, "type")
			ctx := apm.ContextWithTransaction(context.Background(), tx)
			span, ctx := apm.StartSpan(ctx, name, "type")
			span.Duration = time.Second
			span.End()
			tx.Duration = 2 * time.Second
			tx.End()
			<-time.After(time.Millisecond)
		}
		<-time.After(time.Second)
		apm.DefaultTracer.Flush(nil)
		fmt.Printf("%s: %+v\n", name, apm.DefaultTracer.Stats())
	}
}
```

And it's been running steadily, reporting an Error.SendStream each time the APM Server restarts.

```
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:82800 TransactionsDropped:0 SpansSent:82800 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:82900 TransactionsDropped:0 SpansSent:82900 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83000 TransactionsDropped:0 SpansSent:83000 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83100 TransactionsDropped:0 SpansSent:83100 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83200 TransactionsDropped:0 SpansSent:83200 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83300 TransactionsDropped:0 SpansSent:83300 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83400 TransactionsDropped:0 SpansSent:83400 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83500 TransactionsDropped:0 SpansSent:83500 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83600 TransactionsDropped:0 SpansSent:83600 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83700 TransactionsDropped:0 SpansSent:83700 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83800 TransactionsDropped:0 SpansSent:83800 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:83900 TransactionsDropped:0 SpansSent:83900 SpansDropped:0}
apm-server-undefined: {Errors:{SetContext:0 SendStream:13} ErrorsSent:0 ErrorsDropped:0 TransactionsSent:84000 TransactionsDropped:0 SpansSent:84000 SpansDropped:0}
```

**Comment by simitt** [comment]
It sounds like an `ECE` only problem then. Let's sync on this and reproduce together on an ECE instance.

**Comment by simitt** [comment]
This issue was never raised by anyone and not reproducable after the inital investigation. Closing the issue and we can reopen if it becomes a problem for anyone.
