### ISSUE TITLE
[meta] running java-attacher

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/apm-server#7023]
# Status

When running under linux, forking and running the java-attacher is not currently allowed, as APM Server uses seccomp to filter allowed syscalls. 

# Options
## ~(A) Provide seccomp rules to allow the required syscalls~
The `fork/exec` privileges added via seccomp-bpf need to be limited to the java-attacher process.

The below matrix tracks the status of forking and running the java-attacher with the listed operating system/architecture + apm-server mode pair.

| | standalone | managed |
| --- | --- | --- |
| linux/amd64 | https://github.com/elastic/apm-server/issues/7017 | |
| linux/386 | https://github.com/elastic/apm-server/issues/7018 | |
| linux/arm | https://github.com/elastic/apm-server/issues/7019 | |
| linux/arm64 | https://github.com/elastic/apm-server/issues/7020 | |
| darwin | https://github.com/elastic/apm-server/issues/7021 | |
| windows | https://github.com/elastic/apm-server/issues/7022 | |

**nb.** Linux rows are split out by CPU architecture, because each will require an update to its own seccomp policy. seccomp is only supported in linux.

Related Issues: 
- How to set the seccomp policy in managed mode: elastic/elastic-agent#95

## ~(B) Investigate static analysis of fork/exec syscalls~
Verify APM Server's dynamic call graph https://github.com/elastic/apm-server/issues/7109

## (C) Disable seccomp
https://github.com/elastic/apm-server/issues/7305
----

~Update: We decided to move forward with option (A) for now. Focusing on seccomp is more aligned with currently ongoing effort in the agent team. With option (B) it would be hard to ensure that all code paths are checked for restricted syscalls. Given some related conversations around moving subprocesses to their own Integration or Sub-Integration this might not be needed in the future.~

Update the second: it turns out seccomp filters don't support our needs (i.e. allowing only some programs to be executed). After further consideration, we have decided it is safe to disable the current seccomp implementation in APM Server.

**Comment by simitt** [comment]
This is blocked at the moment by https://github.com/elastic/beats/issues/29631 and figuring out how custom seccomp filters should be configured and applied when managed by Elastic Agent.

**Comment by simitt** [comment]
2022-01-25: Updated description to reflect also the alternative option.

**Comment by graphaelli** [comment]
Now that Option C has been selected and the changes for it have been merged, what is left to satisfy this issue?

**Comment by axw** [comment]
I think the only thing left to do is test across all supported platforms:
 - https://github.com/elastic/apm-server/issues/7022
 - https://github.com/elastic/apm-server/issues/7021

**Comment by stuartnelson3** [comment]
I've tested on linux/amd64, but not 386

**Comment by simitt** [comment]
@stuartnelson3 please close this issue once you finished testing on linux.
