### ISSUE TITLE
modelidexer: Dynamically size the number of available bulk indexers 

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#7024]
## Description

APM Server will GA the new Model Indexer in 8.0.0, which improves the bulk indexing performance of APM Server. It defaults to having 10 available bulk indexers, providing a maximum of 10 bulk index requests per APM Server. https://github.com/elastic/apm-server/blob/cf9b7dc086bc87a98da1fb46647915b8b585a3d4/model/modelindexer/indexer.go#L99-L103

Since our long term goal is to have a dynamically sized stack without needing user input to tune certain settings, it would be ideal if the model indexer could dynamically tune the number of bulk indexers.

## Proposed high-level feature

The idea would be to introduce key metrics that would allow the APM Server to take some actions and resize the number of maximum bulk requests and available bulk indexers that it can use at a time.

It would be best to introduce this feature when Elasticsearch supports auto scaling based on indexing load, since that would avoid overwhelming Elasticsearch when increasing the number of bulk indexers when APM Server requires it.

## Challenges

The feature is not without challenges, there are a few variables that we should consider when implementing it.

### Elasticsearch topology

The more we know about the Elasticsearch cluster where APM Server issues bulk requests, the better decisions we can make. 

For instance, if we know or consider the number of Elasticsearch nodes available to process bulk indexing requests, we can establish the maximum number of bulk indexers we can grow to.

Knowing whether Elasticsearch auto-scaling is enabled is also important, since by increasing the number of bulk indexers we can increase the indexing load and "force" Elasticsearch to auto-scale. (This assumes that Elasticsearch can autoscale based on ingest load)

### APM Server topology

Knowing whether there are more than 1 APM Server can also be crucial. When more than 1 APM Server is writing to the same Elasticsearch cluster, increasing the number of bulk indexers on each APM server in isolation can lead to an unreasonable increase in ingest load, thus, the bulk indexer auto-scaling should have some sort of coordination.

### APM Server resources

Last, considering the available resources for the APM Server to consume is crucial, otherwise, the APM Server may run out of memory when the number of bulk indexers is increased, causing the process to crash and leading to data loss and intermittent restarts. Available memory and cgroup limits should be considered.

## Related Issues / Prior Work 

https://github.com/elastic/apm-server/commits/f/onweek-adaptive-sampling

**Comment by marclop** [comment]
@axw rightly mentioned that before we go down this long route we should explore the tradeoffs of providing a higher default for `MaxRequests`.

Now that some of the new benchmarking framework has landed, we should compare the throughputs and also watch the Elasticsearch output metrics to ensure that we don't overwhelm the underlying Elasticsearch cluster too easily.

During the Adaptive Sampling OnWeek, it seemed that a 2GB single Elasticsearch cluster with no other workloads sending data to it was able to allow for ~13-15 MaxRequests before 429 were received.

**Comment by simitt** [comment]
Moving this to backlog for now, given the scheduled issues to make the numer of `MaxRequests` configurable (https://github.com/elastic/apm-server/issues/7719) and measure the impact of a larger number (https://github.com/elastic/apm-server/issues/7718).

**Comment by axw** [comment]
Should we close this now?

**Comment by simitt** [comment]
Good call, the auto-scaling of available bulk indexers was replaced by https://github.com/elastic/apm-server/issues/9181.
