### ISSUE TITLE
source.ip / client.ip mapping, no overrides as of 7.16

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/apm-server#7029]
as of 7.16, `source.ip` is always set to the ip address of the device where the request came from. This change was made in https://github.com/elastic/apm-server/pull/6152
There is no way for the user to override this behaviour. 

In previous versions, it was possible to provide headers such as `forwarded`, `x-real-ip`, `x-forwarded-for` to force apm-server to set the `source.ip` to the` client.ip`

Imagine running a node backend service, that gets requests forwarded from a proxy. This `source.ip` field would always point to the proxy, only the `client.ip` field would have the real client ip. Any malicious behaviour would not be detected properly on the APM data, since the source.ip data always looks benign. 

The Security Solution of Elastic (the UI, detection rules and ML jobs) are always using the source.ip field for detecting threats. 

I suggest that we talk to the security teams or someone more familiar with ECS to figure out if reverting some of the changes is the right step forward, or if we need to make changes on the security side to accommodate this behaviour.

**Comment by axw** [comment]
Thanks for raising this @LucaWintergerst. I'm a little hesitant to just use the header value in `source.ip` as it can be spoofed. As a workaround, it should be possible to use an ingest processor. I'll discuss with the security folks how we should proceed.

**Comment by axw** [comment]
The ECS team recommend that we store the originating client's IP in `source.ip` and `client.ip`, and the network peer (proxy) IP in `source.nat.ip`. The naming is a bit odd, but it sounds like the best option we have at the moment.

**Comment by axw** [comment]
Verified with 8.2.0-BC1:

- sent some RUM events with no special headers, confirmed the peer IP address was stored in `source.ip` and `client.ip` as-is, and no `source.nat.ip` address was recorded
- sent some RUM events with X-Real-IP, confirmed the X-Real-IP address was stored in `source.ip` and `client.ip`, and the peer address was stored in `source.nat.ip`
