### ISSUE TITLE
Automate apmpackage publishing to package-storage (production) and release to EPR

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7070]
The apm integration needs to be merged to the https://github.com/elastic/package-storage `production` branch aligned with the stack release. 

Required steps when the stack release happened:
1. Promote the apm package from `snapshot` to `production`; [tooling for promoting the package](https://github.com/elastic/elastic-package#elastic-package-promote) is already available.
2. [Release changes to the elastic package registry](https://github.com/elastic/integrations/blob/master/docs/developer_workflow_promote_release_integration.md#steps) for `snapshot` and `production`. 

When the apm integration is bundled with Kibana, the integration still needs to be released in the current version to ensure it shows up in https://docs.elastic.co/en/integrations/apm.

**Comment by simitt** [comment]
Related to https://github.com/elastic/apm-server/issues/6970. 
@kseniia-kolpakova this would be another automation step related to apm integration release.

**Comment by mtojek** [comment]
Dropping a small tiny peek into what we're building now.

Teams building their own packages (like APM) will use the [Publishing](https://internal-ci.elastic.co/job/package_storage/job/publishing-job-remote/build?delay=0sec) pipeline (WIP), to publish their packages to https://epr.elastic.co/.

Key features:
* a single, flat package space - no stages, no promotion, no manual actions
* package revisions are idempotent - it's forbidden to override already published revision (unless there is good justification, for example, broken package, illegal content, etc.)
* packages strongly depend on semver
* incoming packages are validated against the latest package spec
* incoming packages can be signed with Elastic key
* once a package is pushed, it will be available to the world and waiting for indexing with cloud Package Registry instances (triggered automatically)

**Comment by simitt** [comment]
Closing this issue, as the production stage is going to be removed with v2.
