### ISSUE TITLE
Testing upgrade flow from 7.17 to 8.0

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7087]
Conduct dedicated upgrade testing from `7.17` to `8.0` for following scenarios. 

## ESS
* [x] Standalone mode
0. Create 7.17 deployment with APM&Fleet Server and ingest data
1. Upgrade stack to 8.0 and wait until all components are up
3. Verify that the 8.0 APM Integration is installed and used in the deployment
4. Verify that data ingestion still works
5. Verify that APM Server is still running in standalone mode (by navigating to APM Settings and having the migration button available) 
6. Optional: Trigger the migration to managed mode and ensure APM Server is restarted and data ingestion works. 

* [x] Managed mode
0. Create 7.17 deployment with APM&Fleet Server and ingest data
1. Navigate to Kibana/APM/Settings/Schema page and switch to Elastic Agent
2. Upgrade stack to 8.0 and wait until all components are up
4. Verify that data ingestion still works
5. Verify that APM Server is still running in managed mode (by navigating to APM Settings) 

Additionally try to break things through timing, manual configuration changes etc. and ensure deployments are eventually recovered to a working state when all components are upgraded.

## ECE
Repeat the ESS steps with ECE `3.0`. Upgrading to `8.0` should not be supported in earlier versions. 

## On-Prem
* [x] Standalone mode (in prefered upgrade order): 
0. Run Elastic Stack and APM Server `7.17` and ingest data
1. Upgrade the Elastic Stack to 8.0
2. Verify that data ingestion still works
3. Manually install the APM Integration via Kibana Fleet Integration UI
<img width="1380" alt="Screenshot 2022-01-17 at 10 33 41" src="https://user-images.githubusercontent.com/5555349/149744437-aaeb9246-c870-4bb3-8aba-f6cc681f6ccc.png">

4. Upgrade APM Server to 8.0 
5. Ingest data and ensure they show up in the APM UI

* [x] Standalone mode (in any upgrade order): 
0. Run Elastic Stack and APM Server `7.17` and ingest data
1. Upgrade the Elastic Stack and APM Server to 8.0
2. Verify that APM Server issues logs about preconditions not being met when trying to ingest data
3. Manually install the APM Integration via Kibana Fleet Integration UI
4. Ingest data and ensure they show up in the APM UI

* [x] Managed mode (in prefered upgrade order): 
0. Run Elastic Stack, Elastic Agent w. Fleet Server and Elastic Agent enrolled to an agent policy with an APM Integration, all in `7.17` and ingest data
1. Upgrade the Elastic Stack to 8.0
2. Verify that data ingestion still works
3. Upgrade the APM Integration to 8.0
4. Verify that data ingestion still works
5. Upgrade the Elastic Agent including the APM Server to 8.0 
6.  Ingest data and ensure they show up in the APM UI

* [x] Managed mode (in any upgrade order):
Change the upgrade order, but essentially repeat the above steps and ensure that eventually the data ingestion works as expected when all components are upgraded.

**Comment by marclop** [comment]
## On-Prem (Local docker-compose with Elasticsearch data volume)

### Architecture: `linux/arm64`

* [x] Standalone mode (in prefered upgrade order): ✅ 
0. Run Elastic Stack and APM Server `7.17` and ingest data ✅ 
1. Upgrade the Elastic Stack to 8.0 ✅ 
2. Verify that data ingestion still works ✅ 
3. Manually install the APM Integration via Kibana Fleet Integration UI ✅ (`8.0.0-dev6`)
4. Upgrade APM Server to 8.0 ✅ 
5. Ingest data and ensure they show up in the APM UI ✅ 

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/7286993/150053352-b95872ec-a410-4f1a-b959-c2b51c9286ad.png">

* [x] Standalone mode (in any upgrade order): 
0. Run Elastic Stack and APM Server `7.17` and ingest data ✅ 
1. Upgrade the Elastic Stack and APM Server to 8.0 ✅ 
2. Verify that APM Server issues logs about preconditions not being met when trying to ingest data ✅ 
```javascript
...
{"log.level":"error","@timestamp":"2022-01-19T10:45:34.923+0800","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":62},"message":"precondition 'apm integration installed' failed: error querying Elasticsearch for integration index templates: unexpected HTTP status: 404 Not Found ({\"error\":{\"root_cause\":[{\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [traces-apm.sampled] not found\"}],\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [traces-apm.sampled] not found\"},\"status\":404}): to remediate, please install the apm integration: https://ela.st/apm-integration-quickstart","service.name":"apm-server","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-19T10:45:37.461+0800","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":62},"message":"precondition 'apm integration installed' failed: error querying Elasticsearch for integration index templates: unexpected HTTP status: 404 Not Found ({\"error\":{\"root_cause\":[{\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [logs-apm.error] not found\"}],\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [logs-apm.error] not found\"},\"status\":404}): to remediate, please install the apm integration: https://ela.st/apm-integration-quickstart","service.name":"apm-server","ecs.version":"1.6.0"}
...
```
3. Manually install the APM Integration via Kibana Fleet Integration UI ✅ (8.0.0-dev6)

apm-server stopped logging precondition errors.

4. Ingest data and ensure they show up in the APM UI ✅ 

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/7286993/150054500-cd113835-4a3f-42c2-a8db-f88e518d56b8.png">

* [ ] Managed mode (in prefered upgrade order): 
0. Run Elastic Stack, Elastic Agent w. Fleet Server and Elastic Agent enrolled to an agent policy with an APM Integration, all in `7.17` and ingest data ✅  (7.16.0 integration) encountered a Kibana Error when trying to upgrade the integration to `7.16.1` 🔴, which I thought we had fixed. I added a comment on https://github.com/elastic/kibana/issues/121238#issuecomment-1016088348.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/7286993/150062338-4dd0405f-6130-4411-bdb6-0ed98b9f1cb5.png">

1. Upgrade the Elastic Stack to 8.0 ✅ 
2. Verify that data ingestion still works ✅ 
3. Upgrade the APM Integration to 8.0 ✅ (The integration was automatically upgraded for me, didn't need to take action)
4. Verify that data ingestion still works ✅ 
5. Upgrade the Elastic Agent including the APM Server to 8.0 ✅ 
6.  Ingest data and ensure they show up in the APM UI ✅ 

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/7286993/150070102-99274c05-d9e1-4471-826a-8b7da56b1675.png">

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/7286993/150070123-16e7311d-afa3-4386-8455-361971fa6f48.png">


* [x] Managed mode (in any upgrade order): ✅ 
Change the upgrade order, but essentially repeat the above steps and ensure that eventually the data ingestion works as expected when all components are upgraded. 

0. Run Elastic Stack, Elastic Agent w. Fleet Server and Elastic Agent enrolled to an agent policy with an APM Integration, all in `7.17` and ingest data ✅  (7.16.0 integration)
1. Upgrade the Elastic Stack and Elastic Agent to 8.0 ✅ 
2. Verify that data ingestion still works ✅ (The integration was automatically upgraded for me, didn't need to take action)

**Comment by marclop** [comment]
## ESS (Staging)

### Using `7.17.0` and `8.0.0-SNAPSHOT`

* [x] Managed mode 🟥  
0. Create 7.17 deployment with APM&Fleet Server and ingest data ✅ 
1. Navigate to Kibana/APM/Settings/Schema page and switch to Elastic Agent ✅ 
2. Upgrade stack to 8.0 and wait until all components are up 🟥 The Kibana instance wasn't accessible
4. Verify that data ingestion still works 
5. Verify that APM Server is still running in managed mode (by navigating to APM Settings) 


* [ ] Standalone mode
0. Create 7.17 deployment with APM&Fleet Server and ingest data
1. Upgrade stack to 8.0 and wait until all components are up
3. Verify that the 8.0 APM Integration is installed and used in the deployment
4. Verify that data ingestion still works
5. Verify that APM Server is still running in standalone mode (by navigating to APM Settings and having the migration button available) 
6. Optional: Trigger the migration to managed mode and ensure APM Server is restarted and data ingestion works.

**Comment by marclop** [comment]
## ECE

Running the latest `ECE 3.0.0-latest` tag I wasn't able to test the upgrades to `8.0.0-SNAPSHOT` or run the `8.0.0-SNAPSHOT` version since the last build for the `elastic-agent` seems to be broken:

```
Done preparing, starting Elastic Agent and Apm. See Elastic Agent and Apm logs for further output.
2022-01-19T06:25:24+0000 Booting at Wed Jan 19 06:25:24 UTC 2022
Starting in elastic cloud mode
Performing setup of Fleet in Kibana

Policy selected for enrollment:  policy-elastic-agent-on-cloud
{"log.level":"info","@timestamp":"2022-01-19T06:25:29.906Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":573},"message":"Spawning Elastic Agent daemon as a subprocess to complete bootstrap process.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:30.057Z","log.origin":{"file.name":"application/application.go","file.line":67},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:30.058Z","log.origin":{"file.name":"application/application.go","file.line":88},"message":"Agent is in Fleet Server bootstrap mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:30.318Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:30.318Z","log.origin":{"file.name":"application/fleet_server_bootstrap.go","file.line":130},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:30.318Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: [::]:6791 (configured: http://0.0.0.0:6791)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:30.320Z","log.origin":{"file.name":"application/fleet_server_bootstrap.go","file.line":140},"message":"Agent is stopped","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:30.910Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":745},"message":"Waiting for Elastic Agent to start Fleet Server","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:31.912Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is XtCEqeeL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:31.913Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 1 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:32.382Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-01-19T06:25:32Z - message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:32.384Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":66},"message":"Updating internal state","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:32.911Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":778},"message":"Fleet Server - Starting","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-01-19T06:25:33.909Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'degraded'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:33.909Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-01-19T06:25:33Z - message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to DEGRADED: Running on policy with Fleet Server integration: policy-elastic-agent-on-cloud; missing config fleet.agent.id (expected during bootstrap process) - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:36.913Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":759},"message":"Fleet Server - Running on policy with Fleet Server integration: policy-elastic-agent-on-cloud; missing config fleet.agent.id (expected during bootstrap process)","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-01-19T06:25:36.914Z","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls_config.go","file.line":105},"message":"SSL/TLS verifications disabled.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:37.424Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":456},"message":"Starting enrollment to URL: https://instance-0000000001:8220/","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-01-19T06:25:37.527Z","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls_config.go","file.line":105},"message":"SSL/TLS verifications disabled.","ecs.version":"1.6.0"}
Successfully enrolled the Elastic Agent.
{"log.level":"info","@timestamp":"2022-01-19T06:25:38.701Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":260},"message":"Elastic Agent has been enrolled; start Elastic Agent","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:38.701Z","log.origin":{"file.name":"cmd/run.go","file.line":185},"message":"Shutting down Elastic Agent and sending last events...","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:38.701Z","log.origin":{"file.name":"operation/operator.go","file.line":216},"message":"waiting for installer of pipeline 'default' to finish","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:38.701Z","log.origin":{"file.name":"process/app.go","file.line":176},"message":"Signaling application to stop because of shutdown: fleet-server--8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:40.202Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'online'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:40.202Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-01-19T06:25:40Z - message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to STOPPED: Stopped - type: 'STATE' - sub_type: 'STOPPED'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:40.202Z","log.origin":{"file.name":"cmd/run.go","file.line":193},"message":"Shutting down completed.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-19T06:25:40.202Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":66},"message":"Stats endpoint ([::]:6791) finished: accept tcp [::]:6791: use of closed network connection","ecs.version":"1.6.0"}
```

**Comment by simitt** [comment]
Testing on ESS non-production env is currently blocked due to missing upgrade option to `8.0.0-rc` candidates.

**Comment by marclop** [comment]
## ESS (Staging)

### Using `7.17.0` and [`8.0.0-rc2`](https://staging.elastic.co/8.0.0-rc2-5e6da84e/summary-8.0.0-rc2.html) (5e6da84e)

* [x] Standalone mode
0. Create 7.17 deployment with APM&Fleet Server and ingest data ✅ 
1. Upgrade stack to 8.0 and wait until all components are up ✅ 
3. Verify that the 8.0 APM Integration is installed and used in the deployment ✅ 
4. Verify that data ingestion still works ✅ 
5. Verify that APM Server is still running in standalone mode (by navigating to APM Settings and having the migration button available)  ✅ 
6. Optional: Trigger the migration to managed mode and ensure APM Server is restarted and data ingestion works. ✅ 

* [x] Managed mode ✅ 
0. Create 7.17 deployment with APM&Fleet Server and ingest data ✅ 
1. Navigate to Kibana/APM/Settings/Schema page and switch to Elastic Agent ✅ 
2. Upgrade the APM Integration to 7.16.2 ✅ 
3. Check that the bug that set the host in the APM Integration to localhost isn't reproducible ✅ 
2. Upgrade stack to 8.0 and wait until all components are up ✅ 
4. Verify that data ingestion still works ✅ 
5. Verify that APM Server is still running in managed mode (by navigating to APM Settings) ✅ 

* [x] Create a deployment using version `8.0.0-rc2` ✅ 
1. Verify that APM server is running in managed mode and can ingest data ✅

**Comment by marclop** [comment]
## ECE (3.0.0-latest)

### Using [`7.17.0`](https://staging.elastic.co/7.17.0-0a126886/summary-7.17.0.html) (0a126886) and [`8.0.0-rc2`](https://staging.elastic.co/8.0.0-rc2-5e6da84e/summary-8.0.0-rc2.html) (5e6da84e)

* [x] Standalone mode
0. Create 7.17 deployment with APM&Fleet Server and ingest data ✅ 
1. Upgrade stack to 8.0 and wait until all components are up ✅ 
3. Verify that the 8.0 APM Integration is installed and used in the deployment ✅ 
4. Verify that data ingestion still works ✅ 
5. Verify that APM Server is still running in standalone mode (by navigating to APM Settings and having the migration button available)  ✅ 
6. Optional: Trigger the migration to managed mode and ensure APM Server is restarted and data ingestion works. ✅ 

* [x] Managed mode 
0. Create 7.17 deployment with APM&Fleet Server and ingest data ✅ 
1. Navigate to Kibana/APM/Settings/Schema page and switch to Elastic Agent ✅ Ingest data ✅ 
2. Upgrade the APM Integration to 7.16.2  ✅  Ingest data ✅ 
3. Check that the bug that set the host in the APM Integration to localhost isn't reproducible ✅ 
2. Upgrade stack to 8.0 and wait until all components are up ✅ 
4. Verify that data ingestion still works ✅ 
5. Verify that APM Server is still running in managed mode (by navigating to APM Settings) ✅ 

* [x] Create a deployment using version `8.0.0-rc2` ✅ 
1. Verify that APM server is running in managed mode and can ingest data ✅

**Comment by simitt** [comment]
Conducted some additional testing last week with the BC-2 `8.0.0-rc2` and today with BC-3:

## Testcase 1
Env: staging
Version: 7.17.0
Mode: standalone

Changing config options to:
```
apm-server.rum.enabled: false
apm-server.ilm.enabled: false
apm-server.ilm.setup.overwrite: true
```

0. Ingesting data ✅ 
1. data are indexed into apm indices (not ILM) ✅ 
2. Stack Monitoring for 7.17 broken 🔴 (https://github.com/elastic/beats/issues/29920)
3. Upgrading to 8.0.0-rc2 ✅ 
4. Ingesting data successfully ✅ 

## Testcase 2
Testing stack monitoring with latest 8.0.0-rc2( BC3)
Env: staging
Version 8.0.0-rc2 (BC3)
Mode: managed
logs&metrics enabled

0. Ingesting data  ✅ 
1. Stack Monitoring UI working for APM  ✅ 

## Testcase  3
Testing to switch to managed mode and upgrade
Env: staging
Version: 7.17.0 -> 8.0.0-rc2 (BC2)

0. Start with standalone 7.17.0 deployment and index data   ✅ 
1. Edit config to disable ILM, index data   ✅ 
2. Migrate (note the user configs showing up)   ✅ 
3. Index data via integration now, using data streams   ✅ 
4. Upgrade apm-package to 7.16.2   ✅ 
5. Index data  ✅ 
6. Update APM Integration via UI; verify that information is really updated (via apm policy editor and via view policy that is passed to elastic-agent)   ✅ 
5. Index data  ✅ 
8. Upgrade to 8.0.0-rc2 (BC2)   ✅ 
5. Index data  ✅ 

BUG: previous user configurations are lost 🔴 https://github.com/elastic/kibana/issues/123945

**Comment by simitt** [comment]
Closing this issue after through testing from the APM Server team.
