### ISSUE TITLE
Managing the Helm Charts for APM Server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7129]
more details to follow

**Comment by simitt** [comment]
@kseniia-kolpakova could we get some support from the automation team for moving the helm charts to the APM Server and adapting the existing e2e tests for APM Server helm charts (if they need to be adapted).

**Comment by jmlrt** [comment]
👋🏻 @simitt, as discussed last week, we'll create a PR to remove apm-server from the main branch on https://github.com/elastic/helm-charts. Do you have suggestions for the communication we'll have to do explaining why we are removing it when we'll create the public PR? cc @nkammah

**Comment by simitt** [comment]
@chrisdistasio wanted to follow up with you regarding the wording.

**Comment by chrisdistasio** [comment]
@simitt / @jmlrt apologies for the delay--one question, as the functionality is moving to Agent, do we know what version it will be introduced?

**Comment by jmlrt** [comment]
> @simitt / @jmlrt apologies for the delay--one question, as the functionality is moving to Agent, do we know what version it will be introduced?

That's a good question. There is no Elastic Agent chart released on our Helm repository ATM. I know that there is a work in progress in https://github.com/elastic/beats/issues/22572 but I don't know the status, cc @ph @kuisathaverat).

**Comment by chrisdistasio** [comment]
i see these two PRs as well.  https://github.com/elastic/beats/pull/28102, https://github.com/elastic/beats/pull/28103.

i'm a bit uncomfortable with removal/deprecation as it's unclear to me that we have a solid or agreed-upon replacement, but the fact that it is beta creates some space.

@jmlrt do you have a drop dead date for language/public pr?
