### ISSUE TITLE
Update docker image to Ubuntu 20.04

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7138]
Update to latest libbeat version for changing the docker base image from `CentOS` to `Ubuntu 20.04` (https://github.com/elastic/beats/pull/29681)

Pulling in latest libbeat will also add other changes, highlighting the ones relevant for APM:
* Update golang version to `1.17.5`
* Add Elastic Product origin header (https://github.com/elastic/beats/pull/29966)
* Support self signed certs on output (https://github.com/elastic/beats/pull/29229)
* Change logs from `json` to `ndjson` (https://github.com/elastic/beats/pull/28927) and file suffix (https://github.com/elastic/beats/pull/28927)

**Comment by axw** [comment]
Closed by #7137
