### ISSUE TITLE
Mention air-gap requirements in setup docs

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#7219]
With the new requirement of the APM integration package, we now require a local EPR in airgapped environments.

We should head off questions about air-gapped environments by linking from https://www.elastic.co/guide/en/apm/guide/master/apm-quick-start.html and https://www.elastic.co/guide/en/apm/guide/master/apm-server-configuration.html to https://www.elastic.co/guide/en/fleet/master/air-gapped.html

**Comment by simitt** [comment]
@bmorelli25 could you add that to your docs issue collection please?

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/apm-server/pull/7285 and https://github.com/elastic/observability-docs/pull/1570.
