### ISSUE TITLE
Force a timestamp on RUM data

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#723]
Our experience has shown that we cannot rely on timestamps in data ( _durations/elapsed time_ is fine) coming from browsers. It turns out that people routinely have computers that are completely our of sync with time or they have purposely backdated their clocks.

For this reason, we need the APM Server to set the current time on all the data that comes in through the client side endpoints. 

Alternatively, we could make timestamp optional, make sure the JS agent doesn't set a timestamp, and let the APM Server set a timestamp on all the entries that don't have a timestamp set.

**Comment by jahtalab** [comment]
@elastic/apm-server will this be included in 6.3 release?

**Comment by jahtalab** [comment]
Yes please :) , It would be great to get this into 6.3.
