### ISSUE TITLE
Rename `process.ppid` to `process.parent.pid`

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#7256]
[ECS 8.0](https://github.com/elastic/ecs/releases/tag/v8.0.0) removed `process.ppid`, which has been replaced with `process.parent.pid`. We should update the server to do the same thing, and investigate whether an alias from `process.ppid` is needed.

We will also need to update our ingest pipelines to rename `process.ppid` sent by older versions of APM Server.

**Comment by simitt** [comment]
@sqren is the APM UI using the `process.ppid` somewhere or is the information just shown? I'm leaning towards just renaming the field without adding an alias if it is not used anywhere.

**Comment by sqren** [comment]
Feel free to rename. It's used in one place but we can easily change that:
https://github.com/elastic/kibana/blob/8b7395d594e87070e3b84ffdc91ceca1ca8c58cb/x-pack/plugins/apm/common/correlations/constants.ts#L27

**Comment by simitt** [comment]
@sqren would that break anything when viewing older data that still have `process.ppid`?

**Comment by sqren** [comment]
No, it wouldn't break anything. We only use it in an exclude list so as not to display that value for that field to the user. We can simply add the new field to that list.

**Comment by sqren** [comment]
I created an issue to track this on the APM UI side: https://github.com/elastic/kibana/issues/127849
