### ISSUE TITLE
Do not require content-type and content-encoding in RUM requests

### ISSUE THREAD

**Issue by devcorpio** [elastic/apm-server#7271]
# Context

In the JavaScript RUM agent we have been working on a feature that allows the agent to send requests that outlive the browser. One of the mechanisms we also want to add is the [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) one.

Now we can't, because currently we are sending the headers _Accept-Encoding_ (this only in browsers where we compress the payload)  and `Content-Type` with the value `application/x-ndjson` in the intake api requests.

In [this issue](https://github.com/elastic/apm-agent-rum-js/issues/1166) for RUM there are more details about it.

# What we would like is:

The APM server to start handling the request for RUM in a different way, that is: not making `content-type` and `accept-encoding `mandatories anymore (but keeping the validation if sent since older versions of the RUM agent will still keep sending those headers.)

Perhaps the Accept-Encoding part will be a bit trickier since we don't send it always. That happens because not all browsers are compatible with the[ Compression Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API):

_The Compression Streams API provides a JavaScript API for compressing and decompressing streams of data using the **gzip** or deflate formats._

Please, let me know if need more context and information

cc: @vigneshshanmugam

**Comment by axw** [comment]
> The APM server to start handling the request for RUM in a different way, that is: not making content-type and accept-encoding mandatories anymore (but keeping the validation if sent since older versions of the RUM agent will still keep sending those headers.)

You mean `Content-Encoding` right? i.e. the encoding of the request body sent by the RUM agent.

> Perhaps the Accept-Encoding part will be a bit trickier since we don't send it always. That happens because not all browsers are compatible with the[ Compression Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API):

When using the Beacon API, will the RUM agent still compress the body where the Compression Streams API is available? If that is the case, I suppose the server will need to auto-detect the encoding.

This all sounds fine. We would:
 - Assume a Content-Type of `application/x-ndjson` if not specified
 - Sniff the Content-Encoding from the first few request body bytes, if not specified

**Comment by devcorpio** [comment]
Hi @axw ,

Yes, apologies I meant `Content-Encoding`

> When using the Beacon API, will the RUM agent still compress the body where the Compression Streams API is available? 

That is right, we will still compressing the body if Compression Streams API is available

> Assume a Content-Type of application/x-ndjson if not specified
Sniff the Content-Encoding from the first few request body bytes, if not specified

Sounds great!
