### ISSUE TITLE
Fix CI build on integration branches

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/apm-server#7335]
It appears that our builds are red on integration branches (main/8.0/8.1/8.2/7.17) for a while now:

![image](https://user-images.githubusercontent.com/245275/154516074-50fe83ad-b120-41db-a114-f78a451d6749.png)

It's typically one or all of these three tasks:

![image](https://user-images.githubusercontent.com/245275/154516725-f718e5fa-7293-4f03-9ea2-9a9dc371ac26.png)

We should perhaps run less and address anything that's flaky and/or depending on snapshots that could cause a difference in builds/tests after merging.

**Comment by axw** [comment]
- apm-ci/branch is the pipeline, it'll fail if one of the other stages fail
- beats-tester/branch is known to be failing (https://github.com/elastic/beats-tester/issues/211), haven't heard any update on this recently but the plan is to migrate to e2e-testing for smoke tests
- system tests are currently plagued by a handful of flaky tests, which we're already tracking

**Comment by axw** [comment]
Just chatted with @Mpdreamz, we should just disable beats-tester if we're moving to e2e-testing and we don't intend to invest in fixing beats-tester.

**Comment by simitt** [comment]
Created https://github.com/elastic/apm-server/issues/7543 for transitioning beats-tester to e2e testing once the automation team's setup is ready.

**Comment by simitt** [comment]
@axw you mentioned removing the beats-tester from our CI; please use this issue for tracking it.
