### ISSUE TITLE
Move `spans` to their own index. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#734]
Seperate spans from transaction documents by storing in their own index.

**Comment by beniwohli** [comment]
Rationale for this request: spans are by far contributing the most to our elasticsearch resource use. By moving them into their own index, we can facilitate retention strategies (delete old spans, or move them to a cheaper machine in a hot/warm cluster setup).

**Comment by Qard** [comment]
Another advantage is to be able to aggregate on spans as a source of time series data. 👍

**Comment by simitt** [comment]
fyi @elastic/apm-ui

**Comment by makwarth** [comment]
@simitt 👍 when is this planned for?

**Comment by simitt** [comment]
This is merged to `master` and `6.x`. As the UI team let us know that splitting indices does not need any UI changes for `transactions, errors` I also thought it is good to merge for this index split. Are there any concerns?

**Comment by makwarth** [comment]
To make sure, @sqren can you confirm? ^

**Comment by sqren** [comment]
We query all indexes on [`apm*`](https://github.com/elastic/x-pack-kibana/blob/master/plugins/apm/index.js#L38), so no objections from here 👍

**Comment by makwarth** [comment]
👍 Better safe than sorry, etc.
