### ISSUE TITLE
Limit open concurrent tcp connections

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#736]
The APM Server will happily accept and create a go routine for each new incoming connection. 
https://github.com/elastic/apm-server/pull/731 will ensure that we don't start processing more than `concurrent_requests`, but it should be possible to limit incoming requests in some way. 

Since go routines are quite cheap and users may legitimately want to accept many connections, the default restriction should be to a high number, say 1000.

**Comment by graphaelli** [comment]
https://godoc.org/golang.org/x/net/netutil#LimitListener looks like it will do the trick.

**Comment by jalvz** [comment]
great finding!
