### ISSUE TITLE
Metrics without agent version

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-server#7385]
**APM Server version** (`apm-server version`): 7.17.0

**Description of the problem including expected versus actual behavior**:
I noticed that the transaction/span metrics created by the apm server do contain `agent.name`, but not `agent.version`, because the agent version is not part of the aggregation key (https://github.com/elastic/apm-server/blob/647c0394f13900f402ad4a4272f5f564f91784c8/x-pack/apm-server/aggregation/spanmetrics/aggregator.go#L287 resp. https://github.com/elastic/apm-server/blob/647c0394f13900f402ad4a4272f5f564f91784c8/x-pack/apm-server/aggregation/txmetrics/aggregator.go#L477). Was this done intentionally?

**Comment by axw** [comment]
They dimensions included were intended to be minimal.

I don't recall why included `agent.name` now. Do you have a use-case for filtering these metrics by `agent.version`? We could consider including it.

**Comment by tobiasstadler** [comment]
No, I do not really have a use case. I was just curious.
