### ISSUE TITLE
Rename GetProcessors to Processors in registry

### ISSUE THREAD

**Issue by crackerplace** [elastic/apm-server#74]
The name GetProcessors sounds more like a java getter and might not be idiomatic go.For reference [this](https://groups.google.com/forum/#!topic/golang-nuts/3H4kmCP9_wU) and [this](https://www.reddit.com/r/golang/comments/34kd8k/alternative_to_using_getters_and_setters/cqxz78p/).

The method [GetProcessors](https://github.com/elastic/apm-server/blob/master/processor/registry.go#L28) can be renamed to Processors and GetProcessor to Processor.

I can make this change if you think this is sensible.

P.S : Currently the methods on the register are not doing any work.They look like java pojos.

**Comment by ruflin** [comment]
For me it doesn't matter too much if we call it `GetProcessors` or `Processors`. Both works. Let's see what the rest of the team thinks.

For the empty registry functions: HereI think it's important that we keep it as I could see additional logic in it in the future so if we add any, we don't have to change the rest of the code. Also it allows us to keep the variables private. But I'm aware this is personal preference :-)

**Comment by crackerplace** [comment]
Yes,this might not be a breaking change.But as the project is in its initial phases if we follow go [conventions](https://golang.org/doc/effective_go.html#Getters) it helps in thinking in terms of go idioms and will help future design as well.

**Comment by ruflin** [comment]
+1 on following to conventions (most of the time ;-) ). Feel free to open a PR with the change, then also the rest of the team can get involved in reviewing it.

**Comment by crackerplace** [comment]
@ruflin kool.

**Comment by simitt** [comment]
I'd appreciate to see this changed, looking forward to the PR.

**Comment by jalvz** [comment]
I also prefer to avoid java-ish `Get*` /  `Set*` / `New*` lingo 👍
