### ISSUE TITLE
Errors from custom transactions are missing from Kibana APM service errors UI

### ISSUE THREAD

**Issue by ctison** [elastic/apm-server#7401]
Hello,

**APM Server version** (`apm-server version`): 8.0.0

**Description of the problem including expected versus actual behavior**:

In APM Kibana UI, when on the `Errors` tab of a service that has custom transactions, the errors are not retrieved because the field `transaction.type` on these errors is not set.

Quick fix: go to `/app/management/ingest/ingest_pipelines/edit/logs-apm.error-8.0.0` and add a processor to set `transaction.type` to `custom` when the field is not present.

![image](https://user-images.githubusercontent.com/17789536/155532781-f3740078-9d2d-4a83-a343-7cefdb5260c1.png)

**Comment by ddatsh** [comment]
already do this

```java
Span        span        = ElasticApm.currentSpan();
Transaction transaction = ElasticApm.currentTransaction();
if (true) {

	try {
		throw new ArrayIndexOutOfBoundsException("aab");
	} catch (Exception e) {
		transaction.captureException(e);
		span.captureException(e);
	}
 }
```

still only Occurrences, no   Group ID | Type | Error message and culprit  in kibana ui ?

**Comment by simitt** [comment]
https://github.com/elastic/apm-server/issues/7376 tracks work for setting a default `transaction.type` and `span.type` if missing. In general though this seems to be an issue on the APM agent side, where the `transaction.type` should be set in the first place. Can you please share which APM agent you are using?

**Comment by simitt** [comment]
> It was working on 7.x but the bug appeared when switched to 8.x.

Have you also updated the elastic-apm-node agent when upgrading to 8.0 or did you only upgrade ES, Kibana and APM Server (Elastic Agent)?

**Comment by ctison** [comment]
Yes I upgraded the elastic agent to `elastic/elastic-agent:8.0.0@sha256:754c600eafed9e0ddb49dd69c9705263b42c270fa66cf7e7f5fd317acac75102` on February 14th. Sorry for delay 😅

Now we have Elastic stack v8.1.2 and I think this problem does not exist anymore, thank you <3!
