### ISSUE TITLE
Add support for span links in OTLP intake

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#7441]
This is a follow-up to https://github.com/elastic/apm-server/issues/7171.

In https://github.com/elastic/apm-server/issues/7171, we are defining the data storage model for span links. This issue is about supporting span links that are sent via OTLP.

Related: https://github.com/elastic/apm-server/issues/7304

**Comment by axw** [comment]
This was implemented in https://github.com/elastic/apm-server/pull/7291
