### ISSUE TITLE
GeoIP processor failures will block data ingestion

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/apm-server#7465]
If the [GeoIP processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/geoip-processor.html) is not configured correctly or if it can not connect to Elastic's GeoIP's endpoint for 30 days the processor will start emitting `tags` under `_source`. 

> If your cluster can’t connect to the Elastic GeoIP endpoint or you want to manage your own updates, see [Manage your own GeoIP2 database updates](https://www.elastic.co/guide/en/elasticsearch/reference/master/geoip-processor.html#manage-geoip-database-updates).

> If Elasticsearch can’t connect to the endpoint for 30 days all updated databases will become invalid. Elasticsearch will stop enriching documents with geoip data and will add tags: ["_geoip_expired_database"] field instead.

Currently our mappings are strict and will start rejecting documents if the `geoip` processor acts up and inject `tags`.

e.g

```json
POST metrics-apm.internal-default/_doc?pipeline=metrics-apm.internal-8.1.0
{
    "@timestamp": "2022-03-04T12:33:00.000Z",
  "observer": {
    "version": "8.1.0",
    "version_major": 8
  }
}
```
*`metrics-apm.internal-8.1.0` is the default pipeline*

will return: 

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "strict_dynamic_mapping_exception",
        "reason" : "mapping set to strict, dynamic introduction of [tags] within [_doc] is not allowed"
      }
    ],
    "type" : "strict_dynamic_mapping_exception",
    "reason" : "mapping set to strict, dynamic introduction of [tags] within [_doc] is not allowed"
  },
  "status" : 400
}
```

Tested on `8.1.0-SNAPSOT` but likely not version bound.

**Comment by Mpdreamz** [comment]
I think this easily reproduces if started with ` -E ingest.geoip.downloader.enabled=false` which is the default when starting Elasticsearch from Kibana through `yarn es snapshot`.

**Comment by simitt** [comment]
I find the geoip processor behavior surprising, to add tags on failure, especially with having an `on_failure` handling defined: 

```
    {
      "geoip" : {
        "database_file" : "GeoLite2-City.mmdb",
        "field" : "client.ip",
        "ignore_missing" : true,
        "on_failure" : [
          {
            "remove" : {
              "field" : "client.ip",
              "ignore_failure" : true,
              "ignore_missing" : true
            }
          }
        ],
        "target_field" : "client.geo"
      }
    }
```

Was able to reproduce with the above described way; and suggest to add another processer at the end of the pipeline to remove the `tags`. We might need to be more finegranular in the future, but afaik we currently do not set any `tags` on metrics, so for now we should be able to just drop them.

**Comment by axw** [comment]
https://github.com/elastic/elasticsearch/issues/87345

**Comment by axw** [comment]
We should have the `tags` field though, because RUM breakdown metric docs (which go into `apm.internal`) will include a `client.ip` field.

**Comment by simitt** [comment]
@axw I think this should be backported to `8.2.3`.

**Comment by axw** [comment]
@simitt the fix was backported: https://github.com/elastic/apm-server/pull/8297

**Comment by simitt** [comment]
🤦‍♀️ my bad, I should have looked at the PR for the backport, not the issue. Thanks!
