### ISSUE TITLE
Shouldn't payload be a pointer

### ISSUE THREAD

**Issue by crackerplace** [elastic/apm-server#75]
At this [line](https://github.com/elastic/apm-server/blob/master/processor/transaction/processor.go#L29),shouldn't the payload be a pointer.

Similarly at this [line](https://github.com/elastic/apm-server/blob/master/processor/validator.go#L26) ,I think the data should be a pointer as we are passing [p.payload](https://github.com/elastic/apm-server/blob/master/processor/transaction/processor.go#L38).

**Comment by ruflin** [comment]
Hi @crackerplace. Happy to see you get involved with apm-server.

The first payload you mentioned is an interface. So I think passing it here as is should work as expected or do you see any unwanted side affects?

For the second line you mentioned it's passed as value as we only extract the data and don't modify it. Passing it by pointer would also work but I prefer in general if not pointer is need to pass a copy except it would become a performance issue.

**Comment by crackerplace** [comment]
@ruflin thanks,Would be happy to contribute :-)

Thanks.Sounds fine as we are passing a pointer to the struct [payload](https://github.com/elastic/apm-server/blob/master/processor/transaction/processor.go#L23) which satisfies pr.Payload.

A simple better change would be to make payload as lower case at [line](https://github.com/elastic/apm-server/blob/master/processor/transaction/payload.go#L9) as we are anywayz returning it as a pointer to an interface.It helps in understanding as well that small caps stands for struct and capital denotes an interface.

**Comment by ruflin** [comment]
Making it private SGTM assuming we don't need it anywhere else. Can you open a PR?

**Comment by crackerplace** [comment]
@ruflin Sure.Will open.
