### ISSUE TITLE
Windows tests should report back on CI

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7599]
Jenkins CI seems to be running unit tests on Windows 2019 + 2022 servers, but not reporting back results. This should be aligned with how test are run and results are reported back for Linux and MacOS. 
<img width="1194" alt="Screenshot 2022-03-21 at 17 52 31" src="https://user-images.githubusercontent.com/5555349/159317670-6984c91e-efda-4b92-8f8f-d01b215eebc2.png">
<img width="921" alt="Screenshot 2022-03-21 at 17 53 15" src="https://user-images.githubusercontent.com/5555349/159317744-4b2b2635-7bb4-4fe7-9fd2-bb2ffbcdabb9.png">

@v1v can you have a look at this please?

**Comment by v1v** [comment]
What job url please?

Bear in mind, Blue Ocean (the nicer UI in Jenkins) might not report correctly the build status until the very end of the build.

**Comment by v1v** [comment]
In addition, windows stages in the CI only runs on a nightly basis as per https://github.com/elastic/apm-server/pull/7375

**Comment by simitt** [comment]
It appears to be the case on every regular PR, for example https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-7596/1/pipeline.

**Comment by simitt** [comment]
> In addition, windows stages in the CI only runs on a nightly basis as per https://github.com/elastic/apm-server/pull/7375

That was my original understanding, but clicking on the stage in Blue Ocean actually indicates that the tests are run (otherwise I'd be completely misreading that UI). I believe in the past the unit tests have been running on windows if they weren't skipped, but not on all the supported OSs (similar to how we ran then on linux, but not all supported OSs, and what seems to be happening now also for MacOS).

**Comment by v1v** [comment]
Thanks for the link, I need to figure out why those stages are clickable. I cannot find any specific build for those two Windows stages in the steps tree view:

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/2871786/159447408-4fdac61a-7403-4868-99b5-143b77eea84d.png">

Probably it's not a bit clear what's that view, but in a nutshell, every step executed in those windows stages are reported in a tree based format, so I cannot see any build specific step neither an allocation of a windows worker. There are no github checks in https://github.com/elastic/apm-server/pull/7596 regarding those Windows stages.

I'll review the pipeline and double check what's the current configuration

**Comment by v1v** [comment]
I think the issue is related to a when condition in the pipeline that uses https://github.com/elastic/apm-pipeline-library/blob/main/vars/matchesPrLabel.groovy and it does interact with GitHub and it produces some steps reflected in the UI

**Comment by v1v** [comment]
I've tried with https://github.com/elastic/apm-server/pull/7610 but same behaviour, I guess we have hit an issue with the Blue Ocean but since it's in maintenance mode we cannot do much these days :/

For now, I'd say the GitHub checks should be the ones that provide a sense of how things went, in addition, the GitHub comment with the Build provides a digested summary what things failed if any.

Sorry if this is not the most elegant answer but at the moment we cannot do much

**Comment by simitt** [comment]
Thanks for looking into this; it sounds like there is nothing that can be done atm and since the windows workers are not actually running, results cannot be linked back. Closing the issue in this case then.
