### ISSUE TITLE
modelindexer: BytesTotal is invalid when compression is enabled

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#7625]
https://github.com/elastic/apm-server/blob/36c6166c0e4fa2b6cc11ab896af78952d0cee022/model/modelindexer/indexer.go#L369-L370

The act of calling `Flush` will close the gzip writer, flushing to the buffer. Counting must therefore happen after closing the gzip writer.

Also, I believe our implementation of the metric differs substantially from the libbeat imlementation which counts bytes written at the transport level: https://github.com/elastic/beats/blob/36d7fffb19d497b71b6ac40e7741677aed076b94/libbeat/common/transport/stats.go#L59. I don't think this particularly matters in practice, but maybe we should at least document the difference (internally, for developers), as well as our definition of the metric:

https://github.com/elastic/apm-server/blob/36c6166c0e4fa2b6cc11ab896af78952d0cee022/model/modelindexer/indexer.go#L474-L475

**Comment by simitt** [comment]
Scoping this for `8.3` to:
* fix that counting happens after closing the gzip writer
* add section to [dev_docs](https://github.com/elastic/apm-server/tree/main/dev_docs) describing the internally collected metrics and difference to libbeat collected metrics.
