### ISSUE TITLE
[Fleet]: Incomplete description for Elastic APM integration under Installed Integrations tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/apm-server#7635]
**Kibana version:**  8.2 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.2.0
BUILD: 51328
COMMIT: 2a93e80574f9c1052c541bc4083a440a623899e8
```

**Preconditions:**
1. 8.2 Snapshot Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Install Elastic APM integration and navigate to Installed integrations.
3. Observe description is incomplete for only Elastic APM integration.
4. Observe description for other installed integrations are complete.

**Expected Result:**
 Complete description should be available for Elastic APM integration under Installed Integrations tab.

**Screenshot:**
![13](https://user-images.githubusercontent.com/77374876/159443793-090b766a-3784-4bc4-8fee-0ba272acad75.JPG)
![14](https://user-images.githubusercontent.com/77374876/159443804-605849b4-4fdd-49ba-af1a-c4405a38fe4e.JPG)

**Comment by joshdover** [comment]
I believe the APM integration package needs to have it's description updated. It should match the format the other integrations have, probably something like `Collect distributed traces and transactions from your applications with Elastic Agent`

**Comment by simitt** [comment]
The APM package description _Monitor, detect and diagnose complex performance issues from your application._ is set in the [Kibana Fleet plugin](https://github.com/elastic/kibana/blob/0e1f9681a2c223d525eec96b4fe24cd4cb62e4c0/x-pack/plugins/fleet/public/applications/integrations/sections/epm/screens/home/available_packages.tsx#L340). @chrisdistasio would you mind reviewing if this wording should be changed? 

After reaching and agreement of what the description should be, it also needs to be updated where the package is created: https://github.com/elastic/apm-server/blob/main/apmpackage/apm/manifest.yml#L6 (don't forget to add a package changelog entry). Once merged, an automatic PR will be created to push the changes to the package registry.

**Comment by chrisdistasio** [comment]
@simitt Let's follow the paradigm of keeping the message consistent on both "browse" and "installed" pages.  after a brief consult with marketing, let's slightly modify the message to "_Monitor, detect and diagnose complex application performance issues_"

**Comment by simitt** [comment]
related Kibana issue https://github.com/elastic/kibana/issues/136086

**Comment by bmorelli25** [comment]
> let's slightly modify the message to "Monitor, detect and diagnose complex application performance issues"

Two recommendations if I may:

* Add a period to the end to maintain consistency with other integration descriptions
* Use an oxford comma per the [Elastic Writing style guide](https://brand.elastic.co/302f66895/p/194a3b-writing-style-guide)

"Monitor, detect, and diagnose complex application performance issues."

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.4 Snapshot and found it **fixed** now.
- Complete description is available for Elastic APM integration under Installed Integrations tab.

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/180715681-5c8e6a60-a9e2-443d-a1bf-a5ed24cbcbd6.JPG)
![3](https://user-images.githubusercontent.com/77374876/180715693-1743240d-33c3-422e-a655-b0509c39ef16.JPG)

**Build details:**
BUILD: 54789
COMMIT: af3a3cba9a7fa3b3e0d2e4766a1db11a5ff4f192

Thanks
