### ISSUE TITLE
Add deprecation note for 32-bit support 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7677]
We want to drop support for APM Server on 32 bit Linux and Windows systems. To inform users about this upcoming step, we want to add depreaction notes. The target release version for fully dropping support is under discussion, but we aim for an early `8.x` release, therefore users should already be informed about the upcoming change from `8.2` on.

Add deprecation note:
* [x] when running apm-server: When starting APM Server on a 32 bit system, it should log a deprecation warning.  
* [x] [support matrix](https://www.elastic.co/support/matrix#matrix_os): The matrix does not specifically mention 32 bit support; we should add a deprecation note for `8.2`.
* [x] [download page](https://www.elastic.co/downloads/apm): add a deprecation note when a 32 bit download is chosen. Something similar to:
<img width="827" alt="Screenshot 2022-03-28 at 10 26 42" src="https://user-images.githubusercontent.com/5555349/160357866-1690ef15-d85e-46ad-a2b9-da11d6a87633.png">
@bmorelli25 can you help with adding a deprecation note to the download page?

---
  
@chrisdistasio for visibility

**Comment by simitt** [comment]
@bmorelli25 we decided on moving forward with the deprecation for `8.2`. Could you help us finding the right wording and way for adding a deprecation note to the download page?

**Comment by bmorelli25** [comment]
Yup 👍

**Comment by bmorelli25** [comment]
@simitt The web updates have been proposed in https://github.com/elastic/website-development/issues/9124. Please feel free to edit my issue description as you see fit.

**Comment by simitt** [comment]
Thanks @bmorelli25 the proposed changes look good. 
I already initiated the additional note in the support matrix.

**Comment by simitt** [comment]
There is no deprecation note on the download page.

**Comment by bmorelli25** [comment]
@simitt thanks for following up on this. I think we can close this as a note exists in both locations on the website. In addition, there's an open issue for the web team to create a component for requests like this in the future: https://github.com/elastic/website-development/issues/9295.
