### ISSUE TITLE
Add OTLP and Jaeger metrics to Stack Monitoring

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#7696]
## Description

We should look into displaying request / response metrics for OTLP or Jaeger in Stack Monitoring for the APM Server. We're already publishing them in the APM Server and should be collected through the `beat` module that metric beat uses. However it is likely that they're missing in the Elasticsearch mappings.

Additionally, we'd need to look into how to extend the existing Stack Monitoring UI to display those metrics once they've been added.

**Comment by simitt** [comment]
As discussed offline, the metrics are already collected, the missing part is to add them to the ES template and the Stack Monitoring UI.
