### ISSUE TITLE
Benchmark the impact of using a higher output MaxRequests default

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#7718]
## Description

The current implementation of the ModelIndexer, defaults to 10 `MaxRequests`, which offers a respectable throughput while ensuring that we don't send too many requests to Elasticsearch as to start receiving 429s. This is particularly important since the current implementation doesn't retry when a 429 is received on the `_bulk` request to Elasticsearch.

https://github.com/elastic/apm-server/blob/b2643205b8a1989b9c6d5317f7296967dada3731/model/modelindexer/indexer.go#L101-L105

## Problem

The problem is that as the APM Server scales up, the number of `MaxRequests` remains constant, and often, the backing Elasticsearch will be a multi-node cluster that could easily handle more concurrent requests. 
It's important that we don't easily overwhelm smaller Elasticsearch clusters.

## Proposed approach

We should explore what the maximum number of `MaxRequests` that we can use as a default, and what the gain is.

**Comment by axw** [comment]
Should we close this? Seeing as we're using more but smaller bulk requests in main.
