### ISSUE TITLE
modelindexer: Expose the number of available bulkindexers

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#7728]
## Description

We currently don't have any visibility into what the number of available bulk indexers is and would like to change that. 

I'm unsure what the exact metric name  we should use considering that if we are to also add visualizations for the metric in Stack Monitoring they should work both for the libbeat output and our own model indexer.

## Beat metrics reference

I saw that there's a `libbeat.pipeline.clients` but I am unsure if we can reuse the name for this purpose.

- https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-beat-stats.html

**Comment by marclop** [comment]
Should we open a follow-up issue to discuss how or if we'd want to integrate this metrics back into Stack Monitoring?

**Comment by simitt** [comment]
@marclop I believe we could add this as a point to the research task https://github.com/elastic/apm-server/issues/7504. WDYT?
