### ISSUE TITLE
Performance tests publishing documents to ES

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#773]
Take a closer look at the current pipeline and publishing handling implemented in `libbeat`, and whether performance could be improved by alternative approaches or improvements.

**Comment by alvarolobato** [comment]
@roncohen  said after a talk with Simon:

> regarding optimizing performance of ingestion of data into Elasticsearch: 
> I just got off a call with @simonw and there are some interesting points we should be aware of:
> 
> - Each bulk HTTP request to ES means an fsync to disk. fsyncs are expensive. 
> - Each bulk HTTP request is handled single-threadedly by ES. In other words, all documents in a single bulk request are handled by the same thread sequentially. 
> - By default, the number of threads handling bulk requests is equal to the number of cores on the ES machine. This has implications for the number of libbeat “workers” we should be using. 
> - ES operates with a bulk size much higher than what i believe we’ve been thinking about at around 3k-5k, with some benchmarks running at 15k.
>

**Comment by simitt** [comment]
Investigate *spooling to disk* which is a newly added feature of `libbeat`.

**Comment by simitt** [comment]
Continuing the work of @jalvz to look into an [alternative ES client](https://github.com/olivere/elastic) for performance comparisons to `libbeat` memory queue and pushing documents to ES.

Three different branches have been compared:
* master branch commit 26f93b2, as this was roughly the time when first investigations started
* using alternative ES client (omitting the transformation)
* current master branch (commit 558480c)

Different configuration options were tested with different load generation. The results are very much tight to the environment where those tests were run. The intention is to reach comparable results for the different approaches. 

One noteable difference is that the branch with the alternative solution doesn't run a `transformation` process. 

*Results* 
# Local Test Run

*used testing profile:*
		
    V1Transaction1, 80, 45
    V1Transaction2, 40, 50

## Run 1:

| docs (k) | RAM (MB)| CPU | branch  | conc req  | mem events| flush events | flush timeout | flush size| ES worker | ES bulk | 
| ------------- |:-------------:| -----:| -----:| -----:|-----:|-----:|-----:|-----:|-----:|-----:|
| 134 | 120-280 |380% | master 26f93b2 | 50 | 1000 | 0   | 0    | - | 1 | 500 |
| 229 | 30-104 |280% | alternative      | 50 | -    | -   | 1/5s |1mb| 1 | 500 |
| 253 | 60-130 |300% | master         | 50 | 1000 | 0   | 0    | - | 1 | 500 |

![local_1](https://user-images.githubusercontent.com/5555349/38673281-298da71e-3e51-11e8-99c2-5589be8fef9b.png)


## Run 2:

| docs (k) | RAM  (MB)| CPU | branch  | conc req  | mem events| flush events | flush timeout | flush size| ES worker | ES bulk | 
| ------------- |:-------------:| -----:| -----:| -----:|-----:|-----:|-----:|-----:|-----:|-----:|
| 133 | 750-1.250|400% |master 26f93b2| 1000 | 1000 | 0 | 0  | -  | 4 | 250 |
| 295 | 175-380  |330% |alternative     | 1000 | -    | - | 1s | 1mb| 4 | 250 |
| 300 | 260-500  |330% |master        | 1000 | 1000 | 0 | 0  | -  | 4 | 250 |

![local_2](https://user-images.githubusercontent.com/5555349/38673299-374987b0-3e51-11e8-92db-884d658fc6bd.png)


## Run 3 - ES turned off, all events need to be buffered:
*Alternative approach doesn't work without ES*

| docs (k) | RAM (MB)| CPU | branch  | conc req  | mem events| flush events | flush timeout | flush size| ES worker | ES bulk | 
| -- |:------:|  -----:| -----:| -----:|-----:|-----:|-----:|-----:|-----:|-----:|
| - | 100-220| 300% | master 26f93b2| 50 | 500 | 0 | 0    | -  | 1 | 250 |
| - | 40-80 | 130% | master        | 50 | 500 | 0 | 0    | -  | 1 | 250 |

![local_3](https://user-images.githubusercontent.com/5555349/38673308-3df33c8c-3e51-11e8-94c3-6ed2d22e1812.png)


## Run 4 - ES turned off, all events need to be buffered:
*Alternative approach doesn't work without ES*

| docs (k) | RAM (MB)| CPU | branch  | conc req  | mem events| flush events | flush timeout | flush size| ES worker | ES bulk | 
| ------ |:------:|------:| -----:| -----:|-----:|-----:|-----:|-----:|-----:|-----:|
| - | 240-470| 180%| master 26f93b2| 1000 | 1000 | 0 | 0 |-| 4 | 250 |
| - | 280-500| 180%| master| 1000 | 1000 | 0 | 0 | - | 4 | 250 |

![local_4](https://user-images.githubusercontent.com/5555349/38673333-4d41de96-3e51-11e8-8a83-b8e02ebc2d50.png)


## Run 5 - Best Throughput

| docs (k) | RAM (MB)| CPU | branch  | conc req  | mem events| flush events | flush timeout | flush size| ES worker | ES bulk |
| ------------- |:-------------:|-----:|  -----:| -----:|-----:|-----:|-----:|-----:|-----:|-----:|
| 324 | 60-130 | 300% | alternative| 100 | -  | - | 1s | 1mb | 2 | 500 |
| 272 | 75-150 | 330%| master    | 50   | 1000 | 0 | 0  | -   | 4 | 300 |

![local_5](https://user-images.githubusercontent.com/5555349/38673344-595b9a00-3e51-11e8-8665-c3a01390efd8.png)


## Run 6 - Best Throughput settings - Heavy Nodejs Test Script

| docs (k) | RAM (GB)| CPU | branch  | conc req  | mem events| flush events | flush timeout | flush size| ES worker | ES bulk |
| ------------- |:-------------:|-----:|  -----:| -----:|-----:|-----:|-----:|-----:|-----:|-----:|
| 400 | 800 | 6 - 9.5 | 400% | alternative| 100 | - | - | 1s | 1mb| 2 | 500 |
| 160 | 700 | 6.5 - 11 |400% | master| 50 | 1000 | 0 | 0 | - | 4 | 300 |

![local_6a](https://user-images.githubusercontent.com/5555349/38673360-66da5478-3e51-11e8-94d9-55a127449ed3.png)
(alternative)

![local_6b](https://user-images.githubusercontent.com/5555349/38673365-6a283244-3e51-11e8-9169-197b1407e8f6.png)
(master)

## Run 7 - Comparing alternative with transformation

*used testing profile:*
		
    target.V1Error1, 30, 100
    target.V1Error2, 1, 10
    target.V1Transaction2, 500, 100

| docs (k) | RAM (MB) | CPU | branch  | conc req  | mem events| flush events | flush timeout | flush size| ES worker | ES bulk | 
| ------------- |:-------------:|-----:|  -----:| -----:|-----:|-----:|-----:|-----:|-----:|-----:|
| 290 | 30-65 | 380% | alternative| 100 | -  | - | 1s | 1mb | 1 | 1000 |
| 283 | 40-75 | 380% | alternative with transformation, but using go structs| 100 | -  | - | 1s | 1mb | 1 | 1000 |
| 263 | 40-85 | 330% | master    | 100   | 1000 | 0 | 0  | -   | 1 | 500 |

![local_7_tiny](https://user-images.githubusercontent.com/5555349/38674299-4b5363fe-3e54-11e8-8177-d583851bfeaa.png)


## Run 8 - ES Cloud Test Run
*used testing profile:*
		
    target.V1Error1, 30, 100
    target.V1Error2, 1, 10
    target.V1Transaction2, 500, 100

| docs (k) | RAM (MB)| CPU | branch  | conc req  | mem events| flush events | flush timeout | flush size| ES worker | ES bulk |
| ------------- |:-------------:|-----:|  -----:| -----:|-----:|-----:|-----:|-----:|-----:|-----:|
| 75  | 30-50 | 80% | alternative | 50 | -  | - | 1s | 1mb | 1 | 100 |
| 133 | 30-60 | 125% | alternative| 50 | -  | - | 1s | 1mb | 2 | 100 |
| 74 | 40-75| 90% | master    | 50   | 100 | 0 | 0  | -   | 1 | 50 |
| 56 | 40-75| 70% | master    | 50   | 100 | 0 | 0  | -   | 2 | 50 |

![cloud_1](https://user-images.githubusercontent.com/5555349/38673449-a1e0b1ac-3e51-11e8-838e-cf0657961649.png)

**Comment by simitt** [comment]
Decided to wait with further investigations until automatic testing support (from @jalvz ) can be used.

**Comment by alvarolobato** [comment]
@simitt @jalvz the automated testing support is already available right?

*Test execution*
In regards to test executions, there is now a new server configured for the CI environment specifically to execute benchmarks which should yield reproducible results.

*Objectives*
We need to define clear objectives for these tests I would say the following:
[ ] - Measure apm-server performance + libbeat with different configuration parameters
[ ] - Learn how changing different configuration knobs in libeat affects APM server performance
[ ] - Setup a an automated benchmark suite that allows us to establish a baseline to compare performance on each change and refresh of libbeat (we can defer this one to a follow up task)
[ ] - Decide if we DO have a performance problem or on the contrary we are ok with the current setup
[ ] - Evaluate if our integration approach with libbeat is correct or if we need to change something

**Comment by jalvz** [comment]
Broke this down and created https://github.com/elastic/apm-server/issues/992 https://github.com/elastic/apm-server/issues/993

I talked to Felix re. the new machine for benchmarks, will follow up after I sort out more priority issues.

**Comment by alvarolobato** [comment]
Great, thanks.

**Comment by jalvz** [comment]
this can be closed, right?
