### ISSUE TITLE
Allow enabling pprof via `pprof_enabled` in the APM Package

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#7733]
## Description

To allow taking different kinds of profiles while running `apmbench` we should add a new `pproof_enabled` input variable to the APM integration which defaults to `false`. We'd then be able to customize the to suit our needs.

Additionally, it may also be necessary to take profiles of the APM Server to aid debugging some issues.

**Comment by simitt** [comment]
Have you thought about where this should be added in the APM Integration UI? Right now we have an `expvar.enabled` input variable in the _General_ section; might be worth to introduce a dedicated _Debug_ section (or something similar) with these settings.

**Comment by marclop** [comment]
I think that it may be worth doing so in case we need to ask customers to enable debug settings (hopefully not). I'm not a UI expert, so I don't know what the best layout would be, but to me, having a dedicated debug section seems worthy, and it should probably include both expvar and pprof toggles.

**Comment by lahsivjar** [comment]
Closed via #8002 APM-UI work is linked in the parent issue.
