### ISSUE TITLE
Backend dependencies granularity: keep backwards compatibility

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7734]
Follow up on https://github.com/elastic/apm-server/issues/7715 to also adapt the processing logic to the new intake fields:

## Intake API
Deprecate `span.context.destination.service.resource` on the Intake API. 

## Processing Logic
For backwards compatibility reason, the APM Server should 
* for certain span types, keep populating `span.destination.service.resource`. If agents are sending the new `span.context.service.target.*` fields, the value needs to be derived from the new fields (data compatibility)
* always populate the new `span.service.target.*`. For backwards compatibility with old agents, split the value from `span.destination.service.resource` to derive `span.service.target.*` information. 

A detailed description for when and how to derive the values is provided in https://github.com/elastic/apm/pull/627/files#diff-78ae87d6c58be8cc0ed40d4dcd78faa83a58e462ad0b836912194a5cf8aed336R143

**Comment by simitt** [comment]
Cross linking https://github.com/elastic/apm-server/issues/7745#issuecomment-1114625600 - @lahsivjar could you please update the metrics aggregation key accordingly?

**Comment by SylvainJuge** [comment]
I discovered last week that there was some issues with the algorithm previously defined in https://github.com/elastic/apm/pull/627.
- we can't reliably infer `span.destination.service.resource` value from `span.service.target.{type,name}` on apm-server, given that `span.destination.service.resource` will still be computed on agent for compatibility with older apm-server, we need to keep the provided value by the agent.
- when ingesting data without the new fields, we need to back-fill them with a rather simple algorithm and use a marker value in `service.target.type` that will allow the UI to later query on the new fields and display the `resource` for compatibility.

**Comment by lahsivjar** [comment]
@SylvainJuge Thanks for the update, the logic is clear to me now. Below is the summary of the APM-server work:

PR #7924 has been updated to align with the remaining work of Phase 1 (as defined in elastic/apm#627) required for APM server which is:

1. Transaction intake api to accept `service_target_{type,name}` and propogate it to the related metrics document
2. Service destination metrics and dropped spans metrics to include the new fields

PR #7925 contains the required work for Phase 3 i.e. inferring new fields from `span.destination.service.resource`
