### ISSUE TITLE
Backend dependencies granularity: Add `transaction.dropped_spans_stats.service_target_*`

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7745]
### Intake API
Extend transaction Intake API to accept `transaction.dropped_spans_stats.service_target_type` and `transaction.dropped_spans_stats.service_target_name`.

### Aggregated Metrics Calculation
Extend [`transaction.DroppedSpanStats`](https://github.com/elastic/apm-server/blob/main/model/transaction.go#L149-L153) to contain the `service_target_*` fields. For calculating related span metrics, add the new fields to the [`aggregationKey`](https://github.com/elastic/apm-server/blob/main/model/transaction.go#L149-L153) to consider the new fields in the aggregation. 

### ES data storage
None of the dropped spans stats should be stored in Elasticsearch, the information is only used for calculating metrics.The [`DroppedSpansStatsDiscarder`](https://github.com/elastic/apm-server/blob/main/model/modelprocessor/dropped_spans_stats.go) already takes care of removing the information before sending data to Elasticsearch. No changes required for this part.

**Comment by AlexanderWert** [comment]
I think, we forgot about the `span destination metrics` that are calculated by the APM Server. Those should add the new fields as part of the aggregation key as well.

@simitt should we create a new issue for that or cover it within this one?

**Comment by simitt** [comment]
@lahsivjar and I briefly talked about it for https://github.com/elastic/apm-server/issues/7734. Since we keep populating the currently used `span.destination.service.resource` in the apm-server for backwards compatibility, I don't think it is a hard requirement to update the aggregation key at this point, but it would be future proof. I assume we would need to consider both keys for now, as the UI still expects the backwards compatible key.

**Comment by simitt** [comment]
Just saw https://github.com/elastic/apm/pull/627#discussion_r861830812; which makes it clear that both keys should be take into account for

**Comment by lahsivjar** [comment]
@simitt In the PR #7924 I have added support for `service.target.*` field for both, `span` and `droppedSpanStats`. This should take care of adding both new and old field as metric dimensions for all cases. Am I missing any other scenarios?
