### ISSUE TITLE
Span.id is limited to 999999

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#775]
When trying to send a span with a Span id >= 1 000 000, the APM server responds with a 400 and this error message:
 ```
Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"
  I[#/transactions/0/spans/0/id] S[#/properties/transactions/items/properties/spans/items/properties/id/type] expected integer or null, but got number
```

The JSON Schema spec does not limit the range of the `integer` data type: http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.1, so there might be something wrong with the go JSON schema validator .

**Comment by simitt** [comment]
By transforming the input to a `map[string]interface{}` the large Integers are in the format of e.g. `9.999999999e+09` instead of `9999999999`.

The [validator](https://github.com/santhosh-tekuri/jsonschema/blob/master/schema.go#L159) does expect an `int` here instead of a `float`.
