### ISSUE TITLE
docs: Add trouble shooting section to APM Guide

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#7752]
The new APM guide is not offering a troubleshooting section common problems anymore. While some of the problems are not applicable to the APM Integration, the majority of the section still has value. We should add a revised version of the [Common Problems](https://www.elastic.co/guide/en/apm/guide/current/common-problems.html): 

* remove the parts that directly run commands via the apm-server CLI, for example `apm-server test config`.
* remove the `queue is full` section, this doesn't happen any more
* reference the [Input APM](https://www.elastic.co/guide/en/apm/guide/current/input-apm.html) section for details on how to configure the APM Server
* keep suggestions to check the APM agent & server logs
* keep section around any [TLS failures](https://www.elastic.co/guide/en/apm/guide/current/common-problems.html#ssl-client-fails) and [common ssl problems](https://www.elastic.co/guide/en/apm/guide/current/common-problems.html#_common_ssl_related_errors_and_resolutions)
* remove the section around [field limit exceeded](https://www.elastic.co/guide/en/apm/guide/current/common-problems.html#field-limit-exceeded) - should not happen anymore; if it does we should be informed about it rather than provide a guide for an unexpected edge case
* keep [i/o timeout](https://www.elastic.co/guide/en/apm/guide/current/common-problems.html#io-timeout)
* change the [If Elasticsearch is down](https://www.elastic.co/guide/en/apm/guide/current/common-problems.html#server-es-down) section to something like the APM Server will eventually deny incoming requests and the Server and the APM agent should be issuing logs accordingly.

**Comment by marclop** [comment]
I opened https://github.com/elastic/apm-server/issues/7692 and they seem to have some overlap, but your issue is more complete than the one I wrote. Should I close the one I opened?

**Comment by simitt** [comment]
It's not quite the same, although it has some overlap. Let's leave both open for now and @bmorelli25 can decide whether to adress them at once or in two separate PRs.
