### ISSUE TITLE
benchmarking: Record more APM Server usage metrics

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#7817]
## Description

We currently record a few metrics related to the APM Server's event processing and golang memory allocations. We're still missing some more metrics to help us collect data points that are useful as it comes to sizing APM Server and understanding its memory usage.

We should aim to record (ideally in a histogram so we can see distributions):

* RSS memory consumption 
* Goroutines
* Available indexers

GC metrics ([Go docs](https://pkg.go.dev/runtime/metrics)): 

* GC cycles
* Heap information

**Comment by simitt** [comment]
This looks like a good set of metrics to start with. I expect we need to collect more metrics eventually, but we can do that later on.
