### ISSUE TITLE
Cannot index event publisher for Elastic APM integration

### ISSUE THREAD

**Issue by yash-gill** [elastic/apm-server#7818]
ES, Kibana, Fleet & APM Server versions: 7.17.0,

Not able to get logs and metrics through Fleet integrations, the log file path and creds are fine but getting these in the logs:

`Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xc08a3b7edab497da, ext:6086970045383160, loc:(*time.Location)(0x557809a6d9e0)}, Meta:null, Fields:{"agent":{"name":"rum-js","version":"5.10.0"},"client":{"ip":"x.x.x.x"},"data_stream.dataset":"apm.internal","data_stream.namespace":"haproxy_and_utils","data_stream.type":"metrics","ecs":{"version":"1.11.0"},"metricset.name":"transaction_breakdown","observer":{"ephemeral_id":"b8151fb3-23e3-4d51-b8a2-7bb85bb3ea88","hostname":"x-x","id":"8db334b8-1a43-42b8-a670-736681b5ec88","type":"apm-server","version":"7.15.2","version_major":7},"processor":{"event":"metric","name":"metric"},"service":{"environment":"prodEnv","language":{"name":"javascript"},"name":"x-x","version":"1.0.5216-220226"},"transaction":{"name":"POST https://x.x.x/api/logging/LogMany/","type":"http-request"},"transaction.breakdown.count":0,"transaction.duration.count":1,"transaction.duration.sum.us":140,"user_agent":{"original":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"}}, Private:interface {}(nil), TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=400): {"type":"strict_dynamic_mapping_exception","reason":"mapping set to strict, dynamic introduction of [sum] within [transaction.duration] is not allowed"}, dropping event!`

`Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xc08b6c92c27d5f61, ext:6399369938699486, loc:(*time.Location)(0x55ce551219e0)}, Meta:null, Fields:{"_doc_count":10,"_metric_descriptions":{"transaction.duration.histogram":{"type":"histogram"}},"agent":{"name":"rum-js"},"data_stream.dataset":"apm.internal","data_stream.namespace":"haproxy_and_utils","data_stream.type":"metrics","ecs":{"version":"1.11.0"},"event":{"outcome":"unknown"},"metricset.name":"transaction","observer":{"ephemeral_id":"07e31876-8a6b-4b28-b071-cb2aee4441d8","hostname":"x-x","id":"bdea063b-a649-4b0a-aeb6-654f2d5bfcb0","type":"apm-server","version":"7.15.2","version_major":7},"processor":{"event":"metric","name":"metric"},"service":{"environment":"prodEnv","name":"x-client","version":"1.0.5328-220328-prod"},"timeseries":{"instance":"x-client:#X/X/?scheduledTestId=x"},"transaction":{"name":"#X/X/?scheduledTestId=x","root":true,"type":"page-load"},"transaction.duration.histogram":{"counts":[10],"values":[25559039]}}, Private:interface {}(nil), TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=400): {"type":"strict_dynamic_mapping_exception","reason":"mapping set to strict, dynamic introduction of [_metric_descriptions] within [_doc] is not allowed"}, dropping event!`

Sidenote: could this be related to using experimental: true in fleet settings initially? Based on this [discussion](https://discuss.elastic.co/t/fleet-ui-is-unusable-due-to-timeout-errors/300936/12), I turned off that setting and also tried readding the integration as well as creating new policies after reinstalling all assets.

Please let me know about can be done here.

**Comment by simitt** [comment]
@yash-gill I'm going to close this issue since we haven't heard back from you on the Elastic Agent version. If this is still a problem, please open a topic in the [apm discuss forum](https://discuss.elastic.co/c/observability/apm/58) with detailed description of the versions involved.

**Comment by yash-gill** [comment]
Hi @simitt, apologies for the delay. It was indeed the version mismatch that was causing the issue. Upgrading to 7.17 resolved the issue. Thanks a lot for the tip!
Even when my elastic agent was on 7.15.2, apm server integration in fleet showed 7.17, so I didn't catch the issue earlier.
