### ISSUE TITLE
[addFilter] Filter out transaction

### ISSUE THREAD

**Issue by Thetortuga** [elastic/apm-server#784]
Hi,

I am trying to use the addFilter feature to filter out some request.
The example in the doc seems to be outdated:

```js
apm.addFilter(function (payload) {
  if (payload.context.request && payload.context.request.headers) {
    // redact sensitive data
    payload.context.request.headers['x-secret'] = '[REDACTED]'
  }
  // remember to return the modified payload
  return payload
})
```
Indeed, `payload.context` does not exist. Instead, we could make something like that :
```js
apm.addFilter(function (payload) {
  payload.transactions.map((transaction) => {
    if (transaction.type === 'request' &&  transaction.context.request.headers) {
      transaction.context.request.headers['x-secret'] = '[REDACTED]'
    }
  })
  return payload
})
```

Now, I have to find a way to remove a certain request based on used route. I tried removing it through Array.filter but I have an error `cannot read property 'length()' of undefined`.
Is there a way to achieve this ?

**Comment by simitt** [comment]
The APM Server does not support this filter configuration. It looks like you are referring to the [Node.js Agent Reference](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-add-filter) example on how to add a filter in the _agent_. 

You can make use of the [Elastic APM Discussion Forum](https://discuss.elastic.co/c/apm) for questions and discussions. If you found a bug please create an Issue in the [Node.js Agent Github Repository](https://github.com/elastic/apm-agent-nodejs).

**Comment by Thetortuga** [comment]
My bad ! Thanks for the link
