### ISSUE TITLE
Allow clients to request non-blocking ingest behaviour

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#7872]
When using libbeat outputs, we have an arbitrary one second timeout when enqueuing events to the libbeat output event queue: https://github.com/elastic/apm-server/blob/4e5755408350f6868a1cf78270e0a358a81b989a/publish/pub.go#L160

With the new Elasticsearch output (`modelindexer`), we no longer have this arbitrary timeout. Instead, it is the client's responsibility to set a request timeout; the server will block until the request times out/the client closes the connection.

Some clients, such as Lambda, would prefer to minimise latency as the expense of possibly losing events. For Lambda, time is literally money, as invocations are billed by the amount of wall-clock time they are active.

We should look at options for clients to request non-blocking ingest, meaning that if there is queue capacity then APM Server should enqueue an event, and otherwise it should be immediately rejected.

**Comment by axw** [comment]
As an alternative, we should investigate just never blocking if all bulk indexers are flushing, i.e. today's equivalent of "queue is full". This would be similar to the old arbitrary 1 second timeout on enqueue, but now instead it would be immediate. When we investigate this option, we'll need to re-run benchmarks for backend agents.

**Comment by marclop** [comment]
@axw my idea was to introduce a `fail_fast` query parameter to the `intake/v2/events` endpoint (intake/v2/events?fail_fast=true) and return immediately if the current semaphore cannot be acquired. 

Is that sufficient for how we want to treat "immediate" processing, or would we want go a step further and create a `context.WithTimeout()` with a maximum deadline (say 1s or 500ms) to try and ensure speedy processing for that fail_fast request?

With the current interfaces, there's no way to identify when all the bulk indexers are being flushed, if we wanted to expose that in the current decoder, we'd need to do some refactoring to expose that somehow.

**Comment by axw** [comment]
> my idea was to introduce a fail_fast query parameter to the intake/v2/events endpoint (intake/v2/events?fail_fast=true) and return immediately if the current semaphore cannot be acquired. Alternatively, a header could also be used to signal that behavior, but I'm not sure it's "cleaner" or better. I think I'm leaning more towards the query parameter rather than the header since it's more visible and seems easier to use.

I think a query param is fine.

Would it be enough to just get past the semaphore though? IIANM, it is still possible for the final model processor (i.e. modelindexer) to block, say if Elasticsearch is inaccessible for a while.

If a client requests non-blocking mode, could we start a new goroutine to call ProcessBatch? I think we would need to release the batch after the goroutine is done, and reacquire the semaphore before each batch. Also, with this approach the client wouldn't receive any errors due to rate limiting or authz, as these are performed as part of the batch processing.

**Comment by marclop** [comment]
@axw thanks for confirming, I wasn't sure if the immediate processing was including handling the batch or if we just wanted to handle the batch completely async, which seems to be the case here. I think I have enough information to start the implementation now.
