### ISSUE TITLE
[Documentation - OpenTelemetry AWS Lambda] Update docs as a workaround may no longer be required

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#7883]
The [Otel AWS Lambda Node.js instrumentation documentation](https://github.com/elastic/apm-server/blob/main/docs/open-telemetry.asciidoc#instrumenting-aws-lambda-nodejs-functions) contains a workaround specifying `OTEL_EXPORTER_OTLP_ENDPOINT ` waiting for https://github.com/open-telemetry/opentelemetry-js/pull/2331 to be merged.

As this otel-js PR has been merged, we can probably simplify our documentation.

@michaelhyatt the Node.js Lambda Layer seems to have evolved with AMD64 and ARM64 layers as we can see on https://aws-otel.github.io/docs/getting-started/lambda/lambda-jsas you can see on the screenshots below . We probably also have to update this part.

**Before**

<img width="300" alt="image" src="https://user-images.githubusercontent.com/459691/163409117-10db6c09-bcb6-4be7-a19d-7c4581d4c62c.png">

**Today**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/459691/163409258-9df996ee-9e73-4120-9f08-ac0a45acae58.png">

**Comment by michaelhyatt** [comment]
Created #8005

**Comment by simitt** [comment]
The workaround has been removed, closing this issue.
