### ISSUE TITLE
Access log: using warning level for status code >= 400

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-server#793]
Currently, the level for "access log" style log messages is hard coded to `info`: https://github.com/elastic/apm-server/blob/edb22ae93c62309902cfa3d7454881c90a1e9259/beater/handlers.go#L179-L181

Most people probably want to run the APM Server with a lower level, e.g. warning, and hence won't see any access logs at all. This is probably fine in normal operation, but you'd probably still want to see logs for error responses. Could we set the level dynamically depending on the response status code, e.g. if response code >= 400 set it to `warning`?

**Comment by simitt** [comment]
If an error occurs processing the request, it is logged as error here: 
https://github.com/elastic/apm-server/blob/edb22ae93c62309902cfa3d7454881c90a1e9259/beater/handlers.go#L340-L350

**Comment by beniwohli** [comment]
which would make the corresponding access log entry even more valuable, as it contains additional information (source IP, user agent [which is the agent name and version for backend agents], ...), so you can correlate the error to a specific machine or agent version.

btw, does the access log entry contain the request ID? If not, we should probably add it for easier correlateablility™️

**Comment by graphaelli** [comment]
yeah, that happens here: https://github.com/elastic/apm-server/blob/edb22ae93c62309902cfa3d7454881c90a1e9259/beater/handlers.go#L169

**Comment by beniwohli** [comment]
Awesome!

**Comment by roncohen** [comment]
to summarize, at the moment we'll log an access log for each request and an additional error log with the `error` level for requests that caused errors. 

@beniwohli you think this is sufficient?
