### ISSUE TITLE
Is there a way to change the transaction to the interface name?

### ISSUE THREAD

**Issue by Phoebus888** [elastic/apm-server#7931]
![image](https://user-images.githubusercontent.com/45359605/164418408-5f146b83-bc9f-4b19-861a-6a2925c22e59.png)
Interface names are more intuitive

**Comment by simitt** [comment]
Hi @Phoebus888 , the APM Server is not actually infering the transaction name. This is done by the APM agents. 
Please open a topic on this in the [apm discuss forum](https://discuss.elastic.co/c/observability/apm/58).
