### ISSUE TITLE
Move request/response context objects in under parent http property?

### ISSUE THREAD

**Issue by watson** [elastic/apm-server#794]
As discussed in https://github.com/elastic/apm-server/pull/785#discussion_r177718069 it might make sense to move the current `context.request` and `context.response` into `context.http.request` and `context.http.request`.

This will make it clearer that these objects deal with HTTP.

The APM UI will have to be updated with this change though, so that we still show the request and response correctly in their individual tabs.

The big question though is if it's worth the hassle (breaking change and all)

ping @elastic/apm-server @elastic/apm-ui @elastic/apm-agent-devs

**Comment by beniwohli** [comment]
To repeat my concerns from #785: any such move involves a lot of churn for any users of this data (e.g. people that built their own dashboards/watchers or custom scripting using fields in `request` / `response`). Going through with such a change just because it makes the Schema a bit nicer is IMO not worth the work we'd put our users through.

The counterpoint to this is of course that we don't have that many users yet, so doing a change now is better than later down the line. Still, I think we need better arguments than "it makes the schema marginally nicer".

**Comment by axw** [comment]
Agreed that we shouldn't do this lightly, but I think we should take a pass over the API for 7.0, especially if we're going to be making other changes, e.g. to support distributed tracing.

Transaction context is currently biased towards HTTP. When we want to represent other types of transactions, we're currently forced to use "custom" context, e.g. Lambda [0] or gRPC [1].

While you could represent both of those as having a request and a response, the contents will be very different. So we could have request/response with sparsely populated fields, or we could have a application protocol specific fields. I'm not convinced that we even need to split the request/response fields; we could mix them together, and prefix fields with "request_" or "response_" where disambiguation is required (e.g. for headers.)

Here's an example of what I think would be ~ideal.

```json
{
  "http": {
    "method": "GET",
    "url": {"full":"..."},
    "http_version": "1.1",
    "request_headers": {"content-type": "text/plain"},
    "response_headers": {"content-type": "text/plain; utf-8"},
    "status_code": 418
  }
}
```

This would also fit well in span context, and would address https://github.com/elastic/apm-server/issues/777. For span context, we currently have a "db" field with all of the database-specific context in it, so IMO it makes sense to have an "http" alongside it.

[0] https://github.com/elastic/apm-agent-nodejs/pull/234/files#r166961373
[1] https://github.com/elastic/apm-agent-go/commit/201861cc6fee3e7b24825eef13f65f3b3a4655aa#diff-3891395e0a8b3b75c08fe628c3a2e1e9R49

**Comment by axw** [comment]
@jahtalab aren't they already differentiated by transaction vs. span? Transaction is incoming, span is outgoing? I guess things are a little different for frontend though. Either way, direction is orthogonal to the protocol, so I'd prefer something like option 3, but with `"type": "incoming"` as a sibling of `"http": {...}`.

**Comment by simitt** [comment]
@watson a lot of fields have been moved around for ECS in 7.0 in the ES template. This also includes `request` and `response` objects being moved to `http`, see [request](https://github.com/elastic/apm-server/blob/master/_meta/ecs-migration.yml#L46) and [response](https://github.com/elastic/apm-server/blob/master/_meta/ecs-migration.yml#L162) in the ES template. 

I will close this issue. If we want to also rework the Intake API, we should open an issue in the [apm repo](https://github.com/elastic/apm) and have a look at all fields that have been moved around.
