### ISSUE TITLE
Add missing config file descriptions

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#799]
ATM descriptions for following config sections are missing in the official documentation:
* `apm-server.*`
* `queue.*`

Those settings are important to describe for any performance related tweaks.

**Comment by jalvz** [comment]
This is no longer the case, right?

**Comment by simitt** [comment]
I think everything configured directly at `apm-server` except for `apm-server.frontend` is still missing in the docs. Same for `queue.*` .

**Comment by jalvz** [comment]
If in the config section you only want to cover the `apm-server` group I think we are all set. 
`queue.*` are described in the relevant context (https://www.elastic.co/guide/en/apm/server/6.3/tune-apm-server.html), which i think is good. 

If you mean to describe all the options in the config section, then leave this open indeed.

**Comment by jalvz** [comment]
Oh I didn't know we had all that undocumented. Ill show myself out then...
