### ISSUE TITLE
Add automated build to docker hub

### ISSUE THREAD

**Issue by OmgImAlexis** [elastic/apm-server#80]
Could you please add automated builds to docker hub.

**Comment by ruflin** [comment]
Hi @OmgImAlexis 

Thanks for your request. Elastic has its own docker registry (example ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html). As soon as we are ready we will have our own containers on there. If you want to build your own container for now, have a look at the beats docker containers which have very similar requirements: https://github.com/elastic/beats-docker

**Comment by roncohen** [comment]
This is now documented here: https://www.elastic.co/guide/en/apm/server/current/running-on-docker.html

Thanks @OmgImAlexis !
