### ISSUE TITLE
Request full url and query params max length

### ISSUE THREAD

**Issue by hotrush** [elastic/apm-server#801]
I noticed that request url `full` and `query` params having max length in 1024 symbols.

https://www.elastic.co/guide/en/apm/server/master/transaction-api.html#transaction-request-schema

Is there any reason for this and is there any workaround to log my query params except custom block? Just because cutting this looks some weird. Thanks

**Comment by simitt** [comment]
We are limiting fields when they are indexed as an Elasticsearch `keyword`. The reason for this is that the default value for `ignore_above` is set to `1024` in the underlying beats framework.

Unfortunately there is no easy way to workaround this atm.

**Comment by hotrush** [comment]
@simitt thanks for your response. How do you this what is better, trim urls to 1024 symbols length or cut query params at all if length > 1024?

**Comment by simitt** [comment]
The most common implementation atm in the official agents is to cut off at 1024.

**Comment by hotrush** [comment]
@simitt ok, thanks
