### ISSUE TITLE
Traces in Kibana are not data streams, ILM policies don't apply, filling up disk space

### ISSUE THREAD

**Issue by slhck** [elastic/apm-server#8018]
**APM Server version** apm-server version 8.1.3 (amd64), libbeat 8.1.3 [1c7bc9e0bb5a3ab54cb67a881c49b4fda7a62241 built 2022-04-19 07:04:09 +0000 UTC]

**Description of the problem including expected versus actual behavior**:

I have two ELK clusters that I have upgraded from 7.x to 8.x using the recommended migration guides. I have set up APM Server binary with a few agents sending data using Ruby and Python libraries. Both operate fine, except that the APM traces are now filling up the disk space.

Here is the index:

![image](https://user-images.githubusercontent.com/582444/166216201-7179be74-3cdd-4e09-a388-77a8212c86f7.png)

Here are the templates:

![image](https://user-images.githubusercontent.com/582444/166216267-88d9bbc8-c901-4f6a-b557-e4a9f6ddd205.png)

As you can see, the default policy for traces is not applied:

![image](https://user-images.githubusercontent.com/582444/166216336-6c19d909-1e15-4ba0-bd4a-3ee81070ad09.png)

I am unable to create my own ILM policy with rollup, since the traces-apm-default index is just an index, not an index pattern with different underlying indices; just one huge index that eats up disk space.

I have tried [migrating to data stream](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-migrate-to-data-stream.html#indices-migrate-to-data-stream-request) but it fails with:

```
➜ curl -k -XPOST -u elastic:XXXXX https://localhost:9200/_data_stream/_migrate/traces-apm-default
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"alias [traces-apm-default] does not exist"}],"type":"illegal_argument_exception","reason":"alias [traces-apm-default] does not exist"},"status":400}%                                                                                                                                                                
```

Also, using `traces-apm*` does not work:

```json
{"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:admin/data_stream/migrate] is unauthorized for user [elastic] with roles [superuser], this action is granted by the index privileges [manage,all]"}],"type":"security_exception","reason":"action [indices:admin/data_stream/migrate] is unauthorized for user [elastic] with roles [superuser], this action is granted by the index privileges [manage,all]","caused_by":{"type":"illegal_argument_exception","reason":"the action indices:admin/data_stream/migrate does not support wildcards; the provided index expression(s) [traces-apm*] are not allowed"}},"status":403}
```

Here is another user experiencing exactly the same issue: https://discuss.elastic.co/t/traces-apm-default-not-create-as-data-stream-after-migrate-to-apm-integration/302511

**Steps to reproduce**:

- Have a cluster at latest 7.x
- Upgrade to 8.x

**Provide logs (if relevant)**:

I have no migration logs available unfortunately.

**Comment by slhck** [comment]
I should add that I can view traces in the APM frontend:

![image](https://user-images.githubusercontent.com/582444/166217609-bf6ff442-92dc-4958-bcf8-7b5ba2e4832b.png)

However, clicking on one of them shows graphs with latency, throughput, failed transaction rate and time spent by span type, but not the actual latency distribution:

![image](https://user-images.githubusercontent.com/582444/166217717-4d04dfe9-e9ec-4d77-866e-7b03be75d6c7.png)

**Comment by simitt** [comment]
Hi @slhck the indices should indeed be data streams, with a default ILM policy being applied. 
Can you please provide detailed information about the upgrade process? It seems that you are running a self managed stack, please let us know in detail if you are using docker, installing from package manager etc. and in which exact order you upgraded the stack. This will help us try to reproduce; we are not yet aware of a general upgrade problem.

**Comment by slhck** [comment]
Yes, indeed I am running a self-managed stack. In principle it uses the same setup as https://github.com/deviantony/docker-elk – with the addition of apm-server added via its official image. The apm-server is reachable from Elasticsearch and Kibana via the Docker network.

During migration I simply replace the upstream images in the Dockerfile and reboot the individual services, beginning with Elasticsearch, and once that reaches green status, the other services (Kibana, Logstash, APM Server).

I have migrated in the following order:

- 7.17.0 (ensuring no problems are indicated in Kibana's upgrade assistant)
- 8.1.0
- 8.1.1
- 8.1.2
- 8.1.3

When I set up a fresh APM integration on 8.1.3, this bug is not present, and `traces-apm-default` is a data stream.

**Comment by slhck** [comment]
Meanwhile, do you believe it is possible to remove the APM integration entirely from Kibana, and add it again to set up the correct indices? (If so, how?)

**Comment by simitt** [comment]
> Meanwhile, do you believe it is possible to remove the APM integration entirely from Kibana, and add it again to set up the correct indices? (If so, how?)

You can navigate to the Fleet UI in Kibana and remove the APM integration and then add it again. Looking at the docker setup that you shared it seems that you are running the `standalone` version of APM Server and not have it managed by Elastic Agent. Therefore removing just the integration setup and adding it again shouldn't be too interruptive. 
Changes are only applied to new indices though. Is it feasible to reindex the existing `traces` index which is not a data stream, once you ensured the setup is as expected?

**Comment by slhck** [comment]
>  you are running the standalone version of APM Server and not have it managed by Elastic Agent.

Correct.

> Is it feasible to reindex the existing traces index which is not a data stream, once you ensured the setup is as expected?

I am not sure what you mean by that exactly. I was actually planning to just delete it and start from scratch. Do you mean reindexing it to the (hopefully newly generated) data stream, so that I can keep the old data around?

**Comment by slhck** [comment]
Hm, so I went to the Integrations settings and first deleted the individual integrations listed for APM and System (I think they were called `apm-1` and `system-1`). Then I removed the integrations altogether. Now no integrations are shown:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/582444/166415655-bc3effec-8d58-4327-9a36-75659d62789b.png">

I also deleted the whole `traces-apm-default` index after that.

I then rebooted the entire stack, but it automatically created the wrong index again, despite no integration being set up:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/582444/166415740-b5082310-e0fd-4218-92eb-134032bd8fbe.png">

Could you please let me know how I can completely remove the APM integration and start from scratch without actually destroying the entire cluster?

**Comment by simitt** [comment]
> Could you please let me know how I can completely remove the APM integration and start from scratch without actually destroying the entire cluster?

Could you remove the integration via Fleet UI, remove the index, then add the integration again (which will force an overwrite of the index templates etc) and then start up apm server again. 

Please also let me know at which point you migrated to data streams (from indices). Was that in `7.17` (following [upgrade-to-data-streams](https://www.elastic.co/guide/en/apm/guide/7.17/upgrade-to-data-streams.html)) or did you first upgrade to `8.0` and then after starting the stack install the Integration?

**Comment by slhck** [comment]
Ah, wait a second! I have not seen https://www.elastic.co/guide/en/apm/guide/7.17/upgrade-to-data-streams.html. So I didn't change this. I guess I didn't see it and Kibana (when upgrading to 8.0) also didn't inform me about it (despite having had APM enabled), neither did the logs, and it happily keeps ingesting data to the old index. Maybe that's why I didn't notice it.

I will definitely try this.

> Could you remove the integration via Fleet UI

How exactly? When I go to Management --> Fleet, I have no Agents, as I have no Fleet Server.

![image](https://user-images.githubusercontent.com/582444/166934116-286a63f2-99b9-4a08-bc34-2dc5a6e2bf15.png)

I do have individual Agent policies, Enrollment tokens, Data streams, and Settings listed. Should I delete them manually from each of the tabs?

**Comment by slhck** [comment]
It seems that this YML setting did it:

```yaml
apm-server:
  data_streams.enabled: true
```

I basically had to restart the server.

The problem is that this only worked for one of the sever. For the other one, it didn't actually show the Elastic APM integration as installed, so I manually went to `/app/fleet/integrations/apm-8.2.0/add-integration` and added it again.

For what it's worth, reading the document you linked to, it only says "should upgrade to data streams" and not "must upgrade to data streams", so even if I had seen it, I _might_ not have done the migration. Even now I guess I would have expected the ILM policies to still work on the traces index, for people who did not migrate.

I wonder if there's anything else that could be done to prevent users from runing into the same issue. Maybe:

- Throwing an error in APM Server in case this setting is not present after a certain version
- Keeping an ILM policy around that clears out old traces if an index exists
- Preventing the user from using the Elastic APM integration when the data stream is not actually set up

As I mentioned above, the recent changes related Elastic Agent and Fleet were a bit overwhelming to me as an end user. I can grasp the standalone APM server setup, but there's quite a bit of terminology now floating around with Fleet and Legacy APM etc., so it's easy to miss having to make that change.

**Comment by simitt** [comment]
Thanks for confirming that this helped @slhck . For the second server, please follow the same procedure of removing the apm integration, removing the index, adding the integration again and then restarting apm-server. 

>>  Could you remove the integration via Fleet UI

>How exactly? When I go to Management --> Fleet, I have no Agents, as I have no Fleet Server.

You can navigate to the APM Integration's Settings page, where you will find an _Uninstall/Install Elastic APM_ button. 
<img width="1029" alt="Screenshot 2022-05-05 at 16 37 06" src="https://user-images.githubusercontent.com/5555349/166947787-20e16941-f377-4923-bc88-8f2814ff17d5.png">


I did not mean to imply that setting the datastream enabled in `7.17` is a required step. Everything should still work without it, as from `8.0` on, the APM server should block writing data until the Integration is installed. Installing the APM integration is a manual process though (outside of the Elastic cloud that we can manage). 
With this additional information I can dig into it further, it does sound like there is a bug somewhere. 

> As I mentioned above, the recent changes related Elastic Agent and Fleet were a bit overwhelming to me as an end user. I can grasp the standalone APM server setup, but there's quite a bit of terminology now floating around with Fleet and Legacy APM etc., so it's easy to miss having to make that change.

We appreciate the feedback and keep iterating on the documentation and onboarding process to make this smoother.

**Comment by simitt** [comment]
When I try to replicate this, I do see the expected log message in the apm-server logs that it cannot index events until the Integration is installed
```
apm_1               | {"log.level":"error","@timestamp":"2022-05-05T15:16:07.567Z","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":62},"message":"precondition 'apm integration installed' failed: integration package not yet installed: to remediate, please install the apm integration: https://ela.st/apm-integration-quickstart","service.name":"apm-server","ecs.version":"1.6.0"}
```
Once I install the integration, the datastreams are set up and everything worked as expected (even without the additional step of setting `apm-server.data_streams.enabled: true`). 

Since another user was reporting the same issue (as you also mentioned earlier), I suspect that we might have a timing issue somewhere.

**Comment by simitt** [comment]
For deleting the apm data and setup you can navigate to the Kibana Index Management and manually delete 
* indices 
* data streams
* index templates
* component templates
* ilm policies
* ingest pipelines

for `traces-apm`, `logs-apm`, `metrics-apm`. 

Note: I don't believe you have to delete the `apm*` indices, templates etc from `7.x` deployments and suggest you keep them if you are still interested in the data
<img width="1917" alt="Screenshot 2022-05-06 at 09 14 46" src="https://user-images.githubusercontent.com/5555349/167084945-21a2e421-4131-4433-ad7c-68169b531898.png">
<img width="1912" alt="Screenshot 2022-05-06 at 09 14 33" src="https://user-images.githubusercontent.com/5555349/167084957-58888f25-f6ba-48b2-b7ef-8bba531330c6.png">
<img width="1912" alt="Screenshot 2022-05-06 at 09 14 21" src="https://user-images.githubusercontent.com/5555349/167084970-237bb729-985c-4eec-8e91-359ec71379f0.png">

**Comment by slhck** [comment]
I stopped the APM server, then deleted everything I can.

It worked except for the `.apm-agent-configuration` index and the `.apm-custom-link` index, which Elasticsearch refuses to delete, even when using the `elastic` user:

```json
{
  "error": {
    // ...
    "type": "security_exception",
    "reason": "action [indices:admin/delete] is unauthorized for user [elastic] with roles [superuser] on restricted indices [.apm-agent-configuration], this action is granted by the index privileges [delete_index,manage,all]"
  },
  "status": 403
}
```

Anyway, that seems to have done the job:

![image](https://user-images.githubusercontent.com/582444/167095655-2b26a97e-69aa-44b4-b6bb-5889facedf37.png)

I'm not sure what differed between those two ELK instances, but some remaining configuration must have caused the index to become recreated.

Thanks for your help!

**Comment by simitt** [comment]
Glad you could sort this out and thanks for your patience. 

I further investigated the code and found the root cause for how this can happen: The server ensures it only writes to ES if the templates are installed, but when the server is shut down before the APM Integration installs, it still flushes all events to ES, independent of whether or not the integration has been installed. Confirming that this is a bug in the APM Server.
