### ISSUE TITLE
Otel Java agent 1.13.0 renamed JVM GC metrics to follow Otel Semantic Conventions

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#8042]
The [Otel Java agent 1.13.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.13.0) renamed JVM GC metrics to follow the [OpenTelemetry Semantic Conventions for JVM metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics)

Old metrics:
```
runtime.jvm.memory.area{type="used",area="heap"} 2000000
runtime.jvm.memory.area{type="committed",area="non_heap"} 200000
runtime.jvm.memory.area{type="used",pool="PS Eden Space"} 2000
```

New metrics:
```
 process.runtime.jvm.memory.init{type="heap",pool="G1 Eden Space"} 1000000
 process.runtime.jvm.memory.usage{type="heap",pool="G1 Eden Space"} 2500000
 process.runtime.jvm.memory.committed{type="heap",pool="G1 Eden Space"} 3000000
 process.runtime.jvm.memory.max{type="heap",pool="G1 Eden Space"} 4000000
 process.runtime.jvm.memory.init{type="non_heap",pool="Metaspace"} 200
 process.runtime.jvm.memory.usage{type="non_heap",pool="Metaspace"} 400
 process.runtime.jvm.memory.committed{type="non_heap",pool="Metaspace"} 500
```

See new code https://raw.githubusercontent.com/open-telemetry/opentelemetry-java-instrumentation/v1.13.1/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/MemoryPools.java

**Comment by cyrille-leclerc** [comment]
@AlexanderWert could you please help us map the new Otel metrics to the Elastic APM GUI metrics?

**Comment by atahar-shapuri** [comment]
@kruskall  Can you please let us know ,Which version this is fixed ?
