### ISSUE TITLE
Document motivation for validation rules concerning the Intake API 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#805]
As questions about the structure or specific validation rules concerning the Intake API are coming up more often, find a good way to documen major outcomes of previous discussions and motivations for specific decisions.

**Comment by jalvz** [comment]
I suggest to remove this issue. Is to time consuming, we don't even remember many decisions, and we are going to have a new API anyways. I think we should do it going forward, but not retroactively.
Thoughts?

**Comment by simitt** [comment]
Fine with me, I remember opening it as we had several questions about decisions at one point.
