### ISSUE TITLE
Create docker-compose.yml for fleet managed apm-server

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8052]
Create a `docker-compose.yml` for an easy out-of-the-box onboarding experience to users. This isn't necessarily meant for production usage, but should provide an easy way to spin up ES, Kibana, Elastic Agent with Fleet Server and have the APM Integration added and configured.

To achieve this, leverage the current [docker-compose.yml](https://github.com/elastic/apm-server/blob/main/docker-compose.yml), add apm integration and leverage the Kibana preconfiguration API for configuring the agent policy with apm integration enabled. 

We also want to share this with @insukcho as this can be useful for the support team to spin up a stack with managed apm-server and test things.

**Comment by renat473** [comment]
Hi @simitt ,

what would it take to start a fleet server in a local environment connected to elasticloud, is there such a possibility?

**Comment by marclop** [comment]
@renat473 it is possible, you can navigate to your Elastic Cloud deployment and follow this guide: https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html

This GitHub issue is intended to ease development and spinning up a local Elastic Stack. It doesn't really have anything to do with Elastic Cloud.

**Comment by cdavid15** [comment]
I started looking at trying to migrate from legacy APM server which has been solid for us passed 3 years to the newer approach and this would be incredibly useful as we run a full on prem solution. 

I found that the documentation is very heavy on the physical install method opposed to containerised and information relating to the required preconfiguration api calls is lacking / difficult to find.  While I am sure I’ll be able to piece it all together having a simple reference file that can just be spun up would have huge benefits. 

Will keep an eye out on this and hopefully see something up the 8.6 release.

**Comment by simitt** [comment]
After some internal discussion, we are moving forward with a different solution, built on k8s and [tilt](https://tilt.dev/). With @axw's PR https://github.com/elastic/apm-server/pull/9421 one can issue `tilt up` to spin up Elasticsearch, Kibana, Fleet Server, and an Elastic Agent with the APM integration injected. Under the hood, this uses ECK.

**Comment by simitt** [comment]
Developer docs on how to use `tilt` can be found at [dev-docs#tilt](https://github.com/elastic/apm-server/blob/main/dev_docs/TESTING.md#tilt--kubernetes).
