### ISSUE TITLE
Changing the APM integration namespace breaks ingestion

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-server#8087]
**APM Server version** (`apm-server version`): 8.2.0

**Description of the problem including expected versus actual behavior**: Changing the APM integration namespace after setting up the integration breaks event ingestion. 

**Steps to reproduce**:

I tested both locally (8.3.0-snapshot) and on Elastic Cloud (8.2.0)

 1. Spin up the Stack and add the APM integration. Use the recommended `default` namespace.
 2. Send trace events to APM Server.
 3. Edit the APM integration and change the namespace to something like `prod`. Save the integration and wait for the Elastic Agent to update.
 4. Send trace events to APM Server. As far as I can tell, there aren't any agent or server logs to indicate ingestion isn't working; the APM Server logs `request accepted` (see screenshot below).
 5. View your data streams and indices and note that there are no new `*apm-prod*` data streams or indices and that events haven't been indexed.

**Provide logs (if relevant)**: 
<img width="1195" alt="Screen Shot 2022-05-11 at 8 34 11 AM" src="https://user-images.githubusercontent.com/5618806/167889624-cbc3c145-f6e9-4a8f-8e50-54d3f838731a.png">

**Comment by simitt** [comment]
This seems to be a regression on `8.2`. Te namespace actually worked in `8.1`. I just confirmed that data can be successfully ingested to a custom namespace in `8.1`.
