### ISSUE TITLE
Server fails to start when empty config value is passed

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#809]
Currently starting apm server with `./apm-server -e -E dotted.path.variables=` fails. 
This can happen in scripts when a variable is sent although the value for it can be optional. 

The error is raised at `ucfg.Unpack(beaterConfig)`: 
https://github.com/elastic/apm-server/blob/5cac6cc5c5ae4f70b4c9d0dc5c5dbf7ac95e42c2/beater/beater.go#L26-L28

**Comment by graphaelli** [comment]
@simitt is that exactly the command you're triggering a failure with?  I'm not seeing that behavior on any version of apm-server I've tried.

**Comment by simitt** [comment]
Sorry for being unclear, the `dotted.path.variables` is just a placeholder. If you use some existing config value the server doesn't start, e.g.. `./apm-server -E apm-server.frontend.enabled=`

Output is 
`Exiting: Error reading config file: can not convert 'object' into 'bool' accessing 'apm-server.frontend.enabled'`

**Comment by jalvz** [comment]
Incorporated here https://github.com/elastic/apm-server/commit/b67a9c068b58b0e0e0b4ebfd114dc6a7d645a0cd
