### ISSUE TITLE
Global labels in transaction metrics

### ISSUE THREAD

**Issue by sqren** [elastic/apm-server#8139]
**Feature request**
Global labels should be available on transaction metrics.

**Background**
For 8.4 the APM UI team is planning to compute which services that belong in a service group at runtime (https://github.com/elastic/kibana/issues/128623). 

When a user creates a service group they are asked to provide a kql string that matches the services they want to include.
This kql string is then used as a filter when retrieving the services for a selected service group. 
The fields in the kql string must be limited to dimensions available in transaction metrics, to avoid falling back to transaction events at runtime.

Customers have requested the ability to create service groups based on business-specific global labels like `department_name` and `department_owner_email`.

**Comment by simitt** [comment]
@sqren and I had a discussion around this, where I raised following concerns:

* global labels are user controlled: if we start adding the global labels to the transaction metrics, then they need to be reflected in the aggregation key. At the moment the aggregation key consists of well defined attributes, with this change we would open it up to user controlled cardinality. 
* Adding global labels to metrics documents increases the number of fields that are part of the mapping of the internal apm metrics data stream, potentially increasing the risk of mapping explosion. @sqren do you know if we have telemetry on global labels (how many labels per service)? For assessing the risk, it would be interesting to have insights into how global labels are currently used. 

How should the APM Server behave when global labels would be causing any of the two mentioned issues:
* should there be a safeguard such as setting an arbitrary limit of how many labels are considered safe for the aggregation key, and all additional labels be ignored? This would lead to data inconsistency, especially when running multiple APM Servers where different lables are considered until the maximum is reached. 
* should customers be able to turn off using global lables in transaction metrics as a workaround? If so, how/where should this be configurable? 

@axw do you have any thoughts on this?

**Comment by simitt** [comment]
> This is no more a problem for internal metrics than it is for traces, is it? I think this would eventually be addressed by https://github.com/elastic/apm-server/issues/5963.

In general I agree, but when introducing the labels on metrics documents, there might be upgrade issues for users that had almost reached the mapping limits in their previous version. This might be a theoretical issue though and not worth holding back the whole feature.

**Comment by sqren** [comment]
> @sqren do you know if we have telemetry on global labels (how many labels per service)?

We don't have anything of that kind, no. If we were to add telemetry for this, how would we differentiate between a global label and a normal label? I assume they are both stored under `labels.*`

**Comment by axw** [comment]
Right, there's no way to do that just looking at the docs. We would need to produce the telemetry in APM Server.
