### ISSUE TITLE
Standardize on backend agent buffering and APM Server communication

### ISSUE THREAD

**Issue by watson** [elastic/apm-server#818]
It would be a good idea if we standardized on how backend agents buffer data before it's sent to the APM Server and how the agents handle server communication failure etc.

As GitHub isn't the ideals environment for bigger threaded discussions, I've instead created a document on Google Drive that allows everyone to make inline comments and add edit-suggestions.

The document is a first draft of a set of programming language neutral rules that hopefully can encompass everybody. It contains a lot of assumptions, including default values that might not be ideal. Please scrutinize!

https://docs.google.com/document/d/1a5O7lV1C77iVZSBDwTPbHC8nkiBu0mkaJy74WrVnX_Q/edit?usp=sharing

The document is public to the internet, so everyone should be able to participate 😄 

/cc @elastic/apm-agent-devs @elastic/apm-server

**Comment by alvarolobato** [comment]
@watson does this still make sense? What are the next steps?

**Comment by watson** [comment]
The new intake API supersedes this
