### ISSUE TITLE
How do I build an apm rally dataset? 

### ISSUE THREAD

**Issue by wajika** [elastic/apm-server#8183]
This is not a bug, but I don't see how I should successfully get it to work.
I want to test the writing test of multiple fields and multiple data types in elasticsearch. When I browsed the apm code repository, I found that there is a data production tool called rally. I think it should meet my requirements, so I try to run the gencorpora directory code, but it didn't work either. what should I do?

```
/home/wajika/apm-server/rally/gencorpora# go run .
2022/05/22 14:17:39 Generating corpus "http_and_sql"
Traceback (most recent call last):
  File "/home/wajika/apm-server/script/cat_bulk.py", line 57, in <module>
    proc = subprocess.Popen([
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './apm-server'
```

**Comment by axw** [comment]
@wajika sorry, the apm-server/rally bits are a bit incomplete. Please try this:

1. `docker-compose up -d` -- starts Elasticsearch and Kibana
2. `make apm-server`-- builds an apm-server binary locally, which is used for generating the Rally test data (corpora)
3. `make rally` -- runs Rally with the generated corpora, sending to Elasticsearch running in Docker from step 1

**Comment by wajika** [comment]
> axw thanks you for the fast reply.

I also found other interesting things yesterday, don't know if they help me.
I see you are talking about "hey-apm" and "apmbench", but I didn't find the address of "apmbench", I just want to test whether the remote elasticsearch performance can be maintained for long-term use, is hey-apm simpler than rally?

**Comment by axw** [comment]
@wajika both hey-apm (https://github.com/elastic/hey-apm) and apmbench (https://github.com/elastic/apm-server/tree/main/systemtest/cmd/apmbench) are used for measuring the performance of apm-server. As you said above:

> I want to test the writing test of multiple fields and multiple data types in elasticsearch.

I think you want Rally. I would like to clarify something though: are you interested in benchmarking a change to APM's Elasticsearch schema? If so, then `make rally` in apm-server is the way forward. If the change you would like to test is not specifically related to APM's schema, then maybe you should be using Rally directly: https://github.com/elastic/rally

**Comment by wajika** [comment]
> @wajika both hey-apm (https://github.com/elastic/hey-apm) and apmbench (https://github.com/elastic/apm-server/tree/main/systemtest/cmd/apmbench) are used for measuring the performance of apm-server. As you said above:
> 
> > I want to test the writing test of multiple fields and multiple data types in elasticsearch.
> 
> I think you want Rally. I would like to clarify something though: are you interested in benchmarking a change to APM's Elasticsearch schema? If so, then `make rally` in apm-server is the way forward. If the change you would like to test is not specifically related to APM's schema, then maybe you should be using Rally directly: https://github.com/elastic/rally

I probably found hey-apm and apmbench from what you're talking about, but I just don't have any information to understand how to do it. I think they are great, just lack the documentation introduction.
Regarding "are you interested in benchmarking a change to APM's Elasticsearch schema?" , I'm sorry, I'm not testing APM, I use the apm rally dataset because our elasticsearch saves more apm data than logs, And the schema model of apm is more complicated than that of ordinary logs.
I think if you can use apm's dataset to test, you should be able to find a suitable elasticsearch hardware configuration.
esrally is a bit too bulky for me.

**Comment by wajika** [comment]
I can switch to esrally, can you provide the apm rally dataset directly?

**Comment by axw** [comment]
> I probably found hey-apm and apmbench from what you're talking about, but I just don't have any information to understand how to do it. I think they are great, just lack the documentation introduction.

Sorry about that. These tools have been developed primarily for the APM Server team's internal usage.

> I'm sorry, I'm not testing APM, I use the apm rally dataset because our elasticsearch saves more apm data than logs, And the schema model of apm is more complicated than that of ordinary logs.
> I think if you can use apm's dataset to test, you should be able to find a suitable elasticsearch hardware configuration.

Understood.

> I can switch to esrally, can you provide the apm rally dataset directly?

Sorry, this is not something we provide. What you can do is use Rally to extract the documents out of Elasticsearch, and use those to create "tracks". See https://esrally.readthedocs.io/en/stable/adding_tracks.html#creating-a-track-from-data-in-an-existing-cluster
