### ISSUE TITLE
Re-add the sourcemap: write privilege to the docs <= 8.2

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8192]
The APM Api Key docs do not list the `sourcemap:write` privilege anymore. However, if one creates an API Key via Kibana APM UI with default settings, this privilege is still required. 

The docs should be updated to contain the `sourcemap:write` privilege until they have also been removed in Kibana (https://github.com/elastic/kibana/issues/132689). 

Refereneces that need to be updated to contain the `sourcemap: write` privilege:
* https://www.elastic.co/guide/en/apm/guide/8.2/api-key.html#create-api-key-user
* https://www.elastic.co/guide/en/apm/guide/8.2/api-key-legacy.html
* https://www.elastic.co/guide/en/apm/guide/8.2/beats-api-keys.html (this partially overlaps with the `api-key-legacy.html` resource, maybe combine them?)

**Comment by bmorelli25** [comment]
I'm not sure I follow. We removed the `sourcemap:write` privilege because of the conversation in https://github.com/elastic/apm-server/issues/6844#issuecomment-1121380766. Are you saying that in order to make a source map for any privilege with the APM UI, this privilege needs to be included?

**Comment by simitt** [comment]
Removing the `sourcemap: write` is generally the right move. But the Kibana UI has not removed it yet and it is ticked by default, leading to an error when the user role has been created without that permission. I described it in https://github.com/elastic/kibana/issues/132689. My suggestion is to keep the role and the APM Kibana UI behavior in line for a better user experience.

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/apm-server/pull/8330.
