### ISSUE TITLE
TBS docs list a valid sample rate of 1, but APM Server does not support it

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8222]
While the example docs list `1` as a valid value for TBS sampling rate, the APM Server rejects it: 
```
- sample_rate: 1 
  service.environment: production
  trace.name: "GET /very_important_route"
- sample_rate: .01 
  service.environment: production
  trace.name: "GET /not_important_route"
- sample_rate: .1 
```

This is due to https://github.com/elastic/apm-server/blob/main/x-pack/apm-server/sampling/config.go#L237:L245, where a value of `1` is specifically excluded. 

We either need to update the docs and explain why 100% sampling rate is excluded, or change the limits.

**Comment by simitt** [comment]
@axw you left a comment in the code, can you please add some more context on the problem space.

**Comment by axw** [comment]
> While the example docs list 1 as a valid value for TBS sampling rate, the APM Server rejects it:

Nit: where are there examples with `1` as a valid value? The examples in the description are `.01` and `.1`.

> can you please add some more context on the problem space

I had the intention of optimising the case where 100% sampling was desired, by bypassing all the reservoir sampling. I don't recall if there was any good reason to outright reject 100% sampling rate. I can't see one now, looking through the code. Modifying it to accept 1 also does not cause any issues. I'll relax the constraint, and open another issue to optimise the 100% case.

**Comment by frconil** [comment]
FWIW this is what we have documented https://www.elastic.co/guide/en/apm/guide/8.2/configure-tail-based-sampling.html#_example_configuration

**Comment by axw** [comment]
Thanks. My eyes glanced over the first policy (also copied in the description), where the sample rate is indeed `1`.
