### ISSUE TITLE
Manual Test Plan for 8.3.0 release

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8224]
When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished. Testing can be started when the first build candidate (BC) is available.

* [x] Smoke Testing ESS setup: Given a lack of automated tests running on ESS, we need to conduct some manual testing on Cloud to ensure no regressions are introduce. 
  * [x] Create an _APM & Fleet Server_ deployment in `7.17` and then upgrade to `8.3.0` (BC) and verify that
    * [x] The APM Server starts up and can ingest data without throwing any errors, data show up in the APM UI.
    * [x] When enabling metrics collection in the Cloud UI, the Stack Monitoring UI shows data for the APM Server. 
    * [x] The cloud troubleshooting logs and metrics are accessible as expected. 
  * [x] Create an _APM & Fleet Server_ deployment in `7.17` and then upgrade to `8.3.0` (BC) and _switch to managed mode_ and verify that
    * [x] The APM Server starts up and can ingest data without throwing any errors, data show up in the APM UI.
    * [x] When enabling metrics collection in the Cloud UI, the Stack Monitoring UI shows data for the APM Server. 
    * [x] The cloud troubleshooting logs and metrics are accessible as expected. 
  * [x] Create an _Ingest Server_ deployment in `8.2` and then upgrade to `8.3.0` (BC) and verify that
    * [x] The APM Server starts up and can ingest data without throwing any errors, data show up in the APM UI.
    * [x] When enabling metrics collection in the Cloud UI, the Stack Monitoring UI shows data for the APM Server. 
    * [x] The cloud troubleshooting logs and metrics are accessible as expected. 
  * [x] Create an _Ingest Server_ deployment in `8.3.0` (BC) and verify that
    * [x] The APM Server starts up and can ingest data without throwing any errors, data show up in the APM UI.
    * [x] When enabling metrics collection in the Cloud UI, the Stack Monitoring UI shows data for the APM Server. 
    * [x] The cloud troubleshooting logs and metrics are accessible as expected. 
 
* [x] Testing the new k8s webhook before making it available as tech preview, by following the README. 

When picking up a test case from the github board, add yourself as _assignee_ on the PR before you start testing:

* [x] Testing new features and bug fixes as outlined in [8.3.0 user facing test plan](https://github.com/elastic/apm-server/issues?q=is%3Aclosed+label%3Atest-plan++label%3Av8.3.0+-label%3Abenchmarking+)
* [ ] Testing apmbench related changes according to [8.3.0 apmbench test plan](https://github.com/elastic/apm-server/issues?q=is%3Aclosed+label%3Atest-plan++label%3Av8.3.0+label%3Abenchmarking+)

Link any found regressions here.

**Comment by axw** [comment]
I've created an 8.3.0-BC4 deployment. The smoke test went as expected, except that the stack monitoring ES output metrics are all zero: https://github.com/elastic/apm-server/issues/8383

**Comment by simitt** [comment]
8.3 has been released - closing this
