### ISSUE TITLE
TBS processor fails processing events

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8255]
**APM Server version** (`apm-server version`): `8.2.0`

**Description of the problem including expected versus actual behavior**:
APM Server TBS issues were reported, where the APM Server logged following errors: 
```
Row: 36; Column: 5
tail sampler aborted%!(EXTRA zapcore.Field={error 26 0 invalid character 's' after top-level value})
```

The error is returned from the [sampling processor](https://github.com/elastic/apm-server/blob/main/x-pack/apm-server/sampling/processor.go). Additional information regarding the `event` or the (de-)serialization and reading/writing from/to storage should be logged to help troubleshoot the root cause of this issue.

**Comment by stuartnelson3** [comment]
closed by https://github.com/elastic/apm-server/pull/8418
