### ISSUE TITLE
OpenTelemetry metric labels lost between 8.1.2 and 8.2.2

### ISSUE THREAD

**Issue by matschaffer** [elastic/apm-server#8260]
**APM Server version** (`apm-server version`): 8.2.2, also main

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. Start up ES, kibana & a local apm-server 8.1.2
 2. Run https://github.com/matschaffer/elastic-otel-metrics/blob/main/src/server/index.ts with `OTEL_EXPORTER_OTLP_ENDPOINT="localhost:8200"`
 3. Note that documents include a `labels.rule: role_0` field
 4. stop 8.1.2, start 8.2.2 with same config
 5. Note that the same documents no longer contain `labels.rule`

**Provide logs (if relevant)**:

![Pasted_Image_2022_05_31_14_57](https://user-images.githubusercontent.com/690/171102958-bfd808a5-1207-45c0-9c0f-b7345702bcf2.png)

https://mat-otel-collection.kb.asia-northeast1.gcp.cloud.es.io:9243/app/r/s/flaky-obedient-energy

Discovered during work for https://github.com/elastic/kibana/issues/128755

Will re-test on main.

**Comment by matschaffer** [comment]
Same behavior on master. I'll continue my work on 8.1.2 since it seems to talk to newer ES versions without complaining.

![Screen Shot 2022-05-31 at 15 22 01](https://user-images.githubusercontent.com/690/171106150-e3a297cf-c346-4fc3-9b7b-fa5adb74c4c0.png)

**Comment by lahsivjar** [comment]
@matschaffer The version of otlp-exporter used in the project `elastic-otel-metrics` is [v0.27.0](https://github.com/matschaffer/elastic-otel-metrics/blob/56eaa554114fc132aa8e272391123d64d8ef219f/package.json#L8-L9). This version, as reported by the [opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js/tree/experimental/v0.27.0/experimental/packages/opentelemetry-exporter-metrics-otlp-grpc), was last tested with `otlp-collector` version `v0.25.0` whereas apm-server version `8.2.2` uses [v0.44.0](https://github.com/elastic/apm-server/blob/v8.2.2/go.mod#L44-L45).

The root-cause of the observed issue seems to stem from the removal of `labels` from the proto definition.
- `elastic-otel-metrics` uses [v0.27.0](https://github.com/open-telemetry/opentelemetry-js/tree/experimental/v0.27.0/experimental/packages/opentelemetry-exporter-metrics-otlp-grpc) which uses [the old proto with ONLY labels fields](https://github.com/open-telemetry/opentelemetry-proto/blob/59c488bfb8fb6d0458ad6425758b70259ff4a2bd/opentelemetry/proto/metrics/v1/metrics.proto#L293-L323)
- APM-server upgraded the version of collector in `8.2.x` from `v0.34.0`, in `8.1.x` to `v0.44.0` thereby removing the deprecated `Labels` field (ref [v0.34.0](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.34.0/model/internal/data/protogen/metrics/v1/metrics.pb.go#L1032-L1066) vs [v0.44.0](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.44.0/model/internal/data/protogen/metrics/v1/metrics.pb.go#L873-L901)). During the transition period, the collector maintained backward compatibility which was removed when the `labels` were dropped.

I think the clients need to update the versions on their end to resolve the issue. @axw @simitt WDYT?

**Comment by simitt** [comment]
Sounds aligned with the strategy to only support the latest/stable versions of otel.

**Comment by matschaffer** [comment]
Thanks @lahsivjar - the 0.28 version lacked oltp, but with https://github.com/open-telemetry/opentelemetry-js/pull/2929 merged I think I can try 0.29.
