### ISSUE TITLE
Add span.name to aggregation key for service destination metrics

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8274]
Add the `span.name` to the aggregation key for service destination metrics. 

* exclude `span.name` for RUM events due to high cardinality values
* add `span.name` for any other event that has `span.destination.service` or the newly introduced `service.target.{type, name}` fields set. 

The aggregation already has a default limit of 10_000 time series per minute. When the limit is reached, metrics docs per event are written to ES. We may want to change behaviour when the limit is reached, e.g. stop aggregating by `span.name` to avoid breaking existing charts in Kibana, such as the dependencies list.

**Comment by axw** [comment]
I think we should hold off on this, as in the first implementation of the backend operations page I think we're going to use span documents.

**Comment by simitt** [comment]
Closing this issue for now, and potentially reopen after a decision was made if any changes are required on the server side.

**Comment by axw** [comment]
Sorry, I interpreted some comments in another thread that we weren't going to use the metrics in 8.4.

**Comment by sqren** [comment]
No worries! Thanks for re-opening!

**Comment by axw** [comment]
We may want to change behaviour when the aggregation limit (10000 groups) is reached, e.g. stop aggregating by `span.name` to avoid breaking existing charts in Kibana, such as the dependencies list.

**Comment by chrisdistasio** [comment]
@simitt @axw given the original plan to include this in 8.4--can it be worked on earlier in the (8.4) cycle to unblock the originally planned work on the ui team?

cc: @sqren

**Comment by axw** [comment]
@chrisdistasio yes, I'll assign myself to this and make the change soon.

**Comment by chrisdistasio** [comment]
thanks for the super fast turnaround on this @axw!
