### ISSUE TITLE
Allow setting numbers as tags

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-server#828]
Having the ability to set custom number values which are indexed in Elasticsearch allows to create aggregated graphs based on transactions.

For example, you could track the number of search results for a search transaction, along with the search query to get a list of the top searches without results.

**Comment by simitt** [comment]
Do you mean something similar as `marks`, which can be nested objects with `number` values? 

This wouldn't be a big issue from a technical point of view (except for the one open issue that we also have with marks https://github.com/elastic/apm-server/issues/708).

**Comment by felixbarny** [comment]
Yes, similar to marks, but mark values should always be a timestamp in ms, right? Shouldn't we map it to a date then?

For this, we should pre-define a mapping so that we don't have the issue mentioned in #708. Double would be the most flexible datatype for this I guess.

**Comment by felixbarny** [comment]
Just flat key value pairs with double values

**Comment by felixbarny** [comment]
OpenTracing allows to set string, boolean and number tags. Converting the numbers to strings does not really break the contract, but it means the users can't create graphs based on the number tags. 

Example: the user could add a tag to a checkout cart span which represents the total value of the cart. If we don't support number tags, the user can't create a Kibana visualization with graphs the revenue.

**Comment by roncohen** [comment]
@felixbarny and I discussed offline and while OT prescribes both: 

* `Span.setTag(String key, Number value)`
* `Span.setTag(String key, String value)`

it doesn't prescribe how the values should be stored or how users should be able to query them. I understand this would be useful, but in order to avoid holding up OT support, let's consider this to be unrelated to OT.

**Comment by watson** [comment]
Side-note: If it's easy to do while we're changing this anyway, I would like to propose that we also support boolean values.

**Comment by simitt** [comment]
We are investigating options to implement this, but it hasn't been implemented yet.

**Comment by toughrogrammer** [comment]
Is there any roadmap about it? Or any other alternative solutions?
