### ISSUE TITLE
Server waits 5 seconds when shutting down even if the queue is empty

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#833]
Steps to reproduce:
1. Start APM Server with no traffic going to it
1. Hit ctrl+c
1. see `stopping apm-server... waiting maximum of 5 seconds for queues to drain` and wait 5 seconds

**Comment by graphaelli** [comment]
I'm only able to replicate this when the configured output is down, presumably because the onboarding document is still in the queue.  @roncohen are there any other scenarios you've encountered this?

**Comment by roncohen** [comment]
You are right of course. Sorry for the noise.
