### ISSUE TITLE
Override maxLength default value of `1024` for keywords in beats

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#839]
Currently the default value for `ignore_above` is set to `1024` in the beats framework. Hence, we use the same limit on the Intake API for string data that are indexed as `keywords` to avoid issues when querying for it.

As explained in the [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html) the document itself would be indexed, but not the keyword field that exceeds the `ignore_above` limit.

**Comment by alvarolobato** [comment]
We need to discuss if we want/need to make this differently. Are there any use cases specific to this?

**Comment by simitt** [comment]
Questions came up here:
https://github.com/elastic/apm-server/issues/801
https://github.com/elastic/apm-server/issues/777

It doesn't seem to be an immediate or urgent request, so I suggest to keep the issue open so we can collect use cases but put it somewhere into the Inbox.

**Comment by graphaelli** [comment]
Can we close this since https://github.com/elastic/beats/pull/7238 is in?

**Comment by graphaelli** [comment]
tested that `ignore_above` in fields.yml overrides the default of 1024 now
