### ISSUE TITLE
APM Server may run out of memory when processing lots of OTLP requests

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#8425]
**APM Server version** (`apm-server version`):

`8.0.0+`

**Description of the problem including expected versus actual behavior**:

If the incoming OTLP event rate is significantly higher than the outgoing Elasticsearch documents, the APM Sever may run out of memory with enough load. We should implement some sort of concurrency limit similar to what we did for the stream processor for the Intake V2 API https://github.com/elastic/apm-server/blob/104d0a85fa675b7bbae7be0ee047b3e8a6b52895/processor/stream/processor.go#L212-L223

**Steps to reproduce**:

1. Run APM Server that indexes events to a small Elasticsearch server (2GB of RAM for example).
2. Run `apmbench -run BenchmarkOTLPTraces -benchtime=2m -count=2 -agents=64`
3. Watch it run out of memory.

**Comment by kruskall** [comment]
We added a memory-limiting semaphore with https://github.com/elastic/apm-server/pull/10987

I think this can be closed, also see https://github.com/elastic/apm-server/issues/9242
