### ISSUE TITLE
Update "setup-repositories" section

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#844]
Currently [our documentations](https://www.elastic.co/guide/en/apm/server/6.2/setup-repositories.html) points to the wrong place for deb/rpm artifacts as reported here: https://discuss.elastic.co/t/latest-apm-server-package-6-2-3-on-the-beats-apt-repository/128157/2

**Comment by simitt** [comment]
Yes , the fixes I did in the documentation also need to be backported to the released `6.2` branch, as this is the `current` atm.

**Comment by simitt** [comment]
closed by #851
