### ISSUE TITLE
Update OTel Collector dependency >= 0.56.0

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-server#8576]
OpenTelemetry Swift introduced in version `1.3` [changes that require OTel Collector version](https://github.com/open-telemetry/opentelemetry-swift/releases/tag/1.1.3) >= `0.56.0`.

As a consequence the iOS APM agent cannot update to OpenTelemetry Swift versions > 1.2.0 as long as we do not update the corresponding OTel collector dependency in the APM server. This can become a blocker for new features and important updates we depend on in OpenTelemetry Swift.

We need to update the `go.opentelemetry.io/collector/*` dependencies to the latest version (or at least something >= `0.56.0`). 

Since nearly [every release on the OTel collector](https://github.com/open-telemetry/opentelemetry-collector/releases) repository has breaking changes it's not clear whether an update of the collector dependencies would break some behavior for *older* OTel agents / OTLP intake formats. Some investigation and testing is needed for this.

**Comment by AlexanderWert** [comment]
@bryce-b Looks like current version of `opentelemetry-swift` does not work with the newest versions of the collector either:
https://github.com/open-telemetry/opentelemetry-swift/issues/311

Could you please verify this / or test with collector `0.55.0`, so that we know which version of the collector dependency we would need to update the APM server to?

Thanks!

**Comment by simitt** [comment]
@elastic/apm-server let's wait for @bryce-b investigation which collector version is reliable before updating.

**Comment by bryce-b** [comment]
I spun up the demo otel-collector in the [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo) which runs v0.56.0 of the collector. I was able to successfully capture traces using the latest version of opentelemetry-swift (v1.1.4)

Screencap on a trace captured in zipkin.
<img width="2019" alt="Screen Shot 2022-07-28 at 3 19 20 PM" src="https://user-images.githubusercontent.com/75274611/181646898-359ed338-5f7d-48d9-910d-f61ff5fbc6c3.png">

**Comment by simitt** [comment]
Updated the description and title to reflect an update to `0.56.0`.
