### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#8644]
We should ensure the apm-server binary is reproducibly built, meaning that given the same commit then `apm-server` binaries built are byte-for-byte identical, regardless of the machine on which they are built and the time at which they are built.

The build process currently injects the git commit and build timestamp via `-ldflags -X foo=bar`, which breaks reproducibility. Rather than injecting the build date, we should use the commit date. If the binary is reproducible, the time at which it was built is not important. Ideally we would extract the commit hash and date from [runtime/debug.BuildInfo](https://pkg.go.dev/runtime/debug#BuildInfo); this requires Go 1.18+. Alternatively, we can inject the values at build time, like we do today.

Doing this has several benefits, including auditability, and speeding up builds by caching.

**Comment by simitt** [comment]
> Ideally we would extract the commit hash and date from [runtime/debug.BuildInfo](https://pkg.go.dev/runtime/debug#BuildInfo); this requires Go 1.18+.

https://github.com/elastic/apm-server/issues/8752 to track go 1.18 support

**Comment by axw** [comment]
#8732 just injects the vars as before. We can consider using `runtime/debug` in the future.
