### ISSUE TITLE
Java attacher discovery rules are unordered

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-server#8659]
Discovery rules are used within the APM agent integration to determine which processes should be automatically attached to.
The way they are handled is ordered, where only the first matched rule is used to either include or exclude the process from attachment. 
However, they are currently stored as a map, which is unordered.

https://github.com/elastic/apm-server/blob/a7c0603f9dcf1a8bb1a7a232b7c664dd9286ac3f/beater/config/java_attacher.go#L26

**Comment by felixbarny** [comment]
It's stored as an array of maps, so I don't think they're unordered

https://github.com/elastic/apm-server/blob/cf8f0a616f94aadb00595c81ccdc2a61aa8ebd2d/internal/beater/config/java_attacher_test.go#L27-L31

IIRC, this has been done so it maps best to yaml.

**Comment by eyalkoren** [comment]
@elastic/apm-server if someone can guarantee that these maps only have a size of 1 always, then this is not an issue indeed

**Comment by simitt** [comment]
@felixbarny clarified, that the maps will always be of size 1 due to how the UI is built. Closing this issue.

**Comment by felixbarny** [comment]
> if someone can guarantee that these maps only have a size of 1 always, then this is not an issue indeed

This makes sure the size is always 1:

https://github.com/elastic/apm-server/blob/a7c0603f9dcf1a8bb1a7a232b7c664dd9286ac3f/beater/config/java_attacher.go#L37-L39
