### ISSUE TITLE
Support otel/remote-sampler

### ISSUE THREAD

**Issue by tttoad** [elastic/apm-server#8665]
I would like ES to provide dynamic configuration of traces, Just like jaeger/sampler.
The configuration page is provided by kibana.
The implementation can be provided in the opentelemetry-go-contrib/sampler directory.

**Comment by axw** [comment]
@tttoad you can already define sampling rates via Kibana:
 - https://www.elastic.co/guide/en/apm/guide/current/configure-head-based-sampling.html#_dynamic_configuration
 - https://www.elastic.co/guide/en/kibana/8.3/agent-configuration.html

Is there something missing?

**Comment by tttoad** [comment]
I'm using otel, can this support be provided in "opentelemetry-go-contrib/sampler" ?
If you are not planning to do this, I can refer to "Go Agent" for his implementation.

**Comment by axw** [comment]
@tttoad ah, I think I understand now. You would like APM Server to support the Jaeger remote sampling HTTP protocol. Is that correct?

We support Jaeger's gRPC [GetSamplingStrategy method](https://github.com/elastic/apm-server/blob/0420137bea7f9e8ad10ce6b5bbb751b0e0134baa/beater/jaeger/grpc.go#L129-L188), but we don't currently have plans to support the HTTP protocol. We can leave this open as an enhancement request though.

> If you are not planning to do this, I can refer to "Go Agent" for his implementation.

If that works for you, then you might get it working more quickly.

**Comment by tttoad** [comment]
I mean to implement "opentelemetry-go-contrib/sampler/elastic", like "sampler/jaeger".
But you already support Jaeger's gRPC, that's enough for me...

**Comment by axw** [comment]
Great. I'll close this then.
