### ISSUE TITLE
Add APM Server Support for Ubuntu 22.04

### ISSUE THREAD

**Issue by chrisdistasio** [elastic/apm-server#8730]
Ubuntu 22.04 was released on April 21, 2022 and is supported by stack (8.3) and Elastic Agent (8.4)

Align with Elastic Agent platform support to ensure we have supported coverage for APM Integration.

[Related Agent issue](https://github.com/elastic/ingest-dev/issues/998)

Test and ongoing support for APM Server on Ubuntu 22.04.

**Comment by simitt** [comment]
Conduct manual smoke testing for the standalone and Fleet managed APM Server. At least the following should be tested:
* [ ] install APM Server
* [ ] Set up templates, ILM policies, ingest pipelines via APM Integration
* [ ] Send APM data to APM Server 
* [ ] Verify data are successfully ingested into ES

**Comment by axw** [comment]
> Set up templates, ILM policies, ingest pipelines via APM Integration

I'm considering this a prerequisite rather than something that should be tested, as it's not influenced by where or how APM Server is running.

**Comment by axw** [comment]
Tested with Ubuntu 22.04 x86_64 on GCP, using 8.4.0-BC1. I've tested both the Debian package (legacy), and Elastic Agent integration, using TBS with the latter. All good.

**Comment by axw** [comment]
Reopening so we can track adding to the support matrix.

**Comment by simitt** [comment]
@chrisdistasio you can add it to the support matrix for `8.4`. Please close this issue when done.
