### ISSUE TITLE
Aggregate service level metrics (tech preview)

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8756]
To improve the Service Inventory query time, the APM Server should aggregate related metrics. 

## Scope
This should be a Technical Preview behind a feature flag (opt-in).
It should be turned on for elastic-internal deployments (cc @cachedout). 

## Open questions:
* Store aggregated metrics in a new metrics datastream or add them to the existing internal datastream `metrics-apm.internal-<namespace>`?
* Validate if `event.outcome` should be added as dimension.

Related PR: https://github.com/elastic/apm-server/pull/8607

**Comment by cachedout** [comment]
> It should be turned on for elastic-internal deployments

Thanks, @simitt . Please contact us when this feature is present in a snapshot and we'll enable it on the test clusters.

**Comment by axw** [comment]
@cachedout the change should be in the latest snapshot. How is APM Server running in the test clusters? As an Elastic Agent integration, or legacy mode? There is currently no way to configure this feature through the integration, but if running standalone it can be configured by setting `apm-server.aggregation.service.enabled=true`
