### ISSUE TITLE
automatically update elastic-agent-libs dependency

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8774]
With the introduction of https://github.com/elastic/elastic-agent-libs, some of the libbeat dependencies have moved out into this new repository. This repository does not follow the elastic stack release cycle. 
We should have a job to automatically update this dependency on release branches to the latest release tag. Updating once a week and a possibility to trigger a manual update should be good enough.

**Comment by axw** [comment]
Is it not enough to update beats, seeing as libbeat imports elastic-agent-libs?

**Comment by simitt** [comment]
Great point, I was completely ignoring that.
