### ISSUE TITLE
Run benchmarks on scaling APM Sever on ESS beyond 8GB

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#8775]
Verify that the APM Server performance does not degrade when increasing the maximum allowed container size on ESS beyond the current limits of 8GB per instance. 

We should leverage the recently reworked apm benchmark tooling for conducting such tests efficiently. 
@mieciu has offered to provide a dedicated testing envionment on ESS for this and can provide more details via PM.

**Comment by axw** [comment]
We should also compare scaling up vs. scaling out. We have a default limit of 200 concurrent request decoders, which could be a problem if we were to start scaling out at a higher memory threshold.

**Comment by marclop** [comment]
We've concluded the scheduled work on this topic for the `8.5` milestone. We'll look at introducing some changes to the  model indexer in `8.6`, so we can maximize resource usage on bigger instances.
