### ISSUE TITLE
self-instrumentation triggers mapping exceptions

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#8831]
start apm-server with self-instrumentation enabled

```
./apm-server -E instrumentation.enabled=true -e -d '*'
```

wait a minute or less and notice:

```
{"log.level":"error","@timestamp":"2022-08-09T13:37:42.589-0400","log.logger":"modelindexer","log.origin":{"file.name":"modelindexer/indexer.go","file.line":412},"message":"failed to index event (strict_dynamic_mapping_exception): mapping set to strict, dynamic introduction of [parent] within [process] is not allowed","service.name":"apm-server","trace.id":"58bdee8653d6445c590ad24451d57302","transaction.id":"58bdee8653d6445c","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2022-08-09T13:37:42.589-0400","log.logger":"modelindexer","log.origin":{"file.name":"modelindexer/indexer.go","file.line":430},"message":"bulk request completed: 2 indexed, 5 failed (0 exceeded capacity)","service.name":"apm-server","trace.id":"58bdee8653d6445c590ad24451d57302","transaction.id":"58bdee8653d6445c","ecs.version":"1.6.0"}
```

successes and failures continue to be logged after that.

**Comment by axw** [comment]
Was this with 8.5.0-SNAPSHOT? Which commit of Kibana are you running? There was a change a couple of days ago to switch from `process.ppid` to `process.parent.pid` (https://github.com/elastic/apm-server/pull/8783). The latest 8.5.0 integration package in snapshot storage is up to date: https://github.com/elastic/package-storage/commit/4c2a9ccd072122c41405ba24efdc3f7644b50ecf

If Kibana is stale, then the bundled integration package would also be stale.

**Comment by graphaelli** [comment]
My kibana snapshot is older than that package so I suspect you're right and this is already fixed.  I'll close this after confirming with a newer kibana build.

**Comment by graphaelli** [comment]
Relaunched the whole stack and still seeing the same with:

```
Kibana (image built: 2022-08-09 11:40:11 UTC):
	Version: 8.5.0-SNAPSHOT
	Branch: main
	Build SHA: 6655eeff50554078e3f427828846399066cc29e3
	Build number: 55383

Elastic Agent (image built:2022-08-10 04:24:37 UTC):
	Version: 8.5.0-SNAPSHOT
	Branch: main
	Build SHA: dc5b1a2ec19c04e54f663be166e54f892d3c3385
```

How can the integration package version be determined?

**Comment by axw** [comment]
> How can the integration package version be determined?

Not directly. The 8.5.0-SNAPSHOT images are currently bundling the 8.4.0 integration package, so that would explain the issue you're seeing. This will be fixed by https://github.com/elastic/kibana/issues/137759#issuecomment-1204191846

**Comment by axw** [comment]
The integration package was updated, therefore this should no longer be an issue.
