### ISSUE TITLE
Downgrade elastic-agent-system-metrics from 0.4.3 to 0.4.2. 

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/apm-server#8857]
APM Server's automation [pulled in the latest version of libbeat ](https://github.com/elastic/apm-server/pull/8694)that itself [downgraded its dependency](https://github.com/elastic/beats/commit/fba8b8639d1f) on elastic-agent-system-metrics from 0.4.3 to 0.4.2. 

This means that while we depend on the latest version of libbeat our transitive dependency remained stuck on 0.4.3 as its still the highest valid version as per go's dependency version resolving rules. 
This 0.4.3 version sadly contains a concurrency bug while trying to write to a shared map instance: https://github.com/elastic/beats/issues/32467

Propose to fixate our dependency explictly rather then transitively while https://github.com/elastic/beats/issues/32467 is being addressed.

**Comment by axw** [comment]
We've since automatically upgraded to 0.4.4, which includes a fix for that bug.

**Comment by Mpdreamz** [comment]
Even better!
