### ISSUE TITLE
`apm_data_stream_migration` ingest pipeline does not account for removed field `observer.version_major`

### ISSUE THREAD

**Issue by viewable** [elastic/apm-server#8879]
**APM Server version** (`apm-server version`): >= 8.2.0

**Description of the problem including expected versus actual behavior**:

The `apm_data_stream_migration` ingest pipeline in [apm_data_stream_migration.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_data_stream_migration.yml) (https://github.com/elastic/apm-server/pull/5768) does not account for the later-removed `observer.version_major` field (https://github.com/elastic/apm-server/pull/7399), and trying to use this ingest pipeline as intended with legacy indices containing that field will fail:

```
"cause": {
          "type": "strict_dynamic_mapping_exception",
          "reason": "mapping set to strict, dynamic introduction of [version_major] within [observer] is not allowed"
        },
```

**Steps to reproduce**:

 1. Try to reindex any legacy APM index with documents containing the `observer.version_major` field using the `apm_data_stream_migration` ingest pipeline

**Comment by axw** [comment]
Thanks for reporting this @viewable! We'll take a look into it.
