### ISSUE TITLE
Documentation page does not go to the latest documentation when clicking on "current release documentaiton"

### ISSUE THREAD

**Issue by davidgeorgehope** [elastic/apm-server#8887]
In the yellow banner on this page (https://www.elastic.co/guide/en/apm/get-started/6.8/install-and-run.html) for the 6.8 documentation I clicked the link for "current release documentation"

![image](https://user-images.githubusercontent.com/30470909/185231659-7c186063-9451-4b7b-95e9-d125a60b5984.png)

but it did not take me to the lates 8.3 release, it took me to 7.15 as shown below

![image](https://user-images.githubusercontent.com/30470909/185231787-965e4fe7-a71e-42f1-956e-c8e846fd49ec.png)

**Comment by bmorelli25** [comment]
👋. The APM Overview and APM Server Reference were retired in 7.15. Starting in version 7.16 you have to use the new APM Guide. The yellow banner at the top of the page has a link. Unfortunately, there's no way for our current build system to have `current` point to a different book.

**Comment by bmorelli25** [comment]
Hmm. Actually, the 6.8 header is manually added to the build. I've opened https://github.com/elastic/apm-server/pull/8888 to try to fix this.

**Comment by bmorelli25** [comment]
Fixed. Changes should be live within the next hour. Thanks for reporting!
