### ISSUE TITLE
OTEL plugin error in sending data to APM server

### ISSUE THREAD

**Issue by SenthilkumarRasan** [elastic/apm-server#8975]
We have verified Open-telemetry protocol data to APM server endpoint with elastic 7.16 version. We have migrated to 8.2 version and running elastic search observability in kubernetes. APM agents are able to send the data over to APM server endpoint. We are able to get Jenkins data from otel plugin to APM server. Getting 400 bad request error. Is there any additional config required on APM server to get open-telemetry protocol data from Jenkins otel plugin? Thanks

**Comment by axw** [comment]
Please ask questions at https://discuss.elastic.co/c/observability/apm/58. If there is a bug, we'll come back and open an issue. Thanks!
