### ISSUE TITLE
txmetrics: remove `timeseries.instance` field

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#9018]
The `timeseries.instance` field is not used anywhere. Eventually we should move these metrics to using TSDB, which generates a timeseries ID from the dimensions.

**Comment by simitt** [comment]
Wasn't the original intention to use this e.g. for telemetry to get a better understanding of usage and potential issues with the metrics aggregation?

**Comment by axw** [comment]
@simitt I don't recall tbqh. If it was, we could also do that with TSDB using the [`_tsid`](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#tsid) field. We could alternatively compare transaction event count to transaction metric count for a rough approximation.
