### ISSUE TITLE
`agent_config` metrics are not being indexed

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#9048]
**APM Server version** (`apm-server version`): 8.5.0-SNAPSHOT (main)

**Description of the problem including expected versus actual behavior**:

`agent_config` metrics are not being indexed - they are failing to be indexed due to an authorization error. This is most likely related to the refactoring I recently did around setting up model processors; it looks like the agentcfg reporter is attempting to send metrics to the pre-processing chain, which requires authorization.

Also, we don't have an system tests that verify the metrics are indexed.

**Steps to reproduce**:

 1. Run the `TestAgentConfig` system test
 2. Observe that no "agent_config" metric is ever indexed

**Provide logs (if relevant)**:

`{"log.level":"error","@timestamp":"2022-09-06T04:40:45.565Z","log.logger":"agentcfg","log.origin":{"file.name":"agentcfg/reporter.go","file.line":106},"message":"error sending applied agent configs to kibana: no Authorizer in context","service.name":"apm-server","ecs.version":"1.6.0"}`

**Comment by simitt** [comment]
We weren't using the metrics anywhere. Are they even still relevant?

**Comment by axw** [comment]
@simitt the UI started using the metrics in 8.3: https://github.com/elastic/kibana/issues/123109
