### ISSUE TITLE
Add global labels to service metrics

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9060]
Similar to how global labels are part of the aggregation key for transaction metrics (https://github.com/elastic/apm-server/pull/8839), global labels should also be added to the newly introduced service metrics (https://github.com/elastic/apm-server/pull/8607/).

**Comment by simitt** [comment]
@kruskall please ping the UI team once this is merged and can be tested.

**Comment by kruskall** [comment]
@elastic/apm-ui PR merged, let me know if there are any issues with it :bow:

**Comment by sqren** [comment]
Thank you @kruskall !

**Comment by axw** [comment]
Verified with BC2. I used the Go agent to send a handful of transactions with differing global labels, and confirmed that they resulted in separate metrics being reported. I also confirmed that transaction-specific labels are _not_ emitted.
