### ISSUE TITLE
spec: patternProperties key lengths are unbounded

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#910]
I'm writing validation tests in the Go agent, and noticed that there is no limit on the length for keys where we use "patternProperties": Context.tags, Context.custom, Transaction.marks, and Mark.

Is this intentional? Could it be abused?

**Comment by alvarolobato** [comment]
Enforcing this makes JSON schema even more unreadable an also has a negative performance impact. We don't see a strong reason right now to implement this change.
