### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by csakaszamok** [elastic/apm-server#9129]
**APM Server version** (`apm-server version`):
docker.elastic.co/apm/apm-server:8.4.1

**Description of the problem including expected versus actual behavior**:
Expected: Apm server is up and running
Actual: There is error:
failed to deploy a stack: Creating elk-apm_elasticsearch_1 ... [1A[2K Creating elk-apm_elasticsearch_1 ... [32mdone[0m [1Bi/o timeout : exit status 1

**Steps to reproduce**:
Just download the docker-compose and run it under Windows10

**Comment by axw** [comment]
@csakaszamok please open a topic at https://discuss.elastic.co/c/observability/apm/58. If there is a bug, we can come back and reopen this. Please describe in detail what docker-compose configuration you're using, and provide the logs for services that aren't starting.
