### ISSUE TITLE
Unable to install in windows 8

### ISSUE THREAD

**Issue by priyochatterjee08** [elastic/apm-server#916]
![elasticapm](https://user-images.githubusercontent.com/10290106/39755015-d75b8d94-52e1-11e8-997d-4e00cf7c4e49.PNG)

**Comment by roncohen** [comment]
Hi @priyochatterjee08. Thanks for reaching you. If you go to "Services" you should see it. You can also start it from there.

**Comment by alvarolobato** [comment]
This should be working, please reopen with more information if the problem persists.
