### ISSUE TITLE
Unable to build in Ubuntu

### ISSUE THREAD

**Issue by priyochatterjee08** [elastic/apm-server#917]
![elasticapmubuntu](https://user-images.githubusercontent.com/10290106/39755145-93d71a88-5279-11e8-8dc0-8761184f8bd8.png)

**Comment by axw** [comment]
It appears that you're trying to build with Go 1.6. according to the project [https://github.com/elastic/apm-server/blob/master/README.md](README), Go 1.10 or greater is required. Please update and reopen this if you're still having issues.
