### ISSUE TITLE
Manual Test Plan 8.5 release

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#9175]
When picking up a test case, please add your name to this overview beforehand and tick the checkbox when finished. Testing can be started when the first build candidate (BC) is available.

## Smoke Testing ESS setup 
* [x] enable metrics collection in the Cloud UI and check APM Server data show up in the Stack Monitoring UI in Kibana
       (known bug: https://github.com/elastic/apm-server/issues/8383)
* [x] The cloud troubleshooting logs and metrics are accessible as expected. 

Thanks to https://github.com/elastic/apm-server/issues/8303 further smoke tests are run automatically on ESS now. 

## Go agent
* [x] https://github.com/elastic/apm-agent-go/issues/1233 @axw 
* [x] https://github.com/elastic/apm-agent-go/issues/1267 @axw
* [x] https://github.com/elastic/apm-agent-go/issues/1315 @axw

## Lambda extension

* [x] https://github.com/elastic/apm-aws-lambda/issues/256 @kruskall 
* [x] https://github.com/elastic/apm-aws-lambda/issues/225 @lahsivjar 
* [x] https://github.com/elastic/apm-aws-lambda/issues/245 @axw
* [x] https://github.com/elastic/apm-aws-lambda/issues/188

## Test cases from the github board 
[apm-server 8.5 test-plan](https://github.com/elastic/apm-server/issues?q=label%3Atest-plan+label%3Av8.5.0)

Add yourself as _assignee_ on the PR before you start testing.

## Regressions
Link any regressions to this issue.

**Comment by simitt** [comment]
@axw IMO it would make sense to also include the changes on the go-agent and lambda extension which are aligned with the `8.5` release into the test plan. WDYT?

**Comment by axw** [comment]
@simitt yes, sounds good. I'll add sections for them.
