### ISSUE TITLE
Provide description for elastic/apm-server on hub.docker.com

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-server#918]
[elastic/apm-server](https://hub.docker.com/r/elastic/apm-server/) doesn't have any description.

**Comment by graphaelli** [comment]
@jarpy Mind chiming in here?  I'm not sure how to do this or if we even still maintain images on docker hub (instead using https://www.docker.elastic.co/)

**Comment by jarpy** [comment]
We do publish those, so we should definitely add a description. We don't need much though. For the other images we have just enough information to guide people to the documentation and to the Elastic registry.

https://hub.docker.com/r/elastic/elasticsearch/

**Comment by graphaelli** [comment]
Got it, I was thinking of the deprecation notice on https://hub.docker.com/_/elasticsearch/ but that's not relevant here.

It appears the short and full descriptions are edited through the UI, I'll put an internal request in to get those updated as I don't appear to have access.

**Comment by graphaelli** [comment]
done
