### ISSUE TITLE
Remove technical blocker on macOS for java agent auto attachment

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9185]
Remove all remaining technical blockers from supporting the java agent attacher on macOS

* [x] https://github.com/elastic/go-sysinfo/pull/137
* [x] https://github.com/elastic/go-sysinfo/pull/138

This is tracking the work that is currently blocking https://github.com/elastic/apm-server/issues/8718

**Comment by kruskall** [comment]
There is a new technical blocker that prevents bumping the library in APM server. The user id is used for user discovery rules (https://github.com/elastic/apm-server/blob/main/internal/beater/java_attacher/discovery_rules.go) and running the attacher as a different user based on the current id (https://github.com/elastic/apm-server/blob/main/internal/beater/java_attacher/os_utils.go#L34-L55).

A PR has been opened to address the issue: https://github.com/elastic/go-sysinfo/pull/139

**Comment by kruskall** [comment]
PR has been merged, no more technical blockers :tada: 

I think this can be closed. I'll open a PR to bump the library and close the main issue.
