### ISSUE TITLE
Inconsistency in documentation of source map uploading

### ISSUE THREAD

**Issue by andriijas** [elastic/apm-server#9249]
**APM Server version** (`apm-server version`):

8.4

**Description of the problem including expected versus actual behavior**:

The documentation contains inconsistency in the examples

**Steps to reproduce**:

https://www.elastic.co/guide/en/apm/guide/8.4/source-map-how-to.html

1. https://www.elastic.co/guide/en/apm/guide/8.4/source-map-how-to.html#source-map-rum-upload states that bundle_path should be absolute url

In the upload via curl example 
(https://www.elastic.co/guide/en/apm/guide/8.4/source-map-how-to.html#source-map-curl)
bundle_filepath refers to a .map file but with relative path

in the upload via custom app 
https://www.elastic.co/guide/en/apm/guide/8.4/source-map-how-to.html#source-map-rum-upload 
bundle_path refers to the actual js file, not the map file. However in this example it uses absolute url.

We have recently upgraded from kibana 7 to kibana 8 and with that sourcemaps broke in apm for us. We have turned every stone. The sourcemaps are uploaded through the new api, they are listed in the discover tab under fleet artifacts. service name and version matches. Yet the exception trace doesnt show the source map anymore. 

Hitting the "View X occurrences in discover" 
reveals:

  "sourcemap": {
                "error": "unable to find sourcemap.url for service.name=foo service.version=1.0.0 bundle.path=https://test.acme.inc/main.3bc71f31a25542b7a451.js"
              },

we have uploaded sourcemaps with both bundle_path as https://test.acme.inc/main.3bc71f31a25542b7a451.js and https://test.acme.inc/main.3bc71f31a25542b7a451.js.map but none of them works to get the actual mapping working in the exception tab.

Please advise, thanks🙏🙏

**Comment by axw** [comment]
I think this can be closed now - please reopen if there are any issues remaining:

- there is a bug related to relative paths, will be fixed in 8.5.0: https://github.com/elastic/apm-server/issues/8650
- there was a bug in Kibana related to source maps that was fixed in 8.3.0: https://github.com/elastic/kibana/issues/129940
- docs have been fixed/clarified to be more realistic: https://github.com/elastic/apm-server/pull/9359

**Comment by andriijas** [comment]
@axw all of the fixes in 8.5 helped us, thanks for all support
