### ISSUE TITLE
Improve data stream upgrade guide

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#9278]
## Description

It would be good to add a word of caution for customers wanting to migrate to data streams to know that they need to install the APM Integration in order for the APM Server to work. Otherwise the expected assets will be missing and data ingestion will stop. Also it may be good to add a link to the actual ESS migration guide so users don't end up lost in our docs.

![image](https://user-images.githubusercontent.com/7286993/193981580-d3dbeb9a-7985-4256-8fd1-1b09f2893e29.png)

Docs: https://www.elastic.co/guide/en/apm/guide/7.17/upgrade-to-data-streams.html

**Comment by simitt** [comment]
@marclop, on ESS users do not have to manually install the integration - as soon as they migrate, the integration is set up for them. We could add a sentence about the importance on installing the integration, but also point out that this manual step is only required on prem. 

+1 on linking to the migration guide.

**Comment by simitt** [comment]
@bmorelli25 this is not documenting new functionality, but would be nice to get into `7.17` docs eventually.

**Comment by simitt** [comment]
That makes a lot of sense! Thanks for the clarification.

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/apm-server/pull/9917.
