### ISSUE TITLE
Rally cloud benchmarking is not using all the worker nodes

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-server#9284]
As per the current code, rally is only using the coordinator node for generating load. Due to this, testing for higher load volumes might get throttled while generating load. The following issues should be fixed to allow this to happen:

1. Google cloud VPC created for launching rally instances doesn't allow internal communication. Due to this, the `esrally` deamons are not able to communicate with each other causing the rally cluster to not be used.
2. The command line to invoke `rally` currently doesn't pass `load-driver-hosts` flag.

**Comment by axw** [comment]
Removing from test-plan, this is not user facing.
