### ISSUE TITLE
APM stacktrace doesn't work when more than 20 sourcemaps have been uploaded to /api/apm/sourcemaps

### ISSUE THREAD

**Issue by adkfas** [elastic/apm-server#9372]
**APM Server version** (`apm-server version`):

Elastic APM (Elastic-Agent Integration) Version: ` 8.2.1`

Elasticsearch, Kibana, Fleet and APM running in containers:

![WindowsTerminal_37q3RTzAF2](https://user-images.githubusercontent.com/104196741/196031386-b4e68c8f-622d-4e7e-95cf-b906a05fd31a.png)

**Description of the problem including expected versus actual behavior**:

I have used this provided guide [here](https://discuss.elastic.co/t/uploading-sourcemaps-from-aix-webserver/303526/20) by Elastic staff, for testing this issue.

**APM error stacktrace doesn't work when more than 20 sourcemaps have been uploaded to `/api/apm/sourcemaps`, and the needed sourcemap can't be viewed in the list out of the 20 sourcemaps received from the endpoint**

When doing a get request on Kibana endpoint, `/api/apm/sourcemaps`, it only returns max 20 sourcemaps.

In my below screenshots I have tried to capture this issue.

In **Step 1**, you can see the query on **/api/apm/sourcemaps**, only returns max 20 sourcemaps.
In **Step 2**, you can see I uploaded my sourcemap for code "sourcemap_test_8_2" and the upload works good.
In **Step 3**, you can see that my uploaded sourcemap for code "sourcemap_test_8_2" can't be seen in the list from `/api/apm/sourcemaps`.
In **Step 4**, you can see that the error stacktrace **do not work**. Because the needed sourcemap for code "sourcemap_test_8_2" can't be seen in the list from `/api/apm/sourcemaps`.
![Pb4f74eVgi](https://user-images.githubusercontent.com/104196741/196031807-8dca0079-b1e5-43d9-a4db-04ffbae24029.png)

-----

In the next screenshot below, you can see I will remove a couple of sourcemaps, so that my sourcemap for code "sourcemap_test_8_2" can be seen in the list from `/api/apm/sourcemaps`, and after that the stacktrace WORKS.

In **Step 2**, you can see I delete a couple of sourcemaps.
In **Step 3**, you can see after deleting sourcemaps in step 2, my sourcemap  for code "sourcemap_test_8_2" can be seen in the list from `/api/apm/sourcemaps`
In **Step 4**, you can now see that the stacktracing **WORKS**. Because the sourcemap for code "sourcemap_test_8_2" can be seen in the list from `/api/apm/sourcemaps`
![RkqlVT8tk0](https://user-images.githubusercontent.com/104196741/196031809-1855a064-80c6-4c39-b696-72f69639f647.png)

**Comment by axw** [comment]
@adkfas thanks for digging in. This was fixed in 8.3.0: https://github.com/elastic/kibana/issues/129940. Please upgrade and let us know if you still have issues afterwards.

**Comment by adkfas** [comment]
Ah I see, I will upgrade to latest and see, thank  you @axw!!

**Comment by otteryoudoing** [comment]
Hello team, re-opening this issue as I am seeing the same behavior in my 8.6.2 test deployment - 57b95a
Customer is seeing the same in their 8.6.2 monitoring deployment - f827c4

Method of testing.. 
```
curl -X POST "https://monitortest.kb.us-central1.gcp.cloud.es.io:9243/api/apm/sourcemaps" \
-H 'Content-Type: multipart/form-data' \
-H 'kbn-xsrf: true' \
-H 'Authorization: ApiKey RDRzeTJvY0JuLTNnaVBPeDqeZPd0w6WVA5anJvZUZUbi1KckZNSFFmWVR3UQ==' \
-F 'service_name="1"' \       > incremented here from 1-25
-F 'service_version="1.0.0"' \
-F 'bundle_filepath="/test/e2e/general-usecase/bundle.js.map"' \
-F 'sourcemap="{\"version\":3,\"file\":\"static/js/main.chunk.js\",\"sources\":[\"fleet-source-map-client/src/index.css\",\"fleet-source-map-client/src/App.js\",\"webpack:///./src/index.css?bb0a\",\"fleet-source-map-client/src/index.js\",\"fleet-source-map-client/src/reportWebVitals.js\"],\"sourcesContent\":[\"content\"],\"mappings\":\"mapping\",\"sourceRoot\":\"\"}"'

curl -X GET "https://monitortest.kb.us-central1.gcp.cloud.es.io:9243/api/apm/sourcemaps" \
-H 'Content-Type: application/json' \
-H 'kbn-xsrf: true' \
-H 'Authorization: ApiKey RDRzeTJvY0JuLweTNnaVBPeDZPd0w6WVA5anJvZUZUbi1KckZNSFFmWVR3UQ=='
```
(only returns 20 results)
API keys obfuscated

**Comment by otteryoudoing** [comment]
Re-opening linked issue instead, as it fits better being in Kibana repo.
