### ISSUE TITLE
Deprecate `apm-server apikey`

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#9444]
In 7.6 we [introduced the `apm-server apikey` command](https://github.com/elastic/apm-server/issues/2987), enabling users to manage API Keys for APM Agent authentication. This has always been [labelled in the documentation as technical preview](https://www.elastic.co/guide/en/apm/guide/8.4/command-line-options.html#apikey-command) (previously known as "experimental").

In 8.0 we introduced support for [managing API Keys for APM agents in the APM UI](https://github.com/elastic/kibana/pull/120373). The [APM Guide directs users to the APM app](https://www.elastic.co/guide/en/apm/guide/8.4/api-key.html#create-an-api-key). There is also a [guide for creating API Keys through the Elasticsearch REST API](https://www.elastic.co/guide/en/apm/guide/8.4/api-key.html#create-api-key-user), for users who might need to automate API Key management.

The future of API Key management is through Kibana and Elasticsearch. We should deprecate and remove `apm-server apikey`. Technically we could immediately remove the command since it never made it out of technical preview. However, the command has been available for almost 3 years, so I think that would be too rash. We shouldn't wait too long either, since the UI has been available since 8.0. Let's deprecate it and give 1-2 minor releases notice before removing.

I propose we add a deprecation notice to the documentation and command description, and log a warning when the command is invoked.

**Comment by lahsivjar** [comment]
Tested on branch `8.6`:

```bash
$ ./apm-server -h | grep deprecated 
apikey      Manage API Keys for communication between APM agents and server (deprecated)
```

```bash
$ ./apm-server apikey -h | grep deprecated
Manage API Keys for communication between APM agents and server (deprecated).
NOTE: "apm-server apikey" is deprecated, and will be removed in a future release.
```

```bash
$ ./apm-server apikey create | grep deprecated
...

NOTE: "apm-server apikey" is deprecated, and will be removed in a future release.
See https://www.elastic.co/guide/en/apm/guide/current/api-key.html for managing API Keys.
```
