### ISSUE TITLE
Test Elastic Cloud Proxy timeout changes

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9477]
Once available on internal testing infrastructure, ensure that the recent changes in the timeout are not causing issues for APM Server deployments. 

## How to test?
- spin up an APM Server (not important whether integration or standalone is tested, as they have the same default read timeouts).
- send load to APM Server from APM agents and observe unchanged behavior, even when APM Server is overloaded. This can be achieved by downscaling ES to the smallest available size, leading to back pressure on APM Server.

**Comment by kruskall** [comment]
I've run the benchmarks in ESS on the CFT region and in QA, both using the 8.5.0 stack version.

The terraform scripts used can be found at https://github.com/elastic/apm-server/tree/main/testing/benchmark.

Results showed no error responses and similar performance. The timeout does not seem to cause any issue.

The test has been repeated twice to make sure the results are consistent. The APM server size is 1G with a zone count of 1.

**Comment by simitt** [comment]
Thanks @kruskall for conducting the testing and reporting back the results. This issue can be closed then.
