### ISSUE TITLE
Clarify use of references to beats

### ISSUE THREAD

**Issue by markwalkom** [elastic/apm-server#948]
Here - https://www.elastic.co/guide/en/apm/server/current/configuration-template.html - we use `apm-server-%{[beat.version]}` as a reference to the index name. It's a little unclear that the `beats` reference is due to the APM server being built on the beats framework and that this is a standard variable from that.

It'd be great if we could add something to that particular page, or to the overview, that makes this clearer.

**Comment by graphaelli** [comment]
Just looked briefly into making something like `apm.version` work - needs a change to https://github.com/elastic/beats/blob/c5e4c23515abe4450ba73ecf7391200a9a81ced6/libbeat/template/template.go#L53, either upstream or in our vendored beats code.

Agreed that this is very confusing.

**Comment by jalvz** [comment]
There is indeed a mention to it in the overview:

> APM Server is an application built in Go using the beats framework and as such it shares many of the same configuration options as beats

Can that be phrased better?

That specific page is actually a doc copied verbatim from beats, we generally try to avoid overwrite them manually, but we can do it if needed.


I wouldn't change `beat.version` to `apm.version` because then we would have to keep an eye to do that for every case and might not always be trivial. Don't see a reason to hide we are beat neither.

**Comment by markwalkom** [comment]
I did find that but I had to click around, hence why I think we could add a note in that page.

**Comment by roncohen** [comment]
In the mean time, could we solve this simply by adding something like the following in the two places where we use `beat.version` in the docs?:

"`beat.version` refers to a field that APM Server adds to every document. The field contains the current version of APM Server."

**Comment by roncohen** [comment]
sorry, as @jalvz already pointed out, we can't add to that page without also changing it in the beats docs. We could add another conditional in the beats docs to only show the comment for APM Server, but I don't think that's recommendable.

**Comment by jalvz** [comment]
Blocked until we figure out a way of having more flexibility with beats docs

**Comment by bmorelli25** [comment]
Done!

I fixed the index name for APM Server in https://github.com/elastic/beats/pull/9595/, and this was easy to fit into the new conditional: https://github.com/elastic/beats/pull/9595/files#diff-f1a89e6c3a1ce6f296f47ad83b989ff7R234
