### ISSUE TITLE
Disable indexing for custom application metrics

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#9485]
In https://github.com/elastic/apm-server/pull/9316, we have added `index: false` to well-defined metrics, such as system metrics (e.g. CPU usage), and language/runtime-specific metrics (e.g. JVM garbage collector metrics). The rationale behind this is that it is unusual to search on metric values -- they are typically only aggregated -- so we can disable indexing to save some storage space.

We should also do this for custom, application-defined metrics. These are dynamically mapped, so we would need to update the dynamic templates used for mapping them: https://github.com/elastic/apm-server/blob/d87c885d3cedb15c45adb7ca3c007157aa60a9a6/apmpackage/apm/data_stream/app_metrics/manifest.yml#L20-L32

**Comment by lahsivjar** [comment]
Tested with the latest 8.6.0 BC: `8.6.0-8cf9e954`. Validated that indexing is `false` for custom app metrics.
