### ISSUE TITLE
Open telemetry resource attribute `deployment.environment` is ignored

### ISSUE THREAD

**Issue by DrLuke** [elastic/apm-server#9488]
When setting  [`deployment.environment`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/deployment_environment.md) resource attribute in open telemetry, the service's environment remains `Not defined` in APM. Seeing how this is even specifically mentioned in the [docs](https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html#instrument-apps-otel) I'm guessing this is an oversight.

**Comment by DrLuke** [comment]
> If in code, can you please verify that you're setting it as a resource attribute, and not a span attribute?

I had otel-col dump the raw traces and it indeed was a configuration error and the attribute was missing from the traces, thanks for the help and sorry for wasting your time 🙈

**Comment by axw** [comment]
No worries! Thanks for confirming and getting back with the answer.
