### ISSUE TITLE
APM Server experiencing memory issues when TBS is enabled

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9523]
**APM Server version** (`apm-server version`): `8.4.3` (might also impact older versions)

**Description of the problem including expected versus actual behavior**:
APM Server can run OOM when Tail based sampling is enabled. 

**Steps to reproduce**:
It is not yet clear how to reproduce. 
One idea is that such memory issues might be caused by transaction events with a large number of events. 

**Provide logs (if relevant)**:
N/A

**Comment by marclop** [comment]
I've started looking into this issue and reproducing locally. It looks fairly easy to reproduce and make the APM Server run out of memory.

We're currently relying on the default options for Badger's memory settings https://github.com/elastic/apm-server/blob/51760870d040f2d6cfb81a2f83accbb6eafeb1b1/x-pack/apm-server/sampling/eventstorage/badger.go#L25-L29

BadgerDB has an internal compactor which runs when certain thresholds are reached, those can be tuned following the https://dgraph.io/docs/badger/get-started/#memory-usage guidance.

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/7286993/201919388-8988f138-9c0d-4258-96a3-9c25cd0946a4.png">

For a 1GB APM Server we should use much lower settings than the default and ideally dynamically size these depending on the APM Server size.

```go
	// Tunable memory options:
	//  - NumMemtables - default 5 in-mem tables (MaxTableSize default)
	//  - NumLevelZeroTables - default 5 - number of max tables before compaction starts.
	//  - NumLevelZeroTablesStall - number of max tables before writing stalls (waiting for compaction).
	//  - IndexCacheSize - default all in mem, Each table has its own bloom filter and each bloom filter is approximately of 5 MB.
	//  - MaxTableSize - Default 64MB
```

All tunable options are available in Badger's option file https://github.com/dgraph-io/badger/blob/release/v2.2007/options.go.

**Comment by marclop** [comment]
There is also another bug that was introduced when we added the soft limit to TBS storage

<img width="1683" alt="image" src="https://user-images.githubusercontent.com/7286993/202151986-597c0f26-95f6-4dd4-8f7f-4866d73131b4.png">

I will fix that separately, but when the storage limit is reached, the shared transactions will grow until the transaction limit.

https://github.com/elastic/apm-server/blob/3967ed1110e95ac599c7c92b75b14c161715478c/x-pack/apm-server/sampling/eventstorage/storage.go#L182-L206

https://github.com/elastic/apm-server/blob/3967ed1110e95ac599c7c92b75b14c161715478c/x-pack/apm-server/sampling/eventstorage/storage.go#L127-L142
