### ISSUE TITLE
Discrepancy between agent.name and language.name in context

### ISSUE THREAD

**Issue by formgeist** [elastic/apm-server#96]
Steps to reproduce: Expand any document in the Discover table to review the context info.

![screenshot 2017-08-24 10 57 34](https://user-images.githubusercontent.com/4104278/29659010-2b4452a0-88bd-11e7-8fb0-968147032885.png)

**Comment by watson** [comment]
Unfortunately I think this is a general issue that expands beyond just these two properties.

The Node agent [doesn't set](https://github.com/elastic/apm-agent-nodejs/blob/be70e834a40d4b8d1bcad1da39bfe69ad7c17cfe/lib/request.js#L201-L214) the `context.app.language` object at all, which leads me to fear that this entire object is leaking through from another request to the intake API.

I've just done a little testing and by leaving out for instance `context.app.pid` in a request, I get a pid from another object bleeding through.

I'm curious to see if this extends outside the scope of just `context.app` and I'll do some more testing

**Comment by watson** [comment]
I can confirm that this happens for the entire `context.request` object as well: If I send up an error to the APM Server that doesn't contain a `context.request` object, it gets the `context.request` from an older error.

So this sounds like a general issue with all properties on the object.

My working theory is that an object is reused somewhere in the bath between a request to the intake API and Elasticsearch. So properties that are not explicitly overwritten will be reused from a previous request.
