### ISSUE TITLE
Disable enable service metrics options

### ISSUE THREAD

**Issue by yngrdyn** [elastic/apm-server#9608]
Disable the option to enabling service metrics v8.6.
UI team will disable in https://github.com/elastic/kibana/issues/145745 but to be on the safe side regarding upgrading to stable schema versions when serviceMetrics is in GA we should also disabled this option in the server

**Comment by axw** [comment]
Service metrics are already disabled by default. Is it necessary to remove the option from the server altogether? If the UI side is removed, I don't think it'll be visible to users?

**Comment by sqren** [comment]
I don't think it's terribly important since they are disabled by default but OTOH I don't see are reason for letting users enable a feature that won't work.

**Comment by axw** [comment]
The configuration is used by the server for testing purposes. Since it's undocumented and off by default, it shouldn't affect anyone. We're past FF, so I'd rather avoid making code changes unless they're absolutely necessary. Closing, let me know if you have concerns with this.
