### ISSUE TITLE
Re-enable synthetic source

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#9610]
In https://github.com/elastic/apm-server/pull/9544 we disabled synthetic source due to a bug in Elasticsearch: https://github.com/elastic/elasticsearch/issues/91731. Once that is fixed, we should re-enable it.

**Comment by felixbarny** [comment]
Synthetic _source is not GA for non-TSDB indices. Are we still fine with enabling it by default?

**Comment by axw** [comment]
Aside from the one Elasticsearch bug that was found and fixed, it's been working well. It is possible to disable through a component template if push comes to shove. I don't have a very strong opinion, but tend towards leaving it enabled by default.
