### ISSUE TITLE
service metrics: add aggregate_metric_double

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9655]
Add a `aggregate_metric_double` field for the duration on transaction metrics and service metrics (for example `transaction.duration.summary`) to more efficiently aggregate the average duration, without having to iterate over the histogram buckets.

**Comment by carsonip** [comment]
Service metrics is already using DurationSummary and DurationHistogram in https://github.com/elastic/apm-server/blob/04ca7b537fb8dd83da47a484833541913f8168c4/x-pack/apm-server/aggregation/servicemetrics/aggregator.go#L442 while transaction metrics is only using DurationHistogram but not DurationSummary in https://github.com/elastic/apm-server/blob/04ca7b537fb8dd83da47a484833541913f8168c4/x-pack/apm-server/aggregation/txmetrics/aggregator.go#L555

Is there anything extra needed for service metrics in this case? Or is this task only about adding DurationSummary to transaction metrics?

**Comment by simitt** [comment]
IMO adding `transaction.duration.summary` to transaction metrics would fulfill this ask, and also bring service and transaction metrics in line again. @felixbarny @dgieselaar were you expecting something additionally?

**Comment by dgieselaar** [comment]
@simitt no, don't think so.
