### ISSUE TITLE
mobile: translate otel log events to error events 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9659]
When receiving otel log events that represent errors, translate them to APM error events. If they are coming from mobile crashes, the app crash information needs to be mapped to the APM error exception event. 

For translating a log event to an error event, use the existence of `exception.*` attributes to signal that the event is an error: https://opentelemetry.io/docs/reference/specification/logs/semantic_conventions/exceptions/

For the additional information that the error represents an app crash, one additional label will be set. Hopefully this label can be added to the semantiv conventions long term, but for now we start with a label `event.type: mobile-crash`. The information that the error event was created by a mobile app crash needs to be available via an Elasticsearch `error.exception.*` field.

Build on existing code for converting [resource logs](https://github.com/elastic/apm-server/blob/main/internal/processor/otel/logs.go) and [translating exceptions and parsing stacktraces](https://github.com/elastic/apm-server/blob/main/internal/processor/otel/exceptions.go) whereever possible. 

--- 
updated to reflect below comments (28/11/2022)

**Comment by felixbarny** [comment]
We were discussing to add a dedicated attribute to signal that the log represents an app crash. The mobile agent team would be responsible to propose a name and to contribute it to the OTel semantic conventions.

**Comment by axw** [comment]
Aside from the attribute mentioned above, we could consider logs with `exception.*` attributes to be errors: https://opentelemetry.io/docs/reference/specification/logs/semantic_conventions/exceptions/

If they have those, create an error. Otherwise, create an application log. That's essentially what we do for span events today.

**Comment by AlexanderWert** [comment]
We discussed in the last mobile sync that, actually, there might be more than just crashes in the future. 
For example, there are ANR (Application Not Responding) events, that are very similar to errors as well, but need to be marked as a special kind of events. So, an additional field that would describe the type of error / event (e.g. crash vs. error vs. ANR) would be beneficial.

**Comment by AlexanderWert** [comment]
@simitt @kruskall 

Update: We discussed this topic in the mobile sync last week. One update on this is that we will use the `event.name` = `mobile-crash` field (instead of the `event.type` as specified above).

**Comment by AlexanderWert** [comment]
Also, we need to define which field we will use on the ES / ECS side to denote a mobile crash. Any preferences / ideas? Maybe the ECS field `error.type`? Right now we are using `error.exception.type` for the exception class name.

@felixbarny WDYI?

**Comment by kruskall** [comment]
@AlexanderWert Thanks for the updates! I've opened a PR with the implementation.

> Update: We discussed this topic in the mobile sync last week. One update on this is that we will use the event.name = crash field (instead of the event.type as specified above) and event.domain= device. This is then already compliant with OTel semantic conventions.

Do we need any special handling for `event.domain=device` ? Right now it's only checking `event.name=crash`.

> Also, we need to define which field we will use on the ES / ECS side to denote a mobile crash. Any preferences / ideas? Maybe the ECS field error.type? Right now we are using error.exception.type for the exception class name.

I like `error.type`. I'm using that in the PR but I'm open to other proposals! :+1:

**Comment by AlexanderWert** [comment]
> Do we need any special handling for event.domain=device ? Right now it's only checking event.name=crash.

I think it makes sense to use this field to set the ECS event [categorization fields](https://www.elastic.co/guide/en/ecs/current/ecs-event.html). So, for this case it would make sense to set the following ECS fields:

* `event.kind` = `event`
* `event.category` = `device` (though we need to extend ECS to allow this value formally, I'll take care of that)
* `event.type` = `error`

**Comment by kruskall** [comment]
> Are we setting these fields for any of the OTel logs / events already?

I don't think we are afaik. I've added them to the PR.

Note: the processor and decoder have been recently moved to a separate repository so I moved the PR. Sorry for the trouble :bow:

**Comment by axw** [comment]
Reopening as we still need to update apm-server to use the latest apm-data.

**Comment by simitt** [comment]
@kruskall I believe the mapping for the `error_logs` datastream is still missing. @AlexanderWert was running into testing issues, and I can confirm that the fields are not part of the datastream.

**Comment by AlexanderWert** [comment]
@simitt @kruskall Opened a PR to add the mappings: https://github.com/elastic/apm-server/pull/10128

**Comment by kruskall** [comment]
PR merged, let's try to close this again
