### ISSUE TITLE
Add additional aggregation intervals for metrics

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#9703]
## Problem Statement

Today, if a large volume of apm data is ingested, the APM UI might take some time to be able to load data. The APM Server pre-aggregates some metrics and therefore decreases the amount of documents that need to be taken into account by the APM UI queries. The current interval of `1m` is not efficient enough though for achieving the desired UI performance. 

## Solution
APM Server will additionally roll up service, transaction and span metrics into larger intervals. It should aggregate multiple time ranges (`1m`, `10m` and `60m`) concurrently, and flush them to Elasticsearch periodically. Because this is expected to result in some storage increase, the metrics will be written to dedicated data streams, enabling interval-specific ILM policies. This enables users to adapt how long they want to keep high resolution data. 
When shutting down, the APM Server will flush the metrics so that buffered data are not lost. 

## Changes

- [x] Add additional `10m` and `60m` to transaction metrics (https://github.com/elastic/apm-server/pull/9846).
- [x] Add additional `10m` and `60m` to service destination metrics (https://github.com/elastic/apm-server/pull/9926).
- [ ] Add additional `10m` and `60m` to service metrics (#9960).

**Comment by marclop** [comment]
## How to test the changes in the linked PRs



Run the following sequence


```console
$ tilt up
# Wait for APM Server to be healthy.
$ cd systemtest && go run cmd/fleetctl/main.go set-policy-config apm-1 apm-server.aggregation.service.enabled=true
$ Run the ./test.sh script from this link https://gist.github.com/marclop/2b8d1e7278d84e0e787f2b2e35578f62.
# Restart the APM Server
$ go run cmd/fleetctl/main.go set-policy-config apm-1 apm-server.aggregation.service.enabled=false
```

Issue the following query in Kibana dev tools and ensure that there are 27 metrics documents:

```
GET /metrics-apm*/_search
{
  "_source": [false]
}
```

- 9 for service metrics (3 services * 3 metricset.interval (1m, 10m, 60m))
- 9 for service destination metrics (1 dropped span per service * 3 metricset.interval (1m, 10m, 60m))
- 9 for transaction metrics (3 transactions * 3 metricset.interval (1m, 10m, 60m))

Ensure that 3 APM Services are displayed:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/7286993/210351499-3c65ffa9-36ef-4dec-9df6-4d41804f97dc.png">


And that the service map also works

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/7286993/210351554-91f2543c-f142-4936-b5c2-6b1847e8016d.png">

**Comment by kyungeunni** [comment]
I've done initial testing on the cloud env with 8.7 and it seems to create an index and documents for 1m intervals only.

I've created a deployment and generated sample events using the test script from above [comment](https://github.com/elastic/apm-server/issues/9703#issuecomment-1369678814). I could see 3 services on the list and in the service map, but indices and documents for `10m` and `60m` weren't available. 

![image](https://user-images.githubusercontent.com/16660866/221515378-4c0eca62-dfde-4a0f-ad20-ba126ccc1810.png)

I'll continue testing on my local machine too.

**Comment by marclop** [comment]
@kyungeunni just to double check, you were able to verify this after using `?expand_wildcards=all`?

**Comment by kyungeunni** [comment]
Hi @marclop, 
Yes, sorry I thought I've updated the comment above.

I can confirm that I could see all three datastreams and documents were created for each metric. I didn't catch the 10m and 60m are hidden by default.

**Comment by marclop** [comment]
Should we mark this issue as `test-plan-ok`?
