### ISSUE TITLE
Add APM Server Support for RHEL 9

### ISSUE THREAD

**Issue by chrisdistasio** [elastic/apm-server#9717]
Consistent with Elastic Agent team support for major Linux distributions, we should add support for Red Hat Enterprise Linux 9.

We currently provide support for 7 and 8 versions.

**Comment by simitt** [comment]
- [ ] do a quick manual check on an RHEL-9
- [ ] add `RHEL-9` to the [list of supported OSs](https://github.com/elastic/apm-server/blob/main/testing/smoke/supported-os/main.tf#L47) for running the automated smoke tests
- [ ] update the official support matrix to include RHEL-9

**Comment by chrisdistasio** [comment]
updated [support matrix](https://docs.google.com/spreadsheets/d/10B1c0kFe0XrUu9lUwzUEr4XMeK_4ppao2KNzJp_Wp4M/edit#gid=497386949)
