### ISSUE TITLE
Deprecate APM Server support for macOS X 10.15

### ISSUE THREAD

**Issue by chrisdistasio** [elastic/apm-server#9719]
macOS X 15 is EoL on November 30, 2022 and can be deprecated from our support matrix

**Comment by simitt** [comment]
Add deprecation note to https://www.elastic.co/support/matrix#matrix_os.

**Comment by bmorelli25** [comment]
I wonder if this should be a company-wide initiative instead of just APM Server. The support matrix still shows OS X 10.15 as supported for all Elastic products.

**Comment by simitt** [comment]
@chrisdistasio could you coordinate around this and let us know how to move forward?

**Comment by chrisdistasio** [comment]
I'm aware (at this point) of Elastic Agent plans to deprecate with 8.7.  I'm unsure of broader support.

**Comment by simitt** [comment]
@bmorelli25 can you help with adding a deprecation note on the download page. 
@chrisdistasio please add it as deprecated to the support matrix. 
@elastic/apm-server if anyone could pick this up to issue a deprecation note on startup of the apm-server if macOS X 10.15 is recognized (similar to what we do for [32-bit systems](https://github.com/elastic/apm-server/blob/main/internal/beatcmd/beat.go#L262-L267)).

**Comment by chrisdistasio** [comment]
updated [support matrix](https://docs.google.com/spreadsheets/d/10B1c0kFe0XrUu9lUwzUEr4XMeK_4ppao2KNzJp_Wp4M/edit#gid=497386949)
