### ISSUE TITLE
7.17 docs suggest that data streams have a delete phase

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#9741]
https://www.elastic.co/guide/en/apm/guide/7.17/ilm-how-to.html indicates that data streams created by 7.17 have a delete phase. This is not true - we added the delete phase in 8.0: https://github.com/elastic/apm-server/pull/6480

We have no intention to change the ILM policy in 7.17, so we should update the docs.

**Comment by bmorelli25** [comment]
Closed in https://github.com/elastic/apm-server/pull/9916.
