### ISSUE TITLE
Make number of context source lines configurable for sourcemaps

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#978]
Right now the number of context lines included when sources are present is 5 before + 5 after.

We can:

+ Keep it as is (hardcoded) until a users mentions that they need support to tune it.
+ Make it configurable in the apm-server (along with other sourcemap config options).
+ Make it configurable in the agent (and send the config to the apm-server as url param). This is so to keep consistency with other agents, as generally the amount of source code to store is an agent option in other languages.
+ Other?

**Comment by alvarolobato** [comment]
@roncohen what is your opinion here?

**Comment by jalvz** [comment]
@roncohen ping

**Comment by roncohen** [comment]
sorry for the delay here. I'm fine with hardcoding it for now. If we get requests to make it configurable we can iterate on it.

**Comment by jalvz** [comment]
Thanks, closing this for now then
