### ISSUE TITLE
Improve error reporting when queue is full (503)

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-server#990]
When the queue is full the APM Server is just reporting a 503 error without any information on the underlaying error. 
What we have seen is that many times the cause is that elastic search is out of space, there could be also other reasons.

We should expose the real cause of the problem in some way so the user easily know what to do.

**Comment by alvarolobato** [comment]
We don't see any clear path to improve this right now.

**Comment by vikassharma12345** [comment]
APM Server goes down for While. APM agent queue/buffers increased.please suggest,how to free that Queue From all APM Agent. I have 15 different APM Agent to only one APM Server.
Using elastic-apm-agent-1.8.0.jar, elasticapm.properties files to tomcat bin and added following to setenv.bat:CATALINA_OPTS="$CATALINA_OPTS -javaagent:/home/tomcat/elastic-apm-agent-1.8.0.jar -Delastic.apm.service_name=P_24_CA -Delastic.apm.server_url=http://IP -Delastic.apm.environment=PR -Delastic.apm.capture_body=all"
