### ISSUE TITLE
Measure apm-server performance + libbeat with different configuration parameters

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-server#992]
(created out of https://github.com/elastic/apm-server/issues/773#issuecomment-394741852)

**Comment by alvarolobato** [comment]
@simitt can we consider this issue covered by what you did in https://github.com/elastic/apm-server/issues/1414 ? Probably not exactly the same scope but makes this one not needed?

**Comment by alvarolobato** [comment]
Thanks. I'll close this now and we can address specific numbers if we decide to write a fine tunning doc in the future.
