### ISSUE TITLE
Ability to run APM integration with Elastic Agent in standalone mode

### ISSUE THREAD

**Issue by vlaborie** [elastic/apm-server#9972]
I run Elastic Agent in standalone mode on Kubernetes by following this documentation: https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html

I need to use standalone mode because i used Infra As Code and CI pipelines for deploying and configuring my monitoring infrastructure.

I want to add APM integration but it's only supported on Fleet managed Elastic Agent (https://www.elastic.co/guide/en/apm/guide/current/upgrade-to-apm-integration.html#apm-integration-upgrade-limitations).

Can you add support for APM integration in standalone mode ? Why APM integration need Fleet server while others integrations didn't ?

**Comment by simitt** [comment]
Hi @vlaborie , thanks for reaching out. At the moment several features are implemented in a way to require Fleet (for example source map fetching and central agent configuration). We are currently working on making some of these features Fleet independent, but I cannot make any promises or give an ETA regarding APM ingegration standalone mode.

**Comment by kruskall** [comment]
I believe this can be closed now that sourcemap fetching and central agent config works without fleet. cc @simitt
